### ISSUE TITLE
nrf52832 does not respond to control-C - sometimes

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#1003]
While testing the SPI and I2C interfaces to the STMPE610 Touch screen copntroller, I found that once I start my program running, I cannot use control-C to break out.  This occurs with pot the I2C and SPI versions of the driver.

Control-C does work under the REPL -- have not tried other sensors yet.

Revetring to 3.x -- control C works properly running the same code.

No exeption handling in the program.
```
import board
import digitalio
from adafruit_stmpe610 import Adafruit_STMPE610_I2C
i2c=busio.I2C(board.SCL,board.SDA)
st=Adafruit_STMPE610_I2C(i2c)
while True:
    if not st.buffer_empty:
        print(st.read_data())
```

**Comment by arturo182** [comment]
Hmm, I wonder if my UART with nRFx rewrite can fix that.

**Comment by tannewt** [comment]
@hathach Are you looking at this?

**Comment by hathach** [comment]
@tannewt  ah no, I am resolving #1021 usb issue. Will look at this afterwards.

**Comment by jerryneedell** [comment]
this appears to have been fixed. Ok to close?

**Comment by jerryneedell** [comment]
Sorry I tested this on the pca10056 dk  board. Not on feather53832.

**Comment by jerryneedell** [comment]
verified that this is still not working for feather 52832 -- sorry for the confusion.

**Comment by arturo182** [comment]
Yes, since this is 52832, this must be in the UART driver not USB ;)

**Comment by jerryneedell** [comment]
Just a reminder that this issue is still present on the feather_nrf52832. 
Control-c does not terminate an executing script.
The only way to stop a script is a hard reset.

**Comment by tannewt** [comment]
@dhalbert Did you fix this?

**Comment by jerryneedell** [comment]
I have been try to find the istbut have not been successful. If you have suggestions about where to look I’ll be happy to keep working on it.

**Comment by dhalbert** [comment]
@tannewt I just fixed pin claiming for UART, but not UART reset. I think that's still to do.

**Comment by jerryneedell** [comment]
since we have dropped nrf52832  -- should we close this?

**Comment by dhalbert** [comment]
Since no one has complained about this in 52840, let's close.
