### ISSUE TITLE
Switch busio.I2C write to DMA.

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#101]

**Comment by tannewt** [comment]
I2C is slow enough that this isn't useful.

**Comment by ladyada** [comment]
is there an issue for SPI DMA? (i didnt see) *that* would be useful, especially for TFTs

**Comment by tannewt** [comment]
SPI is already DMAed. (QSPI isn't currently though.)

**Comment by ladyada** [comment]
oooh do we wait for DMA to complete before returning from a transmit?

**Comment by tannewt** [comment]
Yup, we still block. The DMA makes the transfer immune to interrupts and things.

**Comment by ladyada** [comment]
ok i think in framebuf maybe that's where i'd optimize it so it does not block. all good!

**Comment by tannewt** [comment]
Yup agreed. We should revamp display support and include this.

**Comment by deshipu** [comment]
The problem with non-blocking SPI transfers is that we handle CS toggling in software, so we have to wait for the transfer to finish anyways, because toggling CS before it finishes would break things. Hardware CS could be one possible solution to that.

**Comment by ladyada** [comment]
oh true... hmm, we could do that as part of the SPI locking process - like, CS is toggled by the DMA interrupt/callback, but you cant use it till then. a little like arduino transactions. just thinking outloud
