### ISSUE TITLE
ReadTheDocs structure issue.

### ISSUE THREAD

**Issue by ghost** [adafruit/circuitpython#1025]
This is a minor readability issue... it would be more clear in the Core Module section of the api ( http://circuitpython.readthedocs.io/en/latest/shared-bindings/index.html# ) if the API list(Modules) came before the support matrix(Support Matrix).

**Comment by tannewt** [comment]
Good idea! Want to try changing it? Its here: https://github.com/adafruit/circuitpython/blob/master/shared-bindings/index.rst

GitHub guide is here: https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github

**Comment by three-bits** [comment]
Yes, I'll figure out how to fix this and do a pull request. I should be a good way to learn CircuitPython workflow.

I didn't see how to assign this to my self in git hub.

**Comment by sommersoft** [comment]
Fixed by #1166. Thanks @dfarning!
