### ISSUE TITLE
nrf: implement busio.UART

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#1039]

**Comment by hathach** [comment]
While working on uart, @arturo182 is it ok now if I remove the macro that use the jlink cdc instead of native cdc. That option is there for you only :)

**Comment by arturo182** [comment]
Which cdc do you mean?

**Comment by hathach** [comment]
the jlink cdc that uses the hwuart on pca10056 CFG_HWUART_FOR_SERIAL
https://github.com/adafruit/circuitpython/blob/master/ports/nrf/supervisor/serial.c#L35

**Comment by arturo182** [comment]
Yes, it's fine to remove that :)

**Comment by hathach** [comment]
anyone knows this function got called, or it is called by system `board_uart`
https://github.com/adafruit/circuitpython/blob/master/ports/nrf/board_busses.c#L108

**Comment by hathach** [comment]
@dhalbert the default uart for pca10056 should be P0.8 and P0.6 instead of P1.1 & P1.2. It is connected to jlink cdc allow for quick testing. Furthermore if jlink cdc is not connected, those pins are in tri-state, which is safe to use with other device. Please let me know if I missed something.
https://github.com/adafruit/circuitpython/blob/master/ports/nrf/boards/pca10056/mpconfigboard.h#L49

**Comment by hathach** [comment]
Ah, I see, seem like you want to keep the pin compatible with Arduino layout :D . Sorry, didn't realize that until I check the pcb

**Comment by dhalbert** [comment]
@hathach right, exactly.

**Comment by hathach** [comment]
@dhalbert  @tannewt  should the `self->buffer` is freed in common_hal_busio_uart_deinit() , or we can just leave it to gc

https://github.com/adafruit/circuitpython/blob/master/ports/atmel-samd/common-hal/busio/UART.c#L217

**Comment by dhalbert** [comment]
Leave it to gc. It is allocated by `gc_alloc()` as a regular garbage-collectable object.

**Comment by hathach** [comment]
ah thanks, this new to me, I will just skip the free for nrf52 as well.

**Comment by hathach** [comment]
probably the same hw issue that I encountering. The first 2 irq uart request will fail miserably without real reason. UART is not too easy after all ~.~  
https://devzone.nordicsemi.com/f/nordic-q-a/33677/nrf52840-pin-uart-rx-bug

**Comment by dhalbert** [comment]
@hathach that devzone post is very confusing. I wonder if that's the PDK board.

**Comment by dhalbert** [comment]
i could try it with a GPS

**Comment by hathach** [comment]
You don't need extra hw to test since only the write() work now. The bug prevent me to do subsequent receiving since it failed at the begining.

here is the code
https://github.com/hathach/circuitpython/blob/nrf52_uart_io/ports/nrf/common-hal/busio/UART.c#L75
board.UART() will call the first nrfx_uart_rx() which will trigger error 4 (frame error) ---> nrfx will cancel transfer internally.

Just run u.read() : this will printf the previous error and call nrfx_uart_rx() again. 
Then call u.read() again to get the previous error of the 1st read which is 0x08 break error.
afterward no more error, call more will result in NRFX_BUSY code.

To test with u.write() you can hook up FTDI cable, it should work.

```
Adafruit CircuitPython 4.0.0-alpha-1079-g9c2530687-dirty on 2018-09-21; PCA10050
>>> import board                                                                
>>> u = board.UART()                                                            
>>> u.read()                                                                    
error = 0x00000004                                                              
rx count = 0x00000000                                                           
b''                                                                             
>>> u.read()                                                                    
error = 0x00000008                                                              
rx count = 0x00000000                                                           
b''                                                                             
>>> 
>>> u.read()                                                                    
rx count = 0x00000000                                                           
b''                                                                             
>>> u.read()                                                                    
rx count = 0x00000000                                                           
Traceback (most recent call last):                                              
  File "<stdin>", line 1, in <module>                                           
AssertionError: error = 0x0BAD000B   
```

**Comment by dhalbert** [comment]
Are you using UART or UARTE?

**Comment by dhalbert** [comment]
I asked for more info in that DevZone case.

**Comment by hathach** [comment]
UART since the rest of repo use it. UARTE is just having DMA to move data into buffer, not really needed for cpy I guess. Also the DMA demands data must be on the SRAM, flash address (i.e global const [] ) won't work. I am not sure if cpy use any of those.

**Comment by dhalbert** [comment]
What exactly is the error you are getting? Is this relevant? https://devzone.nordicsemi.com/f/nordic-q-a/37521/nrf52840-usb_cdc_acm-uart/145013#145013

I saw one DevZone case that recommended using UARTE over UART in nrf52832, but now I can't find it again.

**Comment by hathach** [comment]
error 4 (frame ) then error 8 (break). oh way, I think I found my own error lol, let's me test a bit more.

**Comment by hathach** [comment]
facepalm, I just assign the txd 2 time :( . That is high price to pay here ~.~ . Working late is not good at all lol
https://github.com/hathach/circuitpython/blob/nrf52_uart_io/ports/nrf/common-hal/busio/UART.c#L108

**Comment by dhalbert** [comment]
no problem, but time to sleep!

**Comment by hathach** [comment]
Do you prefer UARTE to UART, I could upgrade it to UARTE. Though, you must make sure all data is in SRAM not flash, and we must malloc buffer if needed. I think it is not really gain much benefit, since the uart is slow, cpu time for moving data is not much at all.

**Comment by dhalbert** [comment]
No, I don't prefer, just thought that UARTE might not have the problem, and now it's moot.

**Comment by hathach** [comment]
uart io should be done, I will hook an GPS wing to test tomorrow. Phew, too much time for the easy uart. Hopefully there is no more bugs :D

**Comment by hathach** [comment]
No problems, I will make the switch. the flow is similar to what I am doing anyway. IRQ vs DMA only has diff that cpu must move the data manually. But I think I will test what I have first before switching. I will also update the serial.c as well. currently serial.c use polling method, so there should be no impact at all.

**Comment by tannewt** [comment]
DMA can be a bit faster even when we poll because it runs even when the cpu
is handling an interrupt.

**Comment by hathach** [comment]
@tannewt yeah, I am moving it to uarte now.

**Comment by tannewt** [comment]
Ok great!

**Comment by dhalbert** [comment]
Still to implement: using both instances on nRF52840. Add `uart_init()` to disable on soft restart. @hathach I will take these up later.

**Comment by tannewt** [comment]
This has been done right?

**Comment by ladyada** [comment]
its been solid so far, @jerryneedell has done the most testing

**Comment by jerryneedell** [comment]
It’s been working great on the particle boards

**Comment by dhalbert** [comment]
It only provides one UARTE, and there are two available. Not sure the `uart_init()` has been fixed either. See https://github.com/adafruit/circuitpython/issues/1039#issuecomment-427496583 above.

**Comment by dhalbert** [comment]
Nope, no `uart_init()` yet.

**Comment by jerryneedell** [comment]
oops - sorry about the premature close...

**Comment by tannewt** [comment]
@dhalbert Can we close this now after #1541 ?

**Comment by dhalbert** [comment]
Yes, I thought it was going to get closed automatically.

**Comment by tannewt** [comment]
It's not super smart about how when it knows to close: https://help.github.com/articles/closing-issues-using-keywords/
