### ISSUE TITLE
nrf: implement microcontroller.Processor.temperature

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#1041]
There is a TEMP peripheral to measure the on-chip temperature. Looks very easy to use: a register returns the temp in degrees C.

**Comment by arturo182** [comment]
This is already done https://github.com/adafruit/circuitpython/blob/master/ports/nrf/common-hal/microcontroller/Processor.c#L36

**Comment by dhalbert** [comment]
Ah, great! I only read the first line of that routine :)
