### ISSUE TITLE
nrf: implement rotaryio.IncrementalEncoder

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#1045]
There is a QDEC (quadrature decoder) peripheral that does the work.

**Comment by dhalbert** [comment]
Discussed this: better to use a timer so we can have more than one instance.

**Comment by ladyada** [comment]
@Tasm-Devil you can help @nickzoic beta test :)

**Comment by nickzoic** [comment]
That's be great!  I've got the hardware on the bench, I'll have a PR in
the next few days ...

**Comment by CedarGroveStudios** [comment]
Is there a way to preset the rotary encoder count value after instantiation? Would greatly simplify tracking the encoder value when a single encoder was used to provide multiple selection parameters.

**Comment by dhalbert** [comment]
`.position` is not read-only: you can assign it a value.

**Comment by CedarGroveStudios** [comment]
Excellent! Thank you!
