### ISSUE TITLE
nrf: implement supervisor.Runtime.serial_connected

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#1047]
RIght now `nrf/common-hal/supervisor/Runtime.c` `serial_connected()` always returns `true`.

**Comment by arturo182** [comment]
Not when using USB: https://github.com/adafruit/circuitpython/blob/master/ports/nrf/supervisor/serial.c#L94 And for HW UART I'm not sure it's possible to detect it.

**Comment by dhalbert** [comment]
OK great, I only saw the first definition in that file.
