### ISSUE TITLE
nrf: SPI flash and QSPI flash support

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#1049]
As used on existing SAMD Express boards.

I don't see an explicit issue for this, but maybe I missed it.

**Comment by hathach** [comment]
note to myself: The flash chip is GD25Q16CTIGR right

**Comment by hathach** [comment]
Will try to remember it :D. I went through the time when Nordic sdk upgrade requires massive amount of work for migration. So I often to write the code in its generic form. The new nrfx seems to do a great job :D

**Comment by hathach** [comment]
QSPI on pca10056

![image](https://user-images.githubusercontent.com/249515/45032358-d113c580-b07b-11e8-8136-04c64b81f620.png)

**Comment by hathach** [comment]
doing a bit of testbench, is the speed Ok 
**clock 32 Mhz**
![screenshot from 2018-09-08 16-56-42](https://user-images.githubusercontent.com/249515/45252897-50f5a480-b388-11e8-964b-66bbf6187ceb.png)

**clock 8 Mhz**
![screenshot from 2018-09-08 16-51-45](https://user-images.githubusercontent.com/249515/45252900-56eb8580-b388-11e8-9004-d158691e511a.png)

**Comment by ladyada** [comment]
cool!

**Comment by hathach** [comment]
The read speed is similar to cpx test, but the write speed is not that great. I will do a bit more tweaks to see if it could improve more. 
![screenshot from 2018-09-08 23-49-34](https://user-images.githubusercontent.com/249515/45256541-f1b48600-b3c1-11e8-81de-e0acc7ddb581.png)

**Comment by dhalbert** [comment]
The write code -might- need work. It seems slow on SAMD51 (writing a large file takes a long time), and maybe there's a little bug somewhere.

**Comment by tannewt** [comment]
Write speed is erase limited since we don't do any fancy block allocations. I would love to do balancing that erases after a write but that only helps for a single block.

**Comment by tannewt** [comment]
I added this with 97bc95183d5114ce69c9387ebd2e2aa13feb65a7

**Comment by ladyada** [comment]
w00p
