### ISSUE TITLE
import performance slower in 3.0

### ISSUE THREAD

**Issue by daguitarguy** [adafruit/circuitpython#1051]
On the trinket m0, have a file "mylib.py" (attached sample) with 14 functions and 2 class definitions.

In REPL, call:
>>>import time
>>>var1= time.monotonic(); import mylib; print(time.monotonic()-var1)
 
This takes about 14.7 seconds on circuitpython 3.0, and 0.1 seconds on 2.3.1

[mylib.txt](https://github.com/adafruit/circuitpython/files/2208224/mylib.txt)

**Comment by dhalbert** [comment]
@tannewt I think this is a problem with unnecessary recursion in the long-lived code. I'll have a PR shortly.

**Comment by tannewt** [comment]
#1052 fixes this
