### ISSUE TITLE
Metro M4 Express: Crash trying to use both AnalogOut pins

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#1059]
The following, when entered at the repl, consistently crashes CircuitPython on the line which attempts to create the second AnalogOut instance:
```python
from board import A0, A1
from analogio import AnalogOut

fine = AnalogOut(A0)
print(fine)
coarse = AnalogOut(A1)
print(coarse)
```

The crash is "hard enough" that the CIRCUITPY drive cannot be accessed either until I use the reset button or re-plug the module.

```python
Adafruit CircuitPython 3.0.0-2-g08def6b51 on 2018-07-25; Adafruit Metro M4 Express with samd51j19
>>> 
>>> 
>>> from board import A0, A1
>>> from analogio import AnalogOut
>>> 
>>> fine = AnalogOut(A0)
>>> print(fine)
<AnalogOut>
>>> coarse = AnalogOut(A1)
[hangs here]
```
It doesn't matter which AnalogOut is created first, it's always the second creation that causes the crash.

This affects my self-built branch from today's tip of 3.x, as well as the 3.0.0 release from adafruit.

**Comment by jepler** [comment]
After re-plugging the module this works again.  Some state must have survived the reset button(!) to cause the problems I reported.  Given this, I don't know whether it's worth leaving this issue open.

**Comment by tannewt** [comment]
Thanks for following up!
