### ISSUE TITLE
arm-none-eabi-ld: region `FLASH' overflowed by 1436 bytes

### ISSUE THREAD

**Issue by rmd6502** [adafruit/circuitpython#107]
Using arm-none-eabi-gcc 4.9.3.  Using the 4.8.3 packaged with Arduino resulted in an overflow of 1452 bytes.
Attaching log from make V=1
[buildlog.txt](https://github.com/adafruit/circuitpython/files/798355/buildlog.txt)

**Comment by tannewt** [comment]
Please use GCC 6.x and try again.

Here is what I'm using:
`arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 6.2.1 20161205 (release) [ARM/embedded-6-branch revision 243739]`

**Comment by tannewt** [comment]
Please reopen if the latest GCC doesn't fix this and the Travis build is green. (Code size is currently broken but I'm working on it.)
