### ISSUE TITLE
Freezing module of unreleased git project fails.

### ISSUE THREAD

**Issue by aaronaverill** [adafruit/circuitpython#1081]
I followed the directions to freeze one of my modules that I tracked in git using the instructions here:

https://learn.adafruit.com/building-circuitpython/adding-frozen-modules

Build fails:

FREEZE ../../frozen/CircuitPython_NeoSprite
fatal: No names found, cannot describe anything.
fatal: No names found, cannot describe anything.
Traceback (most recent call last):
  File "../../tools/preprocess_frozen_modules.py", line 14, in version_string
    tag = subprocess.check_output('git describe --tags --exact-match', shell=True, cwd=path)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'git describe --tags --exact-match' returned non-zero exit status 128

The command failing is:

git describe --tags

Which returns an error if the project is in git but doesn't have a tag. Once I added a release in github, it worked fine.

Note that if you're adding code that isn't in git, the git describe --tags will use the parent circuitpython directory and all is well.

So probably, the instructions should be updated to add a step to create a release, or better perhaps this bit of code should have a default tag and handle the case where the subprocess call returns a non zero code.

**Comment by dhalbert** [comment]
Added a warning in https://learn.adafruit.com/building-circuitpython/adding-frozen-modules.
