### ISSUE TITLE
Change "RuntimeError: maximum recursion depth exceeded" 

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#1086]
The message `RuntimeError: maximum recursion depth exceeded` is kind of confusing, because you can get it in any situation where the stack gets too deep, not just because of actual recursion.

I think `maximum stack depth exceeded` would be clearer.

**Comment by tannewt** [comment]
We could create a stock translation good for googling and one for beginners. I should have the PR out tomorrow or monday.

**Comment by dhalbert** [comment]
Closing as won't fix for now; this hasn't been a really big support issue.
