### ISSUE TITLE
nativeio switch_to_output() and switch_to_input() require keywords for all arguments

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#109]
These nativeio routines require keywords for all args. The args are defined with MP_ARG_KW_ONLY:
```
switch_to_output(value=False, drive_mode=DriveMode.PUSH_PULL)
switch_to_input(pull=None)
```

1. Did you mean to require keywords for all these args ? For instance, I always have to say `switch_to_input(pull=...)` to set a pullup or pulldown, which seemed a little excessive for a one-arg method.
2. If you do want to require keywords, then the doc should look like:
```
switch_to_output(*, value=False, drive_mode=DriveMode.PUSH_PULL)
switch_to_input(*, pull=None)
```
I think there may be other methods as well where doc does not show `*,` to show required keywords.

**Comment by tannewt** [comment]
Good points @dhalbert ! I'll go over it today and follow up with a change shortly.
