### ISSUE TITLE
PyPi install when Adafruit Blinka only required for example

### ISSUE THREAD

**Issue by kattni** [adafruit/circuitpython#1091]
We need to document that Adafruit Blinka will likely be needed to use with the example, because it is not a requirement for the library, as the UART object is passed in. 

Related to #979 

Documentation needed for the following libraries:

- [ ] GPS
- [ ] Pixie
- [ ] FancyLED?
- [ ] Waveform

**Comment by dhalbert** [comment]
@kattni is this still relevant? (Just making a pass through some issues.)

**Comment by kattni** [comment]
@dhalbert I don't think so. I think we ended up adding Blinka for everything anyway. If not, we'll sort it on the library end.
