### ISSUE TITLE
Read the Docs seriously out of date or not building correctly

### ISSUE THREAD

**Issue by kattni** [adafruit/circuitpython#1108]
In adding RTD links to all the guides, I'm finding that some docs are seriously out of date or are not building correctly. Some haven't built in a long period of time, others are more recent but new builds are not triggering. This went unnoticed because when they last built they passed, so the badge has shown passing the entire time.

The ones that have not built in several months do not have webhooks - RTD is instead setup as a service. Only the maintainers on a particular project have access to setup the webhook - adabot and the person who imported it into RTD in the first place. The more recent ones have failing webhooks. All of this needs to be resolved.

- [ ] IRRemote - no webhook
- [ ] MAX31855 - no webhook
- [ ] Pixie - webhook failing to deliver payload
- [ ] TMP007 - webhook failing to deliver payload
- [ ] Thermal Printer - building correctly, but build page url structure is different, may be fine
- [ ] CCS811 - no webhook

**Comment by sommersoft** [comment]
@kattni this _appears_ to be good now? All of the listed repos have RTD builds within the last month. Granted, I didn't check any RTDs for libraries not listed here...

**Comment by kattni** [comment]
Yeah I think this is probably fine. If anything comes up again, we'll deal with it then.
