### ISSUE TITLE
String internationalization for German.

### ISSUE THREAD

**Issue by turbinenreiter** [adafruit/circuitpython#1112]
I'm gonna get started on German translations.

**Comment by turbinenreiter** [comment]
https://github.com/adafruit/circuitpython/pull/1114

**Comment by dglaude** [comment]
@turbinenreiter , I believe the first step is to create your de.po file and push it here: https://github.com/adafruit/circuitpython/tree/master/locale

This is because the first step for someone wanting to help is to check if the file exist, not to dig in every linked issue on #1098 ...

**Comment by Tasm-Devil** [comment]
There is still a lot work to be done. I've got the problem, that I feel uncomfortable to translate native python error messages because it will be harder to search for those errors in the Internet after translations.

**Comment by Tasm-Devil** [comment]
houston we have a problem.
The german translations aren't displayed properly in the REPL. The encoding is wrong. 
`ZurÃ¼ckverfolgung (jÃ¼ngste Aufforderung zuletzt)` should be `Zurückverfolgung (jüngste Aufforderung zuletzt)`
