### ISSUE TITLE
Can't import _thread

### ISSUE THREAD

**Issue by pvanallen** [adafruit/circuitpython#1124]
In Micropython, there is _thread, which is a minimal implementation of threading. 

https://docs.pycom.io/chapter/firmwareapi/micropython/_thread.html

Is it supported in Circuitpython? If so, how can I import it? If not, it would be incredibly useful. For example, here's an example I developed for Micropython on the ESP32

https://github.com/pvanallen/esp32-getstarted/blob/master/docs/multitasking.md

**Comment by deshipu** [comment]
There is not threading in CircuitPython.

**Comment by dhalbert** [comment]
We are thinking about ways to do multiprocessing and asynchronous processing, but we want to make it easy for beginners, and not just replicate existing tricky mechanisms. So we have not turned on the existing MicroPython mechanisms in our builds.

**Comment by pvanallen** [comment]
Thanks for the explanation - makes sense. If you want input on this, or testing of the ideas with students, I'd like to help. I teach in an MFA program, [build tools](https://github.com/pvanallen/delft-toolkit-v2/blob/master/README.md) and teach designers how to use programming to make prototypes for things like IoT and AI, where multiprocessing and asynchronous processing are critical. I'm using the Circuit Playground Express, ESP32, etc. and am switching from Arduino to Python.

**Comment by dhalbert** [comment]
Thanks, see if you have any comments for #619, which may or may not be enough for you.

**Comment by victorcedron** [comment]
In the present 2024 is _thread or another mechanism for threads available in circuitpython?, well I am using a pico w and it would be great to get the maximum resources for an automation project with AI.

**Comment by dhalbert** [comment]
See https://learn.adafruit.com/cooperative-multitasking-in-circuitpython-with-asyncio#faq-3106700 for our thoughts on this.
