### ISSUE TITLE
Add a BATTERY pin to board pins

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#1149]
`BATTERY` was already added to the hallowing, but `BATTERY` is not an alias for `D9` on Feathers. Would be convenient so you don't have to remember which pin. Suggested by @jedgarpark and @caternuson.

**Comment by arofarn** [comment]
Note : it's already ``board.VOLTAGE_MONITOR``, at least on Feather M4 Express.

**Comment by dhalbert** [comment]
The idea is that there's a pin with a name that matches the silkscreen labeling on the boards ("BAT" or BATTERY").
