### ISSUE TITLE
Long command in REPL history crashing trinket m0

### ISSUE THREAD

**Issue by daguitarguy** [adafruit/circuitpython#1181]
On trinket m0, with CircuitPython 3.0.1, connecting through Mu (or any serial connection), on the REPL  run command:

>>>print("111111111122222222223333333333444444444455555555566666666667777777777888888888899999999990000000000111111111122222222223333333333444444444455555555556666666666777777777788888888889999999999000000000011111111112222222222333333333344444444445555555555")

After successful execution, press arrow up key.

Expected Result: view the previously executed command from the REPL history
Actual Result:  the string "pr" is shown in the screen, and the trinket m0 has crashed, no more commands are accepted in the REPL, and the device cannot be ejected through USB.

**Comment by dhalbert** [comment]
Fixed by #1185.
