### ISSUE TITLE
Is there Deep sleep for D21 with RTC ?

### ISSUE THREAD

**Issue by bobricius** [adafruit/circuitpython#119]
Is implemented sleep functons with rtc for use D21 in watch powered with cr2032 ?
Bod controll ?

**Comment by tannewt** [comment]
I think the chip has it but I haven't implemented it. I'm not focusing on power consumption because our primary target is education and prototyping. I'd happily accept pull requests. Otherwise, it'll be a while until I get to it.

**Comment by bobricius** [comment]
https://github.com/edgecollective/circuitpython it seems that somebody started with sleeping but wakeup not working ....

**Comment by dhalbert** [comment]
Closed in favor of #696.
