### ISSUE TITLE
Crystall less configuration ?

### ISSUE THREAD

**Issue by bobricius** [adafruit/circuitpython#120]
Is implemented or can be configured crystall less custom board ?

**Comment by tannewt** [comment]
It is implemented for the upcoming Gemma, Trinket and CircuitPlayground. The basic thing to change is the include in `conf_clocks.h`: https://github.com/adafruit/circuitpython/blob/master/atmel-samd/boards/gemma_m0/conf_clocks.h

You can also `#define CRYSTALLESS` and use a different linker script if you want it to save the calibration anytime its on USB. Only the CircuitPlayground does this now: https://github.com/adafruit/circuitpython/blob/master/atmel-samd/boards/circuitplayground_express/mpconfigboard.mk
