### ISSUE TITLE
No __dict__  built into cp classes?

### ISSUE THREAD

**Issue by TG-Techie** [adafruit/circuitpython#1207]
does circuit python have the __dict__ part of classes incorporated?  I could not get it to work

I am making some a  classes for python and  I wanted to make my class  where the user can add their own variable to it, this is done with the add method (using kwargs for many at a time). then try to update self.__dict__ with the new keywords from kwargs but the serial output says my object does not have that attribute. 

if not is there any way  so when someone adds a new variable to the object to add a pointer to the new  to a list? 

I tried printing __dict__ of a created class in idle and it worked (3.7.0)
this is where I found the __dict__ stuff:
https://stackoverflow.com/questions/2675028/list-attributes-of-an-object

![image](https://user-images.githubusercontent.com/39284876/45918209-73d88c00-be51-11e8-8913-b158783cdb61.png)

![image](https://user-images.githubusercontent.com/39284876/45918220-a2566700-be51-11e8-9c9d-faec29b30c30.png)

**Comment by deshipu** [comment]
Even normal Python's classes don't need to have a `__dict__` — that is an internal detail which you shouldn't be relying on. Instead you should use `getattr` and `setattr` for getting and setting attributes that you have specified as strings.

**Comment by TG-Techie** [comment]
Thanks Deshipu, I'll check it out then get back!

**Comment by TG-Techie** [comment]
okay, that worked! . also it would be great if there was some sort of attr func that returns a pointer to an attribute like below.   Would this be permissible for me to try to add? Although it isn't in python python...

x = class_with_attributes()
my_pointer = attr( x, 'attr_name', value) # this makes my_pointer a pointer to x.attr_name

thoughts ?

**Comment by deshipu** [comment]
Well, there are no pointers in Python, but isn't this what `getattr` does?

**Comment by dhalbert** [comment]
Closing. Reopen if anything else, or just ask in discord.
