### ISSUE TITLE
polyphonic WAV playback on M4

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#1221]
on big-memory chips like M4, if we restrict to all-same-samplerate then we could implement 4-simultaneous WAV playbacks?
related:
https://github.com/adafruit/circuitpython/issues/987

i wrote some code to do this in pure python but its not fast enough to do on the fly :/
this is for Trellis M4 projects + would also let me replace the audio FX boards with circuitpython. also great for props - a common request is a 'background sound' and then a triggered 'foreground' sound and no audio boards can do it unless you drop a ton o' $

**Comment by tannewt** [comment]
Done with https://github.com/adafruit/circuitpython/pull/1242
