### ISSUE TITLE
String internazionalization for Italian

### ISSUE THREAD

**Issue by platipo** [adafruit/circuitpython#1226]
I'm willing to add Italian translation. #1098

**Comment by tannewt** [comment]
Yay! Thank you! 🎉

**Comment by platipo** [comment]
I opened the issue for the main reason that I need more informations on some lines. Example: https://github.com/adafruit/circuitpython/blob/master/locale/circuitpython.pot#L509
https://github.com/adafruit/circuitpython/blob/master/locale/circuitpython.pot#L513
Can you give more context on the pull up/down, please?

**Comment by tannewt** [comment]
Its a common electronics concept. See wikipedia for an explanation: https://en.wikipedia.org/wiki/Pull-up_resistor

**Comment by platipo** [comment]
That's exactly what I was looking for. Can you help me with  [_advertisment packet_](https://github.com/adafruit/circuitpython/blob/master/locale/circuitpython.pot#L754)?

**Comment by platipo** [comment]
Shouldn't it be advertisement instead of advertisment? Or am I mistaken?

**Comment by tannewt** [comment]
Yup, looks like a typo.

**Comment by platipo** [comment]
I'm not sure what [STA](https://github.com/adafruit/circuitpython/blob/master/locale/circuitpython.pot#L622) stands for, can you give me a hint please? Also [bit clock / bit clock pin](https://github.com/adafruit/circuitpython/blob/master/locale/circuitpython.pot#L261)?

**Comment by dhalbert** [comment]
bit clock in i2S
https://en.wikipedia.org/wiki/I%C2%B2S
https://it.wikipedia.org/wiki/I%C2%B2S

STA is short for "station": https://en.wikipedia.org/wiki/Station_(networking)
https://it.wikipedia.org/wiki/IEEE_802.11

**Comment by platipo** [comment]
Thanks @dhalbert!

Is there someone available to check my translation? There are about 100 lines missing to do.
