### ISSUE TITLE
nrf port storage.erase_filesystem() does not work

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#1243]
It looks like the storage.erase_filesystem() erase was not fully implemented on the nrf port

the nrf port passed the argument to do a "force_create"
https://github.com/adafruit/circuitpython/blob/master/ports/nrf/common-hal/storage/__init__.c#L44

but it is not used by filesystem_init()

nrf port
https://github.com/adafruit/circuitpython/blob/master/ports/nrf/supervisor/filesystem.c#L39
atmel port
https://github.com/adafruit/circuitpython/blob/master/ports/atmel-samd/supervisor/filesystem.c#L46

I'll be happy to fix this an put in a PR

**Comment by dhalbert** [comment]
Fixed by #1245.
