### ISSUE TITLE
Unable to change filesystem label

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#1252]
Doing so causes the filesystem to not show over USB!

```python
import storage

storage.remount("/", readonly=True)

m = storage.getmount("/")
m.label = "TRELLIS_PY"

storage.remount("/", readonly=False)
```

**Comment by tannewt** [comment]
(That goes in `boot.py`)

**Comment by tannewt** [comment]
The serial connection can still be used so you can recover by renaming the `boot.py` file to something else.

**Comment by kattni** [comment]
Tested on Feather M4 running 4.0.0alpha.3 and 4.0.0alpha.5. Including a `boot.py` with the above contents successfully renames the CIRCUITPY drive and mounts without issue following the rename.

**Comment by tannewt** [comment]
Ok, closing this. I believe I had a separate bug at the time that I was hitting.
