### ISSUE TITLE
Does CircuitPython 4.0 imply Bundles 4.0?

### ISSUE THREAD

**Issue by mew-cx** [adafruit/circuitpython#1281]
Hi,

Thanks for CircuitPython, I'm enjoying exploring w ItsyBitsy M4.

I didn't see mention in the release notes, and given the 2.x v 3.x versioning described on the [libraries page](https://learn.adafruit.com/welcome-to-circuitpython/circuitpython-libraries), it would seem that there will be a library bundle version for 4.x?  

I don't know if you're officially using [Semantic Versioning](https://semver.org/)?  If so, that major version bump also suggests an incompatibility from 3.x.

cheers
-- mew

**Comment by dhalbert** [comment]
The library bundle version numbers actually refer to the .mpy version. By coincidence this matches the CircuitPython version, but 3.x and 4.x .mpy files will probably continue to be compatible. You can use the 3.x bundle with 4.0.0-alpha.<n>

However, to avoid confusion, we're going to publish 3.x and 4.x bundles (and drop 2.x). We actually just made a change to do this: https://github.com/adafruit/circuitpython-build-tools/pull/19
