### ISSUE TITLE
mac os finder killing file contents on HalloWing

### ISSUE THREAD

**Issue by jedgarpark** [adafruit/circuitpython#1297]
I've had something odd happen a few times now on HalloWing w the Hackaday Superconference badge code. I rename the `touchslideshow_code.py` to `code.py` in the Finder, and when it, restarts the `code.py` file is an entirely empty file.

Running 4.0.0 Alpha 2 and this code: (https://github.com/adafruit/CircuitPython_Badge_README/tree/master/final_versions/HACKADAY_SUPERCON_2018)

**Comment by tannewt** [comment]
@jedgarpark What do you mean by restart? Are you unplugging it and plugging back in?

**Comment by jedgarpark** [comment]
No, the board restarts whenever I add or change a file using the Finder, so when I rename the .py file to code.py and hit enter, the Feather restarts.

**Comment by tannewt** [comment]
This is going to be hard to reproduce and is likely no longer an issue. Please re-open if it still is an issue.
