### ISSUE TITLE
Implement changing PWM frequency

### ISSUE THREAD

**Issue by tdicola** [adafruit/circuitpython#13]
Right now the PWM objects just let you change duty cycle with the duty function (0-255, 8 bit values).  However it would be handy to also support changing the frequency with the freq function which takes in a frequency in hertz for the PWM signal to use.  This is similar to the behavior in the ESP8266 port (IIRC there is a limitation that the frequency is global across all PWM output, so it's not the end of the world if we need a similar limitation vs. trying to have a mess of timers for each PWM output).

**Comment by tannewt** [comment]
Fixed in e3f9ee839afb5a369779a30a96214c929e76911e. You can now set a fixed frequency in the constructor which on SAMD will allow multiple PWMOuts to share the same timer or set `variable_frequency` to claim a whole timer and be able to change the frequency after construction.
