### ISSUE TITLE
[nRF52840] Set NFC pins to be used as GPIO by default

### ISSUE THREAD

**Issue by uhrheber** [adafruit/circuitpython#1300]
The stock setting on the pca10059 dongle, and possibly also on the pca10056 DK configures the pins P0_09 and P0_10 as NFC pins, therefore they can't be used as GPIO pins. Also after a full chip erase, the pins are configured as NFC by default.

Circuitpython allows to define them as GPIOs, without any warning, even if they are reserved for NFC.

As NFC isn't supported by Micropython at this time, and probably for a long time to come, it would make sense to configure those pins as GPIOs by default, and maybe add an option to use them as NFC pins in the mpconfigport.h file later.

To configure them as GPIOs, the NFCPINS register (base address: 0x10001000 offset: 0x20C) has to be set to 0.

**Comment by arturo182** [comment]
There is a `CONFIG_NFCT_PINS_AS_GPIOS` define that can be used to achieve this, it could be used on a per-board basis, I've been using it locally for my board.

See also https://github.com/NordicSemiconductor/nrfx/blob/d4ebe15f58de1442e3eed93b40d13930e7785903/mdk/system_nrf52.c#L184

**Comment by uhrheber** [comment]
Thank you, arturo182, I didn't see that.

**Comment by tannewt** [comment]
So to summarize, we should:
- [ ] Enable `CONFIG_NFCT_PINS_AS_GPIOS` by default because NFC isn't currently supported
- [ ] Have DigitalInOut verify the pins aren't configured for NFC.

Anything else?

**Comment by uhrheber** [comment]
That nails it.

**Comment by dhalbert** [comment]
I got this working and will do a PR. However, a couple of notes:
1. On the PCA10056 board, there are P0.09, and P0.10 positions on the black female headers. But these are unconnected unless you move the 0-ohm jumper resistors from R44 to R43 and R46 to R45. That was a head-scratcher for a while; see [this Nordic Devzone comment](https://devzone.nordicsemi.com/f/nordic-q-a/30703/gpio-pin-mapping-issue-in-nrf52840-pdk/121521#121521). It's easier to test using the TP17 and TP18 test points near those resistors (near the NFC connector).
2. The nRF52832 NFC pins [are described](https://devzone.nordicsemi.com/f/nordic-q-a/42990/nrf52832-pin-11-p0-09-and-pin-12-p0-10-is-only-3-0v/167770#167770) as having some kind of shunt between them for protection. So there is leakage current between the pins. I don't know if the nRF52840 is the same, but it seems possible. So they may not work as well.

**Comment by dhalbert** [comment]
Also, I didn't restrict this to just `DigitalInOut`, since conceivably the pins could be used for other purposes.
