### ISSUE TITLE
clipped audio confuses the heck out of mixer/audioio

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#1305]
yeah we shouldnt clip audio but perhaps theres an offbyone that makes it sound particularly sad

**Comment by tannewt** [comment]
Ya, I think there is an overflow somewhere.

**Comment by sommersoft** [comment]
@ladyada can you reevaluate this to see if #2080 fixes it? The mixing is now halved per sample to avoid "ring modulation", in addition to the previous hard clipping.

**Comment by ladyada** [comment]
ill defer to @jepler to try this out since he'll have the setup for it - a clipped sine wave should not cause static, just sound clipped :)

**Comment by jepler** [comment]
I did testing of this and found that the scaling of voices prevented clipping or overflows in the scenarios I used, with 1 or 2 voices. (I did not test >2 voices though)
