### ISSUE TITLE
Request: include json support

### ISSUE THREAD

**Issue by robmarkcole** [adafruit/circuitpython#1307]
Being able to dump a dict to a json string is pretty handy. From danh on Discord chat: `Feel free to open an issue about turning it on, especially in the M4 and nRF ports. It's off due to lack of space in the M0 ports, and there were some minor issues as well when I tried to turn it on: https://github.com/adafruit/circuitpython/pull/138. We'd probably rename both ure and ujson to re and json.`

**Comment by ladyada** [comment]
@robmarkcole fyi i've been using ujson on m4 builds, seems to work well! try it out :)

**Comment by vgoodwinv** [comment]
This can be closed?
