### ISSUE TITLE
Change `sys.path` to `['', '/', '.frozen', '/lib']` to address memory on builds with frozen libs

### ISSUE THREAD

**Issue by kattni** [adafruit/circuitpython#1310]
The issue with memory allocation failures on M0 builds with frozen libraries is coming up constantly now. The most reasonable solution is to switch the path to `['', '/', '.frozen', '/lib']` to resolve this. 

While it would be ideal to address the underlying issue instead, it's not reasonable right now to fix all of the memory issues we're seeing in the M0 builds. There is no quick answer to fixing the underlying issue, and we need something in place now. 

I discussed it again with @caternuson because he's a perfect example of the support people who are dealing with this. If we make this change, the thing that will have to happen is for users to upgrade to the latest version of CircuitPython, a step which is much simpler to identify and explain than explaining frozen modules and the reason for deleting the library from the /lib folder.

**Comment by dhalbert** [comment]
I agree with this. We can make a 3.1.0 release and also incorporate into master. Happy to do the work.

**Comment by tannewt** [comment]
I'm ok with this too. I think its a good compromise because it doesn't let the use-case specific builds creep out into the bundle.

**Comment by kattni** [comment]
Excellent. I'm going to update the issue on the bundle and close it in favor of this one.

**Comment by kevinjwalters** [comment]
I just made a summary of the 3.0.x situation to make current situation more visible and readable by the masses: https://forums.adafruit.com/viewtopic.php?f=60&t=143160

**Comment by dhalbert** [comment]
Fixed by #1314. Released in 3.1.1.
