### ISSUE TITLE
audioio - staticky *sometimes* during playback of long files

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#1316]
@tannewt ping me when you do this one, its on the trellis m4, not thru the mixer and only sometimes?
but if it does happen, its the same static each time

[wave.zip](https://github.com/adafruit/circuitpython/files/2545095/wave.zip)

**Comment by tannewt** [comment]
Maybe @deanm1278 would like to take a look before I can. :-)

**Comment by deanm1278** [comment]
do you have any test code for this?

**Comment by ladyada** [comment]
https://github.com/adafruit/adabox-demos/blob/master/adabox010/python/stereo_audio.py

**Comment by ladyada** [comment]
one possible - i think this has to do with USB activity that occurs while audio plays. if i have alot of print()s it causes a staticky effect

**Comment by tannewt** [comment]
@dhalbert I think this might be related to your current investigation.

**Comment by dhalbert** [comment]
Fixed by #5196

**Comment by ladyada** [comment]
yessssssssssssssssssssssss

**Comment by dhalbert** [comment]
I am not sure this is really fixed completely, but it is better.
