### ISSUE TITLE
displayio: Make FourWire SPI object available?

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#1337]
@ATMakersOrg tried an RFM FeatherWing needing SPI on the back of the HalloWing. But since the regular Feather SPI pins are attached to the display and used for the `FourWire` display object, SPI on the regular pins was not available.

Would it be possible to make that SPI object available via a property, or is it really too dedicated to share?

**Comment by tannewt** [comment]
We should make it available through board.SPI if it isn't already.

**Comment by tannewt** [comment]
The shared SPI should be available through `board.SPI()` now on Hallowing.
