### ISSUE TITLE
esp8266 busio pin check error

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#134]
on an esp8266 (Huzzah breakout) When initializing busio.I2C it returns an error for Pin DVDD "in use"

to replicate execute:

from board import *
import busio
bus = busio.I2C(SCL,SDA)
generates:
ValueError: Pin DVDD in use

**Comment by tannewt** [comment]
Hi @jerryneedell, I can't reproduce this on the feather version. I'm using 0.10.1.

```
Adafruit CircuitPython 0.10.1 on 2017-05-20; ESP module with ESP8266
>>> from board import *
>>> import busio
>>> bus = busio.I2C(SCL, SDA)
>>>
>>>
PYB: soft reboot
#5 ets_task(40100164, 3, 3fff839c, 4)
boot.py output:


Press any key to enter the REPL. Use CTRL-D to soft reset.

Adafruit CircuitPython 0.10.1 on 2017-05-20; ESP module with ESP8266
>>> from board import *
>>> import busio
>>> bus - busio.I2C(SCL, SDA)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'bus' is not defined
>>> bus = busio.I2C(SCL, SDA)
>>>
```

Any thing I missed? Does it still repro for you?

**Comment by jerryneedell** [comment]
Odd -  I was using a "non-feather" ESP8266 Huzzah - in case that makes a difference. I try both when I get home later this afternoon.

**Comment by jerryneedell** [comment]
I guess you fixed it ... ;-)  I can't reproduce it now either. Sorry ... Feel free to close it, I'll repost it if/when I can reproduce it. - I hate problems that just go away. They usually reappear at the worst possible time ...

**Comment by tannewt** [comment]
No worries! I'd rather have an issue filed that goes away versus not hearing about something at all. Thanks again @jerryneedell! Reopen if it happens again.
