### ISSUE TITLE
create driver for TMP006

### ISSUE THREAD

**Issue by caternuson** [adafruit/circuitpython#1355]
For this:
https://www.adafruit.com/product/1296

A driver for the TMP007, which replaces the TMP006, already exists. However, might help to go ahead and make one for the TMP006 also, for people still using it, ex:
https://forums.adafruit.com/viewtopic.php?f=50&t=143712

**Comment by ladyada** [comment]
@caternuson ok we still have some in stock, and we've already got some python code , so between the original py library and the tmp007 it should not be hard

**Comment by caternuson** [comment]
Done.
https://github.com/adafruit/Adafruit_CircuitPython_TMP006

**Comment by ladyada** [comment]
niiiiice
