### ISSUE TITLE
Having diffuculties with PWM on Trinket M0

### ISSUE THREAD

**Issue by Pigweed** [adafruit/circuitpython#1368]
I am super new to Circuit Python and the Adafruit boards so please be patient. I am working my way through the online tutorials and made it through the Trinket M0 Circuit Python guide with no trouble here:
https://learn.adafruit.com/adafruit-trinket-m0-circuitpython-arduino/circuitpython

Now I am working through Circuit Python Essentials and am stuck on the PWM section here:
https://learn.adafruit.com/circuitpython-essentials/circuitpython-pwm

I get this:
code.py output:
Traceback (most recent call last):
  File "code.py", line 3, in <module>
ImportError: no module named 'pulseio'

I have been digging around but cannot find anything to clear this up. 
Any advice on where to go from here?

**Comment by dhalbert** [comment]
Unfortunately, `pulseio` is not available on the Trinket M0, Gemma M0, and other non-Express boards (boards without external SPI flash chips) due to lack of space. Check out the "Support Matrix" here: https://circuitpython.readthedocs.io/en/3.x/shared-bindings/index.html#module-support-matrix.

**Comment by ladyada** [comment]
dan, i thought we added it in 3 after we made space?  its audio that didnt make itin?

**Comment by dhalbert** [comment]
@ladyada is right! I'm sorry. `pulseio` is present in version 3.x. I assume you're running 2.x or earlier. Update to 3.1.1 and you'll be fine! Note that you also need to update the libraries in the lib directory to 3.x versions. For directions, see: 
https://learn.adafruit.com/welcome-to-circuitpython/installing-circuitpython
https://learn.adafruit.com/welcome-to-circuitpython/circuitpython-libraries

Temporarily rename `main.py` or `code.py` to something else, like `mainx.py` while you are updating CircuitPython and the libraries. You can get stuck in a confusing error state if the old libraries are still present when you update and main.py is running automatically.

**Comment by ladyada** [comment]
all good! lots has changed 😊

**Comment by Pigweed** [comment]
Home Run! Thank you so much. I am impressed by this little board.
