### ISSUE TITLE
Add status LED error code for incompatible mpy error

### ISSUE THREAD

**Issue by kattni** [adafruit/circuitpython#1369]
As per discussion here: https://github.com/adafruit/Adafruit_CircuitPython_Bundle/issues/94

We need to add another status LED error code to the current set for the incompatible mpy error. We agreed on pulsing blue for when this error is encountered.

**Comment by terriko** [comment]
I'm working on this at the pycon sprints and have discovered that setting the LED to any other colour results in it going red -- except if you set it to yellow.  So I think maybe something is using the LED colour to check status and freaking out if it's not one of the expected statuses?  Will do some reading.
