### ISSUE TITLE
bleio examples and documentation?

### ISSUE THREAD

**Issue by edwios** [adafruit/circuitpython#1371]
Hi,

Is there any further documentation on using the bleio as a peripheral? I can start the advertising but there is no further documentation on how to handle a connection, such as setting the connection handler and various event types, etc..

I am trying to build a very simple example following the one in ubluepy_temp, simply reporting the CPU temperature.

SoC I am using is the nRF52840.

BR/
Ed

**Comment by dhalbert** [comment]
The `bleio` API that's included now is incomplete, and is undergoing a revision and expansion. Watch for a release relatively soon that has more (and changed) functionality.
