### ISSUE TITLE
SAMD51+tinyusb - doesnt auto doesnt soft-reset on save during time.sleep()

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#1390]
Adafruit CircuitPython 4.0.0-alpha.4-4-g2b739e1 on 2018-12-08; Adafruit Feather M4 Express with samd51j19

using atom with dan's flush-write plugin, but i dont think its related. try below and change print text then save, it wont restart till time.sleep finishes

```
while True:
    print('hello')
    time.sleep(10)
```

**Comment by tannewt** [comment]
My guess is that the sleep isn't checking to see if a reload has been requested.
