### ISSUE TITLE
Driver for SHARP memory displays

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#1409]
https://www.adafruit.com/product/3502

**Comment by deshipu** [comment]
I had several attempt at writing a driver for those, but somehow I can't get them to work, even if I reproduce the Arduino logic exactly. There is some black magic at work in there, possibly having to do with timings.

**Comment by deshipu** [comment]
By the way, is there a datasheet available for the 168x144 one somewhere? I couldn't find anything.

**Comment by ladyada** [comment]
hiya driver is here!
https://github.com/adafruit/Adafruit_CircuitPython_SharpMemoryDisplay
closing this issue, if you have q's, put em in that repo :)
