### ISSUE TITLE
build Zerro error

### ISSUE THREAD

**Issue by CarlFK** [adafruit/circuitpython#1410]
docs and reality don't match:

https://github.com/adafruit/circuitpython/tree/master/ports/atmel-samd#building
```
To build for the Arduino Zero:
make
```
```
carl@twist:~/src/circuitpython/ports/atmel-samd$ make
Makefile:3: *** You must provide a BOARD parameter.  Stop.
carl@twist:~/src/circuitpython/ports/atmel-samd$ 
```

**Comment by ladyada** [comment]
closin' cause i think dox are now clear. please reopen if its still not right :)
