### ISSUE TITLE
Cannot use input() nor raw_input()

### ISSUE THREAD

**Issue by cyborg5** [adafruit/circuitpython#143]
Attempts to use keyboard input on Circuit Python such as

Value=input("Please type a value:")

gives an error message "input not defined". Same problem with "raw_input("prompt:")"

Also it doesn't help to "import builtins" and then "Value=builtins.input("Prompt:")"

This was on Circuit Python 0.10.1 on a Feather M0 Express

**Comment by tannewt** [comment]
Looks like `raw_input` is a python2 thing. Adding `input` shortly.
