### ISSUE TITLE
I2C not working on Grand Central

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#1456]
I cannot get my Grand Central to communicate with some I2C devices -- tried FRAM and LSM9DS1
I am using SDA = D20, SCL = D21 as per:
https://github.com/adafruit/circuitpython/blob/master/ports/atmel-samd/boards/grandcentral_m4_express/pins.c#L61
for the FRAM
```

Adafruit CircuitPython 4.0.0-alpha.5-120-g573c6d60b on 2019-01-11; Adafruit Grand Central M4 Express with samd51p20
>>> import fram_i2c_simpletest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fram_i2c_simpletest.py", line 9, in <module>
  File "/lib/adafruit_fram.py", line 209, in __init__
  File "/lib/adafruit_bus_device/i2c_device.py", line 78, in __init__
  File "/lib/adafruit_bus_device/i2c_device.py", line 76, in __init__
ValueError: No I2C device at address: 7c
>>> 
```
for the lsm9ds1:
```

Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 4.0.0-alpha.5-120-g573c6d60b on 2019-01-11; Adafruit Grand Central M4 Express with samd51p20
>>> import lsm9ds1_simpletest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "lsm9ds1_simpletest.py", line 10, in <module>
  File "/lib/adafruit_lsm9ds1.py", line 369, in __init__
  File "/lib/adafruit_bus_device/i2c_device.py", line 78, in __init__
  File "/lib/adafruit_bus_device/i2c_device.py", line 76, in __init__
ValueError: No I2C device at address: 1e
>>> 



```

if I run I2C_SCAN, it just hangs -- cannot control C out -- have to hard reset.
i2c_scan.py
```
import board
import busio

i2c = busio.I2C(board.SCL, board.SDA)
count = 0

# Wait for I2C lock
while not i2c.try_lock():
    pass

# Scan for devices on the I2C bus
print("Scanning I2C bus")
for x in i2c.scan():
    print(hex(x))
    count += 1

print("%d device(s) found on I2C bus" % count)

# Release the I2C bus
i2c.unlock()

```

Both the FRAM and LSM9DS1 work normally when connected to a feather_nrf52840 SCL/SDA

**Comment by ladyada** [comment]
try the SDA/SCL pins?

**Comment by jerryneedell** [comment]
I did  those first -- they did not work either.

**Comment by jerryneedell** [comment]
did you test with CP or arduino?

**Comment by ladyada** [comment]
wierd - just arduino that i can recall

**Comment by jerryneedell** [comment]
I can try arduino just to make sure HW is OK , but I think there is a problem in CP -- there was a forum post as well https://forums.adafruit.com/viewtopic.php?f=60&t=146073

**Comment by ladyada** [comment]
hmm - ok wanna take a look at the board definition? see if maybe the pins aren't defined right?

**Comment by jerryneedell** [comment]
sure -- should SDA/SDC be the ones silkscreened because they definitely are not - they are SDA1/SCL1 in pins.c

**Comment by jerryneedell** [comment]
Is there a schematic available?

**Comment by ladyada** [comment]
@kattni can give you the schem (guide is coming up soon!)

**Comment by kattni** [comment]
Provided!

**Comment by dhalbert** [comment]
Tried an SHT31 with a recent CircuitPython build. Also doesn't work: it can't find the device. But it knows it's connected: it doesn't complain about "needs a pullup". I tried SCL1 and SDA1 (pins 24 and 25), and it works fine.

In CircuitPython, the pin mapping appears wrong: SCL and SDA are also 21 and 20, respectively, which are at the other end of that side of the board.

**Comment by jerryneedell** [comment]
Ah -- OK - the LSM9DS1 also works using SDA1/SCL1 on 25/24 
It's not clear what is wrong with SCL/SDA on 21/20 since the schematic shows them going to the right pins - actually multiple pins...

**Comment by jerryneedell** [comment]
looking at the arduino variants.h https://github.com/adafruit/ArduinoCore-samd/blob/master/variants/grand_central_m4/variant.h#L216
I am confused by the pin numbers -- how do these map to the schematic?

**Comment by dhalbert** [comment]
ok, yes, pins 21 and SCL, and pins 20 and SDA are correspondingly connected together (verified with ohmmeter).

**Comment by jerryneedell** [comment]
I verified that an MCP9808 sensor work using the SCL/SDA pins under Arduino

**Comment by dhalbert** [comment]
Looks like some SERCOM errors in https://github.com/adafruit/samd-peripherals/blob/master/samd/samd51/pins.c. I wonder if there are differences between the SAMD51 chips. Anyway, diagnosed.
