### ISSUE TITLE
displayio OnDiskBitmap properties

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#1460]
expose width/height so we can center images :)

**Comment by tannewt** [comment]
@caternuson Do you have cycles for this? It's similar to the other core work you did.

**Comment by caternuson** [comment]
I could probably work it in. But @siddacious - you were wanting to try this last time. So why don't you go ahead and take this one.

**Comment by siddacious** [comment]
All done!

**Comment by tannewt** [comment]
Thank you @siddacious!
