### ISSUE TITLE
displayio - 8 bit interface

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#1465]
SPI is good, but 8 bit is 8x better ;)

**Comment by tannewt** [comment]
How often are you updating a large portion of the screen? It might be better to do partial updates before doing 8 bit parallel support.

**Comment by ladyada** [comment]
partial is better - but 8 bit lets me finalize hardware - so even tho its less useful, its slightly more of a blocker

**Comment by tannewt** [comment]
kk, does @PaintYourDragon have C code for it already? It'd be great to DMA it so we can compute pixels while we transmit.

**Comment by ladyada** [comment]
you can....but its held together with duct tape n string because you have to toggle the Write Latch after each 8-bit write. https://github.com/adafruit/Adafruit_TFTDMA
