### ISSUE TITLE
PortIn and PortOut constructors return None rather than exception

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#1490]
They should raise an exception to make incorrect use more obvious.

**Comment by cpforbes** [comment]
Would it make sense to just remove the constructors instead?
So they behave like microcontroller.Processor or supervisor.Runtime?

**Comment by tannewt** [comment]
Yup! I just looked at that yesterday and did exactly that. Feel free to do it for me. I've lumped mine in with a bunch of other changes.
