### ISSUE TITLE
Circuit Playground Express build fails with strncpy error using developer.arm.com compiler

### ISSUE THREAD

**Issue by siehputz** [adafruit/circuitpython#1498]
Building master with the compiler from developer.arm.com I see:

CC ../../lib/tinyusb/src/class/msc/msc_device.c
../../lib/tinyusb/src/class/msc/msc_device.c: In function 'proc_builtin_scsi':
../../lib/tinyusb/src/class/msc/msc_device.c:273:7: error: 'strncpy' output truncated before terminating nul copying 8 bytes from a string of the same length [-Werror=stringop-truncation]
       strncpy((char*) inquiry_rsp.vendor_id  , CFG_TUD_MSC_VENDOR     , sizeof(inquiry_rsp.vendor_id));
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../lib/tinyusb/src/class/msc/msc_device.c:274:7: error: 'strncpy' output truncated before terminating nul copying 16 bytes from a string of the same length  -Werror=stringop-truncation]
       strncpy((char*) inquiry_rsp.product_id , CFG_TUD_MSC_PRODUCT    , sizeof(inquiry_rsp.product_id));
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [build-circuitplayground_express/lib/tinyusb/src/class/msc/msc_device.o] Error 1

Apparently being caused by the following defines in 
build-circuitplayground_express/genhdr/autogen_usb_descriptor.h

// Vendor name included in Inquiry response, max 8 bytes
#define CFG_TUD_MSC_VENDOR          "Adafruit"

// Product name included in Inquiry response, max 16 bytes
#define CFG_TUD_MSC_PRODUCT         "CircuitPlaygroun"

**Comment by dhalbert** [comment]
This is an issue in the tinyusb library; I filed an issue there a few days ago: https://github.com/hathach/tinyusb/issues/33. For now just use the 7-2018-q2 release of the arm gcc toolchain.
