### ISSUE TITLE
no parallelio module for communicating with chips

### ISSUE THREAD

**Issue by TG-Techie** [adafruit/circuitpython#1504]
I would love to talk to a display or parallel chips without (i haven't yet but will need to) bit banging the protocol. for example, the portal now is configured in parallel but I would love to have a more traditional library to talk to it in addition to displayio

**Comment by tannewt** [comment]
What other chips are parallel? Could you give an example of the code you'd like to write?

**Comment by TG-Techie** [comment]
my main interest in the ili9341 and other parallel displays

**Comment by tannewt** [comment]
Ok, I've added the ability to have display bus (FourWire or ParallelBus) send a command. This is likely all you need. PR incoming with it.

**Comment by TG-Techie** [comment]
awesome!  when working I'll post some code and close, sound good?
