### ISSUE TITLE
property inheritance: not able to call properties from parent classes

### ISSUE THREAD

**Issue by TG-Techie** [adafruit/circuitpython#1507]
the code below returns this error:

Traceback (most recent call last):
  File "main.py", line 39, in <module>
  File "/file_location", line ###, in val
AttributeError: 'super' object has no attribute 'val'

```
class parent():
    def __init__(self, initval):
        self._val = initval

    @property
    def val(self):
        return self._val

    @val.setter
    def val(self, valin):
        self._val = valin
        print('in parent')

def child(parent):

    @property
    def val(self):
        return super()._val

    @val.setter
    def val(self, valin):
        super().val = valin
        print('in child')
```

**Comment by notro** [comment]
This doesn't work in CPython either. 
Maybe this can give some insight: https://stackoverflow.com/questions/13595607/using-super-in-a-propertys-setter-method-when-using-the-property-decorator-r

I tested Example 2 and it works in CircuitPython.

**Comment by dhalbert** [comment]
@notro Thanks, this is a complicated issue. Let close it as not an issue specific to CircuitPython.
