### ISSUE TITLE
Direction OUTPUT/INPUT

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#152]
INPUT & OUTPUT instead of IN and OUT? whatcha think?

**Comment by willingc** [comment]
Sounds reasonable to me. Assuming it's to make things clearer for the end user. Or is it to avoid namespace conflicts?

**Comment by ladyada** [comment]
mostly to match Arduino-ese? i dunno. im mixed about it. Arduino uses INPUT/OUTPUT and Raspi uses IN/OUT

**Comment by tannewt** [comment]
Either way is fine with me. I should be able to do this today alogn with moving the Enum-like class out of DigitalInOut into digitalio.

**Comment by willingc** [comment]
It's a coin toss. One of the reasons that Raspberry Pi uses the shorter IN/OUT is that younger kids are not the best typists. I think either option is fine.
