### ISSUE TITLE
socket.makefile is missing ...

### ISSUE THREAD

**Issue by nickzoic** [adafruit/circuitpython#1522]
In the process of looking into #703 / #1500 I noticed that `socket.makefile()` is missing.

In CPython, this returns a file object wrapping the socket, so normal file handle operations can be used.
* https://docs.python.org/3/library/socket.html#socket.socket.makefile 

In MicroPython it just returns the socket *but* the socket itself supports file handle operations
* https://docs.micropython.org/en/latest/library/usocket.html#usocket.socket.makefile

In CircuitPython we're going for a strict subset so I think the behaviour should be more like CPython's, return a different object wrapping the same underlying socket.

**Comment by nickzoic** [comment]
In CPython, it looks like you can call "s.makefile()" multiple times and
get multiple different file objects, but the file objects *each* have a
buffer so behaviour on reads is somewhat undefined.
In MicroPython, "s.makefile()" exists only for compatibility and just
returns "s".  This means that you can call "s.makefile().makefile()"
which is a bit weird.
I'd propose that in CircuitPython we should stick to a more CPython like
convention but maybe have "s.makefile()" always return the same object
for convenience.  We'd normally not have much of a buffer anyway,
compared to CPython, due to the smaller RAM size in these platforms.

**Comment by nickzoic** [comment]
(work in progress over at https://github.com/nickzoic/micropython/tree/circuitpython-nickzoic-1522-socket-makefile-missing )

**Comment by hierophect** [comment]
@tannewt similar ping on this as #2097

**Comment by tannewt** [comment]
Yup, ok to close.
