### ISSUE TITLE
Pulsed Audio

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#1532]
Add ability to playback audio through a PWM output. That will allow us to playback audio on pins that don't have a DAC. An RC filter can be added to smooth it out.

**Comment by jepler** [comment]
@tannewt this is implemented on nrf now, and infrastructure is committed would help a future implementation for atmel_samd.  Do you want to hold this issue open?

**Comment by tannewt** [comment]
Nope, let's close this. We can always open a new issue when we want it for samd. Thanks 🎉
