### ISSUE TITLE
DISPIO: buggy?? 

### ISSUE THREAD

**Issue by TG-Techie** [adafruit/circuitpython#1539]
in this and another program, it just crashes after going through a try except

```
import TG_Display_Emulator as disp, board, time

disp.DISPLAY = board.DISPLAY
disp.WIDTH = 320
disp.HEIGHT = 240


for i in range(255):
    try:
        disp.rect(i,i,i,i,disp.color(255-i, i//2 * 128, i))
    except:
        pass
```
crashes the pyportal

need:
https://github.com/TG-Techie/TG_CircuitPython_Display_Emulator

**Comment by tannewt** [comment]
@TG-Techie Do you have a debugger handy like a JLink? That would allow you to get a backtrace.

**Comment by TG-Techie** [comment]
not hand, I'm back near one on Saturday after 5

**Comment by tannewt** [comment]
Please try it with #1548.

Smaller examples that cause the crash are handier as well. Thanks!

**Comment by tannewt** [comment]
@TG-Techie did you get a chance to test this with the latest code?

**Comment by tannewt** [comment]
@TG-Techie Please reopen if this is an issue still.
