### ISSUE TITLE
Feather nrf52840 is missing the ure module

### ISSUE THREAD

**Issue by dastels** [adafruit/circuitpython#1547]
The ure module  is present on the Feather, ItsyBitsy, & GrandCentral, but not on the Feather nRF52840.

**Comment by dhalbert** [comment]
I'm going to refactor the `mpconfigport.h` files so we have a common set of features turned on/off across the atmel and nrf ports.

There are some serious differences, including choice of MICROPY_OBJ_REPR (!).

**Comment by dhalbert** [comment]
Added to nrf builds by #1554. Enhanced by #1544.
