### ISSUE TITLE
DISPIO: zero Shape height crashes and bootloops cp

### ISSUE THREAD

**Issue by TG-Techie** [adafruit/circuitpython#1549]
try making s shape have no height! then putting it in a group and showing it

it should raise a ValueError: Width of Shape cannot be zero
it doesn't

**Comment by TG-Techie** [comment]
height too

**Comment by ladyada** [comment]
@TG-Techie if you can write a minimal (but complete) example code for these bugs to demonstrate it crashing, plus the output of the crash that will really help us find and squish these bugs! the more details/info, the better as it lets us focus on fixing :)

**Comment by TG-Techie** [comment]
Totally will write one up now
error message: starts boot looping and does not appear on usb 

```
from displayio import *

shp = Shape(20, 0)
```

**Comment by tannewt** [comment]
Please update to the latest master. I fixed this with #1548. Thank you for the small code example.

Also, it should no longer boot loop. It should enter safe mode now after a crash.
