### ISSUE TITLE
RTC Functionality missing from NRF making DS3231 Library Unusable

### ISSUE THREAD

**Issue by makermelissa** [adafruit/circuitpython#1561]
Regarding Discussion in PR https://github.com/adafruit/Adafruit_CircuitPython_FeatherWing/pull/27, in the latest official release (beta 2), the functions are there, but cause a BCDDateTimeRegister object to be returned. @jerryneedell had compiled a build from master on 2/15 and that was missing the mktime() and localtime() functions, but the BCDDateTimeRegister seemed to be fixed.

**Comment by makermelissa** [comment]
Forgot to mention, Dan mentioned there was work being done on this in #1534.

**Comment by makermelissa** [comment]
Ok, now that I've successfully compiled the latest version of circuitpython, it appears the specific functionality I need is the mktime() and localtime() functions in the time package.

**Comment by nickzoic** [comment]
G'day Melissa!  PR #1534 did not turn out as well as I'd hoped but hopefully the PR #1736 should address this ...

**Comment by nickzoic** [comment]
G'day @makermelissa #1736 is merged & I think it works for my very small test case, can you confirm that this works okay for you now?

**Comment by makermelissa** [comment]
Tested and it works great! Thanks @nickzoic.
