### ISSUE TITLE
Improve rtc documentation

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#1563]
There should be a simple example in the doc, and `rtc.RTC datetime` should say it takes a `struct_time`, etc.

**Comment by nickzoic** [comment]
Yeah, it is a bit obscure.  There's sample code in PR #1534 ... the stuff to update is the `\\|` stuff in `shared-bindings/rtc/__init__.c`, right? I probably should have done that as part of #1534 already ...

**Comment by tannewt** [comment]
Yup, `\\|` lines are filtered out and treated as an rst file.
