### ISSUE TITLE
trinket_m0 analogout fails after soft reset

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#1565]
The following test script will execute after a hard RESET, but fails with an I/O Error after a soft reboot

test.py
```
from analogio import *
from board import *
aout = AnalogOut(D1)
```

```
HARD RESET
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.

Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 4.0.0-beta.2-79-gfd3e9ce2f on 2019-02-17; Adafruit Trinket M0 with samd21e18
>>> import test
>>> 
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.



Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 4.0.0-beta.2-79-gfd3e9ce2f on 2019-02-17; Adafruit Trinket M0 with samd21e18
>>> import test
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "test.py", line 3, in <module>
OSError: [Errno 5] Input/output error
>>> 

```

**Comment by ladyada** [comment]
are you saving with Mu?

**Comment by makermelissa** [comment]
Jerry, I and iraytrace (on discord) all experienced this with a fresh build off master on CP. I personally saved using Mu, and I think the others did as well.

**Comment by jerryneedell** [comment]
I was not using Mu. Just running from REPL And typing control-d to reboot. I was not using code.py. Just test.py.

**Comment by ladyada** [comment]
ok yeah i have seen this lately but i thought it was related to save failing. i noticed that if i opened code.py in Mu and saved it (maybe changing a char and deleting) then it would magically work, or maybe its unreleated
