### ISSUE TITLE
Connection dropping with BLE Connect app when printing mobile data streams

### ISSUE THREAD

**Issue by kattni** [adafruit/circuitpython#1568]
Feather nRF52840 and the Adafruit Bluefruit LE Connect application used. Android version.

Here is the process.
- I have my code.py running to print Accel/Gyro/Magnet/Quat packets. The code runs fine while it’s waiting to connect.
- I connect using the Bluefruit app. Connects fine. I go to the controller, and enable each of the four data streams.
- The code starts printing the data streams to the serial console, but it prints them at weird inconsistent intervals. (As in, they do not print in order e.g. 1,2,3,4,1,2,3,4. It's more 1,1,2,1,1,3,4,2,4,2,1,1,2,1,1,1,1,2,1,4 etc.)
- After about 15-60 seconds, the serial console stops printing anything. The app continues streaming apparently.
- I cannot at this point use ctrl+c/ctrl+d to do anything, I Couldn’t even terminate the screen session successfully - it let me get to where it should terminate, but the disconnect dialogue line stayed at the bottom of my terminal “are you sure you want to disconnect? y/n”. I tried to connect to the board using `screen` in another window, and it let me, indicating that it had in fact terminated the previous session. I was unable to use ctrl+c/d in this session as well.
- In the meantime, I edited code.py to prepare for the next test run. Eventually, PyCharm told me it couldn’t save the changes because it lost connection and CIRCUITPY ejected from my computer.
- I had to physically reset the board and CIRCUITPY showed up again.

I can reproduce this every time I try. I tried `print`ing 2 streams at a time, it seems to stay connected longer, but eventually crashes in the same way. It doesn't seem to be specific to a particular data stream.

**Comment by dhalbert** [comment]
Partly fixed by https://github.com/adafruit/Adafruit_CircuitPython_BluefruitConnect/pull/10, but there's still a hard fault sometimes on the CircuitPython side. Still debugging that.
