### ISSUE TITLE
displayio - Change backlight freq to 50KHz instead of 5KHz

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#1571]
`pwmout_result_t result = common_hal_pulseio_pwmout_construct(&self->backlight_pwm, backlight_pin, 0, 5000, false);`

in Display.c should be changed to 50000, as 5KHz is within hearing range and if you PWM the pyportal backlight you can hear a squeeking noise :)

**Comment by ladyada** [comment]
(i can submit a PR once https://github.com/adafruit/circuitpython/pull/1552 is merged since that's what im working in)

**Comment by tannewt** [comment]
@ladyada want to PR this or should I?

**Comment by ladyada** [comment]
if you dont mind doing it, im going to try to focus on testing PR's with the time i have today

**Comment by tannewt** [comment]
kk, on it.
