### ISSUE TITLE
ctrl-d not running main.py

### ISSUE THREAD

**Issue by TG-Techie** [adafruit/circuitpython#1578]
Adafruit CircuitPython 4.0.0-beta.2-97-g0dc260058 on 2019-02-20; Adafruit PyPortal with samd51j20

it only runs main when main is saved

**Comment by tannewt** [comment]
More details please. When are you typing ctrl-d? If main is running you'll need to ctrl-c then ctrl-d.

**Comment by TG-Techie** [comment]
consistently when in the repl

**Comment by dhalbert** [comment]
This is probably fixed by the filesystem flush fixes.
