### ISSUE TITLE
Adafruit Feather M0 Bluefruit LE releases?

### ISSUE THREAD

**Issue by conchyliculture** [adafruit/circuitpython#1583]
Hi,
README.rst says the [Adafruit Feather M0 Bluefruit LE](https://www.adafruit.com/product/2995) is part of the supported boards, though I can't find any .u2f nor .bin files in the release (so I can't follow the install procedure [here](https://learn.adafruit.com/welcome-to-circuitpython/non-uf2-installation
).
Do you have documentation on how to build circuitpython.bin file myself?
Is the board going to be officially supported soon?

Thanks!

**Comment by jerryneedell** [comment]
Use the release for the M0 adalogger. It has pin D8 defined and is needed as the SPI chip select.

**Comment by jerryneedell** [comment]
More info here https://learn.adafruit.com/munny-lamp/code-with-circuitpython
