### ISSUE TITLE
`displayio` - have available property for width and height

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#1588]
realized while trying to center an image we don't have a way to 'ask' the `board.DISPLAY` what we are :)
- `width`
- `height`
- `color_depth`

from initizer here: https://circuitpython.readthedocs.io/en/latest/shared-bindings/displayio/Display.html

no rush from me - but i can see it coming in handy when people have various displays!

**Comment by dhalbert** [comment]
Fixed by #1601.
