### ISSUE TITLE
Add ESP32 support

### ISSUE THREAD

**Issue by water5** [adafruit/circuitpython#1629]

**Comment by dhalbert** [comment]
There is no native build for ESP32. However, we have a good library that supports using the ESP32 as a co-processor: https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI. This library is used for the PyPortal.

Using the ESP32 as a co-processor is advantageous in several ways: we don't need to port CircuitPython itself to the ESP32, which is a major task; we can substitute another Wifi-capable co-processor if another good one comes along, and having another core running the network code improves performance and removes potential concurrency issues.

**Comment by microDev1** [comment]
CircuitPython just got a `BLE` workflow, so `esp32` support is now possible.

**Comment by Neradoc** [comment]
The ESP32 is supported now via the Web Workflow.
I think we can close this issue.
