### ISSUE TITLE
neopixel_write broken?

### ISSUE THREAD

**Issue by mindforger** [adafruit/circuitpython#163]
i just updated to 1.0.0 RC4 and wanted to take some measureing for power consumption ... but i am unable to turn off the status LED

>import board
import neopixel_write
data = bytearray([0,0,0])
neopixel_write.neopixel_write(board.D8, data)

it is just changing from green to white and then blinks blueish until it repeats

----

i am getting the feeling the documentation is straight up misleading ... can i please have an working (and tested) example code on how to use the neopixel_write please? internet and adafruit page are inconclusive on neopixel_write with either (pin, buf) or (pin, buf, is800kHz) or (pin, buf, sizeInBytes)

**Comment by tannewt** [comment]
That's indicating an error. You have a typo with baord instead of board.

**Comment by mindforger** [comment]
i did not copy that, i had a typo while writing the issue, this is NOT the issue
if you read my edited post i need an working example, because the documentation is very inconclusive on how to use the command and it's signature

**Comment by mindforger** [comment]
yeah i just noticed you answered via email, so you were not able to read it, the used code is absolutely fine, i edited it line for line, only the neopixel_write always fails!

**Comment by tannewt** [comment]
I'll take a look at providing better docs and example later today. What docs are you currently looking at? I expect most people to use the [NeoPixel library](https://github.com/adafruit/Adafruit_CircuitPython_NeoPixel) instead of `neopixel_write` directly.

**Comment by mindforger** [comment]
I tried that one and it failed right at the last line call to neopixel_write

**Comment by tannewt** [comment]
You tried the library and it failed? Please post your code.

I also put an example here: https://circuitpython.readthedocs.io/en/stable/shared-bindings/neopixel_write/__init__.html

**Comment by jerryneedell** [comment]
Scott- I tried you example on an M0 Express - 2 issues 
I think the OUTPUT has t be Upper Case
Then the last line failed
This was with 1.0.0.rc4-1  adn the lastest librry bundle 1.0.0-rc2 release
Did I miss an update?

>>> import board
>>> import neopixel_write
>>> import digitalio
>>> pin = digitalio.DigitalInOut(board.NEOPIXEL)
>>> pin.direction = digitalio.Direction.OUTPUT
>>> pixel_off = bytearray([0, 0, 0])
>>> neopixel_write(pin, pixel_off)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'module' object is not callable

- Jerry

**Comment by tannewt** [comment]
Yeah, I thought I had fixed that. It should be `neopixel_write.neopixel_write(pin, pixel_off)`

**Comment by jerryneedell** [comment]
Cool! That works!

**Comment by jerryneedell** [comment]
And it does have to be:
pin.direction = digitalio.Direction.OUTPUT
correct?

**Comment by tannewt** [comment]
yeah, I don't know why thats not fixed either

**Comment by tannewt** [comment]
Not saving in my editor would do it. *groan*

**Comment by mindforger** [comment]
oh come on, i need to set the direction of the pin before using it and that is why it stopps running XD
i thought the syntax was wrong in some way

now everything works just fine, thank you

**Comment by tannewt** [comment]
@mindforger it defaults to input. Thats one reason why using the neopixel library is easier. :-)

**Comment by mindforger** [comment]
@tannewt i must have used a bit different version of the neopixel lib but the one you linked won't even import without green -> yellow(blueish when i use neopixel.py instead of neopixel.txt) -> 5x blueish
>from neopixel import *

[neopixel.txt](https://github.com/adafruit/circuitpython/files/1144137/neopixel.txt)

**Comment by tannewt** [comment]
So are you all set?

**Comment by mindforger** [comment]
well i am in a learning process to find all the hidden details i have to look out for when not using an dedicated IDE ... i am spoiled ... maybe i should return back to writing stuff in a notepad and compile it by hand for a bit basic practise again
