### ISSUE TITLE
Enable the SWD/SWC debugging pins to be used as normal pins when not debugging

### ISSUE THREAD

**Issue by deshipu** [adafruit/circuitpython#1633]
We could use the PA30 and PA31 pins as normal GPIO pins (and also SPI and I2C and so on) in CP3, however in CP4 they are always busy when we try to use them. It would be great if we could use them, even if that was optional only for some boards and disabled debugging entirely.

**Comment by sommersoft** [comment]
Just linking an approach I mentioned in the previous "force board into safe mode" issue. Will gather/expand thoughts regarding this later.

https://github.com/adafruit/circuitpython/issues/990#issuecomment-403130037

**Comment by tannewt** [comment]
@sommersoft DBGPRES is perfect! Thanks!

**Comment by sommersoft** [comment]
👍 
_I totally forgot to "gather/expand later"_ 😄
