### ISSUE TITLE
Add board.SPEAKER alias for PyPortal

### ISSUE THREAD

**Issue by caternuson** [adafruit/circuitpython#1634]
This is simply to make things a little easier by being more consistent. Similar to naming the [battery voltage sense pin](https://github.com/adafruit/circuitpython/issues/1149). On the PyPortal, the two pins associated with the speaker are currently named:

- `board.SPEAKER_ENABLE`
- `board.AUDIO_OUT`

On the CPX and the Hallowing, the second one is called `board.SPEAKER`. So suggest either renaming or adding an alias for that as well.

**Comment by ladyada** [comment]
aliasing board.SPEAKER sounds good - wanna try the PR? :)

**Comment by caternuson** [comment]
Sure #1635

**Comment by dhalbert** [comment]
Fixed by #1635.
