### ISSUE TITLE
Idea: hide "private" names from tab completion

### ISSUE THREAD

**Issue by deshipu** [adafruit/circuitpython#1636]
This is just an idea for discussion: what if we filtered the names considered by auto-completion to filter out all names that start with the underscore, *unless* the user has already typed an underscore? The rationale behind this is that those usually are implementation details of the module/class in question, and the chance the users actually want to call them from outside are small.

**Comment by tannewt** [comment]
Makes sense to me. I thought we tab completed with the entered prefix but I haven't looked into it.

**Comment by deshipu** [comment]
We do. This is only for the case when the prefix is empty (as right after a period, for example).

**Comment by katlings** [comment]
This sounds fun; I'm going to tackle it for PyCon 2019 sprints!

**Comment by tannewt** [comment]
Done by @katlings with #1850!
