### ISSUE TITLE
SAMD Pinout tables cutoff in docs

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#166]
Work some CSS magic on ReadTheDocs so that the horizontal scroll bar comes back.

**Comment by dhalbert** [comment]
Issue mentioned here: https://github.com/rtfd/sphinx_rtd_theme/issues/117 and here: http://rackerlabs.github.io/docs-rackspace/tools/rtd-tables.html with supposed fixes. What's weird is that the first link seems to have a fix that was committed. Many references to related issues in first link.
