### ISSUE TITLE
add board PyCon Gemma 2018 to builds

### ISSUE THREAD

**Issue by ptorrone** [adafruit/circuitpython#1664]
for circuitpython boards with different silk' on the board, let's add it as a build so it shows up on: https://circuitpython.org/downloads

pycon 2018 gemma info is here:
https://github.com/adafruit/CircuitPython_Badge_README/tree/master/final_versions/PYCON_2018

(photos, etc).

**Comment by tannewt** [comment]
Closing in favor of #1673 which is one issue for the tooling and can include initial boards to do.
