### ISSUE TITLE
add Digi-Key + Adafruit PyCon 2019 board to builds

### ISSUE THREAD

**Issue by ptorrone** [adafruit/circuitpython#1666]
for circuitpython boards with different silk' on the board, let's add it as a build so it shows up on: https://circuitpython.org/downloads

add Digi-Key + Adafruit PyCon 2019 board to builds, can be a placeholder - images to follow soon and we'll also link to:
https://github.com/adafruit/PyCon2019

**Comment by tannewt** [comment]
Closing in favor of #1673 which is one issue for the tooling and can include initial boards to do.
