### ISSUE TITLE
update express starter guides @ 1.0

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#167]
its a todo for scott! plz update this guide to match 1.0 
https://learn.adafruit.com/admin/guides/1615/editor/9140
this is shared between both feather & metro. thx :)

**Comment by tannewt** [comment]
Will do!

**Comment by tannewt** [comment]
Updated the guide by using `led.direction = digitalio.Direction.OUTPUT` instead of `switch_to_output()`.
