### ISSUE TITLE
displayio.Palette not checking color_count

### ISSUE THREAD

**Issue by caternuson** [adafruit/circuitpython#1671]
Can instantiate a `Palette` with a `color_count` that exceeds max (255?) without getting any errors. But then it errors out later.
```python
Adafruit CircuitPython 4.0.0-beta.5 on 2019-03-17; Adafruit PyPortal with samd51j20
>>> from displayio import Palette
>>> p1 = Palette(255)
>>> p2 = Palette(256)
>>> p1[0] = 0xFF0000
>>> p2[0] = 0xFF0000
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: Palette index out of range
>>> 
```

**Comment by deshipu** [comment]
This is strange, because I don't see anything that would limit the size of the palette — ``uint32_t`` is used as the index type everywhere.

**Comment by deshipu** [comment]
Ah, I see, ``color_count`` is ``uint8_t`` in the ``displayio_palette_t`` struct.
