### ISSUE TITLE
Add additional builds for special versions of boards

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#1673]
We have two special versions of CPX coming and we'd like separate downloads and download pages on the website for them. We don't need them to be unique builds though. So, we can copy the original version with a different name. It does need to work with build board info too.

We need to do this for:

- [ ] PyCon Gemma 2018
- [ ] DigiKey + Adafruit PyCon 2019 CircuitPlayground
- [ ] 4-H Green CircuitPlayground

**Comment by deshipu** [comment]
I would love to do that for the PewPew 10.3 (the big one) as well, if possible.
