### ISSUE TITLE
String internationalization for Polish

### ISSUE THREAD

**Issue by deshipu** [adafruit/circuitpython#1690]
I will work on that.

**Comment by dhalbert** [comment]
Do you want to try to get this done for 4.0 or 4.x (later)?

**Comment by deshipu** [comment]
I'm not really aiming at any particular deadline — I'm working on it as I have time. Currently I'm at about 40%, so my guess is that I should finish by the end of this week, but I can't guarantee it.

**Comment by dhalbert** [comment]
PR #1725 from @deshipu merged to complete this for 4.0.
