### ISSUE TITLE
ESP8266 messages still present in translations

### ISSUE THREAD

**Issue by deshipu** [adafruit/circuitpython#1702]
I have noticed that the translation template still contains all the messages for functions related to WiFi configuration on the ESP8266. Since the support for ESP8266 is getting removed in this version, perhaps we should also remove the messages, so that the translators don't have to do unnecessary work, and to save space?

**Comment by dhalbert** [comment]
We should remove the esp8266 port from the translation files. However, the strings don't show up at all in anything that's built, because they're port-specific and not included in non-esp8266 ports. So it appears it's a waste of human time, but not flash space.

**Comment by dhalbert** [comment]
Fixed by #1716.
