### ISSUE TITLE
displayio.Group.sort()

### ISSUE THREAD

**Issue by deshipu** [adafruit/circuitpython#1704]
It would be nice to have it, to be able to, for example, sort the sprites by their ``y`` coordinate.

**Comment by tannewt** [comment]
Note that this is `.sort` so it happens in place. `sorted(group)` would create a new object.

@deshipu Does this need to be native? You could make a Group subclass to do it instead.

**Comment by deshipu** [comment]
It's a bit difficult to do fast sorting when all you have is access to individual elements...

How about a different approach — instead of having Group as the container, have Group.items that would be a regular Python list — then you get all the list methods for free, including slices and sort.

**Comment by tannewt** [comment]
The challenging bit of C sorting is that the key function will likely be python still. (How would you choose what to sort by otherwise?)

I've thought about making Group more closely tied to list post-4.0.0. I don't like static allocation it does now.

**Comment by deshipu** [comment]
I could keep a helper list on the side, sorting it and updating the group with it, but currently that would involve removing all elements from the group one-by-one, and then re-adding them one-by-one from the list. Slice assignment could be great for this (``group[:] = sorted(group)``) I suppose.
