### ISSUE TITLE
displayio.Group rotation and flipping

### ISSUE THREAD

**Issue by deshipu** [adafruit/circuitpython#1705]
It would be nice to be able to rotate the Group in 90° increments, and to be able to mirror and vertically flip it. One way of implementing it would be adding an ``orientation`` attribute, with eight possible values. One bit would control horizontal flip, one bit — vertical, and last bit would control swapping of the ``x`` and ``y`` coordinates (diagonal flip). This way we can have all possible orientations.

**Comment by tannewt** [comment]
Would you prefer Group over TileGrid support?

**Comment by deshipu** [comment]
I have no preference, both work for me, and I suppose ``TileGrid`` is a little easier to implement, but having it on ``Group`` would be more consistent given that groups already have coordinate offsets on them. Come to think of it, to have it on groups you would need to have it on tiles first, so maybe we can start with that, and add it to the group later if it is needed.

For me the use case is to save on the amount of graphics stored in memory for things that rotate or are animated by mirroring (most walking animations in my games, etc.)

**Comment by tannewt** [comment]
Totally. I plan on adding them. It's just a question of where. Starting with TileGrid makes sense to me.

One challenge will be OnDiskBitmap because reads in one direction are waaaaaayyyy faster than the other.
