### ISSUE TITLE
Consider using SdFAT library instead of Python modules for SD card

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#1717]
@ladyada says this code is solid: https://github.com/greiman/SdFat

**Comment by NightSkySK** [comment]
SdFAT library is excellent, I'm looking forward to having it on CircuitPython. One of the features most expected is initialize at the highest speed supported by the board which can be up to 50 MHz.

**Comment by jepler** [comment]
We improved SD card performance when we added the sdioio & sdcardio modules in 6.0.
