### ISSUE TITLE
displayio.Bitmap wrapping after certain displayio.Palette size

### ISSUE THREAD

**Issue by caternuson** [adafruit/circuitpython#1744]
Tested on a PyPortal with:
```
Adafruit CircuitPython 4.0.0-beta.6 on 2019-03-30; Adafruit PyPortal with samd51j20
```
Test code:
```python
import board
import displayio

COLORS = 16

palette = displayio.Palette(COLORS)
palette[0] = 0x000000
palette[1] = 0xFFFFFF

bitmap = displayio.Bitmap(320, 240, COLORS)
bitmap[(100, 100)] = 1
bitmap[(100, 101)] = 1
bitmap[(101, 100)] = 1
bitmap[(101, 101)] = 1

tile_grid = displayio.TileGrid(bitmap, pixel_shader=palette)
group = displayio.Group()
group.append(tile_grid)
board.DISPLAY.show(group)
board.DISPLAY.refresh_soon()
```
run the above get the expected little square:
![color16](https://user-images.githubusercontent.com/8755041/55532165-bcbf9780-5661-11e9-8a6f-821f054dbedf.jpg)
change this line to:
```python
COLORS = 17
```
run again and some kind of repetition happens:
![color17](https://user-images.githubusercontent.com/8755041/55532198-dbbe2980-5661-11e9-932b-e2907b1240ac.jpg)

**Comment by makermelissa** [comment]
Oh, I thought it was just me.

**Comment by caternuson** [comment]
FYI - The mentioning of `displayio.Palette` is a red herring. It's simply triggered by the `value_count` parameter when creating the Bitmap instance. Anything above `16` creates the behavior.

Also, direct indexing vs. using (x,y) tuple does not matter.

**Comment by caternuson** [comment]
Nice! Thanks for the fix. And now my hacks to `adafruit_imageload` seem to be working better also :)
![flowers](https://user-images.githubusercontent.com/8755041/55640794-2da9a100-5781-11e9-9544-a93555fd9a73.jpg)
