### ISSUE TITLE
Allow displayio to treat all SPI parameters as commands

### ISSUE THREAD

**Issue by makermelissa** [adafruit/circuitpython#1750]
The SSD1331 likes everything sent as commands. I could format the INIT data as all commands, but that gets lengthy, so it would be nice to just pass a parameter to allow this to happen automatically. Additionally all of the boundary parameters need to be treated as commands too.

**Comment by deshipu** [comment]
I think all displays want parameters as commands. Data is strictly only for pixel data.

**Comment by tannewt** [comment]
I checked the ST7735R datasheet and it says parameters are data. (See the D/C column below.)

![Screen Shot 2019-04-05 at 11 16 19 AM](https://user-images.githubusercontent.com/52649/55648156-6737d780-5794-11e9-8628-1ea81b74ec02.png)

**Comment by deshipu** [comment]
You are right, I tested it with DC=0 and it doesn't work on that display then. Sorry for the assumption.
