### ISSUE TITLE
Update to ASF4 and add SAMD51 support.

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#178]
SAMD51 datasheet: http://ww1.microchip.com/downloads/en/DeviceDoc/60001507A.pdf

**Comment by ladyada** [comment]
:D

**Comment by tannewt** [comment]
My work in progress is here: https://github.com/adafruit/circuitpython/tree/asf4

It is very early and it doesn't even compile. However, I figured I'd get it out there in case someone . can't wait to work on it.

Please coordinate with me if you do because I will rebase the asf4 branch as master progresses and the branch starts to actually work.

**Comment by tannewt** [comment]
I'm going to close this in favor of separate issues to make it easier to assign different tasks.
