### ISSUE TITLE
Turn on zlib for larger builds

### ISSUE THREAD

**Issue by rdagger** [adafruit/circuitpython#1789]
The docs indicate zlib support:  https://circuitpython.readthedocs.io/en/latest/docs/library/uzlib.html

However, it doesn't look like it's implemented for the nRF52840.  I tried the Feather nRF52840 Express and the PCA10059.

I'm trying to write a CircuitPython Png decoder and this would be very helpful.

**Comment by dhalbert** [comment]
`uzlib` is not turned on for any CircuitPython ports. It might be nice to have if it's not too big. It should be moved to shared-bindings and shared-module.

**Comment by dhalbert** [comment]
See PR #1274

**Comment by dhalbert** [comment]
Partly addressed by #6069. See #6284 for further followup.
