### ISSUE TITLE
Crash into the HardFault_Handler.

### ISSUE THREAD

**Issue by stephenvowell** [adafruit/circuitpython#1826]
Using CircuitPython 4.0.0-rc.1

You are running in safe mode which means something unanticipated happened.
Looks like our core CircuitPython code crashed hard. Whoops!
Please file an issue at https://github.com/adafruit/circuitpython/issues
 with the contents of your CIRCUITPY drive and this message:
Crash into the HardFault_Handler.

**Comment by deshipu** [comment]
Thank you for the crash report. Can you attach the contents of your CIRCUITPY drive too, please?

**Comment by stephenvowell** [comment]
[Archive.zip](https://github.com/adafruit/circuitpython/files/3112245/Archive.zip)
I recreated the error

**Comment by tannewt** [comment]
@stephenvowell what board was it running on?

**Comment by tannewt** [comment]
Ah, I see the boot_out.txt says Metro M0. I'm unable to reproduce it. Please reply if it still happens on the latest S3 build and I'll reopen.
