### ISSUE TITLE
Failer to boot into Safe Mode

### ISSUE THREAD

**Issue by hexthat** [adafruit/circuitpython#1831]
```python
import microcontroller
microcontroller.on_next_reset(microcontroller.RunMode.BOOTLOADER)
microcontroller.reset()
```
works as expected but
```python
import microcontroller
microcontroller.on_next_reset(microcontroller.RunMode.SAFE_MODE)
microcontroller.reset()
```

Does not enter safe mode. I was going to use it like "else statement" boots to safe_mode stopping code.

**Comment by tannewt** [comment]
What board are you using?

**Comment by hexthat** [comment]
Tested on  Feather_m4_express and hallowing_m0_express, neither goes into safe mode
