### ISSUE TITLE
Add a way to do a reload from code

### ISSUE THREAD

**Issue by deshipu** [adafruit/circuitpython#184]
Sometimes the code might need to do a reset, for example, as a way of recovering from an unexpected exception in a long-running program, or as a way of clearing the state of the device to load a new subprogram.

**Comment by mmabey** [comment]
@deshipu I don't know if these are the kind of solutions you're looking for, but MicroPython has a [`reset()`](http://docs.micropython.org/en/latest/esp8266/library/machine.html#machine.reset) function as well as something called a [watchdog timer](http://docs.micropython.org/en/latest/esp8266/library/machine.WDT.html). Perhaps @tannewt can comment on the likelihood that one or both of these could be ported over to CP.

**Comment by Andon-A** [comment]
This would be super-useful in a few of the examples that I am planning for #345

**Comment by tannewt** [comment]
You mean to reload the program right? A reset would do a fully reinitialization of the microcontroller and stop USB when available.

**Comment by deshipu** [comment]
I mean the same thing that ctrl+d does in REPL.

**Comment by tannewt** [comment]
OK, I call that reload.

The tricky part here is that we want to exit the existing code and immediately re-run it. Normally, we'd go into our wait state with the status led fading in and out.

**Comment by caternuson** [comment]
It'd also be useful if a file to run on reset could be specified. This would let people use this in main.py to specify a different file to run and eliminate the need to rename. Or it could be used in a more complex way like a menu system to allow selecting one of the other .py files to be run programmatically.

**Comment by tannewt** [comment]
@deshipu thats a great idea! Mind filing a separate issue for it?

**Comment by rhooper** [comment]
I'm going to have a look at this.

**Comment by tannewt** [comment]
Fixed by @rhooper in #838. Thank you!
