### ISSUE TITLE
Feather M4 does soft reboot when files on it are being edited while a file is also running

### ISSUE THREAD

**Issue by evaherrada** [adafruit/circuitpython#1862]
I don't think this is an issue that needs to be fixed, but I think that it would be worth adding something to some docs somewhere telling people to edit the code locally and then copy it across to the board. I was using vim, and I think the creation and modification of .swp files is partly to blame.

**Comment by kevinjwalters** [comment]
Reading a file (on Windows and possibly other host o/s) can also trigger a reload: https://github.com/adafruit/circuitpython/issues/1830#issuecomment-487023904
