### ISSUE TITLE
Support `microcontroller.on_next_reset` on nrf

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#1868]

**Comment by jepler** [comment]
Addressed by #1996.

**Comment by jepler** [comment]
@tannewt however, that fix was applied only to the master branch.  Do you want me to reopen this and create a version to apply to 4.x?

**Comment by tannewt** [comment]
nah, I have a feeling most nrf folks will skip straight to 5.x to get all the new ble goodness.
