### ISSUE TITLE
digitialio -document how to unset pullup/down

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#187]
https://circuitpython.readthedocs.io/en/latest/shared-bindings/digitalio/Pull.html

'None' is valid too! :)

**Comment by kevinjwalters** [comment]
[Adafruit Learn: CircuitPython Basics: Digital Inputs & Outputs: Digital Inputs](https://learn.adafruit.com/circuitpython-digital-inputs-and-outputs/digital-inputs) mentions `digitalio.Pull.NONE`. I put some feedback in as that does not exist and I'm not sure it ever has, doesn't appear in CP 2 docs.

**Comment by dhalbert** [comment]
> [Adafruit Learn: CircuitPython Basics: Digital Inputs & Outputs: Digital Inputs](https://learn.adafruit.com/circuitpython-digital-inputs-and-outputs/digital-inputs) mentions `digitalio.Pull.NONE`. I put some feedback in as that _does not exist_ and I'm not sure it ever has, it doesn't appear in CP 2 docs.

Fixed in the guide. Thanks for spotting this.
