### ISSUE TITLE
Sort filenames in .po translation files

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#1871]
`xgettext --add-location=file` does not sort the filenames: they seem to be in random order, which causes unnecessary diffs. We could post-process the files to sort the filenames.

I looked in the `gettext` [bug list](https://savannah.gnu.org/projects/gettext/) and don't see this mentioned in any open or closed bug.

**Comment by godlygeek** [comment]
Any chance this is just because we just pipe the output of `find` directly to `xargs xgettext` and `find` returns files in an arbitrary order?  Perhaps piping through `sort` in the middle would do it.

**Comment by tannewt** [comment]
It's worth a shot!

**Comment by dhalbert** [comment]
I was going to write an awk script or similar, but then discovered that the filenames could be split over multiple lines.

**Comment by tannewt** [comment]
I'm doing this. I think @godlygeek is right.

**Comment by smurfix** [comment]
Either that, or freeze PYTHONHASHSEED.

**Comment by tannewt** [comment]
@smurfix How does PYTHONHASHSEED fit into it?
