### ISSUE TITLE
Add multimedia keyboard support to HID devices

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#190]
Needed to support https://github.com/adafruit/Adafruit_CircuitPython_HID/issues/5.

**Comment by tannewt** [comment]
To do this we may need to allow for configurable USB descriptors.

**Comment by ladyada** [comment]
prereq: https://github.com/adafruit/circuitpython/issues/565

**Comment by tannewt** [comment]
This is done right @dhalbert ?

**Comment by dhalbert** [comment]
Yup.
