### ISSUE TITLE
[docs error] dispio rst param rendering

### ISSUE THREAD

**Issue by TG-Techie** [adafruit/circuitpython#1921]
In the docs for displayio the first parameter starts with the word or instead of `displayio.FourWire`
docs: https://circuitpython.readthedocs.io/en/4.x/shared-bindings/displayio/Display.html
source: https://github.com/adafruit/circuitpython/blob/aae7cb3eb0ba547b1253b4bf55488465915a9ce4/shared-bindings/displayio/Display.c#L81

**Comment by tannewt** [comment]
I think we need to split the type out of :param: and then define it with :type: I think. Example here: http://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#info-field-lists
