### ISSUE TITLE
wav sample_rate appears limited to less than 65536

### ISSUE THREAD

**Issue by kevinjwalters** [adafruit/circuitpython#1922]
I wanted to experiment with some non-audio sample playback and made some 8bit wavs to check playback. 64000 is ok but this one at 96000Hz plays slowly and inspecting `sample_rate` shows why:

```
>>> wave_file = open("Evillaugh.96000.8bit.mono.wav", "rb")
>>> wave = audioio.WaveFile(wave_file)
>>> wave.sample_rate
30464
>>> 30464+65536
96000
```

That's on 4.0.0-rc1 which happened to be on the CPX I was playing with. Also checked 4.0.1 which has same behaviour.

I had a very quick look and I saw a lot of 32bit values being used by args and variables I'm not sure where the 16bit 65536 limitation is coming from.

I'd also be interested in any bottlenecks I'll encounter as I try faster sample_rate. Will CPX be capable to playing 100000 or 350000 8bit (or 16bit?) samples per sec from a wav file on the built-in flash?

**Comment by C47D** [comment]
Appears to me it's because `sample_rate` is an `uint16_t` in the `audioio_wavefile_obj_t` type.

https://github.com/adafruit/circuitpython/blob/c5a4e19d6f76a09cba73149d5e3d4548da320899/shared-module/audioio/WaveFile.h#L34-L55

**Comment by kevinjwalters** [comment]
Thanks @C47D, I tested 4.1.0-beta.0 last night with an 80kHz sample and this now appears to work fine: https://www.youtube.com/watch?v=WME0PRTvCk8

**Comment by C47D** [comment]
Glad it worked, it does look beautiful, great music too. Is your project documented somewhere i would like to know more about it!

**Comment by kevinjwalters** [comment]
I'm still debugging and cleaning code up but will let you know when it's out on t'Internet.

**Comment by kevinjwalters** [comment]
Published last week: [Adafruit Learn: Making oscilloscope images with DACs](https://learn.adafruit.com/dac-oscilloscope-images)
