### ISSUE TITLE
Displayio / MiniTFTFeatherWing noise at left edge of screen

### ISSUE THREAD

**Issue by iraytrace** [adafruit/circuitpython#1923]
The following code:
```
     import time
     from adafruit_featherwing import minitft_featherwing
     minitft = minitft_featherwing.MiniTFTFeatherWing()
     print('hello')
     while True:
         pass
```
Produces the following image with noise on the left side:
![TFT_label_bug_2](https://user-images.githubusercontent.com/3651273/58879240-36e0bc80-86a3-11e9-9e52-5bfecab89642.gif)

This noise persists even if the display is more substantially over-written as in:

```
import time
import board
from adafruit_featherwing import minitft_featherwing
import displayio
import terminalio
from adafruit_display_text import label

minitft = minitft_featherwing.MiniTFTFeatherWing()

label_count = 5
labels = list()
group = displayio.Group(max_size=label_count, scale=1, x=0, y=0)
font = terminalio.FONT
f_width, f_height = font.get_bounding_box()

colors = [0xffffff, 0xb0b0b0, 0xffff00, 0xb0b0b0, 0x00d0d0]
for i in range(label_count):
    labels.append(label.Label(font, max_glyphs=37, color=colors[i], line_spacing=0.94))
    labels[-1].x = 5
    labels[-1].y = i * f_height + int(f_height*.5)
    labels[-1].text = 'line %d' % i
    group.append(labels[-1])

minitft.display.show(group)
while True:
    pass
```

Which produces:

![TFT_label_bug](https://user-images.githubusercontent.com/3651273/58879378-8b843780-86a3-11e9-8406-c4265968111d.gif)

**Comment by makermelissa** [comment]
Hi, which version of CircuitPython are you running this with? I tried it with 4.0.1 and it didn't produce this.

**Comment by makermelissa** [comment]
I see on the forum, you grabbed an s3 build. I'm going to try compiling CP with the latest master to see if I can get this to reproduce.

**Comment by makermelissa** [comment]
Ok, I was able to reproduce this with the latest build. It appears that the initial screen draw is not completely drawing everything.

**Comment by tannewt** [comment]
@makermelissa I can take a look at this. I changed a good amount of this code so I'm not surprised there are bugs.
