### ISSUE TITLE
Timer for nRF52840?

### ISSUE THREAD

**Issue by edwios** [adafruit/circuitpython#1954]
Instead of using a while True: loop, I would like to use Timer(,,,callback) to periodically trigger a callback function. The reason is, I want to reduce the power consumption as much as possible so that I can deploy, for example, a temperature sensor that can run on a CR2032 coin cell for months.

Is there any way to realise this?

Thanks!

**Comment by dhalbert** [comment]
We have no way currently to do this. Low-power sleep and the like are on our long-term feature list, but we are not.

(Closed in favor of #696.)
