### ISSUE TITLE
import multiterminal throws ImportError

### ISSUE THREAD

**Issue by iot49** [adafruit/circuitpython#1980]
```python
>>> import multiterminal

Traceback (most recent call last):
  File "<stdin>", line 9, in <module>
ImportError: no module named 'multiterminal'
```

I tried UNSUCCESSFULLY adding defines to circuitpy_mpconfig.mk.

```
ifndef CIRCUITPY_MULTITERMINAL
CIRCUITPY_MULTITERMINAL = 1
endif
CFLAGS += -DCIRCUITPY_MULTITERMINAL=$(CIRCUITPY_MULTITERMINAL)
```

and circuitpy_defns.mk

```
ifeq ($(CIRCUITPY_MULTITERMINAL),1)
SRC_PATTERNS += multiterminal/%
endif
```

**Comment by tannewt** [comment]
What are you trying to do? multiterminal was only ever implemented for ESP8266 which is no longer supported.

**Comment by iot49** [comment]
I’m trying to catch <stdout> and <stdin> (specifically while executing
“exec()”).

(Assigning sys.stdout is not supported in micro/circuitpython).

Bernhard

**Comment by iot49** [comment]
I solved the "problem" with a handler function in `supervisor/shared/micropython.c` that, when set, is called with whatever is written to serial. Handles output only and is much simpler than multiterminal.

Contact me if interested.
