### ISSUE TITLE
UART receiver_buffer_size

### ISSUE THREAD

**Issue by iot49** [adafruit/circuitpython#1982]
`shared-bindings/busio/UART.h` declares the type of `receiver_buffer_size` as `uint8_t`. This prevents defining buffers >255 bytes and results in strange error messages (e.g. for 256, "invalid size"). 

Changing the type to `uint16_t` (same as in `py/ringbuf.h`) fixes this (corresponding change required also in common-hal).

**Comment by tannewt** [comment]
@iot49 mind filing a PR for this fix?

**Comment by iot49** [comment]
Done.

**Comment by ATMakersBill** [comment]
Did this get merged in?  I don't see the PR (but I'm not a Git expert)

**Comment by ATMakersBill** [comment]
Nevermind - I updated to 4.1 and it fixed it - thank you!
