### ISSUE TITLE
Request VID/PID for SnekBoard

### ISSUE THREAD

**Issue by keith-packard** [adafruit/circuitpython#2019]
Pull request #2018 adds support for SnekBoard, which is a SAMD21G18A board with 9V motor controllers for use with Lego Power Functions motors and sensors. I'll need a 'real' USB VID/PID before this pull request should be merged.

**Comment by ladyada** [comment]
Here ya go!
```
Keith P Snek      VID 0x239A    PID 0x004D  # bootloader
                                PID 0x804D  # arduino
                                PID 0x804E  # circuitpython
```

**Comment by keith-packard** [comment]
Thanks so much! I've updated the code, and also submitted a pull request for the uf2 bootloader project https://github.com/adafruit/uf2-samdx1/pull/78.
