### ISSUE TITLE
Enable binascii on SAMD port

### ISSUE THREAD

**Issue by brentru** [adafruit/circuitpython#2022]
Binascii is available in WiFi ports (ESP/NRF), but not SAMD ports. 
 
 Specifically, I'm interested in the `a2b_base64` (https://circuitpython.readthedocs.io/en/latest/docs/library/binascii.html#binascii.a2b_base64) and `b2a_base64`(https://circuitpython.readthedocs.io/en/latest/docs/library/binascii.html#binascii.a2b_base64) methods from the binascii API for a RSA implementation I'm working on.

**Comment by tannewt** [comment]
We may be able to do M4 but I doubt it'll fit in M0.

**Comment by ladyada** [comment]
m4 only is fine
