### ISSUE TITLE
Add .hex() method to bytes objects

### ISSUE THREAD

**Issue by brentru** [adafruit/circuitpython#2024]
The CPython bytes.hex() property does not exist for CircuitPython bytes objects:

```
>>> b'\xf0\xf1\xf2'.hex()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'bytes' object has no attribute 'hex'
```

https://docs.python.org/3/library/stdtypes.html#bytes.hex

**Comment by dhalbert** [comment]
As a workaround, you can use `binascii.hexlify()`, I think.

**Comment by brentru** [comment]
@dhalbert  `binascii` does not exist within samd ports (https://github.com/adafruit/circuitpython/issues/2022). Hexlify also returns a bytes object, .hex returns a string object.

**Comment by tannewt** [comment]
@brentru I corrected the terminology here. `.hex()` is a method because it is a function on an object. Properties are used like variables without parens.

**Comment by theacodes** [comment]
Here's CPython's implementation: https://github.com/python/cpython/blob/master/Python/pystrhex.c

**Comment by dhalbert** [comment]
This now exists, not sure when it showed up:
```py
Adafruit CircuitPython 9.0.0-alpha.2 on 2023-10-27; Adafruit Metro M4 Express with samd51j19
>>> b'abc'.hex()
'616263'
```
