### ISSUE TITLE
Polish up native api docs so that stubs are complete

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#2041]
`make stubs` generates .pyi files that can be used in editors like VS code to provide helpful hints. The rST docs need to be fixed up so that the stubs include things like valid types.

**Comment by tannewt** [comment]
PR that added stubs: https://github.com/adafruit/circuitpython/pull/1915

Example PR that fixed up some comments: https://github.com/adafruit/circuitpython/pull/1920

**Comment by sw23** [comment]
@tannewt Can I pick up this work item for #hacktoberfest?  I looked at the code and have a good handle on what needs to be done.  Thanks!

**Comment by tannewt** [comment]
@sw23 Totally! Feel free to submit PRs to improve the type stubs.

**Comment by dhalbert** [comment]
@dherrada Is this kind of all done?

**Comment by dherrada** [comment]
@dhalbert I think so, but @tannewt would know best

**Comment by tannewt** [comment]
I think so too. I suspect we'll get issues once more folks use them but we can have separate issues/PRs for those. Thanks @dherrada for going over it all.
