### ISSUE TITLE
Crash into the HardFault_Handler

### ISSUE THREAD

**Issue by reply2jh** [adafruit/circuitpython#2069]
This will cause the hardfault_handler to be called

import time
x = time.time()
x = x*1.0
y = time.localtime(x)

**Comment by jepler** [comment]
I can confirm this on the following software/hardware combination: `Adafruit CircuitPython 5.0.0-alpha.0-189-g85d739847-dirty on 2019-08-17; Adafruit PyPortal with samd51j20`

**Comment by jepler** [comment]
`time.localtime(1.0)` seems to be enough to cause the fault.
