### ISSUE TITLE
PyRuler still not enumerating on MacOS Mojave

### ISSUE THREAD

**Issue by siddacious** [adafruit/circuitpython#2107]
Same issue as reported in #2064. Didn't fix itself.

**Comment by dhalbert** [comment]
What version are you running now? I was unable to reproduce on a Macbook with USB-C-to-USB-A adapter, running 10.14.6. And is this latest master or 5.0.0-alpha.1, or 4.1.0?

Does it work fine on other machines? Do you have another Mac to try it on?

**Comment by tannewt** [comment]
Also, are there any hubs between the Mac and the device?

**Comment by dhalbert** [comment]
@siddacious still true with latest CircuiPython Build?

**Comment by siddacious** [comment]
@dhalbert I opened up the other pyruler I bought at the same time as the other and it works fine; probably a hardware issue? I'm fine with closing, sorry for dragging my feet on this
