### ISSUE TITLE
Missing assets from 5.0.0 Alpha 1

### ISSUE THREAD

**Issue by makermelissa** [adafruit/circuitpython#2118]
It appears some assets are missing from the release such as the Metro M4 Express.

**Comment by tannewt** [comment]
Yup, we ran out of API quota. Will release today hopefully to validate that the new token fixes it.

In the meantime, they are available on S3: https://adafruit-circuit-python.s3.amazonaws.com/index.html?prefix=bin/metro_m4_express/en_US/

**Comment by makermelissa** [comment]
Perfect, thanks.

**Comment by tannewt** [comment]
Alpha 2 has all 904 assets so the token fix worked!

**Comment by ladyada** [comment]
nice work!
