### ISSUE TITLE
Trinket M0: No SPI pins in board

### ISSUE THREAD

**Issue by deshipu** [adafruit/circuitpython#213]
Trying to run any of the SPI examples, I get:
```
>>> spi = busio.SPI(clock=board.SCK, MOSI=board.MOSI, MISO=board.MISO)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'SCK'
```

Changing this to:

```
spi = busio.SPI(clock=board.D3, MOSI=board.D4, MISO=board.D2)
```
makes it work, but then I have to write board-specific code.

**Comment by tannewt** [comment]
How does it work when there is no chip select line? Isn't that usually used to signify transaction boundaries?

**Comment by deshipu** [comment]
No idea, honestly, but it works. It would be nice to have those pin names in the board module, though.

**Comment by tannewt** [comment]
I hesitate to add the pin names because most SPI devices won't work due to no pin for the chip select.

**Comment by deshipu** [comment]
Any pin can be specified as chip select, and it's the driver for the particular device that is responsible for toggling it.

**Comment by deshipu** [comment]
I really have no idea about how the chip select line is related to this issue at all.

**Comment by tannewt** [comment]
I was confusing the Gemma which has 3 GPIO with the Trinket which has enough for SPI. Pull request proposed with the names.
