### ISSUE TITLE
Meowbit support?

### ISSUE THREAD

**Issue by Mr-Coxall** [adafruit/circuitpython#2145]
Can the Meowbit be added to have CircuitPython support?
https://www.kittenbot.cc/collections/frontpage/products/meowbit-codable-console-for-microsoft-makecode-arcade

**Comment by tannewt** [comment]
Looks like it is an STM32F401. We're currently targeting the F411, F412 and F405 but may be able to support the F401 in the longer term.

**Comment by hierophect** [comment]
The F401 is very similar to the F411. It may be trivially simple to add. However, since I don't have a viable dev board for it on hand, I think this is probably best scheduled after we have modules like displayio up and running.

**Comment by ladyada** [comment]
@hierophect feel free to pick up a https://www.adafruit.com/product/4324 on your travels :)
