### ISSUE TITLE
Fix warnings in sphinx documentation build

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#215]
There are unconnected pages, ambiguous references, and warnings about the new `templates/replace.inc` file, which came in with MPy v1.9.2

**Comment by willingc** [comment]
@dhalbert I noticed that too. I've been refactoring the docs since the build is a bit odd as it stands. Trying to restructure so the docs will be more maintainable over time. Feel free to tackle yourself or I'm happy to take this on.

**Comment by dhalbert** [comment]
@willingc If you would like to that would be great! Thanks! It would also be nice to suppress the irrelevant stuff (e.g., `pyboard` module documentation).

**Comment by tannewt** [comment]
Thanks for doing this! One thing I changed from MicroPython is defaulting the role to `any` this means more references are missing but some are connected and are more useful.
