### ISSUE TITLE
nRF52840 analog voltage returning low

### ISSUE THREAD

**Issue by kattni** [adafruit/circuitpython#2150]
The max voltage returned on any of the pins on the Circuit Playground Bluefruit is 3.01 when connected to the 3.3V and ground pads using a potentiometer. It should be returning 3.29 when maxed out as the 3.3V pin does.

Apparently there is an analog reference that must be set, that is currently hitting a max of 3.0V vs the 3.6V it should be.

**Comment by jepler** [comment]
#2161 resolved this.
