### ISSUE TITLE
How to import large complicated python scripts from sd card?

### ISSUE THREAD

**Issue by AdinAck** [adafruit/circuitpython#2157]
I have a grand central, and have successfully set up importing singular .py scripts from the sd card and am trying to get numpy working, but it is not working. The current error is:
AttributeError: 'module' object has no attribute 'array'
Which basically means it has not imported numpy properly XD.
Numpy is a series of folders instead of a single .py which I suspect is the issue. I was wondering if there is a way to make this work.
Thanks!

**Comment by ladyada** [comment]
hiya - numpy is not going to be supported, its extremely CPython dependant!

**Comment by tannewt** [comment]
@AdinAck Did you modify sys.path to include the folder on the sd card?

As @ladyada says it's highly likely that numpy will take too much memory and/or require native modules we don't support.

**Comment by AdinAck** [comment]
Yes the sys.path included the SD card. I have given up on using numpy. Thanks for the help though~

Adin Ackerman

**Comment by dhalbert** [comment]
@AdinAck We recently heard about this interesting library: https://micropython-ulab.readthedocs.io/en/latest/, which might be able to fit on certain CircuitPython builds.

**Comment by AdinAck** [comment]
That’s awesome I’ll check it out!
