### ISSUE TITLE
Request VID/PID for Serpente

### ISSUE THREAD

**Issue by arturo182** [adafruit/circuitpython#2159]
We merged the Serpente support into CP with the Trinket PID, which I didn't realize was a problem. Let's fix it here and in the uf2 bootloader :)

Thank you!

**Comment by ladyada** [comment]
Arturo Serpente   VID 0x239A    PID 0x0057  # bootloader
                                PID 0x8057  # arduino
                                PID 0x8058  # circuitpython

**Comment by arturo182** [comment]
Wow that was fast :D

**Comment by ladyada** [comment]
z00000000000000000m
please update both circuitpy and uf2 :)
