### ISSUE TITLE
STM32: randomize os.urandom

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#2168]
reminder so we don't forget!

**Comment by hierophect** [comment]
Note that TRNG is supported on the F412 and the F405, but doesn't exist on the F411. Is that significant for this case? Should I just pass in a pseudorandom number for the F411?

**Comment by tannewt** [comment]
On the 411 just return false like the SAMD21 does. The actual `random` module already does pseudorandom and uses this as the seed if it can.

**Comment by hierophect** [comment]
Glad I asked. Sounds good.
