### ISSUE TITLE
STM32: second soft reboot after writing

### ISSUE THREAD

**Issue by hierophect** [adafruit/circuitpython#2170]
STM32 boards will sometimes soft reboot 1-5 seconds after being written to flash. I'd like input on whether anyone else experiences this error to rule out mac-related USB issues and the like.

**Comment by ladyada** [comment]
this happens on mac's cause they write cruft to the disk - it doesnt happen on windows or linux

**Comment by ladyada** [comment]
closin cause thats how macos is :)

**Comment by hierophect** [comment]
Oh. Should I close issue then?

**Comment by hierophect** [comment]
whoop ninjad
