### ISSUE TITLE
STM32: Improve I2C reset workaround

### ISSUE THREAD

**Issue by hierophect** [adafruit/circuitpython#2172]
I2C currently has problems resetting after a soft reboot, such as after a write to disk. The error is actually not listed in the F4 errata, but follows the exact pattern of the "I2C analog filter may provide wrong value" error listed in the F10xx erratas [here](https://www.st.com/content/ccc/resource/technical/document/errata_sheet/f5/50/c9/46/56/db/4a/f6/CD00197763.pdf/files/CD00197763.pdf/jcr:content/translations/en.CD00197763.pdf) (2.14.7) and [here](https://www.st.com/content/ccc/resource/technical/document/errata_sheet/7d/02/75/64/17/fc/4d/fd/CD00190234.pdf/files/CD00190234.pdf/jcr:content/translations/en.CD00190234.pdf#page26)(2.13.7). Stack exchange discussion is [here](https://electronics.stackexchange.com/questions/272427/stm32-busy-flag-is-set-after-i2c-initialization).

The current workaround for this error is crude and not fully implemented as advised in the errata, and could be improved to match the recommended solution.

**Comment by tannewt** [comment]
![Screen Shot 2019-09-20 at 10 44 09 AM](https://user-images.githubusercontent.com/52649/65347334-a2d42b80-db93-11e9-8f04-73e4ef4137a2.png)

**Comment by hierophect** [comment]
Making a note of this forum issue (experiences internal displayio error on reset) to try and validate whether it's related: https://forums.adafruit.com/viewtopic.php?f=60&t=159872&p=789428#p789428
