### ISSUE TITLE
STM32: Support new dev boards

### ISSUE THREAD

**Issue by hierophect** [adafruit/circuitpython#2196]
To be added:

- PYB LR Nano V2 [F411]
- F411 "Blackpill", generic [F411]
- Meowbit [F401]

**Comment by ladyada** [comment]
matek betaflight controllers use stm32f405
https://www.amazon.com/MATEKSYS-F405-STD-Flight-Controller-STM32F405/dp/B079CN4QX3

**Comment by hierophect** [comment]
@ladyada I'll need some new VIDs and PIDs for these boards, correct?

**Comment by ladyada** [comment]
PYB Nano v2       VID 0x239A    PID 0x0067  # bootloader
                                PID 0x8067  # arduino
                                PID 0x8068  # circuitpython

F411 BlackPill    VID 0x239A    PID 0x0069  # bootloader
                                PID 0x8069  # arduino
                                PID 0x806A  # circuitpython

**Comment by hierophect** [comment]
@ladyada thanks!
