### ISSUE TITLE
`.Trashes` file on iOS is confusing iOS

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#2199]
~~`.Trashes`, created when a filesystem is initialized, should be a directory, not a file.~~ See https://github.com/hathach/tinyusb/issues/182#issuecomment-538320398.

**Comment by dhalbert** [comment]
OK, further research. We deliberately made `.Trashes` a file, not a directory, because for MacOS, that prevents a "trash can" from being created on the filesystem with deleted files. It works to do that on MacOS, but apparently iOS is not acting properly. So we could report this to Apple.

**Comment by CollinCunningham** [comment]
@dhalbert Do you know if creating `.Trashes` as a file instead of a directory is an official solution from Apple or a hack/workaround?

**Comment by dhalbert** [comment]
@CollinCunningham The technique appears multiple places, but nothing official that I can find. It does not appear to be documented, but then, Apple doesn't document a lot of stuff. I did some websearches on site:apple.com and could only find mentions in discussions.apple.com

**Comment by dhalbert** [comment]
Did someone report this to Apple? I thought that was in the works.

**Comment by CollinCunningham** [comment]
@dhalbert i believe pt filed a bug report

**Comment by dhalbert** [comment]
I re-tested this on IOS 13.3 on an iPhone 6S, and it's still a problem. I can delete, say, `code.py` in the Files app, but when I browse away to another device and then browse back to CIRCUITPY, `code.py` is still there, and it's also still there if I remove the board and plug it into a regular host computer.

We could special-case the `.Trashes` folder and have anything moved into it automatically be deleted immediately. I'm not sure if that's a great user experience, but maybe it's no worse than the behavior of a `.Trashes` file.

**Comment by ladyada** [comment]
like you mean circuitpy FAT handler would look for the path and delete any FAT entries?

**Comment by dhalbert** [comment]
@ladyada, yeah, that's really kind of bad, and it would confuse the host computer, which would have a different idea of what the filesystem looks like. I take it back.

**Comment by ladyada** [comment]
what if we have a trashes folder but its like, non-writable?

**Comment by dhalbert** [comment]
> what if we have a trashes folder but its like, non-writable?

I'll try that.

**Comment by dhalbert** [comment]
It turns out there are no per-entry file or directory permissions on ordinary FAT filesystems, so there's no way to make just that folder be read-only.

**Comment by dhalbert** [comment]
I think we have this figured out now -- nothing to change.
