### ISSUE TITLE
Request USB VID/PID for StringCar M0 Express board

### ISSUE THREAD

**Issue by CedarGroveStudios** [adafruit/circuitpython#2215]
A pull request will be coming soon for support of the Cedar Grove StringCar M0 Express board. It's a SAMD21E18A. Would it be possible to issue a unique USB VID/PID for this board before submitting the PR?  Thanks!

**Comment by ladyada** [comment]
CGrover StringCar M0   VID 0x239A    PID 0x005F  # bootloader
                                PID 0x805F  # arduino
                                PID 0x8060  # circuitpython

**Comment by CedarGroveStudios** [comment]
Thank you!

**Comment by ladyada** [comment]
:D
