### ISSUE TITLE
Requesting a USB PID for Winterbloom Sol

### ISSUE THREAD

**Issue by theacodes** [adafruit/circuitpython#2217]
Winterbloom Sol will be an open source (hardware and software) Eurorack MIDI to CV module.

I'll be publishing the board files and sending a PR to CircuitPython to add support for Winterbloom Sol very soon.

Could I have a USB PID for this? 💜

**Comment by ladyada** [comment]
comin right up!!!

**Comment by ladyada** [comment]
```
Winterbloom Sol   VID 0x239A    PID 0x0061  # bootloader
                                PID 0x8061  # arduino
                                PID 0x8062  # circuitpython
```

**Comment by theacodes** [comment]
Thank you so much! ✨

**Comment by ladyada** [comment]
🦄🦄🎹🎹
