### ISSUE TITLE
particle:argon uf2 installation

### ISSUE THREAD

**Issue by WilliamGFish** [adafruit/circuitpython#2231]
With my Argon the CircuitPython installation has never worked.

I have reinstalled the boot-loader several times but the uf2 file after writing fails to have any effect.

Help please..

Billy..

**Comment by WilliamGFish** [comment]
I have followed the instructions and my boron lte board is the same

**Comment by tannewt** [comment]
Are you able to see the *BOOT drive after installing the bootloader?

**Comment by WilliamGFish** [comment]
Yeah the bootloader shows as ARGONBOOT and BORONBOOT as expected. When I drop the uf2 file onto drive it writes then nothing. No drive appears but the COM port is active.

**Comment by tannewt** [comment]
Try listing the drive from the REPL. `os.listdir()` Did you just get the Particle boards? It's possible they switched SPI flash chip and CircuitPython isn't configured to talk with it.

**Comment by WilliamGFish** [comment]
OK now i'm not sure what to do... REPL- I've got Mu which just tells me there is not Adafruit boards available.
The Particle boards are built around an NRF52840 whicih I have been using with Zephyr for months but am currently trying to re-program (re-flash to stock) the ESP32 for standard AT commands.

Circuit Python was a good choose to do this but I'm failing at the first hurdle.

**Comment by tannewt** [comment]
You can access the REPL without Mu by following these instructions: https://learn.adafruit.com/welcome-to-circuitpython/kattni-connecting-to-the-serial-console#using-something-else-8-11

You'll have to look into the Particle docs to find out if there is a different SPI Flash.

**Comment by WilliamGFish** [comment]
They both use the MX25L1606. I have attached block diagrams


![image](https://user-images.githubusercontent.com/43581311/67118467-d8912200-f1dc-11e9-9a46-1a2776eaa184.png)
![image](https://user-images.githubusercontent.com/43581311/67118489-e3e44d80-f1dc-11e9-9a1e-95eff9450725.png)

**Comment by WilliamGFish** [comment]
I use Putty and Termite but just get a blank screen. This is okay, according to the guide? 

How do I get my program to the board? Do I go back to BOOT mode them copy?

**Comment by WilliamGFish** [comment]
PROGRESS:
Just flashed with the Adafruit Feather nRF52840 Express with nRF52840 version of CircuitP and we have REPL prompt

**Comment by WilliamGFish** [comment]
PROGRESS:
Used _**adafruit-circuitpython-pca10059-en_US-4.1.0.uf2**_ and it has appeared as drive and COM port

**Comment by WilliamGFish** [comment]
I have been following these instructions and not having success

**Comment by jerryneedell** [comment]
Just to clarify - did you try the adafruit_circuitpython_particle_argon_en_US-4.1.0.uf2?

**Comment by WilliamGFish** [comment]
when I use ARGON version doesn't appear as a USB drive.

If I use Xenon then USB Drive (CURCUITPY) appears

**Comment by WilliamGFish** [comment]
With ARGON or BORON still nothing with XENON:


```
Adafruit CircuitPython 4.1.0 on 2019-08-03; Particle Xenon with nRF52840
>>>
>>>
>>>
>>>
>>>
>>> control=C
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'C' is not defined
>>>

```

The only thing that separates them is the UART connection to Modems

Any thoughts?

**Comment by jerryneedell** [comment]
Makes no sense to me.  I use the argon build on argon and xenon build on xenon. 
Not sir3 if it matters, do you have the argon boot loader on the Argon? How did you install the boot loader?  Did you use this guide?   https://learn.adafruit.com/circuitpython-on-the-nrf52/build-flash-particle

**Comment by WilliamGFish** [comment]
That is the guide is used and have used the "correct" version on both the Argon and Boron boards with the same result.

I have been using these boards with Zephyr for months now and was looking at circuitpython as a alternative but its not been successful so far.

**Comment by WilliamGFish** [comment]
I'm back on this and still not able to either my Argon or Boron board to bring up Circuit Python?

I have tried various boot-loaders and uf2 but still nothing.

If a flash the uf2 for the Xenon on either a Argon or Boron it comes up straight away.

Lost....need some ideas.

Billy..

**Comment by WilliamGFish** [comment]
Some direct reponces to questions:

**> Do you have the argon boot loader on the Argon?** 
I'm using the Argon on the Argon and Boron on the Boron.

adafruit-circuitpython-particle_argon-en_US-4.1.0.uf2
adafruit-circuitpython-particle_argon-en_US-4.0.1.uf2
adafruit-circuitpython-particle_argon-en_US-4.0.0.uf2
adafruit-circuitpython-particle_argon-en_US-5.0.0-alpha.4.uf2


adafruit-circuitpython-particle_boron-en_US-4.1.0.uf2


**> How did you install the boot loader?** 

**> Did you use this guide?** https://learn.adafruit.com/circuitpython-on-the-nrf52/build-flash-particle
Yes that was my starting point, yet i'm using pre-compiled versions and boot-loader and uf2

**Comment by jerryneedell** [comment]
How did you flash the bootloader -- with the Arduino IDE?
get your board into the Bootloader and post the contents of the INFO_UF2.TXT file.

**Comment by jerryneedell** [comment]
I just flashed the afadfruit_bluefruit_nrf52840 bootlaoade via a J-Link as described in the guide and then put the particle_argon_4.1.0.uf2 on it and all worked fine.

**Comment by WilliamGFish** [comment]
> How did you flash the bootloader
I used nrfjprog, I even out of habit do an eraseall.

`nrfjprog --program particle_argon_bootloader-0.2.13_s140_6.1.1.hex --sectoranduicrerase -f nrf52 --reset`
> get your board into the Bootloader and post the contents of the INFO_UF2.TXT file.
The bootloader works as expected which is the frustrating thing.


I am starting to think its a windows thing, Win10 can be a pain "resolving" problems for you.

Thanks for your continued support.

Billy..

**Comment by jerryneedell** [comment]
If you have arduino installed -- update to the lated adafruit nrf5284 BSP and try that.

**Comment by WilliamGFish** [comment]
> If you have arduino installed -- update to the lated adafruit nrf52840 BSP and try that.

Not an Arduino guy, normally i would be hacking code onto the NRF52 via C and nrfjprog. I generally don't use them USB drives, USB is just as a serial console.

Thats why I'm startting to suspect this could be a windows problem

**Comment by jerryneedell** [comment]
ddi you do all three steps 
![Screen Shot 2019-10-22 at 3 43 40 PM](https://user-images.githubusercontent.com/15856834/67325230-d67fd980-f4e2-11e9-990c-21699ee04ce1.png)

**Comment by jerryneedell** [comment]
I may be wrong -- where did you get the bootloader file -- I will try to replicate it.

**Comment by jerryneedell** [comment]
OK -- I just downloaded the same bootloader .hex file from the nrf52 bootloader repository and used the same command to flash it (after erasing) and then loaded the 4.10. .UF2 and it all worked as expected. perhaps it it is windows -- I'm out of ideas ....

**Comment by WilliamGFish** [comment]
Jerry, found it.... ruddy Windows. 
In device manager it was only showed as Argon serial port. Not normally a problem as I only use serial comms. 
So un-installed device and started again...bingo it's working. 

Now how do we get this into the trouble shooting guide.

**Comment by jerryneedell** [comment]
Congratulations! Glad it is working -- I think @dhalbert maintains that guide.

**Comment by dhalbert** [comment]
Is this Windows 10 or 7? Did you install any drivers initially that might have taken control of this? I don't remember if Particle supplies any drivers.

**Comment by jerryneedell** [comment]
Still odd that you had partial success with the xenon build ....

**Comment by WilliamGFish** [comment]
The Xenon build presented a difference device which appeared as a USB Drive, which is the clue I needed to trace the issue. 100% Windows trying to be clever but failing.

I don't use a Particle Xenon as I use the NRF52_DevKit seems silly to buy another version of the same thing.

So if someone does not see a CIRCUITPY drive they need to look in Device Manager -> Disk Drives; if they do not see an Argon/Boron/Xenon drive they need to check ->Ports (COM &LPT) to see if they have ARGON Serial (or corresponding version). Then right click and uninstall device (including drivers). 
Plug board back in and it should configure correctly.

**Comment by jrbski** [comment]
> The Xenon build presented a difference device which appeared as a USB Drive, which is the clue I needed to trace the issue. 100% Windows trying to be clever but failing.
> 
> I don't use a Particle Xenon as I use the NRF52_DevKit seems silly to buy another version of the same thing.
> 
> So if someone does not see a CIRCUITPY drive they need to look in Device Manager -> Disk Drives; if they do not see an Argon/Boron/Xenon drive they need to check ->Ports (COM &LPT) to see if they have ARGON Serial (or corresponding version). Then right click and uninstall device (including drivers).
> Plug board back in and it should configure correctly.

I had the same issue, and the part I was missing was the 'including drivers' part of uninstalling the serial port driver (in my case for a xenon) under win10.. once I hit the checkbox to remove the drivers, the circuitpy drive appeared.

Thanks @WilliamGFish for the great summary on this issue!
