### ISSUE TITLE
nrf: Update nrfx to 1.8.1 or later

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#2235]
nrfx ~~1.8.0~~ 1.8.1 is now available. We should update https://github.com/adafruit/nrfx and the checkout we use for CPy.

Notably (from 1.8.0 release notes)

>Fixed an issue in the TWIM driver that would make the driver stuck when a premature STOP condition was generated by a slave device. The driver now handles this situation properly and signals that a bus error occurred.

**Comment by tannewt** [comment]
Done in #2395
