### ISSUE TITLE
Esp8266 webrepl_setup fails to import machine

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#224]
In 2.0.0-rc.1 module machine is not available. webrepl_setup imports machine and fails.

**Comment by jerryneedell** [comment]
The fix to make machine available works fine and I am now able to get the web replacement working. There still appears to be some problem with the web real configuration. If I import webrepl_setup and enable it on boot it seems to work OK after a power cycle. However if I enter a control-D then it reports that webrepl has not been configured. It appears to work again after a power cycle.

**Comment by tannewt** [comment]
I don't think its intended to work across soft reloads. I'll take a harder look at this Tuesday though.
