### ISSUE TITLE
busio.UART write sometimes returns None

### ISSUE THREAD

**Issue by ThomasAtBBTF** [adafruit/circuitpython#2263]
Currently it happens (I observed this in SAMD boards) that, if lots of data is written to the uart the write call returns none.
The reason in seems to be in pystream.c (https://github.com/adafruit/circuitpython/blob/master/py/stream.c#L237)
I can handle this problem by waiting "a little" and retry, which seems to work.
Only I can not say how short "a little" can shall be.,,,,,
I think UART.out_waiting() would be helpful.

**Comment by ladyada** [comment]
`out_waiting` is a good idea for fast chips and slower baud rates it is part of pyserial so we can mimic it

**Comment by ThomasAtBBTF** [comment]
Thank you for considering this!

**Comment by dhalbert** [comment]
I think this may be due to a bug in the SAMD implementation that is not waiting for all the characters to be written. We mean for `UART.write()` to be blocking, but it appears it is not waiting properly.
