### ISSUE TITLE
no restart on save with Mu

### ISSUE THREAD

**Issue by Miro87043** [adafruit/circuitpython#2288]
I'm working on a project using a Feather M4. I'm collecting data from sensors (moisture, lux, temp) and sending to Adafruit IO. When I'm doing short tests in code is does a soft restart on save without issue. Once I start connecting to the internet and sending to IO soft restart does not happen on save. The file saves appropriately when I check it in another editor, but still no restart. I'm using Mu 1.0.2 on mac. code.py attached.

[code.txt](https://github.com/adafruit/circuitpython/files/3846731/code.txt)

**Comment by dhalbert** [comment]
Closing this for now, since many things have changed since this report. Please reopen or open a new issue if this shows up with the latest CircuitPython and libraries.
