### ISSUE TITLE
Request VID/PID for ndGarage Bit6 board

### ISSUE THREAD

**Issue by ndGarage** [adafruit/circuitpython#2289]
Bit6 is still under development. It consists of one SAMD21E18. It has a user button and 19 LEDs to play with. It aims at the beginners with CircuitPython. It may need two PIDs for both bootloader and app. I will submit the pull request once it is tested. Thanks.

**Comment by ladyada** [comment]
ndGarage Bit6     VID 0x239A    PID 0x0065  # bootloader
                                PID 0x8065  # arduino
                                PID 0x8066  # circuitpython
