### ISSUE TITLE
STM32 - displayio SPI TFT displays not initing/displaying

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#2308]
something odd with STM32 and displayio for tft. OLED works, and there's TFT traffice

@hierophect youc an post saleae traces here

**Comment by hierophect** [comment]
Is this for my now closed PR? On master we shouldn't have displayio enabled at all? I haven't quite gotten back to displayio since I raised the board frequencies.

**Comment by ladyada** [comment]
yes correct!
