### ISSUE TITLE
VID/PID for a new samd21 board

### ISSUE THREAD

**Issue by sarfata** [adafruit/circuitpython#2322]
We built a board roughly based on the trinket m0 with IR receive/transmit capabilities. It's a shitty addon for conference badges. Hardware and software are all opensource: https://github.com/sarfata/shirtty-addon.

I am working on a PR to get this merged into master (#2294 is the first PR against 4.x but I will open a new one against master). Would be great to have a custom PID for this board. Thanks!

**Comment by ladyada** [comment]
Shirtty Add-on    VID 0x239A    PID 0x006B  # bootloader
                                PID 0x806B  # arduino
                                PID 0x806C  # circuitpython
