### ISSUE TITLE
On metro m0 express random module is only available as urandom

### ISSUE THREAD

**Issue by joeynelson** [adafruit/circuitpython#233]
The documentation seems to imply that for circuit python it should be random.

**Comment by dhalbert** [comment]
`urandom` changed to `random` from CircuitPython 1.0.0 to 2.0.0.
http://circuitpython.readthedocs.io/en/stable/index.html is the documentation for 1.0.0 ("stable").
http://circuitpython.readthedocs.io/en/latest/index.html is the documentation for 2.0.0, not quite release yet ("latest").

Sorry about the doc naming: it's confusing.

**Comment by joeynelson** [comment]
Got it.  Thanks for quick response.  And thanks for the great work helping make embedded programming ever more accessible.
