### ISSUE TITLE
Increase monotonic_ns precision

### ISSUE THREAD

**Issue by olivier-boesch** [adafruit/circuitpython#2334]
Hi Everyone,

I'm using M4 express (circuitpython v.5.0.0beta0) with circuitpython in physics and geophysics education. I'm on a project that measure the speed of wave in rocks.

I was afraid, when i saw the precision of the monotonic_ns function as 1ms only.

Is it possible to make it work in a more precise way like the micros function in arduino ?

Thanks.

Olivier B.

**Comment by ladyada** [comment]
please use pulsein for precision timing, Python is not a real-time precision programming language
https://circuitpython.readthedocs.io/en/latest/shared-bindings/pulseio/PulseIn.html

**Comment by olivier-boesch** [comment]
As I'm used two analogic inputs and measuring between these two signals, using pulsein is not possible. Is it ?

If I convert my schematic to use only one input, I could use pulsein but what is the minimum level to get a high with pulsein?

Thanks

**Comment by ladyada** [comment]
please post a link to your code/reference to the project so we can see what you are trying to do
