### ISSUE TITLE
NeoPixels do not turn off on Circuit Playground Bluefruit on REPL soft reboot

### ISSUE THREAD

**Issue by kevinjwalters** [adafruit/circuitpython#2341]
There's some difference in behaviour here between the Circuit Playground Bluefruit and Circuit Playground Express. If you turn on some pixels and then hit Cntrl-D in REPL on a CPX then pixels turn off. On a CPB it they remain on.

Perhaps there are also other peripherals that are not re-initialised too?

```
Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 5.0.0-beta.0 on 2019-11-19; Adafruit Circuit Playground Bluefruit with nRF52840
>>>
>>> from adafruit_circuitplayground.bluefruit import cpb
>>> cpb.pixels[5] = (50, 0, 0)
>>> cpb.pixels[6] = (0, 50, 0)
>>> cpb.pixels[7] = (0, 0, 50)
>>>
soft reboot
```

This is on `5.0.0-beta.0` with the latest library copied in from https://github.com/adafruit/Adafruit_CircuitPython_CircuitPlayground - I am running `4.1.0` on the CPX, btw.

**Comment by dhalbert** [comment]
CPX resets the neopixels to all off in board.c:reset_board(). Do the same for CPB.

**Comment by kevinjwalters** [comment]
It wasn't in the release notes but I thought I'd check `5.0.0.beta.3`. FYI, I'm still seeing the NeoPixels left on.
