### ISSUE TITLE
USB VID/PID request for RAK5010

### ISSUE THREAD

**Issue by jmarcelino** [adafruit/circuitpython#2343]
Hello,

I'm porting CircuitPython to the RAK5010 board (mentioned here https://twitter.com/jmarcelino/status/1201032376257843202 ). This is a nRF52840 board with interesting connectivity (2G and LTE-M) plus sensors: https://doc.rakwireless.com/datasheet/rakproducts/rak5010-wistrio-nb-iot-tracker-datasheet . 

It would really help if you could facilitate  a suitable VID / PID for this as indicated in the (excellent!) porting documentation. I'm expecting to submit a PR for it in the next few days.

Thank you very much in advance!

**Comment by ladyada** [comment]
```
RAK5010           VID 0x239A    PID 0x006D  # bootloader
                                PID 0x806D  # arduino
                                PID 0x806E  # circuitpython
```

**Comment by ladyada** [comment]
thanks :)
