### ISSUE TITLE
VID/PIDs for XinaBox xChips

### ISSUE THREAD

**Issue by KalbeAbbas** [adafruit/circuitpython#2349]
Hi,
I am from XinaBox, we manufacture modular electronics. We want to port 
circuitpython to our  boards/xChips, please facilitate VID/PIDs for these:

* CC03 (based on SAMD21)
* CS11 (based on SAMD21)
* CW03 (based on SAMD21)
* ...and for soon to be launched xChip based on nRF52840, **CB03**

Your assistance is appreciated. Thanks :)

https://xinabox.cc/

**Comment by ladyada** [comment]
Hi @KalbeAbbas @gotfredsen we grant VID/PIDs to hobbyist, DIY and independent makers. we can grant you one VID/PID. for the amount of hardware you are making, you must purchase a USB VID.

https://www.usb.org/getting-vendor-id
