### ISSUE TITLE
#2297 breaks status neopixel on SAMD51 boards

### ISSUE THREAD

**Issue by theacodes** [adafruit/circuitpython#2357]
It seems something about #2297 broke the status neopixel, at least for Winterbloom Sol boards.

Firmware built from previous revisions works fine, and all firmwares built after the change are affected.

The pixel works in the bootloader, but once circuitpython starts it's off. Neither the supervisor nor user code (using `neopixel_write` or `neopixel`) are able to control the neopixel.

Surprisingly, I had *one* board where the status pixel *almost* worked - it just displayed the colors incorrectly (basically wouldn't display anything below ~127 on each color channel).

**Comment by deshipu** [comment]
The neopixel protocol is very timing sensitive, so the original code probably had to compensate for all those background tasks being called in the background...

**Comment by theacodes** [comment]
Slight update: @jepler was able to reproduce this on SAMD builds. 

Also, here's a logic analyzer capture from the broken build when writing `(0b01010101, 0b01010101, 0b01010101)` to the pixel:

![Annotation 2019-12-05 085749](https://user-images.githubusercontent.com/250995/70257488-394dcd00-173f-11ea-9f22-b40676f0cb5e.png)

Compared to a working build:

![Annotation 2019-12-05 090427](https://user-images.githubusercontent.com/250995/70257491-3c48bd80-173f-11ea-84ce-770170fd8277.png)

**Comment by dhalbert** [comment]
Still works on SAMD21: Trinket and Metro M0

**Comment by theacodes** [comment]
Updating from the discord conversation.

@jepler has a *much* better analyzer than me. It seems the issue is that the timing is about ~10% faster:

bad (917khz):
![MSO1104Z_2019-12-05_11 15 02](https://user-images.githubusercontent.com/250995/70268283-fb5ba380-1754-11ea-9fdd-c1cf7021bed8.png)

good (800khz):
![MSO1104Z_2019-12-05_11 17 00](https://user-images.githubusercontent.com/250995/70268290-fdbdfd80-1754-11ea-95a9-ad1bfeb49178.png)

**Comment by jerryneedell** [comment]
just to clarify -- this issue is not limited to the "status" neopixel -- For example, on a grand central_m4_express, I cannot operate a neopixel ring on Pin A1

**Comment by jepler** [comment]
Closed via #2363
