### ISSUE TITLE
mem allocation error -> hardfault

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#238]
whee! try this on a feather m0 running 1.0.0 for a good time

[main.txt](https://github.com/adafruit/circuitpython/files/1279839/main.txt)

**Comment by tannewt** [comment]
This was a doozy!

I thought I had reproduced it in GDB with 2.0 but discovered the MTB was left running. I have a fix for that here: 1ebb5b8cb9d97d73ae1fb9c3794fa64d0ee7ec3f

I went back and tried it with 1.0 and discovered I had already fixed it in fab634e3eeb456e9d5dffa2cabb9ded39c45d6b6 with my change to lib/utils/pyexec.c.
