### ISSUE TITLE
robohatmm1 in 4.1.x branch needs to be renamed to robohatmm1_m4 to match master

### ISSUE THREAD

**Issue by makermelissa** [adafruit/circuitpython#2412]
This is causing an issue on the build names and how the boards show up on circuitpython.org

**Comment by makermelissa** [comment]
Unfortunately, I'm not the greatest at dealing with multiple branches on such a complex repo, so I'm not sure the best way to go about it.

**Comment by dhalbert** [comment]
So after it's fixed manually by https://github.com/adafruit/circuitpython-org/pull/344, we need to rename the board before doing any more 4.x releases (per discussion with @makermelissa in discord).

**Comment by makermelissa** [comment]
It might need to be fixed before the next 5.x release if the data files are completely regenerated.

**Comment by dhalbert** [comment]
I can add renamed assets in the 4.1.2 release to match the new board name, so that the links will continue to work. Where are the board names extracted from: the last release to generate the circuitpyhon-org PR, or somewhere else?

**Comment by makermelissa** [comment]
You don't need to rename the assets. I'm pointing to the current ones.

**Comment by makermelissa** [comment]
I think you just need to change the folder name under ports/atmel-samd/boards

**Comment by dhalbert** [comment]
@wallarug See above. The robohatmm1 in the 4.x tree is a SAMD21 board. Is that discontinued? Are you expecting everyone to use CircuitPython 5.x now? If that's true, we could just remove the board from 4.x. Thanks for looking.

**Comment by wallarug** [comment]
Hey @makermelissa  and @dhalbert 

Please remove robothatmm1 from the 4.x tree.   We are only making the SAMD51.

If you feel so inclined, the robohatmm1_m4 from the master branch can be put onto 4.x as well.

**Comment by wallarug** [comment]
Can this issue be closed now?  @dhalbert @makermelissa

**Comment by makermelissa** [comment]
Yeah, I'm good with closing it.

**Comment by dhalbert** [comment]
Fixed by #2415.
