### ISSUE TITLE
no module named 'adafruit_lis3dh'

### ISSUE THREAD

**Issue by SnowWolf-385** [adafruit/circuitpython#2434]
When attempting to run the sample circuitplayground_button_a.py code that came with the CircuitPython 5 bundle (adafruit-circuitpython-bundle-5.x-mpy-20191228). Code crashes at imports due to 

```
no module named 'adafruit_lis3dh'
```

This is with adding the adafruit_circuitplayground to the lib folder on the CircuitPlayground Bluefruit. 

From online searching it implies their is an error with the CircuitPython build or the Ada library.  If you think this is user error please let me know.

```
Press any key to enter the REPL. Use CTRL-D to reload.soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Traceback (most recent call last):
  File "code.py", line 2, in <module>
  File "adafruit_circuitplayground/__init__.py", line 27, in <module>
  File "adafruit_circuitplayground/bluefruit.py", line 46, in <module>
  File "adafruit_circuitplayground/circuit_playground_base.py", line 46, in <module>
ImportError: no module named 'adafruit_lis3dh'
```

**Comment by dhalbert** [comment]
The Circuit Playground Bluefruit doesn't have the library modules for the on-board sensors "frozen" in, unlike the CPX. See https://learn.adafruit.com/adafruit-circuit-playground-bluefruit/circuit-playground-bluefruit-circuitpython-libraries for information about adding those libraries.
