### ISSUE TITLE
gcc-arm-embedded added back to Homebrew-cask

### ISSUE THREAD

**Issue by dunkmann00** [adafruit/circuitpython#2453]
Not exactly sure where to put this so my apologies if this isn't the right place. But just wanted to point this out for @tannewt and @dhalbert 

https://github.com/Homebrew/homebrew-cask/pull/75091

**Comment by siddacious** [comment]
ooh, thanks for the tip @dunkmann00 !

**Comment by tannewt** [comment]
Thanks @dunkmann00! I've submitted a PR to update the version: https://github.com/Homebrew/homebrew-cask/pull/75184

**Comment by dhalbert** [comment]
Does this need to be updated? https://learn.adafruit.com/building-circuitpython/macos

**Comment by tannewt** [comment]
Done!
