### ISSUE TITLE
ImportError: no module named 'displayio' on CPX with TFT Gizmo

### ISSUE THREAD

**Issue by reversefold** [adafruit/circuitpython#2462]
Attemping to run TFT gizmo examples on Circuit Playground Express. displayio ImportError happens with both CircuitPython 4.1.2 and 5.0.0-beta2.

**Comment by ladyada** [comment]
use https://circuitpython.org/board/circuitplayground_express_displayio/

**Comment by reversefold** [comment]
Aha! That's what I was missing. It's working for me now, thanks much!
