### ISSUE TITLE
mimxrt10xx: Implement displayio

### ISSUE THREAD

**Issue by arturo182** [adafruit/circuitpython#2466]
Right now it doesn't compile because `ParallelBus` is not implemented, might need additional work after that part is done.

**Comment by ladyada** [comment]
you can mock ParallelBus, we dont have parallel on most chips - see what we did with STM32 and/or @hierophect can explain!

**Comment by hierophect** [comment]
Happy to chat on Monday if u want. Should be pretty easy and I can help if it isn't.

**Comment by arturo182** [comment]
No worries, I/someone can just copy the file directly from the stm port and it will work, I'm just a bit stuck in the HW world right now, need a few days :)

https://github.com/adafruit/circuitpython/blob/master/ports/stm32f4/common-hal/displayio/ParallelBus.c
