### ISSUE TITLE
mimxrt10xx: Parametrize flash layout

### ISSUE THREAD

**Issue by arturo182** [adafruit/circuitpython#2472]
Like in #2371

**Comment by tannewt** [comment]
I need this for Teensy 4 so I'm doing it now.

**Comment by arturo182** [comment]
awesome, tag me for review when it's ready :)

**Comment by tannewt** [comment]
Done in [7d8dac9](https://github.com/adafruit/circuitpython/commit/7d8dac9211dab92d750a0351335b4ad3fffc05e2)
