### ISSUE TITLE
mimxrt10xx: Support the rest of the EVKs

### ISSUE THREAD

**Issue by arturo182** [adafruit/circuitpython#2477]
Need to add the SDKs, linker files and board definitions for those.

Boards:
- [ ] mimxrt1015_evk
- [x] mimxrt1020_evk
- [ ] mimxrt1050_evk
- [x] mimxrt1060_evk
- [ ] mimxrt1064_evk

**Comment by tannewt** [comment]
I have the top four so I'll take a stab at it today once I'm through email and reviews.

**Comment by tannewt** [comment]
Interesting note in: https://www.nxp.com/docs/en/application-note/AN12042.pdf

<img width="865" alt="Screen Shot 2020-01-13 at 10 27 18 PM" src="https://user-images.githubusercontent.com/52649/72319494-1ffc4280-3654-11ea-9d26-433f05d97f1d.png">
