### ISSUE TITLE
mimxrt10xx: Verify AnalogIn

### ISSUE THREAD

**Issue by arturo182** [adafruit/circuitpython#2478]
It is implemented and I did some quick tests but I think we need more testing before we say it's done.

**Comment by arturo182** [comment]
Just re-tested all 6 inputs on the 1011 Feather and it's looking good so far. I will be creating a test jig for that one and I plan to have different resistor values connected to each analog in pin so I can test that the analog values are as expected.

**Comment by hierophect** [comment]
Also testing this today
