### ISSUE TITLE
mimxrt10xx: Verify the busio module

### ISSUE THREAD

**Issue by arturo182** [adafruit/circuitpython#2483]
Just run sanity tests on SPI, I2C and UART, I probably missed something or there's some corner case.

**Comment by ladyada** [comment]
i2c scanning does not seem to find write-only/read-only devices (?):
SSD1306 OLED, and GTOP I2C GPS are not found on bus

**Comment by ladyada** [comment]
ahh default i2c frequency for scanning (at least) is 1MHz, should be 100khz to allow all things to respond. many devices dont work at 1Mhz :) for now, im testing with
`i2c = busio.I2C(board.SCL0, board.SDA0, frequency=100000)`

**Comment by ladyada** [comment]
SPI freq is 2x faster than expected, setting it to 4MHz -> 8MHz clock speed

**Comment by arturo182** [comment]
This is all great info, thanks :)

**Comment by mubes** [comment]
SPI Frequency is corrected in https://github.com/adafruit/circuitpython/pull/2658

**Comment by mubes** [comment]
I2C Frequency is corrected in #2659 , given that UART was also fixed recently I think it's worth re-testing this lot to see if the ticket can be closed....note that the _requested_ I2C frequency is 400KHz.

There remains a lockup under punishing conditions, but that's a different issue.

**Comment by arturo182** [comment]
I need more than 24h in a day :D

**Comment by arturo182** [comment]
One more patch by @mubes here https://github.com/adafruit/MIMXRT10xx_SDK/pull/1

Should fix the scan issues.
