### ISSUE TITLE
mimxrt10xx: Allow one-way UART

### ISSUE THREAD

**Issue by arturo182** [adafruit/circuitpython#2484]
Right now UART expects TX and RX, need to fix that.

**Comment by arturo182** [comment]
Not 100% related to this issue, but I think the issue related to busio in general is closed now so just wanted to make a note. I spent a few hours yesterday testing and verifying SPI, and I spent a few hours today verifying I2C. I'm fairly confident now that those two peripherals are stable and ready to be used by the general public. Good to see you're on UART, @hierophect :)

**Comment by arturo182** [comment]
Actually my bad, the issue is still open: #2483

**Comment by hierophect** [comment]
@arturo182 have not stress tested Busio or DigitalIO yet, they're on the docket for today :)
