### ISSUE TITLE
mimxrt10xx: Figure out a way to benchmark the USB

### ISSUE THREAD

**Issue by arturo182** [adafruit/circuitpython#2491]
The mimxrt10xx family has a USB High-Speed peripheral, it would be nice to see if we are actually taking advantage of that.

In mass-storage the bottleneck is probably the external flash speed, so that's probably not the best idea to test speeds.

Ideas welcome.

**Comment by tannewt** [comment]
I don't think we need to benchmark but we should confirm we are in high speed mode. (I can with a Beagle.)

**Comment by tannewt** [comment]
Closing. I confirmed the 1011 enumerates as high speed via `lsusb -t`.
