### ISSUE TITLE
mimxrt10xx: Review what crazy options we can turn on in the beefier chips

### ISSUE THREAD

**Issue by arturo182** [adafruit/circuitpython#2492]
We have 1MB of RAM and almost unlimited (well, 8/16/32 MB) code flash, let's do crazy things!

Ideas welcome

**Comment by tannewt** [comment]
I'd like to start marking CircuitPython code and data so we can separate it into specific RAMs. That should speed up all SoCs which have tightly coupled memory (TCM).

**Comment by dhalbert** [comment]
Closing this because many things have happened since it was opened.
