### ISSUE TITLE
mimxrt10xx: Utilize the SDIO interface on the RT1062

### ISSUE THREAD

**Issue by arturo182** [adafruit/circuitpython#2497]
This would be awesome for really fast sd-cards or BLE/WiFi modules that speak SDIO.

From the datasheet:

> – SD/SDIO 3.0 compliance with 200 MHz SDR signaling to support up to 100 MB/sec
> – Support for SDXC (extended capacity)

**Comment by ladyada** [comment]
this is a dup of
https://github.com/adafruit/circuitpython/issues/4020
so closing this one since there's more people there
