### ISSUE TITLE
mimxrt10xx: Utilize the Keypad peripheral in RT1062

### ISSUE THREAD

**Issue by arturo182** [adafruit/circuitpython#2499]
From datasheet:

> The KPP is a 16-bit peripheral that can be used as a keypad matrix interface or as general purpose
> input/output (I/O). It supports 8 x 8 external key pad matrix. Main features are:
>  • Multiple-key detection
>  • Long key-press detection
>  • Standby key-press detection
>  • Supports a 2-point and 3-point contact key matrix

**Comment by ladyada** [comment]
its better to use a common digitalio-using API than a special peripheral

**Comment by dhalbert** [comment]
Closing this because we have `keypad` support.
