### ISSUE TITLE
mimxrt10xx: Utilize the Touch Screen peripheral in RT1062

### ISSUE THREAD

**Issue by arturo182** [adafruit/circuitpython#2500]
The RT1062 has a TSC peripheral, could be useful!

From datasheet:

> The controller utilizes ADC hardware trigger function and control switches in touch screen analogue block. The controller only supports 4-wire of 5-wire screen touch modes.

**Comment by kmatch98** [comment]
Looking at the datasheet for the RT1062, it looks like it includes a touch screen controller for resistive touch screens:

![IMG_0838](https://user-images.githubusercontent.com/33587466/112576377-280b5280-8dc0-11eb-8cd6-47b4b85c7357.jpeg)

**Comment by tannewt** [comment]
I doubt we'll add a separate API for this. I think these touch screens can likely be read already with AnalogIn.

**Comment by ladyada** [comment]
closing cause these aren't complex devices, and its better to use a common analogin-using API than a special peripheral!
