### ISSUE TITLE
_pixelbuf.buf doesn't have a setter

### ISSUE THREAD

**Issue by rhooper** [adafruit/circuitpython#2502]
_pixelbuf.buf doesn't have a setter, breaking some code.

See https://github.com/adafruit/Adafruit_CircuitPython_NeoPixel/issues/65

**Comment by dhalbert** [comment]
@rhooper Sounds like https://github.com/adafruit/Adafruit_CircuitPython_NeoPixel/pull/66 has determined we can close this?
