### ISSUE TITLE
Performance differs with adding or removing a (not used) variable?

### ISSUE THREAD

**Issue by frank1119** [adafruit/circuitpython#2506]
Hi. 
I was writing a little program for reading 3 ADCs of a trinket m0. When I started tuning for some performance, I ran in this particular observation. Adding or removing a dummy variable influences the speed about 10%. I assume it has to do with the internals of Python, e.g. the evaluation of a hashtable or something like that.

The code I run:

```
import board
import analogio
from time import monotonic
import busio
import supervisor
supervisor.set_rgb_status_brightness(0)

def main():
    EMA_a = 0.6
    EMA_a_r = 1 - EMA_a

    pin1 = analogio.AnalogIn(board.A0)
    pin2 = analogio.AnalogIn(board.A1)
    pin3 = analogio.AnalogIn(board.A2)

    EMA_S_1 = pin1.value >> 8
    EMA_S_2 = pin2.value >> 8
    EMA_S_3 = pin3.value >> 8

    prev_1 = -1
    prev_2 = -1
    prev_3 = -1

    octime = monotonic()
    loops = 0
    oloops = 0
    handshake2 = bytearray(6)
    handshake2[0] = 255
    handshake2[1] = 0

    while True:
        EMA_S_1 = (EMA_a * (pin1.value >> 8)) + (EMA_a_r * EMA_S_1)
        EMA_S_2 = (EMA_a * (pin2.value >> 8)) + (EMA_a_r * EMA_S_2)
        EMA_S_3 = (EMA_a * (pin3.value >> 8)) + (EMA_a_r * EMA_S_3)

        new_1 = int(EMA_S_1)
        new_2 = int(EMA_S_2)
        new_3 = int(EMA_S_3)

        if prev_1 != new_1:
            prev_1 = new_1

            handshake2[2] = (new_1 >> 4) | 0x10
            handshake2[3] = new_1 & 0xf
            new_1 = new_1 ^ 0xff
            handshake2[4] = (new_1 >> 4) | 0x10
            handshake2[5] = new_1 & 0xf

            uart.write(handshake2)

        if prev_2 != new_2:
            prev_2 = new_2

            handshake2[2] = (new_2 >> 4) | 0x20
            handshake2[3] = new_2 & 0xf
            new_1 = new_1 ^ 0xff
            handshake2[4] = (new_2 >> 4) | 0x20
            handshake2[5] = new_2 & 0xf

            uart.write(handshake2)

        if prev_3 != new_3:
            prev_3 = new_3

            handshake2[2] = (new_3 >> 4) | 0x30
            handshake2[3] = new_3 & 0xf
            new_3 = new_3 ^ 0xff
            handshake2[4] = (new_3 >> 4) | 0x30
            handshake2[5] = new_3 & 0xf

            uart.write(handshake2)

        if (loops % 2170) == 0:
            ctime = monotonic()
            print(2170/(ctime-octime))
            octime = ctime
        loops += 1

#dummy = None
uart = busio.UART(board.TX, board.RX, baudrate=230400, bits=8, stop=1,
                  timeout=0.000)
main()
```
On a trinket m0 it will write a line indicating the number of iterations per second to the serial console. Make sure to hardwire the pins A0, A1 and A2 to `GND` otherwise this number will vary because of the conditional handling of the changes of the ADC's.
To see the issue I saw just comment or uncomment variable `dummy`. Furthermore I saw that when I do not use the `int()` function this behavior does not occur.

I/m running firmware adafruit-circuitpython-trinket_m0-en_US-5.0.0-beta.3.uf2. The 4.1.2 firmware exposes the same behavior.

B.T.W.: The 5.0.0-beta.3 firmware is faster anyway than the 4.1.2 firmware. For this example 5.0.0 is about 6% faster, so that's really nice.

I know that CircuitPython's main goal is not performance, and it is not a big issue for the application I have in mind, but it just made me wonder.

**Comment by tannewt** [comment]
My guess would be that it's changing the lookup pattern in the global dictionary. I'd recommend watching https://www.youtube.com/watch?v=hHec4qL00x0 for some performance tips. Although it is for MicroPython, it applies to CircuitPython as well.
