### ISSUE TITLE
ports/unix builds `micropython` not `circuitpython`

### ISSUE THREAD

**Issue by rhooper** [adafruit/circuitpython#2512]
The unix port builds `micropython` and not `circuitpython`.  The Makefile should probably be updated to build `circuitpython` (the test suite will also need updating).

**Comment by tannewt** [comment]
I'd rather not rename it actually. It won't have any of the hardware APIs and will lead to more confusion about CircuitPython on Raspberry Pi.

**Comment by rhooper** [comment]
Fair enough!
