### ISSUE TITLE
microcontroller.cpu.temperature doesn't work on Teensy 4.0

### ISSUE THREAD

**Issue by rcolistete** [adafruit/circuitpython#2514]
"Adafruit CircuitPython 5.0.0-beta.3-6-g926375d99-dirty on 2020-01-10; Teensy 4.0 with IMXRT1062DVJ6A" halts after :
```
import microcontroller
microcontroller.cpu.temperature
```
Thanks for making CircuitPython available on Teensy 4.0 !

**Comment by manitou48** [comment]
It seems hardware reset occurs with **calibrationData = OCOTP->ANA1;**  in 
sdk/devices/MIMXRT1062/drivers/fsl_tempmon.c
There is working TEMPMON example in SDK and in Teensy4 core

**Comment by manitou48** [comment]
OK this might be the fix:  in sdk/devices/MIMXRT1062/drivers/fsl_tempmon.c before
calibrationData = OCOTP->ANA1;
add  **CLOCK_EnableClock(kCLOCK_Ocotp);**

>>> microcontroller.cpu.temperature
48.1304

**Comment by ladyada** [comment]
@manitou48 nice find! would you like to submit a PR?

**Comment by arturo182** [comment]
How strange, I definitely tested that code before and it did work, wonder if I removed the clock enabling code somewhere, anyway, @manitou48 if you want to fix it, it should probably be here: https://github.com/adafruit/circuitpython/blob/master/ports/mimxrt10xx/common-hal/microcontroller/Processor.c#L36

**Comment by manitou48** [comment]
others can submit a PR ...
