### ISSUE TITLE
STM32: displayio information lost after a user error

### ISSUE THREAD

**Issue by hierophect** [adafruit/circuitpython#2524]
STM32 chips currently lose critical information held in the displays[] array of shared-`module/displayio/__init__.c` under certain circumstances. I've found two specific ones I am able to replicate: 
 - when the user introduces an error to their python code in a sketch using the display screen, _between_ the use of `displayio.release_displays()` and `display_bus = displayio.FourWire(`. This can be tested by inserting random text directly after release_displays. After the error causing text is removed, the entry in displays[0] will be removed, but the pins will remain claimed, meaning the bus is permanently locked and cannot be released. 
 - When a backlight pin in introduced into the declaration of display(). This will both fail to produce a backlight and will cause the display[0] information to be dropped on reset. 

I've attempted to set a watchpoint on display[0] to find out the context in which it changes, but sadly doing so crashes GDB, my STLink, and my serial monitor... so if anyone knows what's up with that, that'd be spiffy.

**Comment by tannewt** [comment]
Sounds to me like `release_displays` isn't correctly releasing anything. The expectation is that all of the pins should be free for reuse. It isn't expected that the display get reinitialized automatically.

**Comment by hierophect** [comment]
Moving to my new machine has solved my debugger crashes so here's some new debugging findings.

**Comment by hierophect** [comment]
whoops bad button press

**Comment by hierophect** [comment]
This was caused by a dangling pointer error related to PWMOut. It will be resolved with the Meowbit patch.
