### ISSUE TITLE
Requesting VID/PID for the OHS2020 badge

### ISSUE THREAD

**Issue by mwelling** [adafruit/circuitpython#2529]
Adding a port and a UF2 bootloader for the open hardware summit badge.

Was asked to change the VID/PID in the PR.
https://github.com/adafruit/circuitpython/pull/2528

Thank you!

**Comment by ladyada** [comment]
OHS2020 badge     VID 0x239A    PID 0x007F  # bootloader
                                PID 0x807F  # arduino
                                PID 0x8080  # circuitpython

**Comment by mwelling** [comment]
Thanks!

**Comment by ladyada** [comment]
:)
