### ISSUE TITLE
Teensy4/1062  SysTick off by one

### ISSUE THREAD

**Issue by manitou48** [adafruit/circuitpython#2536]
if you examine SysTick->LOAD on Teensy4 with circuitpython (tannewt), you will see the value is 599998.  it should be 599999
For Teensy4 branch, problem is in tick.c, SysTick_Config(ticks_per_ms-1);
For arturo's 1062 branch, problem is in ports/mimxrt10xx/tick.c, SysTick_Config(ticks_per_ms-1);
The SysTick_Config() subtracts 1 internally, so you don't need/want the -1 in the function call.
(I don't have one of arturo's 1062 boards, so I have not verified the problem)

For Teensy4, see register dump https://forum.pjrc.com/threads/59040-CircuitPython-on-Teensy-4!?p=226615&viewfull=1#post226615

**Comment by tannewt** [comment]
Thanks for the report! We will no longer use SysTick time keeping once #2685 is merged (we'll use the RTC instead.) So, closing this since it'll be obsolete soon.
