### ISSUE TITLE
Enable DCache on iMX RT

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#2537]
USB in #2532 is having issues. Like not producing the correct data for CDC and MSC. 

https://forum.pjrc.com/threads/59040-CircuitPython-on-Teensy-4!?p=226968#post226968

Will disable the DCache for now and we can fix this and re-enable the DCache after.

**Comment by arturo182** [comment]
I haven't had that issue on the Feathers or evks so I think it might be only on your branch :D

**Comment by hathach** [comment]
> USB in #2532 is having issues. Like not producing the correct data for CDC and MSC.
> 
> https://forum.pjrc.com/threads/59040-CircuitPython-on-Teensy-4!?p=226968#post226968
> 
> Will disable the DCache for now and we can fix this and re-enable the DCache after.

@tannewt can you sum up the discussion in pjrc forum, seem like they have a strict IP restriction. I tried opera but still cannot pass their firewall.
![image](https://user-images.githubusercontent.com/249515/72826807-1e61f880-3cac-11ea-91e4-50c24d24c83f.png)

**Comment by arturo182** [comment]
Ouch, maybe Paul could whitelist your IP.

In the meanwhile, [here's a screenshot](https://user-images.githubusercontent.com/249082/72830000-19874f80-3c80-11ea-8674-4e87b993f7dd.png)

**Comment by jerryneedell** [comment]
@hathach in case it is useful to know, I found that I was getting read errors when reading a file from Flash at 2k bytes into the file -- see note in https://github.com/adafruit/circuitpython/pull/2532

**Comment by tannewt** [comment]
Here is the specific post:

![Screen Shot 2020-01-21 at 10 26 47 AM](https://user-images.githubusercontent.com/52649/72831892-9d1d4e00-3c38-11ea-857c-604b192a6ec3.png)

**Comment by hathach** [comment]
thanks @tannewt @arturo182 @jerryneedell I will try to see if I could help on this issue :) . Another question, where should I find those mentioned scripts **raytrace.py** and **llutm.py** .

@arturo182 It is hard to whitelist since my IP is dynamic :)

**Comment by tannewt** [comment]
@manitou48 would you mind posting your scripts you used in testing here?

**Comment by manitou48** [comment]
[pystuff.zip](https://github.com/adafruit/circuitpython/files/4099846/pystuff.zip)
I've attached a zip with the circuitpython test scripts.  The scripts ran with with previous release of Teensy4 circuitpython and they run with python3.  here are some performance numbers
`           sinperf   fact   llutm  toggle   raytrace(32x32)
pyboard     13679    2129    1593    13.9 us   5.384 s   micropython v1.5
STM32F405   13114    1885    1984              5.123 s   micropython v1.11
STM32F405   59997    9995    5005    38.4     24.636 s   circuitpython
M4          21973    4028    1984    21.4     10.785 s
T4          31006    3662    5371    43.6     13.178 s
`
FWIW, NXP SDK and Teensy 4 core both copy all of FLASH to RAM as part of startup.  Most NXP examples disable cache.  Teensy 4 has functions to clear sections of cache for DMA and IO use. Here is description of memory layout for Teensy 4:
https://www.pjrc.com/store/teensy40.html

**Comment by tannewt** [comment]
This was done in #3522
