### ISSUE TITLE
Check number of bytes buffered on UART bus before attempting to read all

### ISSUE THREAD

**Issue by mmabey** [adafruit/circuitpython#254]
Regarding #209, I had an idea that may help speed things up. Instead of simply waiting for `read()` (and more specifically `common_hal_busio_uart_read()`) to timeout when the buffer is empty, why not just check the length of the input buffer first and request that amount? The use case scenario this fits best is when `read()` is called with no value for `nbytes` specified, meaning they want to read all available bytes.

If a value is specified for `nbytes` and it is less than or equal to the number of bytes available, there still isn't an issue. If `nbytes` is greater than the number of bytes available, IMO this is when it makes sense to allow the function to time out.

I believe this is the function that needs to be changed:
https://github.com/adafruit/circuitpython/blob/5aa8922038a5f0ee07c7c36a3d8eab0547f585bc/shared-bindings/busio/UART.c#L181-L191

**Comment by ladyada** [comment]
we now have `in_waiting` just like pyserial!
see in use here https://github.com/adafruit/Adafruit_CircuitPython_ESP_ATcontrol/blob/master/adafruit_espatcontrol/adafruit_espatcontrol.py#L205
