### ISSUE TITLE
gamepad missing from circuitplayground_express crickit and displayio builds

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#2560]
The CP library now needs `gamepad`, but this native module was turned off a while ago in the CPX crickit and displayio builds for space reasons. One hopes there is room to turn it back on.

Thanks @foamyguy for discovering this issue.

**Comment by tannewt** [comment]
Why does it need gamepad now?

**Comment by dhalbert** [comment]
`gamepad` was added to implement `adafruit_circuitplayground_base.were_pressed` here: https://github.com/adafruit/Adafruit_CircuitPython_CircuitPlayground/pull/51

**Comment by tannewt** [comment]
heh, of course I reviewed it. :-)

**Comment by dhalbert** [comment]
yes, I thought i would not say that explicitly :)

**Comment by dhalbert** [comment]
Fixed by #2565.
