### ISSUE TITLE
Gameduino 3X native module

### ISSUE THREAD

**Issue by jamesbowman** [adafruit/circuitpython#2578]
Gameduino 3/3X are BridgeTek 810/815 emebdded GPUs with touchscreens.

Support for them can be done entirely in Python. Class diagram:

![image](https://user-images.githubusercontent.com/894763/73683811-cfd33780-4677-11ea-8784-0e0996fd236f.png)

By replacing one module (eveL) with a native module, the performance-critical methods are 4-7X faster, measured on a Metro M4.

Python code:
https://github.com/jamesbowman/py-bteve

C module for eveL:
https://github.com/jamesbowman/py-bteve/tree/master/circuitpython-shared-bindings-eveL

**Comment by ladyada** [comment]
nice! want to do a PR?

**Comment by jamesbowman** [comment]
Yes!

**Comment by ladyada** [comment]
yay! feel free to start a draft PR if you'd like - we would only have it turned on for our larger boards like the M4 and nrf52840

**Comment by jamesbowman** [comment]
Done in PR #2581 

Enabled only for metro_m4_express and metro_nrf52840_express.

**Comment by dhalbert** [comment]
Fixed by #2581.
