### ISSUE TITLE
Add The STM32 Port To Docs Module Support Matrix

### ISSUE THREAD

**Issue by sommersoft** [adafruit/circuitpython#2587]
The STM32 port isn't being included in the module [Support Matrix on RTD](https://circuitpython.readthedocs.io/en/latest/shared-bindings/support_matrix.html). 

The port needs to be added here:
https://github.com/adafruit/circuitpython/blob/master/docs/shared_bindings_matrix.py#L29

_Note: could possibly include additional tweaks [here](https://github.com/adafruit/circuitpython/blob/master/docs/shared_bindings_matrix.py#L137) to handle chipset definitions._

I marked it as "Long term", because I'm not sure the milestone that STM is aligned to.

**Comment by hierophect** [comment]
Sorry, I haven't done much docs stuff. STM32 is pretty close to NRF in terms of how mpconfigboard.mk is laid out. Is there anything else that I need to change, beyond adding stm32 to this file?

**Comment by sommersoft** [comment]
@hierophect no need to be sorry, in my opinion. Its a largely undocumented step, and not easily visible. Could probably be added to the "How to add a new board" learn guide.

Adding the port's folder name to the `SUPPORTED_PORTS` list is the starting point. Then I would build the docs and check that everything is correct. If not, the _Note_ above is probably related to the failure point. I haven't been following the STM code-base that closely, so I'm not immediately aware of any idiosyncrasies.

**Comment by hierophect** [comment]
Is there a set of instructions for building the docs locally?

**Comment by sommersoft** [comment]
I've always just opened and copied the CI step. 🤣 https://github.com/adafruit/circuitpython/blob/master/.github/workflows/build.yml#L63

Python environment can be tricky. IIRC, I have a pyenv setup for building. Here are the deps:
```
pip install Sphinx sphinx-rtd-theme recommonmark sphinxcontrib-svg2pdfconverter 
```

**Comment by hierophect** [comment]
Sounds good, thanks for the advice. I'll set up an environment and see how it goes.

**Comment by hierophect** [comment]
@sommersoft my control build (no changes) is not working, unfortunately:
```
Warning, treated as error:
RSVG converter command 'rsvg-convert' cannot be run. Check the rsvg_converter_bin setting
```
Google says this might be related to a missing dependency for sphinxcontrib-svg2pdfconverter. But why would that be any different than the remote build?

**Comment by hierophect** [comment]
Nevermind, just had to install librsvg. Didn't realize I had to do that with brew rather than pip.
