### ISSUE TITLE
Add `busio` support to atmel-samd.

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#259]
This breaks down to:

- [x] I2C
- [x] SPI (non-DMA)
- [x] SPI (DMA)
- [x] OneWire (handled by bitbangio/OneWire)
- [x] UART

**Comment by tannewt** [comment]
I2C support was added with 7292984204e7ac28a5b69c23930ff7b8be003faf

**Comment by dhalbert** [comment]
SPI non-DMA added by #443.

**Comment by tannewt** [comment]
I'm going to close this and make a new issue for DMA. DMA is not needed for the alpha.

Great work @dhalbert!
