### ISSUE TITLE
External Flash Driver for W25Q80DV

### ISSUE THREAD

**Issue by lgnashold** [adafruit/circuitpython#2593]
I'm doing a project with the W25Q80DV external flash, and it looks like circuitpython only supports the W25Q80DL version. It looks like they're nearly identical, except the DV uses a flash device type of 0x40 instead of 0x60. I updated the code so I could use it for my project. I was wondering if it would be worth making a PR to integrate these changes, or if there was a reason only the W25Q80DL is supported.

**Comment by siddacious** [comment]
@lgnashold As far as I know, the only reason it hasn't been a board that needed it yet. Additions are welcome; perhaps even consider making a PR to add your board as well :)
