### ISSUE TITLE
Fomu port of CircuitPython

### ISSUE THREAD

**Issue by ghost** [adafruit/circuitpython#2604]
The Tomu team have a port of CircuitPython here https://github.com/xobs/circuitpython/tree/fomu/ports/litex for the Fomu (new to the Adafruit shop) so while I try to hunt down a Tomu port, you could add the port to the official CircuitPython repository. If I find a Tomu port, I will edit this post.

**Comment by tannewt** [comment]
@xobs want to open a PR for official fomu support?

@aidancuckoo I don't know of a Tomu port. It only has 8k ram so using it won't be pleasant.

**Comment by aidancuckoo** [comment]
@tannewt Apparently there was a mistake with the data import and so mithro, the creator of Tomu fixed the issue, therefore now according to the website, Tomu is not compatible with CircuitPython or even MicroPython.

**Comment by gojimmypi** [comment]
@aidancuckoo do you have any additional details, link to more info, etc? You mention the `Tomu` (the ARM version) but this issue description is `Fomu'  (the FPGA version)

If **F**omu, this must be just regarding the hacker version, and not the production version that Adafruit sells, correct?

I'm certainly curious as to what @xobs has to say, as well.

**Comment by gojimmypi** [comment]
fwiw - I have @tannewt 's Circuit Python working on my FOMU! :) I have a blog about it [here](https://gojimmypi.blogspot.com/2020/04/circuit-python-on-fomu-in-wsl-plus.html). In short, I used the [fomu toolchain](https://github.com/im-tomu/fomu-toolchain/releases) on WSL with the [LiteX port of Adafruit's Circuit Python](https://github.com/adafruit/circuitpython/tree/master/ports/litex).

**Comment by dhalbert** [comment]
We now have a partial port. Closing this. More specific issues can be opened for additional functionality.
