### ISSUE TITLE
nrf: needlessly short SPI DMA cycles?

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#2616]
I noticed that it seems like on nrf our code currently limits SPI transactions to `SPIMx_EASYDMA_MAXCNT_SIZE` (== 16) bytes.  I think MAXCNT_SIZE is actually indicating the number of implemented bits in the MAXCNT register.  I'm not sure how much overhead there is to initiating each transaction, but it could make a difference.

![](https://cdn.discordapp.com/attachments/327298996332658690/677146053992251393/unknown.png)

the number of implemented bits also matches for the PWM peripheral, which has `#define PWM0_EASYDMA_MAXCNT_SIZE 15`

![](https://cdn.discordapp.com/attachments/327298996332658690/677147070792204288/unknown.png)

**Comment by tannewt** [comment]
Good catch! I bet it will speed things up.
