### ISSUE TITLE
Errror loading 5.0 Beta 5 onto NRF52840 Feather Express

### ISSUE THREAD

**Issue by ATMakersBill** [adafruit/circuitpython#2637]
Got this error while copying the .UF2 file onto a NRF58240 in Bootloader mode.
CIRCUITPY drive showed up after this, but I thought I should report it.

Windows 10, got the '840 about 2 months ago.

![image](https://user-images.githubusercontent.com/32851154/74797175-81897f80-5298-11ea-97d9-fae15b219c49.png)

**Comment by dhalbert** [comment]
What is in INFO_UF2.txt? I want to duplicate with the same bootloader version.

**Comment by ATMakersBill** [comment]
UF2 Bootloader 0.2.6 lib/nrfx (v1.1.0-1-g096e770) lib/tinyusb (legacy-525-ga1c59649) s140 6.1.1
Model: Adafruit Feather nRF52840 Express
Board-ID: NRF52-Bluefruit-v0
Bootloader: s140 6.1.1
Date: Dec 21 2018

**Comment by dhalbert** [comment]
I can duplicate this with "UF2 Bootloader 0.2.6", but it works fine with 0.2.9. So just update the bootloader if you want to stop seeing this.

This seems similar to #1575, which was fixed in the bootloader by fixes pertaining to https://github.com/adafruit/Adafruit_nRF52_Bootloader/issues/46.
