### ISSUE TITLE
MKR Zero and Nano 33 IoT released as UF2

### ISSUE THREAD

**Issue by fgallaire** [adafruit/circuitpython#2660]
They need to be released as BIN

**Comment by fgallaire** [comment]
Shouldn't apply to Circuit Playground Express and Trinket M0 (and all M0 board) too as I don't understand how 488 KB and 359 KB UF2 can be flashed on 256 KB MCU ?

**Comment by dhalbert** [comment]
The UF2 files are not densely packed. Each 512-byte block consists of at most 476 bytes of data, and possibly less: https://github.com/microsoft/uf2.

There are UF2 bootloaders available for `mkrzero` and `nano33iot` in https://github.com/adafruit/uf2-samdx1/tree/master/boards, but you are right, we should publish `.bin` as well.

**Comment by fgallaire** [comment]
OK thanks @dhalbert for the explanation

**Comment by fgallaire** [comment]
> There are UF2 bootloaders available for `mkrzero` and `nano33iot` in https://github.com/adafruit/uf2-samdx1/tree/master/boards, but you are right, we should publish `.bin` as well.

Yes, but I see no Arduino boards in the releases

> The UF2 files are not densely packed. Each 512-byte block consists of at most 476 bytes of data, and possibly less: https://github.com/microsoft/uf2.

So, if the .bin file used to generate the UF2 file is under 256 KB, the UF2 file is always goof to be flashed regardless its real size ?

**Comment by tannewt** [comment]
They are now released as bin and uf2.
