### ISSUE TITLE
Publishing a release runs the same set of actions twice

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#2674]
When I publish a release, I see two GitHub Actions jobs starting. Both build everything and upload to S3. Is this some side effect of a release publish, or could we get rid of one of these?

![image](https://user-images.githubusercontent.com/2847802/75635430-0dc66b80-5be4-11ea-8fd0-e361a5469c35.png)

**Comment by tannewt** [comment]
Does this still happen?

**Comment by dhalbert** [comment]
It looks like the problem went away:

![image](https://user-images.githubusercontent.com/2847802/85347235-080fd100-b4c6-11ea-84c8-f62c6d1bdf45.png)
