### ISSUE TITLE
Feather M4 Express has no pin D6 but has D7

### ISSUE THREAD

**Issue by hybotics** [adafruit/circuitpython#2708]
The title pretty well says it all. There is no pin D6 on a Feather M4 Express. There _is_ a pin D7 though. You might want to check the pins for the Feather M0 boards also.

**Comment by hybotics** [comment]
Pin D9 also seems to be affected.

**Comment by dhalbert** [comment]
`board.D6` and `board.D9` are defined: https://github.com/adafruit/circuitpython/blob/master/ports/atmel-samd/boards/feather_m4_express/pins.c. Maybe you installed a different .uf2 on your Feather M4? Which board is listed in `boot_out.txt`, or what shows up in the initial REPL prompt?

**Comment by hybotics** [comment]
You are right, of course. It is the ItsyBitsy that has D7, ACK.
