### ISSUE TITLE
Requesting USB PID for Winterbloom Big Honking Button

### ISSUE THREAD

**Issue by theacodes** [adafruit/circuitpython#2715]
Winterbloom Big Honking Button will be an open source (hardware and software) Eurorack sampler that honks at you 🦆.

PR for board support coming in soon, could I have a USB PID for this? 💜

**Comment by ladyada** [comment]
allocated 0x6005 (GOOS) for you :D
```
HONK BUTTON       VID 0x239A    PID 0xE005  # bootloader
                                PID 0x6005  # circuitpython
                                PID 0x6006  # arduino
```

💜 stay home, do synths! 💜

**Comment by theacodes** [comment]
Hahaha what a perfect PID. Thank you so much!
