### ISSUE TITLE
Mounting boot loader's filesystem

### ISSUE THREAD

**Issue by pmvr** [adafruit/circuitpython#2724]
Hi there,

I would like to know, if and how it is possible to mount the boot loader's filesystem on a board via the `storage` module?
The idea is to upload a new uf2-firmware programmatically and then to a soft reset by  `microcontroller.reset()` to install the new firmware.

Thanks a lot.

Matthias

**Comment by tannewt** [comment]
Unfortunately the bootloader's filesystem is fake. When a UF2 is written it goes directly to the internal flash. This isn't possible to do from CircuitPython since it's running from that flash.
