### ISSUE TITLE
Add support for the seeed wio terminal

### ISSUE THREAD

**Issue by olivier-boesch** [adafruit/circuitpython#2759]
Hello,

This new board embeds a atsamd51 so it could be possible to support it easily.

It also has a realtek 8720dn as a wireless coprocessor (not sure). maybe a library coded in python could enable wireless com.

What do you think about it?

I ordered one and will be happy to act at least as a tester.

**Comment by ladyada** [comment]
yes! please ask seeed to submit a PR! :)

**Comment by olivier-boesch** [comment]
This is done...

**Comment by ladyada** [comment]
great, please follow up with them later :)

**Comment by olivier-boesch** [comment]
The answer speaks by itself :

"Forget circuitpython, our ArduPy will make you feel the magic of programming again."
But I don't agree.

**Comment by PTS93** [comment]
wow.. is that a public github issue you could link to or was that via email?

**Comment by olivier-boesch** [comment]
That's a public post on a seeed forum. see by yourself:

https://forum.seeedstudio.com/t/new-releasing-of-wio-terminal-battery-chassis-and-look-forward-to-your-ideas/251049/7

**Comment by tannewt** [comment]
@olivier-boesch We'd be happy to help you add support to CircuitPython. Just let us know when we can!

**Comment by tannewt** [comment]
@ansonhe97 added the board. Wifi isn't supported though.
