### ISSUE TITLE
Explain when main is running on connect

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#28]
When you plug in the board and main is running make sure that it explains whats going on.

**Comment by tdicola** [comment]
Let's be careful to also support scenarios where it's a script and not a user connecting to the serial output.  Like a script to read sensor readings that are periodically taken by the micropython board.  It would cause problems to suddenly start getting output like 'main.py is running'.  Let's put some kind of global config or function to call to disable the output in main.py or boot.py (see the esp8266 os.debug function for an example of enable/disable debug output--this is kinda similar).

**Comment by tannewt** [comment]
I'm going to close this. Its tricky to detect when USB is actually plugged in versus when the first character is received. That makes it hard to do right.
