### ISSUE TITLE
Requesting VID/PID

### ISSUE THREAD

**Issue by LearnWeaver** [adafruit/circuitpython#2829]
I'm building a robotics board that has a SAMD51, display, optical encoders, motor drivers and a few other sensors. Would I please be able to get a VID/PID.

The robot is called a BBS_StudioBot

Thanks!

**Comment by ladyada** [comment]
```
BBS_StudioBot     VID 0x239A    PID 0x00A1  # bootloader
                                PID 0x80A1  # arduino
                                PID 0x80A2  # circuitpython
```
