### ISSUE TITLE
Ultimate GPS driver needed

### ISSUE THREAD

**Issue by hukuzatuna** [adafruit/circuitpython#284]
There is no current support for the Ultimate GPS boards (breakouts or Featherwings) in CircuitPython. We need to develop a buffered I/O library and command interface for sending and receiving NMEA data.

**Comment by ladyada** [comment]
hiya do you mean parsing out the data? because we do have buffered UART I/O that works quite well:
https://learn.adafruit.com/adafruit-gemma-m0/circuitpython-uart-serial

**Comment by hukuzatuna** [comment]
Yes, @ladyada, it's about creating the classes and methods to abstract the parsing from the user (e.g., breaking out the int into hours, minutes, seconds). This will allow users to make a call like "gps.getLat()" and receive a float decimal degree latitude in response. I currently have this built on top of the busio.UART interface.

**Comment by ladyada** [comment]
ok whew - just makign sure!

**Comment by caternuson** [comment]
> This will allow users to make a call like "gps.getLat()" and receive a float decimal degree latitude in response

Consider using `@property` instead of function call to be more pythonic. Returning both lat and lon in a tuple might be a nice way. Ex:
```python
lat, lon = gps.position
```

**Comment by ladyada** [comment]
hiya this was done by @tdicola 
https://learn.adafruit.com/adafruit-ultimate-gps/circuitpython-parsing
huzzah!
