### ISSUE TITLE
BMP280 driver needed

### ISSUE THREAD

**Issue by hukuzatuna** [adafruit/circuitpython#285]
We don't currently have a BMP280 driver for CircuitPython. Fortunately, we can use the register and busio libraries to simplify writing this one.

**Comment by ladyada** [comment]
hiya i'll be doing this and bme280/680 :)

**Comment by tannewt** [comment]
This done?

**Comment by ladyada** [comment]
yah!

**Comment by caternuson** [comment]
just adding ref:
https://github.com/adafruit/Adafruit_CircuitPython_BMP280
