### ISSUE TITLE
Verify that USB_DEVICES matches settings of CIRCUITPY_USB_HID and CIRCUITPY_USB_MIDI

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#2850]
@xobs ran into TinyUSB problems (#2849) when `USB_DEVICES` included `HID` but `CIRCUITPY_USB_HID` was `0`. The makefiles could check for this inconsistency. If USB_DEVICES was not explicitly set by the build, it could even be adjusted based on the values of `CIRCUITPY_USB_HID` and `CIRCUITPY_USB_MIDI`.

**Comment by jepler** [comment]
Addressed by #3038
