### ISSUE TITLE
STM32: Feather F405 stuck in port.c

### ISSUE THREAD

**Issue by hierophect** [adafruit/circuitpython#2861]
The Feather STM32 currently hangs at startup and cannot connect to USB - it appears we may have had some form of regression later in #2685 that I missed in reviews. On the master branch the Feather will hang indefinitely at the LSE setup flag while loop in port.c (`while(__HAL_RCC_GET_FLAG(RCC_FLAG_LSERDY) == RESET`). My PR #2866 attempts a fix by implementing a timeout that switches to the LSI in the event of a LSE failure. However, even with these changes, the board does not connect. Analyzing with GDB shows only constant iteration through port_get_raw_ticks, but I'm unsure if that's accurate as to what's actually going on during runtime. 

Confirmed only on the STM32F405 Feather for now. I'll update as I test other boards.

**Comment by hierophect** [comment]
@tannewt requesting assistance. Can you replicate this on your feather?

**Comment by hierophect** [comment]
Confirmed issue does not occur on the OpenMV, STM32H7.

**Comment by jerryneedell** [comment]
Confirmed that it does not boot with master at c3b3eb4c2
it does boot with 5.3.0.

**Comment by tannewt** [comment]
@hierophect I don't have cycles to look into this now. I think you fixed it in another PR already anyway. :-)

**Comment by hierophect** [comment]
@tannewt I'm still hanging at boot for the Feather. Just did some additional testing and it seems to also brick the Pyboard, but interestingly, NOT the F411 boards (pyb nano, blackpill). I'll work on tracking this down today if you're busy.

**Comment by hierophect** [comment]
@ladyada do you think I could get the mfn part numbers for the LSE and caps used on the Feather?

**Comment by tannewt** [comment]
@hierophect still need the part info? I can look it up too.

**Comment by hierophect** [comment]
@tannewt I would find it interesting to know for future reference, but clearly it wasn't the cause of the problem, so I don't need it for anything specific. If nothing else had worked I would have run it through STM32's appnote of oscillator compatibility formulas for possible problems.

**Comment by tannewt** [comment]
Kk, it's not super easy for me to get so I'll just close this. I believe #2874 fixes this.

**Comment by hierophect** [comment]
@tannewt I think you mean #2866? If so yes that was the intended fix, I forgot to put in the Resolves keyword.
