### ISSUE TITLE
time.time() can fail in current master

### ISSUE THREAD

**Issue by DavePutz** [adafruit/circuitpython#2872]
A call to time.time() fails with various errors unless a prior call has been made to rtc.set_time_source().

In 5.3 release:
```
>>> import time
>>> time.time()
947386557
```
Using current master:
```
>>> import time
>>> time.time()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: '' object has no attribute 'datetime'
```
This was on a Metro Express M0. On a CircuitPlayground Express it simply crashes into safe mode.

If rtc.set_time_source() is called then time.time() works correctly:
```
>>> import rtc
>>> import time
>>> rtc.set_time_source(rtc.RTC())
>>> time.time()
946685377
```

**Comment by tannewt** [comment]
Fixed by #2881. Thanks @DavePutz
