### ISSUE TITLE
http://adafru.it/mpy-update short URL points to 2.X docs

### ISSUE THREAD

**Issue by siddacious** [adafruit/circuitpython#2882]
context:
https://forums.adafruit.com/viewtopic.php?f=60&t=165259

http://adafru.it/mpy-update forwards to
https://circuitpython.readthedocs.io/en/2.x/docs/troubleshooting.html#valueerror-incompatible-mpy-file

It looks like the short URL needs to be updated to point to 5.X. I can do it but I don't know how/where

**Comment by kattni** [comment]
@siddacious I will ping you privately. As far as I know Internal Dev or PT needs to update it.

**Comment by tannewt** [comment]
@kattni did you have @ptorrone update it yet?

**Comment by siddacious** [comment]
@tannewt I think that ball is in my court. I'll send an email asap

**Comment by siddacious** [comment]
I put in the request just now

**Comment by tannewt** [comment]
Thanks @siddacious!

**Comment by siddacious** [comment]
This has been taken care of
