### ISSUE TITLE
No Module Named analogio

### ISSUE THREAD

**Issue by ArmstrongSubero** [adafruit/circuitpython#2916]
When using the STM32F746ZG discovery get "ImportError: no module named 'analogio'"

**Comment by ArmstrongSubero** [comment]
Digging through the source saw it is not supported. Maybe when I get some time if no one gets around to it I'll do a port.

**Comment by tannewt** [comment]
@ArmstrongSubero Let us know if you need help when adding it. We love getting more contributors involved.

**Comment by ArmstrongSubero** [comment]
I added it. 

https://github.com/ArmstrongSubero/CircuitPython/tree/main/STM32F746ZG%20Analog%20Support/build-nucleo_f746zg

**Comment by ladyada** [comment]
@ArmstrongSubero nice work! next up is a PR, do you need a hand creatinng one?

**Comment by ArmstrongSubero** [comment]
@ladyada Thank you! I'll do a PR in about a week, I want to do some more testing first 😁

**Comment by hierophect** [comment]
@ArmstrongSubero a draft PR is a good place to start - it lets other people check things out but keeps it from being merged if there are other things you want to make sure are added. I have a STM32F746ZG and worked on the F4 AnalogIO previously so if you decide to post a PR I'd be happy to give it a test.

**Comment by ArmstrongSubero** [comment]
@hierophect np I'm swamped today so I'll do one tomorrow.

**Comment by ArmstrongSubero** [comment]
@hierophect I did the PR.
