### ISSUE TITLE
NRF: nRF52833 needlessly allocates 8 kB of RAM to SPIM3

### ISSUE THREAD

**Issue by xobs** [adafruit/circuitpython#2946]
As noted by @dhalbert in https://github.com/adafruit/circuitpython/pull/2933#issuecomment-632859678, the new nRF52833 part does not suffer from the same DMA bug that requires the nRF52840 port to dedicate 8 kB of RAM to SPIM3.

Currently, the one nRF52833 port (Simmel) disables SPIM3, which means it does not have access to the sole fast SPI bus in the system.

The SPIM3 DMA workaround should be special-cased so that it does not get enabled on parts that are not nRF52840.

**Comment by xobs** [comment]
I'm mostly creating this issue so that I don't forget about it!

**Comment by dhalbert** [comment]
> Relatedly, the current linker file only correctly implements the required workaround if `SOFTDEVICE_RAM_SIZE` is a multiple of 8K of at most 56K. 

Right, this should be noted in a comment. The `SOFTDEVICE_RAM_SIZE` was determined by trial and error, and I always meant it to be a multiple of 8K.

> Also, I believe
> 
> https://github.com/adafruit/circuitpython/blob/37e77b21cd3e33b00675310e4070e115d3c2357c/ports/nrf/boards/common.template.ld#L44
> 
> should be `+ LENGTH(SPIM3_RAM)`.

That is correct. Fortunately, `_spim3_ram_end` isn't actually used anywhere. :smiley:

**Comment by riggs** [comment]
Do note that 64K of softdevice RAM (current default) puts the SPIM3 area in the same block as all the other application RAM.

**Comment by dhalbert** [comment]
@riggs You are right, I see what you mean. I missed the non-uniform size of the RAM blocks. I will open a new issue for this.
