### ISSUE TITLE
Optimize the CI builds

### ISSUE THREAD

**Issue by k0d** [adafruit/circuitpython#2969]
I'm opening this issue so that we can discuss how we speed up the builds. Here are a few ideas.

Docker image containing dependencies
Clean gcc-arm-toolchain folder so it contains only needed files (my initial tests show ~600mb can shrink to ~100mb).
Use GitHub Actions caching (https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#using-the-cache-action)

**Comment by MicroDev1** [comment]
We now implement caching in most places and I don't think that there is a need for using a `docker` image in CI now.
We can still however publish a `docker` image with all the CP deps as a package.

**Comment by tannewt** [comment]
Thanks @MicroDev1. I'll close this.
