### ISSUE TITLE
_bleio.ScanEntry.matches() is too strict for "all=True" matches

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#2973]
`bleio_scanentry_data_matches()` in `shared-module/_bleio/ScanEntry.c` returns `false` prematurely if the the first prefix doesn't match the first structure and `!any` is `true`. It should try all the structures.

**Comment by kevinjwalters** [comment]
When fixing this it would be useful to keep an eye on any code which might fail on matching sub-classes of one or two `Advertisement`s. As mentioned in discord, I've had the _same_ code running on three boards which transit to each other and receive each other's broadcasts. Sometimes one goes "deaf" and doesn't pick up a particular sub-classed `Advertisement` for >15s which is really odd compared to its neighbour which receives them fine. The "deaf" CPB then suddenly picks up the next sub-class in the protocol fine. These all have single `prefix` matches on the default matching scheme.

**Comment by kevinjwalters** [comment]
Actually, I'm starting to think it's my code that's getting out of sync with itself. Now I've got my own matching code I can also see more detail when it doesn't match and I have a very small sequence of different `Advertisement` types. I accept the current one and one after but not the one before...
