### ISSUE TITLE
`storage` module is missing from documentation (after stubs conversion?)

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#2976]
I noticed that there are no search hits for `VfsFat` in the [current doc build](https://circuitpython.readthedocs.io/en/latest/search.html?q=vfsfat&check_keywords=yes&area=default)  though it was in the [5.0.x docs](https://circuitpython.readthedocs.io/en/5.0.x/search.html?q=vfsfat&check_keywords=yes&area=default).  I encountered this locally because trying to link to `storage.VfsFat` in stubs documentation for the new `_sdcardio` module failed at doc build time. (#2863)

**Comment by sommersoft** [comment]
Looks like an indentation issue.
- `VsFat`'s doc is indented beyond the start of the lines: https://github.com/adafruit/circuitpython/blob/master/shared-bindings/storage/__init__.c#L170

- `extraxt_pyi` explicitly looks for `.startswith('//|')`: https://github.com/adafruit/circuitpython/blob/master/tools/extract_pyi.py#L24
