### ISSUE TITLE
mimxrt10xx: SSD1306 not working

### ISSUE THREAD

**Issue by hierophect** [adafruit/circuitpython#2977]
Testing the SPI module of the 1010 EVK shows normal results with a BMP280, but has no results with a 128x32 SSD1306 using DisplayIO (screen cross-tested on an STM32 to make sure it works). This could indicate a problem with either SPI or the DisplayIO module on the mimxrt port. 

I don't currently have an I2C version of this screen, or another OLED screen to test with, so if anyone else has a DisplayIO device and a 1010 EVK they could verify this with it'd be helpful. I have this problem both on and before #2964 so testing on either build would be useful information.

**Comment by jepler** [comment]
I re-tested this and the 128x64 OLED is working for me in SPI mode with #4487.  It may have been fixed even earlier.
