### ISSUE TITLE
New bootloader on nRF52840 MDK is incompatible with HEX

### ISSUE THREAD

**Issue by APDevice** [adafruit/circuitpython#2982]
The MakerDiary nRF52840 MDK is now shipping with the UF2 bootloader. It no longer works with the CircuitPython HEX.

**Comment by dhalbert** [comment]
@xiongyihui Would you submit PR's to https://github.com/adafruit/circuitpython https://github.com/adafruit/circuitpython-org to update to .uf2?

**Comment by sommersoft** [comment]
Core repo update is here: https://github.com/adafruit/circuitpython/blob/master/tools/build_board_info.py#L55

I'd recommend changing to `HEX_UF2` so that non-uf2 users will still get releases (for now at least).

**Comment by xiongyihui** [comment]
@APDevice I think you are using nRF52840 MDK USB Dongle.
@sommersoft Thanks for the hint. Will submit a PR later

**Comment by tannewt** [comment]
Fixed by #2986
