### ISSUE TITLE
teensy 4.1 and 4.0 builds not booting

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#2998]
The most recent builds for the teensy 4.1 and teensy 4.0 do nto boot for me
this fails to boot
```
jerryneedell@jerryneedell-ubuntu-macmini:~/projects/adafruit_github/teensy_loader_cli$ ./teensy_loader_cli -mmcu=imxrt1062 -w ~/Downloads/adafruit-circuitpython-teensy41-en_US-20200602-e889287.hex
```
this boots OK 
```
jerryneedell@jerryneedell-ubuntu-macmini:~/projects/adafruit_github/teensy_loader_cli$ ./teensy_loader_cli -mmcu=imxrt1062 -w ~/Downloads/adafruit-circuitpython-teensy41-en_US-5.4.0-beta.0.hex 
jerryneedell@jerryneedell-ubuntu-macmini:~/projects/adafruit_github/teensy_loader_cli$ 
```

same for teensy 4.0

**Comment by jerryneedell** [comment]
the last build that works was:

```
adafruit-circuitpython-teensy41-en_US-20200519-916ca9f.hex 
```
it starts failing with 
```
adafruit-circuitpython-teensy41-en_US-20200520-0af5dd5.hex

**Comment by tannewt** [comment]
@hierophect Do you have teensy's you can test this with?

**Comment by hierophect** [comment]
Well, I've tried this on the 4.0 and something critical is getting reset outside the flash pins, I think. Commenting out reset_all_pins from port_reset results in normal operation so it's definitely a pin overwrite issue... but which pin?

**Comment by tannewt** [comment]
> but which pin?

I'd suggest binary searching it. Make reset_all_pins only reset half of them and then repeat for the bad half.

**Comment by hierophect** [comment]
@tannewt yeah I tried that this morning, it actually fails with *every* pin in never_reset. From what I could briefly gather with the Jlink before it stopped connecting altogether, the chip might actually be crashing when it hits the never reset portion?

**Comment by hierophect** [comment]
True... I'll try stepping through the reset portion more carefully and try and figure out what's going on. Maybe it isn't adding them to never reset, somehow? It'd be weird, since it works just fine on the 1010
