### ISSUE TITLE
Merge in upstream MicroPython changes

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#2999]

**Comment by theacodes** [comment]
A small bump on this, as it's something I'd really love to see happen.

Notable things that we'd get:

- Type annotations (PEP 526).
- Walrus assignment operator (PEP 572).
- Matrix multiplication `@` operator (PEP 465).
- Underscored numeric literals (PEP 515).
- Support for dynamically loading native modules in `mpy` files.
- Numerous code size improvements.
- Significantly better native code emitter.

I don't presently have the time (or expertise) to do this myself, but I would be interested in sponsoring this.

**Comment by dhalbert** [comment]
I am willing to do this when I have time. We are thinking of waiting for the MicroPython 1.13 release.

**Comment by benetherington** [comment]
Bump from me too!

MicroPython 1.13 was released in September, and the walrus assignment operator is very handy for tidy code.

**Comment by timonsku** [comment]
+1 on this from me, being able to write native modules without needing to integrate with the core would be huge.

**Comment by timonsku** [comment]
See https://github.com/pimoroni/pimoroni-pico/tree/main/micropython/modules for a use case for this. This probably ties also into https://github.com/adafruit/circuitpython/issues/2825

**Comment by deshipu** [comment]
@timonsku having been through the process of trying to use that, I have to say it's not as useful as it seems. The problem is that all the functions you are going to call have to be included in a special table at compile time — and only a handful is there by default — so while it's useful for speeding up some purely computational functions, it's very limited otherwise.

**Comment by tannewt** [comment]
I'm also very concerned about the support burden of native modules that work for ARM but not xtensa or risc-v for example. I'd encourage folks to write native modules in the core instead. We're happy to have them.

**Comment by garethhcoleman** [comment]
Is this separate issue still valuable alongside #4280?

**Comment by tannewt** [comment]
> Is this separate issue still valuable alongside #4280?

Ya, I think so. Issues can live when inactive and PRs should be closed when they are. We can close this when the 1.14 merge is done.

**Comment by ladyada** [comment]
nice!
