### ISSUE TITLE
_bleio.ScanEntry.matches(..., all=) keyword arg conflicts with all()

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#3007]
`all` is a keyword arg for `_bleio.ScanEntry.matches()`, but `all()` is also the name of a builtin function, and so the keyword arg is flagged by pylint, etc. as masking the builtin function name. So let's change the arg name.

**Comment by dhalbert** [comment]
To make this transition smooth, we should add an alternate name for `all`, change all the libraries, and then remove `all()`. So we may need to defer removing all until 7.0.0.

`match_all` is probably a good alternate name.

**Comment by tannewt** [comment]
`match_all` sounds good to me.

**Comment by tannewt** [comment]
I'll add the `match_all` kwarg so we can remove `all` in 8.
