### ISSUE TITLE
_bleio.ConnectionError conflicts with standard exception ConnectionError

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#3008]
pylint will complain in some cases about `_bleio.ConnectionError` shadowing the original global `ConnectionError` exception.

Let's consider changing the name of the `_bleio` exception.

**Comment by dhalbert** [comment]
@tannewt What do you think about adding a new name aliased to the old name for 6.0.0, and then drop in 7.0.0? I'm not sure what a better name is, maybe `ConnError` or `BluetoothConnectionError` or `BTConnectionError`.

**Comment by dhalbert** [comment]
The basic problem is that:
```python
from _bleio import ConnectionError
```
will trigger a pylint complaint, because it's shadowing the system exception.

Another alternative I thought of is simply to drop `_bleio.ConnectionError`, and use the system-provided `ConnectionError` for that particular error. We don't provide `_bleio.IOError`, etc., so using the system `ConnectionError` may be clear enough.

**Comment by tannewt** [comment]
Using the native one is fine with me. You could have the BLE version inherit from ConnectionError to start.
