### ISSUE TITLE
SD card hangs

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#301]
if you remove the SD card between read/write's (say in repl) theres no timeout or error

**Comment by kattni** [comment]
Tested with 3.0b. When SD card is removed, the code continues for a short time, and then eventually hangs. There is no error thrown. This is more likely to be an error in the adafruit_sdcard driver.

**Comment by dhalbert** [comment]
This does appear to be an `adafruit_sdcard` issue. Closing this in favor of:https://github.com/adafruit/Adafruit_CircuitPython_SD/issues/8.
