### ISSUE TITLE
Rename "master" branch to "main"

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#3021]
It's a clearer term with less history.

**Comment by dhalbert** [comment]
https://github.com/desktop/desktop/issues/6478 did something equivalent, and mentions a few things to make sure to change. Also, there are mentions of that issue by a bunch of other folks, so check out the linked issues at the end, for further things  to check for.

**Comment by tannewt** [comment]
We could also rename ***all*** of our repos programmatically.

**Comment by tannewt** [comment]
Here is a blog with tips from @shanselman : https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx

**Comment by tannewt** [comment]
Had one github action to update: #3024

**Comment by jerryneedell** [comment]
FYI -- just came across this https://www.washingtonpost.com/opinions/2020/06/12/tech-industry-has-an-ugly-master-slave-problem/?utm_campaign=wp_opinions_pm&utm_medium=email&utm_source=newsletter&wpisrc=nl_popns

**Comment by stefanoborini** [comment]
-1. Context matters. This is newspeak.

**Comment by tannewt** [comment]
We want to do this in the long term but will likely wait to hear more from GitHub until we do all of the library repos. CircuitPython core is already switched over.

**Comment by tannewt** [comment]
@kattni Have we finished switching libraries over?

**Comment by kattni** [comment]
@tannewt For the most part. Everything else is being tracked within its own repo. This can be closed.
