### ISSUE TITLE
More visible warning on old version docs pages

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/circuitpython#3022]
On the older version docs pages such as this one: https://circuitpython.readthedocs.io/en/4.x/shared-bindings/displayio/Group.html

There is a warning at the top and center but I find it somewhat easy to overlook when I arrive on a docs page from a google search or other link.

The two ideas for improvement I had were to make the warning a bolder color and/or make it scroll with the page so it's always visible.

**Comment by FoamyGuy** [comment]
I use the Django docs somewhat frequently as well and tend to overlook the warning less. Here is an example of their out of date pages: https://docs.djangoproject.com/en/2.1/

The warning is a top bar and it stays with the user as they scroll.

**Comment by tannewt** [comment]
@sommersoft Any idea about how to implement this?

**Comment by dhalbert** [comment]
This is not hard to do in CSS, something like:
.warning {
```css
  position: fixed; /* Set to fixed position */
  top: 0; /* Position at the top of the page */
}
```

**Comment by sommersoft** [comment]
I actually tried that in developer mode (with `position: sticky`). Didn't work for me (yet). Also, there is no unique ID for that box; just using `admonition` or `warning` would apply to any of them in the documentation. Which, we have some scattered throughout.

That box is inserted by RTD's rendering, so without a good way to CSS it, there's not much to do. I peeked in the RTD docs, and it's barely mentioned that this happens, and there is nothing really beyond that. https://docs.readthedocs.io/en/stable/versions.html#version-warning

**Comment by FoamyGuy** [comment]
I'm not sure I fully understand how Sphinx and Read the Docs work together to create the docs pages (or if there are other components at work). So perhaps I am overlooking something. It looks like there is support for custom js code: https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html

It would be ideal if that warning already had a unique id or class to target with a CSS rule. But since it doesn't maybe it's possible to use custom JS code to find the version warning box based on it's contents and then add an id or class to it.

**Comment by sommersoft** [comment]
I actually just found out why setting the `position` in CSS isn't working. RTD's theme sets `overflow-x: hidden` on the entire HTML body, which breaks the usage of `position`.

Disabling `overflow-x` allows it to sticky, but there are some side-effects (more than I'm aware of, I'm sure). 

I can at least select the only box we're worried about with the proper CSS selector:
```css
.document > .admonition {
    position: sticky;
    top: 0px;
}
```
One side-effect I'm seeing is some float-like behavior:
![rtd_sticky_warning PNG](https://user-images.githubusercontent.com/21211479/84209104-d8e77180-aa7a-11ea-92a0-2b34a7150660.jpg)

**Comment by sommersoft** [comment]
This invocation produces fairly good results for me on Chrome:
```css
.document > .admonition {
    position: sticky;
    top: 0px;
    background-color: salmon;
    z-index: 2;
}

body {
    overflow-x: unset!important;
}
```
4.x and earlier don't seem to call the `docs/static/customstyle.css` on RTD, so that will need to be fixed for it to be applied I think.

![rtd_css_sticky_outdated](https://user-images.githubusercontent.com/21211479/84212476-9a09e980-aa83-11ea-9216-6b58d1135335.png)

**Comment by FoamyGuy** [comment]
hierophect asked in the discord about a way to hide the notification if it is made sticky. I agree that we should try provide a way to do that if possible. 

Here is a bit of Javascript that will hide the notification when it gets clicked on:
```javascript
$(".document > .admonition").click(function(){$(this).hide()});
```
I tested in with the browser console on the live docs page and it seems to be working. 

Clicking on the latest version link does fire this listener and hide the box, but it does not interfere with being taken to the next page. If we wanted we could target a smaller zone for click-ability like just the title bar, or add an X in the corner.

**Comment by simontorres** [comment]
So, this has been already solved? should this issue be closed?

**Comment by tannewt** [comment]
Yup! Thank you @simontorres
