### ISSUE TITLE
External Interrupt

### ISSUE THREAD

**Issue by CaptainJackey** [adafruit/circuitpython#3029]
Will circuitpython add the GPIO External Interrupt funtion later?

**Comment by tannewt** [comment]
We won't be adding the external interrupt callback that MicroPython has.

At some point we'd like to support external interrupts as a sleep wakeup though.

**Comment by CaptainJackey** [comment]
> We won't be adding the external interrupt callback that MicroPython has.
> 
> At some point we'd like to support external interrupts as a sleep wakeup though.

Imagine that scene, I want to use a GPIO input (SWITCH) to control several funtions of a system, and maybe some funtions have delay inside. And how could check the SWITCH efficiently without External Interrupt in CircuitPython?

**Comment by tannewt** [comment]
See #1380
