### ISSUE TITLE
MIMXRT1020-EVK unable to get SPI working

### ISSUE THREAD

**Issue by timonsku** [adafruit/circuitpython#3055]
Running CPY 5.3.0 I'm trying to use SPI bus 1 which is mapped to D11-D13 in the pins config here:
https://github.com/adafruit/circuitpython/blob/main/ports/mimxrt10xx/boards/imxrt1020_evk/pins.c#L19-L21
Here the excerpt from the datasheet:
![image](https://user-images.githubusercontent.com/2370185/85236597-9b41fb80-b41f-11ea-867a-02eab9ede537.png)
I defined my SPI bus like so:
`spi = busio.SPI(clock=board.D13,MOSI=board.D12,MISO=board.D11)`

D12/GPIO_AD_B0_13 is designated as  "LPSPI1_SDI" which I have to assume is Secondary Device Input aka MOSI so that sounds correct to me but CPY complains that its an invalid SPI pin selection.

I reverse MISO and MOSI it does not complain but posts:
`common_hal_busio_spi_write: status 400`

I can not test anything higher than 5.3 unfortunately as that seems to crash, the CPY drive never comes up.

**Comment by jepler** [comment]
We believe this the error "common_hal_busio_spi_write: status 400" has been fixed #4048.  Please feel free to re-open (or open a fresh issue if "re-open" is not available) if this problem still exists.

We are aware of the problem getting the 1020-EVK to work at all (#3510) and hope to address it soon.

Note that in the datasheet, "SDI" indicates Serial Data In from the point of view of the microcontroller, which is MISO (microcontroller in, secondary out) in SPI parlance.
