### ISSUE TITLE
Allow custom builds to disable CDC, MSC in a better way

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#3065]
In #3038 @dhalbert suggested that it would be beneficial to allow CDC and MSC to be disabled just like MIDI and HID can be now.  He gives a rationale there.

So:
 * Add CIRCUITPY_USB_CDC and CIRCUITPY_USB_MSC
 * Check them at various sites as appropriate to disable code and/or built in modules
 * Use them to compute the USB_DEVICES string, instead of always including CDC and MSC
   * A Makefile trick to deal with not getting a leading comma will be necessary
 * When done, remove the ability to directly specify USB_DEVICES, it's unneeded at that point.

Note that this does not mean the CircuitPython definition is changing e.g., to allow devices without MSC into the core!  However, we do wish to enable people to make custom builds that are not in the core that have these disabled for various reasons.

**Comment by dhalbert** [comment]
Fixed by #4689 and previous PR's.
