### ISSUE TITLE
USB: Check number of descriptors at build time

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#3066]
In #3038 @dhalbert noted it would be handy to check that the enabled USB devices fit within the MCU-specific number of USB descriptors:
> Another check we could add (this is getting complicated) is counting endpoints for boards with limited endpoints, and warning you there are too many. It has to know CDC takes 2, and others take only one. It could count words/commas in USB_DEVICES.

As it stands, I think such builds succeed but crash when loaded on a board.

**Comment by jepler** [comment]
@dhalbert didn't you add this checking to all platforms when you added the 2nd CDC?  If so, please close.

**Comment by dhalbert** [comment]
I didn't even know there was an issue :). FIxed by #4215.
