### ISSUE TITLE
ESP32-S2 not recognized on Windows

### ISSUE THREAD

**Issue by PTS93** [adafruit/circuitpython#3075]
Using the Saola-1 Wroom devkit and running CircuitPython 6.0 alpha or 5.4.0 beta or really any CPY version that I tried I can't get the device to enumerate on Windows. On a Ubuntu 18.04 machine it shows up as a MSC drive and I can connect to REPL.
On Windows 10 1909 I just get an error that the USB device malfunctioned.

I would assume that this is an issue with TinyUSB and not CPY but I wanted to open it here in case it is not. I have not verified if TinyUSB standalone would work.
@hathach

**Comment by hathach** [comment]
@PTS93  can you verify that it work with bare metal example from tinyusb here 
https://github.com/hathach/tinyusb/tree/master/examples/device/cdc_msc_freertos

just run `idf.py build flash`

**Comment by PTS93** [comment]
Ok this is odd. Now that I formatted the CPY drive in Linux through the REPL it now shows up on Windows too. Maybe that was the issue that the FAT device was not properly formatted and windows is picky there? Or I'm having an issue with the connector here. It was picky with Linux too when I used a breadboard for the native USB.

**Comment by PTS93** [comment]
I took a closer look at my bread board. Turns out I chose the exact point where the breadboard had a short which caused D- to short to VBUS. It's an intermittent short and I guess Linux was more tolerant to that.
![2020-06-27 13 55 27](https://user-images.githubusercontent.com/2370185/85921699-43235300-b87e-11ea-84dc-ca73aba4f372.jpg)
