### ISSUE TITLE
STM32: Add RTC Module

### ISSUE THREAD

**Issue by dglaude** [adafruit/circuitpython#3085]
'''Adafruit CircuitPython 5.4.0-beta.1 on 2020-06-08; Feather STM32F405 Express with STM32F405RG

>>> import time
>>> time.time()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: RTC is not supported on this board'''

**Comment by dhalbert** [comment]
Fixed by #6468.
