### ISSUE TITLE
WeChat group?

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#3110]
Hi @dahanzimin, @ryevertigo, @namaRyo, and any other Chinese devs, would you be interested in starting a WeChat group for CircuitPython? I can sort out how to get an account. Thanks!

**Comment by notelainemade** [comment]
Hello Scott @tannewt, this is Elaine from Seeed! We just finished the LCD driver added into Wio Termina today :)  I will be glad to join the WeChat group to share more CircuitPython dev process for the community in China. May I add your WeChat if you already get the account?

**Comment by tannewt** [comment]
Hi Elaine! I don't have an account yet but you can always email me scott@adafruit.com too. I'll let you know when I have a WeChat account.

**Comment by tannewt** [comment]
Ok, I'm `tannewt` on WeChat now! 🎉

**Comment by namaRyo** [comment]
Hi, my name is Ryo Ikuyama. my weChat id is "ikuyama"
please invite me if I can join.

**Comment by notelainemade** [comment]
My wechat id is "iamElaineee"!

**Comment by notelainemade** [comment]
@tannewt  Sent request

**Comment by ptorrone** [comment]
@tannewt please add `adafruit` when ya can too! (that's our wechat id)

**Comment by hierophect** [comment]
Hey all. Would anyone be willing to help verify my account? Would love to help with any stm32 discussions.

**Comment by tannewt** [comment]
@namaRyo I invited you as a friend and can add you to the group chat after that.

**Comment by dahanzimin** [comment]
> 大家好。有人愿意帮我核实一下我的账户吗？愿意帮助任何stm32讨论。

@hierophect What is your wechat? May I add you to discuss the STM32 series

**Comment by hierophect** [comment]
Hi @dahanzimin, I have not been able to get a wechat because I do not know any mainland Chinese people who can help me with security verification. Would you be interested in helping me verify my account? I would love to discuss the STM32.

**Comment by dahanzimin** [comment]
> Hi @dahanzimin, I have not been able to get a wechat because I do not know any mainland Chinese people who can help me with security verification. Would you be interested in helping me verify my account? I would love to discuss the STM32.

I'm very happy. I understand that you need to download the wechat app and register with your mobile phone number. Of course, I haven't registered wechat overseas, or how can I help you complete the security certification

**Comment by dahanzimin** [comment]
> Hi @dahanzimin, I have not been able to get a wechat because I do not know any mainland Chinese people who can help me with security verification. Would you be interested in helping me verify my account? I would love to discuss the STM32.

@hierophect I Baidu, need security authentication QR code, you send me email, I help you authentication, 353767514@qq.com

**Comment by hierophect** [comment]
![IMG_A4AEF5270476-1](https://user-images.githubusercontent.com/5904176/87332252-4c145580-c509-11ea-93c1-bd1a1c8b7e26.jpeg)
@dahanzimin

**Comment by tannewt** [comment]
@dahanzimin I'm on WeChat as `tannewt` and we have a CircuitPython group setup I'll invite you to.

**Comment by tannewt** [comment]
Closing. Folks can add me on WeChat and I'll add you to the group.
