### ISSUE TITLE
ItsyBitsy M4 Express resets itself periodically

### ISSUE THREAD

**Issue by AdinAck** [adafruit/circuitpython#3111]
Every 15 seconds or so my ItsyBitsy will reset itself, even with no code on it. I just got it today and am barely able to program it since it keeps disconnecting and reconnecting with my computer. I have the latest CircuitPython release on it.

**Comment by AdinAck** [comment]
old bootloader caused the issue

**Comment by jepler** [comment]
Hey, thanks for the update, I'm glad you were able to resolve the problem.  I was just writing a response suggesting that you take this to our customer service forums: https://forums.adafruit.com/viewforum.php?f=62
