### ISSUE TITLE
Requesting a new PID for FeatherSnow v2

### ISSUE THREAD

**Issue by ndGarage** [adafruit/circuitpython#3115]
I'm requesting a VID/PID for my new SAMD21E18-based FeatherSnow v2. This revision is tested OK. 

The change includes several fixes in hardware like reassign pins and some cosmetic touch. A preliminary page is up on Hackaday. The link is https://hackaday.io/project/173537-feathersnow-v2.

Thanks,
-Henry

**Comment by ladyada** [comment]
feathersnow     VID 0x239A    PID 0x00B9  # bootloader
                                PID 0x80B9  # arduino
                                PID 0x80BA  # circuitpython
