### ISSUE TITLE
Docs title tag always shows 0.0.0

### ISSUE THREAD

**Issue by dunkmann00** [adafruit/circuitpython#3134]
I've noticed this for a while but didn't think much of it at first. Now I think it definitely seems like it shouldn't be like this. On all the pages for the CP docs the html title shows the version as 0.0.0. As a result of this, if you Google 'circuitpython docs' the name for the page also shows 0.0.0. Is this intended?

**Comment by tannewt** [comment]
It is not intended. I think it's a matter of getting the version into the sphinx config.

**Comment by dunkmann00** [comment]
I took a crack at this one, I don't have any experience with Github workflows...or sphinx docs, but I think that pull request may work!
