### ISSUE TITLE
Crash into safe mode from REPL due to voltage dip when connecting I2C breakout

### ISSUE THREAD

**Issue by siddacious** [adafruit/circuitpython#3139]
Board is a Metro M4 with UF2 2.0.0
Sensor is a prototype AS7341 but it will occur with nearly every sensor I use

![image](https://user-images.githubusercontent.com/1183985/87074557-e4da6680-c1d3-11ea-927a-dd9d82e7dcd8.png)
I will update my UF2 version and try to get some info on the voltage levels

**Comment by dhalbert** [comment]
I have reproduced this on CircuitPython 5.3.0 on a Metro M0 and on A Feather M4. The Feather seems a bit less sensitive: a couple of sensors did not trigger this. I did not reproduce it on a Feather Sense (nRF52840).

It happens when plugging in a STEMMA sensor, or if you interrupt the power lines on one that is already plugged in.

**Comment by dhalbert** [comment]
I am not sure if there's anything to fix or work around on the software side. If there really is a glitch in the 3.3V rail that drops it below the 2.7V brownout level, then that's an electrical issue which could be significant. For instance, the external QSPI flash chips are not spec'd for operation below 2.7V, and could read or write bad data if their voltage dips.

**Comment by siddacious** [comment]
@dhalbert Indeed there is a pretty substantial dip, well below 2.7V:
![image](https://user-images.githubusercontent.com/1183985/87176273-bb324580-c28e-11ea-94b4-16a8f5046d91.png)

Here's the capture from the screenshot above:
https://www.dropbox.com/s/gk8usbzqbtujw2x/sensor_insert_vcc_sag.sal?dl=0
Note that this is from the Logic 2 alpha so you'll have to have that installed to view it

I'll close this since it does seem to be unrelated to CircuitPython
