### ISSUE TITLE
Requesting a VID/PID for a new nRF52840 based board called TinkeringTech ScoutMakes Azul

### ISSUE THREAD

**Issue by tinkeringtech** [adafruit/circuitpython#3146]
Hi,

Requesting a VID/PID for a new Circuitpython, Feather form factor based board call TinkeringTech Scoutmakes Azul. 
Will be submitting a PR to add to CP. Its based on the Adafruit nRF52840 express with some additions:

-128x32 OLED built-in
-USB type C
-Power switch

At the home stretch of getting the boards out.
https://www.instagram.com/p/CBdmkFbJNzQ

Thanks for the work on CP!

**Comment by dhalbert** [comment]
Here you go:

```
TinkeringTech Scoutmakes Azul  VID 0x239A    PID 0x00BD  # bootloader
                                             PID 0x80BD  # arduino
                                             PID 0x80BE  # circuitpython
```
