### ISSUE TITLE
Add board.ID method for pulling which board is running your code.

### ISSUE THREAD

**Issue by Andon-A** [adafruit/circuitpython#316]
At the moment, different boards use different pin methodology for IDing their pins. These match the silkscreen on the device itself, which is great. However, this can be annoying for porting code from one device to another, especially if the only thing that changes is pin designations. A special case is for examples: The "Blink" example for one board doesn't necessarily work on another board, and that's one of the most simple examples there is.

Implementing an "ID" function in the board library could allow for easily coding a small library that returned the correct pins, or including code to allow for a program to be uploaded onto a different board without changing the program itself.

Realistically, it would only have to return a string. board.ID() would return "ESP8266" or "Feather M0 Basic" or whatever board it happened to be running on. That would allow for the following code to work for a blink example that would work on both a Feather M0 Basic and ESP8266:

```
import digitalio
import board
import time

led = 0

if board.ID = "ESP8266":
    led = digitalio.DigitalInOut(board.GPIO0)
elif board.ID = "Feather M0 Basic":
    led = digitalio.DigitalInOut(board.D13)

led.direction = digitalio.Direction.OUTPUT

while True:
    led.value = not led.value
    time.sleep(0.5)
```

**Comment by tannewt** [comment]
The board is available through the `os.uname()` tuple result as `machine`.

```
Adafruit CircuitPython 2.0.0 on 2017-09-12; Adafruit Trinket M0 with samd21e18
>>> import os
>>> os.uname()
(sysname='samd21', nodename='samd21', release='2.0.0', version='2.0.0 on 2017-09-12', machine='Adafruit Trinket M0 with samd21e18')
>>>
```
