### ISSUE TITLE
One use of ble_drv_remove_event_handler may not remove handler due to second arg being NULL

### ISSUE THREAD

**Issue by kevinjwalters** [adafruit/circuitpython#3171]
I noticed an unusual call to `ble_drv_remove_event_handler` a few days ago. The previous line assigns NULL to the second argument:

https://github.com/adafruit/circuitpython/blob/8f928340c68fc5ef590546039b0a3db44502415b/ports/nrf/common-hal/_bleio/Adapter.c#L474-L478

Since both arguments are used together to find the entry:

https://github.com/adafruit/circuitpython/blob/8f928340c68fc5ef590546039b0a3db44502415b/ports/nrf/bluetooth/ble_drv.c#L80-L92

I believe that call to `ble_drv_remove_event_handler` will not work as intended and will leave this event handler active in some way. This also could create a small memory leak.

I've not executed this code, I just noticed it looked different to the other uses in the code so I may be wrong here. I may have mentioned this in comments on another ticket but that eludes me at the moment.

**Comment by dhalbert** [comment]
I think you're right, those lines should be reversed.
