### ISSUE TITLE
Feather M0 Adalogger does not have D8 or D7

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#323]
D8 is the internal green LED
D7 is the interral Card Detect pin  (can be called SD_CD if ya like)
but those pins aren't exposed :)

**Comment by tannewt** [comment]
Did you get D7 and D8 from `board`? It looks like you shouldn't https://github.com/adafruit/circuitpython/blob/master/atmel-samd/boards/feather_m0_adalogger/pins.c

**Comment by ladyada** [comment]
yah it should have them, but doesnt yet :)
they're 'internal' to the adalogger - not exposed on the breakout. 
D7 is PA21
D8 is PA06

**Comment by tannewt** [comment]
Ah ok! Is it urgent or can we have this a beginner task? It'd be to the file linked above:

- [ ] Add PA21 as `D7` and `SD_CD`
- [ ] Add PA06 as `D8` and `GREEN_LED`

**Comment by ladyada** [comment]
its a good beginner task

**Comment by mrmcwethy** [comment]
@Andon-A are you still working on this issue?

**Comment by Andon-A** [comment]
@mrmcwethy Yes, I just haven't had a lot of spare time to actually build it and put it on the adalogger to make sure I didn't screw up.

**Comment by Andon-A** [comment]
This is addressed in PR #461 - Marking as closed.
