### ISSUE TITLE
display glitches in spirit level demo with "latest" 6.0.0-alpha.2-143-gc394af412 

### ISSUE THREAD

**Issue by d-c-d** [adafruit/circuitpython#3247]
installed 
  adafruit-circuitpython-clue_nrf52840_express-en_US-20200803-c394af4.uf2
(boot message "Adafruit CircuitPython 6.0.0-alpha.2-143-gc394af412 on 2020-08-03; Adafruit CLUE nRF52840 Express with nRF52840" )

there are glitches on the display
![image](https://user-images.githubusercontent.com/15486587/89374941-7f2dad00-d6a1-11ea-8624-82d0bcaffb8f.png)
and eventually the screen becomes two white bars
![image](https://user-images.githubusercontent.com/15486587/89375005-a08e9900-d6a1-11ea-8875-079fd8a51323.png)

installing
  adafruit-circuitpython-clue_nrf52840_express-en_US-6.0.0-alpha.2.uf2
boot_out.txt: "Adafruit CircuitPython 6.0.0-alpha.2 on 2020-07-23; Adafruit CLUE nRF52840 Express with nRF52840
" yields pretty spirit level display with no glitches

![image](https://user-images.githubusercontent.com/15486587/89375142-eba8ac00-d6a1-11ea-9739-2eb8cc909fda.png)

was using the "latest" libraries
  adafruit-circuitpython-bundle-6.x-mpy-20200804.zip

**Comment by DavePutz** [comment]
Looks like this is being caused by the optimization improvement in PR #3190. I will open a PR to revert that for the Clue.
