### ISSUE TITLE
USB VID/PID Request for PicoPlanet

### ISSUE THREAD

**Issue by bleeptrack** [adafruit/circuitpython#3253]
Hi,
I'm currently working on a series of SAMD21 boards that have procedurally generated decorations and capacitive touch buttons:
https://twitter.com/Bleeptrack/status/1291013322062659586

I'd like to compile my own version of the adafruit trinket bootloader to give CPY support to my boards. Would it be possible to receive a VID/PID for this purpose? This would be amazing.

Thank you very much!

**Comment by ladyada** [comment]
those PCBs are so cute!!!!

**Comment by jepler** [comment]
I agree! 
![image](https://user-images.githubusercontent.com/1517291/89648399-c45e0480-d884-11ea-8a8b-adc1d2bdd686.png)

**Comment by ladyada** [comment]
```
BleepTrack PicoPlanet    VID 0x239A    PID 0x00C1  # bootloader
                                PID 0x80C1  # arduino
                                PID 0x80C2  # circuitpython
```

**Comment by caternuson** [comment]
> procedurally generated decorations

:astonished: :thumbsup: neat!
