### ISSUE TITLE
Document more differences between various builds

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#328]
The [Core Modules Support Matrix](https://github.com/adafruit/circuitpython/blob/master/shared-bindings/index.rst) lists some of modules are implemented in one port but not another. However, there are other differences that should be documented somewhere:
1. Other modules that are not in `shared-bindings` that differ, e.g. `framebuf` is not in non-Express samd builds.
2. Language features that differ, such as presence of absence of `reversed()`.

**Comment by tannewt** [comment]
`framebuf` and other modules outside of `shared-bindings` aren't listed because they aren't supported. Ideally, only shared-bindings modules are supported because that structure ensures they are documented well too.

**Comment by tannewt** [comment]
@dhalbert Mind doing this soon so we can close this issue? Thanks!

**Comment by tannewt** [comment]
Done in #863
