### ISSUE TITLE
Add `traceback.format_exception()`

### ISSUE THREAD

**Issue by ThomasAtBBTF** [adafruit/circuitpython#3301]
It is great that sys has:
sys.print_exception(exc, file=sys.stdout)
but it would be helpful if the exceptionstring would be available as well to process in it.

**Comment by tannewt** [comment]
Is there a CPython API you are referring to? I don't see `sys.exceptionstring` here: https://docs.python.org/3/library/sys.html

**Comment by ThomasAtBBTF** [comment]
Hmm,
in CPython I do:
    exc_type, exc_value, exc_traceback = sys.exc_info()
    errorlines = traceback.format_exception(exc_type, exc_value, exc_traceback)
and this will give me what I want!
Somewhere inside CircuitPython there must be code which generates "errorlines".
And these "errorlines" are printed inside "sys.print_exception"
I am looking for a way to get to these "errorlines" without the need to print them!

**Comment by trailhead** [comment]
This would be handy in cases where you have a hard UART for debugging, but the REPL isn't working for whatever reason.  I'm printing my exceptions to the UART, but don't know how to get the traceback, line, or filename.

**Comment by microDev1** [comment]
We now have `CPython` compatible `traceback` module implemented. Adding `format_exception()` is the next step.
