### ISSUE TITLE
USB VID/PID Request for microS2

### ISSUE THREAD

**Issue by microDev1** [adafruit/circuitpython#3319]
Hi,

I'm currently working on an esp32-S2 based board.
I'd like to give CPY support to my boards. Would it be possible to receive a VID/PID for this purpose? 

Thanks!

**Comment by microDev1** [comment]
> Hi, are you a company or an individual? If a company, which company? Thanks.

@dhalbert I am an individual.

**Comment by dhalbert** [comment]
```
microDev1 microS2  VID 0x239A 

PID 0x00C5  # bootloader
PID 0x80C5  # arduino
PID 0x80C6  # circuitpython
```
