### ISSUE TITLE
PIN STRONG!

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#332]
are we using strong mode? lets do it!
![image](https://user-images.githubusercontent.com/1214161/31629215-f56baa00-b280-11e7-9f1b-f026ab29cf35.png)

**Comment by dhalbert** [comment]
btw, I looked in the arduino_samd core both upstream and our version, and DRVSTR is apparently not set to strong in either one. (It's not even mentioned in `cores/`. There's even a bug about it: https://github.com/arduino/ArduinoCore-samd/issues/158. We can still set it to strong in CircuitPython.

**Comment by ladyada** [comment]
tested, does make a difference with LEDs so i'd like to stick DRVSTR = 1

**Comment by dhalbert** [comment]
Fixed by #341.
