### ISSUE TITLE
Broken or missing NOR flash is not appropriately detected

### ISSUE THREAD

**Issue by hierophect** [adafruit/circuitpython#3323]
As noted by @jepler, `spi_flash_init` within `supervisor_flash_init` is responsible for creating the NOR flash device based on pins assigned in the board profile. However, if the JEDEC ID is not returned by the NOR flash, no error is currently logged, allowing the device to proceed as if it has a filesystem but without any actual filesystem capabilities. This could be altered to emit some form of failure mode to inform the user that there is a hardware issue with their NOR flash. 

Confirmed on the Feather STM32F405 by setting the NOR flash pins to an incorrect set of SPI flash pins not connected to the NOR flash. `os.listdir('/')` results in a return of `[]`, and `storage.erase_filesystem()` crashes the Circuitpython board until it is manually reset.

**Comment by dhalbert** [comment]
Fixed by #5785. Now goes into safe mode if CIRCUITPY can't be mounted or created. Tested by trying on some boards that have bad flash chips or bad connections.
