### ISSUE TITLE
ESP32-S2 WROVER: additional memory not supported

### ISSUE THREAD

**Issue by emard** [adafruit/circuitpython#3328]
I downloaded this

[Adafruit CircuitPython Saola-1 WROVER board](https://adafruit-circuit-python.s3.amazonaws.com/index.html?prefix=bin/espressif_saola_1_wrover/en_US/)

and tried to get free memory but about 64K is free where 2MB PSRAM
should be on WROVER board

import gc; gc.collect(); gc.mem_free()
63792

**Comment by askpatrickw** [comment]
Hey @emard  the ESP32-S2 support is still in progress but good news the PSRAM support is in this PR: https://github.com/adafruit/circuitpython/pull/3315

**Comment by emard** [comment]
I will continue following this PR thread so we can close this issue
