### ISSUE TITLE
Update ESP8266 neopixel_write to work with CP neopixel.py

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#334]
Update the neopixel_write code for the ESP8266 so it works with the neopixel.py driver in the Adafruit_CircuitPython_Neopixel

This was originally reported as an issue with the driver:
[https://github.com/adafruit/Adafruit_CircuitPython_NeoPixel/issues/15](url)

**Comment by tannewt** [comment]
Done in c6a15f7. Thanks @jerryneedell!
