### ISSUE TITLE
_bleio.Adapter.start_scan does not validate max timeout size

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#3340]
The timeout size for an nRF SD scan (if one is given) is 16-bits, which is in units of 10ms. `common_hal_bleio_adapter_start_scan()` should validate that the incoming timeout will fit. Currently it does not, so any value gets converted to 10ms units and then is truncated to 16 bits.

**Comment by kevinjwalters** [comment]
My REPL experiments with `timeout=7200.0` yielded actual durations of `648.035`, `648.112`, `648.035` based on `time.monotonic_ns()` timing on a CLUE (with `auto_refresh` off) running 5.3.0.

**Comment by dhalbert** [comment]
Fixed by #3861.
