### ISSUE TITLE
ulab missing ulab.linalg.norm function

### ISSUE THREAD

**Issue by kevin-tracy** [adafruit/circuitpython#3343]
ulab.linalg.norm function is in the documentation but not present on my version of circuitpython. 

I'm using the following board:

Adafruit CircuitPython 5.3.1 on 2020-07-13; Adafruit Grand Central M4 Express with samd51p20

Thank you. 
```
Adafruit CircuitPython 5.3.1 on 2020-07-13; Adafruit Grand Central M4 Express with samd51p20
>>> from ulab.linalg import norm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name norm
```

**Comment by jepler** [comment]
Hi!

It appears that we added linalg.norm sometime after the 5.3.1 release.  It is not listed in the documentation page for 5.3.1: https://circuitpython.readthedocs.io/en/5.3.x/shared-bindings/ulab/__init__.html

At this time, it's necessary to use a prerelease, such as 6.0.0-alpha.3, to have this function available.

Please let us know if you try 6.0.0-alpha.3 and still run into this problem.
