### ISSUE TITLE
USB VID/PID Request for MuseLab nanoESP32-S2

### ISSUE THREAD

**Issue by maditnerd** [adafruit/circuitpython#3351]
I'd like to give CPY support to nanoESP32-S2 boards on behalf of MuseLab. 
Would it be possible to receive a VID/PID for this purpose?

I didn't find any VID/PID in MuseLab documentation : https://github.com/wuxx/nanoESP32-S2

I'm an individual with no affiliation with Muselab.

Thanks!

**Comment by dhalbert** [comment]
If you plug one of the boards in now, what VID/PID does it show?

**Comment by tannewt** [comment]
@wuxx Please provide a USB VID and PID for this board.

**Comment by wuxx** [comment]
Hi，nanoESP32-S2 has two USB port，one connect to CH340 which is usb to serial IC from WCH，
the another USB is from ESP32-S2，the USB VID & PID is define in your code，We  hasn't register USB VID & PID currently.

**Comment by maditnerd** [comment]
I reupload the default firmware (from https://github.com/wuxx/nanoESP32-S2), and I got this VID/PID used for tiny USB Mass storage
VID: 0xCAFE
PID: 0x4003

Should I use this one ? I don't know how to check if this is a valid VID/PID.

Here is USBDeview screenshot
![image](https://user-images.githubusercontent.com/2841495/91813778-7b0a9600-ec33-11ea-8c80-7703bb1dea76.png)

**Comment by wuxx** [comment]
this vid/pid is the demo code from expressif, if just for test yourself, you can use it freely

**Comment by maditnerd** [comment]
I want to add this board to circuitpython, I follow @tannewt's instructions but I need a unique VID/PID to finish my pull request.
So I guess as cool as having CAFE ☕ as VID is, it won't be OK for this purpose ?

**Comment by wuxx** [comment]
ok.... if you or ciruitpython don't care about the USB vid/pid register things... just use it.
and the vid CAFE currently not belong to any company...

here is some reference:
How to obtain an USB VID/PID for your project
https://www.voti.nl/docs/usb-pid.html

The USB ID Repository
http://www.linux-usb.org/usb-ids.html

How to get a PID code
http://pid.codes/howto/

**Comment by tannewt** [comment]
@ladyada How do you want to handle this?

**Comment by ladyada** [comment]
@tannewt getting to some old emails, @dhalbert can allocate a pid

**Comment by dhalbert** [comment]
okee, will do tomorrow

**Comment by tannewt** [comment]
@maditnerd Please use:

```
MuseLab nanoESP32-S2       VID 0x239A    PID 0x00DE  # bootloader
                                         PID 0x80DE  # circuitpython
```

**Comment by maditnerd** [comment]
Thanks ❤️ , i'll check what i've done (probably rewatch @tannewt video), and do a pull request on both **adafruit/circuitpython** and **adafruit/circuitpython-org**

I asked my sister (who is a photographer) to take a picture of the board.

![muse_lab_esp32](https://user-images.githubusercontent.com/2841495/93311441-4c311a00-f806-11ea-9412-0511c301de82.jpg)

**Comment by tannewt** [comment]
Pic looks awesome! I've merged both PRs so I'll close this. Thanks for the addition!
