### ISSUE TITLE
Reading the value of an output pin behaves differently in ESP32S2 than in SAMD

### ISSUE THREAD

**Issue by anecdata** [adafruit/circuitpython#3353]
Is this a bug, or is it explicitly undefined behavior to read the value of an output?
```
>>> import board
>>> from digitalio import DigitalInOut, Direction
>>> led = DigitalInOut(any_gpio)
>>> led.direction = Direction.OUTPUT
```

PyPortal (alpha.3):
```
>>> led.value = True
>>> led.value
True
```
(the LED is ON)

vs.

Saola (alpha.3):
```
>>> led.value = True
>>> led.value
False
```
(the LED is ON)

_[edited to explicitly show pin is set up in either case as an output]_

**Comment by jepler** [comment]
If it's not intended to be able to read back the value previously set on an output pin, accessing the value property to read it should give an exception.

I think the problem arises because the esp-idf defines the return value of this routine in a surprising way, rather than returning the value currently driven onto the pin:
```
 * @brief  GPIO get input level
 *
 * @warning If the pad is not configured for input (or input and output) the returned value is always 0.
 *
 * @param  hw Peripheral GPIO hardware instance address.
 * @param  gpio_num GPIO number. If you want to get the logic level of e.g. pin GPIO16, gpio_num should be GPIO_NUM_16 (16);
 *
 * @return
 *     - 0 the GPIO input level is 0
 *     - 1 the GPIO input level is 1
```

**Comment by anecdata** [comment]
FWIW, input behaves the same on both. It's conceptually an easier case to make that it's an error since the value is controlled by an external source:
```
>>> pin = DigitalInOut(any_gpio)
>>> pin.direction = Direction.INPUT
>>> pin.value
False
>>> pin.value = True
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: Cannot set value when direction is input.
```
