### ISSUE TITLE
Check write_value on ESP32-S2 and other ports

### ISSUE THREAD

**Issue by hierophect** [adafruit/circuitpython#3447]
The STM32 port has recently been modified to properly acknowledge the `write_value` parameter during SPI reads (#3431). However, numerous ports still ignore it, including ESP32-S2, NRF52, and Spresense. These ports should be tested to see what their behavior during reads actually is, and whether it may cause bugs with certain devices that have been overlooked up to now.

**Comment by jepler** [comment]
This works for sure on esp32-s2 (I was using SD cards with it today), but is appears it's not properly supported on nrf or spresense.  Oddly, sdcardio was tested and working on feather sense https://learn.adafruit.com/adafruit-microsd-spi-sdio/feather-sense-adalogger-featherwing.
