### ISSUE TITLE
Examples are outdated

### ISSUE THREAD

**Issue by Andon-A** [adafruit/circuitpython#345]
The examples in the aptly-named /examples directory are out of date, some extremely so. It appears that they're all microPython based

These should be updated, replaced, or removed, and organized depending on what boards they run on.

My preferences:

- If it relies on specific hardware that there is no CircuitPython board comparable to, remove it.
- If its purpose is outside the scope of CircuitPython, remove it. 
- If we can adapt it to a specific CircuitPython board (I'm looking at you, Circuit Playground), do so.
- If it's an easy update, bring it into line with to-be-created guidelines.

**Comment by tannewt** [comment]
@Andon-A this would be awesome! Are you up for it?

**Comment by Andon-A** [comment]
Absolutely. I'm guessing most of them will end up being completely re-done or removed, but first up is the guidelines.

**Comment by tannewt** [comment]
Guidelines look good to me!

**Comment by fmorton** [comment]
I submitted a pull request for one converted example and added a new one in the process. Glad to do more if you would like.

**Comment by tannewt** [comment]
At minimum we should delete unsupported docs and examples by 3.0.

**Comment by fmorton** [comment]
I will get to this in the next couple weeks if no one else does.

Frank

**Comment by tannewt** [comment]
Great! Thanks Frank!
