### ISSUE TITLE
readthedocs removes file extension from URLs

### ISSUE THREAD

**Issue by timonsku** [adafruit/circuitpython#3479]
If you go to f.e. https://circuitpython.readthedocs.io/en/latest/CONTRIBUTING.html
Clicking on any link that is supposed to go to a markdown file in the github repo yields a 404 because it removes the file extension.
F.e. instead of linking to `https://github.com/adafruit/circuitpython/blob/main/CODE_OF_CONDUCT.md` (notice the **.md**)
it links to `https://github.com/adafruit/circuitpython/blob/main/CODE_OF_CONDUCT`

The markdown file this page is based on is correct though, it includes the file ending in the URL. So I assume this gets lost in the processing somewhere.

**Comment by sw23** [comment]
I explored this issue as part of hacktoberfest and found that this is actually an issue with the recommonmark package, and has been fixed (though a new package version has yet to be released):
https://github.com/readthedocs/recommonmark/pull/181
https://github.com/readthedocs/recommonmark/commit/e821106417bddaa76b1808cf4fce7d65d2459dd2

It's probably worth waiting for a new package version.

**Comment by PTS93** [comment]
Great find, thanks. I nudged them if they might consider a release, this seems to have been the only commit since may.

**Comment by tannewt** [comment]
@sw23 thank for looking into this! Please feel free to mention me on any PRs to circuitpython or libraries that you want to count for Hacktoberfest.

**Comment by theacodes** [comment]
We could install directly from source in our requirements.txt:

```
git+https://github.com/readthedocs/recommonmark.git@e821106#egg=recommonmark
```

I'm happy to send a PR to do this if y'all want.

**Comment by tekktrik** [comment]
Has this been fixed?  It looks like the CODE OF CONDUCT now links to an online page (HTML) instead of 404'ing.  Or am I misunderstanding?

**Comment by prcutler** [comment]
> Has this been fixed? It looks like the CODE OF CONDUCT now links to an online page (HTML) instead of 404'ing. Or am I misunderstanding?

tekktrik appears to be right.  I tested both the original link and the only other Markdown I could file, and both pages load the HTML page and no longer 404:

* https://docs.circuitpython.org/en/latest/docs/common_hal.html (common_hal.md)

Unless I'm misunderstanding too, this can be marked fixed and closed.

--Paul

**Comment by tekktrik** [comment]
@adafruit/circuitpythonlibrarians I think this can potentially be closed
