### ISSUE TITLE
ESP32-S2 os.rename() not possible

### ISSUE THREAD

**Issue by emard** [adafruit/circuitpython#3488]
at ESP32-S2 I unmounted USB-storage drive from PC
and tried to rename a file, not permitted because of read-only filesystem?

os.rename("file1.bin","file2.bin")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 30] Read-only filesystem

**Comment by deshipu** [comment]
The file system is by default mounted read-only to avoid corruption when it's modified through USB. You have to re-mount it as read-write to perform any file operations. See https://learn.adafruit.com/circuitpython-essentials/circuitpython-storage

**Comment by emard** [comment]
thnx it works!
