### ISSUE TITLE
MatrixPortal crashes into safe mode (CircuitPython core code crashed hard. Whoops!)

### ISSUE THREAD

**Issue by wifijt** [adafruit/circuitpython#3506]
CircuitPython 6 Beta 1 

Matrix Portal M4

Trying to run the Moon Phase Clock for Adafruit Matrix Portal

Crashes hard and I have to reload CircuitPython from the bootloader to recover

[boot_out.txt](https://github.com/adafruit/circuitpython/files/5319504/boot_out.txt)

[code.txt](https://github.com/adafruit/circuitpython/files/5319509/code.txt)

**Comment by jepler** [comment]
I have reproduced this problem on my matrixportal.  I ran the following lines at the REPL and got the same behavior (safe mode reset):
```
>>> from adafruit_matrixportal.matrix import Matrix
>>> MATRIX = Matrix(bit_depth=4)
```

**Comment by jepler** [comment]
Thanks for the report @wifijt -- you should now be able to grab a fixed firmware by using the "absolute latest" link at https://circuitpython.org/board/matrixportal_m4/ or wait for the next prerelease to come out.  Either way, please let us know your results!
