### ISSUE TITLE
Update ESP-IDF to official version

### ISSUE THREAD

**Issue by hierophect** [adafruit/circuitpython#3516]
Despite the name, #3492 does not actually update to the master branch of the ESP-IDF - due to a compatibility issue in TinyUSB, we are now simply on a more up-to-date fork. Once TinyUSB is working with the most recent version of the Espressif IDF repo, we should switch to a stable release. This will allow faster integration of new features and newly enabled modules, which are still under active development for the ESP32-S2.

**Comment by hierophect** [comment]
@hathach if you are able to dig up anything in your testing, please track update in this issue.

**Comment by hathach** [comment]
Pr is on the way :)
