### ISSUE TITLE
MatrixPortal M4 A0 in use error

### ISSUE THREAD

**Issue by makermelissa** [adafruit/circuitpython#3552]
When attempting to use board.A0 with CircuitPython 6.0 Beta 2 with NeoPixels, I am seeing this error:
```
code.py output:
Traceback (most recent call last):
  File "code.py", line 4, in <module>
ValueError: A0 in use
```

It can be reproduced with this simple bit of code
```
import board
import digitalio

pin = digitalio.DigitalInOut(board.A0)
```

**Comment by makermelissa** [comment]
Oh, looks like it requires a soft reboot.

**Comment by makermelissa** [comment]
FYI, I also tried this with the absolute newest image and the behavior is still there, so it hasn't been fixed yet.

**Comment by tannewt** [comment]
Can you reproduce this on a Metro M4? I don't have a MatrixPortal yet.

**Comment by makermelissa** [comment]
I'll give it a try.

**Comment by makermelissa** [comment]
It did not have the same issue despite them both using PA02 for A0.

**Comment by tannewt** [comment]
Does it work after a soft reboot but not in the first run of code.py?

**Comment by makermelissa** [comment]
It works when it first starts up, but the pin doesn't work after a soft reboot like it's not getting reset or something.

**Comment by makermelissa** [comment]
It also does the same thing with A2, but A1, A3, and A4 act normal.

**Comment by tannewt** [comment]
I have no idea why this would be the case for *just* this board. I'll get one in a few days and see if I can reproduce it. Thanks!

**Comment by tannewt** [comment]
Ok, I see this on my MatrixPortal too.

**Comment by dhalbert** [comment]
@martingosnell Answerd in #5440.
