### ISSUE TITLE
PID for new boards

### ISSUE THREAD

**Issue by Targett363** [adafruit/circuitpython#3553]
Hi I'm going through Kattni's How to "Add a New Board to CircuitPython" for my ESP32S2 Module Clip board and I'm pretty much there except for needing a VID&PID, well 2 I guess as you can attach either WROOM or WROVER variants to the board.

The guide suggests asking for help here...

**Comment by dhalbert** [comment]
Could you give us a "manufacturer" name and official board names?

**Comment by Targett363** [comment]
I am the Manufacturer "Targett" and the Board names are "ESP32S2 Module Clip" Wroom and Wrover.
I'd propose the name targett_module_clop_wroom and targett_module_clip_wrover in my fork.

**Comment by Targett363** [comment]
https://www.tindie.com/products/20752/

**Comment by tannewt** [comment]
Here is the other PR: https://github.com/pidcodes/pidcodes.github.com/pull/564

**Comment by Targett363** [comment]
Scott, tank you so much. Git newbie, I thought I'd done something fatally wrong over there.
