### ISSUE TITLE
ESP32S2 build fail

### ISSUE THREAD

**Issue by BradChan** [adafruit/circuitpython#3575]
cd ports/esp32s2
make BOARD=muselab_nanoesp32_s2

Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
Unable to check whether maximum number of endpoints is respected
IDF_PATH=/home/cyz/circuitpython/ports/esp32s2/esp-idf cmake -S . -B build-muselab_nanoesp32_s2/esp-idf -DSDKCONFIG=build-muselab_nanoesp32_s2/esp-idf/sdkconfig -DSDKCONFIG_DEFAULTS="esp-idf-config/sdkconfig.defaults;esp-idf-config/sdkconfig-opt.defaults;esp-idf-config/sdkconfig-4MB.defaults;boards/muselab_nanoesp32_s2/sdkconfig" -DCMAKE_TOOLCHAIN_FILE=/home/cyz/circuitpython/ports/esp32s2/esp-idf/tools/cmake/toolchain-esp32s2.cmake -DIDF_TARGET=esp32s2 -GNinja
CMake Error: The source directory "/home/cyz/circuitpython/ports/esp32s2/build-muselab_nanoesp32_s2/esp-idf" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
Makefile:248: recipe for target 'build-muselab_nanoesp32_s2/esp-idf/config/sdkconfig.h' failed
make: *** [build-muselab_nanoesp32_s2/esp-idf/config/sdkconfig.h] Error 1

**Comment by skieast** [comment]
Usually a **make BOARD=(whatever) clean** does it for me. 
I actually always do the following when building (in my case under the fish shell and WSL2)
```
cd ports/esp32s2/esp-idf
./install.fish   
set -x IDF_PATH $PWD 
source $PWD/export.fish      
cd ..
make BOARD=(something) clean
make BOARD=(something) 
 ```
