### ISSUE TITLE
Circuit Playground Express status LED?

### ISSUE THREAD

**Issue by ajs256** [adafruit/circuitpython#3585]
Hello,

I was wondering if there was any way to use one of the built-in LEDs on the Circuit Playground Express (or even an external one) in a similar way to the status NeoPixel or Dotstar seen on other boards.

I use VSCode for editing code, and it’s kind of a pain to have to `screen` in to get to the REPL or output.

**Comment by tannewt** [comment]
You can modify the CircuitPython build to set `MICROPY_HW_NEOPIXEL` like here: https://github.com/adafruit/circuitpython/blob/main/ports/nrf/boards/feather_nrf52840_express/mpconfigboard.h#L33

Build instructions for CircuitPython are here: https://learn.adafruit.com/building-circuitpython

This VSCode plugin may be a simpler solution: https://github.com/joedevivo/vscode-circuitpython
