### ISSUE TITLE
Socket missing recv_into. Using more memory to be compatible

### ISSUE THREAD

**Issue by Sembazuru** [adafruit/circuitpython#3604]
I downloaded adafruit-circuitpython-matrixportal_m4-en_US-6.0.0-rc.0.uf2 and adafruit-circuitpython-bundle-6.x-mpy-20201024.zip tonight for the AdaBox16 that I recieved yesterday. For every query through the esp32 in all the demos (for example the moon phase clock) that I tried I get the following error message: "Socket missing recv_into. Using more memory to be compatible". The demos all seem to work, so maybe it is just a warning.

**Comment by makermelissa** [comment]
Yeah, this is just a warning until a different library gets updated. You can ignore.
