### ISSUE TITLE
busio.SPI only supports 8bit words. Possible to change?

### ISSUE THREAD

**Issue by CARMICH** [adafruit/circuitpython#3634]
Hello!
busio.SPI only supports 8bit words. I only need 40 bit words. Could I just change all the unt8 to unt40 in the spi.h and spi.c, then create a new uf2 of cpy to flash on my express board?

**Comment by jepler** [comment]
Hi and thanks for your question.  The circuitpython issue tracker is not the best place for questions, please consider using our [forums](https://forums.adafruit.com/) or [discord chat](https://adafru.it/discord) for asking questions.

If you need to send a 40-bit message on the SPI bus, the way to do it is to prepare a 5-byte piece of data to send.  Assuming that you are using a board with "long int" support (most boards except those with M0 microcontrollers), you can make such an array of bytes like so, depending on the order in which the bytes need to be presented ("big" or "little" endian):
```
>>> l = 0x1112131415
>>> l.to_bytes(5, 'big')
b'\x11\x12\x13\x14\x15'
>>> l.to_bytes(5, 'little')
b'\x15\x14\x13\x12\x11'
```

There are other ways to convert between integers and bytes, such as the struct module, but that only supports standard 1/2/4/8 byte widths.
