### ISSUE TITLE
GrayScale OLED not working in rc.1

### ISSUE THREAD

**Issue by makermelissa** [adafruit/circuitpython#3646]
I tested using I2C. There were no errors, it just didn't display anything. It does work with the absolute latest, however when it does an autoreload it does not run until you unplug and replug in the board. It seems like the I2C port is not being reset.

**Comment by makermelissa** [comment]
I just noticed RC.1 is available and will try it with that.

**Comment by makermelissa** [comment]
Oops, just realized I had originally noticed the issue in rc.1.

**Comment by tannewt** [comment]
Please post your test code and also note what board you are using. Does it work on other ports?

**Comment by makermelissa** [comment]
I'm using a Feather M4 Express and my test code is at https://github.com/adafruit/Adafruit_CircuitPython_SSD1327/blob/master/examples/ssd1327_simpletest.py

**Comment by makermelissa** [comment]
What do you mean ports? Like different pins or do you mean a different board?

**Comment by tannewt** [comment]
I mean a different board with a different chip. (Not just another SAMD51)

**Comment by tannewt** [comment]
This works for me on 6.0.0-rc.1 on the Feather M4 Express and the latest SSD1327 library (1.2.0). I just commented out the display_text bits to reduce my dependencies.

**Comment by dhalbert** [comment]
@makermelissa Do you still see this with the same or different test conditions as @tannewt? This does not seem to be a showstopper for 6.0.0 any more unless you are doing something different.

**Comment by makermelissa** [comment]
Oh right. I'll check again.

**Comment by makermelissa** [comment]
I just tried again and it's working.

**Comment by dhalbert** [comment]
OK, great! Thanks.
