### ISSUE TITLE
How can redirect the REPL output on the screen

### ISSUE THREAD

**Issue by BradChan** [adafruit/circuitpython#3654]
I have a board Esp32s2 saola wrover that connected to a display(st7789). It works perfect. I want to show the REPL  on the screen like board Clue.

**Comment by ladyada** [comment]
easy - simply create the displayio for that display
https://learn.adafruit.com/circuitpython-display-support-using-displayio
https://github.com/adafruit/Adafruit_CircuitPython_ST7789
