### ISSUE TITLE
Booting from the SD card

### ISSUE THREAD

**Issue by kahveciderin** [adafruit/circuitpython#3700]
Title says it all, I don't want the boot.py/main.py on the internal flash, rather in the SD card. How may I accomplish this?

**Comment by tannewt** [comment]
We don't support it because the SD card may not exist. You can use `import` to load code off the SD card from `main.py`. https://github.com/adafruit/circuitpython/pull/3454 also provides a new way to reload the VM and run a different file.

**Comment by kahveciderin** [comment]
@tannewt  soo can I put the precompiled python data to the internal flash on the samd51 and tell the samd to execute a file from the sd card?

**Comment by ladyada** [comment]
there isnt 'precompiled python' in the sense that it is executed. python is interpretted only. you can use mpy-cross to mpy'ify a py file, that only makes it more compact (bytecode conversion). then import it as any other python code

**Comment by tannewt** [comment]
@kahveciderin I'm not sure what you are trying to accomplish.

**Comment by kahveciderin** [comment]
@ladyada yeah that was what i meant

@tannewt i am trying to execute a file from the sd card, without the external flash.

**Comment by tannewt** [comment]
@kahveciderin Please explain the larger context. I want to understand why you are trying to execute without internal flash.

We don't have a way to execute from the external flash without something on the built in flash fs.

**Comment by kahveciderin** [comment]
@tannewt let's say I have soldered the flash chip out. I want to execute from the sd card. Is this possible?

**Comment by deshipu** [comment]
You can compile a version that uses a part of the internal flash for the filesystem.

**Comment by tannewt** [comment]
@kahveciderin It is not possible with the current code. As deshipu points out, you could have a code.py on an internal filesystem to configure and run off the sd card.

**Comment by kahveciderin** [comment]
@tannewt do I need to edit the ```run_code_py``` function in the main.c file?

**Comment by tannewt** [comment]
@kahveciderin It depends on how you are mounting the SD card. If you mount it to / then you shouldn't need to.
