### ISSUE TITLE
storage.remount("/", True) resulting in RuntimeError on 6.1.0-beta.2

### ISSUE THREAD

**Issue by Neradoc** [adafruit/circuitpython#3709]
So I'm encountering the following with the latest build from S3.
The following boot.py (no matter if using True or False).

```python
import storage
storage.remount("/", False)
```

Results in the following boot_out.txt
```
Adafruit CircuitPython 6.1.0-beta.0 on 2020-11-17; FeatherS2 with ESP32S2
boot.py output:
Traceback (most recent call last):
  File "boot.py", line 2, in <module>
RuntimeError: Cannot remount '/' when USB is active.
```

And the read/write status of the drive is not changed as expected no matter what.

**Comment by kattni** [comment]
Adding info from #3833 - storage.remount("/", True) resulting in RuntimeError on 6.1.0-beta.2 

When working through [this CircuitPython storage example](https://learn.adafruit.com/circuitpython-essentials/circuitpython-storage) on QT Py M0, running 6.1.0-beta.2, it fails to work properly - the temperature logging file is never created and the filesystem never switches to read-only. Checking `boot_out.txt`, I find the following traceback:
```
Traceback (most recent call last):
  File "boot.py", line 18, in <module>
RuntimeError: Cannot remount '/' when USB is active.
```
I tried attaching it to a USB battery pack, thinking it meant the USB data connection - this did not resolve the issue, the results are the same. Tried the example on a Trinket running 6.1.0-beta.2, and the results are the same.

I tried the QT Py and Trinket running 6.0.0, and the example works properly.

**Comment by vivianasalcedo** [comment]
The solution they presented to store the microcontroller temperature in a file does not work. Although it was written in the boot.py storage.remount("/", FALSE), it does not work in a cyclic way, it does it only once, that is, it only saves the temperature once. I wonder how to solve this problem?
The solution they presented to store the microcontroller temperature in a file does not work. Although it was written in the boot.py storage.remount("/", FALSE), it does not work in a cyclic way, it does it only once, that is, it only saves the temperature once. I wonder how to solve this problem?

**Comment by dhalbert** [comment]
We think we fixed the bug. If you think there is a new bug, could you file an issue with complete details, or could you ask for help in discord: https://adafru.it/discord or the forums: https://forums.adafruit.com/viewforum.php?f=60 ? We need to see the code you're using and the versions you're using.

**Comment by vivianasalcedo** [comment]
I don't think it is corrected, in the boot.py is the following code "short version":
storage.remount("/", FALSE)

It is assumed that when it is FALSE in the above command, then a file can be opened and written to. 


while TRUE:
             file = open("temperature.txt", "wr")
             file.write(str(int(int(microcontroller.cpu.temperature))))
             file.close()

**Comment by dhalbert** [comment]
Are you using `FALSE`/`TRUE` or `False`/`True`. The latter is correct.

Please show your whole code, both boot.py and code.py.

**Comment by Neradoc** [comment]
> Although it was written in the boot.py storage.remount("/", FALSE), it does not work in a cyclic way, it does it only once, that is, it only saves the temperature once. I wonder how to solve this problem?

Booleans notwithstanding, that is to be expected, `open(...,"wr")` will truncate the file, so you overwrite it with the last temperature every time. You want `"a"` for append.

**Comment by vivianasalcedo** [comment]
boot.py : 
import board
import digitalio
import storage

cambio =  digitalio.DigitalInOut(board.D2)
cambio.direction = digitalio.Direction.INPUT
cambio.pull = digitalio.Pull.UP
storage.remount("/", cambio.value)
print(cambio.value)

**Comment by vivianasalcedo** [comment]
code.py:
import microcontroller
import time
import board
import digitalio

while True:
    temp = microcontroller.cpu.temperature
    file = open("temperatura.txt","wr")
    file.write('{0:f}\n'.format(int(temp)))
    file.close()
    time.sleep(3)

**Comment by dhalbert** [comment]
As @Neradoc mentions, change `"wr"` to `"wa"`:
```py
    file = open("temperatura.txt","wr")
```

**Comment by vivianasalcedo** [comment]
not working

**Comment by dhalbert** [comment]
I see you on discord. Let's discuss there rather than here.

**Comment by vivianasalcedo** [comment]
which means wa

**Comment by vivianasalcedo** [comment]
unfortunately it doesn't work, do you have more examples of how to save files in circuitpython?

**Comment by vivianasalcedo** [comment]
Thanks for your help Neradoc and dhalbert, I did it again with more calm and I really wrote again in the same line, now I can add the data to the .txt file.
