### ISSUE TITLE
ESP32S2: common_hal_mcu_delay_us() not yet implemented

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#3739]
On ESP32S2 right now, `common_hal_mcu_delay_us()` looks like this, and doesn't do any delays.
```c
void common_hal_mcu_delay_us(uint32_t delay) {

}
```

This routine is used in a number of places (I2C pullup detection, `PulseIO`, display stuff), so it is probably causing some problems.

**Comment by ladyada** [comment]
heh

**Comment by dhalbert** [comment]
workin' on a simple fix :)
