### ISSUE TITLE
The firmware of esp32-s2 is normal by nano official test. Is there a problem with the board?

### ISSUE THREAD

**Issue by 60999** [adafruit/circuitpython#3751]
I'm sorry to disturb you. I use nanoesp32-s2 / firmware from https://github.com/wuxx/nanoESP32-S2/blob/master/firmware/flash_ image_ cdc_ msc.bin, write it to 0x00, connect gpio19 and gpio20 (the schematic diagram is the same as nano, add resistance in the middle), insert USB2.0 interface into the computer, and successfully display the small U disk.

Then we use adafruit circuit Python muselab_ nanoesp32_ s2-zh_ Latn_ Pinyin-6.0.0.bin, write to 0x00

Serial terminal display:
```

ESP- ROM:esp32s2-rc4-20191025

Build:Oct 25 two thousand and nineteen

rst:0x1 (POWERON), boot:0x8 (SPI_ FAST_ FLASH_ BOOT)

SPIWP:0xee

mode:DIO , clock div:2

load:0x3ffe6100 , len:0x8

load:0x3ffe6108 , len:0x18a0

load:0x4004c000 , len:0x930

load:0x40050000 , len:0x2cc8

entry 0x4004c1b4
```

What is the reason for this? How can I fix this problem?

**Comment by 60999** [comment]
By the way, my motherboard is the esp-12k development board nodemocu-32-s2

**Comment by tannewt** [comment]
What is the issue? That UART output looks ok.

**Comment by tannewt** [comment]
I don't know anything about uPyCraft. If it is running successfully, you should see a drive appear. You can build a debug version of CircuitPython and see what UART logging you get with that.

**Comment by 60999** [comment]
I confirm that I have seen the drive appearance, but only these contents are displayed in the terminal environment. I cannot enter the development environment starting with ">>>"

**Comment by dingramax** [comment]
Try connecting with putty. On the board I'm using currently the Saola M1 all i have to do is put in the com port I don't need to put in the baud rate or anything the board figures it out ymmv

**Comment by 60999** [comment]
The same problem occurs with another piece of nodemocu-32-s2.

**Comment by dhalbert** [comment]
@60999 Please try to connect with another terminal program, such as putty or Tera Term, as suggested by @dingramax.

I am confused about which board firmware you're using: you say you're using `muselab_nanoesp32_s2`, but your board is "nodemocu-32-s2", so they don't match. Is it "mocu" or "mcu"? Could you post a pointer to that board? It's possible the pin connections are different.

**Comment by 60999** [comment]
> Try connecting with putty. On the board I'm using currently the Saola M1 all i have to do is put in the com port I don't need to put in the baud rate or anything the board figures it out ymmv

I used putty to get the same results.
Is the firmware incompatible? It's also an esp32-s2 chip.

**Comment by 60999** [comment]
> @60999 Please try to connect with another terminal program, such as putty or Tera Term, as suggested by @dingramax.
> 
> I am confused about which board firmware you're using: you say you're using `muselab_nanoesp32_s2`, but your board is "nodemocu-32-s2", so they don't match. Is it "mocu" or "mcu"? Could you post a pointer to that board? It's possible the pin connections are different.

I use esp32 S2 chip esp-12k development board: nodemocu-32-s2, burning Firmware of 
 muselab_ nanoesp32_ S2 development board.

**Comment by 60999** [comment]
When I use esp32 S2 chip nanoESP32-S2 development board, burning Firmware of
nanoESP32-S2 development board.

`ESP-ROM:esp32s2-rc4-20191025
Build:Oct 25 2019
rst:0x1 (POWERON),boot:0x8 (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:2
load:0x3ffe6100,len:0x8
load:0x3ffe6108,len:0x18a0
load:0x4004c000,len:0x930
load:0x40050000,len:0x2cc8
entry 0x4004c1b4
`
That's the same display.

**Comment by 60999** [comment]
Sorry ,my mistake. It must use another usb port.Thanks for help.
