### ISSUE TITLE
Add access to backup RAM to save state during deep sleep

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#3789]
Most chips with deep sleep capability provide backup RAM that remains energized during deep sleep. Allow access to this RAM, say via a `microcontroller.nvm`-style mechanism. This will allow a deep-sleeping program to remember state without using flash.

**Comment by tannewt** [comment]
Note that there are also retained registers usually too. The S2 has 8 32 bit retained registers in the RTC. We'll either want multiple memory segments or one oddly sized memory where you fill it from the beginning and the retention adapts accordingly. This adaptation can also match RAMs that can have varied retention sizes.

**Comment by dhalbert** [comment]
Done as part of sleep implementation.
