### ISSUE TITLE
Change "MagTag" to "Adafruit MagTag" in the support matrix

### ISSUE THREAD

**Issue by d-c-d** [adafruit/circuitpython#3831]
see https://circuitpython.readthedocs.io/en/6.0.x/shared-bindings/support_matrix.html

One would expect that the MagTag would in this list, but it is not present today

**Comment by dhalbert** [comment]
6.0.x does not support the MagTag: you have to use 6.1.x. The [circuitpython.org downloads page](https://circuitpython.org/board/adafruit_magtag_2.9_grayscale/) for MagTag does not list 6.0.x.

You can find the MagTag listed here: https://circuitpython.readthedocs.io/en/latest/shared-bindings/support_matrix.html.

However, there is a bug that it's listed just as "MagTag", and not as "Adafruit MagTag". We need to fix that.

**Comment by d-c-d** [comment]
Thanks - 
   **is there a link to the latest docs anywhere**?
     (e.g.   https://circuitpython.readthedocs.io/en/latest/shared-bindings/support_matrix.html )
   When I started at https://circuitpython.readthedocs.io/ I only got to the 6.0.x docs, 
Note that the link from https://learn.adafruit.com/adafruit-magtag?view=all goes to 
   https://circuitpython.readthedocs.io/
   which is loading the 6.0.x docs, not the 'latest'
   
   ( I guess the view all as one page end up bringing in the generic 
      https://learn.adafruit.com/adafruit-magtag/welcome-to-the-community
       link, so that probably explains why ReadTheDocs under magtag still goes to 6.0.x )

**Comment by tannewt** [comment]
On Read the Docs you can click the bottom left box to switch versions. It has latest and all of the previous major versions.
