### ISSUE TITLE
Auto-reload not working during simulated deep sleep?

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#3844]
From a feedback comment on the new Deep Sleep Guide:

>One thing I've noticed about using deep sleep that was very confusing at first (as well as regular sleep for long periods) is that code no longer auto-reloads when I save in Mu. It seems like the Magtag is hanging. You need to mouse into the REPL and type CTRL-C.

**Comment by ladyada** [comment]
yes, this bug report is reproducable - i have to manually restart after updating code

**Comment by tannewt** [comment]
This might be fixed in my PinAlarm PR. It tweaks how we notify the CP task from other tasks.

**Comment by dhalbert** [comment]
I retested this with a simple program on the MagTag, and I don't see this problem now.
```py
import alarm
import time

print("HelloWorld!")   # I edited this during simulated deep sleep.

a = alarm.time.TimeAlarm(monotonic_time=time.monotonic() + 10)
alarm.exit_and_deep_sleep_until_alarms(a)
```
