### ISSUE TITLE
Move actions in test ci task that are more likely to fail to be earlier

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#3877]
The most likely reasons for the `test` CI job to fail are translation check failures and documentation build failures. Let's move those earlier so that the job will fail more quickly. The translation check can come first.

**Comment by microDev1** [comment]
I had this thought earlier... CI tests can be moved on the basis of :-
- Speed of completion.
- Frequency of occurrence.

On this basis we can have `translation`, `usb vid/pid` tests earlier and tests like `docs build` can be moved further ahead... unless the CircuitPython CI uses parameters generated from previous checks which I don't think it does.

**Comment by dhalbert** [comment]
Fixed by #3881.
