### ISSUE TITLE
SAMD51 - busio.UART will not initialize if receiver_buffer_size is not a multiple of 4

### ISSUE THREAD

**Issue by AdamCummick** [adafruit/circuitpython#3901]
On a SAMD51 CircuitPython build 6.0.0-278-g66fb09506

busio.UART will not initialize if receiver_buffer_size is not a multiple of 4. This is probably a hardware limitation, but I did not find it referenced in the documentation.

```py
import board
import busio

buffer_len = 3 # will fail unless this is a multiple of 4
port1 = busio.UART(board.TX1, board.RX1, baudrate=115200, receiver_buffer_size=buffer_len)

```

**Comment by dhalbert** [comment]
Fixed by #5026.
