### ISSUE TITLE
Valid values for timeout of BLERadio.start_scan() seem to be ignored

### ISSUE THREAD

**Issue by catequalsgood** [adafruit/circuitpython#3942]
Issue #3826 was fixed in 6.0.1 but the fix seems to have introduced a new bug. Any timeout value >= 0.1 seems to be ignored now (no timeout). I had the code below running for 14 min and it did not precede past "Scanning for an Adafruit Server advertisement...". I checked 6.0.0 again and the behaviour there is as expected. 
I tested this on a Feather Sense using 6.1.0 RC as well as 6.0.1.

```
import time

import adafruit_ble
from adafruit_ble_adafruit.adafruit_service import AdafruitServerAdvertisement
import supervisor

ble = adafruit_ble.BLERadio()

connection = None

print("Scanning for an Adafruit Server advertisement...")
for adv in ble.start_scan(AdafruitServerAdvertisement, timeout=1.0):
    print("about to connect")
    connection = ble.connect(adv)
    print("connected")
    break

ble.stop_scan()

supervisor.reload()
```

**Comment by dhalbert** [comment]
Also reported by @dglaude in  #3963.
