### ISSUE TITLE
Is there a plan to support esp32-s3?

### ISSUE THREAD

**Issue by kingsjl** [adafruit/circuitpython#3948]
Is there a plan to support esp32-s3?

**Comment by ladyada** [comment]
yes, once we get chips we can investigate adding support. there's no eta and we don't even have samples yet :)

**Comment by street-grease-coder** [comment]
@ladyada they shipped out samples to some makers on youtube, ahead of world wide release time

**Comment by ladyada** [comment]
@street-grease-coder hi what are the specific links for folks who have em?

**Comment by street-grease-coder** [comment]
@ladyada  can I pm you somehow?

**Comment by ladyada** [comment]
nope

**Comment by street-grease-coder** [comment]
https://www.youtube.com/watch?v=tcrFiZuUi18
https://www.youtube.com/channel/UCu7_D0o48KbfhpEohoP7YSQ
I would include more details, but not here, hope that's useful to you anyways..

**Comment by ladyada** [comment]
hi - that video is esp32-c3 not s3?

**Comment by StuartIanNaylor** [comment]
The esp32-s3 (S3) could be amazingly useful from KWS to image recognition but if Espressif try to shoehorn into Espressif only solutions of esp32-who & esp32-skainet its likely going to be a flop.
If we get anywhere near a complete port of tensorflow-lite then wow its got big potential.

**Comment by ladyada** [comment]
hi, sub to https://github.com/adafruit/circuitpython/issues/4363 for status updates
