### ISSUE TITLE
sys.platform not present for ESP32-S2 boards like FeatherS2

### ISSUE THREAD

**Issue by kevinjwalters** [adafruit/circuitpython#3951]
A new FeatherS2 (from @unexpectedmaker) which comes with `6.0.0` does not have `sys.platform`:

```
Adafruit CircuitPython 6.0.0 on 2020-11-16; FeatherS2 with ESP32S2
>>> import sys
>>> dir(sys)
['__class__', '__name__', 'argv', 'byteorder', 'exit', 'implementation', 'maxsize', 'modules', 'path', 'print_exception', 'stderr', 'stdin', 'stdout', 'version', 'version_info']
>>> sys.version
'3.4.0'
>>> sys.platform
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'platform'
```

@jepler mentions in land of Discord

> it looks like this is missing because the port doesn't define a macro.  It would need to be similar to nrf: ports/nrf/mpconfigport.h:#define MICROPY_PY_SYS_PLATFORM "nRF52840".

referring to https://github.com/adafruit/circuitpython/blob/main/ports/esp32s2/mpconfigport.h which seems a lot small than the `nrf` and `atmel-samd` ones.

**Comment by anecdata** [comment]
Added in [https://github.com/adafruit/circuitpython/pull/3954](https://github.com/adafruit/circuitpython/pull/3954). Closing.
