### ISSUE TITLE
Copyright notice on ReadTheDocs still shows 2014-2020

### ISSUE THREAD

**Issue by hugodahl** [adafruit/circuitpython#4000]
I noticed that the copyright date on the [CircuitPython ReadTheDocs site](https://circuitpython.readthedocs.io/) is still displaying 2020. I realize that it doesn't (yet) show 2021 since there haven't been any updates for the site in 2021 yet, however, when the site is updated to support the next release of CP, it should display 2021.

Looking over the docs section of the code, and this history of the configuration line ([`/conf.py`](https://github.com/adafruit/circuitpython/blob/47015d778944d8f30d45c76446d4a1dc4ad66a45/conf.py#L106)), this appears to be something that is manually updated when noticed or opportune. It may be worthwhile having the "to" year of the copyright statement be determined programmatically when the docs are generated so that the statement reflects the correct time period.

**Comment by tannewt** [comment]
@hugodahl Want to make a PR to update it?

**Comment by hugodahl** [comment]
Can do!
