### ISSUE TITLE
VS Code MagTag - ModuleNotFoundError

### ISSUE THREAD

**Issue by eukrit** [adafruit/circuitpython#4015]
Hi AdaFruit/CircuitPython,

I'm new and I was trying to follow this instruction: 
https://learn.adafruit.com/magtag-covid-tracking-project-iot-display/circuitpython-internet-test

I've got a silly obstacle on VS Code related to the module not found as per the attached screenshot.
I think I've got all the files right as per the attached images.

Would you please help?

![2021-01-17_23-26-26](https://user-images.githubusercontent.com/36352296/104849315-8f69d980-591b-11eb-9a19-6cdd0a98ec4d.jpg)
![2021-01-17_23-26-31](https://user-images.githubusercontent.com/36352296/104849317-91339d00-591b-11eb-8536-bf705c1097d4.jpg)
![2021-01-17_23-28-13](https://user-images.githubusercontent.com/36352296/104849332-af010200-591b-11eb-8616-74f2e1c9adc2.jpg)
![2021-01-17_23-28-40](https://user-images.githubusercontent.com/36352296/104849344-bf18e180-591b-11eb-838d-32d7fb994054.jpg)

Extensions Installed: Arduino, CircuitPython, Python, Pylance
Latest Library: adafruit-circuitpython-bundle-6.x-mpy-20210117
Latest MagTag UF2: adafruit-circuitpython-adafruit_magtag_2.9_grayscale-en_US-6.1.0-rc.1

**Comment by dhalbert** [comment]
That is VSCode not finding the module, but it doesn't mean it's not working on the board. Did you `pip3 install adafruit-circuitpython-requests` in Windows?

This kind of support issue is better handled in https://adafru.it/discord or https://forums.adafruit.com. Thanks.

**Comment by eukrit** [comment]
Thank you dhalbert.
