### ISSUE TITLE
Comment Fix - QSPI SCK and CS Reversed

### ISSUE THREAD

**Issue by mrangen** [adafruit/circuitpython#4016]
I just noticed a comment that could be improved for clarity, as I referenced it and it led me to think I had my QSPI SCK and CS pins reversed.

circuitpython/ports/atmel-samd/boards/itsybitsy_m4_express/mpconfigboard.h

15    // DotStar pins, QSPI CS, and QSPI SCK
16    #define MICROPY_PORT_B (PORT_PB02 | PORT_PB03 | PORT_PB10 | PORT_PB11)

As it stands, PORT_PB02 and PORT_PB03 are understood to be the DotStar Pins, PORT_PB10 the QSPI CS, and PORT_PB11 the QSPI SCK. While it is correct about the DotStar pins, the QSPI CS and QSPI SCK are reversed.

I recommend replacing the comment on Line 15 with:

// DotStar SCK, DotStar MOSI, QSPI SCK, and QSPI CS

**Comment by ladyada** [comment]
good eyes! could you submit a PR with the fix? :)

**Comment by mrangen** [comment]
Sure thing! It'll be my first!

**Comment by ladyada** [comment]
awwwseome!
here's a guide that may help
https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github

**Comment by mrangen** [comment]
Thanks!

**Comment by tannewt** [comment]
Thank you!
