### ISSUE TITLE
VID/PID Request for new board design

### ISSUE THREAD

**Issue by GMDII** [adafruit/circuitpython#4026]
Hello. 
I am creating a derivative of the Grand Central M4. I will be using the ATSAMD51P20A

Requesting a VID/PID for the new board. 

Thanks so much.

**Comment by skerr92** [comment]
Hey there! If you’re needing a VID/PID checkout pidcodes. I believe @tannewt has been pushing this direction. He has access to the review process and can get it sorted there.

**Comment by rfefx** [comment]
So i am following this guide on adafruit. https://learn.adafruit.com/how-to-add-a-new-board-to-circuitpython/overview
which let me to this pull request. Pidcodes requires the open source software and hardware. I can't get my board added to circuitpython without the VID/PID so it's a catch 22.

**Comment by skerr92** [comment]
Submit your pull for pidcodes and let Scott know what you’re doing. As long as the PID is available, you should have no issues pushing to CP for a PR. (I’ve done this twice already)

I am happy to help if need be.

**Comment by tannewt** [comment]
> So i am following this guide on adafruit. https://learn.adafruit.com/how-to-add-a-new-board-to-circuitpython/overview
> which let me to this pull request. Pidcodes requires the open source software and hardware. I can't get my board added to circuitpython without the VID/PID so it's a catch 22.

You can open source the code in your own fork to satisfy the pid.codes requirement and then PR to CircuitPython after.

**Comment by dhalbert** [comment]
@tannewt described a path forward. Closing for now. Happy to help further if you are still stuck.
