### ISSUE TITLE
Get unique ID from flash

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#4039]
The RP2040 chip itself doesn't have a unique id so implement it by getting the flash chip's ID.

**Comment by dhalbert** [comment]
xref to https://github.com/raspberrypi/pico-sdk/pull/12

**Comment by sgbaird** [comment]
xref: https://github.com/adafruit/circuitpython/pull/4141#issuecomment-1266237208 (how to get the unique ID in CircuitPython)

**Comment by dhalbert** [comment]
https://docs.circuitpython.org/en/latest/shared-bindings/microcontroller/index.html#microcontroller.Processor.uid will get you the UID
