### ISSUE TITLE
Better factor out flash config

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#4041]
Right now the flash size is hard coded and the init code is as well. The flash init code is 256 bytes of arm code loaded by the bootloader, checksummed and run. The build process is a bit tricky due to the checksum so it's hardcoded for now.

**Comment by dhalbert** [comment]
@tannewt do you want to do this by 6.2.0 final?

**Comment by tannewt** [comment]
It's ok with me if it misses 6.2.0 but I don't plan on switching to anything else until it's out for review. (So it'll be out for review if 6.2.0 is blocked on me working on other things.)
