### ISSUE TITLE
Re-adding core modules for boards that don't have them

### ISSUE THREAD

**Issue by Yobmod** [adafruit/circuitpython#4055]
Hi,
I'm working on a project that will have a circuitpython board communicating with a rpi/pc over serial, and I wanted to send the data as json. This works with my m4 express airlift board, which the json library built-in.

But I now want to miniturise my set up by using a QtPy, and the json lib isn't present. Is there a guide to re-adding core modules?
I've compiled circuitpython with added modules before (e.g neopixel.mpy), but I can't find a json.mpy anywhere. 

Also, is there a list of which modules are included for each board? The U2F download page for M4 airlift doesn't say it comes with json (circuitpython 6.1.0). How can I see if a given board has a core lib built-in?

**Comment by jepler** [comment]
Hi and thanks for your question.

I filed a separate bug for the documentation issue.

It looks like there's not enough available program (flash) capacity on the unmodified QT Py to allow the addition of the json built in module.  I am not aware of a pure-python version (In CircuitPython, .mpy files are byte-compiled versions of .py files), though that doesn't mean one doesn't exist.

If you wanted to solder a flash chip on and transform your board into a QT Py Haxpress, it looks like it is possible to add json to the English-language build (but it doesn't fit e.g., in the German language build).  In the file **ports/atmel-samd/boards/qtpy_m0_haxpress/mpconfigboard.h** add the following lines at the very end:
```
#undef MICROPY_PY_IO
#define MICROPY_PY_IO                               (1)
#undef MICROPY_PY_UJSON
#define MICROPY_PY_UJSON                            (1)
```
and build CircuitPython.

Building CircuitPython: https://learn.adafruit.com/building-circuitpython/build-circuitpython
About adding a flash chip to QT Py: https://learn.adafruit.com/adafruit-qt-py/pinouts#reverse-side-spi-flash-3073285-10

Remember to back up your CIRCUITPY before flashing with the "haxpress" version, it will erase and format the flash chip the first time.
