### ISSUE TITLE
docs: support matrix: doesn't show certain modules, e.g., json

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#4056]
In #4055, @yobmod observed that the built in `json` module doesn't appear in the support matrix or on circuitpython.org's list of supported modules.

This is because it is enabled/disabled by `MICROPY_PY_UJSON` in a **.h** file, rather than by `CIRCUITPY_JSON` in a **.mk** file.

It would be nice if either this was converted to work in the usual way, or **docs/shared_bindings_matrix.py** could learn how to find these kinds of modules too.

I don't have a full list of modules that are affected by this, but looking at `help("modules")` on a full build like Metro M4 Express and comparing it to the support matrix should give a pretty good idea of which modules are affected.

**Comment by dhalbert** [comment]
Related: #1900 (move json to shared-bindings), #1901 (move re to shared-bindings), #1911 (fix docs)
