### ISSUE TITLE
Hook up RTC for sleeping and timekeeping

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#4067]

**Comment by tannewt** [comment]
https://github.com/adafruit/circuitpython/pull/4110 Allows us to set the RTC. For sleeping, we need to modify https://github.com/adafruit/circuitpython/blob/main/ports/raspberrypi/supervisor/port.c#L164-L187 for sleep support.

**Comment by xorbit** [comment]
I don't know enough to know if it's related to this issue, but where `time.time()` used to fail because no RTC was attached, it now seems to produce seemingly random numbers (but they're from a repeating set) on the RPi Pico.

**Comment by tannewt** [comment]
@microdev1 any idea if your RTC work should have fixed time.time?

**Comment by microDev1** [comment]
It seems like [`common_hal_rtc_init()`](https://github.com/adafruit/circuitpython/blob/08f30fedf5401dd6aa9bf318e4d1eda59ae5652f/ports/raspberrypi/common-hal/rtc/RTC.c#L33-L35) is not getting called which leads to generation of random numbers. 
I am not sure where to add a call for it, how do other ports handle RTC initialization?

**Comment by tannewt** [comment]
@microDev1 I suspect RTC init is done in `port_init` in `supervisor/port.c`.n

**Comment by microDev1** [comment]
`port_init` works... since this is a small change I might include it with my `UART` work or maybe you can fit it in somewhere. :)

**Comment by tannewt** [comment]
Fixed by #4816
