### ISSUE TITLE
Add shown_group property to DisplayIO.display

### ISSUE THREAD

**Issue by benetherington** [adafruit/circuitpython#4073]
Hey folks! This might be a heavy lifter, and I really wish I had enough C knowledge to even get started on a PR for this requested feature.

Currently, display.show() is the only available interaction with the group displayed on a DisplayIO device. If you want to interact with that group, you need to keep track of it somewhere. I'm working on a project that is split into multiple modules, and it's already messy enough to make sure all my code has access to the display object. It would be nice for parts of my code to modify, store, or inspect the displayed group.

I'd like to be able to do something like the following:

code.py
```python
display = adafruit_displayio_ssd1306.SSD1603(bus, width, height)
main_menu_group = Group()
display.show(main_menu_group)

clock = Clock(display)
clock.iterate()
```

clock.py
```python
class Clock():
  def __init__(self, display):
    self.display = display
    self.clock_group = None
    self.interrupted_group = None

  def grab_display(self):
    self.interrupted_group = self.display.shown_group()
    self.display.show(self.clock_group)

  def release_display(self):
    self.display.show(self.interrupted_group)

  def iterate(self):
    if self.clock_group is None:
        self.set_up_display()
    self.grab_display()
    t = time.localtime()
    if t.tm_hr < 17: 
      self.time_label.text = time.time()
    else:
      self.release_display()
```

Thank you to all the CircuitPython contributors for their hard work! This is such an amazing community.

**Comment by tannewt** [comment]
I don't think we need to change CircuitPython for this. Instead, I'd recommend wrapping the display object in another class that does the grab and release tracking for you. That way the clock class can focus on rendering itself.
