### ISSUE TITLE
Add optional pin pull.UP/DOWN to countio.Counter for open-collector sensors

### ISSUE THREAD

**Issue by CedarGroveStudios** [adafruit/circuitpython#4094]
Would it be possible to add an optional pin _pull.UP_ attribute to _countio.Counter_? The capability would accommodate a variety of digital sensors with open-collector outputs, eliminating the need for an added pull-up resistor.

**Comment by tannewt** [comment]
What are some example sensors? How much does the resistor value matter? It's usually better to be explicit with an external value.

**Comment by CedarGroveStudios** [comment]
Before trying _countio_, an internal pull-up was sufficient to work with both optical and hall-effect interrupter sensors. The pull-up value is not critical for most low to medium-speed applications like motor RPM. Don't know if the internal pull-up value provides enough current for the speed of a remote control IR sensor.

Sensors tested:
Hall-Effect:  [https://www.adafruit.com/product/158](url)
IR Reflective: [https://www.adafruit.com/product/3930](url)
T-Slot Interrupter: [https://www.adafruit.com/product/3986](url)

Does _rotaryio_ provide pull-ups for encoder pins? I've been able to read encoders without pull-up resistors. Hmmm.

**Comment by tannewt** [comment]
> Does _rotaryio_ provide pull-ups for encoder pins? I've been able to read encoders without pull-up resistors. Hmmm.

I don't think so. I think our guide has you hook one up.

**Comment by tannewt** [comment]
> Before trying _countio_, an internal pull-up was sufficient to work with both optical and hall-effect interrupter sensors. The pull-up value is not critical for most low to medium-speed applications like motor RPM. Don't know if the internal pull-up value provides enough current for the speed of a remote control IR sensor.

I'm ok if you want to add a kwarg for this.

**Comment by CedarGroveStudios** [comment]
I'm completely unsure about where to start when it comes to modifying one of the core elements. Time to look at how that's done. Thanks.

**Comment by ladyada** [comment]
@CedarGroveStudios you can do it! we can help support ya, try making a draft PR when you're ready for some eyes :)

**Comment by CedarGroveStudios** [comment]
Thanks! Another fun trip outside my comfort zone!

@tannewt:  Interestingly, the _rotaryio_ guides I've looked through that involve CircuitPython have no pull-up resistors for the two quadrature encoder pins.  [https://learn.adafruit.com/rotary-encoder/overview](url)

**Comment by tannewt** [comment]
Yup, I'm wrong. IncrementalEncoder on the SAMD turns them on automatically: https://github.com/adafruit/circuitpython/blob/main/ports/atmel-samd/common-hal/rotaryio/IncrementalEncoder.c#L59-L63

**Comment by CedarGroveStudios** [comment]
According to the information in read the docs, pull up/down and None appear to be included now. I’ll test and confirm that it works with the listed sensors.

**Comment by dhalbert** [comment]
Fixed by #5803.
