### ISSUE TITLE
Teensy 4.1: "True==False" crashes CircuitPython

### ISSUE THREAD

**Issue by RyannDaGreat** [adafruit/circuitpython#4097]
So does 1==True, True==1 etc. There's no stack trace; it simply reboots.
I'm using adafruit-circuitpython-teensy41-en_US-6.0.0-rc.2.hex

**Comment by dhalbert** [comment]
I loaded 6.00-rc.2, 6.1.0, and 6.2.0-beta.1 on a Teensy 4.1, using the [Teensy Loader GUI app](https://www.pjrc.com/teensy/loader_linux.html) on Ubuntu 20.04. These simple tests work for me:
```
Adafruit CircuitPython 6.1.0 on 2021-01-21; Teensy 4.1 with IMXRT1062DVJ6A
>>> True==False
False
>>> 
```
Please try one of the latest .hex's.,
How are you loading the .hex? I'm thinking you are getting an incomplete load or something like that.

**Comment by RyannDaGreat** [comment]
Thank you - I tried reflashing CircuitPython and now it works for some reason lol. I guess it got corrupted somehow
