### ISSUE TITLE
ESP32-S2: Configurable resources based on board RAM

### ISSUE THREAD

**Issue by anecdata** [adafruit/circuitpython#4103]
Is it possible to have multiple configs for RAM, like we do for flash `circuitpython/ports/esp32s2/esp-idf-config/` so that boards with more RAM could be allocated more resources, like more sockets, more pystack, etc.?

**Comment by dhalbert** [comment]
The nRF ports do RAM allocation to set aside RAM for use by the nRF SoftDevice and to allocate RAM for a SPIM3 buffer (a hardware bug workaround):
https://github.com/adafruit/circuitpython/blob/70a5f464df709737fb90a9ab69baf08671c8f383/ports/nrf/boards/common.template.ld#L21-L31.

**Comment by anecdata** [comment]
We have `CONFIG_SPIRAM_SIZE`  in board-by-board `sdkconfig`, but it seems if other resource parameters are board-by-board, capabilities may fragment and be harder to troubleshoot when issues arise.

**Comment by tannewt** [comment]
Note that right now we don't use external ram for sockets or pystack. We simply use all external RAM for the CP heap. To allow for more sockets, we'd need to change how RAM is shared between CP and the IDF. Basically now we don't tell the IDF about it. In the future we could tell the IDF and then allocate the heap through the IDF.

One wrinkle is that then the IDF memory may not be DMA-able so for any IDF buffers we'll have to be careful.

**Comment by hierophect** [comment]
This recently came up in #4061, since TLS sockets take up 2 sockets apiece now, so you can only have 2 of them total. @anecdata noted that might be a bit restrictive.

**Comment by anecdata** [comment]
Looks like `PYSTACK` is set to 1536 globally in `py/circuitpy_mpconfig.h`, but could be easily overridden at the port level (no existing overrides I could find) or board level (I think only TG-Watch does this).

In cases where there is sufficient external RAM for heap, what's the downside to using more internal RAM for IDF/sockets and pystack?

**Comment by tannewt** [comment]
I think you'll find that the tradeoff is between IDF/sockets (which gets the remainder) and pystack.

**Comment by anecdata** [comment]
More up-to-date detail, with references to PRs addressing some of the use cases, in #5915.

Closing this old issue.
