### ISSUE TITLE
USB PID request: Winterbloom Binary Star

### ISSUE THREAD

**Issue by theacodes** [adafruit/circuitpython#4104]
Hi friends. I'll be sending a PR here and over at uf2-samdx1 to add Binary Star's configuration. Could I have a set of PIDs please? 😺 

![please](https://user-images.githubusercontent.com/250995/106370166-730b6b00-6325-11eb-9a3b-f3fcc6805339.gif)

**Comment by dhalbert** [comment]
Winterbloom Binary Star,bootloader,0x239A,0x00F5
Winterbloom Binary Star,arduino,0x239A,0x80F5
Winterbloom Binary Star,circuitpython,0x239A,0x80F6

**Comment by theacodes** [comment]
Many thanks!
