### ISSUE TITLE
APDS9960 Driver

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#411]
Driver for the gesture sensor.

https://www.adafruit.com/product/3595

**Comment by dglaude** [comment]
Some work in progress from @mrmcwethy here: https://github.com/mrmcwethy/Adafruit_CircuitPython_APDS9960

**Comment by tannewt** [comment]
This is done here: https://github.com/adafruit/Adafruit_CircuitPython_APDS9960
