### ISSUE TITLE
Socketpool `socket.sendto()` cannot send UDP data to ports above 255

### ISSUE THREAD

**Issue by StarWitch** [adafruit/circuitpython#4127]
# Setup

* Microcontroller: UnexpectedMaker FeatherS2 (ESP32-S2) (fw: 0.2.1)
* CircuitPython: 6.1.0 & custom build from `main`
* Host computer: macOS 11.2 
* Tools used: Wireshark

# Description

It seems that `port` for `socket.sendto()` is bound to the length of an `uint8_t`, capping it out at `255`, and then overflowing back to `0` when port numbers above that are specified.

I confirmed this by seeing seemingly random ports show up when I was trying to send data over port `9000`, only to have my host machine with Wireshark report that the FeatherS2 was trying to connect over port `70`.

# Reproduce

Here's a testing script that reproduces this behaviour:

```python
import wifi
import ipaddress
import time
import socketpool

try:
    from secrets import secrets
except ImportError:
    print("WiFi secrets are kept in secrets.py, please add them there!")
    raise

print("Connecting to WiFi")
wifi.radio.connect(secrets["ssid"], secrets["password"])
print("Connected to WiFi: {0} - IP: {1}".format(secrets["ssid"], wifi.radio.ipv4_address))

socketpool = socketpool.SocketPool(wifi.radio)

HOST_IP = "0.0.0.0" # change this to your host machine's private local IP (i.e: wherever you're running Wireshark)

while True:
    with socketpool.socket(socketpool.AF_INET, socketpool.SOCK_DGRAM) as sock:
        sock.settimeout(0)
        sock.sendto("0xff", (HOST_IP, 254)) # will appear as a request to port 254 (correct)

    with socketpool.socket(socketpool.AF_INET, socketpool.SOCK_DGRAM) as sock:
        sock.settimeout(0)
        sock.sendto("0xff", (HOST_IP, 257)) # will appear as a request to port 1 (incorrect)

    with socketpool.socket(socketpool.AF_INET, socketpool.SOCK_DGRAM) as sock:
        sock.settimeout(0)
        sock.sendto("0xff", (HOST_IP, 259)) # will appear as a request to port 3 (incorrect)

    time.sleep(1)
```

Set up Wireshark on the host/server machine and observe what ports the MCU tries to connect to (filter by the IP of the MCU).

<img width="272" alt="image" src="https://user-images.githubusercontent.com/34408664/106937461-c5fd6d80-66eb-11eb-9156-9f5ae29824c7.png">

# Fix

Changing the function `common_hal_socketpool_socket_sendto()` to accept `mp_int_t port` instead of `uint8_t port` fixes this error for me, in both `shared-bindings` and in the `ports/esp32s2` directories. This brings it in line with the TCP-based functions for `SOCK_STREAM`, etc. I reflashed my FeatherS2 with my newly-built version of CircuitPython, you can see here that I can send data on port `9000` now:

<img width="282" alt="image" src="https://user-images.githubusercontent.com/34408664/106942301-05c75380-66f2-11eb-855d-7dc4b1e7a7a3.png">

However, there are other functions such as `common_hal_socketpool_socket_bind()` which also take `uint8_t port` that may be affected as well. I'm unsure as to what impact that might have downstream as this is my first time modifying CircuitPython. I'm also unsure if this affects more than just my FeatherS2, but it seems likely given that the default `shared-bindings` C library also has `uint8_t`.

TCP connections with `socket.connect(...)` followed by `socket.send(...)` are unaffected, as far as I can tell. It seems to be limited exclusively to UDP connections, due to TCP already taking `mp_int_t port`.

**Comment by hierophect** [comment]
Thanks for noticing this, definitely an oversight! Might have been an unintended carryover from another API.
