### ISSUE TITLE
When will UART be implemented for RP2040?

### ISSUE THREAD

**Issue by hriday111** [adafruit/circuitpython#4144]
I've been wanting to do a project and as UART is not implemeted yet:
NotImplementedError: UART not yet supported

I cannot do he project, the project uses a circuit python library, hence I cannot use micropython.

UART works well on MICROPYTHON, why not CIRCUITPYTHON?

I've been desperately waiting for this implementation, I even flash the latest uf2 from the s3 server.

**Comment by dhalbert** [comment]
You can watch issue #4036. Implementing UART is on our very short list. Right now we are working on audio I/O. We don't publish schedules for when something will be done, but rest assured we want to do it as soon as possible.
