### ISSUE TITLE
RP2040 PIO Instruction Limit

### ISSUE THREAD

**Issue by LuminousOwl** [adafruit/circuitpython#4145]
The PIO StateMachine is limiting the number of PIO instructions to 16, but it should be 32. It is a simple comparison error limiting it to 32 bytes instead of 64 bytes needed for 32 16-bit instructions.  I have fixed it and can do a pull request.

**Comment by tannewt** [comment]
@LuminousOwl A PR would be awesome! Thank you so much for fixing my bugs. :-)

**Comment by LuminousOwl** [comment]
You're welcome. The Adafruit tutorial on building CircuitPython is great. I was surprised how easy it was to do a build for testing.
