### ISSUE TITLE
Raspberry Pi-Pico UART not Supported

### ISSUE THREAD

**Issue by zack-cpp** [adafruit/circuitpython#4180]
Trying to use UART on pi pico board. I started by finding pin names from _[board](https://circuitpython.readthedocs.io/en/latest/shared-bindings/board/index.html)_ modules.
![dir board](https://user-images.githubusercontent.com/56311615/107663364-e023e680-6cbd-11eb-91fe-3584018bc161.PNG)

Based on the _[example](https://learn.adafruit.com/circuitpython-essentials/circuitpython-uart-serial)_ from adafruit, i adjust the TX and RX to GP8 and GP5.

**_`uart = busio.UART(board.GP4, board.GP5, baudrate=9600)`_**

when i run the code, i got this error message:
![error](https://user-images.githubusercontent.com/56311615/107664715-4bba8380-6cbf-11eb-9845-3402f589fe50.PNG)

I change to the default TX and RX Pi-Pico's pin, referenced to [this closed issue](https://github.com/adafruit/circuitpython/issues/4121#issue-800418879), and still got same error.

is UART for Pi-Pico circuitpython not supported yet?

**Comment by ladyada** [comment]
correct, dupklicate of
https://github.com/adafruit/circuitpython/issues/4036
you can sub to that issue to be notified when resolved

**Comment by panchalnikunj** [comment]
https://www.youtube.com/channel/UCA4j-J-TFW_9Dt4iTwIjtYQ

Once visit this channel for Raspberry Pi Pico Projects

**Comment by dhalbert** [comment]
@panchalnikunj It is inappropriate to spam our repos with pointers to your YouTube channel, even if it is relevant material. I am deleting your comments. Please do no do this again.
