### ISSUE TITLE
neopixel: calling show() after deinit() doesn't raise an exception

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#4218]
I was surprised at this:
```python
>>> n = neopixel.NeoPixel(board.GP0, 1, auto_write=False)
>>> n.deinit()
>>> n.show()
>>> 
```

Expected behavior: `n.show()` raises an exception since the related object has been deinitialized
Actual behavior: `n.show()` does not raise an exception

I only tested on Pico, so this may be a port-specific problem.  However, I didn't label it as such initially.

**Comment by Beau28713** [comment]
```python
>>> import board
>>> import neopixel
>>> pixel = neopixel.NeoPixel(board.NEOPIXEL, 10, auto_write=False)
>>> pixel.deinit()
>>> pixel.show()
>>> 
```

Running the above example on circuit playground express crashed the core code and rebooted the hardware into safe mode. 

![CP_Cplay](https://user-images.githubusercontent.com/65408911/133064393-44091639-5d09-4498-a387-ef09c72980f2.PNG)

**Comment by tannewt** [comment]
I think the fix is to check if the digitalio is deinited here: https://github.com/adafruit/circuitpython/blob/main/shared-bindings/neopixel_write/__init__.c#L63

**Comment by Beau28713** [comment]
I'll take a look at it. Thanks
