### ISSUE TITLE
2017-11-08 3.0beta build - no REPL or mass storage mount

### ISSUE THREAD

**Issue by hukuzatuna** [adafruit/circuitpython#422]
I rebuilt the firmware tonight and flashed my Metro M4 Express. Now I cannot get Putty to open a serial connection to the COM port (I get an "Unable to open connection to COM50 Cannot open serial port" error). Also, CIRCUITPY does not appear when the M4 is connected. This behavior is the same regardless of which USB port I use or whether I connect to a USB hub. Rebooting the laptop doesn't change the behavior (this is Windows 10, by the way). No pattern of resetting the M4 or dropping into the bootloader changes the behavior.

**Comment by dhalbert** [comment]
I also see this problem on Windows 10, and a similar problem on Windows 7.
Some testing data with a Metro M4 on various commits. Note that I have a slow Windows 10 box running Windows Insider build 17025. I had to press F5 in the Explorer window to get Windows to update the list of disk drives promptly.

* 1893669: just before Python-generated USB descriptors.
CIRCUITPY drive D:, REPL OK.
* 4aeef10: introduction of generated descriptors.
Windows shows CIRCUITPY D: and "Removable disk E:. Clicking on E: gives a dialog "Please insert a disk into Removable Disk (E:).". Connecting to COM port: typing does not bring up REPL (no REPL on Linux either).
* 123c226: _Usb write protection + fixes._
D: and E:  visible. E: is now called "USB Drive". No REPL on Windows or Linux.
* 3b17980: _Enable LONGINT on M4 + usb fix._
D: and E: visible. REPL now works.
* e267b2c: _Update deps: ASF, micropython and usb_descriptor._
same as above
* 5ff6417: _atmel-samd: Stop double CSW after MSC reads_
same as above
* 048f0f0: includes 182a946: _Tweak mass storage code to finish read sooner._
Causes Windows Explorer to show a very slow progress bar when trying to open CIRCUITPY D:

If I checkout the tip of master and revert 182a946, things are OK again. I'll file a PR for that.

I wonder if this may also have something to do with @kattni's issueson Mac reported last night.
