### ISSUE TITLE
`make html`: Sees unintended files from submodules

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#4220]
Can we change the setup of sphinx so that it doesn't see "problems" like these when building in a clone which has been used to build an esp32s2 FW:
```
/home/jepler/src/circuitpython/ports/esp32s2/.idf_tools/tools/cmake/3.16.4/share/cmake-3.16/Help/command/file.rst:159: WARNING: Could not lex literal_block as "cmake". Highlighting skipped.
```
(and many others)

Possibly we could do this by having a whitelist of locations to use, instead of looking everywhere.

**Comment by tannewt** [comment]
The exclude list is here: https://github.com/adafruit/circuitpython/blob/main/conf.py#L177
