### ISSUE TITLE
ESP32-S2 2nd USB-CDC background to TX/RX pins

### ISSUE THREAD

**Issue by emard** [adafruit/circuitpython#4227]
HI

I see 2nd serial is added and thanx to this.

Let's say I want just talk to connected TTL serial
hardware and I need a simple command to cut
me off current REPL and to 8-bit transparently conect to
TX/RX pins, but in background, to keep current
application running.

for example if I have modem on pins 10 and 11
I just need something like this

```
>>> connect(tx=10,rx=11,baud=115200)
ATD1234
OK
```
no more REPL until reboot and that's all I need.

**Comment by dhalbert** [comment]
For that you just use `busio.UART` ([docs](https://circuitpython.readthedocs.io/en/latest/shared-bindings/busio/index.html#busio.UART)). It's not yet implemented on the RPi Pico, but will be fairly soon. It's on all other boards.
