### ISSUE TITLE
Add en-uk translation option to weblate

### ISSUE THREAD

**Issue by garethhcoleman** [adafruit/circuitpython#4286]
Dear sir, madam and personages who prefer otherwise

I humbly request the opportunity to make a modest contribution to the magnificence that is circuit python.

As you can doubtless divine, I am fluent in British English and feel compelled, nay impelled, to forward my services.

If you would be so kind as to add the Queen's English to the list of possible languages, I can then begin the task of translation.

I remain, your most obedient servant

**Comment by jepler** [comment]
@garethhcoleman It should be possible to add to the en_GB translation weblate now!  We're slightly changing our strategy about when builds with particular translations are enabled, so @tannewt can work with you to define a milestone to reach before we turn that flag on.  Thank you for helping us improve CircuitPython, and don't hesitate to ask (especially in Discord) if you have questions about anything.
