### ISSUE TITLE
ESP32S2: hard crash with gamepad on soft reboot

### ISSUE THREAD

**Issue by Neradoc** [adafruit/circuitpython#4288]
The following codeon a UM Feather S2 causes a crash (loss of USB and reset) on soft reboot, like by saving a file, with latest (and drops into safe mode on 6.1.0, which is better in terms of recoverability).
```py
import board
import gamepad
from digitalio import DigitalInOut, Pull
button1 = DigitalInOut(board.IO7)
pad = gamepad.GamePad(
	button1,
)
```
Tested on a Lilygo TTGO too.
Seems similar to #4166, but different port, slightly different symptoms.

**Comment by deshipu** [comment]
Possibly related to #3693.
