### ISSUE TITLE
ItsyBitsy M0 Express no audiobusio library

### ISSUE THREAD

**Issue by Fennek94** [adafruit/circuitpython#4289]
Hello
I want to get the I2S bus working. I found an example [(https://learn.adafruit.com/adafruit-max98357-i2s-class-d-mono-amp/circuitpython-wiring-test)] were I try but there is an error: ImportError: no module named 'audiobusio'

How can I fix it? I used the CircuitPython version 6.0.1
Thanks for your help.

**Comment by dhalbert** [comment]
The M0 (SAMD21) builds don't have enough room for `audiobusio` and several other modules, sorry. The list of which modules are included with which boards is here: https://circuitpython.readthedocs.io/en/latest/shared-bindings/support_matrix.html
