### ISSUE TITLE
typo in busio.SPI doc

### ISSUE THREAD

**Issue by 2bndy5** [adafruit/circuitpython#4293]
https://github.com/adafruit/circuitpython/blob/538cd7eadad5a7364cd33650ecbdb735ca89d27d/shared-bindings/busio/SPI.c#L60

[renders improperly](https://circuitpython.readthedocs.io/en/latest/shared-bindings/busio/index.html#busio.SPI) because it's missing the required whitespace. Should be `.. note::`

**Comment by ladyada** [comment]
thanks!
