### ISSUE TITLE
[FeatureRequest] configparser to read ini files

### ISSUE THREAD

**Issue by bitboy85** [adafruit/circuitpython#4303]
As it is possible to use read/write from the internal storage i guess it would be useful to have a library that handles configuration files.

https://docs.python.org/3/library/configparser.html

**Comment by tannewt** [comment]
Moved to circuitpython for more visibility. Typically we use python files for config now because they can be imported.

**Comment by tekktrik** [comment]
I was actually thinking of doing this as a side project, is this something that there's still interest in adding to the main library (instead of the Community Bundle where I would have added it)?

**Comment by tannewt** [comment]
I think the community bundle is fine. It's got good visibility through `circup`.

**Comment by deshipu** [comment]
I don't think this is a good first issue, a whole library with proper api and tests seems like something an experienced programmer should make. Should we remove the label?

**Comment by dhalbert** [comment]
I think we are set with this with TOML libraries and the built-in `settings.toml` support.
