### ISSUE TITLE
merged conflict from WIP -< master branch?

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#432]
https://github.com/adafruit/circuitpython/blob/master/ports/atmel-samd/spi_flash.c#L31

im surprised it builds :D

**Comment by dhalbert** [comment]
That's from a couple of months ago! But we aren't building spi_flash.c yet on master, so no one ever tried to compile it!

**Comment by tannewt** [comment]
Yup, I realized I missed this but figured it'd get fixed when we start including it again in the build.

**Comment by stewmystre** [comment]
This issue is resolved as of pull request #465, it can be closed.

**Comment by dhalbert** [comment]
@stewmystre thanks for pointing this out!
