### ISSUE TITLE
NVM documentation has bad example usage

### ISSUE THREAD

**Issue by destinysagent** [adafruit/circuitpython#4336]
I'm trying the NVM example on: https://circuitpython.readthedocs.io/en/latest/shared-bindings/nvm/index.html?highlight=NVM

using the line: `microcontroller.nvm[0:3] = b\"\xcc\x10\x00\"` after importing microcontroller, both in REPL

This gives a syntax error Invalid Sybtax

![image](https://user-images.githubusercontent.com/58855944/110125097-da9c5680-7dba-11eb-8478-ea1866568cb3.png)

boot_out.txt is: Adafruit CircuitPython 6.2.0-beta.3-15-gc68073e12 on 2021-03-05; Raspberry Pi Pico with rp2040

**Comment by microDev1** [comment]
This is a docs issue... can you try with `microcontroller.nvm[0:3] = b"\xcc\x10\x00"`.

**Comment by destinysagent** [comment]
Yes, that appears to work fine - Many thanks microDev1

**Comment by dhalbert** [comment]
Documentation has a stray `\`.

**Comment by destinysagent** [comment]
Just for clarification, the document has two stray \ - b\"\xcc\x10\x00\" as opposed to the correct b"\xcc\x10\x00"
