### ISSUE TITLE
CTRL+D (\x04) doesn't work on usb_cdc.serials[1]

### ISSUE THREAD

**Issue by ismael-miguel** [adafruit/circuitpython#4343]
**Firmware**

```python
Adafruit CircuitPython 6.2.0-beta.3 on 2021-03-04; Raspberry Pi Pico with rp2040
```

**Behavior**

On `usb_cdc.serials[0]`, receiving a CTRL+D (\x04) control character causes the board to reset.
On `usb_cdc.serials[1]`, nothing happens.

**Additional Info**

Was just expecting the board to reset, as sending a CTRL+D (\x04) over `usb_cdc.serials[0]` has that behaviour.
Maybe nothing happens because the REPL doesn't read that channel, and the REPL is what controls the reset?

**Comment by FoamyGuy** [comment]
I think this is the intended behavior. The new CDC "channel" does not have any special use for ctrl+d and ctrl+c. That way if you application requires to use them it won't get interrupted by circuitpython things.
