### ISSUE TITLE
usb_cdc.serials[1].connected always return False for Raspberry Pi Pico

### ISSUE THREAD

**Issue by ismael-miguel** [adafruit/circuitpython#4345]
**Firmware**

```python
Adafruit CircuitPython 6.2.0-beta.3 on 2021-03-04; Raspberry Pi Pico with rp2040
```

**Code/REPL**

```python
import usb_cdc
usb_cdc.serials[1].connected
```

**Behavior**

Running the following code ALWAYS returns `False`, even when reading data to/from the Raspberry Pi Pico, on that USB CDC channel.

```python
>>> import usb_cdc
>>> usb_cdc.serials[1].connected
False
```

**Additional Info**

Despite returning `False`, the link is working properly.

I can send and receive data, without any issues.

<hr>

According to this: https://circuitpython.readthedocs.io/en/latest/shared-bindings/usb_cdc/index.html
> True if this Serial is connected to a host. (read-only)

Since it is connected to a host, should return `True`.

And no, the Raspberry Pi Pico is the only device connected to serial, and both ports belong to it:
![image](https://user-images.githubusercontent.com/10207857/110187767-70fb6700-7e11-11eb-9fc9-40dc30ca4bc2.png)

**Comment by dhalbert** [comment]
I do not see this problem with beta.3, either on Windows or Linux. I do have to be connected to `serials[1]` before it turns to `True`. In the screenshot below, I at first did not have a connection to COM18, but then when I did connect via TeraTerm, you can see it changed from `False` to `True'.

![image](https://user-images.githubusercontent.com/2847802/110210247-c0b44f80-7e5e-11eb-9534-36995b841868.png)

**Comment by ismael-miguel** [comment]
Interesting ...

When I use C# to connect to it, it returns `False`, but I can read and send data without issues:
![image](https://user-images.githubusercontent.com/10207857/110213788-70a6ae80-7e99-11eb-887a-a3cd338ee573.png)


But when I use PuTTY, it return `True`:
![image](https://user-images.githubusercontent.com/10207857/110213625-b4e57f00-7e98-11eb-844c-f339043ac57a.png)

**Comment by dhalbert** [comment]
I wonder if the C# code you are using is closing the connection after each write or something like that. If you do a read with a timeout in C# so it hangs while you check, does it show as connected during that time?

**Comment by ismael-miguel** [comment]
The C# code uses the SerialPort.DataReceived event, and waits for a text line.
(https://docs.microsoft.com/en-us/dotnet/api/system.io.ports.serialport.datareceived?view=netframework-4.7.2)

It opens the connection and waits.
There's nothing written to close the connection.

<hr>

I've tried to stop on the `serial.ReadLine();` method, in C#:
![image](https://user-images.githubusercontent.com/10207857/110217009-b53a4600-7ea9-11eb-92ba-aabece20063c.png)

But it still returns `False`:
![image](https://user-images.githubusercontent.com/10207857/110217099-34c81500-7eaa-11eb-80f4-d875255f0bac.png)

**Comment by hathach** [comment]
You need to set line state DTR to 1, it is used by tinyusb to detect terminal connection

**Comment by dhalbert** [comment]
Thanks @hathach. Some websearching shows this is a convention, and that terminal programs typically assert it when opening the conenction. So does `pyserial`, by default. This does not mean that DTR/DSR-style flow control is enabled. There is no other easy way to determine that something is connected on the host end. I can add more docmentation to `.connected` to make this clear.

Some more websearching shows that other people have had this problem with C#, which defaults to DTR not being set.

**Comment by ismael-miguel** [comment]
Thank you @hathach and @dhalbert.

I can confirm that setting `serial.DtrEnable = true;` in C# solved the issue:
![image](https://user-images.githubusercontent.com/10207857/110247672-33a7ee00-7f65-11eb-8dda-83fe7f095cb9.png)

Would be amazing if this was documented, to avoid possible duplicated issues.
