### ISSUE TITLE
Feather 52 2.0.1 bootload zip corrupted

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#436]
https://github.com/adafruit/circuitpython/blob/master/ports/nrf/boards/feather52/bootloader/feather52_bootloader_2.0.1_s132_single.zip

doesnt open?

**Comment by microbuilder** [comment]
I had issues with this as well, not sure what's up but I'll get a new one generated and uploaded.

**Comment by microbuilder** [comment]
Here's a file that you can replace with as a temp workaround.

[feather52_bootloader_2.0.1_s132_single.zip](https://github.com/adafruit/circuitpython/files/1465664/feather52_bootloader_2.0.1_s132_single.zip)

**Comment by tannewt** [comment]
This fixed?

**Comment by jerryneedell** [comment]
Yes
