### ISSUE TITLE
6.2.0 beta 4 release notes

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#4361]
This release, **6.2.0-beta.4**, is the fifth beta release of CircuitPython **6.2.0**. Notable changes since 6.2.0-beta.3 include new RP2040 fixes and features, enhancements to `bitmaptools`, and turning off `usb_cdc` by default. See **Port status** below for details on port stability for each port, and **Known issues** for known problems. If you find any issues with this release, please [file an issue](https://github.com/adafruit/circuitpython/issues/new/choose).

## Download from circuitpython.org
Firmware downloads are available from the  [downloads page](https://circuitpython.org/downloads)  on [circuitpython.org](https://circuitpython.org). The site makes it easy to select the correct file and language for your board.

## Installation
To install follow the instructions in our new [Welcome to CircuitPython!](https://learn.adafruit.com/welcome-to-circuitpython/installing-circuitpython) guide. To install the latest libraries, see [this page](https://learn.adafruit.com/welcome-to-circuitpython/circuitpython-libraries) in that guide.

Try [the latest version of the Mu editor](https://learn.adafruit.com/welcome-to-circuitpython/installing-mu-editor) for creating and editing your CircuitPython programs and for easy access to the CircuitPython serial connection (the REPL).

## Port status
CircuitPython has a number of "ports" that are the core implementation for a variety of microcontroller families. Stability varies on a per-port basis. As of this release, `atmel-samd`, `cxd56` (Spresense),  `nrf`, and `stm` for the F4 family are **stable**. `esp32s2`, `raspberrypi`, and `stm` for other STM chip families are being actively improved but may be missing functionality and have bugs. `litex` and `mimxrt10xx` are in an alpha state and *will* have bugs and missing functionality.

## Changes since 6.2.0-beta.3

Full commit log is [here](https://github.com/adafruit/circuitpython/compare/6.2.0-beta.3..6.2.0-beta.4).

### Fixes and enhancements
- Mark `bitmaptools.arrayblit()` destination as dirty. #4430. Thanks @jepler.
- Add `displayio.Palette.is_transparent(palette_index)`. #4426. Thanks @kmatch98.
- Add uniform `board.LED` pin names for several boards. More later. #4421. Thanks @kattni.
- Add `bitmaptools.readinto()` and `bitmaptools.arrayblit()`. #4403. Thanks @jepler.
- Disable `usb_cdc`, the second USB serial port, by default. it was on by default in 6.2.0-beta.3. It is still available to use in a custom build. #4384. Thanks @dhalbert.
- Save ~1500 bytes of firmware space via slight changes in vm execution with a minor speed penalty. #4344. Thanks @jepler.
- Refactor displayio set_pixel for use in bitmap_tools. #4357. Thanks @kmatch98.
- Update TinyUSB. #4327. Thanks @hathach.
- Fix regression of TinyUSB version. #4365. Thanks @tannewt.
- Fix incorrect 16-bit signedness in `displayio.TileGrid`. #4287. Thanks @deshipu.
- Fix `TileGrid.transpose_xy` crash. #4331. Thanks @dhalbert.
- Update `ulab` to fix matrix vetor multiplication issue. #4250. Thanks @jepler.
- Code and documentation cleanups. #4335. #4337, #4338, #4351, #4391. Thanks @tyomitch.

### Board- and port-specific changes
- **ESP32-S2**
  - Fix watchdog `deinit()`. #4325. Thanks @microDev1.
- **RP2040**
  - Add `displayio.ParallelBus`. #4130. Thanks @gamblor21.
  - Add `rotaryio`. #4329. Thanks @jepler.
  - Enable `audiomp3`; it works at low bit rates. #4380. Thanks @jepler.
  - Lower default flash speed. #4392, #4393. Thanks @tannewt.
  - Initalize `rtc` with a reasonable time. #4379. Thanks @jepler.
  - Add new features to `rp2pio.StateMachine`. #4329. Thanks @jepler.
  - Add double reset into UF2 bootloader. #4375. Thanks @hathach.
  - Fix use of `tud_disconnect()`. #4327. Thanks @hathach.
  - Fix clock stretch on `board.I2C()`. #4390. Thanks @dhalbert.
  - Allow more than one program per PIO. #4405. Thanks @DavePutz.
- **SAMD51**
  - Use `SDASETUP` to improve I2C rise times. #4370. Thanks @jposada and thanks @k3wals for the diagnosis.
- **Spresense**
  - Minor I2C, SPI, and UART fixes. #4386, #4412. Thanks @kamtom480.
- **STM32**
  - Add all modules enabled in STM32F405 to STM32F407. #4385. Thanks @hierophect.
  - Fix `UART.deinit()`. #4383. Thanks @hierophect.
  - Add GD25Q16C as a possible flash chip. #4356. Thanks @jerryneedell.
- **Teensy 4.0 and 4.1**
  - Enable EVE. #4342. Thanks @jamesbowman.

### Build and infrastructure changes
- Run code-formatting over source code based and add to pre-commit. #4362, #4415. Thanks @microDev1 and @jepler.
- Shrink some builds, using optimization flags. #4333. Thanks @dhalbert.
- Avoid secondary build failure when a test fails. #4340. Thanks @jepler and thanks @microDev1 for the original inspiration PR. 
- Automatically count `EXTERNAL_FLASH_DEVICES`. #4358. Thanks @jepler.

### Documentation
- Improve documentation for `RTC`, `TouchIn`, and `analogio`. #4402, #4407. Thanks @jposada2020.
- Add `README.rst` link to SourceGraph, which provides searching in the `circuitpython` repo. #4416. Thanks @tannewt.
- Add RP2040 port to `README.rst`. #4416. Thanks @tannewt.
- Correct and enhance documentation for `usb_cdc`. #4359. Thanks @dhalbert.
- Fix typos in `microcontroller.nvm` documentation. #4346. Thanks @jepler.
- Translation additions and improvements. Thanks:
  - @MisterD66 (German)
  - @Edrig (French)
  - @hugodahl (French)
  - @Padanian (Italian)
  - @bergdahl (Swedish)
  - Amir Muhammad Al-Omari (Swedish)
  - @fede2cr (Spanish)
  - @jposada202020 (Spanish)
  - @wtuemura (Portuguese - Brazil)
  - @hexthat (Chinese - Pinyin)
  - Luca De Filippo (Italian)

## New boards since 6.2.0-beta.3
- Franzininho WiFi Wroom. #4347. Thanks @FBSeletronica.
- Franzininho WiFi Wrover.#4348.  Thanks @FBSeletronica.
- Pimoroni Tiny 2040. #4228. Thanks @ZodiusInfuser.
- Pimoroni Keybow 2040. #4228. Thanks @ZodiusInfuser.
- Pimoroni PicoSystem. #4228. Thanks @ZodiusInfuser.
- SparkFun MicroMod nRF52840. #4350. Thanks @nitz.
- SparkFun Pro Micro RP2040. #4419. Thanks @spe2.

## Breaking changes since 5.x
- `i2cslave` is now `i2cperipheral` and the class in it is changed as well.
- The `stop` kwarg has been removed from `I2C.writeto()`. If no stop is desired, then use `writeto_then_readfrom`.
- The default speed of busio.I2C and board.I2C is now 100khz, not 400khz as before. Use `busio.I2C` to set the speed explicitly.
- `_bleio.ConnectionError` has been removed. Code will now raise the native `ConnectionError` instead.

## Known issues
- ESP32-S2: Crash when repeatedly creating and destroying busio.I2C object on ESP32-S2. #3846.
- RP2040: A few I2C devices do not work on the RP2040 with `busio.I2C`. Use `bitbangio.I2C` instead, and use `bitbangio.I2C(..., probe=False)` if necessary. See #4082 and #4235.
- See https://github.com/adafruit/circuitpython/issues for other issues.

## Thanks
Thank you to all who used, tested, and [contributed since 6.2.0-beta.3](https://github.com/adafruit/circuitpython/graphs/contributors?from=2021-03-03&to=2021-03-18&type=c), including @ajs256, @askpatrickw, @bergdahl, @caternuson, @danielwarnersmith, @DavePutz, @dglaude, @dhalbert, @dpgeorge, @Edrig, @falkenad, @FBSeletronica, @fede2cr, @FoamyGuy, @hathach, @hexthat, @hierophect, @hugodahl, @ismael-miguel, @jamesbowman, @jepler, @jerryneedell, @jposada202020, @kamtom480, @kattni, @kevinjwalters, @kmatch98, @ladyada, @makermelissa, @microDev1, @mintakka, @MisterD66, @nitz, @Padanian, @siehputz, @skieast, @spe2, @tannewt, @tylercrumpton, @tyomitch, @v923z, @weblate, @wtuemura, and many others on GitHub and Discord. Join us on the [Discord chat](https://adafru.it/discord) to collaborate.

## Documentation
Documentation is available [in readthedocs.io](https://circuitpython.readthedocs.io/en/latest/).

This release is based on [MicroPython 1.9.4 @25ae98f](https://github.com/micropython/micropython/commit/25ae98f07cb3c4488cb955403dfe56b8bb8db6f0). Support upstream MicroPython by purchasing [a PyBoard](https://store.micropython.org/#/store) (from Adafruit [here](https://www.adafruit.com/product/2390)) or [sponsoring MicroPython on GitHub](https://github.com/sponsors/micropython).

## Translations
One important feature of CircuitPython is translated control and error messages. With the help of fellow open source project [Weblate](https://weblate.org/), we're making it even easier to add or improve translations. Sign in with an existing account such as Github, Google or Facebook and [start contributing through a simple web interface](https://hosted.weblate.org/engage/circuitpython/). No forks or pull requests needed!

## Troubleshooting
Check out [this guide](https://learn.adafruit.com/welcome-to-circuitpython/troubleshooting) for info on common problems with CircuitPython. If you are still having issues, then post to the [Adafruit Support Forums](https://forums.adafruit.com/viewforum.php?f=60) and join [Discord](https://adafru.it/discord).

**Comment by dhalbert** [comment]
(Explanation - after accidentally pressing "Publish Release" instead of "Save Draft", I am going to keep draft release notes in an issue, so that can't happen again. Two other advantages are that the editing interface has a menu bar, unlike the release notes editor page, and it's public. I'll create an issue for each upcoming release and then close it on release.)

**Comment by microDev1** [comment]
> I'll create an issue for each upcoming release and then close it on release.

This is a good change. 👍
Should these upcoming release notes be pinned?

**Comment by dhalbert** [comment]
Good idea - pinned.

**Comment by ajs256** [comment]
Suggestion: The last release to include builds as release assets was for 4.x, maybe we don't need the explanation that assets aren't on the release page anymore.

**Comment by ajs256** [comment]
Now that there are issue templates, the "file an issue link" should link to [`/issues/new/choose`](https://github.com/adafruit/circuitpython/issues/new/choose). The current link opens a blank issue, instead of the template list.

**Comment by dhalbert** [comment]
> Now that there are issue templates, the "file an issue link" should link to [`/issues/new/choose`](https://github.com/adafruit/circuitpython/issues/new/choose). The current link opens a blank issue, instead of the template list.

Fixed -thanks!

**Comment by dhalbert** [comment]
6.2.0-beta.4 released.
