### ISSUE TITLE
busio.SPI not working as expected in CircuitPython 6.2.0.beta.1

### ISSUE THREAD

**Issue by jposada202020** [adafruit/circuitpython#4369]
**Firmware**

```python
Adafruit CircuitPython 6.2.0-beta.1 on 2021-01-27; Seeeduino Wio Terminal with samd51p19
```

**Code/REPL**

```python
>>> import board
>>> import digitalio
>>> import busio
>>> import adafruit_sdcard
>>> spi = busio.SPI(board.SD_SCK, MOSI=board.SD_MOSI, MISO=board.SD_MISO)
>>> cs = digitalio.DigitalInOut(board.SD_CS)
>>> sdcard = adafruit_sdcard.SDCard(spi, cs)

```

**Behavior**

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/adafruit_sdcard.py", line 116, in __init__
  File "/lib/adafruit_sdcard.py", line 137, in _init_card
  File "/lib/adafruit_sdcard.py", line 125, in _clock_card
AttributeError: 'SPIDevice' object has no attribute 'spi'
```

**Description**

- Error while trying to use the sd card library
- Only happens with Circuitpython 6.2.0-beta-1 and above
- Asked in Discord, nobody heard about this

**Additional Info**

This works well in 
```python
Adafruit CircuitPython 6.2.0-beta.0 on 2021-01-22; Seeeduino Wio Terminal with samd51p19
```

```python
>>> import board
>>> import digitalio
>>> import busio
>>> import adafruit_sdcard
>>> spi = busio.SPI(board.SD_SCK, MOSI=board.SD_MOSI, MISO=board.SD_MISO)
>>> cs = digitalio.DigitalInOut(board.SD_CS)
>>> sdcard = adafruit_sdcard.SDCard(spi, cs)
>>> 

```

Review the comit log on https://github.com/adafruit/circuitpython/compare/6.2.0-beta.1...main, this catched my eye related to SPI or BUSIO. 

Changes in these files in the release that could be related:
* https://github.com/adafruit/circuitpython/compare/6.2.0-beta.1...main#diff-29d057f035549d38cebb7837b665416f1e5094dbaed1e0c768f84b914f7b8d51
* https://github.com/adafruit/circuitpython/compare/6.2.0-beta.1...main#diff-d1ed5c69625e5c46dd28c67cc98f364f76c369187ba2727a45114e69314829f4
* https://github.com/adafruit/circuitpython/compare/6.2.0-beta.1...main#diff-17bd45f5bae76167f7d48d01ef99a1bfd442d4f4d37c58a1e856e3d2a0d91795

Removing [this](url) line resolves the issue.

**Comment by jepler** [comment]
Upgrade adafruit_sdcard.  It looks like you have a version which does not contain the fix for https://github.com/adafruit/Adafruit_CircuitPython_SD/issues/42.
