### ISSUE TITLE
[RFC] hid keyboard layouts

### ISSUE THREAD

**Issue by bitboy85** [adafruit/circuitpython#4374]
I've created a slightly modified version of the existing keyboard library which allows to change the keyboard layout. It includes a german layout.
Before creating a pull request i wanted to ask for comments.

https://github.com/bitboy85/circuitpython_keyboardext

**Comment by tannewt** [comment]
@bitboy85 PRs are the best way to get feedback on changes because they allow inline comments. So, please make one.

**Comment by bitboy85** [comment]
OK, so here it is: https://github.com/adafruit/Adafruit_CircuitPython_HID/pull/60

**Comment by tannewt** [comment]
Thanks! Further comments are on the PR. Closing this.
