### ISSUE TITLE
HID Gamepad Core Support for 3.x

### ISSUE THREAD

**Issue by eighthree** [adafruit/circuitpython#438]
Hi folks! I'm currently using a feather m0 and a joy featherwing as a HID Keyboard device for a RetroPie build and would love to have HID Gamepad support for 3.0 :)

Would love to help test this as well.

**Comment by tannewt** [comment]
@dhalbert Is this on your radar for your USB work?

**Comment by dhalbert** [comment]
Implemented by #776. @eighthree: this should be in the next 3.0 alpha. Thanks for testing, if you have a chance! See #776 and https://github.com/adafruit/Adafruit_CircuitPython_HID/pull/19 for details.
