### ISSUE TITLE
Digitizer HID 

### ISSUE THREAD

**Issue by ArielWolle** [adafruit/circuitpython#4396]
Hey I know that the digitizer is written into your HID devices but not enabled as it say here https://github.com/adafruit/circuitpython/blob/550eab2ddda780adb939693a51c8c07c4a540c36/tools/gen_usb_descriptor.py#L24.

I've been trying to build circuitpython with this feature enabled but can seem to get the rp2040 port to build properly (with or without the changes). Whether its a uf.2 build or advice on how to get a digitizer working anything would be useful thanks!

**Comment by dhalbert** [comment]
Here you go: https://learn.adafruit.com/building-circuitpython/customizing-usb-devices
