### ISSUE TITLE
Can't disable mass storage for the Pimoroni tiny 2040

### ISSUE THREAD

**Issue by ArielWolle** [adafruit/circuitpython#4417]
Error when building lastest firmware (git clone https://github.com/adafruit/circuitpython.git)

**Code/REPL**

adding the line: CIRCUITPY_USB_MSC = 0
to /ports/raspberrypi/boards/pimoroni_tiny2040/mpconfigboard.mk results in a build error 

**Behavior**

![image](https://user-images.githubusercontent.com/36164850/111230513-1c4cae80-85be-11eb-8062-44b8cfe1a077.png)

**Description**

Trying to disable mass storage as i need to write to the tiny 2040 using the storage module but dont want to eject every time i plug it in. Being used as an HID device so needs to be plugged into data and power of usb not just power. Have not tried any other rp2040 boards, just the tiny 2040.

Removing [this](url) line resolves the issue.

**Comment by ladyada** [comment]
@ArielWolle wanna try submitting a PR where the line is behind an #ifdef or #ifnef (the url isnt working)

**Comment by dhalbert** [comment]
We thought this was fixed by #4283, which was merged, so it should be in the latest source base. Could you paste the source URL again?

**Comment by ArielWolle** [comment]
i a git cloned staright from the main branch url yesterday i will try again right now

**Comment by ArielWolle** [comment]
Just tried rebuilding again using "git clone https://github.com/adafruit/circuitpython.git" and same issue works as soon as I take that line out

**Comment by deshipu** [comment]
It's possible it worked with my test board because I had ``CIRCUITPY_STORAGE`` disabled.

@ArielWolle which line exactly? Your link point to nowhere.

**Comment by ArielWolle** [comment]
I added the line 
CIRCUITPY_USB_MSC = 0
to the bottom of:
https://github.com/adafruit/circuitpython/blob/1be5ca7881a8aa8d32a783bc6a94994886463c30/ports/raspberrypi/boards/pimoroni_tiny2040/mpconfigboard.mk

**Comment by miclooking** [comment]
> 
> 
> I added the line
> CIRCUITPY_USB_MSC = 0
> to the bottom of:
> https://github.com/adafruit/circuitpython/blob/1be5ca7881a8aa8d32a783bc6a94994886463c30/ports/raspberrypi/boards/pimoroni_tiny2040/mpconfigboard.mk
> 
> This is what my mpconfigboard.mk board looks like
> 
> ![image](https://user-images.githubusercontent.com/36164850/111366863-73a85880-866a-11eb-9f39-a8e6ae5a4735.png)

I get the same error when adding CIRCUITPY_USB_MSC = 0 in mpconfigboard.mk for Raspberry Pi Pico.
Is there any solution for this?
Thanks.
