### ISSUE TITLE
Missing uPy "sys.maxsize" 

### ISSUE THREAD

**Issue by Mantic** [adafruit/circuitpython#442]
CircuitPython is missing "sys.maxsize" from the micropython libraries, as mentioned here: https://forums.adafruit.com/viewtopic.php?f=60&t=126615

**Comment by dhalbert** [comment]
It's turned on in the Express boards builds, but not for Gemma M0, Trinket M0, and Feather M0 basic builds. It uses 24 bytes. We should turn it on for all builds in 3.0 definitely.

**Comment by dhalbert** [comment]
Fixed by #518.
