### ISSUE TITLE
rp2040: allow rotaryio pins to be reversed

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#4422]
github user @wildestpixel notes that the rp2040's quadrature decoder doesn't allow the pins to be swapped in order.  If feasible, allow the pins to be specified in either order, and if they are in the swapped order then switch the counting direction.

**Comment by daveythacher** [comment]
Adding bool to constructor to reverse direction would probably solve this. It looks like this would about 10 lines of code. Bool change operation from += to -=. Logic is incremental encoder so reversing the pins will just change the direction.

https://github.com/adafruit/circuitpython/blob/51c09e877d72d07d06276a8f9d40342833412a72/ports/raspberrypi/common-hal/rotaryio/IncrementalEncoder.c#L161

Probably should add bool to structure here. 
https://github.com/adafruit/circuitpython/blob/51c09e877d72d07d06276a8f9d40342833412a72/ports/raspberrypi/common-hal/rotaryio/IncrementalEncoder.h#L34-L40

Set in constructor.
https://github.com/adafruit/circuitpython/blob/51c09e877d72d07d06276a8f9d40342833412a72/ports/raspberrypi/common-hal/rotaryio/IncrementalEncoder.c#L60-L68

Would break compatibility with: (May be autogenerated, but for all platforms?) No idea on how the python section connects in.
https://circuitpython.readthedocs.io/en/latest/shared-bindings/rotaryio/index.html

https://en.wikipedia.org/wiki/Incremental_encoder
