### ISSUE TITLE
Allow changing the iJack name for MIDI when we do dynamic USB descriptors

### ISSUE THREAD

**Issue by infovore** [adafruit/circuitpython#4433]
I've been prodding this library as an alternative to some other code I have, and it's super-impressive. One question: what's the most appropriate way to change the auto-generated device name?

In my MIDI Monitor tool, I get this:

![image](https://user-images.githubusercontent.com/1103/111634708-ad09d100-87ee-11eb-935c-2e49684f0e92.png)

and I've had good success with other boards on changing the detected devicename - which I appreciate might be a USB setting rather than a MIDI-specific setting. I'm new to CP, so am imagining this is a `settings.py` or `boot.py` issue, but don't quite know where to begin.

**Comment by dhalbert** [comment]
transferred and re-titled

**Comment by kevinjwalters** [comment]
@infovore How do two boards show up in that tool?

**Comment by samkusnetz** [comment]
hello. i'm a relatively new user of circuitpython, recently crossing over from my long, long time with arduinos. i would enthusiastically appreciate this feature!

**Comment by dhalbert** [comment]
Superseded by #4191.
