### ISSUE TITLE
QT PY: no yellow status LED on boot

### ISSUE THREAD

**Issue by Neradoc** [adafruit/circuitpython#4448]
On the QT PY, the status LED does not light yellow on boot (for the reset to safe mode procedure).
This is because the LED needs an enable pin that is set in `board_init` that is called after `wait_for_safe_mode_reset`.

I tried moving `board_init` earlier, but:

`filesystem_init` must be before `board_init` (because of SPI displays as stated by the comment in main.c).
`board_init` must be before `wait_for_safe_mode_reset` so the status LED can be used.
`wait_for_safe_mode_reset` must be before `filesystem_init` (uses safe_mode in an argument).

So this needs a different type of solution.

**Comment by dhalbert** [comment]
Related to #4451.

**Comment by kattni** [comment]
The ItsyBitsy RP2040 also does not show yellow on start up.

**Comment by kattni** [comment]
This is resolved by #4743. It can be closed when that PR is merged. Tested on both Itsy and QT Py.
