### ISSUE TITLE
QT Py Analog Input pin reading voltage even when nothing is connected

### ISSUE THREAD

**Issue by levgrav** [adafruit/circuitpython#4469]
I have nothing connected to the QT Py except for the USB C cable and I am reading the pin value for  A3 and it gives me a reading that fluctuates between around 25000 and 32000 and that does not make sense to me. Is this normal?

Here is my code:
```
import board
import time
from analogio import AnalogIn

therm = AnalogIn(board.A3)

while True:
    v = therm.value
    print(v)
    time.sleep(0.1)
```

**Comment by dhalbert** [comment]
You are reading electrical noise on the pin because it's unconnected.
