### ISSUE TITLE
Suggestion for adafruit_display_shapes.line and line thickness

### ISSUE THREAD

**Issue by bill22152** [adafruit/circuitpython#4476]
Can we add a thickness to this function?  make it a default to 1 but allow user to set line width.

Also, can the line end in a Dot, Arrow, or nothing?

**Comment by ladyada** [comment]
this is actually much harder than you'd think! line thickness needs to be handled as a low-level polygon drawing function.

**Comment by kmatch98** [comment]
Currently one option is to use the vectorio library and draw a polygon (rectangle). I think it will created “filled” polygons only. 

If you need an example of a vectorio polygon look at the needle on the recent Dial widget here:  https://github.com/adafruit/Adafruit_CircuitPython_DisplayIO_Layout/blob/main/examples/displayio_layout_dial_simpletest.py

If you’d like other basic examples let me know and I can try to find one m

**Comment by kmatch98** [comment]
Oh and here is the link to the vectorio documentation:
https://circuitpython.readthedocs.io/en/6.1.x/shared-bindings/vectorio/index.html

**Comment by ladyada** [comment]
yeah a line that is not thickness 1 needs to be drawn as a filled poly!

**Comment by jposada202020** [comment]
@I should have read this before, @kmatch98 and I were having a similar discussion here . https://github.com/adafruit/CircuitPython_Community_Bundle/pull/63
Maybe you could draw this in the python level!?

**Comment by kmatch98** [comment]
I’d suggest the new library that @jposada202020 added to draw lines with arrows:

https://github.com/jposada202020/CircuitPython_ArrowLine

**Comment by jposada202020** [comment]
I have added in the meantime a dot ending. It is available now in the Adafruit Community Bundle.

**Comment by kmatch98** [comment]
This is addressed in the Python libraries and other code. Closing for now.
