### ISSUE TITLE
btree for Circuitpython

### ISSUE THREAD

**Issue by bill22152** [adafruit/circuitpython#4477]
Sometimes you just need indexed persistent storage without wifi.

**Comment by ajs256** [comment]
You can write files to the `CIRCUITPY` drive from user code. [This guide](https://learn.adafruit.com/cpu-temperature-logging-with-circuit-python/) gives you the basics.

**Comment by bill22152** [comment]
I need C.R.U.D. I get from btree or I could have used a text fileWm E Fitzpatrick(703) ***@***.***
-------- Original message --------From: ajs256 ***@***.***> Date: 3/24/21  4:51 PM  (GMT-05:00) To: adafruit/circuitpython ***@***.***> Cc: bill22152 ***@***.***>, Author ***@***.***> Subject: Re: [adafruit/circuitpython] btree for Circuitpython (#4477) 
You can write files to the CIRCUITPY drive from user code. This guide gives you the basics.

**Comment by dhalbert** [comment]
MicroPython has an optional `btree` module. Have you used it before? We have not turned it on in any CircuitPython builds.

**Comment by bill22152** [comment]
I have used btree in 'Python', 'C' and 'C++' projects in the past and it works well at mapping hash arrays to storage..
It's light weight and easy to use.

Will MicroPython run on a PyPortal?

**Comment by dhalbert** [comment]
MicroPython is not supported on the PyPortal. If you would like some kind of keyed storage immediately, you can use the `json` module and read and write JSON files, though it will not be as efficient as `btree`. We can leave this open if you would like something like `btree` in the long run.
