### ISSUE TITLE
another problem with busdevice-in-core and bitbangio?

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#4494]
I found that with the following code, the with-statement is never entered (circuitpython waits forever).  However, if I change the type of spi bus to board.SPI() aka busio.SPI, it completes.

```python
# spi = board.SPI()
spi = bitbangio.SPI(board.SCK, MISO=board.MISO, MOSI=board.MOSI)
cs = digitalio.DigitalInOut(board.D10)
dev = adafruit_bus_device.spi_device.SPIDevice(spi, cs)
print("before with-statement")
with dev as card:
    print("with-statement")
print("after with-statement")
```

**Comment by jepler** [comment]
@ladyada this is one of the problems that prevents bitbangio to work with adafruit_sdcard, the other is that the constant write value during an SPI read transaction is not supported.

**Comment by ladyada** [comment]
ok!
