### ISSUE TITLE
Missing parameter in Error Message

### ISSUE THREAD

**Issue by lesamouraipourpre** [adafruit/circuitpython#4505]
https://github.com/adafruit/circuitpython/blob/010232574eda7612fc2d37e3ca42a4d936d9737e/shared-bindings/time/__init__.c#L282

If I'm reading the code correctly `len` should be passed into the error message as well as `9`.
FWIW my C skills are very rusty.

**Comment by tannewt** [comment]
You are right! It should be `9, len);`. Want to make a PR? Thanks!
