### ISSUE TITLE
make: *** No rule to make target 'common-hal/sdioio/SDCard.c'

### ISSUE THREAD

**Issue by K2AAE** [adafruit/circuitpython#4514]
Current build 3/29/2021 new firmware build after disabling modules

BOARD=adafruit_feather_rp2040
ERROR:
`kevin@Aorus:~/circuitpython/ports/raspberrypi$ make BOARD=adafruit_feather_rp2040
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
make: *** No rule to make target 'common-hal/sdioio/SDCard.c', needed by 'build-adafruit_feather_rp2040/genhdr/qstr.split'.  Stop.
kevin@Aorus:~/circuitpython/ports/raspberrypi$`

Module settings in:
/circuitpython/ports/raspberrypi/adafruit_feather_rp2040/mpconfigboard.mk
CIRCUITPY_SDIOIO=1
CIRCUITPY_SDCARDIO=0

**Comment by ladyada** [comment]
this isnt a bug, we dont have SDIO support at this time

**Comment by K2AAE** [comment]
Thanks
