### ISSUE TITLE
Supervisor: return the actual set_next_stack_limit set value

### ISSUE THREAD

**Issue by anecdata** [adafruit/circuitpython#4520]
`supervisor` has a function to "Set the size of the stack for the next vm run."
https://circuitpython.readthedocs.io/en/latest/shared-bindings/supervisor/index.html#supervisor.set_next_stack_limit

But "If its too large, the default will be used." The function has no return value. Returning the actual value set would be useful. to know whether the request was successful, or for programmatically obtaining the default limit.

**Comment by spencer-burke** [comment]
I'll give this a shot.

**Comment by tannewt** [comment]
@spencer-burke We're happy to guide you on our Discord: https://adafru.it/discord

**Comment by tannewt** [comment]
As @microDev1 points out on the PR:

> I don't think this resolves issue #4520. The stack size is set on the next VM run so with the function call there isn't a way to confirm whether the requested stack_limit is used or the default_limit is used.

So, I don't think this is possible. Sorry about the confusion @spencer-burke.

**Comment by tannewt** [comment]
I think we should leave it as-is. Sorry!
