### ISSUE TITLE
Disable HID Gamepad by default once dynamic HID descriptors are implemented

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#4531]
HID Gamepad causes MacOS and iOS not to respond to HID Mouse. in 7.0.0, disable HID Gamepad by default, assuming that dynamic HID descriptors are implemented. Addresses #4479.

**Comment by hathach** [comment]
I am late to the party, did re-arrange #4560 the report ID get both mouse and gamepad work with iOS. I have seen similar issue with BLE HID as well on the arduino nrf52. Plan to get back to implement it in the near future. Another way it adding additional HID interface for gamepad, it may work.

**Comment by dhalbert** [comment]
@hathach #4560 fixed it on MacOS but not iOS. I am deep into dynamic USB descriptors now, so it should be possible. I will not implement two HID devices yet, but maybe eventually.

**Comment by dhalbert** [comment]
Fixed by #4689.
