### ISSUE TITLE
Web interface for custom firmware builds

### ISSUE THREAD

**Issue by MicroDev1** [adafruit/circuitpython#4552]
Proposal for having a web interface to build custom firmware where only the modules that are required for a specific project can be selected and if storage space is saved doing this it can be added to the `CIRCUITPY` drive.

Something like this: https://nodemcu-build.com/

**Comment by tannewt** [comment]
I'm ok with this but would ask that it *not* label the builds with the CircuitPython name. Creating essentially infinite combinations will be a huge support burden. (We have trouble with folks mixing different CP versions already.)

**Comment by ajs256** [comment]
> that it not label the builds with the CircuitPython name

How about "CustomPython"? Or "MyPython"?

**Comment by tannewt** [comment]
CustomPython would work MyPython might be too close to [MyPy](http://mypy-lang.org/).

**Comment by hierophect** [comment]
SockPython? That way we can make one of these for Blinka:
![image](https://user-images.githubusercontent.com/5904176/113742997-2b141600-96d1-11eb-8a97-771dd3e80215.png)

**Comment by MicroDev1** [comment]
You can now make custom board builds in your fork. See https://github.com/adafruit/circuitpython/pull/7594#issuecomment-1432525280.
