### ISSUE TITLE
bitbangio.I2C doesn't work on imxrt1010-evk

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#4568]
I have the evk and attached a BNO055 sensor to it, wondering whether bitbangio was a workaround for #3763 (it's not)

Devices should be [26,40] but software bitbangio says ...
```
>>> i2c = bitbangio.I2C(sda=board.SDA, scl=board.SCL)
>>> i2c.try_lock()
True
>>> i2c.scan()
[26, 40, 41, 42, 43, 44, 45]
>>> i2c.scan()
[26, 40, 41]
>>> i2c.scan()
[26, 40, 41]
>>> i2c.scan()
[26, 40, 41]
```

Underlying cause could be similar to #3845 but not sure yet.

**Comment by dhalbert** [comment]
Re-tested on a Metro M7 1011, with an SHT40 and a BNO055. Seems to work now. Scan works. To get the BNO055 to work, I had to length the clock-stretching `timeout` when creating the `bitbangio.I2C()` object. So something fixed this, maybe #5866.
