### ISSUE TITLE
Teensy 4.0/4.1 hardware RTC does not keep time unpowered while having vbat supply

### ISSUE THREAD

**Issue by Remowylliams** [adafruit/circuitpython#4574]
**Firmware**

```python
Adafruit CircuitPython 6.2 and earlier on 2021-04-07; Teensy 4.0/4.1
```

**Code/REPL**

```python
import rtc
import time
r = rtc.RTC()
r.datetime = time.struct_time((2021, 4, 8, 19, 11, 15, 2, -1, -1))
time.localtime()
struct_time(tm_year=2021, tm_mon=4, tm_mday=8, tm_hour=19, tm_min=11, tm_sec=26, tm_wday=3, tm_yday=98, tm_isdst=-1)
```

**Behavior**

With a vbat (3v Li) battery connected (battery is 3.2v) when you pull the usb connection and reconnect..
Adafruit CircuitPython 6.2.0-rc.0 on 2021-04-06; Teensy 4.0 with IMXRT1062DVJ6A
```python
import rtc
import time
time.localtime()
struct_time(tm_year=1970, tm_mon=1, tm_mday=1, tm_hour=0, tm_min=1, tm_sec=38, tm_wday=3, tm_yday=1, tm_isdst=-1)
```
**Description**

A battery backed RTC should keep time.

It's just amazing no one seems to have reported the problem before now. Part of the reason I went with
a Teensy 4.0 is it had a battery backed RTC I needed in my project without adding extra bulk beyond a battery.
 
**Additional Info**

I have dug into the source code and SDK and found that all the routines for interacting with the RTC could
be found here circuitpython/ports/mimxrt10xx/sdk/devices/MIMXRT1062/drivers/fsl_snvs_lp.c
I don't have a full enough experience with the circuitpython code to figure out how to fix it.

Thanks in advance I hope I can use CircuitPython in my projects in the future.

**Comment by zestyping** [comment]
@tannewt Any insight into why this isn't working?  Do we know that the `rtc` module is even configured to read from the RTC chip in this case?

**Comment by tannewt** [comment]
I haven't worked on this code in quite a while. We've never officially started supporting it with Adafruit-funded folks so it's unlikely we'll get to it soon.

It does look like the `rtc` module talks to the internal RTC. The place to look is here: https://github.com/adafruit/circuitpython/blob/main/ports/mimxrt10xx/common-hal/rtc/RTC.c

That's the code that configures the RTC of the device. `supervisor/port.c` may have some clock initialization in it as well. Losing the value may be a power config problem or re-init problem. I'm not sure which.

**Comment by karelv** [comment]
Any updates?
