### ISSUE TITLE
should gettext be in the requirements list?

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#4626]
I don't see gettext in the requirements-dev.txt  list https://github.com/adafruit/circuitpython/blob/main/requirements-dev.txt

Isn't it needed for "msgfmt" ?

This came up in a recent forum discussion https://forums.adafruit.com/viewtopic.php?f=60&t=178208#p867734

**Comment by dhalbert** [comment]
`requirements-dev.txt` is only Python packages. `msgmft` is part of `gettext`, which is installed using `apt`: https://learn.adafruit.com/building-circuitpython/linux#install-build-tools-on-ubuntu-2986713-2

**Comment by jerryneedell** [comment]
Ah -- sorry for the confusion
