### ISSUE TITLE
Pushes to temporary patch branches get uploaded to S3

### ISSUE THREAD

**Issue by Neradoc** [adafruit/circuitpython#4632]
On occasion a patch branch on the adafruit/circuitpython repository is created for a Pull Request. This commit will be uploaded to S3, since every commit is uploaded to S3 regardless of the branch and whether or not it comes from an accepted PR. I feel like that could be confusing when pointing people to S3 to try "the latest".
Could/should those be skipped for the S3 upload in CI ?

**Comment by tannewt** [comment]
Ya, I think we should only include pushes to main. I think this is what to change: https://github.com/adafruit/circuitpython/blob/main/.github/workflows/build.yml#L403

**Comment by Neradoc** [comment]
I think changing all the relevant ifs to add `github.ref == 'refs/heads/main'` would work to limit pushes without interfering with releases (on 6.x branches for example), but I don't know how to test it:
> if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'release' && (github.event.action == 'published' || github.event.action == 'rerequested'))

I followed the doc example of a push action that is limited to the main branch:
https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#determining-when-to-use-contexts
> In this example, the if statement checks the github.ref context to determine the current branch name; if the name is refs/heads/main, then the subsequent steps are executed.

**Comment by tannewt** [comment]
I think you can test on your own fork with its branches. The S3 upload steps will be attempted but fail (I think.) We can also just do best guess and check to see how it changes for this repo.
