### ISSUE TITLE
CircuitPython core crashes after a try except catches an OSError: no SD card

### ISSUE THREAD

**Issue by stewmystre** [adafruit/circuitpython#469]
After a try except catches an 'OSError: no SD card' the next attempt to create an Adafruit_sdcard.SDCARD 
with an actual SD card present results in a CircuitPython core crash and subsequent boot into safe mode.

**Comment by kattni** [comment]
Unable to reproduce this issue with 3.0b. Please reopen this issue if you are still running into this issue. Thanks!
