### ISSUE TITLE
Investigate cookiecutter templates for easy library generation

### ISSUE THREAD

**Issue by tdicola** [adafruit/circuitpython#47]
Putting this on the main micropython lib but this really applies to the libraries (micropython-adafruit-* repos).  We're starting to get a lot of conventions for libraries, like having a .travis.yml to support auto MPY generation or adding libraries as submodules to the micropython bundler repo.  Let's see if we can capture all these things in a adafruit micropython library template so that a command can be run to give the scaffolding for a new library.  This could include stuff like .travis.yml, a readme with instructions on exactly what to do to get bundler support, an examples folder, etc.

Cookiecutter is a generic project templating tool worth checking out for this: https://github.com/audreyr/cookiecutter

**Comment by willingc** [comment]
@tdicola Cookiecutter is an awesome project. We are using it for Project Jupyter for widget constructions. One particularly nice cookiecutter template is https://github.com/audreyr/cookiecutter-pypackage cc/ @audreyr @hackebrot

**Comment by hackebrot** [comment]
@willingc I do think [cookiecutter](https://github.com/audreyr/cookiecutter) is a great project (but I'm a little biased 😁)

**Comment by tannewt** [comment]
Here is an initial cookiecutter for CircuitPython libraries: https://github.com/adafruit/cookiecutter-adafruit-circuitpython

**Comment by willingc** [comment]
Nice! Thanks @tannewt.
