### ISSUE TITLE
samd21: Correct DAC maximum speed

### ISSUE THREAD

**Issue by jeremyherbert** [adafruit/circuitpython#4701]
Hi,

This is a really esoteric issue, but I was looking through the code and found this line: https://github.com/adafruit/circuitpython/blob/e6dc3e4686c74ad1828d07475194fc45e8f65ab0/ports/atmel-samd/common-hal/analogio/AnalogOut.c#L87

However, in the datasheet here: https://ww1.microchip.com/downloads/en/DeviceDoc/SAM_D21_DA1_Family_DataSheet_DS40001882F.pdf

Section 47.6.3 does not exist (section 47.6 does, but that is the document revision history which doesn't have anything relevant). There is however a section 37.6, which contains Table 37.7 - "Maximum Peripheral Clock Frequencies". But this table states that the maximum DAC clock is 350kHz, not 12MHz. FWIW the table also states the maximum ADC clock frequency wrong as well, so unsure what I should be believing...

Could you please correct this comment to indicate where the 12MHz came from?

**Comment by dhalbert** [comment]
Thanks for spotting this. The "SAMD21" and "SAMD51" got reversed in error when the comments were reformatted at a certain commit. See:
https://github.com/adafruit/circuitpython/commit/5c24023240be492ddcf0cacec21318a182933391

![image](https://user-images.githubusercontent.com/2847802/116822207-91af1700-ab4b-11eb-9753-b31517d3b771.png)
