### ISSUE TITLE
Improve bitbangio.SPI to have same API as busio.SPI

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#472]
`bitbangio.SPI` is missing `write_readinto()` (bitdirectional SPI) and also doesn't have the optional buffer slicing `start` and `end` arguments. Implement these to make it have the same API as `busio.SPI`.

**Comment by Sigafoos** [comment]
I'd like to tackle this one if possible!

**Comment by deanm1278** [comment]
hey @Sigafoos I'm gonna look at this right now :)

**Comment by tannewt** [comment]
@deanm1278 this is done right?

**Comment by jepler** [comment]
It looks like #564 did *NOT* add the out_start, out_end, in_start, and in_end keyword-only arguments to `bitbang.SPI.write_readinto`.

**Comment by tannewt** [comment]
Fixed by #821
