### ISSUE TITLE
Replacement for sys.print_exception()

### ISSUE THREAD

**Issue by anecdata** [adafruit/circuitpython#4748]
Removed with the MicroPython 1.12 merge:
https://github.com/adafruit/circuitpython/pull/4693
But something like it is super useful for debugging, especially for intermittent exceptions.

There was a brief discussion on Discord:
https://discord.com/channels/327254708534116352/327298996332658690/839326516596178944

**Comment by tannewt** [comment]
@Neradoc would you mind posting an example of handling an exception in CPython that we could make work in CircuitPython? (I've never done it in CPython.) Thanks!

**Comment by Neradoc** [comment]
I haven't used it in C Python, my concern is how to implement code like that (6.2.0).

```py
import adafruit_logging as logging
import io
import sys

logger = logging.getLogger(__name__)

try:
    do_some_stuff()
except NameError as ex:
    # just print exception without raising (debugging)
    sys.print_exception(ex)
    # log exception with a logger (stdout or file)
    with io.StringIO() as sio:
        sys.print_exception(ex, sio)
        logger.error(sio.getvalue())
    # log exception to a file
    with open("/log.txt", "a") as fp:
        sys.print_exception(ex, fp)
```
```
Traceback (most recent call last):
  File "test_circuitpython.py", line 8, in <module>
NameError: name 'do_some_stuff' is not defined
3139.43: ERROR - Traceback (most recent call last):
  File "test_circuitpython.py", line 8, in <module>
NameError: name 'do_some_stuff' is not defined
```
To replicate that feature, I think it's easier to give access to the string, and with a function that doesn't take 3 arguments. We could also have `print_exc()`.
```py
import logging
import traceback
import os

logger = logging.getLogger(__name__)

try:
    do_some_stuff()
except NameError:
    trace = traceback.format_exc()
    # just print exception without raising
    print(trace)
    # log exception with a logger (stdout or file)
    logger.error(trace)
    # log exception to a file
    with open("log.txt", "a") as fp:
        fp.write(trace)
```
```
Traceback (most recent call last):
  File "/path/to/the/test_cpython.py", line 8, in <module>
    do_some_stuff()
NameError: name 'do_some_stuff' is not defined

Traceback (most recent call last):
  File "/path/to/the/test_cpython.py", line 8, in <module>
    do_some_stuff()
NameError: name 'do_some_stuff' is not defined
```
Alternatives.
Note the first argument is `etype` and the doc says:
> Changed in version 3.5: The etype argument is ignored and inferred from the type of value.
```py
    trace = traceback.format_exception(None, ex, ex.__traceback__)
    print("".join(trace))
    traceback.print_exception(None, ex, ex.__traceback__)
    traceback.print_exception(*sys.exc_info())
    traceback.print_exc()
    with open("log.txt", "a") as fp:
        traceback.print_exception(None, ex, ex.__traceback__, file=fp)
```
Note: Circuitpython does not have `Exception.__traceback__` exposed.

**Comment by deshipu** [comment]
I would just like to note, that sometimes you don't want a complete traceback, but just the last one or two lines of it, so that you can scroll the error in a similar way as the microbit does it.

**Comment by microDev1** [comment]
I implemented a `traceback` module for this [here](https://github.com/adafruit/circuitpython/compare/main...microdev1:traceback).
Currently it just moves `sys.print_exception()` to `traceback.print_exception()`.

**Comment by ThomasAtBBTF** [comment]
This is very useful!
An old issue #3301 would be fixed with this!
Thank you for working on this.

**Comment by ThomasAtBBTF** [comment]
A

> I implemented a `traceback` module for this [here](https://github.com/adafruit/circuitpython/compare/main...microdev1:traceback).
> Currently it just moves `sys.print_exception()` to `traceback.print_exception()`.

It would also be super helpful to be able to obtain the traceback-string instead of just printing it.

**Comment by microDev1** [comment]
> It would also be super helpful to be able to obtain the traceback-string instead of just printing it.

Yup! as mentioned [above](https://github.com/adafruit/circuitpython/issues/4748#issuecomment-839138492) the plan is to have an api equivalent to [cpython traceback module](https://docs.python.org/3/library/traceback.html) but the availibilty of the module functions will vary depending on the board due to flash restrictions.

**Comment by tannewt** [comment]
Note that function availability shouldn't vary with board. variation should be done at the module level. For string support we could support supplying a file-like object that code just be a string buffer.
