### ISSUE TITLE
round() returns 0 always?

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#476]
@jedgarpark noticed this!

```
Adafruit CircuitPython 2.1.0 on 2017-10-17; Adafruit Trinket M0 with samd21e18
>>>
>>> round(1.0)
0
>>> round(2.0)
0
>>> round(3.0)
0
>>> round(3.2)
0
```

!?

**Comment by kattni** [comment]
He's still using 2.1, and the fix is in the newer unreleased version of CircuitPython.

**Comment by ladyada** [comment]
oops - ok thx! whee :)

**Comment by jedgarpark** [comment]
I mean no harm. ;)

**Comment by tannewt** [comment]
For the record, I'd much rather have issues like this than have people not
file issues that haven't been fixed. So good work everyone!
