### ISSUE TITLE
readthedocs is not building, possibly since #4844

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#4879]
@dhalbert noticed:
> FYI the "latest" readthedocs build has been failing for a while. Example: https://readthedocs.org/projects/circuitpython/builds/13973349/. I'm not sure what's wrong at first glance.
```
Running Sphinx v3.5.4
Traceback (most recent call last):
  File "setup.py", line 47, in <module>
    data_files=build_data_files_list(),
  File "setup.py", line 34, in build_data_files_list
    result.append((site.getsitepackages()[0] + "/" + package + "/",
AttributeError: module 'site' has no attribute 'getsitepackages'
make: *** [stubs] Error 1
```

@kattni asked me to file an issue and tag everybody.

I investigated and found that the problem may have been introduced by @FoamyGuy's #4844. I was able to duplicate the problem when using `virtualenv` (note: not `venv`!)
```
jepler@afk:/tmp$ rm -rf env; python3.7 -mvirtualenv -p python3.7 env
Already using interpreter /usr/bin/python3.7
Using base prefix '/usr'
/usr/lib/python3/dist-packages/virtualenv.py:1090: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
New python executable in /tmp/env/bin/python3.7
Also creating executable in /tmp/env/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
jepler@afk:/tmp$ /tmp/env/bin/python -c 'from site import getsitepackages'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'getsitepackages' from 'site' (/tmp/env/lib/python3.7/site.py)
```

Subsequently, I found concerns that besides not working in RTD the stubs might still not be in the right format for uploading to pypi.  I compared the layout of a wheel produced with `python setup.py bdist_wheel` (they are just zip files, but you have to trick your zip program into opening them!) to [lxml-stubs](https://files.pythonhosted.org/packages/e8/69/6d26ae5a0da93651ef6eca8b591193bb253f288df851d73700604ede535f/lxml_stubs-0.2.0-py3-none-any.whl) [on pypi](https://pypi.org/project/lxml-stubs/).

I have prepared #4878 which makes the layout look more like what I saw in lxml-stubs and allows mypy to work.  However, it can't be tested on RTD before being merged, unfortunately.

**Comment by dhalbert** [comment]
Fix works!

![image](https://user-images.githubusercontent.com/2847802/121557326-aa300e00-c9e2-11eb-9b8d-58af886b267b.png)
