### ISSUE TITLE
ESP32-S2 webserver

### ISSUE THREAD

**Issue by reppad** [adafruit/circuitpython#4892]
Hello makers,
Maybe I missed it but I couldn't find any way to use an ESP32-S2 board as a webserver with CircuiPython.
There is a library for the ESP32 throught SPI (adafruit_esp32spi_wsgiserver), I would very much like to have something comparable for the ESP32-S2, maybe in the wifi module of the ESP32-S2 port or via a dedicated library? 
Thanks for your great job on CircuitPython and microcontroller support in general!

**Comment by Neradoc** [comment]
There's a port of wsgiserver for the S2, I think I should add it to the community bundle, but it's usable as is.
https://github.com/Neradoc/circuitpython-native-wsgiserver

**Comment by reppad** [comment]
Thank you Neradoc, I'll look at it.
Indeed it would deserve to be in the bundle with an example which displays a web page !

**Comment by tannewt** [comment]
Closing. Thanks @Neradoc.
