### ISSUE TITLE
Do not freeze examples into internal frozen modules

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#491]
@jerryn pointed out that the code in the examples directory was frozen into the CPX frozen libraries. In the case he mentioned, some of the LIS3DH examples are actually buggy with respect to the CPX because the I2C address needed is different.

I propose not to freeze the examples. Not sure that .mpy's of examples are that useful anyway.

**Comment by ladyada** [comment]
yeah please dont freeze examples, they're more useful as plain text!

**Comment by dhalbert** [comment]
Fixed by #492.
