### ISSUE TITLE
All bundle libraries should have an examples folder

### ISSUE THREAD

**Issue by mrmcwethy** [adafruit/circuitpython#493]
Here is the list of libraries that still need an examples folder:

Pending PRs needing Review

Completed PRs

- [Adafruit_CircuitPython_Thermistor](https://github.com/adafruit/Adafruit_CircuitPython_Thermistor)
- [Adafruit_CircuitPython_SimpleIO](https://github.com/adafruit/Adafruit_CircuitPython_SimpleIO)
- [Adafruit_CircuitPython_NeoPixel](https://github.com/adafruit/Adafruit_CircuitPython_NeoPixel)
- [Adafruit_CircuitPython_RTTTL](https://github.com/adafruit/Adafruit_CircuitPython_RTTTL)
- [Adafruit_CircuitPython_SD](https://github.com/adafruit/Adafruit_CircuitPython_SD)
- [Adafruit_CircuitPython_BusDevice](https://github.com/adafruit/Adafruit_CircuitPython_BusDevice)
- [Adafruit_CircuitPython_HID](https://github.com/adafruit/Adafruit_CircuitPython_HID)
- [Adafruit_CircuitPython_DS18X20](https://github.com/adafruit/Adafruit_CircuitPython_DS18X20)
- [Adafruit_CircuitPython_Waveform](https://github.com/adafruit/Adafruit_CircuitPython_Waveform)
- [Adafruit_CircuitPython_Register](https://github.com/adafruit/Adafruit_CircuitPython_Register)
- [Adafruit_CircuitPython_MCP9808](https://github.com/adafruit/Adafruit_CircuitPython_MCP9808)
- [Adafruit_CircuitPython_IS31FL37](https://github.com/adafruit/Adafruit_CircuitPython_IS31FL3731)
- [Adafruit_CircuitPython_ADS1x15](https://github.com/adafruit/Adafruit_CircuitPython_ADS1x15)
- [Adafruit_CircuitPython_OneWire](https://github.com/adafruit/Adafruit_CircuitPython_OneWire)
- [Adafruit_CircuitPython_TSL2561](https://github.com/adafruit/Adafruit_CircuitPython_TSL2561)
- [Adafruit_CircuitPython_DS1307](https://github.com/adafruit/Adafruit_CircuitPython_DS1307)
- [Adafruit_CircuitPython_PCF8523](https://github.com/adafruit/Adafruit_CircuitPython_PCF8523)
- [Adafruit_CircuitPython_CircuitPlayground](https://github.com/adafruit/Adafruit_CircuitPython_CircuitPlayground)
- [Adafruit_CircuitPython_MAX31855](https://github.com/adafruit/Adafruit_CircuitPython_MAX31855)
- [Adafruit_CircuitPython_BNO055](https://github.com/adafruit/Adafruit_CircuitPython_BNO055)
- [Adafruit_CircuitPython_MAX7219](https://github.com/adafruit/Adafruit_CircuitPython_MAX7219)
- [Adafruit_CircuitPython_DotStar](https://github.com/adafruit/Adafruit_CircuitPython_DotStar)

**Comment by Sigafoos** [comment]
I'm not seeing examples for some of the repos that you have checked off: Adafruit_CircuitPython_SD for example.

**Comment by mrmcwethy** [comment]
@Sigafoos The checked ones are ones that I plan on adding examples to.  If you want to help with examples, pick one that is not check yet.

**Comment by Sigafoos** [comment]
@mrmcwethy got it!

**Comment by mrmcwethy** [comment]
@Sigafoos BTW: if you really like any of the ones I selected, please let me know, you can do em.

**Comment by Sigafoos** [comment]
I believe SimpleIO can be closed after adafruit/Adafruit_CircuitPython_SimpleIO@6667bb6

**Comment by mrmcwethy** [comment]
Ok, I moved SimpleIO to the Completed PR list.

**Comment by mrmcwethy** [comment]
https://github.com/adafruit/Adafruit_CircuitPython_MAX7219
https://github.com/adafruit/Adafruit_CircuitPython_BusDevice
https://github.com/adafruit/Adafruit_CircuitPython_HID

Ready for review.

**Comment by mrmcwethy** [comment]
@tannewt to get examples done for the current library, i had to lint it as well. These are examples that will need to be rewritten for you experimental version of IS31FL3731.  Let me know if you want me to finish that work.

**Comment by tannewt** [comment]
@mrmcwethy I'll merge it now.

I'm actually tempted to punt on the experimental version for a bit longer until we know how we want all of the displays to work.

**Comment by mrmcwethy** [comment]
We finally have examples folders for all the Adafruit Bundle Libraries.  Thanks everyone!

**Comment by ladyada** [comment]
AMAZING!!!! thanks x 1000 for your help @mrmcwethy

**Comment by tannewt** [comment]
🎉

**Comment by dhalbert** [comment]
@mrmcwethy thank you and thank everyone who else who contributed examples! The libraries are in great shape!
