### ISSUE TITLE
PulseOut crashes if pulse is too short

### ISSUE THREAD

**Issue by dmcomm** [adafruit/circuitpython#4937]
**Firmware**

```python
Adafruit CircuitPython 7.0.0-alpha.3-433-g5a4a80336 on 2021-06-25; Raspberry Pi Pico with rp2040
```

**Code/REPL**

```python
import array
import board
import time
import pulseio
import pwmio

pwm = pwmio.PWMOut(board.GP0, frequency=38000, duty_cycle=2**15)
pulseOut = pulseio.PulseOut(pwm)

pulses = array.array('H', [1000,1000,1000,2000,1,1000])

while(True):
    print(".")
    pulseOut.send(pulses)
    time.sleep(5)
```

**Behavior**

The PWM output is continuously on. The terminal doesn't respond to Control-C. The CIRCUITPY drive still works but the auto-reload does not occur.

**Other**

If you make it so that 0 is accepted but guaranteed to do nothing, that would also provide a workaround for #4923 .

**Comment by DavePutz** [comment]
This issue stems from the fact that PulseOut is using PWM at a given
frequency.
That means that values that are less than the width of the PWM pulse are
not going
to be handled correctly. At 38Khz, a pulse is about 26 microseconds; 13
high and 13 low.
So, trying to send a pulseout pulse of 1 microsecond is not going to work.
That said;
hanging in a non-responsive state is obviously not the correct way to
handle this.
Some thoughts on what could be done; an error could be returned to the
Python
script; the 'too small' request could be stretched to the minimum (in this
case about
13 microseconds); or we could jump through a bunch of hoops to turn off PWM,
send the requested short pulse manually, and turn PWM back on. @dmcomm; any
ideas
on what you think should happen?

**Comment by dmcomm** [comment]
```python
Adafruit CircuitPython 7.0.0-alpha.3-495-gcece6492a on 2021-07-03; Raspberry Pi Pico with rp2040
```

Currently, 5us hangs while 10us does not, whether the frequency is 38kHz or 500kHz. So the hang doesn't appear to be due to the number of PWM cycles requested.

10us at 38kHz sometimes produces a pulse and sometimes does not, which isn't really a problem.

If that needed to be fixed, I would choose "delay for the specified number of microseconds without outputting anything".

**Comment by dmcomm** [comment]
```python
Adafruit CircuitPython 7.0.0-alpha.3-495-gcece6492a on 2021-07-03; Raspberry Pi Pico with rp2040
```

```
import array
import board
import time
import pulseio
import pwmio

pwm = pwmio.PWMOut(board.GP0, frequency=500_000, duty_cycle=0x8000)
pulseOut = pulseio.PulseOut(pwm)

for i in range(20, 0, -1):
    time.sleep(2)
    print(i)
    pulses = array.array('H', [100,100,i,100])
    pulseOut.send(pulses)

```
Crashes somewhere between 8 and 5. The same if I change frequency to 38000. Also the same if I put the small number in the gap rather than the pulse.
