### ISSUE TITLE
Remove displayio.Group max_size parameter from libraries

### ISSUE THREAD

**Issue by lesamouraipourpre** [adafruit/circuitpython#4959]
Now that `max_size` has been disabled in `shared-bindings/displayio/Group.c` ready for removal in CircuitPython 7, it needs to be removed from all the libraries that make use of it before this can happen.
https://github.com/adafruit/circuitpython/blob/37c52110c5fdcc4b47567e85cba628470f658f84/shared-bindings/displayio/Group.c#L45
I propose to work through the libraries and make the necessary PRs. This Issue is intended as a central tracking point which will eventually allow the removal of the parameter from `shared-bindings`, hopefully before the release-candidate of CP7.

- [x] Adafruit_CircuitPython_CLUE - https://github.com/adafruit/Adafruit_CircuitPython_CLUE/pull/45
- [x] Adafruit_CircuitPython_CursorControl - https://github.com/adafruit/Adafruit_CircuitPython_CursorControl/pull/24
- [x] Adafruit_CircuitPython_Dash_Display - https://github.com/adafruit/Adafruit_CircuitPython_Dash_Display/pull/2
- [x] Adafruit_CircuitPython_Display_Button - https://github.com/adafruit/Adafruit_CircuitPython_Display_Button/pull/31
- [x] Adafruit_CircuitPython_Display_Shapes - https://github.com/adafruit/Adafruit_CircuitPython_Display_Shapes/pull/38
- [x] Adafruit_CircuitPython_Display_Text - https://github.com/adafruit/Adafruit_CircuitPython_Display_Text/pull/153
- [x] Adafruit_CircuitPython_DisplayIO_Layout - https://github.com/adafruit/Adafruit_CircuitPython_DisplayIO_Layout/pull/40
- [x] Adafruit_CircuitPython_DisplayIO_SH1106 - https://github.com/adafruit/Adafruit_CircuitPython_DisplayIO_SH1106/pull/4
- [x] Adafruit_CircuitPython_DisplayIO_SH1107 - https://github.com/adafruit/Adafruit_CircuitPython_DisplayIO_SH1107/pull/6
- [x] Adafruit_CircuitPython_DisplayIO_SSD1305 - https://github.com/adafruit/Adafruit_CircuitPython_DisplayIO_SSD1305/pull/12
- [x] Adafruit_CircuitPython_DisplayIO_SSD1306 - https://github.com/adafruit/Adafruit_CircuitPython_DisplayIO_SSD1306/pull/21
- [x] Adafruit_CircuitPython_FRAM - _Not displayio.Group_
- [x] Adafruit_CircuitPython_Gizmo - https://github.com/adafruit/Adafruit_CircuitPython_Gizmo/pull/19
- [x] Adafruit_CircuitPython_HX8357 - https://github.com/adafruit/Adafruit_CircuitPython_HX8357/pull/15
- [x] Adafruit_CircuitPython_ILI9341 - https://github.com/adafruit/Adafruit_CircuitPython_ILI9341/pull/27
- [x] Adafruit_CircuitPython_ImageLoad - https://github.com/adafruit/Adafruit_CircuitPython_ImageLoad/pull/54
- [x] Adafruit_CircuitPython_MONSTERM4SK - https://github.com/adafruit/Adafruit_CircuitPython_MONSTERM4SK/pull/8
- [x] Adafruit_CircuitPython_PortalBase - https://github.com/adafruit/Adafruit_CircuitPython_PortalBase/pull/42
- [x] Adafruit_CircuitPython_ProgressBar - https://github.com/adafruit/Adafruit_CircuitPython_ProgressBar/pull/32
- [x] Adafruit_CircuitPython_PyBadger - https://github.com/adafruit/Adafruit_CircuitPython_PyBadger/pull/45
- [x] Adafruit_CircuitPython_PYOA - https://github.com/adafruit/Adafruit_CircuitPython_PYOA/pull/23
- [x] Adafruit_CircuitPython_SSD1325 - https://github.com/adafruit/Adafruit_CircuitPython_SSD1325/pull/11
- [x] Adafruit_CircuitPython_SSD1327 - https://github.com/adafruit/Adafruit_CircuitPython_SSD1327/pull/10
- [x] Adafruit_CircuitPython_SSD1331 - https://github.com/adafruit/Adafruit_CircuitPython_SSD1331/pull/14
- [x] Adafruit_CircuitPython_SSD1351 - https://github.com/adafruit/Adafruit_CircuitPython_SSD1351/pull/16
- [x] Adafruit_CircuitPython_ST7735 - https://github.com/adafruit/Adafruit_CircuitPython_ST7735/pull/15
- [x] Adafruit_CircuitPython_ST7735R - https://github.com/adafruit/Adafruit_CircuitPython_ST7735R/pull/25
- [x] Adafruit_CircuitPython_ST7789 - https://github.com/adafruit/Adafruit_CircuitPython_ST7789/pull/23
- [x] Adafruit_CircuitPython_turtle - https://github.com/adafruit/Adafruit_CircuitPython_turtle/pull/24
- [x] Check Community Bundle
- [x] Community/drivers/gc9a01 - https://github.com/tylercrumpton/CircuitPython_GC9A01/pull/2
- [ ] Community/drivers/ili9163 - https://github.com/electronut/Electronutlabs_CircuitPython_ILI9163/pull/2
- [x] Community/helpers/arrowline - https://github.com/jposada202020/CircuitPython_ArrowLine/releases/tag/0.8.1
- [x] Community/helpers/candlesticks - https://github.com/jposada202020/CircuitPython_Candlesticks/releases/tag/0.6.1
- [x] Community/helpers/circuitpython_display_frame - https://github.com/FoamyGuy/CircuitPython_Display_Frame/pull/1
- [x] Community/helpers/styles - https://github.com/jposada202020/CircuitPython_styles/releases/tag/0.5.1
- [x] Check CircuitPythonOrg Bundle
- [x] CPO/DisplayIO_Annotation - https://github.com/circuitpython/CircuitPython_Org_DisplayIO_Annotation/pull/4
- [x] CPO/DisplayIO_Cartesian - https://github.com/circuitpython/CircuitPython_Org_DisplayIO_Cartesian/pull/4
- [x] CPO/DisplayIO_FlipInput - https://github.com/circuitpython/CircuitPython_DisplayIO_FlipInput/pull/3
- [x] CPO/DisplayIO_SwitchRound - https://github.com/circuitpython/CircuitPython_Org_DisplayIO_SwitchRound/pull/6

Below is the output of `grep -r max_size * | grep -v adafruit_fram | sort` against `Adafruit_CircuitPython_Bundle/libraries` at `Fri 16 Jul 17:03:22 BST 2021`
```
drivers/displayio_sh1106/examples/displayio_sh1106_simpletest.py:splash = displayio.Group(max_size=10)
drivers/displayio_sh1106/README.rst:    splash = displayio.Group(max_size=10)
drivers/monsterm4sk/examples/monsterm4sk_pumpkin_shifting_eyes.py:left_group = displayio.Group(max_size=4)
drivers/monsterm4sk/examples/monsterm4sk_pumpkin_shifting_eyes.py:right_group = displayio.Group(max_size=4)
drivers/monsterm4sk/examples/monsterm4sk_rainbow_stars.py:left_group = displayio.Group(max_size=4, scale=3)
drivers/monsterm4sk/examples/monsterm4sk_rainbow_stars.py:right_group = displayio.Group(max_size=4, scale=3)
drivers/monsterm4sk/examples/monsterm4sk_simpletest.py:left_group = displayio.Group(max_size=4)
drivers/monsterm4sk/examples/monsterm4sk_simpletest.py:right_group = displayio.Group(max_size=4)
drivers/monsterm4sk/README.rst:    left_group = displayio.Group(max_size=4)
drivers/monsterm4sk/README.rst:    right_group = displayio.Group(max_size=4)
drivers/ssd1325/examples/ssd1325_simpletest.py:    max_size=10,
drivers/ssd1325/examples/ssd1325_simpletest.py:splash = displayio.Group(max_size=10)
drivers/st7735r/examples/st7735r_128x160_colored_labels.py:splash = displayio.Group(max_size=10)
drivers/st7735r/examples/st7735r_128x160_colored_labels.py:text_group_left = displayio.Group(max_size=10, scale=1, x=0, y=6)
drivers/st7735r/examples/st7735r_128x160_colored_labels.py:text_group_right = displayio.Group(max_size=10, scale=1, x=80, y=6)
drivers/st7735r/examples/st7735r_128x160_simpletest.py:splash = displayio.Group(max_size=10)
drivers/st7735r/examples/st7735r_128x160_simpletest.py:text_group = displayio.Group(max_size=10, scale=2, x=11, y=64)
drivers/st7735r/examples/st7735r_minitft_featherwing_simpletest.py:splash = displayio.Group(max_size=10)
drivers/st7735r/examples/st7735r_minitft_featherwing_simpletest.py:text_group = displayio.Group(max_size=10, scale=2, x=11, y=40)
drivers/st7735r/examples/st7735r_minitft_simpletest.py:splash = displayio.Group(max_size=10)
drivers/st7735r/examples/st7735r_minitft_simpletest.py:text_group = displayio.Group(max_size=10, scale=2, x=11, y=40)
drivers/st7735r/examples/st7735r_simpletest.py:splash = displayio.Group(max_size=10)
drivers/st7735r/README.rst:    splash = displayio.Group(max_size=10)
```

**Comment by FoamyGuy** [comment]
Thanks for putting this together. We'll need to run a similar pass through the learn guide repo to change instances of this as well.

**Comment by jposada202020** [comment]
@lesamouraipourpre I give all the thanks here for all these PRs. This is hard work!!!

**Comment by jposada202020** [comment]
Arrowline Done --> https://github.com/jposada202020/CircuitPython_ArrowLine/releases/tag/0.8.1
Candlesticks Done --> https://github.com/jposada202020/CircuitPython_Candlesticks/releases/tag/0.6.1
Styles Done --> https://github.com/jposada202020/CircuitPython_styles/releases/tag/0.5.1
