### ISSUE TITLE
Status LED blinks blue on startup on MacroPad

### ISSUE THREAD

**Issue by kattni** [adafruit/circuitpython#4969]
### CircuitPython version

```python
Adafruit CircuitPython 7.0.0-alpha.3-497-g23baa02c1 on 2021-07-06; Adafruit Macropad RP2040 with rp2040
```

### Code/REPL

```python
Issue occurs on startup.
```

### Behavior

After updating to the latest build of CircuitPython, the status LED blinks blue after the yellow safe mode blinking on the MacroPad. I was informed that the blue flashing is related to Bluetooth pairing, however the MacroPad has no Bluetooth capabilities. I did not test it on other non-Bluetooth boards.

**Comment by tannewt** [comment]
This might be due to us having BLE HCI support enabled.
