### ISSUE TITLE
Rename _pixelbuf and adafruit_pypixelbuf to match - as adafruit_pixelbuf

### ISSUE THREAD

**Issue by kattni** [adafruit/circuitpython#4992]
This came out of  #4926 - the scope of which was refined to an initial step which is nearly completed by #4991.

This issue is to address the part of the previous issue not yet dealt with - renaming `_pixelbuf` and `adafruit_pypixelbuf` to `adafruit_pixelbuf` so they match for seamless usage. This will simplify the usage in NeoPixel and DotStar, and any future applications.

The current suggestion is to create a new Python library called `adafruit_pixelbuf` and copy `adafruit_pypixelbuf` into it (without the `colorwheel()` code as that is now native to CircuitPython in `rainbowio`). Then we rename `_pixelbuf` to `adafruit_pixelbuf` to match. Simultaneously, we need to update NeoPixel and DotStar to use `adafruit_pixelbuf`. We also need to ensure that everything is working properly in Blinka.

A discussion about how to do this without breaking current usage must be had before moving forward. I will be discussing this with @dhalbert. I believe as long as we leave backwards-compatible code in NeoPixel and DotStar until 7.0 stable is released, it should be seamless.

**Comment by tannewt** [comment]
I think we'll want to make a second top-level module entry that maps _pixelbuf to `adafruit_pixelbuf` and rename the files internally. Then in 8.0.0 we can remove the _pixelbuf naming in favor of adafruit_pixelbuf.
