### ISSUE TITLE
Auto-Reload not releasing APA102_MOSI on Trinket_M0

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#4997]
### CircuitPython version

```python
Adafruit CircuitPython 7.0.0-alpha.4-49-g9fdecacec on 2021-07-13; Adafruit Trinket M0 with samd21e18
```

### Code/REPL

```python
code.py:

import adafruit_dotstar
import board

pixel = adafruit_dotstar.DotStar(board.DOTSTAR_CLOCK, board.DOTSTAR_DATA, 1)

while True:
    pixel.fill((255, 255, 0))
```

### Behavior

Runs normally and continues to run normally after a  Control-D soft reboot

but if I write soemthing to the CIRCUITPY drive whil it it running, it does an "auto-reload" and fails
on Linux I did `touch /media/jerryneedell/CIRCUITPY/junk` while it was running

caused:
```
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Traceback (most recent call last):
  File "code.py", line 4, in <module>
  File "adafruit_dotstar.py", line 112, in __init__
ValueError: APA102_MOSI in use

Code done running.
```

**Comment by tannewt** [comment]
This might be due to the board specific pin mask that prevents reset. (I forget what its called.) We should probably remove it completely in favor of never reset.
