### ISSUE TITLE
stm32f411_blackpill_with_flash appears to reserve flash for nvm but does not implement the module

### ISSUE THREAD

**Issue by evildave666** [adafruit/circuitpython#5045]
The WeAct blackpill_with_flash board (unlike the non-haxpress version) seems to reserve 16k of flash for nvm usage. It uses the ports/stm/boards/STM32F411_nvm_nofs.ld linker script, but does not seem to actually implement the nvm module in the build. It would be a good idea to reclaim this space for future use given a) the port already omits some built-in modules, the claimed reason being space, and b) a tinyuf2 port is in progress for this board and will need to be shoehorned in somewhere.

I have made a successful local build with this space merged into FLASH_FIRMWARE with all of the omitted modules reincluded and it now fits with 8k of space to spare.

**Comment by tannewt** [comment]
@evildave666 I'm ok with using that 16k for something else. Does this make sense @hierophect ?

**Comment by evildave666** [comment]
This was resolved with PR 5061.
