### ISSUE TITLE
PWM-generated tones may be off-frequency at higher frequencies

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#5092]
### CircuitPython version

```python
recent 7.0.0 versions
```

### Code/REPL

```python
# strange how the sound jumps around at around 1800 and on up
# Tested with CircuitPython 7, not with 6
from time import sleep
from adafruit_macropad import MacroPad
macropad = MacroPad()
for freq in range(200,10000, 50):
    print(f"freq: {freq}")
    macropad.start_tone(freq)
    sleep(.45)
    macropad.stop_tone()
    sleep(.05)
```

### Behavior

he tone jumps randomly at 1850 and up.

### Additional information

Original report here: https://forums.adafruit.com/viewtopic.php?f=59&t=181842

Check PWM frequency calculation and setting.

**Comment by RufusVS** [comment]
Through additional testing I found out that frequencies as low as 666 and 670 drop out, though adjacent frequencies play, if this helps.

**Comment by jepler** [comment]
```
    uint32_t best_numerator = 0;
    uint32_t best_denominator = 0;
    uint32_t best_error = system_clock;
        
    for (uint32_t denominator = 0xffff; denominator > 0; denominator--) {
        uint32_t numerator = (denominator * sample_rate) / system_clock;
        uint32_t remainder = (denominator * sample_rate) % system_clock;
```

For sample rates above around 65536, the math overflows at `(denominator * sample_rate)`

**Comment by jepler** [comment]
Because the macropad sine wave contains 100 samples, problems would start at around 65536/100 Hz

**Comment by dhalbert** [comment]
I have been looking at the `PWMOut` frequency setting, which is pretty grainy at lower frequencies.

**Comment by jepler** [comment]
It looks like the DMA will happily update the PWM _register_ faster than the PWM's carrier frequency, but you're right that at higher sample rates maybe not all the samples would actually make it out via PWM
