### ISSUE TITLE
Implement I2C clock stretching in bitbangio

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#511]
Some I2C sensors require clock stretching and do not work properly when using bitbangio (necessary on the esp8266).  Examples are CCS811 https://github.com/adafruit/Adafruit_CircuitPython_CCS811/issues/9  and bno055.

**Comment by deshipu** [comment]
This is strange, because I remember that I implemented clock stretching for MicroPython for the software I2C... Could it be that CircuitPython didn't use that?

Looking at the code, it's there: https://github.com/adafruit/circuitpython/blob/master/shared-module/bitbangio/I2C.c#L53

Do you have a logic analyzer to capture what is happening with that sensor?

**Comment by jerryneedell** [comment]
I do have some logic analyzer captures - GitHub won't accept the file types. I can get them to you in discord.

**Comment by jerryneedell** [comment]
I'll have to regenerate them, but it won't be today -  the ones I have are too large because I captures some analog data as well. I'll try to repeat the tests tomorrow and post the files.  Sorry for the confusion.

**Comment by jerryneedell** [comment]
here is a screenshot of the Logic analyzer capture - perhaps it will tell you enough
![screenshot](https://user-images.githubusercontent.com/15856834/34588172-991a7a96-f179-11e7-9cfc-06a20d3f2f0e.png)

**Comment by jerryneedell** [comment]
this is the start of the capture 
![screenshot2](https://user-images.githubusercontent.com/15856834/34588220-d1784026-f179-11e7-9661-ea283366471c.png)

**Comment by jerryneedell** [comment]
I lowered the I2C frequency to 10000 and it works better, but still occasionally fails withe either an OSError 5 as above or sometimes a RunTime error 2. I don’t have a logic analyzer capture of it at 10000. Would you like to see one?

**Comment by deshipu** [comment]
What value of pull-up resistors are you using? Do you have analog pins on your logic analyzer, or an oscilloscope, so that you can actually see the shape of the signal? How long are the wires?

**Comment by jerryneedell** [comment]
The breakout board has 10k pulllups. I’ll try to get some scopeshots to post this morning. I was having some trouble getting good shots yesterday. I also have another sensor, mcp9808 also with 10k pull-ups connected. Wires are about 15 cm. to ccs811.

**Comment by jerryneedell** [comment]
ccs811 - 10Khz clock
![ds1z_quickprint32](https://user-images.githubusercontent.com/15856834/34610709-4337e98e-f1f0-11e7-8487-9f5d5cb063ff.png)

ccs811 - default clock
![ds1z_quickprint33](https://user-images.githubusercontent.com/15856834/34610710-435871ea-f1f0-11e7-9145-472926541b9e.png)
ccs811 - default clock
![ds1z_quickprint35](https://user-images.githubusercontent.com/15856834/34610711-4377d1e8-f1f0-11e7-8c7d-61ef2554c6ad.png)

**Comment by deshipu** [comment]
Those signals look reasonable, I don't think this is the problem.

**Comment by jerryneedell** [comment]
I have tried several approaches- here is a summary:
slow clock rate to 10Hkz -- works "better" runs for 10s of seconds or minutes then fails

increase Clock stretching limit to 512 - works a bit better -sometimes works at default clock rate - still fails eventually even at 10Khz

noted that 3V line was sagging (sometimes below 3V) when ccs811 running. powered with 5Vin and level shifters on SCL/SDA
still tight increased clock stretch timeout  it works "better" It now runs at both default clock rate and 10Khz, but still crashes after 10s of seconds to minutes.  3.3v line is better but still sags to < 3.1 V.

running out of ideas.

**Comment by jerryneedell** [comment]
After much discussion with @deshipu and many tests on esp8266 and feather m0 (bit banging) there does not appear to be any problem with i2c clock stretching. At least the issues with the ccs811 do not appear to be related to clock stretching so it is time to close this issue.
