### ISSUE TITLE
board.LED not defined for Grand Central M4 Express

### ISSUE THREAD

**Issue by NathanY3G** [adafruit/circuitpython#5111]
### CircuitPython version

```python
Adafruit CircuitPython 7.0.0-alpha.5-140-g9a6b11806 on 2021-08-08; Adafruit Grand Central M4 Express with samd51p20
```

### Code/REPL

```python
import board
from digitalio import DigitalInOut, Direction
led = DigitalInOut(board.LED)
```

### Behavior

The following error is displayed:

```
AttributeError: 'module' object has no attribute 'LED'
```

### Description

Although this is a minor issue, for code portability it would be nice not to have to use conditional logic or to change the original source code.

**Comment by anecdata** [comment]
The Learn Guide (https://learn.adafruit.com/adafruit-grand-central/pinouts) points out that the silk for the user LED for `D13` is `L`, but there is not a `board.L` either that I can see (https://github.com/adafruit/circuitpython/blob/main/ports/atmel-samd/boards/grandcentral_m4_express/pins.c).

**Comment by NathanY3G** [comment]
Thanks for the information @anecdata and file reference. Since it looks like it should be a one-liner I will take the liberty of creating a MR myself.

**Comment by FoamyGuy** [comment]
It looks to me like the Metro M0 and Metro M4 devices are in the same boat as this without `LED` or `L`

I'm going to take a shot at adding it to those devices.

**Comment by NathanY3G** [comment]
I have just seen your reply @FoamyGuy! Thank you both for such quick replies :-)

I have already created a MR for the GCM4: https://github.com/adafruit/circuitpython/pull/5112 if anybody has time to take a look.

**Comment by FoamyGuy** [comment]
actually, I'm not sure how I missed it in both, but the Metro M0 and M4 do already have them. 

Anyhow, thanks for adding that to the Grand Central build.
