### ISSUE TITLE
SSD1680 Epaper - buffer wraps when width is higher than 255 pixels

### ISSUE THREAD

**Issue by saeugetier** [adafruit/circuitpython#5119]
### CircuitPython version

```python
Adafruit CircuitPython 6.3.0 on 2021-06-01; Raspberry Pi Pico with rp2040
```

### Code/REPL

```python
DISPLAY_WIDTH = 296
DISPLAY_HEIGHT = 128

display = adafruit_ssd1680.SSD1680(display_bus, width=DISPLAY_WIDTH,
                                 height=DISPLAY_HEIGHT,
                                 rotation=90, busy_pin=epd_busy,
                                 highlight_color=0x000000)
```

### Behavior

The display buffer is not displayed correctly. The width is higher than can be addressed with 1 byte. The right part of the display buffer is displayed on the left side overlapping the previous drawn buffer.

### Description

Content is not displayed correctly.

### Additional information

- Problem was found with a Waveshare 2,9 inch  e-Paper Module using a SSD1680 chipset.

**Comment by saeugetier** [comment]
This is how the drawn display buffer looks:

![Image](https://user-images.githubusercontent.com/1408260/128884393-d9160ab4-6e03-49c0-b52c-e0daa80e134b.jpg)

**Comment by tannewt** [comment]
The bug may be in this file but I'm not sure where: https://github.com/adafruit/circuitpython/blob/main/shared-module/displayio/EPaperDisplay.c

**Comment by saeugetier** [comment]
[EPaper.zip](https://github.com/adafruit/circuitpython/files/6969035/EPaper.zip)

I have recorded the communication between the Raspi Pico and the EPaper. I saw that the chip select is high between the first and second byte after the command. The chip select is not high after the command has been sent. Maybe the chip select ends the communication and the initialization is done with wrong parameters.

![Pulseview](https://user-images.githubusercontent.com/1408260/129086038-59b82396-202e-47ef-aca2-c69d6b67a19c.png)

**Comment by saeugetier** [comment]
I found the bug: 
The command "set_row_window_command" has a wrong byte order: The content is command: 0x45, data: 0x00, 0x00, 0x01, 0x27. But correct is: command: 0x45, data: 0x00, 0x00, 0x27, 0x01.

The byte order has to be flipped here:
https://github.com/adafruit/circuitpython/blob/main/shared-module/displayio/display_core.c#L300-L303

**Comment by tannewt** [comment]
Ok, looks like we'll need a setting for MSB vs LSB. I assume it's working as-is for LCDs so this eink must do the opposite.

Want to make a PR for it? That display isn't used by Adafruit currently so it won't be a priority for Adafruit funded folks.

**Comment by lesamouraipourpre** [comment]
Maybe related, there is an issue on Blinka relating to missing `MSB` using SPI with MicroPython.
https://github.com/adafruit/Adafruit_Blinka/issues/480

**Comment by saeugetier** [comment]
@tannewt I can prepare a pull request. But I need somebody for testing the Adafruit EPD, if they still work.

**Comment by tannewt** [comment]
We can ask some folks to test from the PR. We'll want to test some TFT as well since that code is used for all displays.
