### ISSUE TITLE
tools/codeformat.py could handle problems better (uncrustify errors)

### ISSUE THREAD

**Issue by microDev1** [adafruit/circuitpython#5126]
With `uncrustify=0.69` (default with `Ubuntu 20.04`):

- when `python3 tools/codeformat.py -cv` is run, a bunch of errors can be seen
- when uncrustify is run with pre-commit, the errors go undetected and the formatting hook passes. 

My theory is that pre-commit expects the hook to return a certain error code on failure but `codeformat.py` isn't doing that.

**Comment by jepler** [comment]
Keep in mind that uncrustify 0.69 is not supported. Adding a check that causes pre-commit to fail if that is the installed version would be welcome.

**Comment by jepler** [comment]
As far as I know, this problem does not affect 0.71.

**Comment by jepler** [comment]
We discussed this further on Discord, and think it would be a good idea to change codeformat to
 * add a specific version check
 * make a subprocess exiting with nonzero status cause codeformat to exit with nonzero status. Using `subprocess.check_call` is OK for this, even though it means it would stop processing files after the first error exit status.
