### ISSUE TITLE
FileTransferProtocol: problems with non-ascii filenames

### ISSUE THREAD

**Issue by antonio-openroad** [adafruit/circuitpython#5146]
**CircuitPython version**

Adafruit CircuitPython 7.0.0-alpha.5 on Circuit Playground Bluefruit

**Behavior**
These problems are related to the Bluetooth FileTransferProtocol

Filenames with accents can be created but cannot be removed. 
For example if you create a folder named "Carpeta sin título" ("untitled folder" in Spanish) it is not possible to remove it later

Filenames with emojis cause bigger problems. 
Creating a folder using the  with an emoji name will make the listDirectory command return incorrect data that does not follow the protocol.
If an existing folder created via USB contains emojis the listDirectory command returns correct data, but the name reported is wrong.

**Comment by tannewt** [comment]
https://github.com/adafruit/Glider-for-iOS/pull/10 is needed on the Glider side.

Fix for FATFS incoming.
