### ISSUE TITLE
esp32s2: implement sdioio

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#5179]
Can we use https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/api-reference/storage/sdmmc.html ?

**Comment by microDev1** [comment]
This can't be done on the `esp32s2`. The support is for `esp32` and `esp32s3`.

Check for `SOC_SDMMC_HOST_SUPPORTED` in `esp-idf/components/soc/esp32XX/include/soc/soc_caps.h`.

**Comment by jepler** [comment]
Ah, I've learned to check if the URL says esp32s2 but apparently that's not enough to distinguish whether the functionality is actually available.
