### ISSUE TITLE
USB VID/PID Request for Warmbit BluePixel

### ISSUE THREAD

**Issue by warmbit** [adafruit/circuitpython#5215]
Hi,

I'm currently working on a nRF52840 board as LED controller. The prototype has been assembled. I'd like to have it work with both Circuit Python and Arduino. Would it be possible to receive a VID/PID for this purpose? 

Thank you very much!

**Comment by tannewt** [comment]
Adafruit is no longer granting PIDs to folks outside of Adafruit. You can request a PID from https://pid.codes for open source hardware (they have testing pids too) or most chip manufacturers sublicense PIDs. I think [Nordic is ok](https://devzone.nordicsemi.com/f/nordic-q-a/50638/usb-pid-for-nrf52840) if you use a random PID with their VID.
