### ISSUE TITLE
Add __name__ to all `board` modules

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#5248]
@capellini  noticed that (most?) boards don't have `__name__` in the board module: https://github.com/adafruit/circuitpython/issues/5183#issuecomment-906807750

It would be good to see this added, just for consistency's sake.

**Comment by PracticalMetal** [comment]
Hi, I would like to work on this. Can you suggest me ways to get started?

**Comment by dhalbert** [comment]
Take a look at #5222, which added `board.board_id`. The author wrote a script to automate the changes.
