### ISSUE TITLE
Circuit Python with Sublime Text

### ISSUE THREAD

**Issue by Camerutttt** [adafruit/circuitpython#525]
Anyone knows how to use Sublime Text with Circuit Python? I have already installed Deviot but do not know how to continue from there.

**Comment by tannewt** [comment]
Please ask on the support forum: https://forums.adafruit.com/viewforum.php?f=60

GitHub issues should be used for bugs and feature requests.

**Comment by tandpfun** [comment]
Camerutttt, It is possible, just write your python code, and when you save it, call it 'main.py' or whatever filename you like.

**Comment by tandpfun** [comment]
sorry, scott. :)
<i class="fa fa-check-square" aria-hidden="true"></i>
