### ISSUE TITLE
nRF52840 BLEUART doesn't receive messages - ble_bluefruit_color_picker doesn't work 

### ISSUE THREAD

**Issue by jpconstantineau** [adafruit/circuitpython#5252]
### CircuitPython version

```python
Adafruit CircuitPython 7.0.0-beta.0 on 2021-08-24; Adafruit Feather nRF52840 Express with nRF52840
library bundle: adafruit-circuitpython-bundle-7.x-mpy-20210827
```

### Code/REPL

```python
# SPDX-FileCopyrightText: 2020 ladyada for Adafruit Industries
# SPDX-License-Identifier: MIT

# CircuitPython NeoPixel Color Picker Example

import board
import neopixel

from adafruit_bluefruit_connect.packet import Packet
from adafruit_bluefruit_connect.color_packet import ColorPacket

from adafruit_ble import BLERadio
from adafruit_ble.advertising.standard import ProvideServicesAdvertisement
from adafruit_ble.services.nordic import UARTService

ble = BLERadio()
uart_service = UARTService()
advertisement = ProvideServicesAdvertisement(uart_service)

pixels = neopixel.NeoPixel(board.NEOPIXEL, 10, brightness=0.1)

while True:
    # Advertise when not connected.
    ble.start_advertising(advertisement)
    while not ble.connected:
        pass
    ble.stop_advertising()

    while ble.connected:
        if uart_service.in_waiting:
            packet = Packet.from_stream(uart_service)
            if isinstance(packet, ColorPacket):
                print(packet.color)
                pixels.fill(packet.color)
```

### Behavior

- When code runs, no error messages occur...
- When I connect with the app, (Bluefruit LE Connect v3.3.2), it connects successfully (both app and REPL are fine).
- I then go into the "Controller", select "Color Picker"
- I pick a color, then "select"
- I would expect the neopixel to light-up and display the color chosen. However, nothing happens.
- REPL didn't show anything as well.

### Description

I added a couple of print statements. I was able to see that it was connected (print in while ble.connected: )
however, I never saw anything being received by the uart_service (in the if uart_service.in_waiting:)

### Additional information

code from [nrf52840 feather guide](https://learn.adafruit.com/circuitpython-nrf52840/neopixel-color)

**Comment by mrdalgaard** [comment]
I noticed that setting BLE up in REPL, and then connecting the app to it will allow you du send text to the REPL console from the client, but not in the other direction. So it seems to be working one way.

**Comment by ladyada** [comment]
@tannewt i think this is the NUS thing?

**Comment by tannewt** [comment]
Yup, the plan is to switch the UUIDs used for the CP serial connection.
