### ISSUE TITLE
Make IO9 available on lilygo_ttgo_t8_s2_st7789

### ISSUE THREAD

**Issue by deBaer** [adafruit/circuitpython#5277]
Hi, sadly, the board module on this board doesn't know IO9. It's the ADC the battery is connected to for measuring the battery voltage.

**Comment by anecdata** [comment]
Want to try a Pull Request? The change is in this file:
https://github.com/adafruit/circuitpython/blob/main/ports/esp32s2/boards/lilygo_ttgo_t8_s2_st7789/pins.c

Until it's fixed, you can access this pin with `microcontroller.pin.GPIO9`
