### ISSUE TITLE
Deal with multiple boards showing same drive name on Mac OSX (and maybe other OS's)

### ISSUE THREAD

**Issue by tdicola** [adafruit/circuitpython#530]
I noticed while doing some radio library development that I needed to have two CircuitPython boards (M0-based) connected to my Mac at once (one for transmitting, the other for receiving).  This presented an interesting problem as both boards show up in Finder with the exact same drive name (CIRCUITPY):
<img width="228" alt="screen shot 2018-01-16 at 11 53 23 am" src="https://user-images.githubusercontent.com/1332183/35009276-ed31a99a-fab3-11e7-86f9-99f2676b378f.png">
If you use the command line you can see a small difference in the /Volumes directory with the name (one is given /Volumes/CIRCUITPY/ and another /Volumes/CIRCUITPY 1/):
<img width="710" alt="screen shot 2018-01-16 at 11 54 53 am" src="https://user-images.githubusercontent.com/1332183/35009333-16cbd9f6-fab4-11e7-8973-045bb5b7df82.png">
In both cases though it's really hard to figure out which board to copy a file to as they both appear the same.  A quick workaround is to add a dummy text file to the board so you can see it in finder and realize the difference.  However I think we should consider some way to disambiguate the board names.  This would greatly help scenarios like a classroom where a teacher might have multiple boards connected to set them up, etc.  Or just normal users with two boards connected to their computer.

Some thoughts mentioned in discussion:
- Generate the filesystem label/name with a hash or few bits from the board's unique ID at the end.  So CIRCUITPY could be CIRCUITPY_1AF etc.
- Allow users to change the name of the filesystem label programmatically, like in boot.py.  This is actually kind of interesting because it would allow very clear board-specific names.  Like a temperature sensor node could be named TEMP1, TEMP2, and be very easy to spot when connected to a computer.

**Comment by tannewt** [comment]
@jepler I agree with you that the user could do it as needed. A lot of our guides reference CIRCUITPY and it'd be good to be exact by default.

How about we add something to `storage` that can change it during `boot.py`? That way the process is OS agnostic but still done by the user.

**Comment by jepler** [comment]
@tannewt interesting idea, I will try to take a look at doing that this weekend.  I am not familiar with the storage module yet, but maybe the API should look something like: `storage.setlabel(filesystem, "newlabel")` ?  I'm not actually seeing in the docs what sort of values you might pass for `filesystem` though, hm.

**Comment by tannewt** [comment]
IIRC `remount` uses the mountpoint. So `"/"` or `"/sd"`.

**Comment by jepler** [comment]
@tannewt with #712 merged, can we close this up?  or is there more to do (tutorial documentation to be written?)

**Comment by tannewt** [comment]
Closing sounds good! I'll try and remember to highlight its addition in the next set of release notes. Thanks!
