### ISSUE TITLE
ATSAMD build error (audio_dma.c)

### ISSUE THREAD

**Issue by water5** [adafruit/circuitpython#5309]
### CircuitPython version

```python
Adafruit CircuitPython github (2021-09-08), with ItsyBitsy M4 Express / Mini SAM M4.
```

### Code/REPL

```python
make BOARD=itsybitsy_m4_express
or
make BOARD=mini_sam_m4
```

### Behavior

audio_dma.c: In function 'audio_evsys_handler':
audio_dma.c:420:31: error: implicit declaration of function 'dma_write_back_descriptor' [-Werror=implicit-function-declaration]
  420 |             (DmacDescriptor *)dma_write_back_descriptor(dma->dma_channel)->DESCADDR.reg;
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~
audio_dma.c:420:31: error: nested extern declaration of 'dma_write_back_descriptor' [-Werror=nested-externs]
audio_dma.c:420:74: error: invalid type argument of '->' (have 'int')
  420 |             (DmacDescriptor *)dma_write_back_descriptor(dma->dma_channel)->DESCADDR.reg;
      |                                                                          ^~
cc1: all warnings being treated as errors
make: *** [../../py/mkrules.mk:74: build-itsybitsy_m4_express/audio_dma.o] Error 1

**Comment by dhalbert** [comment]
The `samd-peripherals` submodule has been updated. You'll need to get the new version:
```
git submodule sync --quiet --recursive && git submodule update --init
```

Also note that the `esp-idf` submodule has been updated, and is now in a different repo.
