### ISSUE TITLE
SSD1309 Display Library

### ISSUE THREAD

**Issue by Capekk** [adafruit/circuitpython#5346]
Hello, I was looking for a way to program SSD1309 display in circuitpython but there is no library for it. I just wanted to know if the library can or can't be made. Or is there any other way to program SSD1309 using circuitpython?

**Comment by tannewt** [comment]
It should be doable. I'd start with this driver: https://github.com/adafruit/Adafruit_CircuitPython_DisplayIO_SSD1306

What display(s) are you using?

**Comment by Capekk** [comment]
It's 2.42 inch 128x64 OLED LCD Display Module SSD1309 12864 7 Pin SPI/IIC I2C

**Comment by deshipu** [comment]
Try and see if the ssd1306 driver works, it should be similar enough.

**Comment by Capekk** [comment]
Ye I'm gonna try it, but I haven't received it yet. I was just asking if it's even possible. Thanks for the help guys.

**Comment by dhalbert** [comment]
@Capekk This is an ancient issue, but did you get the SSD1309 to work with the SSD1306 driver?

**Comment by Capekk** [comment]
> issue

Hello @dhalbert, 
I did! In the end I used adafruit_ssd1306 and adafruit_framebuf libraries for my project. The setup was set like this: 
oled = adafruit_ssd1306.SSD1306_I2C(128, 64, i2c)
It worked without issues. I don't think that the latter library is even necessary, since I've only used it for the graphics... Hope it helps.

**Comment by dhalbert** [comment]
Great! Glad to hear that it worked!
