### ISSUE TITLE
microcontroller.on_next_reset() behavior discrepancy on nrf

### ISSUE THREAD

**Issue by rdoursenaud** [adafruit/circuitpython#5353]
### CircuitPython version

```python
Adafruit CircuitPython 7.0.0-rc.2-dirty on 2021-09-15; Adafruit Feather nRF52840 Express with nRF52840
```

### Code/REPL

```python
import microcontroller
microcontroller.on_next_reset(microcontroller.RunMode.BOOTLOADER)
```

### Behavior

The board resets immediately into bootloader mode without waiting for a `microcontroller.reset()` as the method name and [documentation](https://learn.adafruit.com/circuitpython-essentials/circuitpython-resetting#reset-into-specific-mode-3087084-14) implies.

### Description

Running the very same code on `Adafruit CircuitPython 7.0.0-rc.2-dirty on 2021-09-15; Adafruit Matrix Portal M4 with samd51j19` yields the expected result of waiting for `microcontroller.reset()` or a reset button press to jump into bootloader mode.

**Comment by dhalbert** [comment]
Fixed by #7468.
