### ISSUE TITLE
CPX: board.MOSI, .MISO, and .SCK should refer to external pins, not SPI flash

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#536]
The `board.MOSI`, `board.MISO`, and `board.SCK` pins on Circuit Playground Express refer to the SPI flash pins. That isn't too useful; it would probably be better to designate some externally available pins for SPI use. By experimentation, these work (and maybe more would):
```python
# order is SCK, MOSI, MISO
busio.SPI(board.A3, board.A2, board.A1)
busio.SPI(board.A1, board.A3, board.A2)
```
A1, A2, and A3 are the only set of three externally available pins on the same SERCOM.

**Comment by kattni** [comment]
As noted in the PR, learn guide will need to be updated to reflect this change when 3.0 is released. Issue fixed with https://github.com/adafruit/circuitpython/pull/540.
