### ISSUE TITLE
Display.fill_row documentation doesn't match code

### ISSUE THREAD

**Issue by lesamouraipourpre** [adafruit/circuitpython#5362]
### CircuitPython version

```python
Adafruit CircuitPython 7.0.0-rc.1-65-gcddbfffb3-dirty on 2021-09-13; Adafruit PyPortal with samd51j20
```

### Code/REPL

```python
import board
import displayio
import array

display = board.DISPLAY
width = display.width
height = display.height
scale = 20
g = displayio.Group(scale=scale)
display.show(g)

bufsize = 2 * (width if display.rotation in (0,180) else height)
for y in range(0, height, scale):
    
    # buffer = bytearray(bufsize)
    buffer = array.array('B', [0]*bufsize)  # Let's make it crash

    outbuffer=display.fill_row(y,buffer)
```

### Behavior

```python
%Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 18, in <module>
ValueError: Buffer is not a bytearray.
```

### Description

The documentation for `Display.fill_row()` says it accepts a `WriteableBuffer`:
https://github.com/adafruit/circuitpython/blob/1f82fa9d991622308144989daf9884109fa31c6d/shared-bindings/displayio/Display.c#L448-L452

However, if anything other than a `bytearray` is passed in, it raises an error:
https://github.com/adafruit/circuitpython/blob/1f82fa9d991622308144989daf9884109fa31c6d/shared-bindings/displayio/Display.c#L470-L472

Should the documentation be updated to expect a `bytearray`, or should the code be updated to deal with the full range of `WriteableBuffer`s?

**Comment by tannewt** [comment]
Either solution is fine with me.
