### ISSUE TITLE
usb_cdc.data.write no longer appears to work in 7.0.0

### ISSUE THREAD

**Issue by makermelissa** [adafruit/circuitpython#5381]
### CircuitPython version

```python
Adafruit CircuitPython 7.0.0 on 2021-09-20; Adafruit Macropad RP2040 with rp2040
```

### Code/REPL

```python
import usb_cdc
usb_cdc.data.write(bytes("test"))
```

### Behavior

Nothing

### Description

Code previously worked in CircuitPython 7.0.0 Alpha 5, but haven't tested versions in between.

**Comment by dhalbert** [comment]
What is in your `boot.py`?

**Comment by makermelissa** [comment]
I may have gotten a little too eager on this. It wasn't outputting because the version of the macropad library I had was older. Updating fixed it.
