### ISSUE TITLE
MP3 audio does not loop on 7.0.0

### ISSUE THREAD

**Issue by gamblor21** [adafruit/circuitpython#5415]
### CircuitPython version

```python
Adafruit CircuitPython 7.0.0 on 2021-09-20; Adafruit Hallowing M4 Express with samd51j19
```

### Code/REPL

```python
import board
import digitalio
from audiomp3 import MP3Decoder
from audioio import AudioOut

speaker_enable = digitalio.DigitalInOut(board.SPEAKER_ENABLE)
speaker_enable.direction = digitalio.Direction.OUTPUT
speaker_enable.value = True

audio = AudioOut(board.SPEAKER)
mp3 = open("laugh.mp3", "rb")
decoder = MP3Decoder(mp3)

audio.play(decoder, loop=True)
```

### Behavior

Audio starts playing, plays properly once and does not loop. Only tested with the single MP3 so far. MP3 used can be found at https://github.com/gamblor21/Laughing_Skull/blob/main/laugh.mp3

**Comment by jepler** [comment]
huh probably something similar to 
 * https://github.com/adafruit/circuitpython/issues/5164

**Comment by jepler** [comment]
don't you need a `while True: pass` to prevent your example program from exiting right after it starts playback?

**Comment by gamblor21** [comment]
I believe I was doing it in the REPL there. I still have the project sitting on a table somewhere so I will try to pull it out tomorrow and update it and see what it is doing.

**Comment by gamblor21** [comment]
Just tested with 7.2.0-alpha.2 and it is still occurring both in the REPL and in my actual code.

The project I was using this on is https://github.com/gamblor21/Laughing_Skull (`code-distance.py` is the version being ran).

**Comment by jepler** [comment]
Finally got around to reproducing this. On Trellis M4, the MP3 audio stops but the `playing` property of the speaker stays `True`.

**Comment by jepler** [comment]
We believe this is fixed. In fact, we believe so strongly that it is fixed, that we fixed it a second time.
