### ISSUE TITLE
Rename HID device

### ISSUE THREAD

**Issue by benwa** [adafruit/circuitpython#5445]
Currently, unless we recompile CircuitPython, we have to use "CircuitPython HID" for things like a game controller.
I'd like to be able to rename that, if at all possible.

**Comment by dhalbert** [comment]
- Related to #4433.

**Comment by fasteddy516** [comment]
I would love to see this functionality as well.  If you have multiple CP USB-HID devices connected simultaneously, selecting a specific one from a list (i.e. choosing a controller in a game, or a specialized input device for an editing suite) involves a mini-game of "which 'CircuitPython HID' device is which". 😃   

Something along the lines of `usb_hid.enable(name="My Nifty Controller", ...)` in `boot.py` would be lovely.

**Comment by George-TL** [comment]
With CPv8 we have supervisor.set_usb_identification() which is step in right direction.
Unfortunately "lsusb -v" still shows "CircuitPython HID" on iInterface attribute.

**Comment by usamashafiqs** [comment]
Any update on this

**Comment by dhalbert** [comment]
There are no immediate plans to implement this. If someone feels like working on a PR, that would be great.

**Comment by MariuszCwikla** [comment]
I would also like to have this feature.
I actually spent some time and implemented it here #8989
