### ISSUE TITLE
add Driver for SHT31D Temperature/Humidity Sensor

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#545]
https://www.adafruit.com/product/2857

**Comment by ladyada** [comment]
just adding a note, the arduino library is here https://github.com/adafruit/Adafruit_SHT31

**Comment by deshipu** [comment]
And the MicroPython one is here: https://github.com/kfricke/micropython-sht31

**Comment by jerryneedell** [comment]
Unless someone else want this one - you can assign it to me and I'll give it a shot.

**Comment by ladyada** [comment]
goooo foooor iiiiiit :)

**Comment by jerryneedell** [comment]
I have the basics working - can now read temperature and humidity and pass the checksums! The si7021 circuitpython library was a a great guide along with the Arduino  llibrary for the sht31. I hope to have something to share in the next few days.

**Comment by jerryneedell** [comment]
Driver released

**Comment by ladyada** [comment]
awesome work @jerryneedell - you did great!!! :)
