### ISSUE TITLE
7.0.0 crashes without import microcontroller

### ISSUE THREAD

**Issue by b-blake** [adafruit/circuitpython#5469]
### CircuitPython version

```python
Adafruit CircuitPython 7.0.0 on 2021-09-20; Raspberry Pi Pico with rp2040
Board ID:raspberry_pi_pico
boot.py output:
	Write to Flash  : False
	Write to SD Card: True
	boot.py Finis
```

### Code/REPL

```python
No erreo code given when it crashes.  Must push reset or remove power.
```

### Behavior

Crash without 'import microcontroller' even though not used.
Runs just fine with 'import microcontroller'

### Description

I built an application that would take in an RCA IR code of 'change input' and put out 7 'skip 30 seconds' TiVo IR codes. The application was working fine. I wanted to find out how to reference a pin that is not defined by CircuitPython but is on the RP2040. I used 'import microcontroller' to test how to define a pin using 'from microcontroller import pin' then 'test = pin.GPIO6'. It worked fine. I have commented out lines 2 and 3 of the test code. and things work fine. If I comment out the first test line (import microcontroller) the program crashes within the 'import adafruit_irremote' library after iteration #4 of 7 each time. microcontroller is not referenced in my code or in adafruit_irremote.py code. Below is my code that works/doesn't work minus the libraries. There are no error codes displayed on REPL. The only way out is a hard reset with the reset button or pulling power. Ctrl-C has no effect.

**Comment by jepler** [comment]
Looks like you have a `boot.py` file.  Please attach its content in case it is relevant.

**Comment by b-blake** [comment]
Jepler,

Below is my boot.py file.  The result is not used.  The pin to determine what action to take is changed board to board to avoid conflict.  I get the same results when I remove boot.py.  Pin A3 is unused on the ItsyBitsy.

###########################################
"""CircuitPython Essentials Storage logging boot.py file"""
import board
from digitalio import DigitalInOut, Direction, Pull
import storage

# For Feather M0/M4 Express, RPi Pico, etc.
switch           = DigitalInOut(board.A3)
switch.direction = Direction.INPUT
switch.pull      = Pull.UP

# If the switch pin is connected to ground CircuitPython can write to the root drive
storage.remount("/", switch.value)
print("\tWrite to Flash  :", (not switch.value))
print("\tWrite to SD Card:", switch.value)
print("\tboot.py Finis")
###########################################

**Comment by b-blake** [comment]
The code has evolved.  below is the code as it stands now.  Also the symptoms have changed on the ItsyBitsy only.  If "import microcontroller" ((Line 13)) is not commented out the device crashes after 4 codes are transmitted ((Line 245)).  No error codes given on REPL.  A hard reset is required.  There was an issue between .mpy and .py library files but that went away for no good reason.  
((Problem with .py library files.  Replaced with .mpy files. Things OK. Test again with .py, problem gone.))

##
##   IR Relay and translate by B.B.Blake 10/10/2021
##
#################### Import entrincic libraries ####################
import array
import board
import digitalio
from   digitalio import DigitalInOut, Direction, Pull
import neopixel
import pulseio
import pwmio
import time
##import microcontroller # I don't know why we need it, but we do.
#################### Import extrincic libraries ####################
import adafruit_esp32spi
from   adafruit_esp32spi import PWMOut
import adafruit_irremote

#################### Figure out what board we have ####################
Pico, Itsy, QTPy, Fthr, ANRC = False, False, False, False, False
bd    = board.board_id # Ask the AdaFruit OS what board we are using
print("\f" + bd, end=" - ")
if  (bd == "raspberry_pi_pico"):         Pico = True
elif(bd == "adafruit_itsybitsy_rp2040"): Itsy = True
elif(bd == "adafruit_qtpy_rp2040"):      QTPy = True
elif(bd == "adafruit_feather_rp2040"):   Fthr = True
elif(bd == "arduino_nano_rp2040_connect_rp2040"): ANRC = True
else:
    while(True):
        print("Board Not Supported.")
        time.sleep(15)
        pass
print("Board Supported.")

#################### Set some variables and constants ####################
freq  = 38000 # IR Tone Frequency
duty  = 32768 # IR Tone Duty Cycle, aka 50%

RED     = (255, 0, 0)
GREEN   = (0, 255, 0)
BLUE    = (0, 0, 255)
CYAN    = (0,255,255)
MAGENTA = (255,0,255)
YELLOW  = (255,255,0)
WHITE   = (255, 255, 255)
BLACK   = (0, 0, 0)

AdaFruit = False
## IR Codes from TiVo IR transmitter, the Peanut
SKIP30  = [0xD0, 0x27, 0x30, 0x85] # SKIP30 - TiVo
INPUT   = [0xF4, 0x0B, 0xFB, 0x04] # INPUT - RCA Source Select
## IR Codes from eBay IR transmitter
Skip_1  = [0xBA, 0x45, 0xFF, 0x00]
Skip_2  = [0xB9, 0x46, 0xFF, 0x00]
Skip_3  = [0xB8, 0x47, 0xFF, 0x00]
Skip_4  = [0xBB, 0x44, 0xFF, 0x00]
Skip_5  = [0xBF, 0x40, 0xFF, 0x00]
Skip_6  = [0xBC, 0x43, 0xFF, 0x00]
Skip_7  = [0xF8, 0x07, 0xFF, 0x00]
Skip_8  = [0xEA, 0x15, 0xFF, 0x00]
Skip_9  = [0xF6, 0x09, 0xFF, 0x00]
Skip_10 = [0xE6, 0x19, 0xFF, 0x00]
OK      = [0xE3, 0x1C, 0xFF, 0x00]
## IR Codes from AdaFruit IR transmitter
if(AdaFruit):
    Skip_1  = [0xEF, 0x10, 0xBF, 0x00]
    Skip_2  = [0xEE, 0x11, 0xBF, 0x00]
    Skip_3  = [0xED, 0x12, 0xBF, 0x00]
    Skip_4  = [0xEB, 0x14, 0xBF, 0x00]
    Skip_5  = [0xEA, 0x15, 0xBF, 0x00]
    Skip_6  = [0xE9, 0x16, 0xBF, 0x00]
    Skip_7  = [0xE7, 0x18, 0xBF, 0x00]
    Skip_8  = [0xE6, 0x19, 0xBF, 0x00]
    Skip_9  = [0xE5, 0x1A, 0xBF, 0x00]
    Skip_10 = [0xF3, 0x0C, 0xBF, 0x00]
    OK      = [0xF6, 0x09, 0xBF, 0x00] # aka ENTER/SAVE

#################### Configure things based on the board found ####################
if(Pico == True):
    IR_TX            = board.GP26

    IR_RX            = board.GP2
    IR_PWR           = board.GP1 # Draw power for the CHQ1838 form GPIO pin 1
    IR_PWR           = DigitalInOut(IR_PWR)
    IR_PWR.direction = Direction.OUTPUT
    IR_PWR.value     = True


    R_LED            = DigitalInOut(board.GP6)
    R_LED.direction  = Direction.OUTPUT
    B_LED            = DigitalInOut(board.GP7)
    B_LED.direction  = Direction.OUTPUT
    G_LED            = DigitalInOut(board.GP8)
    G_LED.direction  = Direction.OUTPUT
    R_LED.value, B_LED.value, G_LED.value = True,  True,  True
    time.sleep(0.5)
    R_LED.value, B_LED.value, G_LED.value = False, True, False 

if(Itsy == True):
    IR_TX            = board.TX

    IR_RX            = board.RX  # Pin connected to  IR receiver.
    IR_PWR           = board.D5
    IR_PWR           = DigitalInOut(IR_PWR)
    IR_PWR.direction = Direction.OUTPUT
    IR_PWR.value     = True

    PIXEL_PIN0       = board.NEOPIXEL # NeoPixel #0
    PIXELS_NUM0      = 1              # NeoPixel #0
    PIXEL_BRIGHT0    = 0.25           # NeoPixel #0
    PIXEL_ORDER0     = neopixel.GRB   # NeoPixel #0
    status_light0    = neopixel.NeoPixel(PIXEL_PIN0, PIXELS_NUM0, brightness=PIXEL_BRIGHT0, auto_write=True,  pixel_order=PIXEL_ORDER0)
    status_light0[0] = WHITE
    PIXEL_PIN1       = board.D7       # NeoPixel #1
    PIXELS_NUM1      = 1              # NeoPixel #1
    PIXEL_BRIGHT1    = 0.25           # NeoPixel #1
    PIXEL_ORDER1     = neopixel.RGB   # NeoPixel #1  (In, +5, Gnd, Out]-flat side to Right [RGB]
    status_light1    = neopixel.NeoPixel(PIXEL_PIN1, PIXELS_NUM1, brightness=PIXEL_BRIGHT1, auto_write=True,  pixel_order=PIXEL_ORDER1)
    status_light1[0] = WHITE
    time.sleep(0.5)
    status_light0[0] = BLUE
    status_light1[0] = BLUE

if(QTPy):
    IR_TX            = board.TX

    IR_RX            = board.RX

    PIXEL_PIN0       = board.NEOPIXEL # NeoPixel #0
    PIXELS_NUM0      = 1              # NeoPixel #0
    PIXEL_BRIGHT0    = 0.25           # NeoPixel #0
    PIXEL_ORDER0     = neopixel.GRB   # NeoPixel #0
    status_light0    = neopixel.NeoPixel(PIXEL_PIN0, PIXELS_NUM0, brightness=PIXEL_BRIGHT0, auto_write=True,  pixel_order=PIXEL_ORDER0)
    status_light0[0] = WHITE 
    time.sleep(0.5)
    status_light0[0] = BLUE

if(Fthr):
    IR_TX            = board.TX

    IR_RX            = board.RX

    PIXEL_PIN0       = board.NEOPIXEL # NeoPixel #0
    PIXELS_NUM0      = 1              # NeoPixel #0
    PIXEL_BRIGHT0    = 0.25           # NeoPixel #0
    PIXEL_ORDER0     = neopixel.GRB   # NeoPixel #0
    status_light0    = neopixel.NeoPixel(PIXEL_PIN0, PIXELS_NUM0, brightness=PIXEL_BRIGHT0, auto_write=True,  pixel_order=PIXEL_ORDER0)
    status_light0[0] = WHITE 
    time.sleep(0.5)
    status_light0[0] = BLUE

if not QTPy: LED           = DigitalInOut(board.LED)
if not QTPy: LED.direction = Direction.OUTPUT

#################### Create IR encoder and decoder ####################
# Create pulse INPUT and IR decoder.
pulses  = pulseio.PulseIn(IR_RX, maxlen=200, idle_state=True)
#pulseout = pulseio.PulseOut(IR_TX, frequency=freq, duty_cycle=duty) Duplicate
decoder = adafruit_irremote.GenericDecode()

## Create a 'pwmio' OUTPUT, to send infrared signals on the IR transmitter @ 38KHz
pwm = pwmio.PWMOut(IR_TX, frequency=freq, duty_cycle=duty) 
pulseout = pulseio.PulseOut(pwm)
## Create an encoder that will take numbers and turn them into NEC IR pulses
encoder = adafruit_irremote.GenericTransmit(header=[9500, 4500], zero=[562,  562], one=[562, 1687], trail=562, debug=False) 
##encoder = adafruit_irremote.GenericTransmit((9500, 4500), (562, 1687), (562, 562), 562)
print("#"*80)

#################### Function Definitions ####################
## Fuzzy pulse comparison function:
def fuzzy_pulse_compare(pulse1, pulse2, fuzzyness=0.2):
    if(Pico): R_LED.value, G_LED.value, B_LED.value = False, False, False
    if(Itsy): status_light0.fill(BLACK)
    if(Itsy): status_light1.fill(BLACK)
    if(QTPy): status_light0.fill(BLACK)
##    print(len(pulse1), len(pulse2))
    if len(pulse1) != len(pulse2):
##        print("Pulse Lengths don't match.")
        if(Pico): B_LED.value = True
        if(Itsy): status_light0.fill(BLUE)
        if(Itsy): status_light1.fill(BLUE)
        if(QTPy): status_light0.fill(BLUE)
        return False
    for i in range(len(pulse1)):
        threshold = (int(pulse1[i]) * fuzzyness)
        if abs(pulse1[i] - pulse2[i]) > threshold:
##            print(abs(pulse1[i] - pulse2[i]), i)
            if(Pico): R_LED.value = True
            if(Itsy): status_light0.fill(RED)
            if(Itsy): status_light1.fill(RED)
            if(QTPy): status_light0.fill(RED)
            return False
    if(Pico): G_LED.value = True
    if(Itsy): status_light0.fill(GREEN)
    if(Itsy): status_light1.fill(GREEN)
    if(QTPy): status_light0.fill(GREEN)
    return True

def make_fingerprint(datain, nbits=32, debug=False):
    datax = datain.copy()
    header=[9500, 4500]
    zero=[562,  562]
    one=[562, 1687]
    trail=562
    bits_to_send = len(datax) * 8
    if nbits is not None and nbits < bits_to_send:
        bits_to_send = nbits
    durations = array.array("H", [0] * (2 + bits_to_send * 2 + (0 if trail is None else 1)))
    durations[0] = header[0]
    durations[1] = header[1]
    if trail is not None:
        durations[-1] = trail
    out = 2
    bit_count = 0
    for byte_index, _ in enumerate(datax):
        byte_count = byte_index  # bbb
    for j in range(byte_count, -1, -1): # bbb
        for i in range(7, -1, -1): # bbb
            bit = datax[j] & 1 # bbb
            datax[j] = datax[j] >> 1 # bbb
            if(bit): # bbb
                durations[out] = one[0]
                durations[out + 1] = one[1]
            else:
                durations[out] = zero[0]
                durations[out + 1] = zero[1]
            out += 2
            bit_count += 1
            if bit_count >= bits_to_send:
                break
    if debug:
        print(durations)
    return(durations)

def skip_loop(loops):
    time.sleep(1)
    if not QTPy: LED.value = True
    for xx in range(loops):
        print(loops-xx, end=" ")
##        print( SKIP30 ) # [0xD0, 0x27, 0x30, 0x85] # SKIP30
##        IR_Command = [0xD0, 0x27, 0x30, 0x85] # SKIP30
        Ky = [0xD0, 0x27, 0x30, 0x85]
        IR_Command = Ky.copy()
##        print(SKIP30, IR_Command, Ky, 1)
        encoder.transmit(pulseout, reverse_bits(IR_Command), nbits=32)
##        print(SKIP30, IR_Command, Ky, 2)
        time.sleep(0.5)
    print("")
    if not QTPy: LED.value = False

def reverse_bits(IN):
    OUT = [0,0,0,0]
    Ks = IN.copy()
    for y in range(8): # Reverse the bits.
        for x in range(4): # Bytes 1 thru 4
            Bit     = (Ks[x] & 1)
            Ks[x]   = (Ks[x] >> 1)
            OUT[3-x] = ((OUT[3-x] << 1) + Bit)
    return(OUT)

#################### Main program ####################
ion = False
while ion: # Just print what the IR receiver receives
    time.sleep(0.3)
    pulses.clear()
    time.sleep(0.4)
    pulses.resume()
    time.sleep(0.3)
    pulse1 = decoder.read_pulses(pulses)
    print("IR Code Received")
    print(len(pulse1))
    print(pulse1)
    print("#"*80)
while not ion: # Perform actions depending what the IR receiver receives
##   Loop waiting to receive pulses.
    while True:
        if(AdaFruit): IR_ = 'AdaFruit'
        else:         IR_ = 'eBay'
        time.sleep(0.1)
        pulses.clear()
        time.sleep(0.1)
        pulses.resume()
        time.sleep(0.1)
        print('IR listener started...')
        # Wait for an IR Code to be detected.
        detected = decoder.read_pulses(pulses)
##        print(detected)
        print('got an IR Code...')
        # Got an IR Code, now compare.
        if fuzzy_pulse_compare(make_fingerprint(INPUT), detected, 0.5):
            print('Received correct INPUT TiVo/RCA remote control press!')
            print('Send Command to turn off the Source Select menu on the TV screen.')
            time.sleep(0.5)
            IR_Command = [0xF4, 0x0B, 0xFB, 0x04] # INPUT - Clear TV Screen
            encoder.transmit(pulseout, reverse_bits(IR_Command), nbits=32)
            skip_loop(7)
        elif fuzzy_pulse_compare(make_fingerprint(OK), detected, 0.5):
            print('Received correct OK '+IR_+' remote control press!')
            pass
        elif fuzzy_pulse_compare(make_fingerprint(SKIP30), detected, 0.5):
            print('Received correct SKIP30 TiVo remote control press!')
            pass
        elif(fuzzy_pulse_compare(make_fingerprint(Skip_1), detected, 0.5)):
            print('Received Skip_1 '+IR_+' remote control press!')
            skip_loop(1)
        elif(fuzzy_pulse_compare(make_fingerprint(Skip_2), detected, 0.5)):
            print('Received Skip_2 '+IR_+' remote control press!')
            skip_loop(2)
        elif(fuzzy_pulse_compare(make_fingerprint(Skip_3), detected, 0.5)):
            print('Received Skip_3 '+IR_+' remote control press!')
            skip_loop(3)
        elif(fuzzy_pulse_compare(make_fingerprint(Skip_4), detected, 0.5)):
            print('Received Skip_4 '+IR_+' remote control press!')
            skip_loop(4)
        elif(fuzzy_pulse_compare(make_fingerprint(Skip_5), detected, 0.5)):
            print('Received Skip_5 '+IR_+' remote control press!')
            skip_loop(5)
        elif(fuzzy_pulse_compare(make_fingerprint(Skip_6), detected, 0.5)):
            print('Received Skip_6 '+IR_+' remote control press!')
            skip_loop(6)
        elif(fuzzy_pulse_compare(make_fingerprint(Skip_7), detected, 0.5)):
            print('Received Skip_7 '+IR_+' remote control press!')
            skip_loop(7)
        elif(fuzzy_pulse_compare(make_fingerprint(Skip_8), detected, 0.5)):
            print('Received Skip_8 '+IR_+' remote control press!')
            skip_loop(8)
        elif(fuzzy_pulse_compare(make_fingerprint(Skip_9), detected, 0.5)):
            print('Received Skip_9 '+IR_+' remote control press!')
            skip_loop(9)
        elif(fuzzy_pulse_compare(make_fingerprint(Skip_10), detected, 0.5)):
            print('Received Skip_10 '+IR_+' remote control press!')
            skip_loop(10)
        else:
            print(detected)
            pass
        if(Pico): G_LED.value = False
        if(Itsy): status_light0.fill(BLACK)
        if(Itsy): status_light1.fill(BLACK)
        if(QTPy): status_light0.fill(BLACK)
        time.sleep(0.1)
        pulses.clear()
        time.sleep(0.1)
        pulses.resume()
        time.sleep(0.1)
        print("#"*80)

**Comment by dhalbert** [comment]
I don't think it is just size. There is memory corruption somewhere. You might leave all these imports in and turn off various parts of the program with `if False:` etc.

**Comment by b-blake** [comment]
Dan,

I have narrowed it down to this function call:
print(SKIP30, IR_Command, Ky, 1)
**encoder.transmit(pulseout, reverse_bits(IR_Command), nbits=32)**
print(SKIP30, IR_Command, Ky, 2)

Encoder is defined much earlier by:
# Create an encoder that will take numbers and turn them into NEC IR pulses
**encoder = adafruit_irremote.GenericTransmit(header=[9500, 4500], zero=[562,  562], one=[562, 1687], trail=562, debug=False)** 

I have no control over adafruit_irremote or the intrinsic functions it calls.  I doubt they are part of the issue.

The code crashes after the first print call but before the second.  Previously when it was crashing at 4 SKIP30 calls there was a bunch of diagnostic code and lots of crap coding.  When I cleaned up a bunch of the crap code and diagnostic stuff, the issue went away.  When I added in some code to make the program more flexible the crashes cam back.  So size is a **tell**; as to what/where, I have no clue.

Your idea about memory corruption is interesting because the issue only happens in my ItsyBitsy RP2040.  It does not raise its ugly head on my QT Py RP2040, Feather RP2040, or Raspberry Pi Pico.  I started development on the RPi Pico but wanted to make it portable to the other RP2040 platforms.  (Don't tell anybody, but the AdaFruit platforms are better in several ways.)  There was also an issue of bad algorithm execution on the ItsyBitsy that went away for no discernable reason. *Not working with .py library. *Working with .mpy library. *Working with .py library.  Trying to isolate to an .py library issue didn't work.  Both started working.  So much for that idea.

Bruce
