### ISSUE TITLE
PWM auto-brightness for displays does not work

### ISSUE THREAD

**Issue by deshipu** [adafruit/circuitpython#5476]
### CircuitPython version

```python
Adafruit CircuitPython 7.0.0 on 2021-09-20; Adafruit PyGamer with samd51j19
```

### Code/REPL

```python
import board
import displayio
import busio

_TFT_INIT = (
    b"\x01\x80\x96" # SWRESET and Delay 150ms
    b"\x11\x80\xff" # SLPOUT and Delay
    b"\xb1\x03\x01\x2C\x2D" # _FRMCTR1
    b"\xb2\x03\x01\x2C\x2D" # _FRMCTR2
    b"\xb3\x06\x01\x2C\x2D\x01\x2C\x2D" # _FRMCTR3
    b"\xb4\x01\x07" # _INVCTR line inversion
    b"\xc0\x03\xa2\x02\x84" # _PWCTR1 GVDD = 4.7V, 1.0uA
    b"\xc1\x01\xc5" # _PWCTR2 VGH=14.7V, VGL=-7.35V
    b"\xc2\x02\x0a\x00" # _PWCTR3 Opamp current small, Boost frequency
    b"\xc3\x02\x8a\x2a"
    b"\xc4\x02\x8a\xee"
    b"\xc5\x01\x0e" # _VMCTR1 VCOMH = 4V, VOML = -1.1V
    b"\x20\x00" # _INVOFF
    b"\x36\x01\xa0" # _MADCTL
    # 1 clk cycle nonoverlap, 2 cycle gate rise, 3 sycle osc equalie,
    # fix on VTL
    b"\x3a\x01\x05" # COLMOD - 16bit color
    b"\xe0\x10\x02\x1c\x07\x12\x37\x32\x29\x2d\x29\x25\x2B\x39\x00\x01\x03\x10" # _GMCTRP1 Gamma
    b"\xe1\x10\x03\x1d\x07\x06\x2E\x2C\x29\x2D\x2E\x2E\x37\x3F\x00\x00\x02\x10" # _GMCTRN1
    b"\x13\x80\x0a" # _NORON
    b"\x29\x80\x64" # _DISPON
)

displayio.release_displays()
_tft_spi = busio.SPI(clock=board.TFT_SCK, MOSI=board.TFT_MOSI)
_fourwire = displayio.FourWire(_tft_spi, command=board.TFT_DC,
                               chip_select=board.TFT_CS, reset=board.TFT_RST)
display = displayio.Display(_fourwire, _TFT_INIT, width=160, height=128,
                            rotation=0, backlight_pin=board.TFT_LITE,
                            auto_refresh=False, auto_brightness=True)

print("great success")
```

### Behavior

Hard crash at the line

```
display = displayio.Display(_fourwire, _TFT_INIT, width=160, height=128,
                            rotation=0, backlight_pin=board.TFT_LITE,
                            auto_refresh=False, auto_brightness=True)
```

### Description

This bug prevents the use of the Stage library on PyGamer and PyBadge, because on those boards I have to re-initialize the displays with the correct MADCTL for the display's physical rotation (the default initialization has wrong MADCTL and does the rotation in software in displayio, which doesn't work for Stage).

### Additional information

As far as I can tell, the board becomes completely unresponsive. There is no output on the serial console, and the USB drive, while still visible, can't be interacted with.

**Comment by deshipu** [comment]
This was originally reported at https://forums.adafruit.com/viewtopic.php?f=60&t=184121&p=894387#p893826

**Comment by deshipu** [comment]
I tried to debug this today, but the PyBadge I have seems to have locked MCU, and PyGamer doesn't seem to have the debugging port at all. I can't reproduce this on PewPew M4.

**Comment by deshipu** [comment]
I managed to get the pybadge unlocked.

This seems to be related to backlight handling, as it seems to be stuck in this loop:

```
Program received signal SIGTRAP, Trace/breakpoint trap.
0x00013f98 in common_hal_pwmio_pwmout_set_duty_cycle (
    self=self@entry=0x20000840 <displays+184>, duty=duty@entry=65535)
    at common-hal/pwmio/PWMOut.c:309
309	        while (tc->COUNT16.SYNCBUSY.bit.CC1 != 0) {
```

**Comment by deshipu** [comment]
Removing ``backlight_pin=board.TFT_LITE`` does not help, but changing ``auto_brightness=True`` to ``False`` makes it work again.

**Comment by deshipu** [comment]
I thought that maybe the pwm pin on the display's backlight is not being de-initialized properly when ``release_displays`` is called, but it seems to be fine, and creating a ``PWMOut`` object on the backlight pin and setting its duty cycle works fine after releasing the displays, without a crash (though I don't see the brightness of the backlight changing on the PyBoard, maybe it's hardwired).

I don't see why the PWM would fail to sync in this case. Any help with this would be appreciated.

**Comment by tannewt** [comment]
I haven't looked at the surrounding code but maybe there is already some sync task happening? Maybe the TC is still being reset? 

Maybe we changed the TC clocking code and the peripheral isn't clocked anymore. That'd cause the sync to hang.

**Comment by deshipu** [comment]
I couldn't follow the development of 7.x version due to personal problems, so it's hard for me to guess what could have been changed around the PWM code for SAMD51. One thing that especially baffles me is that if I create a `PWMOut` from Python code, and set its `duty_cycle` — which calls exactly the same function as the `auto_brightness` — the loop exists correctly and there is no hang. Next time I have a chance to work on this, I'm going to see if adding delays affects the issue.

In the mean time, should I remove the `auto_brightness` from the `stage` initialization code for PyGamer and PyBadge, to make that library work? Should we add note in DisplayIO documentation to not use that option?

**Comment by tannewt** [comment]
I don't know of any SAMD PWM changes off the top of my head so I'm in the same position you are.

> In the mean time, should I remove the `auto_brightness` from the `stage` initialization code for PyGamer and PyBadge, to make that library work? Should we add a note in DisplayIO documentation warning to never use that option?

It's up to you about stage.

I don't want to change the displayio docs because it should work. Instead of warning about a bug, we should fix it.

**Comment by deshipu** [comment]
> I don't want to change the displayio docs because it should work. Instead of warning about a bug, we should fix it.

But ``auto_brightness`` never worked?

**Comment by tannewt** [comment]
Ah, true. It's probably best to remove it completely.

**Comment by deshipu** [comment]
I did some experimenting with delays, but to no avail. So I just went and made the Stage code for PyBadge and PyGamer manage the backlight pin with digitalio, independently from displayio.

**Comment by dhalbert** [comment]
Get rid of this feature in 8.0.0, and maybe make it non-operative in 7.x.x.
