### ISSUE TITLE
same51j19a: Hardfault with UART

### ISSUE THREAD

**Issue by mrdalgaard** [adafruit/circuitpython#5493]
### CircuitPython version

```python
Adafruit CircuitPython 7.0.0-509-gcf4597c6d on 2021-10-20; Adafruit Feather M4 CAN with same51j19a
```

### Code/REPL

```python
>>> import board
>>> import busio
>>> bus = busio.UART(board.TX, board.RX, baudrate=9600, receiver_buffer_size=1024, timeout=5)
>>> bus = busio.UART(board.TX, board.RX, baudrate=9600, receiver_buffer_size=1024, timeout=5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: D0 in use
>>>
paste mode; Ctrl-C to cancel, Ctrl-D to finish
=== print("test")
<press CTRL-D>
```

### Behavior

Trying to initialize UART twice without deinit() between uses will hardfault on subsequent use of paste mode in REPL (memory corruption?!)

It does not seem to be directly related to the REPL or paste mode, as i've had it crash running code too.

### Description

Happens on 7.0.0 release too

**Comment by jepler** [comment]
Reproduced on Feather M4 Express.
