### ISSUE TITLE
Neopixel Library Issue

### ISSUE THREAD

**Issue by john94501** [adafruit/circuitpython#5505]
Hardware: ItsyBitsy M4 + Neopixel Jewel 7
Bootloader: 3.13.0
CircuitPython: 7.0.0 

Initially, all 7 LEDs are off as expected. When I execute this code the center LED on the Jewel lights bright green (brighter that the 0.3 level that was selected), even though I sent them as all off:

    import board
    import neopixel

    OFF = (0, 0, 0)
    RED = (255, 0, 0)

    pixels = neopixel.NeoPixel(board.A1, 7, brightness=0.3, auto_write=False)
    pixels.fill(OFF)
    pixels.show()

Changing the value sent to fill causes the other color elements to light up but the green is always on, so the center does not match the others. If I set them all to green, the center is brighter.

Reverted to CircuitPython 6.3.0 (nothing else changed) and it works as expected.

**Comment by dhalbert** [comment]
See if this fails if the program does not exit.
See if due to floating NeoPixel pin.
