### ISSUE TITLE
readthedocs isn't building

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#5543]
see e.g., this build: https://readthedocs.org/projects/circuitpython/builds/15185882/

```
Running Sphinx v3.5.4
Traceback (most recent call last):
  File "tools/extract_pyi.py", line 201, in convert_folder
    tree = ast.parse(fragment)
  File "/home/docs/.pyenv/versions/3.7.9/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 27
    def continuous_capture_start(self, buffer1: WriteableBuffer, buffer2: WriteableBuffer, /) -> None:
                                                                                           ^
SyntaxError: invalid syntax
make: *** [stubs] Error 1
```

This is due to syntax introduced into a comment at #5540.

**Comment by dhalbert** [comment]
Would newer Sphinx handle this?

**Comment by kattni** [comment]
I don't think so. I just tried to build it and I'm pretty sure I'm running the latest Sphinx locally, and it failed.

**Comment by jepler** [comment]
no it's about the Python version.  This language feature, "/" in a parameter list of `def`, is new in python 3.8 or something.

**Comment by dhalbert** [comment]
I was just wondering if a newer sphinx knew about that new feature, but I'm realizing it depends on Python to do the parsing. (I guess!)

We can consider moving to 3.8 for CI.

**Comment by jepler** [comment]
It's the sphinx version on RTD that matters, can we select it there?

**Comment by jepler** [comment]
Builds are working now https://readthedocs.org/projects/circuitpython/builds/15188695/
