### ISSUE TITLE
SAMD Watchdog Timer only supports timeouts that are a powers of 2 seconds less than or equal to 16 seconds

### ISSUE THREAD

**Issue by DaveSprague** [adafruit/circuitpython#5546]
### CircuitPython version

```python
Adafruit CircuitPython 7.0.0-615-g38c381633 on 2021-11-03; Adafruit ItsyBitsy M4 Express with samd51g19
```

### Code/REPL

```python
import time

for t in range(10,0,-1):
    print("Starting in " + str(t) + " seconds")
    time.sleep(1.0)

from microcontroller import watchdog as w
from watchdog import WatchDogMode

w.timeout = 5.0
w.mode = WatchDogMode.RESET

tenths_count = 400  # tenths of seconds

w.feed()
for i in range(tenths_count):
    print(str(i/10) + " seconds since feeding WatchDog")
    time.sleep(0.1)

print("Reached end")
```

### Behavior

// The watchdog timer is set to 5.0 seconds but it doesn't timeout until 8.0 seconds have elapsed
// Here is the serial monitor output
code.py output:
Starting in 10 seconds
Starting in 9 seconds
Starting in 8 seconds
Starting in 7 seconds
Starting in 6 seconds
Starting in 5 seconds
Starting in 4 seconds
Starting in 3 seconds
Starting in 2 seconds
Starting in 1 seconds
0.0 seconds since feeding WatchDog
0.1 seconds since feeding WatchDog
0.2 seconds since feeding WatchDog
0.3 seconds since feeding WatchDog
0.4 seconds since feeding WatchDog
0.5 seconds since feeding WatchDog
0.6 seconds since feeding WatchDog
0.7 seconds since feeding WatchDog
0.8 seconds since feeding WatchDog
0.9 seconds since feeding WatchDog
1.0 seconds since feeding WatchDog
1.1 seconds since feeding WatchDog
1.2 seconds since feeding WatchDog
1.3 seconds since feeding WatchDog
1.4 seconds since feeding WatchDog
1.5 seconds since feeding WatchDog
1.6 seconds since feeding WatchDog
1.7 seconds since feeding WatchDog
1.8 seconds since feeding WatchDog
1.9 seconds since feeding WatchDog
2.0 seconds since feeding WatchDog
2.1 seconds since feeding WatchDog
2.2 seconds since feeding WatchDog
2.3 seconds since feeding WatchDog
2.4 seconds since feeding WatchDog
2.5 seconds since feeding WatchDog
2.6 seconds since feeding WatchDog
2.7 seconds since feeding WatchDog
2.8 seconds since feeding WatchDog
2.9 seconds since feeding WatchDog
3.0 seconds since feeding WatchDog
3.1 seconds since feeding WatchDog
3.2 seconds since feeding WatchDog
3.3 seconds since feeding WatchDog
3.4 seconds since feeding WatchDog
3.5 seconds since feeding WatchDog
3.6 seconds since feeding WatchDog
3.7 seconds since feeding WatchDog
3.8 seconds since feeding WatchDog
3.9 seconds since feeding WatchDog
4.0 seconds since feeding WatchDog
4.1 seconds since feeding WatchDog
4.2 seconds since feeding WatchDog
4.3 seconds since feeding WatchDog
4.4 seconds since feeding WatchDog
4.5 seconds since feeding WatchDog
4.6 seconds since feeding WatchDog
4.7 seconds since feeding WatchDog
4.8 seconds since feeding WatchDog
4.9 seconds since feeding WatchDog
5.0 seconds since feeding WatchDog
5.1 seconds since feeding WatchDog
5.2 seconds since feeding WatchDog
5.3 seconds since feeding WatchDog
5.4 seconds since feeding WatchDog
5.5 seconds since feeding WatchDog
5.6 seconds since feeding WatchDog
5.7 seconds since feeding WatchDog
5.8 seconds since feeding WatchDog
5.9 seconds since feeding WatchDog
6.0 seconds since feeding WatchDog
6.1 seconds since feeding WatchDog
6.2 seconds since feeding WatchDog
6.3 seconds since feeding WatchDog
6.4 seconds since feeding WatchDog
6.5 seconds since feeding WatchDog
6.6 seconds since feeding WatchDog
6.7 seconds since feeding WatchDog
6.8 seconds since feeding WatchDog
6.9 seconds since feeding WatchDog
7.0 seconds since feeding WatchDog
7.1 seconds since feeding WatchDog
7.2 seconds since feeding WatchDog
7.3 seconds since feeding WatchDog
7.4 seconds since feeding WatchDog
7.5 seconds since feeding WatchDog
7.6 seconds since feeding WatchDog
7.7 seconds since feeding WatchDog
7.8 seconds since feeding WatchDog
7.9 seconds since feeding WatchDog
8.0 seconds since feeding WatchDog
  {-- WatchDog RESET occurs at this point -- }

### Description

This appears to be intentional in the code to take the ceil(log2(n)) / 1024, where n is the timeout in milliseconds.  The effect is that float timeout specified is rounded up to the next higher power of 2 seconds, up to a maximum of 16 seconds.

For example, a timeout of 4.0 seconds will time out after 4.0 seconds but a timeout out of 4.1 seconds will not timeout until 8.0 seconds have elapsed.  Since the maximum number of milliseconds you can specify is 16384, the net result is that the only timeout delays you can get are 1, 2, 4, 8, or 16 seconds.

Is this due to some restrictions one how the watchdog timer is implemented on the SAMD architecture?

Here is the key lines of code that do this calculation of the _timeout_ in seconds given the (float) _new_timeout_ in seconds, along with some comments from the code and some I've _added_ to clarify what's happening.
This is from the file:
**_ports/atmel-samd/common-hal/watchdog/WatchDogTimer.c_** , submitted in this PR: #5483 

```
    int wdt_cycles = (int)(new_timeout * 1000);
       ... 
    // ceil(log2(n)) = 32 - __builtin_clz(n - 1) when n > 1 (if int is 32 bits)
       // added: __buildin_clz returns a count of the number of leading zeros 
    int log2_wdt_cycles = (sizeof(int) * CHAR_BIT) - __builtin_clz(wdt_cycles - 1);
    int setting = log2_wdt_cycles - 3; // CYC8_Val is 0
    float timeout = (8 << setting) / 1024.f;
       // added:  timeout is calculated as a float but it can really only have values of 1.0, 2.0, 4.0, 8.0, and 16.0
```

**Comment by jepler** [comment]
Yes, the hardware is limited to a few specific watchdog timeout periods.

![image](https://user-images.githubusercontent.com/1517291/140545259-ba7c6daa-d3d6-41bd-b4e1-78577f19dc51.png)

You can find out the specific period that has been set by reading the timeout property. It is intended to always be at least as large as the value assigned. (however, there was a small bug there, see #5549)
```
>>> microcontroller.watchdog.timeout = 5
>>> microcontroller.watchdog.timeout
8.0
```
