### ISSUE TITLE
Soft Rebooting of CP 7 every 5 seconds

### ISSUE THREAD

**Issue by kwpodolsky** [adafruit/circuitpython#5548]
### CircuitPython version

```python
Adafruit CircuitPython 7.0.0 on 2021-09-20; Adafruit Feather RP2040 with rp2040
Board ID:adafruit_feather_rp2040
```

### Code/REPL

```python
# FILE: Code.py

import time
import board
import neopixel

#print("Hello World!")

pixels = neopixel.NeoPixel(board.NEOPIXEL, 1)

dir = 0
index = 0
colors = [[255,0,0],[0,255,0],[0,0,255],[255,255,0],[255,0,255],[0,255,255],[255,255,255]]

while True:
    colr = colors[index]
    pixels.fill((colr))
    time.sleep(0.5)
    pixels.fill((0, 0, 0))
    time.sleep(0.5)
    if dir == 0:
      if index == 6:
        dir = 1
#        index = 0
      else:
        index += 1
    else:
      if index == 0:
        dir = 0
#        index = 0
      else:
        index -= 1
```

### Behavior

Code starts to run and every 5 seconds CP does a soft reboot.
Following is on MU console.

"Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:

Code stopped by auto-reload.
soft reboot"

### Additional information

Program runs fine when issued via "import command from REPL"
I have NEVER seen this issue when using MicroPython and boot.py.
WHY does CP insist on soft rebooting or forcing user to enter REPL?
HOW can you have a program that auto runs?

**Comment by kwpodolsky** [comment]
Disregard this bug issue.
Found that I needed to put...

import supervisor
supervisor.disable_autoreload() 

In my code.py file to prevent CP from soft rebooting.

This should be major NOTE somewhere in the CP tutorials.

**Comment by dhalbert** [comment]
When some filesystem operation on CIRCUITPY causes a write, CircuitPython assumes that you have changed your program, and restarts `code.py`. Something on your host computer is writing to CIRCUITPY frequently. What is your host operating system, and what editor are you using? It may be a utility program that is writing to the drive or accessing it in some way that causes a metadata update, such an an indexing or backup program, or a disk-checking utility.

If you want to turn this feature off completely, you can use `supervisor.disable_autoreload()`. https://circuitpython.readthedocs.io/en/latest/shared-bindings/supervisor/index.html#supervisor.disable_autoreload. However, most people don't see the issue you're having, so it would be worth investigating why it's happening.

**Comment by kwpodolsky** [comment]
NONE of the above.    If I disconnect the device and just run it off battery, it did the same thing.
It has to do with the AutoReload "feature" in CP.
Since MP doesn't have that, it was never an issue for me.

By adding the lines of code, above, problem is gone.

**Comment by dhalbert** [comment]
> If I disconnect the device and just run it off battery, it did the same thing.

Auto-reload should not be triggered if the board is not connected to a host, so this is odd. What kind of battery arrangement were you using? What behavior did you see that it was auto-reloading on battery?

**Comment by dhalbert** [comment]
> Auto-reload should not be triggered if the board is not connected to a host, so this is odd. What kind of battery arrangement were you using? What behavior did you see that it was auto-reloading on battery?

As I mentioned, this should not happen at all, if you are not connected to a host.

A usb "power pack" can require a certain amount of power to be drawn to stay on. Testing with a simple 5V AC adapter or charger would remove that possible issue.

Closing this for now, because I think this is a support issue, not  core issue.

**Comment by akshay2000** [comment]
Leaving this comment her for posterity:

Mu can be a culprit sometimes. When I start Mu, it seems to write something to the CIRCUITPY filesystem every few seconds - causing the reload. @kwpodolsky You've probably moved on, but in case you still have your set up, can you kill Mu and see if the reload still happens?
