### ISSUE TITLE
boot_out.txt not created if absent (eg after erase_filesystem)

### ISSUE THREAD

**Issue by Neradoc** [adafruit/circuitpython#5588]
Tested on a Trinket.
```py
>>> import storage
>>> storage.erase_filesystem()
```
The board resets with a fresh CIRCUITPY, but `boot_out.txt` is missing.
Creating a boot_out.txt file makes it be correctly populated on reset.

**Comment by anecdata** [comment]
I observed similar yesterday on PyPortal. Hard reset does it, but not `microcontroller.reset()`.

**Comment by Neradoc** [comment]
I think this could do it but that might not take into account all the possible cases.
```C
} else {
    write_boot_output = true;
}
```
https://github.com/adafruit/circuitpython/blob/18b3e6c4fc2909af70bd8ccef06bb93bf02dce28/main.c#L681-L691

**Comment by jepler** [comment]
Thanks, the info about reset_reason was super helpful!
