### ISSUE TITLE
RP2040 join FIFO in PIO Statemachine

### ISSUE THREAD

**Issue by megazhuk** [adafruit/circuitpython#5604]
In original Micropython already emplemented "JOIN FIFO" functionality.

Do you have any plans to do it in CircuitPython?

This is very useful thing, when working with HISPEED interfaces, because single RX_FIFO extremally quick overloads on 32bit data at 2..4Mhz dataline. Python does not have time to transfer data to the buffer, and FIFO is already full. Doubleling FIFO cal solve this issue.

**from MicroPython GitHub**

issue:
- rp2 PIO: Allow merging Tx/Rx FIFOs together [#6854](https://github.com/micropython/micropython/issues/6854)

pull:
- rp2/rp2_pio: Add fifo_join support for PIO. [#7093](https://github.com/micropython/micropython/pull/7093)

_Originally posted by @kevindawson in https://github.com/raspberrypi/pico-micropython-examples/issues/27#issuecomment-830783883_

**Comment by tannewt** [comment]
CircuitPython does it automatically when a state machine only goes one direction: https://github.com/adafruit/circuitpython/blob/main/ports/raspberrypi/common-hal/rp2pio/StateMachine.c#L291-L296
