### ISSUE TITLE
CP 7.1.0 RP2040 Starts automatically after Ctrl-C

### ISSUE THREAD

**Issue by b-blake** [adafruit/circuitpython#5612]
### CircuitPython version

```python
Adafruit CircuitPython 7.1.0-beta.0-8-g28b5733bd on 2021-11-12; Adafruit Feather RP2040 with rp2040
Board ID:adafruit_feather_rp2040
```

###  SEE BELOW FOR SMALL TEST PROGRAM THAT SHOWS THE BUG ###

```python

Bunch of stuff deleted, see below for example code.
```

### Behavior

code.py starts running by itself while REPL is on the terminal screen with >>> being displayed.  This takes about 25 seconds to happen.  Keyboard untouched.

### Description

If I write edited code.py back to my RP2040 while supervisor.disable_autoreload() is in effect,
and then I go to the REPL screen, hit Ctrl-C while supervisor.enable_autoreload() is in effect and review data.
If I hit Ctrl-D within ~25 seconds, code.py starts normally.
If I wait more than ~25 seconds code.py starts without my request.
I presume the code I write while supervisor.disable_autoreload() was in effect, causes the start of code.py.
My code runs in disable mode for 2 to 5 seconds then runs in enable mode for 15 seconds..

Edditing issues with input ...

### SEE BELOW FOR TEST PROGRAM ###

**Comment by b-blake** [comment]
Please excuse typos in Description.  Edit location and cursor location got out of sync for some reason.  Last two lines should read:

I presume the code I write while supervisor.disable_autoreload() was in effect, causes the start of code.py.
My code runs in disable mode for 2 to 5 seconds then runs in enable mode for 15 seconds..

**Comment by jepler** [comment]
You can use the edit button (inside the 3 dots menu) to edit your comment at any time to fix typos.

**Comment by b-blake** [comment]
> You can use the edit button (inside the 3 dots menu) to edit your comment at any time to fix typos.

Thank you!

**Comment by b-blake** [comment]
This simple code shows the issue on my machine.  The wait time to auto start varies.

Resave the code.py during **disable**
Hit Ctrl-C during **enable**

import time
import supervisor

while True:
    supervisor.disable_autoreload()
    print("Disable for 5 Seconds")
    time.sleep(5)
    supervisor.enable_autoreload()
    print("Enable for 10 Seconds")
    time.sleep(10)

Bruce

**Comment by dhalbert** [comment]
Needs retest after recent rework of autoreload logic.

**Comment by b-blake** [comment]
Dan,

Unable to reproduce problem.  It looks like you fixed it.

Bruce

**Comment by dhalbert** [comment]
Thanks for testing!
