### ISSUE TITLE
Update py descriptor gen to have HID

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#565]
currently has CDC + MSC only
once key/mouse HID support is added we can extend to do multimedia (and maybe joystick!)

**Comment by tannewt** [comment]
What priority do you have for this @ladyada? I don't feel like its required for 3.0 Beta so I'd prefer to wait a bit. Ideally, I'd only assign it to myself once I'm working on it in case someone else beats me to it.

**Comment by ladyada** [comment]
Having the busio & CDC+MSC being done and stable is more important than USB HID, so how about after that feels solid - up to y'all whether it's in the beta or not!

**Comment by tannewt** [comment]
Ok, I'll unassign for now in case someone wants to beat me to it.

**Comment by tannewt** [comment]
Here is where I left on this. Not sure where it was at: https://github.com/tannewt/usb_descriptor/tree/hid

**Comment by tannewt** [comment]
This is done in https://github.com/adafruit/usb_descriptor/commit/2edd94c50b67ac2acc665a5b06e34c2625a8f622. Thanks @dhalbert!
