### ISSUE TITLE
Add height and width properties to vectorio.Rectangle

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/circuitpython#5695]
A few times we've had folks come into the discord and ask about changing the size of shapes created with the `display_shapes` library. Those currently have immutable sizes and it would somewhat difficult to allow them to get resized bigger because they would need to allocate a new Bitmap object (unless Bitmap also got mutable height and width).

We've been directing folks to try out `vectorio` when they need to change the size of their shapes. vectorio.Circle has a `radius` property that can be changed to change the size of the circle. Polygon as a `points` property that can similarly change size or shape of the polygon.

vectorio.Rectangle only accepts height and width at initialization time and does not have properties to access or change them. It would be great if those properties could be added so that the height and width could be manipulated after the Rectangle has been created.

@warriorofwire if you've got the cycles and are interested in making this enhancement that would be awesome. If not no worries though I can try to make an attempt at it as well.

**Comment by WarriorOfWire** [comment]
Oh yeah, thanks for the report! I’ll make time within a few days.
