### ISSUE TITLE
Todays (2021-12-10) build of CP for Raspberry Pi 4B does not work

### ISSUE THREAD

**Issue by dronecz** [adafruit/circuitpython#5703]
### CircuitPython version

```python
latest CircuitPython 7.1.0-beta.2
```

### Code/REPL

```python
none
```

### Behavior

Pi does not boot up

### Description

I download latest build from [web](https://circuitpython.org/board/raspberrypi_pi4b/) and when I flash it to the SD card, I can see these files: 

![image](https://user-images.githubusercontent.com/16454728/145654712-9ea808d5-6cb4-4688-aab0-87810e99841e.png)

When I try older build (7.2.0-alpha.0-102-gb50443240 on 2021-12-10), Pi works OK and I can see these files at my SD card. 

![image](https://user-images.githubusercontent.com/16454728/145654872-ee15d72f-6fe4-4b0f-9490-f3123e5b3f5d.png)

I hope this info help. Thanks for great work!

**Comment by jerryneedell** [comment]
You probably don't want a build from the 7.1.x branch. Try the latest build from 7.2.0-alpha. It should be the previous build to the beta version in the list at the S3 site.

**Comment by jerryneedell** [comment]
FYI -- I just tried the latest build and it does boot for me -- the Mass Stage Drive (CIRCUITPY) is still not working, but I get a REPL on the UART.

**Comment by tannewt** [comment]
@jerryneedell is correct. The `.dtb` files were added after the 7.1.0 branch so please use the absolute newest builds. (We'll do a 7.2.0 unstable release once 7.1.0 is stable.)
