### ISSUE TITLE
allow WaveFile() and MP3Decoder to accept the file path

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/circuitpython#5713]
Recent changes in the core allowed OnDiskBitmap to be passed the file path of an image file instead of user code needing to open the file and then pass the open buffer. This is helpful because it allows user code not to worry about opening and closing the file and negates the need for (and pylint error about) using `with` context processor.

We could add similar functionality. for WaveFile to accept the filepath, same for MP3Decoder.

**Comment by dhalbert** [comment]
Fixed by #6931.
