### ISSUE TITLE
Using usb_cdc.data functions???

### ISSUE THREAD

**Issue by JeffBabis** [adafruit/circuitpython#5730]
### CircuitPython version

> Adafruit CircuitPython 7.0.0 on 2021-09-20; Adafruit Feather M4 Express with samd51j19
Board ID:feather_m4_express
>
> I have been using Arduino boards and their version of the C language for years. 
> Communication through the USB jack (programming port) has always been simple using the Serial module (Serial.begin, Serial.available, Serial.read, Serial.println etc.) 
> I have a customer who requires that I use an Adafruit Feather M4 Express with circuit Python to do the same thing. 
> Using the usb_cdc.Serial functions appear to be what I need but of course the following code must be in the boot program to enable the data port:

```python
import usb_cdc
usb_cdc.enable(console=True, data=True)
```

> All Adafruit resources indicate that I should modify the boot.py file, what do I do since the boot file on the Feather M4 Express is in UF2 format, where do I get the source code to either the Featherboot module (is it open source?) or a version of boot.py that will work on a Feather M4 Express? 
> Would it be possible to compile a stable version of the bootloader that enables both ports for the Feather boards?

### Code/REPL

```python
import usb_cdc
usb_cdc.enable(console=True, data=True)
```

### Behavior

Can not run code since I don't have access to the source code of the bootloader or a copy of a working boot.py file

**Comment by anecdata** [comment]
`boot.py` is a user-written [Circuit]Python file that executes only on a hard reset, prior to `code.py`. You save it on the mounted `CIRCUITPY` volume. It is not part of the circuitpython UF2.

With that in mind, I'd suggest (re-)reviewing this Adafruit Learn Guide:
https://learn.adafruit.com/customizing-usb-devices-in-circuitpython
