### ISSUE TITLE
Please add collections deque to CircuitPython

### ISSUE THREAD

**Issue by jftheoret** [adafruit/circuitpython#5734]
Hello!

Please activate collections deque in CircuitPython. Thanks!

**Comment by tannewt** [comment]
What board are you using? Some of them won't have space for it.

**Comment by jftheoret** [comment]
I'm using the Raspberry Pi Pico.

I was actually looking in the code to see if I could activate it and
recompile?

Thanks :)

**Comment by tannewt** [comment]
You can set `MICROPY_PY_COLLECTIONS_DEQUE` to `(1)` to enable it.

**Comment by jftheoret** [comment]
Thanks!!

I will definitely try it. It's also going to be an opportunity to learn how
to build it :)

**Comment by jftheoret** [comment]
Another quick question for you - I have changed the code, recompiled and
re-flashed the firmware.

The import now works.

When I try to use it:

self.stored_chars = deque([], 4)


I get a ValueError. I am trying to create an empty queue with a maximum of
4 elements.

Can you please give me a hint as how I can investigate this further, as all
I have is a ValueError without any other trace information?







*code.py output:Traceback (most recent call last):  File "code.py", line
130, in <module>  File "code.py", line 73, in __init__ValueError: Code done
running.*

Thanks!!

**Comment by dhalbert** [comment]
Try `deque((), 4)`. The MicroPython code does not support initialization, and only allows an empty tuple, not an empty list.

**Comment by jftheoret** [comment]
Excellent, thank you!

**Comment by polygnomial** [comment]
I built pycubed_v05 (it's an M4 board with SAMD51J20), with `MICROPY_PY_COLLECTIONS_DEQUE = 1`, but the module is not available in CircuitPython. The `.o` file is missing from the `build/py` folder. I also tried with a couple of other combinations of `MICROPY_PY_COLLECTIONS` etc, but have not gotten it to work. Any suggestions?

**Comment by dhalbert** [comment]
Fjxed by #6474. Still omitted on some very small builds.
