### ISSUE TITLE
Core code crashed hard

### ISSUE THREAD

**Issue by ErlendFj** [adafruit/circuitpython#5739]
### CircuitPython version

```python
Adafruit CircuitPython 7.0.0 on 2021-09-20; Adafruit Feather M4 Express with samd51j19
```

### Code/REPL

```python
USB keept dropping out, plugged in battery and got error message Crash into the HardFault_Handler. Maybe this is a brownout related bug/behaviour?
```

### Behavior

cannot run any code

### Description

You are in safe mode because:
CircuitPython core code crashed hard. Whoops!
Crash into the HardFault_Handler.
Please file an issue with the contents of your CIRCUITPY drive at

### Additional information

How do I get out of safe mode?

**Comment by jerryneedell** [comment]
Press the Reset button or power cycle to get out of safe mode.

**Comment by ErlendFj** [comment]
It drops right back in to safe mode. I will try to format the 'drive' if I can get USB to stay alive for long enough.

**Comment by jerryneedell** [comment]
In safe mode, you can delete you code.py or boot.py if they are causing the problem. You can also erase the file system in safe mode.

**Comment by dhalbert** [comment]
This may be because your code is using lots of NeoPixels or other power-hungry hardware, and the USB power is sagging.

What else is connected besides the Feather M4 Express?

**Comment by ErlendFj** [comment]
Did it, I'm now back to Hello World. I suspect that as I debugged my original code, more and more hardware got powered and I gradually moved into brown-out territory. Will reinforce power supply and try again. Thanks for helping.

**Comment by dhalbert** [comment]
I'm closing this for now, but feel free to discuss this kind of support issue on discord: https://adafru.it/discord or the forums: https://forums.adafruit.com/viewforum.php?f=60.

It is also possible you are exercising a bug that is causing the hard fault. In that case, reopen this or open a new issue, with the specific code that is causing that problem. Thanks.
