### ISSUE TITLE
Update Intro guide to include PyCharm MicroPython REPL

### ISSUE THREAD

**Issue by kattni** [adafruit/circuitpython#574]
Add a page to the Intro guide explaining how to get the REPL working in PyCharm with the MicroPython plugin.

**Comment by kattni** [comment]
Guide page is published. However, screenshots are still being updated. Leaving issue open until guide is entirely complete.

**Comment by kattni** [comment]
Screenshots have been updated, guide page here: https://learn.adafruit.com/welcome-to-circuitpython/pycharm-and-circuitpython. Blog post about update has been published here: https://blog.adafruit.com/2018/02/02/guide-update-get-connected-to-the-repl-using-pycharm/

All set to go!

**Comment by pmcanseco** [comment]
Hey there, the learn.adafruit.com link is broken, but the blog post is still up. What's the corrent learn.adafruit.com link?

**Comment by siddacious** [comment]
@pmcanseco both of the links above work for me as does the one in this blog post:
https://blog.adafruit.com/2018/02/02/guide-update-get-connected-to-the-repl-using-pycharm/

Are you talking about a different link? If so please paste it here.

**Comment by ladyada** [comment]
@kattni made it private because it stopped working (i think?)

**Comment by kattni** [comment]
I removed the page because it never really worked properly. It was inconsistent and for me, at least, required deleting all of my settings to get it to work each time. It was never designed to work with CircuitPython, it was designed to work with MicroPython, so it provides a lot of features that are irrelevant to CP such as flashing the board.

If you wish to access the REPL from PyCharm, consider using the built in terminal and `screen` to connect to the serial console/REPL.
