### ISSUE TITLE
remove RTD 'stable' version

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#576]
there's some old rev documentation in RTD ? not sure whats up but

https://circuitpython.readthedocs.io/en/stable/shared-bindings/touchio/TouchIn.html

is not the same as

http://circuitpython.readthedocs.io/en/2.x/shared-bindings/touchio/TouchIn.html

e.g. **raw_value** and **threshold** are missing from 'stable'

here's what it indexes

https://readthedocs.org/projects/circuitpython/

also, if possible, maybe have warnings on the other, deprecated APIs? e.g. http://circuitpython.readthedocs.io/en/1.x/shared-bindings/touchio/TouchIn.html
(not sure if RTD supports it)

**Comment by tannewt** [comment]
Stable is now deactivated but the link still works. The version bar is red. Want that for 1.x as well?

**Comment by ladyada** [comment]
yes please make 1.x red

**Comment by willingc** [comment]
@tannewt You should be able to remove stable from displaying at all through the RTD UI. You should be able to activate/deactivate each build as needed. If you send me screenshots of the UI settings, I can see the config.

You can add warnings on the top of files by using [`rst_prolog`](http://www.sphinx-doc.org/en/stable/config.html#confval-rst_prolog). You may need to write a bit of code in conf.py to select a subset of source docs if desired. [IPython's `conf.py`](https://github.com/ipython/ipython/blob/master/docs/source/conf.py) has examples of its use.

**Comment by tannewt** [comment]
Found it! We "cleaned" the stable copy and deactivated 1.x. Thanks for the tips @willingc!

**Comment by ladyada** [comment]
thanks everyone :)
