### ISSUE TITLE
Consider adding a `storage.format()` to erase and create a fresh filesystem

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#577]
It would be nice to be able to erase and re-create a damaged filesystem from the REPL or a program. Currently on non-Express boards we need to erase all of flash and then reload CircuitPython. On Express boards we have a special Arduino program that erases SPI flash, and then we need to reload CPy.

Something like `storage.format(<filesystem>)` would be helpful. One minor issue is how to specify the filesystem if it's so damaged we don't know what it's named.

Some previous discussion: https://github.com/adafruit/circuitpython/issues/386#issuecomment-356731896 ff.

**Comment by tannewt** [comment]
Could we specify it by mount point? That's consistent with remount I
believe.

**Comment by dhalbert** [comment]
The question I had was whether we can identify the mount point name if it's not mountable due to corruption. But I haven't looked at the code yet.

**Comment by tannewt** [comment]
Ah good point! We could hard code it but that'd be a bit weird.

Have any other ideas? We could fake /dev/disk/* but thats probably overkill.
