### ISSUE TITLE
add  driver for STMPE610 

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#581]
Add a driver for the resistive touch screen stmpe610.  You can assign this to me.

**Comment by ladyada** [comment]
hi! yep this is a good idea :) i did 'FT62xx' called "FocalTouch" 
there's *two* interfaces i2c and spi but we tend to use SPI
and SPI is *wierd* on the STMPE is the 'polarity' depends on startup conditions. so you might end up in MODE1
https://github.com/adafruit/Adafruit_STMPE610/blob/master/Adafruit_STMPE610.cpp#L104

**Comment by ladyada** [comment]
for the return values, i think a dict with 'x' 'y' and 'pressure' might best
https://github.com/adafruit/Adafruit_CircuitPython_FocalTouch/blob/master/adafruit_focaltouch.py#L96
that way its somewhat compatible with focaltouch?

**Comment by jerryneedell** [comment]
Thanks for the pointers. I’m looking forward to getting this going.

**Comment by jerryneedell** [comment]
Just a quick update - Making progress on this. I have the basics working for SPI and I2C.  Patterned after FocalTouch as suggested and I have the basic "paint" demo working with a 2.4inch TFT. Lots of clean-up/tweaking to do.
Still have to deal with the occasional SPI "mode" issue. Seem like just retrying usually gets it "right".

**Comment by ladyada** [comment]
sounds great!

**Comment by jerryneedell** [comment]
done
