### ISSUE TITLE
Compiled the Seeed_XIAO_nRF52840_Sense board is wrong start address

### ISSUE THREAD

**Issue by 0hotpotman0** [adafruit/circuitpython#5814]
Hi I compile the Seeed_XIAO_nRF52840_Sense board is work on my local, coz I add the SOFTDEV_VERSION=7.0.1 in behind the "make BOARD=...SOFTDEV_VERSION=7.0.1",          I think I downloaded that board from the Circuitpython web one does not add "SOFTDEV_VERSION=7.0.1", It cause the start address wrong.

![image](https://user-images.githubusercontent.com/47217650/148319468-902bd1e5-cd81-4bed-bd08-ee981b082fb2.png)

I think the system build the uf2 is the default make BOARD=...,   how can I make it to add SOFTDEV_VERSION=7.0.1 behind the make BOARD=...

How can I solve this case, please give me some advice, thank you.

**Comment by 0hotpotman0** [comment]
If build the board without the "SOFTDEV_VERSION=7.0.1", the start address will be 0x26000

**Comment by tannewt** [comment]
Have you tried setting `SOFTDEV_VERSION=7.0.1` in `ports/nrf/boards/Seeed_XIAO_nRF52840_Sense/mpconfigboard.mk`? I think that should override the setting from `mpconfigport.mk`.

**Comment by 0hotpotman0** [comment]
Hi @tannewt   
Where can I add "SOFTDEV_VERSION=7.0.1", 

Can I add behind the "USB_PRODUCT = "Seeed XIAO nRF52840 Sense"
![image](https://user-images.githubusercontent.com/47217650/148531112-c6feec04-8e7c-4e39-81e6-c111ef7d9516.png)

**Comment by tannewt** [comment]
I think it can go anywhere in that file. It's included by the `Makefile` before the port version.

**Comment by dhalbert** [comment]
Closing this for now. Please reopen if you are still having trouble.
