### ISSUE TITLE
pulseio module missing from Adafruit Trinket M0

### ISSUE THREAD

**Issue by pmdevita** [adafruit/circuitpython#5821]
### CircuitPython version

```python
Adafruit CircuitPython 7.1.0 on 2021-12-28; Adafruit Trinket M0 with samd21e18
Board ID:trinket_m0
```

### Code/REPL

```python
import pulseio
```

### Behavior

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'pulseio'
```

### Description

Between versions 6 and 7, support for pulseio was removed from the Adafruit Trinket M0. You can also see it between the module support matrix pages for [version 6](https://circuitpython.readthedocs.io/en/6.3.x/shared-bindings/support_matrix.html) and [version 7](https://circuitpython.readthedocs.io/en/7.0.x/shared-bindings/support_matrix.html).

Is this a mistake? I'd like to update but I need `pulseio.PulseOut` to get the ir_remote library to talk to PWMOut.

**Comment by dhalbert** [comment]
We removed `pulseio` from the smallest builds (e.g. Trinket M0) to allow room for other features, most notably dynamic USB descriptors: see #4696. It is still available on certain M0 builds. `pwmio.PWMOut` is still available, but you are now out of luck for ir_remote on Trinket -- sorry. You could do a custom build or just continue to use 6.3.0.
