### ISSUE TITLE
ESP32-S3-DevKitC-1-N8R8

### ISSUE THREAD

**Issue by prplz** [adafruit/circuitpython#5824]
The `espressif_esp32s3_devkitc_1` board definition does not work with the N8R8 devkit because it uses octal psram. I was able to get it working by coping the sdkconfig and some never_reset pins from `espressif_esp32s3_box` board.

I opened an issue instead of a PR because there are decisions to be made about how to name and manage these different variants (more discussion at #5678).

So far the boards from espressif are:
- ESP32-S3-DevKitC-1-N8: 8M flash, no psram
- ESP32-S3-DevKitC-1-N8R2: 8M flash, 2M quad psram, can be autodetected (#5678)
- ESP32-S3-DevKitC-1-N8R8: 8M flash, 8M octal psram, needs different sdkconfig and never_reset pins
- ESP32-S3-DevKitC-1-N16R8V: 16M flash, 8M octal psram (not sure about this one, aliexpress special?)

**Comment by tannewt** [comment]
I think our naming should just follow the N16R8V style suffixes.

**Comment by tannewt** [comment]
The V is flash voltage. We shouldn't need a different build for it.

![Screenshot 2022-01-13 at 13-58-59 esp32-s3_datasheet_en pdf](https://user-images.githubusercontent.com/52649/149415676-8bd27414-16fb-4b84-8625-b5f41d15cfee.png)

**Comment by prplz** [comment]
> The V is flash voltage. We shouldn't need a different build for it.

It would still need `CIRCUITPY_ESP_FLASH_SIZE` though right?

Also if [this Amazon page](https://www.amazon.com/Espressif-ESP32-S3-DevKitC-1-N16R8V-Development-Board/dp/B09MFC7D23) is correct, it has octal flash, I'm not sure if that requires some more config changes.

**Comment by tannewt** [comment]
Ya, we'd need flash size because it controls partition layout.

The [datasheet for the modules](https://www.espressif.com/sites/default/files/documentation/esp32-s3-wroom-1_wroom-1u_datasheet_en.pdf) says it's only QSPI.
