### ISSUE TITLE
ulab documentation mentions nonexistent `ulab.spectrum`

### ISSUE THREAD

**Issue by Thynix** [adafruit/circuitpython#5833]
At least as of `Adafruit CircuitPython 7.1.0`, places like [`ulab.numpy.fft`](https://circuitpython.readthedocs.io/en/latest/shared-bindings/ulab/numpy/fft/index.html) documentation refer to a nonexistent "spectrum" function:

> See also ~ulab.extras.spectrum, which computes the magnitude of the fft, rather than separately returning its real and imaginary parts.

I haven't been able to figure out whether it's supposed to exist, or its removal was intentional. 6.3 had the similarly-named [spectrogram](https://circuitpython.readthedocs.io/en/6.3.x/shared-bindings/ulab/fft/index.html#ulab.fft.spectrogram), which has since been removed.

**Comment by tannewt** [comment]
@v923z and @jepler

**Comment by v923z** [comment]
Indeed, this is a very or relic, and the reference should be replaced by `scipy.signal.spectrogram`. I'll take care of it.

**Comment by tekktrik** [comment]
Not sure how to PR over to what seems to be the commit CircuitPython is using, but I submitted https://github.com/v923z/micropython-ulab/pull/522 to the base repo for this.

**Comment by tekktrik** [comment]
Okay, the fix should be merged into master for 8.0.0!

**Comment by dhalbert** [comment]
Fixed.
