### ISSUE TITLE
Release stubs to pypi only when a release is done

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#5838]
Right now the circuitpython stubs are released to pypi on every merge build. This seems excessive, and generates a lot of pre-releases with strange version numbers in pypi: https://pypi.org/project/circuitpython-stubs/#history. I thinik it would make more sense to release the stubs to pypi only when we actually do a release, in `create_website_pr.yml`, which we might rename to `release_tasks.yml` or something like that).

Is there a good reason for doing the stub releases so frequently that I am missing?

![image](https://user-images.githubusercontent.com/2847802/149010657-85e0d032-4971-46be-a6c7-be2c30b9f1cd.png)

**Comment by FoamyGuy** [comment]
updating the stubs for each release instead of every merge sounds sufficient to me. It's always possible to build the in-between versions locally with make so folks can still access them if they do have the need for it.
