### ISSUE TITLE
Validate high priority drivers for 3.0 release

### ISSUE THREAD

**Issue by tdicola** [adafruit/circuitpython#584]
This is an issue to track what drivers have been validated for the 3.0 release.  In discussion on 1/5/18 we decided this is an important release criteria to gate a 3.0 release--validating popular drivers that exercise many code paths.  In particular with 3.0 we have some big changes to memory management and numeric representation/range so validation of drivers that deal with those issues is a priority.

A few to consider:
- Basic I2C usage: BMP280 temperature/pressure.
- [x] Metro M0
- [x] Metro M4
- Basic SPI usage: BMP280 in SPI mode.
- [x] Metro M0
- [x] Metro M4
- Basic bitbang / pulse IO: DHT sensors
- [x] Metro M0 with DHT11
- [x] Metro M4 with DHT11
- Large numbers: SI5351 clock generator (tested with a SW radio)
- [x] Metro M0
- [x] Metro M4
- Other interesting ones: RFM69 radio (already tested by various CircuitPython helpers, who fixed driver bugs)
- [x] M0
- [x] M4

[note: checkboxes must be at first level of list; otherwise checking them off doesn't work properly]

**Comment by ladyada** [comment]
- Multiple SPI devices: TFT FeatherWing (my go-to demo is drawing a bitmap from disk to TFT but a 'touch paint' demo does STMPE + TFT)
- Clock-stretch I2C: BNO055
- framebuf: OLED
- Bi-directional UART: GPS with changing settings via NMEA sentences

**Comment by dhalbert** [comment]
Did a bunch of testing (see checkboxes). Edited some of the tests above (no, I did not test all the Featherwings, just some representative ones0. @kattni: I think the CPX testing is basically done, right? Maybe we can close this.

**Comment by tannewt** [comment]
Sounds like we can close this. @dhalbert want to do the honors?

**Comment by kattni** [comment]
Was `pulsein` and `pulseout` tested on CPX?

**Comment by dhalbert** [comment]
I'll test CPX IR with some existing Learn Guide code.

**Comment by dhalbert** [comment]
All tested!
