### ISSUE TITLE
nRF52: Rename pins to match nRF conventions and DK silk

### ISSUE THREAD

**Issue by arturo182** [adafruit/circuitpython#588]
I think we should rename the pins to PX_YY instead of PAYY and PBYY, so we can match the naming used by Nordic and the silkscreen on the DKs, this issue was also discussed in https://github.com/adafruit/circuitpython/pull/575#issuecomment-362990100

If it's no problem, I can be assigned to this issue.

**Comment by microbuilder** [comment]
I'm OK with this personally.

**Comment by tannewt** [comment]
Sounds good to me!

**Comment by arturo182** [comment]
Fixed in #617

**Comment by microbuilder** [comment]
Thanks. Just waiting for the automated tests to run and I'll have a look at this.

**Comment by microbuilder** [comment]
Closed via #617
