### ISSUE TITLE
nRF52: Clean up examples

### ISSUE THREAD

**Issue by arturo182** [adafruit/circuitpython#590]
It seems some of the examples in the nrf port are not valid anymore, for example the seeed tft one uses framebuf and machine, neither of those modules is available in the port.

Shouldn't the examples be better structured, the ones in the root directory should work on "all" supported ports, the ones inside the port directory should work on all boards that port supports and examples inside a board directory should be board specific and only work on that one (for example if some boards have buttons and others don't).

**Comment by tannewt** [comment]
Yes! Examples in the repo aren't critical because we have detailed tutorials and how-tos on https://learn.adafruit.com.

**Comment by tannewt** [comment]
This done?

**Comment by arturo182** [comment]
No yet, waiting for the cleanup to be done so I can write proper examples and test them with the new code :)

**Comment by tannewt** [comment]
@dhalbert has done this:
* https://github.com/adafruit/Adafruit_CircuitPython_BLE/
* https://github.com/adafruit/Adafruit_CircuitPython_BluefruitConnect
* https://learn.adafruit.com/circuspython-jump-through-hoops-with-bluetooth-le
