### ISSUE TITLE
PulseIn not working on ESP32-S3

### ISSUE THREAD

**Issue by DavePutz** [adafruit/circuitpython#5909]
### CircuitPython version

```python
Adafruit CircuitPython 7.2.0-alpha.1-199-gbed724fc1 on 2022-01-22; ESP32-S3-DevKitC-1-N8 with ESP32S3
```

### Code/REPL

```python
>>> import dht_simpletest
DHT sensor not found, check wiring
DHT sensor not found, check wiring
DHT sensor not found, check wiring
```

### Behavior

Using the dht_simpletest.py script from library examples; no pulses are ever seen. The script works on an ESP32-S2. 

### Additional information

The issue looks to be the use of RMT channels on the ESP32. Looking at the espressif docs (https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/peripherals/rmt.html and https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/api-reference/peripherals/rmt.html ) it seems that the ESP32-S2 has 4 RMT channels which can be used for either transmit or receive. The ESP32-S3, however, has 8 RMT channels with channels 0-3 used for transmitting and 4-7 used for receiving. Since peripherals_find_and_reserve_rmt() returns the lowest unused channel it gives pulsein a channel of 0, and as a result the ring buffer never sees any received pulses. I will look at some possible fixes.

**Comment by tannewt** [comment]
Fixed by #5912
