### ISSUE TITLE
L3GD20H

### ISSUE THREAD

**Issue by PTLindstrom** [adafruit/circuitpython#595]
tannewt asked me to put a "lib request" in on the two chips used in the Adafruit 9dof breakout

**Comment by tannewt** [comment]
Chip is on: https://www.adafruit.com/product/1247 and https://www.adafruit.com/product/1120

**Comment by tannewt** [comment]
And discontinued: https://www.adafruit.com/product/1714 and https://www.adafruit.com/product/1604

**Comment by ladyada** [comment]
dastels wrote one for us, please try it?
https://github.com/adafruit/Adafruit_CircuitPython_LSM303

**Comment by PTLindstrom** [comment]
wow, that was quick.... I'll see if I can make it work

**Comment by ladyada** [comment]
thanks! if it doesn't please open an issue on that repo and we'll see what it could be!

**Comment by tannewt** [comment]
We can close this. There is a separate issue for the L3GD20 (#596).
