### ISSUE TITLE
L3GD20 - a 3-axis gyroscope

### ISSUE THREAD

**Issue by PTLindstrom** [adafruit/circuitpython#596]
tannewt asked me to put a "lib request" in on the two chips used in the Adafruit 9dof breakout 
here is the 2nd chip

**Comment by tannewt** [comment]
Chip is on: https://www.adafruit.com/product/1032

**Comment by mrmcwethy** [comment]
I will attempt to convert Adafruit_L3GD20 -> Adafruit_CircuitPython_L3GD20.

**Comment by mrmcwethy** [comment]
#https://github.com/mrmcwethy/Adafruit_CircuitPython_L3GD20

I have a library in my area which I would like to start pushing thru into the bundle.

**Comment by tannewt** [comment]
@mrmcwethy I've forked it and you should be able to add it to the bundle. https://github.com/adafruit/Adafruit_CircuitPython_L3GD20 Thanks!

**Comment by ladyada** [comment]
closing, we tested it, thanx!
