### ISSUE TITLE
Broken "edit on github" links in published content

### ISSUE THREAD

**Issue by larsks** [adafruit/circuitpython#5965]
### CircuitPython version

```python
N/A
```

### Code/REPL

```python
N/A
```

### Behavior

N/A

### Description

The "Edit on Github" links for core module documentation at https://circuitpython.readthedocs.io/en/latest/ appear to be broken. For example, on any of:

- https://circuitpython.readthedocs.io/en/latest/shared-bindings/countio/index.html
- https://circuitpython.readthedocs.io/en/latest/shared-bindings/board/index.html
- https://circuitpython.readthedocs.io/en/latest/shared-bindings/onewireio/index.html

...and presumably all the others, the "Edit on GitHub" link leads to a 404 error.

**Comment by tannewt** [comment]
We're tracking this here:  #5763
