### ISSUE TITLE
ESP32S3 Sleep Behaviour using PinAlarm

### ISSUE THREAD

**Issue by atctwo** [adafruit/circuitpython#5973]
### CircuitPython version

```python
Adafruit CircuitPython 7.2.0-alpha.1-278-ga04cd6444 on 2022-02-02; ESP32-S3-DevKitC-1-N8R2 with ESP32S3
```

### Code/REPL

```python
import alarm
import board
import digitalio
import neopixel
import time

np = neopixel.NeoPixel(board.NEOPIXEL, 1)

while True:
    np[0] = (50, 50, 50)
    time.sleep(1)
    np[0] = (0, 0, 0)

    # Create a an alarm that will trigger 5 seconds from now.
    time_alarm = alarm.time.TimeAlarm(monotonic_time=time.monotonic() + 5)
    pin_alarm = alarm.pin.PinAlarm(pin=board.IO2, value=False, pull=True)

    # Do a light sleep until the alarm wakes us.
    print("sleeping...")

    alarm.light_sleep_until_alarms(pin_alarm, time_alarm)
    #alarm.exit_and_deep_sleep_until_alarms(time_alarm, pin_alarm)

    print("woken up by", alarm.wake_alarm)
```

### Behavior

There are no error messages, although PinAlarm doesn't appear to wake the ESP32 up.  The ESP32 always prints "sleeping..." and goes into sleep mode with no issues.  After sleeping, when using light sleep, and the button connected to the pin is pressed, nothing happens.  When using deep sleep, the "fake deep sleep" message on the serial console appears when the button is pressed, then it stays in sleep mode (the code doesn't re-run, and nothing else happens).  The message it prints is:
```
Press any key to enter the REPL. Use CTRL-D to reload.
Pretending to deep sleep until alarm, CTRL-C or file write.
```

### Additional information

- the last commit that sleep seems to work without problems for me is 993e51e5cc0a74bc232c05f9089c2d04886fecf6
- the next commit after that (f6cf15de434e77a4eb2f2846ef57da174372e62b) crashes the ESP32S3 on boot, which happens for each commit until 8bae6af12a21577170b89eff322d081dfd628c89, on which the sleep problems occur
- I guess whatever causes this problem was introduced between 993e51e5cc0a74bc232c05f9089c2d04886fecf6 and 8bae6af12a21577170b89eff322d081dfd628c89?
- I'm using switches with external pull-down resistors, but i've also tried this with internal pull-up resistors
- From what I can tell, disconnecting USB from a computer / preventing "fake sleep" doesn't help.
- The example above uses a TimeAlarm at the same time as PinAlarm.  TimeAlarm wakes the ESP32 up fine, and PinAlarm doesn't work whether a TimeAlarm is set up or not
  - when I was testing the code with a PinAlarm and a TimeAlarm together, and the pull ups on the PinAlarm incorrectly configured (with internal pullups and external pull downs), TimeAlarm did some strange things. It wouldn't wake up at the specified time, but when the PinAlarm pin was pressed, it wouldn't wake up straight away, but would then wake up at the specified time (or immediately if that time has already passed)

**Comment by tannewt** [comment]
Looks like the wake from pin failure in light sleep or fake deep sleep was an IDF bug that has been fixed: https://github.com/espressif/esp-idf/commit/41e452e7d8aacb0c6e2aea5b18fe9d6e2c334b9c

I'll update the IDF to fix it.

Deep sleep is broken as described in #6090
