### ISSUE TITLE
os.utime() 

### ISSUE THREAD

**Issue by bludin** [adafruit/circuitpython#5978]
Currently, there seems to be no way to set the modified time or (less importantly) the accessed time of a file in circuitpython, because the os library is lacking utime(). Could this or an equivalent be added?

**Comment by tannewt** [comment]
https://docs.python.org/3/library/os.html#os.utime

This should be easy to add because FATFS has a corresponding function: https://github.com/adafruit/circuitpython/blob/a672ee6da50def65e5544ee24bcf960236d985a2/lib/oofatfs/ff.h#L299
