### ISSUE TITLE
I2C pins on Lilygo TTGO T8 ESP32_S2 V1.1

### ISSUE THREAD

**Issue by morgulbrut** [adafruit/circuitpython#6008]
While testing my new board I found out `board.SDA` and `board.SCL` are not yet defined.

To be fair I didn't also find them in the official pinout diagram from Lilygo.

**Comment by prplz** [comment]
ESP32 can use any output capable pins for I2C

**Comment by dhalbert** [comment]
We don't define `board.SCL` and `board.SDA` pin names unless there are pins labeled as such on the board, or there are very clearly defined defaults.

**Comment by morgulbrut** [comment]
Thanks for the clarification.
