### ISSUE TITLE
Enable _uasyncio

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#6042]
`_uasyncio` is not used for asyncio, right now because the `_uasyncio` implementation of `Task` does not provide`__await___()`. Our internal implementation of `async/await` (done by @WarriorOfWire) requires that. Otherwise code is going to fail. I had to add `__await__()` in the Python version in a couple of places:
https://github.com/adafruit/Adafruit_CircuitPython_asyncio/blob/28ef812f14ef1fde1036eb83a4878bd14aa9a67d/asyncio/task.py#L152
https://github.com/adafruit/Adafruit_CircuitPython_asyncio/blob/28ef812f14ef1fde1036eb83a4878bd14aa9a67d/asyncio/core.py#L52-L53

I started to add `__await__()`, but because `__iter__()` is provided in a special way, I had not yet figured out how to make it work, and so did not use `_uasyncio` initially.

In addition, I would like to rename `_uasyncio` to `_asyncio`, but that is minor.

_Originally posted by @dhalbert in https://github.com/adafruit/circuitpython/pull/6041#pullrequestreview-884596976_

See #6041 for initial work on this (thanks @t-ikegami).

Tagging @WarriorOfWire for interest as well.

**Comment by t-ikegami** [comment]
I have reopened https://github.com/adafruit/circuitpython/pull/6041, where `__await__` method is supplemented to Task class.

**Comment by dhalbert** [comment]
Fixed by #6041.
