### ISSUE TITLE
translations: investigate going full zlib

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#6059]
I noticed that the size of `uzlib` is 3232 bytes when built as an _extmod_ for armv7m. This made me curious, as a ballpark figure would we be better off in terms of code size zlib-compressing the messages.

zlib-compressing messages _individually_ is not going to work as well, but compressing the concatenation of all messages + offsets to find each message in the decompressed string could work.

Currently we have (numbers for adafruit_rotary_trinkey_m0, russian translation):
 * total messages = 272
 * huffman + dictionary decoder = ??? bytes of code
 * overhead of tables (huffman counts, dictionary entries, etc) = 3855 bytes data
 * compressed messages themselves = 5242 bytes data
 * total compression data = 9307

Compare to
 * zilb.compress("".join(messages).encode('utf-8'), 9) = 4676
 * 2-byte lengths or offsets for each message = 544
 * uzlib decompressor itself = 3232
 * total = 8452

So it looks like you come out ahead, even before accounting for the huffman code that can be removed.

Additionally, I think this would make it easier to switch out the message catalog by just concatenating it on to the end of flash, it becomes just a table of offsets + a single zlib stream.

However, it would be slower to throw exceptions, because to read the 272nd message would require decompressing ALL messages. Also, more memory allocations internal to uzlib would be needed while decompressing a message, so it could fail under a wider range of circumstances.

**Comment by tannewt** [comment]
I'm ok with it being slower to print the exception. I doubt it'd be painfully slow. We could sort the string so that non-Exception messages go first.

**Comment by jepler** [comment]
I went ahead and implemented this, but contrary to my above calculations it ended up bigger.  You can check out the code: https://github.com/adafruit/circuitpython/compare/main...jepler:compress-errors-zlib?expand=1

adafruit_rotary_trinkey_m0 (english translation) had 5388 bytes free in flash before the change, but only 4918 bytes free after.

I didn't test on HW but I did make sure that messages seemed to be printed properly from within the unix port.

I'm also concerned about the amount of runtime memory needed, probably about 1.5kB.

There might be something obvious wrong with my approach, so I'll leave this open in case someone cares to discover it :wink:

**Comment by jepler** [comment]
The amount of runtime memory is even bigger than that, about 2.5kB. the uzlib structure is 1.5kB and the "dict" is 1kB.

I threw a few more tricks at it, and even then `ja` was bigger in total flash size. (tricks that mean the auxiliary idea that maybe the translation can just be appended to the bin wouldn't work, either)
```
before - 3776 (ru) 5388 (en) 4072 (ja)
after -  4229 (ru) 5429 (en) 3970 (ja)
```
before = 918145f76
after = c6b68a93a 

I think this isn't going to end up working out, despite my hopes. Part of the reason this isn't working out is that my initial estimates were based on default zlib compression, but that uses a "dict" of 32kB. Compression ratios go down as the size of the dict decreases, but RAM equal to the dict size is needed. For instance, on ja the 1kB dict gives 5500 bytes output size while the 32kB dict gives 4305 bytes.
