### ISSUE TITLE
readthedocs sphinx doc is not always including `*` from signatures

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#6072]
Asterisks in Sphinx Python type signatures are not showing up in the generated doc, but only sometimes:
`usb_cdc.c:`
```c
//| def enable(*, console: bool = True, data: bool = False) -> None:
//|     """Enable or disable each CDC device. Can be called in ``boot.py``, before USB is connected.
```
![image](https://user-images.githubusercontent.com/2847802/154863472-c7994cc1-cb79-4645-876b-4135c68d98ba.png)

But sometimes it shows up:
`SPI.c:`
```c
//|     def configure(self, *, baudrate: int = 100000, polarity: int = 0, phase: int = 0, bits: int = 8) -> None:
//|         """Configures the SPI bus. The SPI object must be locked.
```
![image](https://user-images.githubusercontent.com/2847802/154863302-2b2b86d7-3263-4309-a291-75d58e0b86c8.png)

**Comment by dhalbert** [comment]
This is some kind of problem with `autoapi` dropping `*` in signatures; I can see it in the autoapi output. But I don't know why it's doing that, and I don't see any filed issues complaining about this yet. I have a simple test case.

**Comment by dhalbert** [comment]
I reproduced this problem with a simple example and opened an an autoapi issue about this: https://github.com/readthedocs/sphinx-autoapi/issues/328

**Comment by dhalbert** [comment]
This is still broken in Sphinx 5.0.0.

**Comment by jepler** [comment]
We fixed this in https://github.com/adafruit/circuitpython/pull/6449 for ourselves.
