### ISSUE TITLE
Please consider using new official I2C terminology.

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#6087]
@tannewt noticed that in [I2C-bus specification version 7.0 (October 2021)](https://www.nxp.com/docs/en/user-guide/UM10204.pdf), official new names were given: Target and Controller replace the older deprecated terms.
![image](https://user-images.githubusercontent.com/1517291/155577300-b12639e9-1a7e-4bbc-b4fe-804142483992.png)

This would potentially include renaming (again) the I2CPeripheral class, as well as other code and documentation changes. Since renaming a class is an incompatibility, I've marked this for the 8.0.0 milestone initially.

**Comment by tannewt** [comment]
I think it's worth making the peripheral and target naming available in 8.x and then only target in 9.x.
