### ISSUE TITLE
Math functions from the documentation are missing

### ISSUE THREAD

**Issue by Kuratius** [adafruit/circuitpython#6108]
### CircuitPython version

```python
Adafruit CircuitPython 7.2.0 on 2022-02-24; Adafruit Macropad RP2040 with rp2040
Board ID:adafruit_macropad_rp2040
```

### Code/REPL

```python
import math
math.erf(1)
```

### Behavior

math.erf(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'erf'

### Description

I tried to call erf by doing
import math
math.erf(1) and the call fails.
This function is present in the documentation at https://docs.circuitpython.org/en/latest/shared-bindings/math/index.html  and also in the source code in this repo.

### Additional information

dir(math) also doesnt show this function.

**Comment by dhalbert** [comment]
We don't have `MICROPY_PY_MATH_SPECIAL_FUNCTIONS` turned on, which add `erf`, `erfc`, `gamma`, and `lgamma`. It is a bug in the documentation that they are not noted as possibly being optional.

We can consider turning these one for certain builds. It depends on how much code these add.
