### ISSUE TITLE
Add/fix ReadTheDocs badge

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#613]
We had a bad cookiecutter for a while that added extra lines into the `README.rst` in the ReadTheDocs badge like this:

```rst
.. image:: https://readthedocs.org/projects/adafruit-circuitpython-vcnl4010/badge/?version=latest

    :target: https://circuitpython.readthedocs.io/projects/vcnl4010/en/latest/

    :alt: Documentation Status
```

It should be:

```rst
.. image:: https://readthedocs.org/projects/adafruit-circuitpython-vcnl4010/badge/?version=latest
    :target: https://circuitpython.readthedocs.io/projects/vcnl4010/en/latest/
    :alt: Documentation Status
```

These are super simple changes that are great practice for using GitHub. Feel free to ask questions here as needed.

These repos need a look:

- [x] https://github.com/adafruit/Adafruit_CircuitPython_VCNL4010
- [x] https://github.com/adafruit/Adafruit_CircuitPython_Fingerprint
- [x] https://github.com/adafruit/Adafruit_CircuitPython_APDS9960
- [x] https://github.com/adafruit/Adafruit_CircuitPython_DRV2605
- [x] https://github.com/adafruit/Adafruit_CircuitPython_SGP30
- [x] https://github.com/adafruit/Adafruit_CircuitPython_DS18X20
- [x] https://github.com/adafruit/Adafruit_CircuitPython_AVRprog
- [x] https://github.com/adafruit/Adafruit_CircuitPython_FocalTouch
- [x] https://github.com/adafruit/Adafruit_CircuitPython_MCP9808
- [x] https://github.com/adafruit/Adafruit_CircuitPython_VL6180X
- [x] https://github.com/adafruit/Adafruit_CircuitPython_OneWire
- [x] https://github.com/adafruit/Adafruit_CircuitPython_Thermal_Printer
- [x] https://github.com/adafruit/Adafruit_CircuitPython_DS2413
- [x] https://github.com/adafruit/Adafruit_CircuitPython_VEML6070
- [x] https://github.com/adafruit/Adafruit_CircuitPython_MAX9744
- [x] https://github.com/adafruit/Adafruit_CircuitPython_MCP4725
- [x] https://github.com/adafruit/Adafruit_CircuitPython_SSD1306
- [x] https://github.com/adafruit/Adafruit_CircuitPython_SHT31D
- [x] https://github.com/adafruit/Adafruit_CircuitPython_TLC5947
- [x] https://github.com/adafruit/Adafruit_CircuitPython_Register

Part of #566

**Comment by brentru** [comment]
@tannewt Note - the [SSD1306 repo](https://github.com/adafruit/Adafruit_CircuitPython_SSD1306) 404's [on its ReadTheDocs page](https://circuitpython.readthedocs.io/projects/ssd1306/en/latest/)

**Comment by tannewt** [comment]
Thats the right link for ssd1306 but the build itself isn't set up right. The build output is here: https://readthedocs.org/projects/adafruit-circuitpython-ssd1306/builds/6661205/

I'd expect register to be at https://circuitpython.readthedocs.io/projects/register/en/latest/

**Comment by mrmcwethy** [comment]
@ tannewt @brentru I believe this issue can now be closed.

**Comment by tannewt** [comment]
Great job @mrmcwethy and @brentru !
