### ISSUE TITLE
ESP32-S2/S3 unable to do 3-wire SPI

### ISSUE THREAD

**Issue by skerr92** [adafruit/circuitpython#6141]
### CircuitPython version

```python
Adafruit CircuitPython 7.2.0 (local dirty build) for ODT Branch ESP32-S2
```

### Code/REPL

```python
import board, busio, digitalio

cs = digitalio.DigitalInOut(board.D4)
cs.direction = digitalio.Direction.OUTPUT
cs.value = True

spi = busio.SPI(board.SCK, MISO=board.MISO) # SCK = GPIO35 MISO = GPIO37

while not spi.try_lock():
     pass

spi.configure(baudrate=5000000, phase=0, polarity=0)
cs.value = False
result = bytearray(4)
spi.readinto(result)
cs.value = True
print(result)
```

### Behavior

Returns a `ValueError: No MOSI Pin` on the `spi.readinto(result)` line. Anecdata tested on an ESP32-S3 Dev Kit and it returns the same ValueError. Dan tested on other CircuitPython devices like those that use Atmel and nRF chips without issue. It appears to only affect ESP32-S2/S3 devices.

**Comment by ladyada** [comment]
fyi you can also use bitbangio while-u-wait !
