### ISSUE TITLE
Put _bleio back in for Matrix Portal M4 build

### ISSUE THREAD

**Issue by caternuson** [adafruit/circuitpython#6152]
### CircuitPython version

```python
Adafruit CircuitPython 7.2.1 on 2022-03-14; Adafruit Matrix Portal M4 with samd51j19
```

### Code/REPL

```python
import _bleio
```

### Behavior

```python
Adafruit CircuitPython 7.2.1 on 2022-03-14; Adafruit Matrix Portal M4 with samd51j19
>>> import _bleio
ImportError: no module named '_bleio'
>>>  
```

### Description

see above

### Additional information

Introduced here:
https://github.com/adafruit/circuitpython/pull/6043

Needed to use ESP32 module for BLE
https://learn.adafruit.com/adafruit-matrixportal-m4/circuitpython-ble

**Comment by dhalbert** [comment]
Fixed by #6154.
