### ISSUE TITLE
7.2.2 Hangs After Thonny Connects On Adafruit RP2040 Feather 

### ISSUE THREAD

**Issue by eightycc** [adafruit/circuitpython#6159]
### CircuitPython version

```python
Adafruit CircuitPython 7.2.2 on 2022-03-15; Adafruit Feather RP2040 with rp2040
```

### Code/REPL

```python
No code or input needed to reproduce the problem.
```

### Behavior

```
Connection lost (read failed: device reports readiness to read but returned no data (device disconnected or multiple access on port?))

Use Stop/Restart to reconnect.
```
This message occurs shortly (<30 seconds) after connecting ```thonny 3.2.7``` to an ```Adafruit RP2040 Feather```, and then the  device hangs. 

### Description

Reverting to ```Adafruit CircuitPython 7.2.1 on 2022-03-14; Adafruit Feather RP2040 with rp2040``` corrects the problem.

**Comment by dhalbert** [comment]
And what is the host computer OS and version of Thonny you are using?

**Comment by tannewt** [comment]
@aivarannamaa FYI. We switched our autoreload a bit and may have broken Thonny.

**Comment by eightycc** [comment]
Seeing the problem on 7.2.2, not seeing it on 7.2.1, Thonny version 3.2.7, Ubuntu 20.04.4 LTS: ```Linux ub2004 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux```.

**Comment by aivarannamaa** [comment]
Unfortunately I'm not able to reproduce this with the exact same setup: Thonny version 3.2.7, Ubuntu 20.04.4 LTS, RP2040 Feather with CP 7.2.2. I also tried Thonny 3.3.13 and RPi Pico with the same result.

I do get this error when I disconnect the USB cable, but this is expected.

**Comment by dhalbert** [comment]
I see this, noted in #6159:

With 7.2.2, ReloadException is printed when a file is written when code.py is not running or does not exist. Reported in #6165, and probably subsumes this.

```py
>>> 
ReloadException: 
>>> 
ReloadException: 
>>> 
ReloadException: 
>>> 
ReloadException: 
>>> 
ReloadException: 
```
