### ISSUE TITLE
Redirect sys.stderr to usb_cdc.data

### ISSUE THREAD

**Issue by bludin** [adafruit/circuitpython#6166]
Is there a way to redirect (or copy) sys.stderr to usb_cdc.data?

**Comment by tannewt** [comment]
No, usb_cdc.data is meant for user controlled output. What are you trying to do?

**Comment by bludin** [comment]
I just had a problem with a program that stalled/crashed when I had the console turned off. So it would have been nice to see the traceback in data. But I found the bug in the meantime (I queried usb_cdc.console.connected when usb_cdc.console didn't exist so I had to change the respective line to` if usb_cdc.console and usb_cdc.console.connected: ...`

**Comment by bludin** [comment]
ah yes. Good idea. Thanks a lot.
