### ISSUE TITLE
PI Pico Problem .UF2

### ISSUE THREAD

**Issue by Dodika00** [adafruit/circuitpython#6171]
### CircuitPython version

```python
Adafruit CircuitPython 7.2.3 on 2022-03-16; Raspberry Pi Pico with rp2040
Board ID:raspberry_pi_pico
```

### Code/REPL

```python
nothing
```

### Behavior

nothing

### Description

when i drag or copy .uf2 file in pi pico its not giving me all files in that i wan't

### Additional information

nothing

**Comment by Borna521** [comment]
Dodika00 you solve your probleme.Can you help me

**Comment by Dodika00** [comment]
> Dodika00 you solve your probleme.Can you help me

i did not solve it yet
