### ISSUE TITLE
Absolute mouse (touchscreen) HID support

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#620]
Good one to do when we do multimedia key support (i believe we just need to craft the report API)

**Comment by dhalbert** [comment]
I did a little research on this. It may be an issue finding report descriptors that will work on all the major platforms. Paul Stoffregen has implemented touchscreen HID support for Teensy. The report descriptor he developed I think appears to work on Windows and Mac without external drivers; it may not work on Linux (or at least Raspbian). Some background here and in other forum posts: https://forum.pjrc.com/threads/32331-USB-HID-Touchscreen-support-needed

**Comment by dhalbert** [comment]
Latent support in #776, but not turned on. Needs more testing: it appears touchscreen and gamepad on the same HID endpoints might conflict on at least some platforms (Linux).  Might need to wait for dynamic HID descriptors. Also current report descriptor (emulating a digitizer with stylus), does not necessarily seem to do the right thing with existing built-in drivers on all platforms.

**Comment by dhalbert** [comment]
Now available via user-defined HID descriptors.

**Comment by ladyada** [comment]
woohoo 3 year old issue :D

**Comment by ATMakersBill** [comment]
While I understand how this solves the problem in theory, is there an example or doc that has the descriptor and hid code to process it?

**Comment by dhalbert** [comment]
Digitizer descriptor that worked on at least some systems:

https://github.com/adafruit/circuitpython/blob/6.3.x/tools/hid_report_descriptors.py#L341-L406

I don't know what Python library I was using with this, if any. I may have just seen whether the OS recognized it, as opposed to trying to send a report.

**Comment by Red-M** [comment]
For extra compatibility, these are the USB descriptors that QEMU/KVM use, https://github.com/qemu/qemu/blob/master/hw/usb/dev-hid.c#L398-L410

**Comment by bitboy85** [comment]
If anyone ends up here by google: I've created an example for absolute mouse here: https://gist.github.com/bitboy85/cdcd0e7e04082db414b5f1d23ab09005

**Comment by hdo** [comment]
Anyone have a working example with CircuitPython 7.0? 
Unfortunately i can't get it working with CircuitPython 6.3 on PICO :-(

**Comment by ThomasAtBBTF** [comment]
I have one and will upload it here over the weekend.
BUT: It works on MacOS but not on IOS !
Did not check Windows and Linux.
I opened a feature request to Apple for making it work also under IOS.

**Comment by hdo** [comment]
That would be very helpful. Thanks.

> I have one and will upload it here over the weekend. BUT: It works on MacOS but not on IOS ! Did not check Windows and Linux. I opened a feature request to Apple for making it work also under IOS.
