### ISSUE TITLE
Add support for hidden vectorio shapes

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/circuitpython#6204]
`vectorio` shapes do not currently support being `hidden` by the group that contains them. 

This sample code illustrates the issue:
```py
import time
import displayio
import terminalio
import vectorio
from adafruit_display_text.bitmap_label import Label
import board

display = board.DISPLAY

main_group = displayio.Group()

palette = displayio.Palette(1)
palette[0] = 0x125690

circle = vectorio.Circle(pixel_shader=palette, radius=25, x=70, y=40)
main_group.append(circle)

rectangle = vectorio.Rectangle(pixel_shader=palette, width=40, height=30, x=105, y=45)
main_group.append(rectangle)

lbl = Label(terminalio.FONT, scale=3, text="Hello Shapes!", anchor_point=(0,0), anchored_position=(100, 100))

main_group.append(lbl)

display.show(main_group)

while True:
    main_group.hidden = not main_group.hidden
    time.sleep(1)
```

When this code runs the vectorio shapes remain visible, while the label that is in the same groups blinks visible and hidden as the loop runs:

https://user-images.githubusercontent.com/2406189/160250634-f846293a-fa65-493e-ad05-f5b8ab6f059c.mp4

I intend to work on a solution for this, creating the issue here to get it documented somewhere and see if anyone else has ideas or input about it.

If I am understanding correctly TileGrid and Group have code like this which allows them to handle the case where they get hidden by their containing Group:
https://github.com/adafruit/circuitpython/blob/fcde108d03cf589362f681e7e5acf6677e4d7be0/shared-module/displayio/TileGrid.c#L354-L357

I believe similar functionality could be implemented for vectorio shapes, maybe somewhere in this function:
https://github.com/adafruit/circuitpython/blob/fcde108d03cf589362f681e7e5acf6677e4d7be0/shared-module/vectorio/VectorShape.c#L316

**Comment by WarriorOfWire** [comment]
If you start the application with the shapes hidden do they draw? It might be sufficient to modify this in the get_refresh_areas method instead. Might be necessary in fact if memory serves me. It would be really nice if this could be supported without adding per-shape memory cost
