### ISSUE TITLE
Consistency in unified sensor driver property naming

### ISSUE THREAD

**Issue by tuupola** [adafruit/circuitpython#622]
To avoid hijacking an [unrelated thread](https://github.com/adafruit/circuitpython/pull/600) I move this here. Currently there is [mixed capitalization](https://github.com/tannewt/circuitpython/blob/09bf06bc6bf4eba0ad03916425ad45ebab9f0025/docs/design_guide.rst#L470-L472) in the design guide concerning unified sensor driver property naming.

Consistency is usually good thing. If everything is lowercased there is no need to remember whether one should use capital letters or not. For example lux might be confusing. Is it acronym or word? Should it be `sensor.lux` or `sensor.LUX`? Also when seeing `sensor.TVOC` one is not really sure if it is a constant or property.

I do not have strong feelings about this, but my choice would be lowercased acronyms `sensor.tvoc` and `sensor.eco2`.

**Comment by tannewt** [comment]
I've been silent on this because I haven't felt super strong about it. I thought about expanding them out (`total_volatile_organic_compound` for example) but then they get really long. Ultimately, I agree with you @tuupola. Switching to lowercase makes sense to me.

**Comment by tannewt** [comment]
@tuupola Would you like to switch them to the lower case version?

**Comment by brentru** [comment]
These two libs to be changed to reflect the move to lowercase (am I forgetting any others which use the TVOC/eCO2 property naming?):
https://github.com/adafruit/Adafruit_CircuitPython_SGP30
https://github.com/adafruit/Adafruit_CircuitPython_CCS811

**Comment by tuupola** [comment]
Had missed this. @tannewt sure, I will check them out.

**Comment by tannewt** [comment]
Thanks @tuupola! Let me know if you need any guidance on how to get it done.

**Comment by dherrada** [comment]
@tuupola I put in a pull request to the [CCS811](https://github.com/adafruit/Adafruit_CircuitPython_CCS811) library and it was accepted. I didn't see any problems with the SGP30 library.

**Comment by tannewt** [comment]
SGP30 is missing properties all together. They should be added.

**Comment by tannewt** [comment]
@mrmcwethy would you be interested in adding eco2 and tvoc properties to the SGP30 driver?

**Comment by mrmcwethy** [comment]
@tannewt I would be happy to add these properies.  I will need to order a sgp30 board.

**Comment by tannewt** [comment]
Go ahead and order one (and other other sensors of interest). I think @brentru may have started the sgp30 work though.

**Comment by tannewt** [comment]
Yes please. I'd name them `baseline_tvoc` and `baseline_co2eq` though. Thanks!

**Comment by tannewt** [comment]
The CCS guide needs to be updated: https://learn.adafruit.com/adafruit-ccs811-air-quality-sensor?view=all#circuitpython-wiring-test

**Comment by brentru** [comment]
@tannewt  will do.

**Comment by brentru** [comment]
Modified the CCS and SGP30 guides to match the naming consistencies.

**Comment by tannewt** [comment]
Awesome! I think this is done then. Please reopen if not.
