### ISSUE TITLE
QTPY ESP32C3 import wifi hangs

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#6221]
executing `import wifi` on the qtpy espc2c3  causes the board to hang
```

Adafruit CircuitPython 7.3.0-beta.0 on 2022-04-01; Adafruit QT Py ESP32C3 with ESP32-C3FN4
>>> 
>>> import wifi

```

It has to be power cycled to regain access.

The WiFi works fine on the esp32c3 devkit board.

edited to add: 
The QTPY ESP32C3 wifi  also works with MicroPython v1.18 using the ESP32C3-usb build

**Comment by RetiredWizard** [comment]
This has not been crashing on my QT Py ESP32C3 board with recent 8.0.0-alpha.1 builds

**Comment by tannewt** [comment]
Ok, closing for now. There's been a lot of churn so I'd expect it's fixed. (Folks have been adding C3 boards too so they must work.)
