### ISSUE TITLE
Wifi/(Fake) Deep Sleep on Feather S2 (BME280)

### ISSUE THREAD

**Issue by patrebert** [adafruit/circuitpython#6232]
This issue was posted on circuitpython forum, Adafruit admin recommended
opening of issue here.
This is running mostly verbatim (some lines commented) the example ( https://learn.adafruit.com/adafruit-esp32-s2-feather/i2c-on-board-sensors) for using deep sleep on the BME280 equipped Adafruit Feather S2 (with 60 second sleep time). It may have happened with previous versions also, but I never caught it while running with the usb console attached. This occurred after quite a few hours of running with no apparent issues.

code.py output:
```
Connected to ATT353a6v8!
IP: 192.168.1.104
Current BME280 temperature: 25.39 C
Current BME280 temperature: 77.78 F
Current BME280 humidity: 27.83 %
Current BME280 pressure: 1001.10 hPa
Current battery voltage: 4.17 V
Current battery percent: 0.0 %
Sending data to AdafruitIO...
Sending request failed

Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.
Pretending to deep sleep until alarm, CTRL-C or file write.
Woken up by alarm.

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Traceback (most recent call last):
File "code.py", line 11, in <module>
MemoryError: Failed to allocate Wifi memory

Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 7.3.0-alpha.0-66-g07f8ceb80 on 2022-03-29; Adafruit Feather ESP32S2 with ESP32S2
>>>
```

code.py source:
```python
# SPDX-FileCopyrightText: 2021 Kattni Rembor for Adafruit Industries
# SPDX-License-Identifier: Unlicense
"""
CircuitPython Adafruit IO Example for BME280 and LC709203 Sensors
"""
import time
import ssl
import alarm
import board
import digitalio
import wifi  <--- LINE 11
```
[sleepy.txt](https://github.com/adafruit/circuitpython/files/8410654/sleepy.txt)

**Comment by ladyada** [comment]
if you're getting `Sending request failed` mabye check your io user/key

**Comment by patrebert** [comment]
Checked my username and password on io.adafruit.com, it matches what I've got in secrets.py. I'm attaching putty.log file. Lots of lines, but the short story is that it shows 264 "Data sent!" messages followed by 267 "Sending request failed" mesages, after which it goes to sleep then gives the "Failed to allocate wifi memory" message when it wakes up ~60 seconds later.
[putty1.log](https://github.com/adafruit/circuitpython/files/8412447/putty1.log)
.

**Comment by ladyada** [comment]
@patrebert what if you disconnect USB REPL so that the board really goes to sleep - does it work then? check io to make sure messages are coming thru. you can reduce the sleep delay to speed up the test

**Comment by patrebert** [comment]
Have restarted with 5 second sleep. It's logging results to io.adafruit.com now.

**Comment by patrebert** [comment]
To feed bme280-temperature-f

**Comment by patrebert** [comment]
I've let the feather run since last post, and it hasn't stopped permanently. However, looking at the feed data on io.adafruit.com, there are some big gaps in reported data. The attached plot shows the time in seconds since the last data point, not sure what exactly it was doing during the substantial gaps. I also had another export to a different feed running in parallel on a qt py that just did 5 second sleeps rather than deep sleeps, and it showed no such gaps. My intent was to point to any accessibility problems to io.adafruit.com that impacted both of them but didn't find any. The plot is for today, 4/8.

![bme280-temp-f](https://user-images.githubusercontent.com/12761582/162549706-815fc0a0-b12f-4d1b-bc60-849eb22dc103.png)

**Comment by patrebert** [comment]
Don't know if this is a useful clue or not, but a soft reboot doesn't fix the problem; a reset or power cycle do (temporarily). Also, I tried the code on a UM Feather using an I2C DPS310 board for temp info, wondering if the issue might be board specific. Doesn't seem to be, got the same results.

Press any key to enter the REPL. Use CTRL-D to reload.
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Traceback (most recent call last):
  File "code.py", line 11, in <module>
MemoryError: Failed to allocate Wifi memory

Code done running.

**Comment by pillilz** [comment]
I've noticed the error "MemoryError: Failed to allocate Wifi memory" on "import wifi" as well with:
```Adafruit CircuitPython 7.1.1 on 2022-01-14; Adafruit MagTag with ESP32S2```

The MagTag has no hardware attached. The code loads some data over the wifi and then sleeps for 10min.

The error happened only once and with USB attached.

**Comment by dhalbert** [comment]
Assuming this is only fake sleep, we may need to do more wifi cleanup and resetting on restart.

**Comment by dhalbert** [comment]
It has been a long time since the testing in this issue was done. Have any of you re-tested with a newer version of CircuitPython, e.g. 8.0.0-beta.5?

**Comment by dhalbert** [comment]
I am going to close this for now, absent some newer reports on 8.0.0 builds. There is some problem here, but I'm not sure what it is, and it may have been fixed since the initial reports.
