### ISSUE TITLE
Fix autodoc in library doc builds

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#624]
These repos have docs that may technically pass but the autodoc portion fails. This is usually due to a library not being mocked out. To fix it, a line must be added to conf.py to tell sphinx to mock out specific modules. Here is the line from the latest cookicutter's conf.py:

```py
# Uncomment the below if you use native CircuitPython modules such as
# digitalio, micropython and busio. List the modules you use. Without it, the
# autodoc module docs will fail to generate with a warning.
# autodoc_mock_imports = ["adafruit_bus_device", "micropython"]
```

Copy these four lines, uncomment the fourth and adjust the list until the sphinx build includes the autodocs.

- [x] https://github.com/adafruit/Adafruit_CircuitPython_INA219
- [x] https://github.com/adafruit/Adafruit_CircuitPython_DS3231
- [x] https://github.com/adafruit/Adafruit_CircuitPython_CharLCD
- [x] https://github.com/adafruit/Adafruit_CircuitPython_MAX31865
- [x] https://github.com/adafruit/Adafruit_CircuitPython_AMG88xx
- [x] https://github.com/adafruit/Adafruit_CircuitPython_VL53L0X
- [x] https://github.com/adafruit/Adafruit_CircuitPython_TCS34725
- [x] https://github.com/adafruit/Adafruit_CircuitPython_seesaw
- [x] https://github.com/adafruit/Adafruit_CircuitPython_LSM9DS1
- [x] https://github.com/adafruit/Adafruit_CircuitPython_LSM9DS0
- [x] https://github.com/adafruit/Adafruit_CircuitPython_Thermistor
- [x] https://github.com/adafruit/Adafruit_CircuitPython_VC0706
- [x] https://github.com/adafruit/Adafruit_CircuitPython_HT16K33
- [x] https://github.com/adafruit/Adafruit_CircuitPython_FXOS8700
- [x] https://github.com/adafruit/Adafruit_CircuitPython_FXAS21002C
- [x] https://github.com/adafruit/Adafruit_CircuitPython_LIS3DH
- [x] https://github.com/adafruit/Adafruit_CircuitPython_RTTTL
- [x] https://github.com/adafruit/Adafruit_CircuitPython_IS31FL3731
- [x] https://github.com/adafruit/Adafruit_CircuitPython_ADS1x15
- [x] https://github.com/adafruit/Adafruit_CircuitPython_LSM303
- [x] https://github.com/adafruit/Adafruit_CircuitPython_SimpleIO
- [x] https://github.com/adafruit/Adafruit_CircuitPython_BNO055
- [x] https://github.com/adafruit/Adafruit_CircuitPython_VCNL4010
- [x] https://github.com/adafruit/Adafruit_CircuitPython_Fingerprint
- [x] https://github.com/adafruit/Adafruit_CircuitPython_SGP30
- [x] https://github.com/adafruit/Adafruit_CircuitPython_SHT31D
- [x] https://github.com/adafruit/Adafruit_CircuitPython_APDS9960
- [x] https://github.com/adafruit/Adafruit_CircuitPython_DRV2605
- [x] https://github.com/adafruit/Adafruit_CircuitPython_DS2413
- [x] https://github.com/adafruit/Adafruit_CircuitPython_OneWire
- [x] https://github.com/adafruit/Adafruit_CircuitPython_VEML6070
- [x] https://github.com/adafruit/Adafruit_CircuitPython_VL6180X
- [x] https://github.com/adafruit/Adafruit_CircuitPython_Thermal_Printer
- [x] https://github.com/adafruit/Adafruit_CircuitPython_FocalTouch
- [x] https://github.com/adafruit/Adafruit_CircuitPython_MAX9744
- [x] https://github.com/adafruit/Adafruit_CircuitPython_MCP4725
- [x] https://github.com/adafruit/Adafruit_CircuitPython_AVRprog
- [x] https://github.com/adafruit/Adafruit_CircuitPython_DS18X20

**Comment by sommersoft** [comment]
Just for clarification/get-out-in-front of questions: will these need PRs to the bundle repo, or will adabot pull them automagically?

**Comment by tannewt** [comment]
Just PRs to individual repos. ReadTheDocs is based on each repo so it'll pick them up once merged. They don't even need a release.

**Comment by tannewt** [comment]
https://github.com/adafruit/Adafruit_CircuitPython_APDS9960/pull/8 is the last fix for this I believe.

**Comment by sommersoft** [comment]
Belated close-n-thanks, @brentru!!!
