### ISSUE TITLE
EMC Testmode for nRF52840

### ISSUE THREAD

**Issue by ThomasAtBBTF** [adafruit/circuitpython#6242]
This is a duplication of my post in the Adafruit forum,
maybe it is better located here...

I am almost ready with a product containing a ItsyBitsy nrf52840.
It is a braille keyboard for blind users to connect to IOS devices.
We initially want to build a small production run.
Regardless of the number of products brought to the market we need a CE certificate in Europe.
(Similar to FCC in the US.)

For CE RED and EMV testing, the laboratory tells us that we need to bring the nRF52840 into an EMC-Testmode

In the Nordic nRF52840 SDK documentation I found this:
[https://infocenter.nordicsemi.com/index ... erial.html](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.sdk5.v15.3.0%2Fble_sdk_app_dtm_serial.html)

Here are my questions:
Is anyone here aware of this mode?
Can this mode be "activated" from CircuitPython? (currently, I assume not!)

In an ideal world, I would like to see a library with a function settestmode(mode) that would activate the different modes.
After this call the nRF Chip would be probably unusable for CP until the next boot...

Can anybody help with creating such a library?

**Comment by jepler** [comment]
As discussed on Discord, this is better done by an alternate firmware, not a circuitpython firmware.
