### ISSUE TITLE
Move "extension_by_board" deeper into Ports

### ISSUE THREAD

**Issue by askpatrickw** [adafruit/circuitpython#6269]
I'm adding a C3 board, so I had to specify it is BIN only in `tools/build_board_info.py` which triggers all of CP ports to build.

If this could be moved deeper in the folder hierarchy like under ports/<port_name> that would alleviate builds which are not needed from being triggered.

**Comment by Neradoc** [comment]
The info could be added to `mpconfigport.mk` and `mpconfigboard.mk`, and pulled from it in a similar way that the module support matrix does. That way build configuration for each board is in each board's directory.
