### ISSUE TITLE
Nokia 5110/3110 Monochrome LCD

### ISSUE THREAD

**Issue by brentru** [adafruit/circuitpython#630]
Add support for the Nokia 5110/3110 Monochrome LCD

Product Page: https://www.adafruit.com/product/338

Python Library: https://github.com/adafruit/Adafruit_Nokia_LCD

**Comment by ladyada** [comment]
ported from the python library: https://github.com/adafruit/Adafruit_CircuitPython_PCD8544
should be in pypi in the next few days!
