### ISSUE TITLE
GPIO pins are floating high on Feather ESP32-S2 (original version)

### ISSUE THREAD

**Issue by RetiredWizard** [adafruit/circuitpython#6384]
### CircuitPython version

```python
Adafruit CircuitPython 7.3.0-beta.2-31-g72807bb6c on 2022-05-11; Adafruit Feather ESP32S2 with ESP32S2
```

### Code/REPL

```python
# Issue occurs in REPL before any code is run
```

### Behavior

As soon as the board boots to the REPL prompt >>>, the board LED is turn faintly on and all the GPIO pins go to 3.3V.  

I'm not sure if it's related but I've also noticed that when I2C data is sent over the STEMMA QT connection the charging LED blinks and the voltage on the GPIO's bounces between 3.3V and 3.0V. Also the RGB Neopixel blinks when CTRL-D is pressed.

### Additional information

I built the same code for the Sparkfun ThingPlus RP2040 and the GPIOs don't show the 3.3V issue.

**Comment by tannewt** [comment]
We deliberately changed ESP boards to pull pins up when not in use. Floating them caused sporadic neopixel issues otherwise. We do have a way for a board to set a specific pin to a different state. We could do that for the board LED on the S2 feather so that the pin is pulled down instead.
