### ISSUE TITLE
busio.SPI locks GPIO12 even when it's not used on ESP8266

### ISSUE THREAD

**Issue by deshipu** [adafruit/circuitpython#642]
Trying to initialize DigitalInOut on pin GPIO12 results in:

```
>>> dc = digitalio.DigitalInOut(board.GPIO12)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Pin MTDI in use
```
Tested with CircuitPython 2.2.3.

**Comment by deshipu** [comment]
Seems like the pins are not reset on reset.

**Comment by deshipu** [comment]
I did some more digging, and the issue is actually more complex. It looks like you can't use GPIO12 whenever the SPI perihpheral is created, even if you only defined MOSI and no MISO for it.

**Comment by tannewt** [comment]
@deshipu Could you provide the full test code for the after-SPI init problem you are seeing? Thanks!

**Comment by tannewt** [comment]
@sommersoft Does this sound familiar to you?

**Comment by sommersoft** [comment]
No, it doesn't. I know there are about 6 special pins, but 12 doesn't ring a bell as being one. 0,2,5,6,15, and 16 are the ones I remember off the top of my head. But, I can peek at it a little later.

Initial thought is that there are default settings that could be tweaked in SPI...

**Comment by sommersoft** [comment]
Pretty confident I found it. 

[`common_hal_busio_spi_configure`](https://github.com/adafruit/circuitpython/blob/master/ports/esp8266/common-hal/busio/SPI.c#L109) Lines 109 and 121 both call [`hspi.c/spi_init_gpio()`](https://github.com/adafruit/circuitpython/blob/master/ports/esp8266/hspi.c#L92).

 `spi_init_gpio()` uses all 4 SPI pins (12-15) as a default. There is no conditional check...

So, we can either update `hspi.c`, or re-create the config steps in `common-hal` which is what the `construct` has done. I assume `common-hal` option is preferred, to maintain upstream compatible.

**Comment by sommersoft** [comment]
Good catch. I think it's worth it to explore handling the possibilities... ?
