### ISSUE TITLE
rp2040: usb_cdc says "Cannot change USB device now"

### ISSUE THREAD

**Issue by MikeDev101** [adafruit/circuitpython#6471]
### CircuitPython version

```python
Adafruit CircuitPython 7.3.0 on 2022-05-23; Raspberry Pi Pico with rp2040
Board ID:raspberry_pi_pico
```

### Code/REPL

```python
import usb_cdc
print("Booted")
try:
    usb_cdc.enable(console=True, data=True) # Enable console and data
    print("enabled serial and console")
except Exception as e:
    print(e)
```

### Behavior

code.py output:
Booted
Cannot change USB devices now

Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.

### Description

I was trying to configure my rp2040 for USB serial and console, but I cannot seem to get it to change modes.

**Comment by dhalbert** [comment]
You cannot use `usb_cdc.enable()` except in `boot.py`, which is executed before USB is set up.. Once `code.py` starts, the USB devices are already set up and cannot be changed.

For more info, see https://learn.adafruit.com/customizing-usb-devices-in-circuitpython. You can get more help on https://adafru.it/discord or in our forums, https://forums.adafruit.com/viewforum.php?f=60.
