### ISSUE TITLE
Use on-board crystal oscillators for those boards that have them

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#648]
Currently all 3.0 boards are using the 48MHz DFLL in crystalless mode. It's locked to the USB clock when available, but it would be good to use the on-board crystal for boards that have it. 2.x does do this.

**Comment by dhalbert** [comment]
The SAMD51 errata describes a number of issues  operating the DFLL48M in closed loop mode, which may preclude locking to the XOSC32K.

**Comment by tannewt** [comment]
@notro made good progress on this.

Lets double check everything is setup as we want and uncomment this: https://github.com/adafruit/circuitpython/blob/master/ports/atmel-samd/supervisor/port.c#L289
