### ISSUE TITLE
dir from REPL of displayio.Display object returns error

### ISSUE THREAD

**Issue by RetiredWizard** [adafruit/circuitpython#6536]
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-alpha.0-27-g5c46f2a5a-dirty on 2022-06-12; Adafruit Feather RP2040 with rp2040
```

### Code/REPL

```python
import board
import displayio
displayio.release_displays()
tft_cs = board.D9
tft_dc = board.D10
display_bus = displayio.FourWire(board.SPI(), command=tft_dc, chip_select=tft_cs)
display = displayio.Display(display_bus,"",width=320,height=240)
print(dir(display))
```

### Behavior

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Brightness not adjustable
```

### Description

Attempting to use the dir function on a displayio.Display object results in a RuntimeError reporting that "Brightness not adjustable".

I noticed this when creating a subclass object from the ili9341 library:

     display = adafruit_ili9341.ILI9341(display_bus, width=320,height=240)

**Comment by dhalbert** [comment]
This is another example of #4171 causing problems. I'll close this as a dupe, but thank you.
