### ISSUE TITLE
RP2040 PIO WAIT instruction bounds check

### ISSUE THREAD

**Issue by crackmonkey** [adafruit/circuitpython#6538]
I think the PIO StateMachine code is letting me get away with WAIT-ing on a pin I haven't declared I'm using. It's been very handy, but still wrong. 
https://github.com/adafruit/circuitpython/blob/c3a149c14a1fe2e98280b42273d3d0717501deab/ports/raspberrypi/common-hal/rp2pio/StateMachine.c#L439
I think that should be a >= because wait_index is 0 based but in_pin_count is a count so 0 isn't a valid input. I'm able to `wait 1 pin 1` when `in_pin_count=1`, effectively reading the pin after the only one I declared as an input pin.

**Comment by tannewt** [comment]
Would you mind making a PR? I think you are right.

**Comment by tannewt** [comment]
Fixed by #6550
