### ISSUE TITLE
Missing Modules for Board Adafruit Feather RP2040 (socketpool/mdns)

### ISSUE THREAD

**Issue by 19Bender83** [adafruit/circuitpython#6549]
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-alpha.1 on 2022-06-09; Adafruit Feather RP2040 with rp2040
and Adafruit AirLift FeatherWing - ESP32 WiFi Co-Processor
```

### Code/REPL

```python
import socketpool
import mdns
```

### Behavior

Module missing

### Additional information

Dear package mainters

It would be very usefull to also include these modules for the board Adafruit Feather RP2040 because when you add a WiFi these modules are very usefull an make the life much more easier. I already know the workaround => build it by myself but this is sometimes not possibel for some people (by example new to coding and circut python). 
So please add this modules if there are no technical reason to not do it, or at least make them available as a library for these boards. Maybe there are also some other usefull modules which are missing..... (by example ntp ?)

regards and hope to read from you

**Comment by tannewt** [comment]
socketpool and mdns are for microcontrollers with native wifi. The RP2040 doesn't have native wifi so you'll want to use the ESP32SPI library instead. [The Learn guide for ESP32SPI](https://learn.adafruit.com/adafruit-airlift-breakout/circuitpython-wifi) is good place to start.
