### ISSUE TITLE
enable FRAMEBUF module for nrf52 builds

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#656]
Is there any reason not to enable the  framebuf module for the nrf52 builds? 
[https://github.com/adafruit/circuitpython/blob/master/ports/nrf/mpconfigport.h#L128](url)

It is enable for the  ATMEL SAMD "express" boards, but I think the NRF52s have sufficient flash for it as a default.
I enabled it an built the feather52840 BSP and was able to write to an SSD1306 SPI OLED display so it works OK.
I'll be happy to submit a PR for thsi if you want - or it can just wait for the next update. No rush on it.

**Comment by microbuilder** [comment]
@jerryneedell I'll enable this next PR I push out
