### ISSUE TITLE
busio.UART receive buffer too small?

### ISSUE THREAD

**Issue by dmcomm** [adafruit/circuitpython#6579]
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-alpha.1 on 2022-06-09; Raspberry Pi Pico with rp2040
```

### Code/REPL

```python
import board
import busio
import time
import usb_cdc

#serial = usb_cdc.console
serial = busio.UART(board.GP0, board.GP1, receiver_buffer_size=128)
serial.timeout = 1

while True:
    n = serial.in_waiting
    if n > 0:
        data = serial.read(n)
        serial.write((str(n) + " ").encode("ascii"))
        serial.write(data)
        serial.write("\r\n".encode("ascii"))
    time.sleep(5)
```

### Behavior

With an FTDI adapter hooked up to the UART pins (with no flow control), if I send "0123456789012345678901234567890123456789" I get back "32 01234567890123456789012345678901". If I understood the docs correctly, I expect it to take 64 by default, and to be able to increase it using `receiver_buffer_size` as above.

Using `usb_cdc.console` instead appears to give a buffer of 256 (and does use flow control so we pick up the following chunk the next time around, but that's probably not relevant).

**Comment by tannewt** [comment]
I think I found the issue. The UART has a 32 entry RX FIFO. We usually use an interrupt to pull from that FIFO into the receiver buffer of `receiver_buffer_size`. However, the common_hal function that `in_waiting` calls didn't correctly re-enable interrupts! Hence the 32 byte limit.

Please test that https://github.com/adafruit/circuitpython/pull/6583 fixes the issue.

**Comment by dmcomm** [comment]
Yes that fixes it, thanks!
