### ISSUE TITLE
How to bypass readonly filesystem?

### ISSUE THREAD

**Issue by xiaoyu-tamu** [adafruit/circuitpython#6586]
I'm trying to create the `code.py` on the fly but got error `OSError: [Errno 30] Read-only filesystem`

```
with open("my_feature.py", "w+") as f:
    f.write("""print("my_feature")""")
```

is this possible with circuitpython?

**Comment by RetiredWizard** [comment]
The short answer is yes, using a boot.py file and the `storage.remount` method. You just need to understand that once you change the setting you will no longer have Write access via the CIRCUITPY drive and all changes will have to be done from the microcontroller either through REPL commands or CircuitPython code.

Please take a look at the following learning guide that covers the subject:
https://learn.adafruit.com/circuitpython-essentials/circuitpython-storage

**Comment by xiaoyu-tamu** [comment]
Thank you!
