### ISSUE TITLE
Willing to port Pico W MicroPython code to CircuitPython

### ISSUE THREAD

**Issue by richsad** [adafruit/circuitpython#6593]
Don't know where to leave this. I'm a 40 veteren and have shipped two commercial dev platforms (Symantec C++, Visual Cafe (also originally Symantec). More relevant, I'm polyglot programmer of libraries going back to C/C++ standard libraries. I've also worked on OSes (3). I am a busy CTO but have been looking for something important to do for CP. Check out https://www.linkedin.com/in/richsadowsky/

and write to me at rich@waverleysoftware.com. That reaches me fastest

**Comment by askpatrickw** [comment]
@richsad  Discord is the place to be ... checkout the circuitpython-dev channel.

http://adafru.it/discord

**Comment by tannewt** [comment]
Thanks for the offer! Closing in favor of #6558
