### ISSUE TITLE
esp32: light sleep with time alarm returns immediately if web workflow is enabled

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#6604]
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-alpha.1-54-g8b30f0120-dirty on 2022-07-14; Adafruit Feather ESP32 V2 with ESP32
```

### Code/REPL

```python
import alarm
import time

while True:
    now = time.monotonic()
    target = now + 5
    print(f"Doing work from {now=} until {target=}")
    while time.monotonic() < target: sum(range(100))
    
    target = now + 20
    print(f"Light sleeping from {now=} until {target=}")
    time_alarm = alarm.time.TimeAlarm(monotonic_time = target)
    print(f"{time_alarm=}")
    alarm.light_sleep_until_alarms(time_alarm)
    after = time.monotonic()
    print(f"{after=}, {'EARLY' if after < target else 'OK'}")
```

### Behavior

Typical output:
```
Deep sleeping from now=479.346 until target=499.346
time_alarm=<TimeAlarm>
after=479.355, EARLY
```

### Description

Only while using web workflow including #6591 -- if I comment out the SSID setting in .env and reset then it works. Doesn't matter if I've connected to circuitpython.local or not.

**Comment by RetiredWizard** [comment]
I grabbed the latest bits for the Feather Huzzah32 from the S3 server and got this as output:

     Doing work from now=53.316 until target=58.316
     Light sleeping from now=53.316 until target=73.316
     time_alarm=<TimeAlarm>
     <TimeAlarm>
     after=73.318, OK

I modified your loop slightly to suppress the printing of the "sum(range(100))" value.

The output you referenced seems to be from a slightly different loop though.

**Comment by tannewt** [comment]
I'm unable to reproduce this.
