### ISSUE TITLE
Installation of adafruit-circuitpython-waveshare_rp2040_zero-en_US-7.3.1.uf2 fails to connect

### ISSUE THREAD

**Issue by gitterman** [adafruit/circuitpython#6612]
### CircuitPython version

```python
adafruit-circuitpython-waveshare_rp2040_zero-en_US-7.3.1
```

### Code/REPL

```python
Installation does not connect
```

### Behavior

Installation does not connect

### Description

I just installed adafruit-circuitpython-waveshare_rp2040_zero-en_US-7.3.1.uf2 from https://circuitpython.org/board/waveshare_rp2040_zero/ on my waveshare pico zero
and after that, thonny reports:
_Couldn't find the device automatically.
Check the connection (making sure the device is not in bootloader mode) or choose
"Configure interpreter" in the interpreter menu (bottom-right corner of the window)
to select specific port or another interpreter._
I did reset and re-plug the device, but could not get it to connect.
I then installed rp2-pico-20220618-v1.19.1.uf2 and this worked as it should.

**Comment by dhalbert** [comment]
This is probably a Thonny problem. Thonny doesn't recognize the board as a CircuitPython board. I think it may only do that if the USB VID/PID match a list it keeps. You can click on the mode in the lower right hand corner and switch to CIrcuitPython manually. That should get you going.

**Comment by gitterman** [comment]
Thanks for the hint.
This did the trick.
