### ISSUE TITLE
Web Workflow on ESP32 V2 feather chips doesn't respond in specific scenario

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#6613]
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-alpha.1-54-g8b30f0120-dirty on 2022-07-14; Adafruit Feather ESP32 V2 with ESP32
```

### Code/REPL

```python
# None
```

### Behavior

When you follow a specific set of steps, the circuitpython.local site becomes unresponsive

### Description

 1. load the /cp/serial page in the browser
 2. Click the Ctrl-C button in the web page, so that it is sitting at the ">>>" REPL
 3. Use the browser's reload button

This hangs waiting to load /cp/serial/. The only thing that seems to make it continue is pressing ctrl-d in a terminal connected to the USB serial port.

**Comment by tannewt** [comment]
What browser?

**Comment by jepler** [comment]
firefox on linux

**Comment by RetiredWizard** [comment]
This same behavior is happening on S2 and S3 chips. I suspect this is a subset of the issues I'm seeing in #6610
