### ISSUE TITLE
Add Display to DFRobot Beetle ESP32-C3 Board Definition

### ISSUE THREAD

**Issue by askpatrickw** [adafruit/circuitpython#6616]
The DFRobot esp32-c3 has an 18Pin-FPC, GDI display interface. This needs to be added to the board definition.

> NOTE: This actually and add-on board to the main board.

Board Docs: https://wiki.dfrobot.com/SKU_DFR0868_Beetle_ESP32_C3

Related: https://github.com/adafruit/circuitpython/pull/6615

**Comment by askpatrickw** [comment]
I'm not sure this should go in the board definition. Its actually a add-on proto-board with the GDI interface on it.

**Comment by tannewt** [comment]
Yup, this should generally be in a library rather than built in.

**Comment by askpatrickw** [comment]
OK, I'll close this then and look to do that at some point.
