### ISSUE TITLE
MagTag Battery reads much higher and narrower than expected

### ISSUE THREAD

**Issue by pianohacker** [adafruit/circuitpython#6631]
With a 4.2-3.7V LiPo battery plugged in, `MagTag().peripherals.battery` reads 5.3-5.2V.

**Comment by dhalbert** [comment]
To fix this, we could prevent pulling up the battery pin in its reset state on the MagTag, using the custom pin reset code.

**Comment by dhalbert** [comment]
These appears to be fixed now by #6246. I tried the example above and I get a reasonable value on first read.
