### ISSUE TITLE
Incorporate MicroPython float printing fix

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#6649]
https://github.com/micropython/micropython/commit/f9cbe6bc47dd4f5b8e85178caecd6f0de22b4c34 is a fix to MicroPython that improves the representation of printed floats noticeably.

`ulab` testing now breaks because the tests print differently for CircuitPython and MicroPython:
https://github.com/v923z/micropython-ulab/issues/541

We should consider cherry-picking this fix for 8.0.0 to allow `ulab` CI to work better again and to incorporate the improvement.

Tagging @v923z, who asked that this be noted as an issue.

**Comment by v923z** [comment]
Since the issue is noted here, I am closing https://github.com/v923z/micropython-ulab/issues/541. For 8.0.0, we simply have to uncomment https://github.com/v923z/micropython-ulab/blob/dfed7a844a9bf16c14e7e04282422fad03632dd6/build-cp.sh#L47.
