### ISSUE TITLE
Can't "Paste" into Web Workflow serial terminal command line

### ISSUE THREAD

**Issue by RetiredWizard** [adafruit/circuitpython#6655]
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-alpha.1-69-gbc926b041-dirty on 2022-07-26; Adafruit Feather ESP32S3 4MB Flash 2MB PSRAM with ESP32S3

Circuit Python Built from Pull Request #6651
```

### Code/REPL

```python
None
```

### Behavior

If you attempt to paste text into the command line of the serial terminal the text is displayed as it's pasted, however pressing enter or the "Send" button only sends a carriage return to the microcontroller

**Comment by tannewt** [comment]
This is likely because the "beforeinput" event handler needs to look at input types that are caused by the paste.
