### ISSUE TITLE
circuitpython on riscv64

### ISSUE THREAD

**Issue by abhishekwalia33** [adafruit/circuitpython#6656]
Hi I am trying to port circuitpython on riscv64 it is not working can we get support on riscv. please help me out or when can we expect the support for riscv.

**Comment by tannewt** [comment]
What chip are you trying to run CircuitPython on? How is it not working? Please link to the code you are working on.

We do support riscv32 on the ESP32-C3 already.

**Comment by dhalbert** [comment]
Closing since too non-specific.
