### ISSUE TITLE
touchio not yet supported (CP 3.0 alpha 2)

### ISSUE THREAD

**Issue by hukuzatuna** [adafruit/circuitpython#670]
It would be great to get touchio ported to the latest CircuitPython release.

Board: Trinket M0
Version: Adafruit CircuitPython 3.0.0-alpha.2-13-gdde5ade-dirty on 2018-03-10; Adafruit Trinket M0 with samd21e18

Replicate by: "import touchio" generates "ImportError: no module named 'touchio'"

**Comment by siddacious** [comment]
This ticket *kinda* duplicates #268, but that ticket is specific to the M4 and this one talks about the m0
