### ISSUE TITLE
USB Midi!

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#672]
Requested by JohnPark and Noe. Then we can create simple button instruments using midi.

**Comment by djecken** [comment]
This is a great "example" project for USB MIDI. Simple button presses for triggering midi notes. https://learn.adafruit.com/arcade-button-control-box

**Comment by moliata** [comment]
Any update on this?

**Comment by ladyada** [comment]
moli, we had to refactor all of the usb stack but we’re getting there, subscribe to this topic and youll kniw the moment its available. no ETA 😁

**Comment by moliata** [comment]
@ladyada Awesome, thanks!

**Comment by moliata** [comment]
@ladyada following up, even tho' there is no ETA, do you know is it a couple of days or a few months job? Thanks!

**Comment by ladyada** [comment]
no ETA 😁

**Comment by kevinjwalters** [comment]
For anyone who was following this ticket which was mentioned in https://forums.adafruit.com/viewtopic.php?f=58&t=141504, the CircuitPython library has been around for a while now and can be found in the standard bundle and on GitHub as https://github.com/adafruit/Adafruit_CircuitPython_MIDI
