### ISSUE TITLE
Web Workflow File Manager Missing Icons on MacOS

### ISSUE THREAD

**Issue by makermelissa** [adafruit/circuitpython#6723]
### CircuitPython version

```python
Absolute latest from 8/8/22
```

### Code/REPL

```python
N/A
```

### Behavior

When browsing files on the device with web workflow, many of the unicode characters are missing. See screenshot below.

### Description

<img width="1014" alt="Screen Shot 2022-08-09 at 11 27 16 AM" src="https://user-images.githubusercontent.com/2681417/183734544-d92d67bc-1705-4f72-bcb3-0a4c973d319b.png">

**Comment by tannewt** [comment]
@Neradoc you had ideas for this right?

**Comment by Neradoc** [comment]
Yeah I replaced them with emojis, which are better supported across systems. I could try researching non-emoji alternatives that are better supported, but that seems to be an area where it's hard to get any actual information.

**Comment by makermelissa** [comment]
Emojis should be fine. The main non-emoji alternative is HTML entities like here: https://www.freeformatter.com/html-entities.html
