### ISSUE TITLE
OSError: 19 when attempting storage.mount(vfs, "/sd") for Adalogger Featherwing

### ISSUE THREAD

**Issue by waldo323** [adafruit/circuitpython#674]
using an feather M0 express with adalogger featherwing in trippler I get an OSError: 19 when trying to run storage.mount(vfs, "/sd")

REPL:
>>> import board
>>> import busio
>>> import digitalio
>>> import adafruit_sdcard
>>> import storage
>>>
>>> spi = busio.SPI(board.SCK, MOSI=board.MOSI, MISO=board.MISO)
>>> # Use board.SD_CS for Feather M0 Adalogger
>>> cs = digitalio.DigitalInOut(board.**D10**)
>>>
>>> sdcard = adafruit_sdcard.SDCard(spi, cs)
>>> vfs = storage.VfsFat(sdcard)
>>>
>>> storage.mount(vfs, "/sd")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: 19

I also got this error when running one of the examples (modified with D10 for CS)

additional information:
looking at the guide: the https://learn.adafruit.com/adafruit-adalogger-featherwing/circuitpython   
I got to the bit about cs = digitalio...it states this line is for feather m0 so I think this is where things differ and I am second guessing whether this is the right guide. When I do a dir(board) I don't see SD_CS

tannewt - Today at 7:11 PM
looks like board.D10 would work
SD_CS is for the feather adalogger (not wing)

**Comment by waldo323** [comment]
update from yesterday issue I was having using feather m0 express with adalogger featherwing: I switched from a 16 GB, to 8GB didn't change code or version of circuit python yet but it 'just worked' got a hello world to print to a file on the 8gb board
the guide at: https://learn.adafruit.com/adafruit-adalogger-featherwing/using-the-sd-card 
states:
"The FeatherWing kit doesn't come with an SD card but we carry one in the shop that is guaranteed to work. Pretty much any SD card should work but be aware that some cheap cards are 'fakes' and can cause headaches." 
I believe size not brand is possibly the issue here but this is just my speculation

**Comment by waldo323** [comment]
the main issue is the guide says one thing and board operates differently

possible solutions:
- update library or core code to work with larger cards
- update the guide / documentation to reflect the size should be within certain working values.

**Comment by siddacious** [comment]
Is it possible that one card was formatted differently from the other?

**Comment by waldo323** [comment]
both are SanDisk
both are formatted fat32 with gparted on an ubuntu 16.04 laptop

in attached picture:

- 16 gb on the left did not work,  
- 8 gb on the left did work.

![sdcards](https://user-images.githubusercontent.com/1671616/37384113-56f1bc3a-2723-11e8-9ad4-53bc8b569f92.jpg)

**Comment by waldo323** [comment]
I did notice there was a 1 meg spot non allocated space before the partition for the 8 gb card and no non allocated space on the 16 gb card

**Comment by dhalbert** [comment]
Could you completely erase the 8GB card and reformat it so that it doesn't have an odd partition layout and then try again?

**Comment by ladyada** [comment]
use SD formatter if you can - https://www.sdcard.org/downloads/formatter_4/
its the 'official' method of formatting an SD card to FAT filesys

**Comment by waldo323** [comment]
Oops, my image caption included two lefts. (That's just not right)
I'm glad the cards are labeled. 

Is there an official way to format the SD cards for Linux?

In the meantime, I will format both cards with my windows laptop and the official method when I get home from work, then try both sd cards with the Featherwing Adalogger. 

Thanks :)

**Comment by dhalbert** [comment]
For Linux, you could use `gparted`, `fdisk`, `gnome-disk-utility` (aka "Disks" in a Gnome-ish UI). You can delete any existing partitions and then reformat.

**Comment by waldo323** [comment]
Using Windows version of the SD Card Formatter with the 16 GB card met with success!
the 8 GB formatted with the SD Card Formatter continued to meet with success. (maybe they are friends?)

after formatting in windows, testing on the adalogger, I checked with gparted to see what the partitions look like (they both look different from before) they both have 4 MB not allocated at the beginning of the cards.
![img_20180314_211325](https://user-images.githubusercontent.com/1671616/37439268-bb061a9a-27cd-11e8-87d0-165b6134040c.jpg)
![img_20180314_211355](https://user-images.githubusercontent.com/1671616/37439269-bb123366-27cd-11e8-8c24-e014b342e485.jpg)

**Comment by tannewt** [comment]
Is this still an issue?

**Comment by kattni** [comment]
Closing issue. If you run into problems again, please feel free to reopen the issue!
