### ISSUE TITLE
ESP32-S2 w/ TFT screen flickers upon startup

### ISSUE THREAD

**Issue by TrevKnows** [adafruit/circuitpython#6756]
### CircuitPython version

```python
Issue occurring using absolute build Adafruit CircuitPython 8.0.0-alpha1 using:
adafruit-circuitpython-adafruit_feather_esp32s2_tft-en_US-20220811-f9b9f55.uf2

to build:
adafruit-circuitpython-adafruit_feather_esp32s2_tft-en_US-20220810-a1d48e9.uf2

This build works:
adafruit-circuitpython-adafruit_feather_esp32s2_tft-en_US-20220810-08e3133.uf2
```

### Code/REPL

```python
There was no code added to the code.py. Also, unable to check REPL because the board isn't being recognized.
```

### Behavior

My computer does not recognize the board. 
On startup or when the board is powered on, some text appears on the TFT, flickers; then the screen goes black. This is repeatedly happening.

**Comment by tannewt** [comment]
@dhalbert You were gonna look into this right?

**Comment by ladyada** [comment]
(this is bootloop issue, which i could repro!)

**Comment by tannewt** [comment]
Ok, I found an issue with the websocket ringbuf. It does a % which crashes when size is 0 before init. Fix coming soon.
