### ISSUE TITLE
microcontroller.cpu.temperature not implemented on ESP32-S3

### ISSUE THREAD

**Issue by kattni** [adafruit/circuitpython#6773]
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-alpha.1 on 2022-06-09; Adafruit Feather ESP32-S3 TFT with ESP32S3
```

### Code/REPL

```python
import microcontroller

while True:
    print(microcontroller.cpu.temperature)
```

### Behavior

This code throws the following error:
```
code.py output:
Traceback (most recent call last):
  File "code.py", line 4, in <module>
NotImplementedError:

Code done running.
```

**Comment by dhalbert** [comment]
Temperature is not implemented in ESP-IDF yet for ESP32-S3. It's part of the ULP. See: https://github.com/espressif/esp-idf/issues/8672

**Comment by igrr** [comment]
The temperature sensor API is available for the ESP32-S3: https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/peripherals/temp_sensor.html
The linked issue is related to the temperature sensor driver for the ULP coprocessor.

**Comment by dhalbert** [comment]
@igrr Thanks - I will see about adding it. We are still on 4.4.3 at the moment.
