### ISSUE TITLE
Thonny stops functioning when error introduced into code

### ISSUE THREAD

**Issue by kattni** [adafruit/circuitpython#6804]
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-beta.0 on 2022-08-24; Adafruit Feather ESP32 V2 with ESP32
```

### Code/REPL

```python
x =
```

### Behavior

Thonny will no longer let you interact with the board, either by attempting to save an update to code.py, or through the REPL.

### Description

The code really doesn't matter, as long as it has an error in it. Thonny works great when your code will run. As soon as an error is introduced, Thonny stops working properly. Your code.py file may still be open, but if you make a change and try to save it, it says the board is busy. If you restart the backend in Thonny, no change. If you reset the board, Thonny acts like it's going to see it, and might even jump into what looks like the REPL, but you cannot interact with the board either by saving a file, or trying to interact with the REPL. The status NeoPixel is white, so the board is in the REPL, but Thonny does not register this.

It has been determined that the CircuitPython status bar is the issue. I'm currently running a build with it disabled, and Thonny is working as expected. With an existing build, the status bar shows WiFi status, etc, as long as there are no errors in the code. Once an error occurred, the status bar does not update with the file info or the exception name. And Thonny shows the behavior described above. 

### Additional information

Disabling the status bar in CircuitPython resolves the issue.

**Comment by dhalbert** [comment]
I no longer see this with CircuitPython 8.0.0-beta.2 and Thonny 4.0.1. Closing, but can reopen or open another issue as necessary.
