### ISSUE TITLE
socketpool.SocketPool has no documentation for its __init__()

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#6820]
`socketpool.SocketPool` has no `def __init__():` documentation. @kattni's PyCharm noticed this and complained about the typical argument `socketpool.SocketPool(wifi.radio)`.

**Comment by DJDevon3** [comment]
I’m working on a very similar project to kattni’s. I’m using 7.3.3 and can confirm. My pycharm does the same thing. Says wifi.radio not a valid argument and tries to reference a missing init. Code still works but pycharm not happy about it.

**Comment by tekktrik** [comment]
I got this!
