### ISSUE TITLE
Os.stat missing documentation

### ISSUE THREAD

**Issue by thetazero** [adafruit/circuitpython#6821]
The [os.stat](https://docs.circuitpython.org/en/7.3.x/shared-bindings/os/index.html#os.stat) docs do not fully describe the behavior. 
From the docs it is unclear what the returned tuple represents.
![image](https://user-images.githubusercontent.com/28244551/186771462-cc6a5a78-4a5e-40c4-b4ea-5e595d4545f4.png)

**Comment by BrianPugh** [comment]
the returned tuple is the [same as in normal python](https://docs.python.org/3/library/os.html#os.stat).

Of which, the following are probably properly populated:

`os.stat()[0]`  file type, regular or directory. 
`os.stat()[6]`  file size
`os.stat()[7], os.stat()[8], os.stat()[9]` are all the same and tell the modification time. For that value to be correct, the time has to be set.

**Comment by thetazero** [comment]
Thanks @BrianPugh, I've created a pull improving the documentation based on your comments.
