### ISSUE TITLE
Disable dot release docs in RTD that indirect incorrectly 

### ISSUE THREAD

**Issue by willingc** [adafruit/circuitpython#684]
This is a minor housekeeping follow up to #682. @sommersoft @kattni @tannewt 

### RTD Versions page
<img width="995" alt="screen shot 2018-03-18 at 9 17 35 am" src="https://user-images.githubusercontent.com/2680980/37568065-5e05b676-2a8d-11e8-9fd2-c392100acd14.png">

### Landing page for 2.2.1, 2.2.0, and 2.1.0
<img width="779" alt="screen shot 2018-03-18 at 9 17 49 am" src="https://user-images.githubusercontent.com/2680980/37568074-7630ad1e-2a8d-11e8-8437-fff02279839a.png">

### RTD Admin -> Versions page (using JupyterHub as an example)

As @kattni has updated the links in the GitHub release notes to redirect to 2.x :sunny:, I would recommend that the docs for 2.2.1, 2.2.0, and 2.1.0 be disabled (uncheck `Active`). At present, the RTD UI doesn't offer a good way to change the SHA-1 commit chosen for a release after the release has happened.

<img width="739" alt="screen shot 2018-03-18 at 9 15 37 am" src="https://user-images.githubusercontent.com/2680980/37568107-cfbd8b72-2a8d-11e8-8bde-3bc4373e08a9.png">

**Comment by kattni** [comment]
This is an excellent suggestion. @willingc, thank you for outlining the process! I've disabled 2.2.1, 2.2.0, and 2.1.0 in Read the Docs, leaving latest and 2.x as the active options. So, we should be set for now. Thanks again!

**Comment by willingc** [comment]
Thanks @kattni. Happy to share the process. It took me a long time to find out some of the RTD workflow stuff like this.
