### ISSUE TITLE
Web Workflow: network mDNS hostname often differs from local-device mDNS hostname (links & redirects don't work)

### ISSUE THREAD

**Issue by anecdata** [adafruit/circuitpython#6869]
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-beta.0 on 2022-08-18; Adafruit QT Py ESP32S2 with ESP32S2
```

### Code/REPL

```python
# From another device on the network, "augmented" names are found:
m = mdns.Server(wifi.radio)
for service in m.find(service_type="_circuitpython", protocol="_tcp", timeout=5):
        print(service.instance_name)
        print(service.hostname)
        print(f"{service.ipv4_address}:{service.port}")
"""
Adafruit QT Py ESP32S2-5
cpy-f66961-281
192.168.6.180:80
"""

# So these work:
# curl -v -L http://192.168.6.180/cp/devices.json
# curl -v -L http://cpy-f66961-281/cp/devices.json

# But the device itself does not seem to know about the augmented name:
print(m.hostname)
# cpy-f66961
print(m.instance_name)
# cpy-f66961
# NOTE: this is completely different from the Instance Name reported from other devices using .find

# So this does not work:
# curl -v -L http://cpy-f66961.local/cp/devices.json
```

### Behavior

From the network perspective, CircuitPython mDNS hostnames often have a hyphen and integer appended to the hostname. CircuitPython mDNS `server.find` [code](https://gist.github.com/anecdata/06045da4eb109e7467d9e8068a8dffad) will expose these augmented hostnames (and instance names), and browsers and curl will find the devices using these augmented names.

Anyone who has encountered things like `iPhone (3)` has encountered a related issue, I suspect.

However, the device itself [currently] does not recognize itself with these augmented names. The Web API will report something like:

**Hostname:**
[cpy-f66961](http://cpy-f66961.local/)
**IP:**
[192.168.6.180](http://192.168.6.180/)

and clicking the hostname link on the Web API will fail.

Redirects also fail since the device doesn't answer to its nominal hostname:
```
% curl -v -L http://circuitpython.local/cp/devices.json
*   Trying 192.168.6.180:80...
* Connected to circuitpython.local (192.168.6.180) port 80 (#0)
> GET /cp/devices.json HTTP/1.1
> Host: circuitpython.local
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 307 Temporary Redirect
< Connection: close
< Content-Length: 0
< Location: http://cpy-f66961.local/cp/devices.json
< Access-Control-Allow-Credentials: true
< Vary: Origin, Accept, Upgrade
< Access-Control-Allow-Origin: 
< 
* Closing connection 0
* Issue another request to this URL: 'http://cpy-f66961.local/cp/devices.json'
* Could not resolve host: cpy-f66961.local
* Closing connection 1
curl: (6) Could not resolve host: cpy-f66961.local
```
or simply:
```
% curl -v -L http://cpy-f66961.local/cp/devices.json 
* Could not resolve host: cpy-f66961.local
* Closing connection 0
curl: (6) Could not resolve host: cpy-f66961.local
```

### Description

When a device mDNS hostname has been augmented:
1. the "Hostname:" link on the Web API web page will fail
2. the [File REST API ](https://docs.circuitpython.org/en/latest/docs/workflows.html#web)breaks

### Additional information

Since the device knows its own IPv4 address, perhaps one solution could be to redirect to the IPv4 address instead of to the network-invalid mDNS local-device hostname, and not redirect at all if the entry URL is the IP address.

**Comment by makermelissa** [comment]
Ok, this sounds like it's not yet properly handling mDNS Hostname conflict naming. While in theory, every device should have a unique name because of using the MAC address, this isn't always the case such as with an improperly setup network where multiple mDNS resolvers keep trying to resolve the same host.

This is good info because there may need to be some updates to code.circuitpython.org to deal with this there too.

**Comment by tannewt** [comment]
@anecdata How many devices do you have on the network? Are you relying on web workflow to start wifi or are you starting it everytime yourself in code.py?

**Comment by anecdata** [comment]
Typically less than half a dozen CircuitPython devices with web workflow enabled. I don't have any collisions in the lower three octets of the MAC.

Currently on devices where web workflow is enabled, web workflow starts up wifi.

**Comment by tannewt** [comment]
@anecdata Could you please give me more details of your network setup and what code is running on each device and what device it is? I was able to get the IDF to mangle the instance name but not the hostname.

**Comment by anecdata** [comment]
Not sure what all is useful to you... Multiple industrial-strength APs, all with the same SSID(s). Relatively complex home network wired / wifi, but robust. A lot of devices on the network, a bunch of Apple devices, some Raspberry Pi, myriad other things. There are a lot of CircuitPython devices, though only a handful running web workflow (and none anymore doing non-web-workflow mDNS).

Typically I'm using Safari to interact with the web workflow pages, could be something to do with Mac cacheing. But accessing from Chromium on a Raspberry Pi also requires the numeric extension to the mDNS hostname (note that no devices ever show up in the `Here are other CircuitPython devices on your network:` list on that platform).

My assumption has been that mDNS is really just between the device advertising its hostname and instance name on an IPv4:port, and the device trying to access it (no central name server).

The web workflow devices are all ESP32-S2 (QT Py), now running 8.0.0-beta.3 or -beta.4. Four of them are running rudimentary adafruit_httpserver just for testing. Another is running a typical web client. Another is just chilling in the REPL. All are in Station mode, no APs.

Typical web workflow display as follows:
```
Here are other CircuitPython devices on your network:

[Adafruit QT Py ESP32S2-4 (cpy-d96468-22)](http://192.168.6.165/)
[Adafruit QT Py ESP32S2-6 (cpy-706b80)](http://192.168.6.197/)
[Adafruit QT Py ESP32S2-5 (cpy-a58fbc-83)](http://192.168.6.179/)
[Adafruit QT Py ESP32S2-2 (cpy-70e2de-12)](http://192.168.6.196/)
```
The `Here are other CircuitPython devices on your network:` rarely if ever finds all of the devices, typically 0-3.

A `[cpy-aaeb26](http://cpy-aaeb36.local/)` hostname on one device's web workflow page shows up to other devices' web workflow pages as `[Adafruit QT Py ESP32S2 (cpy-aaeb36-666)](http://192.168.6.194/)`.

Neradoc has also seen this behavior, various discussions on Discord.

**Comment by tannewt** [comment]
Thank you both! I'll try again to replicate it today.

The collision should only happen if two devices share a hostname (which they shouldn't.) Instance names can have this happen too but it isn't critical for the API to work.

**Comment by tannewt** [comment]
I think this change in the IDF will fix it: https://github.com/adafruit/esp-idf/pull/9

Thanks to @anecdata for finding that it is caused by a collision of `circuitpython.local` causing the mac based hostname to be mangled.

**Comment by anecdata** [comment]
This issue of spontaneously-incrementing mDNS hostnames  (e.g., "blahblah-4") appears to be back in CP 9. CP 8.2.10 seems fine. @donutcat spotted it, and there's been discussion on Discord last evening and prior in #help-with-circuitpython.

`Adafruit CircuitPython 9.1.4 on 2024-09-17; Adafruit QT Py ESP32-S3 4MB Flash 2MB PSRAM with ESP32S3`

No `code.py` file.

`settings.toml`:
```py
CIRCUITPY_WIFI_SSID="Redacted"
CIRCUITPY_WIFI_PASSWORD="Redacted"
CIRCUITPY_WEB_API_PASSWORD="passw0rd"
```
(and a similar file on another S3)

Device 34, after reset:
```
% curl -iL http://cpy-****34.local
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Length: 644
Content-Type: text/html
```

Device 84, after reset:
```
% curl -iL http://cpy-****84.local
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Length: 644
Content-Type: text/html
```

Try `circuitpython.local`:
```
% curl -iL http://circuitpython.local
HTTP/1.1 307 Temporary Redirect
Connection: close
Content-Length: 0
Location: http://cpy-****34.local/
Access-Control-Allow-Credentials: true
Vary: Origin, Accept, Upgrade
Access-Control-Allow-Origin: *

HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Length: 644
Content-Type: text/html
```

First time is fine, but after redirecting from `circuitpython.local`, the hostname has changed (though the redirect to the old name may still be cached... somewhere):
```
% curl -iL http://circuitpython.local
HTTP/1.1 307 Temporary Redirect
Connection: close
Content-Length: 0
Location: http://cpy-****34.local/
Access-Control-Allow-Credentials: true
Vary: Origin, Accept, Upgrade
Access-Control-Allow-Origin: *

curl: (6) Could not resolve host: cpy-****34.local
```
It's incremented occasionally even without visiting `http://circuitpython.local`.

Success to the incremented hostname:
```
% curl -iL http://cpy-****34-2.local
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Length: 644
Content-Type: text/html
```

![Screenshot 2024-09-20 at 10 01 43 AM](https://github.com/user-attachments/assets/c392724f-fc88-4033-8c38-26778f2488e9)
![Screenshot 2024-09-20 at 10 01 51 AM](https://github.com/user-attachments/assets/fba77a21-e1d8-41ff-b8c6-d978ead4be33)

Things get stranger if the hostname is changed in `code.py`, but that could be a second-order effect. Instance name also gets incremented.

**Comment by dhalbert** [comment]
`make latexpdf` worked with Sphinx 7.4.7. Then I updated did `pip install --upgrade -r requirements-doc.txt`, and Sphinx got upgraded to 8.1.0. Then `make latexpdf` failed. Checking further.
