### ISSUE TITLE
Brightness is zero on startup on FunHouse, Feather ESP32-S3, etc.

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#6896]
After #6894, on-board displays are dark on initial boot on various boards, including FunHouse and Feather ESP32-S3. Not a problem on PyPortal.

**Comment by gamblor21** [comment]
Set brightness is being called from the constructor and it does seem that (on my device) the brightness cannot be changed so the bug may be in set brightness.

**Comment by dhalbert** [comment]
I neglected to say that in the REPL, it's possible to set `board.DISPLAY.brightness`, and it will work. It just comes up dark.

**Comment by dhalbert** [comment]
I believe the problem is that `board_init()`, which sets up the display and the PWM, is called before `reset_port()` in `main()` (in `main.c`). So `pwmout_reset()` gets called after the initial brightness setting and gets messed up. Before #6894, brightness was set again, and the `PWMOut` was restored, but that isn't happening anymore. I will try some reordering.

**Comment by dhalbert** [comment]
More investigation: `pwmout_reset()` appears to be buggy.
