### ISSUE TITLE
time.monotonic() seems to be scaled in tenths of a second

### ISSUE THREAD

**Issue by cversek** [adafruit/circuitpython#69]
```python
Adafruit CircuitPython v1.8.5-20161020-234-g5b7fcf6-dirty on 2017-01-09; ESP module with ESP8266
>>> import time
>>> for i in range(5):
...     print(time.monotonic())
...     time.sleep(1.0)
...     
...     
... 
5226.959
5236.969
5246.969
5256.979
5266.99
>>> 
```
This behavior seems like it violates the "no-surprises" python style rule and it is not documented: 
https://adafruit-micropython.readthedocs.io/en/latest/shared-bindings/time/__init__.html

**Comment by tannewt** [comment]
Just a bug. Thanks for filing an issue. Fix coming shortly.
