### ISSUE TITLE
"array" module doesn't appear in bindings matrix

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#6935]
### CircuitPython version

```python
8.0.0
```

### Code/REPL

```python
# none
```

### Behavior

In https://docs.circuitpython.org/en/latest/shared-bindings/support_matrix.html the "array" module should be listed, but it's not.

**Comment by Neradoc** [comment]
The `_asyncio` module doesn't appear in matrix either, nor in the modules list (unlike `_bleio` for example).
