### ISSUE TITLE
Unable to access REPL on odroid go

### ISSUE THREAD

**Issue by bennr01** [adafruit/circuitpython#6936]
### CircuitPython version

```python
This has been checked with:

- `adafruit-circuitpython-hardkernel_odroid_go-en_US-20220920-b6f67be.bin`
- `adafruit-circuitpython-hardkernel_odroid_go-en_US-8.0.0-beta.0.bin`
-  a locally built version based on `b6f67be3e`
```

### Code/REPL

```python
# none, no REPL access, fresh flash without any file changes
```

### Behavior

Running the various CircuitPython versions previously mentioned on my odroid go, I am unable to access the REPL via serial connection. Additionally, CircuitPython exhibits various buggy behaviors, ranging from gibberish on the screen to getting stuck when showing the "Adafruit CircuitPython 8.0.0-beta.0-62-gb6f67be3e on 2022-09-20; Hardkernel Odroid Go with ESP32" message on screen . **Please see the 'Description' field of this template for an actual bug description**

### Description

I am trying to run CircuitPython on my odroid go, but I am unable to gain access to the REPL when following the instructions from the guide. Various other behaviors exhibited by CircuitPython make me believe that this may be caused by a bug of the espressif port. Please see the more detailed report below.

**Board**

- odroid go (esp32)

**CircuitPython version**

This has been checked with:

- `adafruit-circuitpython-hardkernel_odroid_go-en_US-20220920-b6f67be.bin`
- `adafruit-circuitpython-hardkernel_odroid_go-en_US-8.0.0-beta.0.bin`
-  a locally built version based on `b6f67be3e`

**Expected behavior**

According to the ["Welcome to CircuitPython!" guide](https://learn.adafruit.com/welcome-to-circuitpython/the-repl) I should be able to access the REPL via serial by pressing CTRL-C.

**Observed behavior** 

The exact observed behavior depends on whether CircuitPython runs for the first time after being flashed or if the device has been turned off since then as well as the version/build used.

**On 20220920-b6f67be:**

When CircuitPython starts for the first time on the odroid go, the display turns on, a short text mentioning the CircuitPython version appears on the bottom of the screen and a cute purple snake appears at the top left. Shortly afterwards, the text disappears and instead seemingly random ASCII-characters appear on various position the screen. These characters are always the same, but their exact position is slightly different depending on the build used.

An excerpt of the characters shown: `9<multiple spaces>5 5<multiple spaces> !  !<newline><markdown reserved character>4 5<multiple spaces>4 5<multiple spaces>@<multiple spaces>!<newline><multiple spaces>)<multiple spaces>$<newline><multiple spaces>D<multiple spaces>E<multiple spaces>" F<multiple spaces>" 0`

These characters do no appear on the serial output.

On subsequent restarts of the device, the gibberish won't appear and the odroid go gets stuck on the version display.

Serial output (on first run):

```
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:12784
load:0x40080400,len:3024
entry 0x400805dc
Serial console setup
Adafruit CircuitPython 8.0.0-beta.0-62-gb6f67be3e on 2022-09-20; Hardkernel Odroid Go with ESP32
Board ID:hardkernel_odroid_go
UID:4B6ED24DB01B

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Hello World!

Code done running.
```

No input sent via serial is being accepted (including CTRL-C).

When I turn the device on afterwards, the serial output ends with the UID line.

**On en_US-8.0.0-beta.0:**

The behavior when using the beta release is nearly the same as with the 0220920-b6f67be build with three key differences:

- there is less gibberish appearing on the screen. More specifically, only the text "y5" appears next to the snake (blinka, I guess?)
- the "code.py" text also appears on the screen, which turns dark afterwards
- on subsequent device starts, the screen shuts down quickly after the "CircuitPython" message appears rather than continue displaying that message

### Additional information

- serial connection is established via `screen` and the USB interface built into the odroid go
- I've verified that inputing text (including ctrl-c) via serial works using MicroPython
- the display takes up to 3 seconds for switching from the default empty/white background to the black background+text
- tested with both an microSD inserted and without one
- flashed both directly via `esptool.py` and using `make BOARD=... flash`

**Comment by tannewt** [comment]
8.1.0-beta.1 works fine for me on my Odroid Go. The issue must have been fixed.
