### ISSUE TITLE
Trinket M0: assigning I2C pins first blocks out UART pins

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#699]
I2C before UART doesn't work:
```
Adafruit CircuitPython 2.2.4-2-gcfcbb3623 on 2018-03-22; Adafruit Trinket M0 with samd21e18
>>> 
>>> import board,busio
>>> i2c = busio.I2C(board.SCL, board.SDA)
>>> uart = busio.UART(board.TX, board.RX)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Invalid pins
```
UART before I2C works:
```
Adafruit CircuitPython 2.2.4-2-gcfcbb3623 on 2018-03-22; Adafruit Trinket M0 with samd21e18
>>> import board,busio
>>> uart = busio.UART(board.TX, board.RX)
>>> i2c = busio.I2C(board.SCL, board.SDA)
>>> 
```

So it would be good to use a different preferred SERCOM allocation order.

@ladyada @kattni : note this as a support issue, came up in https://forums.adafruit.com/viewtopic.php?f=52&t=131725&start=15#p659876

**Comment by tannewt** [comment]
A board-specific hack could help here. Is hard-coding the approach we want to take for things like this?

**Comment by ladyada** [comment]
oi yeah trinket is a very odd case because i fit all the pins on a dual sercom, so you could have either 2 sercoms for i2c/usart or one for a full SPI. i think for now we should document this as an unexpected consequence of the way trinket m0 is set up. long term, we can do hardcoding/hinting.
sound good?

**Comment by dhalbert** [comment]
Documented this restrction in https://learn.adafruit.com/circuitpython-essentials/circuitpython-uart-serial#wheres-my-uart (at the end).
