### ISSUE TITLE
Espressif: FrequencyIn causes crashes

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#6998]
Tested on builds slightly past 8.0.0-beta.1. Tested on Feather ESP32-S2 and ESP-S3, and also Metro ESP32-S2 (using `IO11` and `IO12`).

```py
import board
import pwmio
import frequencyio
import time

pwm = pwmio.PWMOut(board.D11, frequency=150000, duty_cycle=32768)

freq = frequencyio.FrequencyIn(board.D12, capture_period=5)

while True:
    print(freq.value)
    time.sleep(1)
```
Running the above on Feather ESP32-S2 or ESP32-S3 causes safe mode into HardFault Handler  or Internal watchdog timer expired, or just a crash. Trying to write code.py while the program is running may cause enough of a filesystem failure that the fileystem is reformatted on restart.

Discovered while testing #5733, because `FrequencyIn` uses the timers discussed in #5733.

I tried a quick fix of making the `FrequencyIn` object long-lived, but that didn't help.

**Comment by MicroDev1** [comment]
You may want to start working on this post #6913 as the current `PCNT` and `GPTIMER` drivers used by `FrequencyIn` have been deprecated in `idf-v5.0` and replaced with a new api.

**Comment by tannewt** [comment]
The callbacks are marked as IRAM but the Python objects themselves aren't available when the cache is disabled. Flash accesses disable both external flash and external ram. I'm updating this API will have static counters in IRAM for it.
