### ISSUE TITLE
Sort out the apparent 4kB gap between FLASH_FIRMWARE and CIRCUITPY

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#7012]
In #7011 we discussed how there is an apparent 4kB gap between FLASH_FIRMWARE and CIRCUITPY. Determine whether this gap is required; if it is, comment it for the future. If it's not, then enlarge the potential FLASH_FIRMWARE region by 4kB.

**Comment by dhalbert** [comment]
Is it reserved for `microcontroller.nvm`?

**Comment by jepler** [comment]
ooh I should check on that. You're probably right.

**Comment by jepler** [comment]
in which case nvm might be using the wrong address right now
