### ISSUE TITLE
`nvm` module cannot be imported

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#7013]
### CircuitPython version

```python
At least 7.3.3 -- 8.0.0-alpha.1
```

### Code/REPL

```python
>>> import nvm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'nvm'
```

### Behavior

The `nvm` module exists to hold `ByteArray`, the type of `microcontroller.nvm`. However, since at least 7.3.3, this module has not been importable.

We should either remove it (it's largely useless, `type(microcontroller.nvm)` can be used in place of `nvm.ByteArray` for most purposes) or fix it by adding at the end of its file:
```diff
+MP_REGISTER_MODULE(MP_QSTR_nvm, nvm_module, CIRCUITPY_NVM);
```

Since nobody's called it out for being missing, I lean towards just dropping it. However, dropping it means that its type can't be mentioned for purposes of static typing.

**Comment by dhalbert** [comment]
I would say add it back, to avoid having anonymous types.
