### ISSUE TITLE
multiterminal module does not appear to be importable anywhere

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#7015]
### CircuitPython version

```python
8.0.0-alpha.1
```

### Code/REPL

```python
>>> import multiterminal
```

### Behavior

There's no CIRCUITPY_MULTITERMINAL to enable/disable it, no MP_REGISTER_MODULE, etc.

**Comment by dhalbert** [comment]
I think this was only ever used for ESP8266.
