### ISSUE TITLE
GPIO18 & GPIO45~48 definition at LOLIN S3

### ISSUE THREAD

**Issue by chukwon** [adafruit/circuitpython#7062]
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-beta.2 on 2022-10-14; LOLIN S3 16MB Flash 8MB PSRAM with ESP32S3
```

### Code/REPL

```python
import board
help(board)
```

### Behavior

object <module 'board'> is of type module
  __name__ -- board
  board_id -- lolin_s3
  BUTTON -- board.BUTTON
  BOOT0 -- board.BUTTON
  IO0 -- board.BUTTON
  D0 -- board.BUTTON
  IO1 -- board.IO1
  A0 -- board.IO1
  D1 -- board.IO1
  IO2 -- board.IO2
  A1 -- board.IO2
  D2 -- board.IO2
  IO3 -- board.IO3
  A2 -- board.IO3
  D3 -- board.IO3
  IO4 -- board.IO4
  A3 -- board.IO4
  D4 -- board.IO4
  IO5 -- board.IO5
  A4 -- board.IO5
  D5 -- board.IO5
  IO6 -- board.IO6
  A5 -- board.IO6
  D6 -- board.IO6
  IO7 -- board.IO7
  A6 -- board.IO7
  D7 -- board.IO7
  IO8 -- board.IO8
  A7 -- board.IO8
  D8 -- board.IO8
  IO9 -- board.IO9
  A8 -- board.IO9
  D9 -- board.IO9
  IO10 -- board.IO10
  A9 -- board.IO10
  D10 -- board.IO10
  IO11 -- board.IO11
  MOSI -- board.IO11
  A10 -- board.IO11
  D11 -- board.IO11
  IO12 -- board.IO12
  SCK -- board.IO12
  A11 -- board.IO12
  D12 -- board.IO12
  IO13 -- board.IO13
  MISO -- board.IO13
  A12 -- board.IO13
  D13 -- board.IO13
  IO14 -- board.IO14
  A13 -- board.IO14
  D14 -- board.IO14
  IO15 -- board.IO15
  A14 -- board.IO15
  D15 -- board.IO15
  IO16 -- board.IO16
  A15 -- board.IO16
  D16 -- board.IO16
  IO17 -- board.IO17
  A16 -- board.IO17
  D17 -- board.IO17
  IO18 -- board.IO17
  A17 -- board.IO17
  D18 -- board.IO17
  IO21 -- board.IO21
  D21 -- board.IO21
  IO38 -- board.IO38
  D38 -- board.IO38
  NEOPIXEL -- board.IO38
  IO39 -- board.IO39
  D39 -- board.IO39
  IO40 -- board.IO40
  D40 -- board.IO40
  IO41 -- board.IO41
  SCL -- board.IO41
  D41 -- board.IO41
  IO42 -- board.IO42
  SDA -- board.IO42
  D42 -- board.IO42
  IO43 -- board.IO43
  D43 -- board.IO43
  TX -- board.IO43
  IO44 -- board.IO44
  D44 -- board.IO44
  RX -- board.IO44
  I2C -- <function>
  STEMMA_I2C -- <function>
  SPI -- <function>
  UART -- <function>

### Description

IO18(/A17/D18) incorrectly points to IO17;
Missing IO45~IO48.

**Comment by dhalbert** [comment]
We would welcome a pull request to fix.
