### ISSUE TITLE
Pico W wifi.radio.ipv4_address behaviour does not match the documentation.

### ISSUE THREAD

**Issue by BiffoBear** [adafruit/circuitpython#7072]
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-beta.2-9-g5192082e6 on 2022-10-16; Raspberry Pi Pico W with rp2040
```

### Code/REPL

```python
import wifi

print()
print(f"ipv4_gateway    : {wifi.radio.ipv4_gateway}")
print(f"ipv4_subnet     : {wifi.radio.ipv4_subnet}")
print(f"ipv4_address    : {wifi.radio.ipv4_address}")
print(f"ipv4_dns        : {wifi.radio.ipv4_dns}")
```

### Behavior

```
ipv4_gateway    : 192.168.0.1
ipv4_subnet     : 255.255.255.0
ipv4_address    : 0.0.0.0
ipv4_dns        : 8.8.8.8
```

### Description

The documentation for the 'wifi' module state that these 4 properties will return `None` if not connected to an AP.

e.g. "IP v4 Address of the station gateway when connected to an access point. None otherwise."

They all return values other than none when not connected.

**Comment by anecdata** [comment]
Tested that address, gateway. subnet, and dns all now go to `None` after an existing connection [fails](https://github.com/adafruit/circuitpython/issues/6996#issuecomment-1281747848).
