### ISSUE TITLE
Pico W PulseIn not working on GP26

### ISSUE THREAD

**Issue by HelenFoster** [adafruit/circuitpython#7078]
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-beta.2-9-g5192082e6 on 2022-10-16; Raspberry Pi Pico W with rp2040
```

### Code/REPL

```python
>>> import board
>>> import pulseio
>>> p = pulseio.PulseIn(board.GP26)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: GPIO29 in use
>>> import digitalio
>>> d = digitalio.DigitalInOut(board.GP26)
>>>
```

### Behavior

PulseIn is confusing GP26 with GP29? But DigitalInOut is OK.

### Additional information

Works on Beta 1, but not Beta 2 or latest. Pi Pico on Beta 2 is OK.

**Comment by jepler** [comment]
I'll look into this in detail soon.

There's some confusion around "ignored" GPIOs and "TOTAL_GPIO_COUNT" that I have created, and it needs to be cleaned up. It's probably at the root of this issue.
