### ISSUE TITLE
set_ipv4_address NotImplemented on Pico W

### ISSUE THREAD

**Issue by talavrahami99** [adafruit/circuitpython#7085]
Getting the following error on set_ipv4_address line:
TypeError: extra positional arguments given

Code is below. Creating ipaddress objects as specified in the documentation for the wifi module. ipaddress objects are created correctly.

```py
dic = {}
with open('PCATS_WID_CONFIG.ini') as f:
    lines = f.readlines()
    for line in lines:
        if line[0] is not '#':
            line = line.strip()
            key = line.split(':')[0].lower()
            value = line.split(': ')[1]
            dic[key] = value

ip = ipaddress.ip_address(dic["ip"])
netmask = ipaddress.ip_address(dic["netmask"])
gateway = ipaddress.ip_address(dic["gateway"])
#print(ip,netmask,gateway)

wifi.radio.set_ipv4_address(ip,netmask,gateway) # LINE ERROR OCCURS ON
wifi.radio.connect(dic["ssid"],dic["password"])
```

**Comment by talavrahami99** [comment]
Hi,

Thank you for the response. Is there a timeline for when this function
might be implented on the Pico W?

Kind regards,
Tal

**Comment by jepler** [comment]
It's implemented now, if you grab the very latest builds or wait for the next beta release. If you do please let us know if it worked for you, either here or (it it's not working for you) in a fresh issue

**Comment by talavrahami99** [comment]
I've now tested this function on beta.3 and it seems to be working fine.
Thank you.

Kind regards,
Tal
