### ISSUE TITLE
Add touchscreen support for esp32-s3-box

### ISSUE THREAD

**Issue by PaulskPt** [adafruit/circuitpython#7095]
The Espressif [ESP32-S3-Box (Adafruit #5290)](https://www.adafruit.com/product/5290) (version 2.5, this is) has a touchscreen.

![esp32-s3-box_at_Adafruit_description](https://user-images.githubusercontent.com/9107950/197180652-fe4f9970-f0cb-4d68-ac1c-2addf3550455.png)

However, as far as my experience goes, CicruitPython V8.0.0-beta.2, does not offer support for the touchscreen of the esp32-s3-box.
I would like the Adafruit CircuitPython team to add `touchscreen support` for this board,
so I can add this functionality to my [CPY project](https://github.com/PaulskPt/ESP32-S3-Box_MSFS2020_GPSout_GPRMC_and_GPGGA) and future projects too.

I studied the source listings for the esp32-s3-box on: [https://github.com/espressif/esp-box](url)

REPL output in the `README.md` of an  [image demo](https://github.com/espressif/esp-box/tree/master/examples/image_display) script shows:

![esp-box_image_demo_REPL_output_v2](https://user-images.githubusercontent.com/9107950/197194668-259b00fc-bc9b-4f0a-9a29-d8da193cd298.png)

In the file: [esp32_s3_box.c](https://github.com/espressif/esp-box/blob/master/components/bsp/src/boards/esp32_s3_box.c), there are these two parts: 

![esp32-s3-box_components_bsp_src_boards_esp32_s3_box c__](https://user-images.githubusercontent.com/9107950/197187463-ca4a4711-e519-4e7e-bb20-e842fdcbf595.png)

In the file [bsp_board.h](https://github.com/espressif/esp-box/blob/master/components/bsp/include/bsp_board.h) are also - among otherrs - the definitions for: `TOUCH_PANEL_I2C_ADDR`, `GPIO_I2C_SCL GPIO_I2C_SCL ` and `GPIO_I2C_SDA `.

From this all it is clear that the touchscreen panel is connected to the CPU via I2C.

According to the REPL output from the `image demo`  (see above) the touchscreen controller is a device from [Parade Tech](https://www.paradetech.com/products/tt21xxx/)
The product page for the [tt21xxx](https://www.paradetech.com/products/tt21xxx/) shows that the interface to the touchscreen controller is via I2C/SPI.

In the file: [touch panel defs ft5x06.c](https://github.com/espressif/esp-box/blob/master/components/i2c_devices/touch_panel/ft5x06.c) are - among others - defined: 

![esp32-s3-box_extract_fm_ft5x06 c_](https://user-images.githubusercontent.com/9107950/197193644-8c2bf35a-36c9-420a-9715-764d7c3c76b5.png)

The board module of CircuitPython V8.0.0-beta.2 for the esp32-s3-box doesn't contain attributes like:
` board.TOUCH_XL,  board.TOUCH_XR,   board.TOUCH_YD,  board.TOUCH_YU, `

So, in this moment, one cannot implement touch functionality for this device using the latest version of CircuitPython.

**Comment by dhalbert** [comment]
The touch controller is I2C, and its I2C pins are attached to the standard I2C pins (GPIO8 and 18), it looks like, on the schematic. So a library for the touch controller should be usable from CircuitPython now. We have a TT21010 library: <https://github.com/adafruit/Adafruit_CircuitPython_TT21100>.

We wouldn't add those definitions to `board`, etc., they would just be in the library.

**Comment by PaulskPt** [comment]
OK, Dan, thank you very much!  Yes, I saw also in the definitions that I showed above that pins GPIO8 and 18 were assigned. I am going to try it.

**Comment by PaulskPt** [comment]
Touch is working! 

![2022-10-21_21h00_MSFS2020_GPRMC-GPGGA_rx_touch_is_working](https://user-images.githubusercontent.com/9107950/197279982-7bc14584-66c5-46da-b81a-6db10d6450f1.png)

Again, thank you Dan! Closing this feature request.
