### ISSUE TITLE
Circuitpython README.rst  link to Read the Docs (section Documentation) redirects to Error 403 forbidden page

### ISSUE THREAD

**Issue by PaulskPt** [adafruit/circuitpython#7121]
### CircuitPython version

```python
Current
```

### Code/REPL

```python
not relevant
```

### Behavior

![2022-10-25_17h48pt_Github_CircuitPython_README_link_to_readthedocs_broken](https://user-images.githubusercontent.com/9107950/197837902-075a9362-bbd9-4d9f-b71d-c79163c691a4.png)

### Description

On the README page ```https://github.com/adafruit/circuitpython```, README.rst, under ```Documentation```,  I clicked on the link ```Read The Docs``` (http://circuitpython.readthedocs.io/en/latest/?) . I 'landed' on an error page saying ```403 Forbidden```. (see the annotated screenshot above).

### Additional information

I used webbrowser Chrome in MS Windows 11.
I double-checked with browser Microsoft Edge. Same result.

**Comment by PaulskPt** [comment]
The problem seems to be inside the https://docs.circuitpython.org/en/latest/shared-bindings/index.html.
If I enter a search term it redirects me to 403 forbidden. When I click on on of the items listed on the page, e.g. ```adapter```, ```BluetoothError``` or ```RoleError```, the same happens.

**Comment by jepler** [comment]
I can't reproduce here.  I visited https://docs.circuitpython.org/en/latest/README.html then entered RoleError and selected the first/only hit. This took me to https://docs.circuitpython.org/en/latest/shared-bindings/_bleio/index.html#bleio.RoleError which displays in my browser 

If I click the link RoleError (not using search) then it also works, linking me to the same page and anchor https://docs.circuitpython.org/en/latest/shared-bindings/_bleio/index.html#bleio.RoleError

My browser is Firefox 105.0.3 on Debian Linux. Besides on my home internet in the midwest US, I also tried `curl -I` from DigitalOcean droplets in their NYC and SFO datacenters and got "HTTP/2 200" responses, which indicate success.

![image](https://user-images.githubusercontent.com/1517291/197848256-e80930ff-ff7f-4ea3-b6e7-29d9a1fdacb6.png)
![image](https://user-images.githubusercontent.com/1517291/197848371-34871cf8-1366-457f-a007-ee4ca9d87c13.png)

**Comment by jepler** [comment]
It doesn't match the symptoms you reported, but it's notable that cloudflare recorded an outage today. The incident report states that there were "[Increased HTTP 530 Errors](https://www.cloudflarestatus.com/incidents/kdpqngcbbn25)" and was resolved earlier today.

**Comment by PaulskPt** [comment]
Hi Jeff, thank you! You're right. I just checked, now that link works. I just saw on the Portuguese TV that there was here also an outage of WhatsApp. So I close this issue.
