### ISSUE TITLE
ESP32C3 XIAO CircuitPython 8.0.0-beta.4

### ISSUE THREAD

**Issue by WULFFJ** [adafruit/circuitpython#7158]
### CircuitPython version

```python
ESP32C3 XIAO CircuitPython 8.0.0-beta.4
```

### Code/REPL

```python
N/A Can't upload or doing anything else, so its pointless.
```

### Behavior

Issues:

Timeout error still happening.

Thonny file upload of anything larger than read me locks up from 7-30%.  (Edited 10-31-2022 - with building from main some Python scripts can be uploaded but its not consistent.  With Beta 4, scripts cannot be uploaded or I didn't try it enough to see if it would do it occasionally).

MUEditor only brings up REPL.  Files cannot be uploaded.  You have to have it on CircuitPython setting. 

ESPWebTool - the newer one will get to the upload portion and freeze.

ESPWebTool (OLD) - You can upload, but its not going to work with anything.

ESPTool gets the most functionality of any solutions to do any of the above. (Edit for clarity - this is the upload method that saw the best results and could occasionally upload with Thonny.)

Can't have anything USB plugged in or any software running besides the one you are using at the time.  Must run Thonny or MU in administrator mode in Windows.

Errors - 
PROBLEM IN THONNY'S BACK-END: Internal error (serial.serialutil.SerialTimeoutException: Write timeout).
See Thonny's backend.log for more info.
You may need to press "Stop/Restart" or hard-reset your MicroPython device and try again.)

PROBLEM IN THONNY'S BACK-END: Exception while handling 'upload' (thonny.plugins.micropython.mp_back.ProtocolError: Could not complete raw paste).

### Description

I have also tried just building the main branch in WSL.  The directions leave a bit to the imagination about the rest of the process.  Am I supposed to upload just one of the firmware files after it makes?  That did not work.

I really need to get this going, if you gave questions, I will be glad to assist.

**Comment by dhalbert** [comment]
Did this used to work in beta.1 or beta.2?

**Comment by WULFFJ** [comment]
> Did Thonny used to be able to upload larger files in beta.1 or beta.2?

No.  My whole experience with all of this has been terrible.  Even when it works, it does nothing reliable.  I have had the other Xiao boards and no issues.  Its not just Thonny either.  

It appears to be something related to pyserial from the error. \serialwin32.py", line 325, in write
    raise SerialTimeoutException('Write timeout')

I suspect something with this is causing issues with everything but the flashing of the board.  It seems to flash fine on ESPtool or the old online ESP web tool.

Anything uploading causes me issues (Thonny)
Cant ever see the files to upload in MU

Is there any other software for file management or something I can try?  I have beat my head for two weeks now with this thing.



> Did Thonny used to be able to upload larger files in beta.1 or beta.2?

No.  My whole experience with all of this has been terrible.  Even when it works, it does nothing reliable.  I have had the other Xiao boards and no issues.  Its not just Thonny either.  

It appears to be something related to pyserial from the error. \serialwin32.py", line 325, in write
    raise SerialTimeoutException('Write timeout')

I suspect something with this is causing issues with everything but the flashing of the board.  It seems to flash fine on ESPtool or the old online ESP web tool.

Anything uploading causes me issues (Thonny)
Cant ever see the files to upload in MU

Is there any other software for file management or something I can try?  I have beat my head for two weeks now with this thing.

**Comment by WULFFJ** [comment]
I have found one of the big issues I was having with the XIAO esp32c3.  You have to have the antenna attached for it to work with the webserial.  It also seems to have an affect on every other means of interacting with it.  I am not sure why this is, but was able to get MU Editor to work pretty consistently.  The adafruit webserial works now and is pretty reliable.  Thonny is still not working with this.

**Comment by dhalbert** [comment]
> I have found one of the big issues I was having with the XIAO esp32c3. You have to have the antenna attached for it to work with the webserial.

!!

**Comment by camp-easy** [comment]
why my  xiao esp32c3 board doesn't get recognized by mu editor but it's ok with Thonny?

**Comment by dhalbert** [comment]
> why my xiao esp32c3 board doesn't get recognized by mu editor but it's ok with Thonny?

The ESP32-C3 chip does not have full native USB. It cannot present as the CIRCUITPY USB drive. Mu only works when a USB drive is available. Thonny reads and writes files by sending invisible (to you) commands to the REPL over USB serial.
