### ISSUE TITLE
/code doesn't work with web workflow on different port

### ISSUE THREAD

**Issue by jasonehines** [adafruit/circuitpython#7168]
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-beta.4 on 2022-10-30; Adafruit Feather ESP32 V2 with ESP32
```

### Code/REPL

```python
not code related
```

### Behavior

'''Unable to connect. The device [local IP address] was not found. Be sure it is plugged in and set up properly.'''

### Description

I changed the default port (CIRCUITPY_WEB_API_PORT) to 8080 and the /code/ interface gives the error about

**Comment by tannewt** [comment]
I believe /code/ is served by code.circuitpython.org and will need an update.

**Comment by tannewt** [comment]
This works now. Thanks @makermelissa
