### ISSUE TITLE
Enable BLE (_bleio) for the original suffix-less ESP32

### ISSUE THREAD

**Issue by Neradoc** [adafruit/circuitpython#7170]
An issue for reference, as I haven't found one.
This is not the same as #5926 as it's for support of the ESP32, not about the features of BLE on espressif.

**Comment by dhalbert** [comment]
So you mean just turning on the current partial support?

**Comment by Neradoc** [comment]
Yes, whatever is needed to make turning `CIRCUITPY_BLEIO` to 1 in `mpconfigport.mk` to work.

**Comment by jepler** [comment]
It looks like simply setting it to =1 doesn't work...
```
-- Build files have been written to: /home/jepler/src/circuitpython/ports/espressif/build-adafruit_feather_esp32_v2/esp-idf
ninja: Entering directory `build-adafruit_feather_esp32_v2/esp-idf'
ninja: error: unknown target 'esp-idf/bt/libbt.a'
```

**Comment by vladak** [comment]
#8776 also seeks BLE support for plain ESP32.
