### ISSUE TITLE
can i start_ap() without connecting to a network?

### ISSUE THREAD

**Issue by vithp** [adafruit/circuitpython#7172]
I am using the Pico W and i want to make a portable web server. For instance after you connect to the access point you can view local website. However that i have seen, it seems impossible to just create an ap without connecting to a network first.

**Comment by anecdata** [comment]
There is no AP on Pico W currently, follow any progress here:
https://github.com/adafruit/circuitpython/pull/7101

But you can run an HTTP server (or other type of TCP / UDP server) as a wifi client.

The best place for support questions like this is https://adafru.it/discord

**Comment by vithp** [comment]
will it be added for the Pico W? i had seen on the documentation that the Pico W was a supported board for the wifi module>

**Comment by anecdata** [comment]
Station (wifi client of an external AP) for Pico W is supported, same basic API as for `espressif` boards.

Follow the PR mentioned above for progress on AP for Pico W.

**Comment by vithp** [comment]
ahh thank you i might use stations until it is available
