### ISSUE TITLE
** expression extremely slow compared to math.pow()

### ISSUE THREAD

**Issue by educ8s** [adafruit/circuitpython#7174]
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-beta.4 on 2022-10-30; Raspberry Pi Pico with rp2040
```

### Code/REPL

```python
import math, time

def calculate_pi(n):
    """
    Calculate the value of pi using the Bailey–Borwein–Plouffe formula.
    """
    pi = 0
    k = 0
    while k < n:
        pi += (1 / (16 ** k)) * ((4 / (8 * k + 1)) - (2 / (8 * k + 4)) - (1 / (8 * k + 5)) - (1 / (8 * k + 6)))
        k += 1
    return pi

def calculate_pi_pow(n):
    """
    Calculate the value of pi using the Bailey–Borwein–Plouffe formula.
    """
    pi = 0
    k = 0
    while k < n:
        pi += (1 / math.pow(16,k)) * ((4 / (8 * k + 1)) - (2 / (8 * k + 4)) - (1 / (8 * k + 5)) - (1 / (8 * k + 6)))
        k += 1
    return pi

print("Running the algorithm using math.pow()")
start_time = time.monotonic()
pi = calculate_pi_pow(1500)
end_time = time.monotonic()
execution_time = round(end_time - start_time,4)
print(f"Result: {pi}")
print(f"Execution time math.pow(): {execution_time}")

print("\nRunning the algorithm using **")
start_time = time.monotonic()
pi = calculate_pi(1500)
end_time = time.monotonic()
print(f"Result: {pi}")
execution_time = round(end_time - start_time,4)
print(f"Execution time **: {execution_time}")
```

### Behavior

The output of the above script is the following:

Running the algorithm using math.pow()
Result: 3.14159
Execution time math.pow(): 0.177

Running the algorithm using **
Result: 3.14159
Execution time **: 6.0811

The ** expression is very slow compared to the math.pow() function.

I am running the same Pi aproximation algorithm for 1500 iterations.

The algorithm using the ** expression needs 6 secs while the algorithm using the math.pow() function needs 0.17secs.
The speed difference is huge. Also, the ** consumes a lot of memory in each iteration.

### Description

Hello there, I discovered something strange while doing some testing with CircuitPython today.
I was testing this code I wrote some time ago https://github.com/educ8s/CircuitPython-Pi-Calculation-Benchmark

This script calculates the Pi using an approximation algorithm.
I ported the code in C to run on an Arduino Nano and I noticed something strange.
The execution time of the script was linear depending on how many iterations of the algorithm I was doing.
On CircutPython on the other hand the execution time grew exponentially
and the memory usage grew on each iteration
That's the code of the algorithm:

def calculate_pi(n):
    """
    Calculate the value of pi using the Bailey–Borwein–Plouffe formula.
    """
    pi = 0
    k = 0
    while k < n:
        pi += (1 / (16 ** k)) * ((4 / (8 * k + 1)) - (2 / (8 * k + 4)) - (1 / (8 * k + 5)) - (1 / (8 * k + 6)))
        k += 1
    return pi

After a lot of testing I found out the culprit. It is this experession: 16 ** k
I replaced it with math.pow(16,k)
and I now have linear performance and no memory increase at all. Also the speed diference is huge.
For 1500 iterations the scipt needed 6.8sec with the ** expression and only 0.2 sec with math.pow function.

### Additional information

This is not a CircuitPython 8 problem. The same thing happens on CircuitPython 7 as well.

_No response_

**Comment by jepler** [comment]
The types of the expressions are different.  Python and CircuitPython represent ints (integers) exactly, but the memory storage and computation time increases according to the length of the number; floats always use a constant amount of storage but don't represent values exactly: 
```py
>>> type(16**k)
<class 'int'>
>>> type(pow(16, k))
<class 'float'>
```
you can also write `16.**k` so that the power operation is done as a floating point calculation rather than an integer calculation.
