### ISSUE TITLE
CircuitPython Mouse HID Movement Units?

### ISSUE THREAD

**Issue by gabriel-wainmann** [adafruit/circuitpython#7187]
### CircuitPython version

```python
Hi

Have no idea what the units of the mouse movement are: pixels? relative something?
Also, when going back and forth can't get to the same place, which is strange.

Help please.
```

### Code/REPL

```python
-
```

### Behavior

-

### Description

-

### Additional information

-

**Comment by dhalbert** [comment]
mouse is just emulating a regular mouse. It is just requesting to "move this many units" in X and/or Y.  This is how a regular mouse works. It's up to the host computer to interpret that. And if you move larger distances, you will invoke the acceleration algorithm on the host computer, which is perhaps why you are not going back to the same place.

**Comment by dhalbert** [comment]
This kind of support q is better asked in https://adafru.it/discord or https://forums.adafruit.com/viewforum.php?f=60

**Comment by gabriel-wainmann** [comment]
Thank you @dhalbert
