### ISSUE TITLE
ESP32-S2 Failure to run code.py

### ISSUE THREAD

**Issue by TrevKnows** [adafruit/circuitpython#7189]
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-beta.4 on 2022-08-29; Adafruit Feather ESP32S2 with ESP32S2
Board ID:adafruit_feather_esp32s2
```

### Code/REPL

```python
# SPDX-FileCopyrightText: 2021 Kattni Rembor for Adafruit Industries
# SPDX-License-Identifier: MIT
"""CircuitPython status NeoPixel red, green, blue example."""
import time
import board
import neopixel

pixel = neopixel.NeoPixel(board.NEOPIXEL, 1)

pixel.brightness = 0.3

while True:
    pixel.fill((255, 0, 0))
    time.sleep(0.5)
    pixel.fill((0, 255, 0))
    time.sleep(0.5)
    pixel.fill((0, 0, 255))
    time.sleep(0.5)
```

### Behavior

The code.py file doesn't run.
![IMG_0995](https://user-images.githubusercontent.com/6743263/201187672-72f6fe05-3c50-47de-8576-3c3289e3b278.jpg)

Wifi stops working randomly.

The board will randomly enter boot mode.
![IMG_0998](https://user-images.githubusercontent.com/6743263/201187145-91e22c36-8191-4f70-bfc8-813100e14dbc.jpg)

### Description

Since I’ve updated the board, the screen has been blank and doesn’t run code.py. I cannot detect the board on my local wifi network randomly. I’ve attempted to try using CircuitPython 8.0.0-beta.4 on a board running CircuitPython 7.3, but I was met with the same results. 

### Additional information

These are the steps I took to run into this issue:
- Connected the  ESP32-S2 to my MacBook
- I put the board into boot mode
- Added the CircuitPython 8.0.0-beta.4 .uf2 file to the board

**Comment by dhalbert** [comment]
Side conversation determined that the wrong firmware was being loaded (plain Feather ESP32-S2 instead of TFT version)
