### ISSUE TITLE
Replace Display.show() with assignment to Display.root_group

### ISSUE THREAD

**Issue by deshipu** [adafruit/circuitpython#7213]
Pretty much all the `Display.show()` does is setting the root group for the display. However, some users are confused about how this works, and call in a loop on every refresh, or expect it to do something else. Now that we have the `Display.root_group` property, we could replace that method with just a direct assignment to that property. Hopefully, it would make it a little bit clearer how it works.

This would be an API change, so it would require changes in the documentation, example code, and eventually existing user code, so it's not a decision to be made lightly, but I think it would be an improvement.

**Comment by dhalbert** [comment]
We can do this upwardly compatible in 8.0.0 and then drop `.show()` in 9.0.0, so, as @tannewt mentioned in discord, let's do this by 8.0.0 final.

**Comment by dglaude** [comment]
It would be interesting to see how would the code looks like before and after this change... with one simple example. At least it will help me better understand, and maybe discover that I have done things wrong all this time.

**Comment by FoamyGuy** [comment]
@dglaude My understanding is the difference would look like this:

```
import board
import displayio

display = board.DISPLAY

# Setup the file as the bitmap data source
bitmap = displayio.OnDiskBitmap("/purple.bmp")

# Create a TileGrid to hold the bitmap
tile_grid = displayio.TileGrid(bitmap, pixel_shader=bitmap.pixel_shader)

# Create a Group to hold the TileGrid
group = displayio.Group()

# Add the TileGrid to the Group
group.append(tile_grid)

# Add the Group to the Display
# display.show(group)  # old version, call show(), wont do it this way any more
display.root_group = group  # new version, set object as the root_group property on the Display object

# Loop forever so you can enjoy your image
while True:
    pass

```

**Comment by deshipu** [comment]
Alternatively, you don't even need the `group` variable:
```python
import board
import displayio

display = board.DISPLAY

# Setup the file as the bitmap data source
bitmap = displayio.OnDiskBitmap("/purple.bmp")

# Create a TileGrid to hold the bitmap
tile_grid = displayio.TileGrid(bitmap, pixel_shader=bitmap.pixel_shader)

# Create a Group to hold the TileGrid
display.root_group = displayio.Group()

# Add the TileGrid to the Group
display.root_group.append(tile_grid)

# Loop forever so you can enjoy your image
while True:
    pass
```

Unfortunately you can't pass initial contents when creating the group, otherwise it could be even something like:

```python
display.root_group = displayio.Group([tile_grid])
```

**Comment by FoamyGuy** [comment]
I made a branch here: https://github.com/FoamyGuy/circuitpython/tree/set_root_group that allows setting the root_group property on the display. It will certainly still need some work, this is the bare minimum to allow setting. The most basic case of making a group and showing on the display seems to be working as intended but only minimal testing so far.

**Comment by Neradoc** [comment]
How would it work with show(None) which normally resets the display to show the terminal ? Would `display.root_group = None` set the root group to the terminal ? Isn't it weird that setting a property to None yields a different value ?

**Comment by FoamyGuy** [comment]
Yes `display.root_group = None` will show the terminal. 

It agree is a bit strange that setting to `None` has some effect other than "show nothing", but it's the same in the current API calling `show(None)` results in the terminal showing.

Perhaps there could be something like `displayio.TERMINAL_GROUP` or similar as a constant that is either an alias for None, or a new constant value that is used to indicate you want to show the terminal instead of other displayio objects, something like that would make the resulting code more readable and better describe what it does.

**Comment by deshipu** [comment]
> Perhaps there could be something like displayio.TERMINAL_GROUP or similar as a constant that is either an alias for None, or a new constant value that is used to indicate you want to show the terminal instead of other displayio objects, something like that would make the resulting code more readable and better describe what it does.

It could be the actual terminal group, since it is kept in memory anyways.

**Comment by FoamyGuy** [comment]
@deshipu nice, that is perfect. 

I've updated my branch to have `displayio.SERIAL_GROUP` that returns the internal `circuitpython_splash` group. I made a draft PR for it as well. I think it might make a few builds too large, will need to see how the actions shake out. Also possible it needs more changes still, I've done only the bare minimum to make it work I think.
