### ISSUE TITLE
update protomatter to support psram rgbmatrix

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#7228]
The author says "FYI: just made small change in Protomatter for ESP32-S3 to work correctly with PSRAM-equipped Feathers. I’m like 98% sure the change will compile fine w/CircuitPython, but mentioning just in case. This is in the 1.5.2 release on Github."

**Comment by PaintYourDragon** [comment]
Further critical fixes were made in that code today, now at version 1.5.3.
