### ISSUE TITLE
PWMOut Error on Raspberry Pi Pico W

### ISSUE THREAD

**Issue by dbisu** [adafruit/circuitpython#7238]
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-beta.4 on 2022-10-30; Raspberry Pi Pico W with rp2040
```

### Code/REPL

```python
import board
import pwmio

led = pwmio.PWMOut(board.LED, frequency=5000, duty_cycle=0)
```

### Behavior

```
>>> led = pwmio.PWMOut(pin, frequency=5000, duty_cycle=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Expected a Pin
```

### Additional information

Using digitalio.DigitalIO(board.LED) works correctly.

**Comment by dhalbert** [comment]
The LED pin on Pico W is not a regular pin. It is accessed through the CYW43 coprocessor and its firmware, and is not available for PWM use. Real pins like the regular GPIO physical pins _can_ be used with `PWMOut`. (The LED pin on the regular Pico works as you would expect.)

@jepler I am not sure if there's an improvable error message here or not.

**Comment by dbisu** [comment]
Oh, ok.  I was porting some code from the Pico to Pico W.  This explains the difference.  I'll refactor my code that handles the LED.
Thanks.

**Comment by jepler** [comment]
switch validate_obj_is_pin to use mp_arg_validate_type and make mp_arg_validate_type print the required type, so that the error is
```
>>> p = pwmio.PWMOut(board.LED)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: pin must be of type Pin, not CywPin
```
?

**Comment by dhalbert** [comment]
@jepler is your last comment a suggestion? We can move this away from Support.

**Comment by jepler** [comment]
Yes, I think a simple change could improve the error message
