### ISSUE TITLE
revamp supervisor allocation API

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#7334]
I have a sketch at https://github.com/jepler/circuitpython/commit/e635457a32b1cc3b4b611808fcdd16951d12f99c but it doesn't boot.

The idea is to do more to leverage the gc allocator to make the supervisor allocator work.

See the commit message for more details.

Entered as an issue at @tannewt 's request

I don't plan to work on this until after 8 is out, but it was in my brain and I had to do at least this much of it.

**Comment by tannewt** [comment]
So this always has the heap inited on allocation but then it tries to move movable allocations on init? Is there a period where it is deinited?

**Comment by jepler** [comment]
This may be mooted by the split heap code we'll take from micropython.

Yes, in this work there's a moment where the heap is deinited, but "supervisor allocations" are still live. Immediately after the heap is reinited, the supervisor allocations are then marked in use by magic / layer violation.
