### ISSUE TITLE
Fix error when trying to set cpu.frequency but not supported

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#7357]
According to [this forum post](https://forums.adafruit.com/viewtopic.php?p=952677#p952677) the error is "Attribute Error:
'Processor' object has no attribute 'frequency'" It should instead say it isn't settable. I suspect we need to remove the setter when setting isn't possible. The code now returns a NotImplementedException that is being caught internally and producing the error seen. So conditionalize this:

https://github.com/adafruit/circuitpython/blob/10138f43d62a90fa9d090c7eb4bdaaa087016abb/shared-bindings/microcontroller/Processor.c#L89-L91

Instead of this:

https://github.com/adafruit/circuitpython/blob/10138f43d62a90fa9d090c7eb4bdaaa087016abb/shared-bindings/microcontroller/Processor.c#L70-L78

**Comment by dhalbert** [comment]
I can add this to a similar PR I just made, #7358, which also had a confusing `AttributeError.`
