### ISSUE TITLE
minimqtt, not sure if minimqtt or circuitpython

### ISSUE THREAD

**Issue by schaefer01** [adafruit/circuitpython#7366]
Adafruit CircuitPython 7.3.3 on 2022-08-29; Adafruit Feather RP2040 with rp2040

hi,
my first attempt to use minimqtt to talk to a server on a wired lan returned the error:
AssertionError: Error: SSL/TLS is not currently supported by CircuitPython.
1. is this a circuitpython problem or a minimqtt problem
2. in either case, will SSL/TLS be supported in the future?

bob s.

**Comment by dhalbert** [comment]
I will close (without prejudice :) ) as this is subsumed by the other open issues.
