### ISSUE TITLE
CircuitPython 8 for Flipper Zero Wi-Fi Debugger Module (ESP32-S2-WROVER-N4R2)

### ISSUE THREAD

**Issue by saraceni-andrea** [adafruit/circuitpython#7421]
Hi, is there the possibility of a port of CircuitPython 8 for **Flipper Zero Wi-Fi Debugger Module** (ESP32-S2-WROVER-N4R2)?

https://docs.flipperzero.one/development/hardware/wifi-debugger-module
https://docs.flipperzero.one/development/hardware/wifi-debugger-module/schematics

Thanks!

**Comment by dhalbert** [comment]
It would not be hard to add a port; this is also a very plain board and one of the Espressif dev module boards or similar could work as is, without needing a special board definition.
