### ISSUE TITLE
Bump actions to use the newest gcc

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#7432]
arm's toolchain is up to gcc 12, it'd be nice to use it unless it introduces problems.

**Comment by tannewt** [comment]
I did this update [in a branch](https://github.com/tannewt/circuitpython/tree/update_gcc) and only one build is too big: https://github.com/tannewt/circuitpython/actions/runs/4298636837/jobs/7493054457#step:10:31

**Comment by dhalbert** [comment]
https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads

**Comment by bill88t** [comment]
I'm on gcc 13 already.
Only rp2 needs a one-line chance and it's good too.
