### ISSUE TITLE
time.monotonic value reset to zero after Deep Sleep

### ISSUE THREAD

**Issue by DaveSprague** [adafruit/circuitpython#7480]
### CircuitPython version

```python
Adafruit CircuitPython 7.3.3 on 2022-08-29; Adafruit CLUE nRF52840 Express with nRF52840
```

### Code/REPL

```python
import time
import alarm
from adafruit_clue import clue

sleep_time = 20 # seconds

clue_data = clue.simple_text_display(title="  DeepSleep Test", text_scale=2)

current_time = time.monotonic()
    
clue_data[2].text = f"MonoTime: {current_time:.3f}"
clue_data[4].text = f"SleepTime: {sleep_time:.1f}"
clue_data.show()

time.sleep(5)  # show the display for awhile before we go into deep sleep

time_alarm = alarm.time.TimeAlarm(monotonic_time=time.monotonic() + sleep_time)

alarm.exit_and_deep_sleep_until_alarms(time_alarm)
```

### Behavior

The display of the value returned by the time.monotonic() function is the time that's has elapsed since the processor came out of deep sleep.  I've confirmed this with both the nRF52840-based Clue board and the ItsyBitsy M4 (using different code that writes the monotonic time values to an external SD Card module).

The alarm.time.TImeAlarm function implies that the processor/board has access to the updating monotonic time value while in deep sleep since you pass it the "absolute" time that you want to come out of deep sleep (the current monotonic time plus the deep sleep time) but when you come out of deep sleep, the updating monotonic time is reset to zero.

I don't have any deep knowledge of the SAMD51 or the nRF52840 but both of them mention real-time clock/counter functions are supported in hardware.  Would it be feasible to maintain monotonic time through deep sleep with either of these processors when using Circuit Python?

### Description

I posted this issue as a question on the Adafruit CircuitPython forum and @dhalbert suggested I submit it as an issue here.

**Comment by jepler** [comment]
We updated the documentation to reflect that monotonic time is not guaranteed to persist after the interpreter exits, whether it's for reload, deep sleep, etc.
