### ISSUE TITLE
print redirect not supported

### ISSUE THREAD

**Issue by kattni** [adafruit/circuitpython#751]
The following line of code should send the data to the file created during `with open("/sd_card/log.txt", "a") as sdc:` in csv format:

`print(time_stamp, temperature, humidity, battery_voltage, sep=',', file=sdc)`

Instead it prints to the serial console in csv format, and does not print to the file.

We should throw an exception to show this is not supported.

**Comment by dhalbert** [comment]
Unknown keyword arguments now raise an exception.
