### ISSUE TITLE
espressif: use 'new' i2s API, not 'legacy'

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#7527]
In https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/api-reference/peripherals/i2s.html it is detailed that the legacy api using `i2s.h` is deprecated and may be removed in the future. Instead, a different API from `i2s_std.h` (or `i2s_pdm.h` for pdm) should be used now.

**Comment by MicroDev1** [comment]
The same is true for the following as well:
- [ ] ADC
- [ ] GPTIMER
- [ ] I2S
- [ ] PCNT
- [ ] RMT

**Comment by tannewt** [comment]
Done in #8435
