### ISSUE TITLE
Update CYW43 driver to latest

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#7596]

**Comment by bill88t** [comment]
When the merge happens I should retest picow-ap disconnection, should I not?

**Comment by gneverov** [comment]
If we use the cyw43 driver from inside the pico sdk, #7595 would automatically update cyw43 driver.

**Comment by dhalbert** [comment]
@jepler I have assigned myself #7595 and #7596. I will look at whether your changes to the cwy43 library are now incorporated. There are some interesting changes listed in the [1.5.0 release notes](https://github.com/raspberrypi/pico-sdk/releases/tag/1.5.0) about cyw43:

Do you think these will make a difference?

>  Blocking cyw43_arch_wifi_connect_ functions now continue trying to connect rather than failing immediately if the network is not found.

> [restructuring of pico_cyw43_driver]

The updated cyw43 driver code does not quite compile. I'll look further at that.
