### ISSUE TITLE
ssl: ssl_context.load_verify_locations(cadata=None) raises a TypeError

### ISSUE THREAD

**Issue by ide** [adafruit/circuitpython#7656]
### CircuitPython version

```python
Adafruit CircuitPython 8.0.3 on 2023-02-23; Raspberry Pi Pico W with rp2040
```

### Code/REPL

```python
import ssl

ssl_context = ssl.create_default_context()
ssl_context.load_verify_locations()
```

### Behavior

This code throws: `TypeError: can't convert 'NoneType' object to str implicitly`

### Description

The docs describe `cadata` as optional and that None is a valid value: https://docs.circuitpython.org/en/latest/shared-bindings/ssl/index.html#ssl.SSLContext.load_verify_locations. The use case for None is to disable client certificate verification when acting as a server: [`mbedtls_ssl_conf_authmode(&o->conf, MBEDTLS_SSL_VERIFY_NONE)`](https://github.com/adafruit/circuitpython/blob/f9831b3bbccdb29c438b30ec8908dbbaaeaaf791/ports/raspberrypi/common-hal/ssl/SSLSocket.c#LL186C9-L186C70) .

### Additional information

As a workaround, `ssl_context.load_verify_locations(cadata="")` appears to work.

**Comment by tannewt** [comment]
Looks like [`None` is the correct default value](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.load_verify_locations). We must not handle it quite right internally.
