### ISSUE TITLE
Split-string translate() not working

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#7661]
This split-string `translate()` message is not printed when I exercise this error.  Instead I just get `AttributeError:`.
https://github.com/adafruit/circuitpython/blob/8e4626ffba19a8cc18b6e80693f8b6429fbbd91f/shared-bindings/pwmio/PWMOut.c#L273-L275
There may be others like this.
I think we cannot split these due to some limitation in the translation processing?

**Comment by tannewt** [comment]
Ya, I don't think the tool that extracts the string can work on multiple lines.
