### ISSUE TITLE
Split displayio into `displaycore`, `externalframebufferio`, `framebufferdisplayio` and `epaperdisplaypio` (names TBD)

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#7667]
This will save space on boards that have an existing display and are unlikely to have an external epaper display (like pew pew m4).

**Comment by tannewt** [comment]
We should go further with this as we have more boards with displays that aren't supported by `displayio.Display()`. (Dotclock displays use `FramebufferDisplay` for example. We should split `displayio.Display` out as well as `Epaperdisplay`.

**Comment by tannewt** [comment]
`displayio.Display` support LCD and OLED displays that have driver ICs with onboard framebuffer RAM. We should rename it to reflect that.

Also, should we split out the different display busses as well?

**Comment by makermelissa** [comment]
> Also, should we split out the different display busses as well?

That makes sense because paralleldisplay is already split out unless it would be more overhead.

**Comment by deshipu** [comment]
Can we use `busdisplay` instead of `externalframebufferio`?

**Comment by tannewt** [comment]
> Can we use `busdisplay` instead of `externalframebufferio`?

Ya, totally open to different module names.
