### ISSUE TITLE
ATMEL M4 SPI transfer size truncated

### ISSUE THREAD

**Issue by gamblor21** [adafruit/circuitpython#7670]
### CircuitPython version

```python
Adafruit CircuitPython 8.1.0-alpha
Adafruit ItsyBitsy M4 Express with samd51g19
```

### Code/REPL

```python
display_bus.send(42, struct.pack(">hh", 0, 239))
display_bus.send(43, struct.pack(">hh", 80, 319))
display_bus.send(44, gif.bitmap)
```

### Behavior

When sending a large SPI transfer the transfer is truncated. @jepler found reference in the samd51 spec that the block transfer count size in DMA is limited to a 16 bit value which implies the maximum is 64Kb. No error message is raised.

### Description

Would be most useful to have the code detect and send larger transfers without the user seeing. Looks like you can chain transfer descriptors together to handle this situation.

**Comment by dhalbert** [comment]
Fixed by #7673.
