### ISSUE TITLE
wifi.radio.start_ap - Cannot set AuthMode because it is not iterable

### ISSUE THREAD

**Issue by dotpointer** [adafruit/circuitpython#7680]
### CircuitPython version

```python
Adafruit CircuitPython 8.0.2 on 2023-02-14; Adafruit Feather ESP32S2 with ESP32S2
```

### Code/REPL

```python
import wifi
# 1 - give it an AuthMode
wifi.radio.start_ap(ssid='Wireless', password='wireless', authmode=wifi.AuthMode.WPA2)
# 2 - give it an AuthMode inside an iterable list to make it iterable as requested
wifi.radio.start_ap(ssid='Wireless', password='wireless', authmode=[wifi.AuthMode.WPA2])
```

### Behavior

# 1 - It refuses and requests the AuthMode to be iterable
TypeError: 'AuthMode' object is not iterable
# 2 - It is not satisified even when it is iterable
ValueError: Invalid authmode

### Description

The AP mode refuses to use AuthMode other than the default open unencrypted mode.

The problem might be a usage/syntax error, please tell me if so and how to fix it.

The errors are translated from Swedish.

**Comment by dotpointer** [comment]
I found a solution, with WPA2 you also need to supply PSK:

`import`
`wifi.radio.start_ap(ssid='Wireless', password='wireless', authmode=[wifi.AuthMode.WPA2, wifi.AuthMode.PSK])`

**Comment by dhalbert** [comment]
The documentation signature is wrong, it should say `authmodes`, so reopening.

**Comment by dhalbert** [comment]
We should also maybe say that PSK is necessary.
