### ISSUE TITLE
AWS S3 CircuitPython 8.0.3 in incorrect location

### ISSUE THREAD

**Issue by bill88t** [adafruit/circuitpython#7681]
https://adafruit-circuit-python.s3.amazonaws.com/index.html?prefix=bin/mpy-cross/

All the mpy-cross'es for 8.0.3 are placed outside of their respective directories.
(They are not inside, just outside)

It should be checked as to if CI bugged or there was human intervention.

**Comment by dhalbert** [comment]
Turns out this is because the relocation was done on `main` after `8.0.x` was branched. Sorry for the false alarm.

**Comment by bill88t** [comment]
Alright, closing issue.
