### ISSUE TITLE
sdcardio - TypeError: extra keyword arguments given for baudrate

### ISSUE THREAD

**Issue by phantomsixthplayer** [adafruit/circuitpython#7688]
### CircuitPython version

```python
Adafruit CircuitPython 8.0.3 on 2023-02-23; Adafruit Grand Central M4 Express with samd51p20

adafruit-circuitpython-grandcentral_m4_express-en_GB-8.0.3.uf2
update-bootloader-grandcentral_m4-v3.15.0.uf2
```

### Code/REPL

```python
class HiscoreController:
    def __init__(self):
        pass

    def hiscore(self):
        spi = busio.SPI(board.SD_SCK, board.SD_MOSI, board.SD_MISO, baudrate=500000)
        sdcard = sdcardio.SDCard(spi, board.SD_CS)
        vfs = storage.VfsFat(sdcard)
        storage.mount(vfs, "/")
```

### Behavior

```
TypeError: extra keyword arguments given
```

### Description

Can't set the baudrate, has this property been removed?

### Additional information

baudrate (int) – The SPI data rate to use after card setup
https://docs.circuitpython.org/en/latest/shared-bindings/sdcardio/index.html

**Comment by jepler** [comment]
It looks like in your code you are supplying the `baudrate=` argument to `busio.SPI` rather trhan `sdcardio.SDCard`.

Note that usually it would be recommended to set up the SD card once, and to use a mount point like '`/sd`', but while this would be good to keep in mind it doesn't seem to be related to the specific exception that your code caused.

The forums or our discord are better places to ask for help with your circuitpython programs.

**Comment by phantomsixthplayer** [comment]
> It looks like in your code you are supplying the `baudrate=` argument to `busio.SPI` rather trhan `sdcardio.SDCard`.
> 
> Note that usually it would be recommended to set up the SD card once, and to use a mount point like '`/sd`', but while this would be good to keep in mind it doesn't seem to be related to the specific exception that your code caused.
> 
> The forums or our discord are better places to ask for help with your circuitpython programs.

ah mind was in daze reading sdcard everywhere, thanks.

Thanks for the tip re calling it one. For anyone who comes across this if you don't specific "/sd" or another folder and also have files on your grand central root for example you will get errors OSError: [Errno 2] No such file/directory: /fonts/test.pcf if the sdcard is called before the font.
