### ISSUE TITLE
unable to use rshell with 8.0.3 but OK with 8.1.0-beta.0

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#7720]
I'm not sure this is really an "issue" since it appears to have been resolved in 8.1.0-beta.0 but I wanted to bring it to your attention.
A forum post reported an issue using rshell with 8.0.3. on a feather esp32 v2.  In general, you do have to download and install rshell from GitHub to get a necessary fix that has been merged but not released. https://github.com/dhylands/rshell 
I showed the original poster that rshell did work OK but I was using 8.1.0-beta.0 and they still reported an error with 8.0.3. I then reverted to 8.03 and was able to reproduce the error.
After reinstalling 8.1.0-beta.0 it now works again.

Here is a link to the forum post https://forums.adafruit.com/viewtopic.php?p=964655#p964655 with some examples.

It is not obvious to me what "fixed" this in 8.1.0-beta.0 but I though it worth reporting.

**Comment by jerryneedell** [comment]
Thanks -- No need to keep this open.

**Comment by tannewt** [comment]
@Neradoc should we make it not translated?
