### ISSUE TITLE
The module contents are repeated in the tree

### ISSUE THREAD

**Issue by microdev1** [adafruit/circuitpython#7727]
Is this the intended behavior?
   
![docs-issue](https://user-images.githubusercontent.com/70126934/225199089-6374b474-4501-405d-8f59-ad671377df7d.png)

**Comment by tannewt** [comment]
I don't think that's intended.

**Comment by microdev1** [comment]
Did something change? The non-boxed versions have disappeared.

**Comment by Neradoc** [comment]
Comparing the logs of the last run and one a day ago, I see sphinx autoapi 2.1.0 has been released.
And this PR might be relevant:
https://github.com/readthedocs/sphinx-autoapi/pull/374

> Sphinx 5.2.0 adds domain objects to the toctree by default. This is causing duplicate entries to appear in the table of contents when autoapi is in use, since autoapi also adds domain objects to the toctree by default (e.g. #369). It seems sensible to allow sphinx to handle the addition of domain objects to the toctree instead of post-processing it ourselves in autoapi.
> 
> If merged, this PR will cause autoapi to defer to sphinx to handle adding domain objects to the toctree.

**Comment by microdev1** [comment]
> This last PR merged is relevant: https://github.com/readthedocs/sphinx-autoapi/pull/374

Okay, so this can be closed now.
