### ISSUE TITLE
[Git] Latest master cannot `make fetch-submodules`

### ISSUE THREAD

**Issue by bill88t** [adafruit/circuitpython#7786]
On 57ac9aa763587221c2bf55dce746bd50e58159dd, which is current Master, I cannot `make fetch-submodules`.
```
fatal: remote error: upload-pack: not our ref 2b9354539e6e4f722749e87b0bdc22966dc080d9
fatal: Fetched in submodule path 'ports/mimxrt10xx/sdk', but it did not contain 2b9354539e6e4f722749e87b0bdc22966dc080d9. Direct fetching of that commit failed.
make: *** [Makefile:332: fetch-submodules] Error 128
```
Running `git submodule deinit --all -f` doesn't help.

**Comment by microdev1** [comment]
Try removing it from `.git` directory `circuitpython/.git/modules/ports/mimxrt10xx/sdk` and then `make fetch-submodules`.

**Comment by bill88t** [comment]
That worked, thanks, but why was that necessary. Never have I ever had to do this in the past.

**Comment by dhalbert** [comment]
The old way of fetching submodules did a shallow fetch, which leaves incomplete info in the .git directory. I would like to find a clean way of doing this but haven't yet.
