### ISSUE TITLE
PicoW: System hangs when trying to restart code after starting Wifi and webserver.

### ISSUE THREAD

**Issue by paul-1** [adafruit/circuitpython#7790]
### CircuitPython version

```python
Adafruit CircuitPython 8.1.0-beta.0-66-gcc5451ec3-dirty

Working fine in

Adafruit CircuitPython 8.0.4-1-g4517071e6-dirty
```

### Code/REPL

```python
any of the examples from https://github.com/adafruit/Adafruit_CircuitPython_HTTPServer
```

### Behavior

Start Program,  any program interrupt after the httpserver is started will result in a hang/crash when you try to restart code.  The behavior is the same using the wifi in client or ap mode.

**Comment by RetiredWizard** [comment]
I used the httpserver_cpu_information.py example program and after creating a suitable secrets.py ran the example and exited using ctrl-C. At that point if I pressed Ctrl-D the board would crash. One time I received the following message:
```
*** PANIC ***

invalid socket state for err callback
```

**Comment by RetiredWizard** [comment]
The first commit in main that I see this problem on is https://github.com/adafruit/circuitpython/commit/fe40035cb9dd73d1de055ce0931c5fea99e95ffa.

**Comment by dhalbert** [comment]
> The first commit in main that I see this problem on is [fe40035](https://github.com/adafruit/circuitpython/commit/fe40035cb9dd73d1de055ce0931c5fea99e95ffa).

This is the update of the CYW43 driver.

**Comment by paul-1** [comment]
Tested the latest commits, all good here.
