### ISSUE TITLE
i.MX I2SOut and PWMAudioOut: sample rates not evenly divisible into 192kHz are off pitch

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#7800]
For both `I2SOut` and `PWMAudioOut` on `mimxrt10xx` ports, if an audio sample's sample rate is not evenly divisible into 192kHz, the sample plays off pitch.

@jepler notes:

> based on adding some print statements near SAI_TxSetBitClockRate I think it is in fact integer divisors of 192kHz that give correct sample rates. and that I understand but don't want to rush to writing the code so that other frequencies like 44.1kHz operate correctly. (have to change the PLL input to the peripheral which has fractional divisors available, not rely on the integer divisor internal to the peripheral)
> 
> and this will change the MQS carrier frequency slightly as well, because they drive from the same PLL

I tested `I2SOut` on a SAMD21, and this does not occur.

**Comment by dhalbert** [comment]
Sine wave samples and I2S test program for Metro M7 1011:

[sine-samples.zip](https://github.com/adafruit/circuitpython/files/11084083/sine-samples.zip)
[imxplay2.py.zip](https://github.com/adafruit/circuitpython/files/11084100/imxplay2.py.zip)

**Comment by jepler** [comment]
https://webaudiodemos.appspot.com/pitchdetect/index.html is a nice resource for testing pitch online.
