### ISSUE TITLE
Feather S2 TFT Debug Build SCL Pin In Use

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/circuitpython#7831]
### CircuitPython version

```python
Adafruit CircuitPython 8.1.0-beta.1-6-g4e7bbf70a-dirty on 2023-04-03; Adafruit Feather ESP32-S2 TFT with ESP32S2
```

### Code/REPL

```python
>>> import board
>>> dir(board)
['__class__', '__name__', 'A0', 'A1', 'A2', 'A3', 'A4', 'A5', 'BOOT0', 'BUTTON', 'D1', 'D10', 'D11', 'D12', 'D13', 'D14', 'D15', 'D16', 'D17', 'D18', 'D2', 'D35', 'D36', 'D37', 'D41', 'D42', 'D5', 'D6', 'D8', 'D9', 'DISPLAY', 'I2C', 'L', 'LED', 'MISO', 'MOSI', 'NEOPIXEL', 'NEOPIXEL_POWER', 'RX', 'SCK', 'SCL', 'SDA', 'SPI', 'STEMMA_I2C', 'TFT_BACKLIGHT', 'TFT_CS', 'TFT_DC', 'TFT_I2C_POWER', 'TFT_RESET', 'TX', 'UART', 'board_id']
>>> i2c = board.I2C()
```

### Behavior

ValueError exception is raised due to SCL pin in use
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: SCL in use
```

### Description

Debug builds for Feather S2 TFT seem to result in SCL pin being in use so user code is unable to use `board.I2C()` for anything.

I've attempted from within code.py and REPL, both have the same result.

The build is from main branch with the only changes being:
```
CIRCUITPY_ULAB = 0
```
to make room for debug.

and in the make command:
```
DEBUG=1
```

I attempted a non-debug build with `CIRCUITPY_ULAB = 0` still in place to narrow this specifically to debug build being the only variable between the two.

**Comment by Neradoc** [comment]
It looks like it's the default JTAG pins, enabled on debug:

https://github.com/adafruit/circuitpython/blob/4e7bbf70a67fe15a135ad859fa04c13bcef4fde3/ports/espressif/supervisor/port.c#L279-L296

I think you'll want to
```c
#define ENABLE_JTAG 0
```
