### ISSUE TITLE
Metro M7 1011 filesystem is flaky

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#7858]
I have noticed CIRCUITPY problems on the Metro M7 1011. I have had CIRCUITPY intermittently be reformatted after a reset, and have also written files that never show up (e.g. write `test.py`, but can't import it, even after a Linux `sync`). Something about filesystem writes appears to be flaky.

**Comment by tannewt** [comment]
I don't think this should block 8.1. iMX is still very much in flux.

**Comment by tannewt** [comment]
@dhalbert want to poke this again? It seems ok to me now but maybe you can figure out a repro.

**Comment by dhalbert** [comment]
I can't reproduce this now. I was originally testing with a proto Metro 1011 board which seems to have a bunch of problems.
