### ISSUE TITLE
Onewire Reset Issue/Enhancement

### ISSUE THREAD

**Issue by CanyonCasa** [adafruit/circuitpython#7859]
The Onewire reset function returns false when it finds one or more devices on the bus by detecting a presence pulse following the reset low state. Unfortunately, if the bus faults to a stuck low condition for an number of reasons (i.e. 2 terminal device attached backwards, no pullup, hardware failure, etc) the reset will also return false indicating the presence of devices.

A stuck low bus will report a serial number of all zeros, which again unfortunately resolves to a valid crc8 of 0, indicating a valid device. A consequence of this is that you require a parameter for a maximum number of bus devices in the onewirebus scan function to prevent hanging the controller, which shouldn't be required. 

All this can be remedied by testing for a high state as part of the reset function.

It appears the function below from [https://github.com/adafruit/circuitpython/blob/main/extmod/modonewire.c](https://github.com/adafruit/circuitpython/blob/main/extmod/modonewire.c) performs the onewire reset.

```c
STATIC int onewire_bus_reset(mp_hal_pin_obj_t pin) {
    mp_hal_pin_od_low(pin);
    mp_hal_delay_us(TIMING_RESET1);
    uint32_t i = mp_hal_quiet_timing_enter();
    mp_hal_pin_od_high(pin);
    mp_hal_delay_us_fast(TIMING_RESET2);
    int status = !mp_hal_pin_read(pin);
    mp_hal_quiet_timing_exit(i);
    mp_hal_delay_us(TIMING_RESET3);
    return status;
}
```
The fix simply requires changing the last line to...
```c
    return status || !mp_hal_pin_read(pin);
```

A stuck low bus will then return true, indicating a bus failure or no devices present. If the line returns high as expected after the presence pulse it will work normally indicating the presence or not of devices..

Note also the link at the top of the page ...
[https://docs.circuitpython.org/en/latest/shared-bindings/onewireio/index.html#onewireio.OneWire]()
is out of date and should point to ...
[https://www.analog.com/media/en/technical-documentation/tech-articles/1wire-communication-through-software--maxim-integrated.pdf]()

**Comment by tannewt** [comment]
extmod is the MicroPython implementation. The CircuitPython one is:

https://github.com/adafruit/circuitpython/blob/0aea45516b6ad13fd741a115ece931868bb15a37/shared-module/onewireio/OneWire.c#L54-L64

The link is here: https://github.com/adafruit/circuitpython/blob/main/shared-bindings/onewireio/__init__.c#L40

Would you mind making a PR to fix these two issues? Thanks!
