### ISSUE TITLE
build can't find conf.py?

### ISSUE THREAD

**Issue by larsks** [adafruit/circuitpython#791]
If I try to build circuitpython with current master (dd0f8689a), I get:

```
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
FREEZE modules
Traceback (most recent call last):
  File "../../py/makeversionhdr.py", line 108, in <module>
    make_version_header(sys.argv[1])
  File "../../py/makeversionhdr.py", line 70, in make_version_header
    info = get_version_info_from_docs_conf()
  File "../../py/makeversionhdr.py", line 55, in get_version_info_from_docs_conf
    with open(os.path.join(os.path.dirname(sys.argv[0]), "..", "docs", "conf.py")) as f:
IOError: [Errno 2] No such file or directory: '../../py/../docs/conf.py'
make: *** [../../py/py.mk:273: build/genhdr/mpversion.h] Error 1
make: *** Waiting for unfinished jobs....
```

And indeed, there is no `py/conf.py`. It looks as if it was relocated in 46e7f8e to the top-level of the repository.

**Comment by jerryneedell** [comment]
What board are you building CP for?  What command are you executing to build it? What subdirectory are you executing it in?

**Comment by larsks** [comment]
Sorry, duh.  My bad.

I'm building the esp8266 port, from `ports/esp8266`, and I am running `make`.

```
$ pwd
/home/lars/src/micropython/ports/esp8266
$ git log --oneline -1
dd0f8689a (HEAD, circuit/master) Merge pull request #786 from notro/rtc_set_datetime_precision
$ esp-sdk make
Use make V=1, make V=2 or set BUILD_VERBOSE similarly in your environment to increase build verbosity.
Traceback (most recent call last):
  File "../../py/makeversionhdr.py", line 108, in <module>
    make_version_header(sys.argv[1])
  File "../../py/makeversionhdr.py", line 70, in make_version_header
    info = get_version_info_from_docs_conf()
  File "../../py/makeversionhdr.py", line 55, in get_version_info_from_docs_conf
    with open(os.path.join(os.path.dirname(sys.argv[0]), "..", "docs", "conf.py")) as f:
IOError: [Errno 2] No such file or directory: '../../py/../docs/conf.py'
make: *** [../../py/py.mk:273: build/genhdr/mpversion.h] Error 1
```

**Comment by jerryneedell** [comment]
Also did you execute 
```
git submodule update --init --recursive
``` 
after cloning the repository?

**Comment by larsks** [comment]
If I patch `py/makeversionhdr.py` from this:

    with open(os.path.join(os.path.dirname(sys.argv[0]), "..", "docs", "conf.py")) as f:

To this:

    with open(os.path.join(os.path.dirname(sys.argv[0]), "..", "conf.py")) as f:

The build proceeds correctly.

**Comment by larsks** [comment]
I did run `git submodule update --init --recursive`, yes...although that shouldn't matter, because neither `py/` or `docs/` nor `ports/esp8266` are submodules.

**Comment by jerryneedell** [comment]
odd - it builds fine for me  --- did you try running make clean first - just guessing.

**Comment by larsks** [comment]
I did that too.  Very strange.

Can you confirm whether or not you have a `docs/conf.py` in your repository?  If it exists, do you see it in the output of `git ls-files docs/conf.py` show?

**Comment by jerryneedell** [comment]
no conf.py in docs/

**Comment by jerryneedell** [comment]
I see you are running esp-sdk make  -- what OS are you on?  I just execute
make  
on my Ubuntu 16.04 system.

**Comment by larsks** [comment]
`esp-sdk` is just a wrapper script that runs the build inside a docker container (https://github.com/larsks/docker-image-esp-open-sdk). 

I'm pretty sure that build environment is not the problem; looking at the contents of `py/makeversionhdr.py` I think it looks incorrect.  It's clearly trying to find `docs/conf.py`, which as you have verified does not exist.

**Comment by larsks** [comment]
Oh hey, I spotted the problem.

If you look at `py/makeversionhdr.py`, you find:

```python
def make_version_header(filename):
    # Get version info using git, with fallback to docs/conf.py
    info = get_version_info_from_git()
    if info is None:
        info = get_version_info_from_docs_conf()
```

So it falls back to using `docs/conf.py` if `git` isn't available.  It's not in my build environment, and obviously nobody ever tested the fallback path since making that change in 46e7f8e back in 2016.

So it's a real bug, but not one that most people are going to hit.
