### ISSUE TITLE
Do you have any plan to embed the lvgl_binding？

### ISSUE THREAD

**Issue by fvstory** [adafruit/circuitpython#7936]
1.I read the lvgl_binding_micropython code. It make the lvgl source file into a module like the the module framebuffer. I think it all run in the vm(loop the lv.task_handle()). so can do embed it！
2.if we use the c source lvgl to make a special ui，just like the peripheral to call！，this can make the lvgl running in the cpu_core0(eg esp32s3，2 core)，we just need to call the python vm‘s task to make the task loop，but this have two ways to reach: (1)use the thread, like the micropython’s timer call; in circuitpython, it not use, but i see it can ower it in esp_system(vm as a normal freertos task)；(2)use some queue？to give the unique message to let vm polling it？
I think the second method (use the made ui as peripheral）integrate the circuitpython！

**Comment by tannewt** [comment]
Already have an issue for it here: #6699
