### ISSUE TITLE
Help porting M5Stack ESP32 Timer Camera X

### ISSUE THREAD

**Issue by bill88t** [adafruit/circuitpython#7981]
This is a `esp32` board, with 8MB PSRAM and a built-in camera.

It is a board sold by Adafruit ([here](https://www.adafruit.com/product/4959)), but somehow doesn't have CircuitPython support.
The work-in-progress PR I made is [here](https://github.com/adafruit/circuitpython/pull/7941).

I would complete the port myself, but I am unable to do the camera.
I have it working under arduino, so the pins are known and tested.

The board schematics are available in 2 parts, [here](https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/docs/schematic/TimerCAM/TimerCAM_A1-ESP32_SUBSYS.pdf) and [here](https://m5stack.oss-cn-shenzhen.aliyuncs.com/resource/docs/schematic/TimerCAM/TimerCAM_A2-PMS_UART.pdf).
The complete board documentation is available [here](https://docs.m5stack.com/en/unit/timercam_x).

**Comment by tannewt** [comment]
> It is a board sold by Adafruit ([here](https://www.adafruit.com/product/4959)), but somehow doesn't have CircuitPython support.
> The work-in-progress PR I made is [here](https://github.com/adafruit/circuitpython/pull/7941).

We don't necessarily add CircuitPython support for all boards we sell. Generally it is only ones we design and make.

> The work-in-progress PR I made is [here](https://github.com/adafruit/circuitpython/pull/7941).

Thanks! I'd prefer to merge once the CI is happy. Someone else can fix the camera later.
