### ISSUE TITLE
Add Arduino Nano 33 BLE Sense Rev 2

### ISSUE THREAD

**Issue by applecuckoo** [adafruit/circuitpython#7991]
This is a new version of the already-supported Arduino Nano 33 BLE Sense. I opened this issue to discuss the now discontinued Rev 1, but I repurposed it for the Rev 2 after figuring out that all the pins for the Rev 1 were already defined for the Nano 33 BLE port. See https://github.com/adafruit/circuitpython/issues/7991#issuecomment-1552701310 further below for more information.

Arduino documentation: <https://docs.arduino.cc/hardware/nano-33-ble-sense-rev2>
Pinout: <https://docs.arduino.cc/resources/pinouts/ABX00069-full-pinout.pdf>

**Comment by dhalbert** [comment]
If you'd like to contribute a board definition, that would be great. In the other issue you mentioned you don't own the board. Do you have one now?

**Comment by applecuckoo** [comment]
@dhalbert No, I don't own this board. I could probably start from the existing definition, but I should probably get my current PR (#7989) merged before I start work on this.

**Comment by applecuckoo** [comment]
I've specifically changed the scope of this issue to focus on the newer Rev 2 version of the board since the existing definition incorporates the sensor pins in pins.c, as seen here:
https://github.com/adafruit/circuitpython/blob/f2bfced4079389c71cbdcf7d69e16d41f0e3dc98/ports/nrf/boards/arduino_nano_33_ble/pins.c#L51-L55
There are a few differences between the two revisions pin-wise, here is a list of them that I've picked up:
- The LPS22's interrupt pin is now connected to the board at P0.12
- The LSM9DS1 has been substituted for two sensors combining to form a 9-DoF IMU.
  - One of these sensors, the Bosch BMI270, has two interrupt pins connected at P0.11 and P0.20 respectively. This isn't very useful at the moment since a CircuitPython library doesn't exist for the BMI270, but it could be handy if one ever gets developed.
- There are also two pins that you can turn off to disable sensors:
  - p0.22 for the IMU, LPS22 and HS3003 humidity sensor
  - And p0.17 for the mic.

I hope this helps for anyone making a board definition for the Rev 2.

**Comment by applecuckoo** [comment]
Closed by #9347.
