### ISSUE TITLE
TouchAlarm on Qt Py ESP32-S2 not working in SLEEP mode

### ISSUE THREAD

**Issue by mikeysklar** [adafruit/circuitpython#7994]
### CircuitPython version

```python
Adafruit CircuitPython 8.1.0-rc.0 on 2023-05-17; Adafruit QT Py ESP32S2 with ESP32S2
```

### Code/REPL

```python
import alarm
import board

print(alarm.wake_alarm)

touch_alarm = alarm.touch.TouchAlarm(board.A2)

alarm.exit_and_deep_sleep_until_alarms(touch_alarm)
```

### Behavior

The code runs, but does not wakeup upon pin touch.

### Description

[Forum thread](https://forums.adafruit.com/viewtopic.php?t=201048) based on [Adafruit example code](https://learn.adafruit.com/deep-sleep-with-circuitpython/alarms-and-sleep#timealarm-deep-sleep-3078700).

### Additional information

I also reproduced on a Qt Py ESP32-S2 with current bootloader 0.13.0 and current beta CircuitPython 8.1.0-rc.0

**Comment by rxhfcy** [comment]
Consider adding the esp32-s2 label?

**Comment by dhalbert** [comment]
This appears to have stopped working between 7.1.0 and 7.2.0. I'll bisect.

**Comment by dhalbert** [comment]
Apparently due to 13db65566d590fea872121d51eeacfc5d2d612a2:
> Pin reset is now changed to the IDF default which pulls the pin up rather than CircuitPython's old behavior of floating the pin.

So we need to special-case the touch pins

**Comment by dhalbert** [comment]
2bc8d73776434bb2f15113014299a9fffa547109, which is past 13db655, _also_ causes `TouchAlarm` not to work. If I prevent the touch awaking pin from being reset, then 13db655 and forward works, up to but not including 2bc8d73776434bb2f15113014299a9fffa547109 does not. 2bc8d73776434bb2f15113014299a9fffa547109 is part of #6772.

So still working on this.
