### ISSUE TITLE
Low volume when playing .wav file, speaker enabled

### ISSUE THREAD

**Issue by danowall** [adafruit/circuitpython#800]
I’m trying to play a .wav file on the CPX and the audio output is very weak. I believe I’ve properly enabled the speaker using

spkrenable = DigitalInOut(board.SPEAKER_ENABLE)
spkrenable.direction = Direction.OUTPUT
spkrenable.value = True

however the audio is still so quiet you can barely hear it. is there another way to ensure an audio file is played at max volume?

[code.txt](https://github.com/adafruit/circuitpython/files/1971945/code.txt)

**Comment by ladyada** [comment]
use audacity to make sure the file is loud
if you dont know how, ask john park to do this for you

**Comment by danowall** [comment]
amazing! that definitely makes it noticeably louder. I tried using the noise removal tool to clean up the audio clip too, still comes out of the speaker sounding a little muddy but is good enough for now.

**Comment by tannewt** [comment]
@danowall You set? Can we close this?

**Comment by danowall** [comment]
@tannewt yeah we're good here, thank you!

**Comment by ladyada** [comment]
@danowall please close the issue now that its done

(click the close button)
