### ISSUE TITLE
Esp32-s3 busio SPI watchdog reset

### ISSUE THREAD

**Issue by HemQL** [adafruit/circuitpython#8000]
### CircuitPython version

```python
Adafruit CircuitPython 8.0.5 on 2023-03-31; ESP32-S3-DevKitC-1-N8R8 with ESP32S3
Board ID:espressif_esp323_devkitc_1_n8r8
UID:C7FD1A3EA8C9
```

### Code/REPL

```python
import board
import busio
spi = busio.SPI(board.IO36, board.IO35, board.IO37)
cs = board.IO40
print(“SPI initialized.”)
```

### Behavior

Board resets to safe mode for reason: “Internal watchdog timer expired.”

### Description

Also tested in 8.1.0-RC.0. I suspect that busio.SPI() is taking SPI0 used by the ESP32S3 to talk to its internal flash, rather than the SPI2 or SPI3 buses that are safe for the MCU to assign.

### Additional information

Defining the SPI() object in the REPL does not immediately result in an error, and commands like print(some local variable) seem to still work, but most other commands result in a watchdog reset.

**Comment by anecdata** [comment]
> SPI0/1: GPIO26-32 are usually used for SPI flash and PSRAM and not recommended for other uses. When using Octal Flash or Octal PSRAM or both, GPIO33~37 are connected to SPIIO4 ~ SPIIO7 and SPIDQS. Therefore, on boards embedded with ESP32-S3R8 / ESP32-S3R8V chip, GPIO33~37 are also not recommended for other uses.

https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/peripherals/gpio.html
