### ISSUE TITLE
Fetch submodules lazily

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#8036]
Instead of having to do a slow `make fetch-submodules` at the top level after cloning `circuitpython`, fetch the submodules lazily. Fetch the submodules for a particular port only when a build is done in that port directory.

... working on this.

**Comment by bill88t** [comment]
I feel like `make fetch-submodules` shouldn't be removed.
It's nice to be able to run one command to prepare the local repo so that you can go offline.

But seperating it into auto triggers for every port sounds like a great idea.

**Comment by joshua-beck-0908** [comment]
That would be nice. I just wait a long time for every submodules just to change one line of an esp32 board definition. Then the esp-idf build failed anyway. 😅
