### ISSUE TITLE
CPX library doesn't work on CPX (recursion depth hit)

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#8053]
https://forums.adafruit.com/viewtopic.php?p=974225#p974225

**Comment by bill88t** [comment]
Pystack again?

**Comment by RetiredWizard** [comment]
I enabled MICROPY_STACKLESS which resulted in the same "RuntimeError: maximum recursion depth exceeded" message but without the traceback.

I then disabled CIRCUITPY_FULL_BUILD, CIRCUITPY_COUNTIO and CIRCUITPY_BITBANGIO and enabled CIRCUITPY_AUDIOIO and CIRCUITPY_PIXELBUF and the example scripts from the forum post ran without crashing.

I know this isn't a solution but figured it might at least help zero in on the issue.

**Comment by bill88t** [comment]
Stackless should never print that message..
Across all the testing I ever did on stackless it never showed it, even in depths >2.000.000.
Something is horribly going wrong for that to show.

**Comment by RetiredWizard** [comment]
The CPX has a lot less SRAM (32K I believe) than the chips you were probably testing on, would actually running out of available memory possibly trigger the error?
