### ISSUE TITLE
audiopwmio on the ESP32-S3-DevKitC-1-N8R8.

### ISSUE THREAD

**Issue by mirkokral** [adafruit/circuitpython#8064]
The ESP32-S3-DevKitC-1-N8R8 has good support for pwm and there is a working pwmio library in circuitpython for it.
So why not put audiopwmio on it too, i already use PWM for audio on Arduino Framework.

**Comment by dhalbert** [comment]
Subsumed by #3898, so I'll close in favor of that issue.
