### ISSUE TITLE
Custom Board CI accepts custom branch, but doesn't respect it.

### ISSUE THREAD

**Issue by bill88t** [adafruit/circuitpython#8092]
![image](https://github.com/adafruit/circuitpython/assets/21365918/73a148a0-16b1-470a-a4ab-ba49e8af1dc5)
Regardless of the branch set. (It doesn't change it later)
This is misleading.

Spent 2 hours testing picow stability thinking I was on the new `pico-sdk`.

**Comment by tannewt** [comment]
@microdev1 Added this and would know what to fix.

**Comment by microdev1** [comment]
Are you setting the branch using the `Use workflow from` dropdown? The intended way is to use the `Version` input box.

**Comment by bill88t** [comment]
Yea I did use the `Use workflow from`..
I though that for branches that is what I should be using.
Oh well..
