### ISSUE TITLE
Mounted filesystems don't appear over web workflow

### ISSUE THREAD

**Issue by makermelissa** [adafruit/circuitpython#8107]
### CircuitPython version

```python
8.2.0-beta.1-12-g0da62416a-dirty
```

### Code/REPL

```python
N/A
```

### Behavior

Per @ladyada:

Mounted filesystems don't appear - i have a microSD on /sd but does not show up over wifi.

Checked via /fs/ folder on the device and it wasn't there either.

**Comment by tannewt** [comment]
I've been thinking a lot about this and I think we'll need to require that the FS be backed by a native object for reading and writing blocks. MP actually allows for Python implemented block io but that would lead to running Python functions at anytime while other user code runs.

**Comment by ladyada** [comment]
can we do that easier if we requre using sdcardio (which is already semi-native)

**Comment by tannewt** [comment]
Yup, exactly. Using the native sdcardio or sdio rather than the Python sd card library would be required.
