### ISSUE TITLE
Uploading a file that is too large via Web Workflow causes Hard Fault

### ISSUE THREAD

**Issue by makermelissa** [adafruit/circuitpython#8109]
### CircuitPython version

```python
8.2.0-beta.1-12-g0da62416a-dirty
```

### Code/REPL

```python
N/A
```

### Behavior

per @ladyada:

i don't think anyone tried uploading a file that is 'too large' - the board hardfaults

**Comment by dhalbert** [comment]
`8.2.0-beta.1-12-g0da62416a-dirty` is the same as #8100, so tip of `main` at the moment.
