### ISSUE TITLE
Web Workflow File Browser not update progress?

### ISSUE THREAD

**Issue by makermelissa** [adafruit/circuitpython#8110]
### CircuitPython version

```python
8.2.0-beta.1-12-g0da62416a-dirty
```

### Code/REPL

```python
N/A
```

### Behavior

Per @ladyada:

i did pick a shorter file - but the upload progress bar never advances?
![image (1)](https://github.com/adafruit/circuitpython/assets/2681417/af868a25-034d-4503-a609-707b7724af8f)
also would be good to have the onboard neopixel blink just like it does when we upload files via usb (the file does upload tho!)
![image](https://github.com/adafruit/circuitpython/assets/2681417/299e4f49-cdbd-4ee2-9b54-fc30930ceaae)

**Comment by tannewt** [comment]
Right now the progress bar is only for multi-file uploads. The new Fetch API has an experimental body type support for ReadableStream but it isn't support across browsers yet. https://developer.mozilla.org/en-US/docs/Web/API/Request#browser_compatibility
