### ISSUE TITLE
Document that settings.toml is not turned on for SAMD21 boards; raise NotImplementedError

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#8168]
https://forums.adafruit.com/viewtopic.php?t=202975

User tried to use `os.getenv()` on a Trinket M0. Fetching from `settings.toml` is turned off on SAMD21 boards for space reasons. However:
- This is not documented anywhere. Fix that.
- Suggest we raise `NotImplementedError` for `os.getenv()` when `CIRCUITPY_OS_GETENV = 0` instead of just returning `None`. `os.getenv()` is useless when `CIRCUITPY_OS_GETENV = 0`, and raising an error would make that more obvious.

**Comment by jepler** [comment]
The 2nd part has been done.

**Comment by dhalbert** [comment]
fixed by #8185. Should be merged into main.
