### ISSUE TITLE
rp2pio checking for "in" instruction when not always required

### ISSUE THREAD

**Issue by Ultrawipf** [adafruit/circuitpython#8221]
Hardware/Version: RP2040 with circuitpython 8.2.1.

Assuming `sm` as a `rp2pio.StateMachine` it is possible to write a pio program with no `in` instruction and then read an internal state using a `run` command as `sm.run(adafruit_pioasm.assemble("in x, 32"))` to fill the buffer and then read the state with `sm.readinto`.

The command `readinto` will then cause a `RuntimeError: No in in program` error if no `in` instruction was found in the original state machine code. 

Adding an unreachable `in` instruction to the program lets it succeed and correctly read out the data read by the previous command.

This is even an example use case for [run](https://docs.circuitpython.org/en/latest/shared-bindings/rp2pio/index.html#rp2pio.StateMachine.run) so it should not throw an error when no `in` instruction was found.

A good use case for this is reading the state of an encoder internally and reading the count on demand or similar pulse counting applications where no constant stream of data is required.

**Comment by jepler** [comment]
revised and now working with https://gist.github.com/jepler/597b80caa61a4a71f094959c1df66001 (`self._sm.run(self.get)`)

**Comment by jepler** [comment]
and also https://gist.github.com/jepler/891a3c48e2f9f9fb9759bdb5ce081265
