### ISSUE TITLE
Flashing Circuitpython to NRF with different SWD Programmer

### ISSUE THREAD

**Issue by No1089** [adafruit/circuitpython#825]
I’d like to flash a NRF52 chip with Circuitpython but I don’t have the SEGGER, but can buy an Atmel ICE locally - is it possible to have the makefile just output the files to flash?

**Comment by jepler** [comment]
I'm not familiar with Atmel ICE and I don't know whether it can program the nrf52 chip.

However, to answer the specific question you asked, when you `make all` in ports/nrf52, you will get the firmware in several formats, "elf", "bin" and "hex".  These are all "fairly common" formats, and at least one of them is likely to be supported by any flashing tool software.

**Comment by sommersoft** [comment]
@No1089 As you may or may not have read, `nrfjprog` is designed to specifically work with the SEGGER; no indication that it works with any other SWD. I don't see any other utility for other debuggers/programmers, and google isn't turning anything up other than a couple questions.

You could look into programming it via Device Firmware Update (DFU) over serial, which is how the Feather52 - nRF52832 is programmed (other than via SEGGER).

**Comment by tannewt** [comment]
@jerryneedell @microbuilder @arturo182 Would know too.

**Comment by No1089** [comment]
@jepler @sommersoft I had a look at the makefile and as I understood it, it's all fine up to the point where the flasher is called. If the output file can be saved, a different piece of hardware can flash the chip (according to what I know). But I am not sure how the `make sd` part works to flash the bluetooth stack. Sorry for the ignorance, never used of of these programmers/debuggers before.

**Comment by No1089** [comment]
@sommersoft I can source the sparkfun nRF52832 breakout locally, but I want to use this when it arrives: [](https://www.aliexpress.com/item/Fast-Free-Ship-NRF52832-Bluetooth-4-0BLE-SOC-Wireless-Sensor-Acceleration-Sensor-BME280-Environmental-Sensor/32818538078.html?spm=a2g0s.13010208.99999999.262.CScVLv).

**Comment by deshipu** [comment]
As far as I know, Atmel ICE is just a locked down version of the Segger.

**Comment by arturo182** [comment]
According to this http://omzlo.com/articles/programming-samd21-using-atmel-ice-with-openocd it looks like the Atmel ICE is a CMSIS-DAP programmer, so it should be possible to flash a nRF chip using it with the help of OpenOCD.

**Comment by tannewt** [comment]
Looks like it should be possible.
