### ISSUE TITLE
ESP32-S2 web workflow don't work

### ISSUE THREAD

**Issue by casainho** [adafruit/circuitpython#8275]
### CircuitPython version

```python
Adafruit CircuitPython 8.2.2 on 2023-07-31; S2Mini with ESP32S2-S2FN4R2
Board ID:lolin_s2_mini
UID:84722ED59B67
```

### Code/REPL

```python
import time

while True:
    print("Hello World!")
    time.sleep(0.5)
```

### Behavior

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
main.py output:
Hello World!
Hello World!
Hello World!
Hello World!

### Description

I am trying to use the web workflow as explained on the documentation: https://docs.circuitpython.org/en/latest/docs/workflows.html#web

I used a basic code for testing. The ESP32-S2 is not connecting to my router and so the web workflow do not work. A few previous versions of CP, it was working well as expected.

![Screenshot from 2023-08-11 16-11-21](https://github.com/adafruit/circuitpython/assets/147128/82e6730c-7be3-4e8f-980f-e297c5ce9c5f)

![Screenshot from 2023-08-11 16-12-09](https://github.com/adafruit/circuitpython/assets/147128/ed8ff799-e21c-4bfa-a805-0b491c693597)

![image](https://github.com/adafruit/circuitpython/assets/147128/f11bbaff-cb10-47f3-8cff-ef8f13a4db19)

### Additional information

I am being using the [Lolin S2 mini board](https://www.wemos.cc/en/latest/s2/s2_mini.html) and building [this displays](https://opensourceebike.github.io/build_EBike_Bafang_M500/build_display/build_display.html):

![image](https://github.com/adafruit/circuitpython/assets/147128/65bcff2f-5ad2-4509-a97a-b644c25f8cb1)

![image](https://github.com/adafruit/circuitpython/assets/147128/287599b9-f693-492a-a735-3a598c0faf43)

This display will replace my micro scooter battery state indicator board, that is only some LEDs. The display only needs 5V and then communications with the micro scooter control board, using wireless, the ESPNow of CircuitPython that works very well:

![image](https://github.com/adafruit/circuitpython/assets/147128/fa6b0cbe-a8e1-4fce-90d6-a885ab8f5431)

![image](https://github.com/adafruit/circuitpython/assets/147128/c3fdd61d-17b3-4930-b3dc-c8eecb6c0315)

**Comment by tannewt** [comment]
Are you able to get the CircuitPython serial output on the display? It'll show wifi status in the top bar. It looks like the serial terminal in vscode doesn't show it.

**Comment by casainho** [comment]
I tested again on new boards, both with ESP32-S2 and ESP32-S3, with the latest CP 8.2.3. It works well as expected on both boards. Sorry, I now think I did some mistake, maybe a wrong password to my wifi router.

![Screenshot from 2023-08-12 19-50-30](https://github.com/adafruit/circuitpython/assets/147128/132ac8d9-644e-4f67-bc34-60f8ee9cbf15)

![Screenshot from 2023-08-12 20-31-28](https://github.com/adafruit/circuitpython/assets/147128/2129ebfb-f402-4820-aeb5-23b33456b375)

**Comment by casainho** [comment]
I got the issue again. It happens if I am using my home wifi but not if I used my 4G portable router.

But then I did remember I am using a wifi repeater - and I tested that if CP board is configured to connect to home main router it works, but do not work if I connect to the wifi repeater network. Maybe something changed on the wifi repeater, as I didn't had this issue previously...
