### ISSUE TITLE
leading 'u' required on  for json module 

### ISSUE THREAD

**Issue by RetiredWizard** [adafruit/circuitpython#8314]
### CircuitPython version

```python
Adafruit CircuitPython 8.2.0-80-g282e93d3e3-dirty on 2023-08-22; Pimoroni Pico DV Base W with rp2040
```

### Code/REPL

```python
import json
```

### Behavior

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'json'

### Description

Entering
```py
import ujson
```
works fine

### Additional information

I looked through the extmod directory and looked for other modules that might have the same issue and didn't find any but by no means did an exhaustive test.

I also changed the following line in modujson.c
```py
MP_REGISTER_MODULE(MP_QSTR_ujson, mp_module_ujson);
```
to
```py
MP_REGISTER_MODULE(MP_QSTR_json, mp_module_ujson);
```
and `import json` worked, however `import ujson` no longer worked.

**Comment by dhalbert** [comment]
Thanks for noting this. This is a regression from the merge. I will audit the other `MP_REGISTER_MODULE` sites.
