### ISSUE TITLE
set_ipv4_address_ap TypeError: extra positional arguments given

### ISSUE THREAD

**Issue by qingwa2009** [adafruit/circuitpython#8329]
### CircuitPython version

```python
Adafruit CircuitPython 8.2.3 on 2023-08-11; Adafruit Feather ESP32-S3 TFT with ESP32S3
```

### Code/REPL

```python
def startHotPoint():
    print("wifi hot point starting...")
    ip=ipaddress.IPv4Address(HOT_POINT_IP)
    mask=ipaddress.IPv4Address("255.255.255.0")
    #gateway=wifi.radio.ipv4_gateway
    gateway=ipaddress.IPv4Address("192.168.100.1")
    wifi.radio.set_ipv4_address_ap(ip, mask, gateway)
    wifi.radio.start_ap(HOT_POINT_SSID,HOT_POINT_PASSWORD)
```

### Behavior

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: extra positional arguments given

### Description

>>> type(ip) == ipaddress.IPv4Address
True
>>> ip
192.168.111.1
>>> mask
255.255.255.0
>>> gateway
192.168.111.1
>>> wifi.radio.set_ipv4_address_ap(ip, mask, gateway)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: extra positional arguments given

Can you fix this, please!
best regards

**Comment by anecdata** [comment]
They are keyword arguments:

https://docs.circuitpython.org/en/latest/shared-bindings/wifi/index.html#wifi.Radio.set_ipv4_address_ap
