### ISSUE TITLE
list reverse() returns None

### ISSUE THREAD

**Issue by BNNorman** [adafruit/circuitpython#8350]
### CircuitPython version

```python
Adafruit CircuitPython 8.2.0 on 2023-07-05; Raspberry Pi Pico with rp2040

and also tried on

Adafruit CircuitPython 8.2.4 on 2023-08-22; Raspberry Pi Pico with rp2040
```

### Code/REPL

```python
lista=[1,2,3,4]
print(lista.reverse())
```

### Behavior

list reverse() returns None

### Description

I am expecting to see a reversed list [4,3,2,1] not None

### Additional information

None

**Comment by dhalbert** [comment]
This is how regular Python works. `somelist.reverse()` reverses the list in place, modifying the original list, and does not return anything. `reversed(somelist)` returns a reversed list without modifying the original.
