### ISSUE TITLE
Protomatter library updates

### ISSUE THREAD

**Issue by PaintYourDragon** [adafruit/circuitpython#8353]
Protomatter matrix library 1.6.1 (c9c1189) addresses some issues with ESP32-S3. Drive strength compilation issue is fixed, pixel clock is slightly reduced to help w/visual glitches.

The prior release, 1.6.0, if not already in use by CircuitPython, addresses M4 issues. Also a slight pixel clock reduction, and additionally the clock duty cycle is semi-configurable -- perhaps this could be exposed as a named arg in Python, and ignored if not supported by arch. See _PM_setDuty() comments in that lib. Thx.

**Comment by tannewt** [comment]
@dhalbert want to do this before 8.2.5?

**Comment by dhalbert** [comment]
> @dhalbert want to do this before 8.2.5?

I think so, but maybe not expose the argument (yet).

**Comment by dhalbert** [comment]
Fixed by #8376.
