### ISSUE TITLE
Stop wifi on reload on the raspberrypi port

### ISSUE THREAD

**Issue by anecdata** [adafruit/circuitpython#8369]
Now that [auto-connect](https://github.com/adafruit/circuitpython/pull/8367) can be used with or without web workflow, and `wifi.radio.stop_station()` has been [implemented](https://github.com/adafruit/circuitpython/pull/7079) on `raspberrypi`, we should consider disconnecting wifi across reload in the non-Auto-Connect case. This would make `raspberrypi` code behave more like `espressif` code.

In the Auto-Connect case, the presumption is that wifi should stay up as much as possible, and wifi will now survive reloads. But in the non-Auto-Connect case, it's counterintuitive for a reload to start up code with a different state than a reset.

I think we should strive to have the behaviors of the two ports match as much as the SDKs allow. The subtle differences can be confusing, even for non-beginner CircuitPython developers.

**Comment by bill88t** [comment]
On it.
