### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by thetazero** [adafruit/circuitpython#8431]
### CircuitPython version

```python
n/a
```

### Code/REPL

```python
Just the docs here: https://docs.circuitpython.org/en/latest/shared-bindings/ulab/numpy/linalg/index.html#ulab.numpy.linalg.eig
```

### Behavior

![image](https://github.com/adafruit/circuitpython/assets/28244551/220cd02b-151b-439a-9be8-cedcd5fc9afc)

It says it returns `(eigenvectors, eigenvalues)` while it actually returns `(eigenvalues, eigenvectors)`.

Actual behavior is inline with numpy.

### Additional information

Happy to fix this myself, just need to be pointed in the right direction.

**Comment by dhalbert** [comment]
`ulab` is a submodule: the original repo is here: https://github.com/v923z/micropython-ulab/. So submit issues and PR's to that repo.

**Comment by thetazero** [comment]
This issue appears on the circuit python docs, not on the micropython ulab docs.

**Comment by jepler** [comment]
If they've fixed it already, then we will get the fix next time we update ulab. This is likely to happen soon.

**Comment by dhalbert** [comment]
@thetazero Could you link to the docs where the order is correct?
