### ISSUE TITLE
Serving content over HTTPS (Pico-W) using additional crypto-chip

### ISSUE THREAD

**Issue by ams1** [adafruit/circuitpython#8472]
Hi,

I've tried to serve httpS on a Pico W, but it's indeed slow as reported also in: https://github.com/adafruit/circuitpython/issues/7657

Is it possible to use an external crypto chip attached to the Pico W to speedup HTTPS (something like https://learn.adafruit.com/adafruit-atecc608-breakout/overview)?

I just want to know if I'm digging in the right direction [and that it's not a rabbit hole 😄] - IMO an example with this would be highly useful.

Thank you again for your incredible work on this repo!

**Comment by tannewt** [comment]
This isn't really a CP issue. The [adafruit discord](https://adafru.it/discord) or another electronics forum is a better place to ask this. I don't personally have experience running an https server with CP.
