### ISSUE TITLE
SuperMini NRF52840 - fully compatible with Nice!Nano. Add it to the Nice!Nano page?

### ISSUE THREAD

**Issue by Axeia** [adafruit/circuitpython#8473]
Not quite sure what to list this under but I have recently purchased the SuperMini NRF52840 which seems to be fully compatible with the Nice!Nano. 
So I flashed the Nice!Nano CircuitPython build on it and tested all the pins to see if they all map the same and everything seems to be working A-Okay.

So I don't know what the best course of action is here. 
* Should the Nice!Nano CircuitPython page ( https://circuitpython.org/board/nice_nano/ ) get an addition for this board? 
  * Should it just be mentioned on the left side that the SuperMini NRF52840  is compatible?
  * Should it be reflected in the URL/H1 element?
* Should it get its own page/build? (I'm willing to see if I can get a PR to work for it)

**Comment by tannewt** [comment]
Own build is fine. As we discussed on Discord, I'd rather have separate boards to keep clear names as trademarks. It makes things easier if the boards evolve in the future too.
