### ISSUE TITLE
The doesn't appear to be a way to read buttons on the Qualia ESP32-S3

### ISSUE THREAD

**Issue by makermelissa** [adafruit/circuitpython#8507]
### CircuitPython version

```python
Absolute Latest CircuitPython 9
```

### Code/REPL

```python
N/A
```

### Behavior

The buttons are on the GPIO Expander and the code for the expander (inside dotclockframebuffer) seems to only allow sending init sequences, but not reading values.

**Comment by jepler** [comment]
there should be some library for this particular i2c chip that would be used after the LCD initialization. (maybe it doesn't exist yet?) We talked about adding I/O expander in the core (#8377) but didn't do it for some reasons described there.

**Comment by makermelissa** [comment]
Ok, I'll see if I can get it working with Adafruit_CircuitPython_PCF8574 and if so, add an example and close this issue.

**Comment by makermelissa** [comment]
It almost works. Pushing the button has no effect, but it does grab a value from the expander. I'll have to dive more into the specifics of why that may be when I have more than 10 minues.

**Comment by makermelissa** [comment]
Whenever I try switching it to an input and I get the following error:
```
Traceback (most recent call last):
  File "code.py", line 87, in <module>
  File "/lib/adafruit_pcf8574.py", line 142, in switch_to_input
  File "/lib/adafruit_pcf8574.py", line 170, in direction
  File "/lib/adafruit_pcf8574.py", line 87, in write_pin
  File "/lib/adafruit_pcf8574.py", line 74, in write_gpio
OSError: [Errno 19] No such device
```
I also tried using bitbangio, but received this error:
```
Traceback (most recent call last):
  File "code.py", line 87, in <module>
  File "/lib/adafruit_pcf8574.py", line 142, in switch_to_input
  File "/lib/adafruit_pcf8574.py", line 170, in direction
  File "/lib/adafruit_pcf8574.py", line 87, in write_pin
  File "/lib/adafruit_pcf8574.py", line 74, in write_gpio
OSError: [Errno 5] Input/output error
```

**Comment by makermelissa** [comment]
This could be related to #4621.

**Comment by makermelissa** [comment]
It looks like the PCA9554 has special command bytes for configuring the port and having its own CP driver would probably be the best approach.

**Comment by jepler** [comment]
Modifying tags to reflect that a new library is needed

**Comment by makermelissa** [comment]
I'll update this if I find it continues to refuse to work, but I don't think it will be an issue.

**Comment by makermelissa** [comment]
Ok, I have something functioning. New lib was definitely the way to go.

**Comment by makermelissa** [comment]
New library created: https://github.com/adafruit/Adafruit_CircuitPython_PCA9554
