### ISSUE TITLE
Fix mimxrt10xx UART settings after MicroPython v1.21.0 merge

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#8509]
The v1.21 merge (#8508) includes some incomplete changes for the UART clock divisor on `mimxrt10xx`.

In `ports/mimxrt10xx/peripherals/mimxrt10xx/MIMXRT10*/clocks.c`, the clock divisor was changed from 0 to 1:
```c
CLOCK_SetDiv(kCLOCK_UartDiv, 1);  // WAS 0
```
However, this change appears to be incomplete; these sorts of lines will also need to change:
```c
#define BOARD_BOOTCLOCKRUN_UART_CLK_ROOT 80000000UL
```
See https://github.com/micropython/micropython/pull/12377

**Comment by tannewt** [comment]
This doesn't impact us. We don't use their implementation at all. It's unfortunate we share the same port directory name.
