### ISSUE TITLE
Look at shared/runtime/stdout_helpers.c after v1.21.0 merge

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#8510]
See if https://github.com/micropython/micropython/pull/7491 for `shared/runtime/stdout_helpers.c` is worth
incorporating to reduce skew from MicroPython.

**Comment by dhalbert** [comment]
I was wondering whether we should pick up the revised version of the code:
![image](https://github.com/adafruit/circuitpython/assets/2847802/a74e0d00-f32f-4774-a036-390a92e6d2d3)

**Comment by jepler** [comment]
[slapping myself on the forehead emoji]

**Comment by dhalbert** [comment]
It was pretty cryptic :)
