### ISSUE TITLE
time.sleep(0.1) waits forever on ugame10

### ISSUE THREAD

**Issue by deshipu** [adafruit/circuitpython#855]
I'm trying the current master (be12e07d7437b9f2a75659bc944c15cccc8e93c1) on a crystal-less SAMD21 board with external flash (ugame10), and this code:

```python
>>> import time
>>> time.sleep(0.1)
```
blocks forever.

**Comment by notro** [comment]
These are working:
```
Adafruit CircuitPython 3.0.0-alpha.6-149-gbe12e07d7 on 2018-05-20; Adafruit Feather M0 Express with samd21g18
>>> import time; time.sleep(0.1)
>>>
```

```
Adafruit CircuitPython 3.0.0-alpha.6-149-gbe12e07d7 on 2018-05-20; Adafruit CircuitPlayground Express with samd21g18
>>> import time; time.sleep(0.1)
>>>

```

**Comment by deshipu** [comment]
That's the next step, but I'm time constrained, so I'm reporting those bugs here so I don't forget.

**Comment by tannewt** [comment]
I ran into something similar today and will have it fixed shortly. Basically, the new interrupt enable and disable routines in asf4 didn't handle nested calls like asf3 did. The end result is that interrupts get fully disabled.

For now common_hal_mcu_disable_interrupts and enable will work like asf3. However, we may want to change it in the future to be more like asf4 which likely runs faster.
