### ISSUE TITLE
ESP32-C6 WiFi connectivity issues

### ISSUE THREAD

**Issue by bill88t** [adafruit/circuitpython#8552]
### CircuitPython version

```python
Debug build, removed stuff for flash size, (almost) current master (commit 7715ff09cc663b80403f8907fe90c00fd89c9706)

Adafruit CircuitPython 9.0.0-alpha.2-12-g4eb82fea0d-dirty on 2023-11-01; WEACT-ESP32-C6 with ESP32-C6N4

CIRCUITPY_BLEIO = 0
CIRCUITPY_ESPCAMERA = 0

CIRCUITPY_ANALOGBUFIO = 0
CIRCUITPY_AUDIOBUSIO = 0
CIRCUITPY_AUDIOBUSIO_PDMIN = 0
CIRCUITPY_AUDIOIO = 0
CIRCUITPY_AUDIOMP3 = 0
CIRCUITPY_BLEIO_HCI = 0
CIRCUITPY_CANIO = 0
CIRCUITPY_COUNTIO = 0
CIRCUITPY_DOTCLOCKFRAMEBUFFER_USES_SUPERVISOR_ALLOCATION = 0
CIRCUITPY_FRAMEBUFFERIO = 0
CIRCUITPY_FREQUENCYIO = 0
CIRCUITPY_I2CTARGET = 0
CIRCUITPY_IMAGECAPTURE = 0
CIRCUITPY_MEMORYMAP = 0
CIRCUITPY_PARALLELDISPLAYBUS = 0
CIRCUITPY_PS2IO = 0
CIRCUITPY_RGBMATRIX = 0
CIRCUITPY_ROTARYIO = 0
CIRCUITPY_TOUCHIO = 0
CIRCUITPY_ESPULP = 0
CIRCUITPY_COPROC = 0
CIRCUITPY_I2CDISPLAYBUS = 0
CIRCUITPY_EPAPERDISPLAY = 0
CIRCUITPY_BITBANG_APA102 = 0
CIRCUITPY_BINASCII = 0
CIRCUITPY_AUDIOMIXER = 0
CIRCUITPY_ATEXIT = 0
CIRCUITPY_RAINBOWIO = 0
CIRCUITPY_STATUS_BAR = 0
CIRCUITPY_ULAB = 0
CIRCUITPY_ESPNOW = 0
```

### Code/REPL

```python
Nothing, just the settings.toml with correct credentials.
```

### Behavior

```
W (80048) wifi:(bf)761:0x600a7cac:0x01b4b4b0
W (80048) wifi:(agc)0x600a7128:0xd2024800, min.avgNF:0xce->0xd2(dB), RCalCount:0x24, min.RRssi:0x800(-128.00)
W (80058) wifi:(TB)WDEV_PWR_TB_MCS0:19
W (80058) wifi:(TB)WDEV_PWR_TB_MCS1:19
W (80058) wifi:(TB)WDEV_PWR_TB_MCS2:19
W (80068) wifi:(TB)WDEV_PWR_TB_MCS3:19
W (80068) wifi:(TB)WDEV_PWR_TB_MCS4:19
W (80068) wifi:(TB)WDEV_PWR_TB_MCS5:19
W (80078) wifi:(TB)WDEV_PWR_TB_MCS6:18
W (80078) wifi:(TB)WDEV_PWR_TB_MCS7:18
W (80078) wifi:(TB)WDEV_PWR_TB_MCS8:17
W (80088) wifi:(TB)WDEV_PWR_TB_MCS9:15
W (80088) wifi:(TB)WDEV_PWR_TB_MCS10:15
W (80088) wifi:(TB)WDEV_PWR_TB_MCS11:15
I (80098) wifi:11ax coex: WDEVAX_PTI0(0x55777555), WDEVAX_PTI1(0x00003377).

I (80108) wifi:mode : sta (40:4c:ca:41:ff:54)
I (80108) wifi:enable tsf
W (80108) CP wifi: sta start
I (82518) wifi:new:<4,0>, old:<1,0>, ap:<255,255>, sta:<4,0>, prof:1
I (82518) wifi:(connect)dot11_authmode:0x3, pairwise_cipher:0x3, group_cipher:0x3
I (83268) wifi:state: init -> auth (b0)
I (83278) wifi:state: auth -> assoc (0)
I (83278) wifi:Extended Capabilities length:8, subtype:0x10, 40:74:e0:4a:40:4d, Operating mode notification Support
I (83278) wifi:state: assoc -> run (10)
I (83278) wifi:(trc)phytype:CBW20-SGI, snr:83, maxRate:144, highestRateIdx:0
I (83288) wifi:(trc)rate(S-MCS7, schedIdx:0), ampdu(rate:S-MCS7, schedIdx(0, stop:8)), snr:83, ampduState:wait operational
I (83298) wifi:ifidx:0, rssi:-13, nf:-96, phytype(0x3, CBW20-SGI), phymode(0x3, 11bgn), max_rate:1440, he:0
I (83308) wifi:max ampdu length exponent:3(65535 bytes), mmss:5(4 us)
I (85388) wifi:state: run -> init (fc0)
I (85388) wifi:ifidx:0, rssi:-13, nf:-96, phytype(0x3, CBW20-SGI), phymode(0x3, 11bgn), max_rate:1440, he:0
I (85388) wifi:max ampdu length exponent:3(65535 bytes), mmss:5(4 us)
I (85398) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
W (85398) CP wifi: disconnected
W (85408) CP wifi: reason 15 0x0f
I (85408) CP wifi: Retrying connect. 4 retries remaining
W (87818) CP wifi: disconnected
W (87818) CP wifi: reason 205 0xcd
I (87818) CP wifi: Retrying connect. 3 retries remaining
I (90228) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
I (90228) wifi:(connect)dot11_authmode:0x3, pairwise_cipher:0x3, group_cipher:0x3
I (90228) wifi:state: init -> auth (b0)
I (90238) wifi:state: auth -> assoc (0)
I (90238) wifi:Extended Capabilities length:8, subtype:0x10, 40:74:e0:4a:40:4d, Operating mode notification Support
I (90248) wifi:state: assoc -> run (10)
I (90248) wifi:(trc)phytype:CBW20-SGI, snr:82, maxRate:144, highestRateIdx:0
I (90258) wifi:(trc)rate(S-MCS7, schedIdx:0), ampdu(rate:S-MCS7, schedIdx(0, stop:8)), snr:82, ampduState:wait operational
I (90268) wifi:ifidx:0, rssi:-14, nf:-96, phytype(0x3, CBW20-SGI), phymode(0x3, 11bgn), max_rate:1440, he:0
I (90278) wifi:max ampdu length exponent:3(65535 bytes), mmss:5(4 us)
I (92348) wifi:state: run -> init (fc0)
I (92348) wifi:ifidx:0, rssi:-14, nf:-96, phytype(0x3, CBW20-SGI), phymode(0x3, 11bgn), max_rate:1440, he:0
I (92348) wifi:max ampdu length exponent:3(65535 bytes), mmss:5(4 us)
I (92348) wifi:new:<4,0>, old:<4,0>, ap:<255,255>, sta:<4,0>, prof:1
W (92358) CP wifi: disconnected
W (92358) CP wifi: reason 15 0x0f
W (92368) wifi:(itwt)itwt_stop_process!
W (92368) CP wifi: sta stop
I (92378) wifi:flush txq
I (92378) wifi:stop sw txq
I (92378) wifi:lmac stop hw txq
```

### Description

The network it's trying to connect to is my Thinkpad acting as a hotspot.
It's 2.4ghz, and has worked with pretty much all my other boards. So it's very much not it's fault.
Scanning works, and it can see the networks.

I cannot load code for fancy stuff, since it has no native usb and wifi is inoperable.

**Comment by bill88t** [comment]
Also, from usercode, connecting to any of my access points I get:
```
>>> wifi.radio.connect(...)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ConnectionError: Unknown failure 15
```

**Comment by rgrizzell** [comment]
I've also run into this issue trying to port CircuitPython 9.x to LILYGO T-Deck which is based on the **ESP32-S3**. The `timeout` value doesn't seem to have any effect either. It will attempt to connect and then soft-lock until reloaded.

**Comment by anecdata** [comment]
Error 15 is `WIFI_RADIO_ERROR_4WAY_HANDSHAKE_TIMEOUT`, which could have separate causes on ESP32-S3.

**Comment by bill88t** [comment]
Wait, the error codes between `esp_wifi` and CP are kinda different..

In `ports/espressif/common-hal/wifi/Radio.c`, line 340:
```
if ((bits & WIFI_DISCONNECTED_BIT) != 0) {
    if (self->last_disconnect_reason == WIFI_REASON_AUTH_FAIL) {
        return WIFI_RADIO_ERROR_AUTH_FAIL;
    } else if (self->last_disconnect_reason == WIFI_REASON_NO_AP_FOUND) {
        return WIFI_RADIO_ERROR_NO_AP_FOUND;
    }
    return self->last_disconnect_reason;
```
the `last_disconnect_reason` is updated from wifi events in `ports/espressif/common-hal/wifi/__init__.c`, line 117:
```
radio->last_disconnect_reason = reason;
```

The `reason` is the `esp_wifi` event converted to a `wifi_event_sta_disconnected_t` which is an `esp_wifi` typedef if I am not wrong. So did we at no point convert the code to a CP `WIFI_RADIO_ERROR` code, or am I missing something?

The [esp_wifi](https://github.com/espressif/esp-idf/blob/e088c3766ba440e72268b458a68f27b6e7d63986/components/esp_wifi/include/esp_wifi.h#L78) header says this code means `ESP_ERR_WIFI_NOT_CONNECT`.

Meanwhile the `shared-bindings/wifi/Radio.h` specifies it as you said.

**Comment by anecdata** [comment]
`if (event_base == WIFI_EVENT) {` <https://github.com/adafruit/circuitpython/blob/ebf19bd46c2aa7944df739c69b681d8f23a1f385/ports/espressif/common-hal/wifi/__init__.c#L77C5-L77C36>

**Comment by bill88t** [comment]
Looking at IDF changes since 5.1 there are a WHOLE lot of C6 fixes.
I did merge v5.1.1 onto my local submodule and try with that, unfortunately it didn't fix it.

Something that works though is the arduino wifi example with the esp32 plugin version 3.0.0-alpha2.
So I am looking into how that does it.

I also plan on testing idf master but I am quite busy with sbcs right now.

**Comment by romkey** [comment]
A couple of other datapoints:

CircuitPython 9.0.0-alpha.2 on a plain old ESP32 is able to connect to wifi

The ESP-IDF [wifi example](https://github.com/espressif/esp-idf/tree/master/examples/wifi/getting_started/station) worked on a C6 when I built it with ESP-IDF 5.1.1. Haven't tried it with other versions of ESP-IDF yet.  So that and Arduino 3.0.0-alpha2 are two instances of wifi working on the C6.

I'm happy to try out other test builds for you if that would help.

**Comment by bill88t** [comment]
I have done a lot more research into the issue, but found nothing of value.
The current CircuitPython esp wifi code is nice and clean, much simpler than the rp2 wifi code.

I did compare idf examples and the arduino underlying code, but unfortunately only found minor differences in how they handle their wifi stack on esp.
The main stuff is basically identical, with only some tiny stuff being different (`pdTRUE` and `pdFALSE` for the bit waiting).

I did look deeper into how the wifi is initialized and the wifi credential loading but didn't find anything interesting.
I did try playing with the "minimum authmode" and the wifi 6 spec negotiation things (since they are currently unset), but nothing helped.

I also want to also try checking the forked idf code for differences but that will take an incredible amount of time.
Especially for someone like me who is unfamiliar with idf code.

It would also be worthwhile going back to the idf 5.0 and 5.1 merge PRs and retrying artifacts from back then.
Since, it supposedly, was tested then.

**Comment by bill88t** [comment]
It also doesn't help that the wifi spec is basically ungooglable, and I have no clue what the issue really is in nature.
I am basically just throwing pebbles down a ravine to hear how deep it is.

Also I should make it clear, I did test about 20 different combinations of tiny changes with absolutely no effect.
Even trying with an incorrect wifi password the result is always the same.

This leads me to believe that the issue is in the forked idf. But it could be somewhere in init or the config_t.

**Comment by bill88t** [comment]
News!
Commit 39192cc896d09cb72794bdf5d81726a8a6bfb520 works! So it's a matter of finding where the issue was introduced.

**Comment by bill88t** [comment]
Commit at fault: 16d1dc2be07ee7f35079515b081dd817319ab311
It's not a buildable commit, the next buildable is faa445e347d4508d7bb6bf2b8cb175702cea2d63 and exhibits this issue.
The last WORKING commit is: 6649b17fb5b98efed97e9234c670bb16cdf6cac3

**Comment by bill88t** [comment]
It was a 2 line fix.
PR here: https://github.com/adafruit/circuitpython/pull/8595
