### ISSUE TITLE
gc.collect after import

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#856]
in *theory* it shouldnt make a difference whether we collect() after each import in a sketch but ive found that "sketch that work but then fail after a while with memerrors dont have failures if we gc.collect after each import" im testing CPX in 3.0.0

we don't import a lot, its not a time sensitive event, and there's a huge memory slush...why not :)

**Comment by tannewt** [comment]
I'd really like to investigate why this is the case after 3.0.0 is done. Do have an example handy that could be used? Thanks.

**Comment by ladyada** [comment]
https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/master/Crickits/yayayay_flier/code.py

**Comment by tannewt** [comment]
I'm looking at this today. I've got my heap analysis setup going.
