### ISSUE TITLE
create driver for TMP007

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/circuitpython#857]
I could not find a driver for the TMP007 IR Temperature sensor https://www.adafruit.com/product/2023
There is a Python Driver for the Raspberry Pi and I have adapted it to work under CircuitPython.
My initial version seems to be functional.

@tannewt when you have a chance, please create a template for Adafruit_CircuitPython_TMP007

**Comment by tannewt** [comment]
Thanks @jerryneedell ! New repo is here: https://github.com/adafruit/Adafruit_CircuitPython_TMP007

Please propose a PR and let me know if you need me to run cookiecutter.

**Comment by jerryneedell** [comment]
In the past I have run cookie cutter locally then uploaded the files in the PR - Is that ok or is there a better way?

**Comment by tannewt** [comment]
Thats ok!

**Comment by ladyada** [comment]
driver exists, in bundle and was tested!
