### ISSUE TITLE
Cross-reference Building CircuitPython and debugging on SAMD21 guides in README.md

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#858]
Put links to these in the toplevel README.md

https://learn.adafruit.com/building-circuitpython
https://learn.adafruit.com/debugging-the-samd21-with-gdb

**Comment by sommersoft** [comment]
And once it finally gets published? maybe? 😄

https://learn.adafruit.com/circuitpython-samd-debugging-w-atmel-studio-7

**Comment by ladyada** [comment]
@sommersoft is that guide ready for moderation?

**Comment by sommersoft** [comment]
not quite yet. still waiting on @brentru to finish his review (not calling you out! take your time), as well as another Discord user and @kattni (super-busy, as she is).

**Comment by ladyada** [comment]
ok thx!
