### ISSUE TITLE
QT Py S3 with 4MB Flash & 2MB PSRAM won't accept 9.x firmware

### ISSUE THREAD

**Issue by anecdata** [adafruit/circuitpython#8606]
### CircuitPython version

Tried several 9.x from
`adafruit-circuitpython-adafruit_qtpy_esp32s3_4mbflash_2mbpsram-en_US-9.0.0-alpha.4.uf2`
to today's latest
`adafruit-circuitpython-adafruit_qtpy_esp32s3_4mbflash_2mbpsram-en_US-20231114-95fc7e3.uf2`

### Code/REPL

```python
no code
```

### Behavior

Dropping UF2 onto bootloader drive... file copies, but then bootloader drive re-appears. Tried expanded and non-expanded filesystem. Tried fully `erase_flash`-ing, then loading `.bin` firmware, but then console shows boot-looping. None of the variations worked.

Three different QT Py S3 N4R2 boards were tested.

Other S3 boards don't seem to have an issue with 9.x ...Feather S3, Metro S3, etc.

Chip on the QT Py is labeled `FH4R2...`. `os.statvfs("/")` confirms `CIRCUITPY` partition size of 900k+ (non-extended) or ~2MB (extended). PSRAM checks out at 2MB with `gc`. Spec says the `FH4R2` is 4MB `qio` (p.10):
https://www.espressif.com/sites/default/files/documentation/esp32-s3_datasheet_en.pdf"

`mpconfigboard.mk` has 8MB `dio`:
https://github.com/adafruit/circuitpython/blob/main/ports/espressif/boards/adafruit_qtpy_esp32s3_4mbflash_2mbpsram/mpconfigboard.mk
but Dan tried builds fixing flash size, and trying both `dio` and `qio`, neither worked.

(Discord discussion up to here:
https://discord.com/channels/327254708534116352/327298996332658690/1174141068137214054)

**Comment by dhalbert** [comment]
Fixed by #8611.
