### ISSUE TITLE
Check CIRCUITPY_ESP_FLASH_MODE settings on Espressif boards

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#8612]
`CIRCUITPY_ESP_FLASH_MODE` used to only be used in a Makefile target for flashing the board. Now it is used to select the proper `sdkconfig*` file. Many ESP32-S3 boards, and maybe other ESP32-xx boards have it set to `dio`, when it may be able to be set to `qio`.

My understanding is that `dio` will work, just slower. (Am I misunderstanding?). However, if we fix the ones that are now `dio` to `qio`, we should see improved performance, I believe.

We should audit the board `mpconfigboard.mk` files to see which ones can be changed.

**Comment by tannewt** [comment]
> My understanding is that `dio` will work, just slower. (Am I misunderstanding?). However, if we fix the ones that are now `dio` to `qio`, we should see improved performance, I believe.

This is my understanding too.

**Comment by bill88t** [comment]
If this change is what I think it is, (actual flash speed while running), the speed improvement should be pretty considerable, just like with psram.
Actual seconds for big projects like mine.

Though it needs to be actually tested for every board.
I will do it for every board I have, though it takes time.

Also, won't esp32 (non -Sx) also benefit from it?
iirc my camera board has octal connections and is esp32.

**Comment by dhalbert** [comment]
>Though it needs to be actually tested for every board.

For various classes of boards, we shouldn't need to re-test. For instance, the Espressif chips with integral flash, and  modules with in-module flash, will all have the same settings (for each chip or module). It's only when there are external, not pre-packaged flash chips that we have to check the board for how many data lines are connected.
