### ISSUE TITLE
QTPY ESP32S3 9.0.0A5: fails on BLERadio startScan()

### ISSUE THREAD

**Issue by kyril96** [adafruit/circuitpython#8631]
**Adafruit CircuitPython 9.0.0-alpha.5 on 2023-11-15; Adafruit QT Py ESP32-S3 no psram with ESP32S3**

**code.py output (the first few times) :**
]0;🐍192.168.0.144 | code.py | 9.0.0-alpha.5\scanning
Traceback (most recent call last):
  File "code.py", line 5, in <module>
  File "adafruit_ble/__init__.py", line 271, in start_scan
ValueError: Prefix buffer must be on the heap
]0;🐍192.168.0.144 | 271@adafruit_ble/__init__.py ValueError | 9.0.0-alpha.5\
Code done running.

**After repeated runs without the reset button or an unplug, I instead get this:**
code.py output:
]0;🐍192.168.0.144 | code.py | 9.0.0-alpha.5\Traceback (most recent call last):
  File "code.py", line 1, in <module>
  File "adafruit_ble/__init__.py", line 28, in <module>
  File "adafruit_ble/advertising/__init__.py", line 98, in <module>
MemoryError: memory allocation failed, allocating 96 bytes
]0;🐍192.168.0.144 | 98@adafruit_ble/advertising/__init_ MemoryError | 9.0.0-alpha.5\
Code done running.

**The code itself:**
```
ble = BLERadio()
print("scanning")
bleConn=None
for ad in ble.start_scan():
    print ("9.0.0A5 goes kaboom before this can be printed.")
    break
print ("done")

```

**Switching UF2 and lib back to 8.2.6 works as expected:**
code.py output:
]0;🐍192.168.0.144 | code.py | 8.2.6\scanning
9.0.0A5 goes kaboom before this can be printed.
done
]0;🐍192.168.0.144 | Done | 8.2.6\
Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.
]0;�192.168.0.144 | REPL | 8.2.6\
Adafruit CircuitPython 8.2.6 on 2023-09-12; Adafruit QT Py ESP32-S3 no psram with ESP32S3

**Comment by tannewt** [comment]
This may be split heap related.

**Comment by dhalbert** [comment]
I have an easy fix for this, but I'm debugging other things at the same time.
