### ISSUE TITLE
audiobusio.I2SOut word_select and bit_clock only supports ascending sequence pins

### ISSUE THREAD

**Issue by evilhamsterman** [adafruit/circuitpython#8680]
### CircuitPython version

```python
Adafruit CircuitPython 8.2.8 on 2023-11-16; Seeeduino XIAO RP2040 with rp2040
```

### Code/REPL

```python
import audiobusio
import board

DATA = board.A1
LRCLK = board.A2
BCLK = board.A3
audio = audiobusio.I2SOut(BCLK, LRCLK, DATA)
```

### Behavior

```python
Traceback (most recent call last):
  File "main.py", line 25, in <module>
ValueError: Bit clock and word select must be sequential pins
```

### Description

The code is taken from https://learn.adafruit.com/adafruit-audio-bff/circuitpython. The audiobff is designed to be soldered directly to a QT Py board and so the pins cannot be reversed. 

### Additional information

The issue appears to be this line https://github.com/adafruit/circuitpython/blob/60404286abdae3f908849632292e9a1b275926d0/ports/raspberrypi/common-hal/audiobusio/I2SOut.c#L107 in the rp2040 port. No other port appears to have this check so I'm not sure if this is a RP2040 thing, does it have to be ascending sequential or would descending work?

**Comment by evilhamsterman** [comment]
I have them mounted back to back. That's what I wasn't sure if it was a RP2040 thing. Looking at the specifics for gpio arrangement on the Adafruit QT Py RP2040 and the Xiao RP2040 it looks like the gpio pins are reversed. It appears that Adafruit should mention that the bff isn't compatible with the Xiao version

**Comment by dhalbert** [comment]
@jepler @tannewt My understanding is that we could support bit clock and word select pins in reverse order but we'd need two more PIO programs to handle that case. Is that true?
