### ISSUE TITLE
T-Deck use the desk keyboard in REPL directly

### ISSUE THREAD

**Issue by Freyr86** [adafruit/circuitpython#8684]
Hello all,

I just flashed circuitpython on my T-Desck and it all works correctly. But to my great surprise I cannot use the REPL keyboard directly from the T-Desck.

Following advice, I'm going to dig around to create a little circuit python script.

It was pointed out to me that there was the execution of the repl.py script before loading the console, as you had planned a development in this direction.

Can we help at our level?

**Comment by Freyr86** [comment]
No I am not associated with Lilygo but I translate the text with Google translate so my English is approximate

**Comment by Freyr86** [comment]
@RetiredWizard well seen it works on my side I will do some tests thank you very much

**Comment by RetiredWizard** [comment]
I was playing around with this and realized that any user scripts that are imported from the virtual REPL will need the following import block added:
```py
try:
    from tdeck_repl import input
except:
    pass
```

**Comment by tannewt** [comment]
It would be neat to support I2C keyboards natively in CircuitPython. That'd enable using the keyboard when the VM isn't running too. We've started doing this with USB keyboards in CircuitPython 9.
