### ISSUE TITLE
Ad Led_IR pin name to ATOM Lite ESP32 circuitpython  

### ISSUE THREAD

**Issue by sctv** [adafruit/circuitpython#8738]
Adafruit CircuitPython 9.0.0-alpha.6 on 2023-12-12; M5Stack Atom Lite with ESP32

Pin 12/IR pin isn't named in https://github.com/adafruit/circuitpython/blob/main/ports/espressif/boards/m5stack_atom_lite/pins.c but it is on the pinmap and schematic at https://docs.m5stack.com/en/core/atom_lite

It can be accessed via microcontroller.pin.GPIO12

**Comment by carson-coder** [comment]
I made a pull request the should fix this.

**Comment by carson-coder** [comment]
This can be closed now

**Comment by dhalbert** [comment]
Fixed by #8747.
