### ISSUE TITLE
3.0 Beta: busio.UART read(nbytes) returns empty bytearray on timeout rather than None

### ISSUE THREAD

**Issue by CedarGroveStudios** [adafruit/circuitpython#874]
In 3.0.0-beta.0 2018-05-23, busio.UART read(nbytes) does not return the None value upon timeout, just an empty bytearray.

Tested using Metro M4 express hardware.

**Comment by tannewt** [comment]
Will validate that it [matches CPython](https://docs.python.org/3.6/library/io.html):

```
 read(size=-1)

    Read up to size bytes from the object and return them. As a convenience, if size is
unspecified or -1, all bytes until EOF are returned. Otherwise, only one system call is
ever made. Fewer than size bytes may be returned if the operating system call
returns fewer than size bytes.

    If 0 bytes are returned, and size was not 0, this indicates end of file. If the object
is in non-blocking mode and no bytes are available, None is returned.
```

**Comment by CedarGroveStudios** [comment]
3.0 works differently than CPy 2.3.1. The examples break with 3.0 because of the bytearray content check:
`data = uart.read(1)  # get a byte from RX
    if data is not None:
        …`

**Comment by tannewt** [comment]
Yup, it should work now @CedarGroveStudios

**Comment by CedarGroveStudios** [comment]
Super! I'll test it on the next release. Thanks!
