### ISSUE TITLE
rotaryio works poorly on Espressif

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#8740]
found by user: https://forums.adafruit.com/viewtopic.php?t=206898

Reproduced on Feather ESP32-S2  with 7.3.3, 8.2.9, and 9.0.0-alpha.6. Also reproduced on Feather ESP32-S3 with 8.2.9.

With [ANO encoder](https://www.adafruit.com/product/5001): counts OK in one direction, misses many counts and sometimes goes wrong way in other direction.
With [regular encoder](https://www.adafruit.com/product/377): many extra counts in either direction.

Tested with same encoders and wiring on SAMD21 and RP2040 Feathers: both encoders work perfectly fine.

```py
import board
import rotaryio

ENCA = board.D13
ENCB = board.D12
encoder = rotaryio.IncrementalEncoder(ENCA, ENCB)
last_position = None

while True:
    position = encoder.position
    if last_position is None or position != last_position:
        print("Position: {}".format(position))
        last_position = position
```
ANO example output:
```
# one direction
Position: 0
Position: 1
Position: 2
Position: 11
Position: 12
Position: 13
Position: 14
Position: 15
Position: 16
Position: 17
Position: 18
Position: 19
Position: 20
# reverse
Position: 19
Position: 18
Position: 19
Position: 18
Position: 19
Position: 18
Position: 17
Position: 18
Position: 17
```
regular encoder:
```
#one direction
Position: 1
Position: 2
Position: 3
Position: 5
Position: 6
Position: 9
Position: 12
Position: 16
# reverse
Position: 17
Position: 28
Position: 27
Position: 28
Position: 29
Position: 30
Position: 31

**Comment by jepler** [comment]
I wrote a test for rotary encoders that just loops back a digital output signal to the input pins.

My test device was a Metro ESP32-S2 running 8.2.9.

I agree that it looks like the encoder is not counting correctly.

<details>
<summary>Test program></summary>

```py
from rotaryio import IncrementalEncoder
from digitalio import DigitalInOut
import board

class QuadratureOut:
    ph_a = [0, 1, 1, 0]
    ph_b = [0, 0, 1, 1]

    def __init__(self, a, b):
        self.a = DigitalInOut(a)
        self.a.switch_to_output(False)
        self.b = DigitalInOut(b)
        self.b.switch_to_output(False)
        self.position = 0

    def go(self, target):
        while self.position < target:
            self.step(1)
        while self.position > target:
            self.step(-1)

    def step(self, direction):
        if direction not in(-1, 1) or not isinstance(direction, int):
            raise ValueError("Direction must be an integer between -1 and 1")
        position = self.position + direction
        self.position = position
        self.a.value = self.ph_a[position & 3]
        self.b.value = self.ph_b[position & 3]

def encoder_test(out_a, out_b, in_a, in_b):
    qout = QuadratureOut(out_a, out_b)
    qin = IncrementalEncoder(in_a, in_b, divisor=1)

    for _ in range(100):
        print(f"{qout.position: 4d} {qout.a.value:1d}{qout.b.value:1d} {qin.position: 4d}")
        qout.step(1)

encoder_test(board.IO7, board.IO8, board.A5, board.A4)
```

</details>

Partial output:
```
   0 00    0
   1 10    1
   2 11    1
   3 01    0
   4 00    0
   5 10    1
   6 11    1
   7 01    2
   8 00    2
   9 10    3
  10 11    3
...
  99 01   14
```
I saw the final count range anywhere from 12 to 16, far short of the correct 100. If I switch to the negative direction I get counts from -32 to -37 over a couple of tries. For me, then, it is missing steps, and different numbers of steps depending on direction.

While the test should simply see the IncrementalEncoder count up to 100, instead it counts weirdly. I didn't see any jumps like the original poster reported, so there _could_ be two problems at work. For instance, I do not see anywhere that pull-up resistors are set, but generally rotary encoders either pull down to ground or allow the pin to float, so a pull-up is required. (that said, I modified my script to use open drain mode and it seemed to behave the same, so there's that)

One suggestion would be to switch the espressif family microcontrollers over to using pin change detection plus the software quadrature decoder. I do not understand the theory of how the specific configuration of the PCNT counter module is supposed to provide correct quadrature counting.

**Comment by dhalbert** [comment]
I think there is significant bouncing on the regular rotary encoder.

Here is doc on the PCNT peripheral. But I agree, it could be rewritten with interrupts, and that would allow more encoders to be added. The well-factored shared-module partial implementation I think would be easy to finish for the port-specific interrupt part.

**Comment by jepler** [comment]
The theory of how the PCNT implementation works is discussed here, though not in great detail: https://esp32.com/viewtopic.php?t=4983

The idea seems to be that each half of the PCNT peripheral counts on two of the quadrature edges (e.g., both edges of A or both edges of B), selecting the correct count direction based on the value of the other signal.

**Comment by jepler** [comment]
I had a wiring error. With my wiring fixed, I get accurate counting when the signal is driven push-pull. When it's driven open drain, I get erratic counting. So, I think the problem is lacking pull-ups. I'll see if I can fix it.

**Comment by dhalbert** [comment]
Test with real encoders if you can, obviously.

**Comment by jepler** [comment]
well I'm puzzled. setting a pull up explicitly makes no difference. source shows says a pull up is configured anyway when setting up pcnt with esp-idf calls. and implementing my own "fake open bus" mode via .switch_to_input() for a True output fails in the same way (so it doesn't seem to be the a problem of the open bus mode on esp32s2, which we've had before on other platforms)

In fake open-bus mode I can read back the bus value as high (True) so I know there's really a pull there.

I still didn't see the jumps that Dan did, just incorrect counting.

**Comment by dhalbert** [comment]
> I still didn't see the jumps that Dan did, just incorrect counting.

This is still simulated, right? So it wouldn't be simulating contact bounce.

**Comment by dhalbert** [comment]
OK, the problem here seems to be due to choosing D13 as one of the pins. That pin has the board's red LED on it, and is pulling down the weak pullup used by PCNT. Closing this, with the caveat of not using a pin with something else attached.
