### ISSUE TITLE
ESP32-C3 wifi lost after every 2 reset

### ISSUE THREAD

**Issue by llllllllqq** [adafruit/circuitpython#8763]
### CircuitPython version

```python
adafruit-circuitpython-luatos_core_esp32c3-en_US-8.2.9
and also 9.0.0-alpha.6
```

### Code/REPL

```python
none
```

### Behavior

The led always blink 5 times on every reset (both on push rst button or re-plug usb cable). And the wifi is lost, until I reset it again, it turns to work. ( I means wifi only work every 2 reset). Maybe in a safemode but repl doesn't say why. 
```
rst:0x15 (USB_UART_CHIP_RESET),boot:0xe (SPI_FAST_FLASH_BOOT)
Saved PC:0x4038abba
SPIWP:0xee
mode:DIO, clock div:2
load:0x3fcd5810,len:0x24
load:0x403cc710,len:0x668
load:0x403ce710,len:0x2218
entry 0x403cc710
]0;馃悕Wi-Fi: No IP | Done | 8.2.9\
]0;馃悕192.168.1.5 | Done | 8.2.9\Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
]0;馃悕192.168.1.5 | code.py | 8.2.9\Hello World!
]0;馃悕192.168.1.5 | Done | 8.2.9\
Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.
]0;馃悕192.168.1.5 | REPL | 8.2.9\
Adafruit CircuitPython 8.2.9 on 2023-12-06; Luatos Core-ESP32C3 with ESP32-C3

>>> rst:0x15 (USB_UART_CHIP_RESET),boot:0xe (SPI_FAST_FLASH_BOOT)
Saved PC:0x42020300
SPIWP:0xee
mode:DIO, clock div:2
load:0x3fcd5810,len:0x24
load:0x403cc710,len:0x668
load:0x403ce710,len:0x2218
entry 0x403cc710
]0;馃悕Wi-Fi: No IP | Done | 8.2.9\
]0;馃悕Wi-Fi: off | Done | 8.2.9\Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
]0;馃悕Wi-Fi: off | code.py | 8.2.9\Hello World!
]0;馃悕Wi-Fi: off | Done | 8.2.9\
Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.
```

### Description

It's a fresh install by the web installer. WIFI was configured by web installer too. I tried to use a external USB to TTL adapter to connect the esp32-c3 for more logs, but the serial gave me nothing else than repl. 
I tried other firmware (like tasmota) and it works ok, so I believe the hw is not broken. I'm new to circuitpython, if there are more I can do, please comment, thanks a lot.

**Comment by carson-coder** [comment]
if safemode is entered then code.py doesn't run and it tells you when its in safe mode so its not in safemode

**Comment by llllllllqq** [comment]
Today, I reflashed 9.0.0-alpha.6, it worked well. But when I switched to 8.2.9, bug occurred.
Idk why the 9.0.0-alpha.6 version works today, the hardware and flash methods are same as before.
If I find this bug again, I'll post here and reopen this issue. Thanks for your hard work.
