### ISSUE TITLE
Feather M0: OverflowError: small int overflow

### ISSUE THREAD

**Issue by deshipu** [adafruit/circuitpython#88]
When I try to import a program that has this line:

```
x = 1 << 31
```

I'm getting:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: small int overflow
```

**Comment by willingc** [comment]
Hi @deshipu,

Can you add the surround lines to this failing lines or a link to the source? Thanks.

**Comment by deshipu** [comment]
That's all there is. There are no other lines.

**Comment by deshipu** [comment]
Ah, sorry, there is "import modulename", of course.

**Comment by deshipu** [comment]
I think I figured this out. The Feather M0 build only has small ints enabled, this means that I can't use arbitrarily large integers like in normal Python.

**Comment by willingc** [comment]
Cool. Glad you figured it out @deshipu 👍
