### ISSUE TITLE
new driver to travis & add to bundle

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#880]
https://github.com/adafruit/Adafruit_CircuitPython_MatrixKeypad

hey @kattni this should be ready to rock, please travis & bundlify & anything else we need to do for new libraries

**Comment by kattni** [comment]
Will do!

**Comment by kattni** [comment]
Currently working through this.

**Comment by kattni** [comment]
All required steps have been completed: travis, RTD, added to bundle. Ready to go!
