### ISSUE TITLE
sys.version reports as micropython

### ISSUE THREAD

**Issue by bill88t** [adafruit/circuitpython#8802]
### CircuitPython version

```python
Main branch
```

### Code/REPL

```python
import sys
print(sys.version)
```

### Behavior

It reports back `3.4.0; MicroPython 9.0.0-alpha.6-17-g2c453390ec on 2024-01-09`.
Should this really be left to be reported as MicroPython?

Shouldn't it be something like:
`3.4.0; CircuitPython 9.0.0-alpha.6-17-g2c453390ec on 2024-01-09; M5Stack Timer Camera X with ESP32`?
to match the repl prompt somewhat?

If this is intentional feel free to immediately close this issue.
Otherwise I can go and fix it.

**Comment by dhalbert** [comment]
This is not intentional, and is probably due to a merge mistake when we merged from upstream.
