### ISSUE TITLE
bitmaptools.draw_polygon: Change Coordinate Data Type to Integer List

### ISSUE THREAD

**Issue by CedarGroveStudios** [adafruit/circuitpython#8817]
To be able to easily use the entire polygon x-y coordinate range, please consider changing from a ReadableBuffer data type to an integer list.

From https://github.com/adafruit/circuitpython/pull/7471:

> In my application, `bitmaptools.draw_polygon` would be very useful if it accepted a large (>200) list of integers instead of a ReadableBuffer object. For now, _the application is_ iterating through a list and using `draw_line` instead.
The simpletest example shows converting a list to a byte array, but that doesn't allow coordinate values larger than 127. Using `struct` or a `ulab.numpy` array allows larger values up to 16-bits. However, `ulab` isn't available for all boards and `struct` is only practical for lists of just a few points.
A side benefit of changing the coordinate data type to integer would be UI consistency with other bitmaptool drawn objects. I'll open a new issue that specifically asks for coordinate integer lists.
BTW, being able to leave the polygon open is a big plus when plotting waveshapes and formulae, cartesian-style.

**Comment by tannewt** [comment]
I think you want `array.array`. You can give it integer size and it looks like the bitmaptools code will respect it. https://docs.python.org/3/library/array.html

**Comment by CedarGroveStudios** [comment]
Indeed it was respected. It also dropped memory usage dramatically and improved performance slightly. Perhaps the simpletest code should be changed from `byte()` to `array.array()` to help folks like me.

You helped me to peel back another layer of the Python onion. I have some other code that will likely benefit, as well.

Thank you!

**Comment by dhalbert** [comment]
Maybe `ReadableBuffer` is not the clearest type annotation. The documentation should explain that 16-bit values are possible.

**Comment by CedarGroveStudios** [comment]
I first encountered the `ReadableBuffer` data type when working with `synthio.waveform` objects -- and was initially confused. The examples and related learning guide code used `dtype=ulab.numpy.int16` which helped me to understand that those were int16 arrays as well.
