### ISSUE TITLE
import ntptime crashes ESP8266

### ISSUE THREAD

**Issue by amijalis** [adafruit/circuitpython#882]
Hello!

On the most recent version of CircuitPython (3.0 beta), the statement ```import ntptime``` crashes a freshly-flashed Adafruit ESP8266 feather. A bunch of gibberish gets printed to the REPL and then the device restarts.

On a related note, the V2 ntptime module doesn't work either. ```ntptime.time()``` correctly pulls the time from the time server, but ```ntptime.settime()``` does not properly set the rtc module, failing at an ImportError (no module named utime in CircuitPython).

Thanks!

**Comment by siddacious** [comment]
With ESP8266 support bring removed in 4.0, is this obsolete?

**Comment by tannewt** [comment]
Yup! We are no longer supporting CircuitPython on the ESP8266 because it lacks native USB.
