### ISSUE TITLE
dict.keys() is empty in subclassed dict

### ISSUE THREAD

**Issue by miguelgrinberg** [adafruit/circuitpython#8850]
### CircuitPython version

```python
MicroPython 9.0.0-alpha.6-49-gb704452f70 on 2024-01-27; linux [GCC 11.4.0] version
```

### Code/REPL

```python
class MyDict(dict):
    def __init__(self, initial_dict=None):
        super().__init__(initial_dict)

d = dict({'foo': 'bar', 'a': 123})
print(d.keys())  # keys is correct
d = MyDict({'foo': 'bar', 'a': 123})
print(d.keys())  # keys is empty
```

### Behavior

When running the above example, the base dictionary is not initialized correctly.

Output using CircuitPython:

```
{'a': 123, 'foo': 'bar'} dict_keys(['a', 'foo'])
{'a': 123, 'foo': 'bar'} dict_keys([])
```

Output using MicroPython:

```
{'a': 123, 'foo': 'bar'} dict_keys(['a', 'foo'])
{'a': 123, 'foo': 'bar'} dict_keys(['a', 'foo'])
```

Output using CPython:

```
{'foo': 'bar', 'a': 123} dict_keys(['foo', 'a'])
{'foo': 'bar', 'a': 123} dict_keys(['foo', 'a'])
```

### Description

I think this might be in part related to #8758, but unfortunately that fix does not help.

**Comment by dhalbert** [comment]
I made #8851, which I think fixes this.

**Comment by miguelgrinberg** [comment]
Thanks! I can confirm that your fix addresses the problem, and I do not have any more failures in my [microdot](https://github.coim/miguelgrinberg/microdot) test suite related to my `dict` subclass. :tada:

**Comment by dhalbert** [comment]
Great! Thanks for testing so thoroughly.
