### ISSUE TITLE
Differences in audio.play() for i2sOut under 9.x and 8.2.x  

### ISSUE THREAD

**Issue by scogswell** [adafruit/circuitpython#8867]
### CircuitPython version

```python
Adafruit CircuitPython 8.2.6-37-g7af75178ed-dirty on 2024-01-31; BLING! with ESP32S3

Adafruit CircuitPython 9.0.0-beta.0-7-g96be941d83 on 2024-01-31; BLING! with ESP32S3

(Both built for UM BLING by myself locally)
```

### Code/REPL

```python
"""
CircuitPython Wav files
"""
import time
import audiocore
import board
import audiobusio
import microcontroller

audio = audiobusio.I2SOut(microcontroller.pin.GPIO2, microcontroller.pin.GPIO1, microcontroller.pin.GPIO3) 

files=["1.wav", "2.wav"]

while True:
    for f in files:
        print(f)
        with open(f, "rb") as wavfile:
            wav = audiocore.WaveFile(wavfile)
            audio.play(wav)
            while(audio.playing):
                pass
            # audio.stop()   # must be uncommented on 9.x 
    time.sleep(5)
```

### Behavior

(This is a followup to my vaguey-alluded-to statement about IDFerror with UM BLING in issue #8865

When this tiny program runs on UM BLING (only board I can test with an i2s amp on it),  Under 9.x it will play the first file ("1.wav") and when it tries to play the second file ("2.wav") I get an IDFerror:
```
File "code.py", line 19, in <module>
espidf.IDFError: Invalid state 
```
Under 8.2.x both files play without issues.   

Adding an `audio.stop()` after the file has stopped playing makes the error go away on 9.x, and both files play.  The two .wav files are just a voice saying the number, I'll attempt to attach them to this for convenience.   

[1-2.zip](https://github.com/adafruit/circuitpython/files/14115107/1-2.zip)

I'm the first to admit I know very little about i2sOut since this is my first attempt at using it.  Maybe I always need a `audio.stop()` and I'm just lucky 8.2.x works, or maybe this is undesired behaviour?

**Comment by tannewt** [comment]
Thanks for the code. I reproduced it and snuck a fix into #8909
