### ISSUE TITLE
Deque is not iterable

### ISSUE THREAD

**Issue by berkut0** [adafruit/circuitpython#8874]
### CircuitPython version

```python
Adafruit CircuitPython 9.0.0-alpha.6 on 2023-12-12; Waveshare RP2040-Zero with rp2040
```

### Code/REPL

```python
from collections import deque

sa = deque((), 4)

list(sa)
```

### Behavior

It's pretty self-explanatory:
![image](https://github.com/adafruit/circuitpython/assets/8849896/8dde9c74-4a71-44c2-9cca-a072cd91bdb6)

**Comment by tannewt** [comment]
Does this work in MicroPython?

**Comment by berkut0** [comment]
MicroPython v1.22.1 on 2024-01-05
doesn't work either.

**Comment by tannewt** [comment]
I'd filing an issue with MicroPython if one hasn't been filed already. We're trying to get our copy of the VM to match MP.

**Comment by SAK917** [comment]
I have been working on an iterable version of the MP/CP deque for my own application and in researching this, it looks like the lack of iteration has come up numerous times over the years.  I believe this Issue in the MP repo covers it the best:  https://github.com/micropython/micropython/issues/4776.  

Long story short(er), the MP folks seem to have punted on a performant native C implementation of deque that is iterable and are suggesting folks that need/want deque iteration can use an interim Python implementation of deque that is more feature rich but less performant (and must be manually imported) until a long-term solution is implemented, possibly as a native module?  There seems to be some concerns about a C version of deque that is closer in feature parity to the Python version, but requires more space in the build.

@tannewt, if I am successful in creating an iterable C implementation of deque (based on the existing MP deque code), I was originally planning on offering it for incorporation into CP.  In light of your statement above that you are trying to get the CP copy of the VM to match MP, would your preference be for me to try getting it added to MP instead?

**Comment by tannewt** [comment]
> @tannewt, if I am successful in creating an iterable C implementation of deque (based on the existing MP deque code), I was originally planning on offering it for incorporation into CP. In light of your statement above that you are trying to get the CP copy of the VM to match MP, would your preference be for me to try getting it added to MP instead?

Please make a PR to MP with it first. If they don't respond quickly, then we can do it to CP directly. We can also merge it into CP after MP merges it but before it is released. That way the code will still be the same.

**Comment by dhalbert** [comment]
Thank you. We'll pick this up on the next merge from upstream MicroPython.
