### ISSUE TITLE
tools/test-stub.sh broken. Only one of two tests actually fails

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#8891]
`mypy -c 'import busio; b: busio.I2C; b.readfrom_into(0x30, b"")'`

Is supposed to fail because `readfrom_into()` needs to write into the buffer but is given a byte string. However, it doesn't. WriteableBuffer includes two string types that break the whole thing. If you remove them, then the test will fail.

Running mypy on the typing module gives a clue in how it fails:
```
mypy circuitpython_typing
circuitpython_typing/http.py:16: error: Skipping analyzing "adafruit_requests": module is installed, but missing library stubs or py.typed marker  [import-untyped]
circuitpython_typing/device_drivers.py:12: error: Skipping analyzing "adafruit_bus_device.i2c_device": module is installed, but missing library stubs or py.typed marker  [import-untyped]
circuitpython_typing/device_drivers.py:12: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
circuitpython_typing/__init__.py:39: error: Name "rgbmatrix" is not defined  [name-defined]
circuitpython_typing/__init__.py:40: error: Name "ulab" is not defined  [name-defined]
circuitpython_typing/__init__.py:48: error: Name "rgbmatrix" is not defined  [name-defined]
circuitpython_typing/__init__.py:49: error: Name "ulab" is not defined  [name-defined]
circuitpython_typing/__init__.py:131: error: Name "audiocore" is not defined  [name-defined]
circuitpython_typing/__init__.py:132: error: Name "audiocore" is not defined  [name-defined]
circuitpython_typing/__init__.py:133: error: Name "audiomixer" is not defined  [name-defined]
circuitpython_typing/__init__.py:134: error: Name "audiomp3" is not defined  [name-defined]
circuitpython_typing/__init__.py:135: error: Name "synthio" is not defined  [name-defined]
circuitpython_typing/__init__.py:141: error: Name "rgbmatrix" is not defined  [name-defined]
circuitpython_typing/__init__.py:144: error: Name "alarm" is not defined  [name-defined]
circuitpython_typing/socket.py:129: error: Name "_FakeSSLContext" is not defined  [name-defined]
Found 14 errors in 4 files (checked 8 source files)
```

It seems we have a circular dependency between circuitpython_typing and circuitpython stubs.

**Comment by justmobilize** [comment]
Did this come from the stub work, or is it unrelated?

**Comment by justmobilize** [comment]
two test branches for you:
https://github.com/adafruit/circuitpython/compare/main...justmobilize:circuitpython:typing-fixes?expand=1
https://github.com/adafruit/Adafruit_CircuitPython_Typing/compare/main...justmobilize:Adafruit_CircuitPython_Typing:typing-fixes?expand=1

<img width="1187" alt="image" src="https://github.com/adafruit/circuitpython/assets/1547881/37c42dd3-1ba5-4f40-8ede-eb2a33716cfa">

I know the `try/except` to get around the circular imports is strange, but not sure another way...

**Comment by dhalbert** [comment]
> It seems we have a circular dependency between circuitpython_typing and circuitpython stubs.

It seems like this would come up in the CPython world too. I wonder how they get around it.

**Comment by justmobilize** [comment]
Fixed the `try/except` by using `if TYPE_CHECKING`. Which looking is what seems to be common

**Comment by justmobilize** [comment]
@tannewt, 2 questions: 

1. Where would you like `_FakeSSLContext` imported from in `circuitpython_typing/socket.py`? We can either:

   - Do `adafruit_requests` now and if/when `adafruit_connection_manager` is merged, update it (before we remove it from requests)
   - Wait for `adafruit_connection_manager`

2. Looking at the change for [synthio](https://github.com/adafruit/circuitpython/compare/main...justmobilize:circuitpython:typing-fixes?expand=1), do you know what should be in the pyi files?

**Comment by jepler** [comment]
I filed #8895 for the synthio problems (I don't get why we weren't seeing this at CP build time!) but if you want to cover it in some other PR that's fine. The waveform argument should be `Optional` and the correct default is `None`.

**Comment by tannewt** [comment]
> @tannewt, 2 questions:
> 
>     1. Where would you like `_FakeSSLContext` imported from in `circuitpython_typing/socket.py`? We can either:
>        
>        * Do `adafruit_requests` now and if/when `adafruit_connection_manager` is merged, update it (before we remove it from requests)
>        * Wait for `adafruit_connection_manager`
> 
>     2. Looking at the change for [synthio](https://github.com/adafruit/circuitpython/compare/main...justmobilize:circuitpython:typing-fixes?expand=1), do you know what should be in the pyi files?

Lets wait for connection manager. The retry bug is exactly why we should factor out that code. (So we can fix it in one place.)

**Comment by justmobilize** [comment]
Sounds good

**Comment by justmobilize** [comment]
@tannewt if you look at [this PR for Adafruit_CircuitPython_Typing](https://github.com/adafruit/Adafruit_CircuitPython_Typing/compare/main...justmobilize:Adafruit_CircuitPython_Typing:typing-fixes?expand=1), if I pull out the changes to `circuitpython_typing/socket.py` and `requirements.txt` would you be good with that? It will get almost everything done.

**Comment by justmobilize** [comment]
@tannewt OMG. Realizing that `circuitpython_typing/socket.py` exists, means that we don't need that defined in `ConnectionManager` code at all. And that kills a **whole kb** of the `mpy`. Technically we could also remove it from `Requests` now...

If we actually add a `_FakeSSLContext` definition in `circuitpython_typing/socket.py`, we can fix this bug now and remove all that typing code from `ConnectionManager`

**Comment by dhalbert** [comment]
@justmobilize Oh, please, certainly, do that!

**Comment by justmobilize** [comment]
It's been a while since I got excited for removing a KB of compiled code...

So here's the [PR](https://github.com/adafruit/Adafruit_CircuitPython_Typing/pull/35), I'll take it out of draft as soon as the `mpy` thing get's figured out

**Comment by justmobilize** [comment]
@tannewt PR up - https://github.com/adafruit/circuitpython/pull/8898
