### ISSUE TITLE
Broken link to UF2 binary on CircuitPython.org

### ISSUE THREAD

**Issue by henrygab** [adafruit/circuitpython#8903]
Not sure if this is a build issue (thus this issue), or should be updated on website (see https://github.com/adafruit/circuitpython-org/issues/1324).

Started at [CircuitPython.org](https://circuitpython.org/board/adafruit_esp32s3_camera/) website for the Momento board.

Near the bottom is the link to [download](https://github.com/adafruit/tinyuf2/releases/download/0.18.1/tinyuf2-adafruit_esp32s3_camera-0.18.1.zip) the UF2 binary.

However, that link is incorrect.  It is currently:

`https://github.com/adafruit/tinyuf2/releases/download/0.18.1/tinyuf2-adafruit_esp32s3_camera-0.18.1.zip`

Where it should be:

`https://github.com/adafruit/tinyuf2/releases/download/0.18.1/tinyuf2-adafruit_camera_esp32s3-0.18.1.zip`

In particular, the relative ordering between `camera` and `esp32s3` differs between the build system and the website.

**Comment by jepler** [comment]
(I modified the initial message slightly to avoid spoilers)

**Comment by RetiredWizard** [comment]
The link is no longer broken, I believe this can be closed :grin:

**Comment by henrygab** [comment]
I appreciate the spoiler-avoidance.  I'm not sure what was not public.   A simple web search for the next numerical version gives multiple pages of information.   Also, emails to subscribers already went out, with shipping information.

I will defer to your greater knowledge.  Perhaps it was because I said only "reviewing" instead of "reviewing instructions for"?

Either way, thanks for the quick fix!
