### ISSUE TITLE
cpython difference in bind(), connect() arguments

### ISSUE THREAD

**Issue by jepler** [adafruit/circuitpython#8957]
### CircuitPython version

```python
9.0.0-beta
```

### Code/REPL

```python
>>> s = pool.socket() # or socket.socket
>>> b = bytearray(b'0.0.0.0')
>>> s.connect((b, 443))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't convert 'bytearray' object to str implicitly
```

### Behavior

In standard Python, the bytearray is accepted (and the connection fails, because there's no listener):
```py
Python 3.11.2 (main, Mar 13 2023, 12:18:29) [GCC 12.2.0] on linux
>>> b = bytearray(b'0.0.0.0')
>>> s.connect((b, 443))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ConnectionRefusedError: [Errno 111] Connection refused
```
Similar for bind():
```
# circuitpython
>>> s.bind((bytearray(), 1234))
TypeError: can't convert 'bytearray' object to str implicitly
```
vs
```
# cpython 3.11
>>> s.bind((bytearray(), 1234))
>>> 
```

### Additional information

I ran into this while working on #8954. In that PR I was converting the bind/connect argument to a bytearray (because this let me avoid an allocation) but it didn't work.

**Comment by jepler** [comment]
While working on this it might be nice to make the empty hostname function the same as '0.0.0.0', again for compatibility with standard python.

**Comment by tannewt** [comment]
What is the advantage of allowing bytearray ASCII? This seems to go against the idea that strings are for bytes + encoding.

**Comment by jepler** [comment]
standard Python accepts a bytearray here, even if it's surprising. if we can accept a bytearray without (say) code bloat, I don't see why not to.

**Comment by tannewt** [comment]
Where does the bytearray come from? It should be a string. We don't do many things that CPython allows. Only the reverse needs to be true. (That CPython is ok with what we do.)

**Comment by jepler** [comment]
In the draft ssl-anything PR I arrange to just pass the original objects down, instead of unparsing them and rebuilding them. So except for compatiblity with a weird nook of cpython this is moot for me.
