### ISSUE TITLE
Rename `ports/nrf` so as not to overlap with MicroPython

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#8967]
Currently our `ports` directories are disjunct from MicroPython except for `unix` and `nrf`. Renaming the `nrf` directory would make merging from upstream a little easier in the future, so let's do it before the next merge.

I would suggest `nordic`, `nrf52`, or `nrf-sd`. The last is because the port is based on the older SoftDevice, not zephyr. Suggestions welcome.

**Comment by tannewt** [comment]
I wouldn't do `nrf52` because I expect we'll want to add nrf54 support when we can get our hands on one. `nordic` is fine with me.

**Comment by dhalbert** [comment]
done by #9062.
