### ISSUE TITLE
Linker error when compiling CP 8.2.10 with double (complex) float enabled

### ISSUE THREAD

**Issue by h-milz** [adafruit/circuitpython#9028]
### CircuitPython version

```python
Adafruit CircuitPython 8.2.10 on 2024-02-14; Adafruit Feather RP2040 with rp2040
(similarly on feather-m4-express so I suspect it's a general issue)

I am trying to build a custom image for the Feather RP2040, enabling MICROPY_FLOAT_IMPL_DOUBLE, 
MICROPY_PY_CMATH and ULAB_SUPPORTS_COMPLEX. My local changes are in boards/adafruit_feather_rp2040/
mpconfigboard.h (see below), and I noticed that since double was ditched in 2018 (?), apparently 
the newer gcc-arm-none-eabi-10.3.1 (on Ubuntu 22.04 LTS) is more critical about various thing like implicit 
float to double conversions. I also noticed that in many source files, constants are deliberately declared 
as float, like 0.0f, which leads to many compiler errors when handling variables that are declared as 
mp_float_t. I do not think that hardcoding constants as fixed types is very clean, so in order to fix this I 
replaced a number (maybe not all) occurences of float by explicit type casts, e.g. MP_CONST_FLOAT(0.0), 
after which the code compiles cleanly with MICROPY_FLOAT_IMPL_DOUBLE set or not 
set. I also had to ignore some warnings like float-equal and overflow.

So far so good. But in the last stage, the linker now throws many errors like

/usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: build-adafruit_feather_rp2040/extmod/ulab/code/ndarray.o: in function `ndarray_copy_view_convert_type':
ndarray.c:(.text.ndarray_copy_view_convert_type+0x76): undefined reference to `__wrap_round'

Apparently, this behaviour is triggered by setting 

#define MICROPY_FLOAT_IMPL (MICROPY_FLOAT_IMPL_DOUBLE)

A similar thing happens when compiling feather-m4-express: 

/usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: /tmp/firmware.elf.jy2M1p.ltrans113.ltrans.o:<artificial>:(.text.ndarray_binary_power+0x268): more undefined references to `pow' follow

My extra settings in mpconfigboard.h are: 

#ifdef MICROPY_FLOAT_IMPL
#undef MICROPY_FLOAT_IMPL
#define MICROPY_FLOAT_IMPL (MICROPY_FLOAT_IMPL_DOUBLE)
#endif

#ifdef MICROPY_PY_CMATH
#undef MICROPY_PY_CMATH
#define MICROPY_PY_CMATH  (1)
#endif

#ifdef ULAB_SUPPORTS_COMPLEX
#undef ULAB_SUPPORTS_COMPLEX
#define ULAB_SUPPORTS_COMPLEX  (1)
#endif

#pragma GCC diagnostic ignored "-Wfloat-equal"
#pragma GCC diagnostic ignored "-Woverflow"

Thank you!
```

### Code/REPL

```python
-- none --
```

### Behavior

-- none --

**Comment by dhalbert** [comment]
Have you tried on `main` instead? 9.0.0 is imminent, and includes a big jump in gcc versions and MicroPython updates. I think that is where to spend the time to get this to work.

**Comment by jepler** [comment]
Related to this, I have these two commits in one of my trees (port-posix): efcad6457b715dbdb3f38582467e1379ccc8b1b8 e6aac4014eb9b77c641d3fb3ccfa9c0580a3c584

Feel free to pull them into a separate branch and PR it, or use it as the basis of your own changes -- the port-posix work is not progressing at the moment.

**Comment by h-milz** [comment]
@dhalbert, same thing with 9.0.0beta2, tried with m4 express: 

/usr/bin/../lib/gcc/arm-none-eabi/13.2.1/../../../../arm-none-eabi/bin/ld: /tmp/cctg8k9g.ltrans113.ltrans.o:<artificial>:(.text.ndarray_binary_power+0x268): more undefined references to `pow' follow

I also had issues with MP_STATIC_ASSERT in py.obj.h and commented it out - no idea if there are any side effects. 

@jepler, I had to change many more places. Raw git diff below, but it is very possible I did not catch them all. 

`diff --git a/ports/atmel-samd/boards/feather_m4_express/mpconfigboard.h b/ports/atmel-samd/boards/feather_m4_express/mpconfigboard.h
index 0744fc3f92..8ad0068d7d 100644
--- a/ports/atmel-samd/boards/feather_m4_express/mpconfigboard.h
+++ b/ports/atmel-samd/boards/feather_m4_express/mpconfigboard.h
@@ -23,3 +23,25 @@
 // USB is always used internally so skip the pin objects for it.
 #define IGNORE_PIN_PA24     1
 #define IGNORE_PIN_PA25     1
+
+/* local additions for double float and complex handling */
+
+#ifdef MICROPY_FLOAT_IMPL
+#undef MICROPY_FLOAT_IMPL
+#define MICROPY_FLOAT_IMPL (MICROPY_FLOAT_IMPL_DOUBLE)
+#endif
+
+#ifdef MICROPY_PY_CMATH
+#undef MICROPY_PY_CMATH
+#define MICROPY_PY_CMATH  (1)
+#endif
+
+#ifdef ULAB_SUPPORTS_COMPLEX
+#undef ULAB_SUPPORTS_COMPLEX
+#define ULAB_SUPPORTS_COMPLEX  (1)
+#endif
+
+#pragma GCC diagnostic ignored "-Wfloat-equal"
+#pragma GCC diagnostic ignored "-Woverflow"
+
+
diff --git a/ports/atmel-samd/common-hal/alarm/time/TimeAlarm.c b/ports/atmel-samd/common-hal/alarm/time/TimeAlarm.c
index a8f408181f..c929e669bc 100644
--- a/ports/atmel-samd/common-hal/alarm/time/TimeAlarm.c
+++ b/ports/atmel-samd/common-hal/alarm/time/TimeAlarm.c
@@ -78,7 +78,7 @@ void time_alarm_callback(void) {
 
 bool alarm_time_timealarm_woke_this_cycle(void) {
     if (SAMD_ALARM_FLAG_TIME_CHK) {
-        mp_float_t now_secs = uint64_to_float(common_hal_time_monotonic_ms()) / 1000.0f;
+        mp_float_t now_secs = uint64_to_float(common_hal_time_monotonic_ms()) / MICROPY_FLOAT_CONST(1000.0);
         if (now_secs > wakeup_time) {
             woke_up = true;
         }
@@ -116,7 +116,7 @@ void alarm_time_timealarm_set_alarms(bool deep_sleep, size_t n_alarms, const mp_
 
     // Compute how long to actually sleep, considering the time now.
     // At least 1 count = 1/16384 sec is necessary.
-    mp_float_t now_secs = uint64_to_float(common_hal_time_monotonic_ms()) / 1000.0f;
+    mp_float_t now_secs = uint64_to_float(common_hal_time_monotonic_ms()) / MICROPY_FLOAT_CONST(1000.0);
     uint32_t wakeup_in_counts = MAX(1, (uint32_t)((wakeup_time - now_secs) * 16384));
 
 
@@ -137,7 +137,7 @@ void alarm_time_timealarm_prepare_for_deep_sleep(void) {
     // In deep sleep mode, prescaler is set to 1024, so that 1 count = 1/32 s.
     // At least 1 count is necessary.
 
-    mp_float_t now_secs = uint64_to_float(common_hal_time_monotonic_ms()) / 1000.0f;
+    mp_float_t now_secs = uint64_to_float(common_hal_time_monotonic_ms()) / MICROPY_FLOAT_CONST(1000.0);
     uint32_t wakeup_in_counts = MAX(1, (uint32_t)((wakeup_time - now_secs) * 32));
     RTC->MODE0.COMP[1].reg = wakeup_in_counts;
     while ((RTC->MODE0.SYNCBUSY.reg & (RTC_MODE0_SYNCBUSY_COMP1)) != 0) {
diff --git a/py/formatfloat.c b/py/formatfloat.c
index a2855b8afc..57e17fc939 100644
--- a/py/formatfloat.c
+++ b/py/formatfloat.c
@@ -82,15 +82,15 @@ static inline int fp_isless1(float x) {
 
 #pragma GCC diagnostic ignored "-Wfloat-equal"
 #define FPTYPE double
-#define FPCONST(x) x
-#define FPROUND_TO_ONE 0.999999999995
+#define FPCONST(x) (double)x
+#define FPROUND_TO_ONE (double)0.999999999995
 #define FPDECEXP 256
 #define FPMIN_BUF_SIZE 7 // +9e+199
 #define fp_signbit(x) signbit(x)
 #define fp_isnan(x) isnan(x)
 #define fp_isinf(x) isinf(x)
-#define fp_iszero(x) (x == 0)
-#define fp_isless1(x) (x < 1.0)
+#define fp_iszero(x) (x == (double)0)
+#define fp_isless1(x) (x < (double)1.0)
 
 #endif // MICROPY_FLOAT_IMPL == MICROPY_FLOAT_IMPL_FLOAT/DOUBLE
 
diff --git a/py/mpconfig.h b/py/mpconfig.h
index 6510dc13a9..ef8fb91f28 100644
--- a/py/mpconfig.h
+++ b/py/mpconfig.h
@@ -840,7 +840,7 @@ typedef long long mp_longint_impl_t;
 typedef float mp_float_t;
 #elif MICROPY_FLOAT_IMPL == MICROPY_FLOAT_IMPL_DOUBLE
 #define MICROPY_PY_BUILTINS_FLOAT (1)
-#define MICROPY_FLOAT_CONST(x) x
+#define MICROPY_FLOAT_CONST(x) (double)x
 #define MICROPY_FLOAT_C_FUN(fun) fun
 typedef double mp_float_t;
 #else
diff --git a/py/obj.h b/py/obj.h
index 4ddf30115d..771c8a6510 100644
--- a/py/obj.h
+++ b/py/obj.h
@@ -194,7 +194,7 @@ static inline bool mp_obj_is_small_int(mp_const_obj_t o) {
 
 static inline bool mp_obj_is_float(mp_const_obj_t o) {
     // Ensure that 32-bit arch can only use single precision.
-    MP_STATIC_ASSERT(sizeof(mp_float_t) <= sizeof(mp_obj_t));
+    // MP_STATIC_ASSERT(sizeof(mp_float_t) <= sizeof(mp_obj_t));
 
     return (((mp_uint_t)(o)) & 3) == 2 && (((mp_uint_t)(o)) & 0xff800007) != 0x00000006;
 }
diff --git a/py/objstr.c b/py/objstr.c
index b624c35987..a0fa43306b 100644
--- a/py/objstr.c
+++ b/py/objstr.c
@@ -1398,7 +1398,7 @@ STATIC vstr_t mp_obj_str_format_helper(const char *str, const char *top, int *ar
                     #if MICROPY_FLOAT_IMPL == MICROPY_FLOAT_IMPL_FLOAT
                     #define F100 100.0F
                     #else
-                    #define F100 100.0
+                    #define F100 (double)100.0
                     #endif
                     mp_print_float(&print, mp_obj_get_float(arg) * F100, 'f', flags, fill, width, precision);
 #undef F100
diff --git a/py/parsenum.c b/py/parsenum.c
index 68f7417c0b..e2256d0d90 100644
--- a/py/parsenum.c
+++ b/py/parsenum.c
@@ -192,8 +192,8 @@ typedef enum {
 #define SMALL_NORMAL_EXP (-37)
 #define EXACT_POWER_OF_10 (9)
 #elif MICROPY_FLOAT_IMPL == MICROPY_FLOAT_IMPL_DOUBLE
-#define DEC_VAL_MAX 1e200
-#define SMALL_NORMAL_VAL (1e-307)
+#define DEC_VAL_MAX (double)1e200
+#define SMALL_NORMAL_VAL (double)(1e-307)
 #define SMALL_NORMAL_EXP (-307)
 #define EXACT_POWER_OF_10 (22)
 #endif
diff --git a/shared-bindings/_bleio/Adapter.c b/shared-bindings/_bleio/Adapter.c
index 005f30f8b3..6fb7313aa2 100644
--- a/shared-bindings/_bleio/Adapter.c
+++ b/shared-bindings/_bleio/Adapter.c
@@ -33,19 +33,19 @@
 #include "shared-bindings/_bleio/Address.h"
 #include "shared-bindings/_bleio/Adapter.h"
 
-#define ADV_INTERVAL_MIN (0.02f)
+#define ADV_INTERVAL_MIN MICROPY_FLOAT_CONST(0.02)
 #define ADV_INTERVAL_MIN_STRING "0.02"
-#define ADV_INTERVAL_MAX (10.24f)
+#define ADV_INTERVAL_MAX MICROPY_FLOAT_CONST(10.24)
 #define ADV_INTERVAL_MAX_STRING "10.24"
 // 20ms is recommended by Apple
-#define ADV_INTERVAL_DEFAULT (0.1f)
+#define ADV_INTERVAL_DEFAULT MICROPY_FLOAT_CONST(0.1)
 
-#define INTERVAL_DEFAULT (0.1f)
-#define INTERVAL_MIN (0.0025f)
+#define INTERVAL_DEFAULT MICROPY_FLOAT_CONST(0.1)
+#define INTERVAL_MIN MICROPY_FLOAT_CONST(0.0025)
 #define INTERVAL_MIN_STRING "0.0025"
-#define INTERVAL_MAX (40.959375f)
+#define INTERVAL_MAX MICROPY_FLOAT_CONST(40.959375)
 #define INTERVAL_MAX_STRING "40.959375"
-#define WINDOW_DEFAULT (0.1f)
+#define WINDOW_DEFAULT MICROPY_FLOAT_CONST(0.1)
 
 //| class Adapter:
 //|     """
@@ -339,7 +339,7 @@ STATIC mp_obj_t bleio_adapter_start_scan(size_t n_args, const mp_obj_t *pos_args
 
     #pragma GCC diagnostic push
     #pragma GCC diagnostic ignored "-Wfloat-equal"
-    if (timeout != 0.0f && timeout < interval) {
+    if (timeout != MICROPY_FLOAT_CONST(0.0) && timeout < interval) {
         mp_raise_ValueError(MP_ERROR_TEXT("non-zero timeout must be >= interval"));
     }
     #pragma GCC diagnostic pop
diff --git a/shared-bindings/busdisplay/BusDisplay.c b/shared-bindings/busdisplay/BusDisplay.c
index 40e10e522f..92b71484a7 100644
--- a/shared-bindings/busdisplay/BusDisplay.c
+++ b/shared-bindings/busdisplay/BusDisplay.c
@@ -343,7 +343,7 @@ MP_DEFINE_CONST_FUN_OBJ_1(busdisplay_busdisplay_get_brightness_obj, busdisplay_b
 STATIC mp_obj_t busdisplay_busdisplay_obj_set_brightness(mp_obj_t self_in, mp_obj_t brightness_obj) {
     busdisplay_busdisplay_obj_t *self = native_display(self_in);
     mp_float_t brightness = mp_obj_get_float(brightness_obj);
-    if (brightness < 0 || brightness > 1.0) {
+    if (brightness < 0 || brightness > MICROPY_FLOAT_CONST(1.0)) {
         mp_raise_ValueError_varg(MP_ERROR_TEXT("%q must be %d-%d"), MP_QSTR_brightness, 0, 1);
     }
     bool ok = common_hal_busdisplay_busdisplay_set_brightness(self, brightness);
diff --git a/shared-bindings/framebufferio/FramebufferDisplay.c b/shared-bindings/framebufferio/FramebufferDisplay.c
index 3e0c75cd74..78896bc5f7 100644
--- a/shared-bindings/framebufferio/FramebufferDisplay.c
+++ b/shared-bindings/framebufferio/FramebufferDisplay.c
@@ -194,7 +194,7 @@ MP_DEFINE_CONST_FUN_OBJ_1(framebufferio_framebufferdisplay_get_brightness_obj, f
 STATIC mp_obj_t framebufferio_framebufferdisplay_obj_set_brightness(mp_obj_t self_in, mp_obj_t brightness_obj) {
     framebufferio_framebufferdisplay_obj_t *self = native_display(self_in);
     mp_float_t brightness = mp_obj_get_float(brightness_obj);
-    if (brightness < 0.0f || brightness > 1.0f) {
+    if (brightness < MICROPY_FLOAT_CONST(0.0) || brightness > MICROPY_FLOAT_CONST(1.0)) {
         mp_raise_ValueError_varg(MP_ERROR_TEXT("%q must be %d-%d"), MP_QSTR_brightness, 0, 1);
     }
     bool ok = common_hal_framebufferio_framebufferdisplay_set_brightness(self, brightness);
diff --git a/shared-bindings/rgbmatrix/RGBMatrix.c b/shared-bindings/rgbmatrix/RGBMatrix.c
index 4f47ef3814..d043d387e9 100644
--- a/shared-bindings/rgbmatrix/RGBMatrix.c
+++ b/shared-bindings/rgbmatrix/RGBMatrix.c
@@ -317,7 +317,7 @@ STATIC mp_obj_t rgbmatrix_rgbmatrix_set_brightness(mp_obj_t self_in, mp_obj_t va
     rgbmatrix_rgbmatrix_obj_t *self = (rgbmatrix_rgbmatrix_obj_t *)self_in;
     check_for_deinit(self);
     mp_float_t brightness = mp_obj_get_float(value_in);
-    if (brightness < 0.0f || brightness > 1.0f) {
+    if (brightness < MICROPY_FLOAT_CONST(0.0) || brightness > MICROPY_FLOAT_CONST(1.0)) {
         mp_raise_ValueError_varg(MP_ERROR_TEXT("%q must be %d-%d"), MP_QSTR_brightness, 0, 1);
     }
     common_hal_rgbmatrix_rgbmatrix_set_paused(self, brightness <= 0);
@@ -390,7 +390,11 @@ STATIC void rgbmatrix_rgbmatrix_deinit_proto(mp_obj_t self_in) {
     common_hal_rgbmatrix_rgbmatrix_deinit(self_in);
 }
 
+#if MICROPY_FLOAT_IMPL == MICROPY_FLOAT_IMPL_FLOAT
 STATIC float rgbmatrix_rgbmatrix_get_brightness_proto(mp_obj_t self_in) {
+#else
+STATIC double rgbmatrix_rgbmatrix_get_brightness_proto(mp_obj_t self_in) {
+#endif		
     return common_hal_rgbmatrix_rgbmatrix_get_paused(self_in) ? 0.0f : 1.0f;
 }
 
diff --git a/shared-bindings/usb_cdc/Serial.c b/shared-bindings/usb_cdc/Serial.c
index 696e401f62..de8bb6d9ac 100644
--- a/shared-bindings/usb_cdc/Serial.c
+++ b/shared-bindings/usb_cdc/Serial.c
@@ -206,14 +206,14 @@ MP_DEFINE_CONST_FUN_OBJ_1(usb_cdc_serial_reset_output_buffer_obj, usb_cdc_serial
 STATIC mp_obj_t usb_cdc_serial_get_timeout(mp_obj_t self_in) {
     usb_cdc_serial_obj_t *self = MP_OBJ_TO_PTR(self_in);
     mp_float_t timeout = common_hal_usb_cdc_serial_get_timeout(self);
-    return (timeout < 0.0f) ? mp_const_none : mp_obj_new_float(self->timeout);
+    return (timeout < MICROPY_FLOAT_CONST(0.0)) ? mp_const_none : mp_obj_new_float(self->timeout);
 }
 MP_DEFINE_CONST_FUN_OBJ_1(usb_cdc_serial_get_timeout_obj, usb_cdc_serial_get_timeout);
 
 STATIC mp_obj_t usb_cdc_serial_set_timeout(mp_obj_t self_in, mp_obj_t timeout_in) {
     usb_cdc_serial_obj_t *self = MP_OBJ_TO_PTR(self_in);
     common_hal_usb_cdc_serial_set_timeout(self,
-        timeout_in == mp_const_none ? -1.0f : mp_obj_get_float(timeout_in));
+        timeout_in == mp_const_none ? MICROPY_FLOAT_CONST(-1.0) : mp_obj_get_float(timeout_in));
     return mp_const_none;
 }
 MP_DEFINE_CONST_FUN_OBJ_2(usb_cdc_serial_set_timeout_obj, usb_cdc_serial_set_timeout);
@@ -230,14 +230,14 @@ MP_PROPERTY_GETSET(usb_cdc_serial_timeout_obj,
 STATIC mp_obj_t usb_cdc_serial_get_write_timeout(mp_obj_t self_in) {
     usb_cdc_serial_obj_t *self = MP_OBJ_TO_PTR(self_in);
     mp_float_t write_timeout = common_hal_usb_cdc_serial_get_write_timeout(self);
-    return (write_timeout < 0.0f) ? mp_const_none : mp_obj_new_float(self->write_timeout);
+    return (write_timeout < MICROPY_FLOAT_CONST(0.0)) ? mp_const_none : mp_obj_new_float(self->write_timeout);
 }
 MP_DEFINE_CONST_FUN_OBJ_1(usb_cdc_serial_get_write_timeout_obj, usb_cdc_serial_get_write_timeout);
 
 STATIC mp_obj_t usb_cdc_serial_set_write_timeout(mp_obj_t self_in, mp_obj_t write_timeout_in) {
     usb_cdc_serial_obj_t *self = MP_OBJ_TO_PTR(self_in);
     common_hal_usb_cdc_serial_set_write_timeout(self,
-        write_timeout_in == mp_const_none ? -1.0f : mp_obj_get_float(write_timeout_in));
+        write_timeout_in == mp_const_none ? MICROPY_FLOAT_CONST(-1.0) : mp_obj_get_float(write_timeout_in));
     return mp_const_none;
 }
 MP_DEFINE_CONST_FUN_OBJ_2(usb_cdc_serial_set_write_timeout_obj, usb_cdc_serial_set_write_timeout);
diff --git a/shared-module/busdisplay/BusDisplay.c b/shared-module/busdisplay/BusDisplay.c
index c20efe7d68..7d42811695 100644
--- a/shared-module/busdisplay/BusDisplay.c
+++ b/shared-module/busdisplay/BusDisplay.c
@@ -159,7 +159,7 @@ mp_float_t common_hal_busdisplay_busdisplay_get_brightness(busdisplay_busdisplay
 
 bool common_hal_busdisplay_busdisplay_set_brightness(busdisplay_busdisplay_obj_t *self, mp_float_t brightness) {
     if (!self->backlight_on_high) {
-        brightness = 1.0 - brightness;
+        brightness = MICROPY_FLOAT_CONST(1.0) - brightness;
     }
     bool ok = false;
 
@@ -178,7 +178,7 @@ bool common_hal_busdisplay_busdisplay_set_brightness(busdisplay_busdisplay_obj_t
         ok = false;
         #endif
     } else if (self->backlight_inout.base.type == &digitalio_digitalinout_type) {
-        common_hal_digitalio_digitalinout_set_value(&self->backlight_inout, brightness > 0.99);
+        common_hal_digitalio_digitalinout_set_value(&self->backlight_inout, brightness > MICROPY_FLOAT_CONST(0.99));
         ok = true;
     } else if (self->brightness_command != NO_BRIGHTNESS_COMMAND) {
         ok = displayio_display_bus_begin_transaction(&self->bus);
diff --git a/shared-module/usb_cdc/Serial.c b/shared-module/usb_cdc/Serial.c
index 23bcc8722d..b8f9341372 100644
--- a/shared-module/usb_cdc/Serial.c
+++ b/shared-module/usb_cdc/Serial.c
@@ -33,8 +33,8 @@
 
 size_t common_hal_usb_cdc_serial_read(usb_cdc_serial_obj_t *self, uint8_t *data, size_t len, int *errcode) {
 
-    const bool wait_forever = self->timeout < 0.0f;
-    const bool wait_for_timeout = self->timeout > 0.0f;
+    const bool wait_forever = self->timeout < MICROPY_FLOAT_CONST(0.0);
+    const bool wait_for_timeout = self->timeout > MICROPY_FLOAT_CONST(0.0);
 
     // Read up to len bytes immediately.
     // The number of bytes read will not be larger than what is already in the TinyUSB FIFO.
@@ -79,8 +79,8 @@ size_t common_hal_usb_cdc_serial_read(usb_cdc_serial_obj_t *self, uint8_t *data,
 }
 
 size_t common_hal_usb_cdc_serial_write(usb_cdc_serial_obj_t *self, const uint8_t *data, size_t len, int *errcode) {
-    const bool wait_forever = self->write_timeout < 0.0f;
-    const bool wait_for_timeout = self->write_timeout > 0.0f;
+    const bool wait_forever = self->write_timeout < MICROPY_FLOAT_CONST(0.0);
+    const bool wait_for_timeout = self->write_timeout > MICROPY_FLOAT_CONST(0.0);
 
     // Write as many bytes as possible immediately.
     // The number of bytes written at once will not be larger than what can fit in the TinyUSB FIFO.
`

**Comment by h-milz** [comment]
After a bit of code reading, I think I found an ansatz. py/mpconfig.h, if _FLOAT is set, defines: 

#define MICROPY_FLOAT_C_FUN(fun) fun##f

which chops the appended f from all function names in libm/*.c. Otherwise, if DOUBLE ist set, the define is

#define MICROPY_FLOAT_C_FUN(fun) fun 

which chops nothing. Consequently, the functions in libm/*.c are not found. But they should not be found in the first place, but the functions in libm_dbl. 

Later today, I'll introduce INTERNAL_LIBM = 2 as a hack, and will set up libm_dbl to be used in py/circuitpy_defns.mk:837 and following, and in ./ports/raspberrypi/Makefile:425. It's an ugly hack for now. Hints welcome for a better style. 

Any comments concerning the MP_STATIC_ASSERT thing mentioned before? 

(I also tried to use the toolchain libm saying INTERNAL_LIBM=0 and adding -L for the lib path, but I can't seem to make the linker to find it.)

**Comment by h-milz** [comment]
OK it seems I should avoid this hack and try to use libm.a instead. Compiles now, but I'll need to throw out some unneeded modules on M4 Express. In RP2040, I don't get these -wrap-things to link with libm.a.
