### ISSUE TITLE
Adafruit_CircuitPython_Requests needs update

### ISSUE THREAD

**Issue by bablokb** [adafruit/circuitpython#9036]
### CircuitPython version

```python
Adafruit CircuitPython 9.0.0-rc.0 on 2024-03-08; Adafruit MagTag with ESP32S2
```

### Code/REPL

```python
n.a.
```

### Behavior

The `close()` method of `Response` fails in certain cases. This has already been fixed, see https://github.com/adafruit/Adafruit_CircuitPython_Requests/pull/156 but the submodule here needs an update as well, since it still ships the buggy version (I think circup does this too).

Some boards like the Magtag include Requests as part of the frozen libs, so it is not possible that I ship the fixed version myself.

**Comment by dhalbert** [comment]
I did update the frozen modules for 9.0.0-rc.0, but `adafruit_requests` needed a new release, which I didn't realize. I've made that release and will update again before final. We should check whether any other libraries need a release as well.
