### ISSUE TITLE
SPI Device Manager needs parameter for bit width

### ISSUE THREAD

**Issue by kamocat** [adafruit/circuitpython#9044]
The [busio.SPI](https://docs.circuitpython.org/en/latest/shared-bindings/busio/#busio.SPI) class has a parameter to set the bit width, but this parameter is not available in the [SPI device manager](https://docs.circuitpython.org/en/latest/shared-bindings/adafruit_bus_device/spi_device/index.html)

**Comment by kamocat** [comment]
It seems the implementation could be as simple as passing along the kwargs:

```python
class SPIDevice:
    def __init__(self, bus, cs:digitalio.DigitalInOut|None=None, cs_active_value=False, extra_clocks:int=0, **kwargs):
        self.bus = bus
        self.cs = cs
        self.active_val = cs_active_value
        self.extra_clocks = extra_clocks
        self.config = kwargs
    def __enter__(self):
        assert self.bus.try_lock()
        self.bus.configure(self.config)
        if self.cs is not None:
            self.cs.value = self.active_val
        # FIXME: insert extra clocks
    def __exit__(self):
        if self.cs is not None:
            self.cs.value = not self.active_val
            self.bus.unlock()
```

**Comment by tannewt** [comment]
@kamocat PRs to the Python busdevice and the core C implementation would be welcome.

**Comment by kamocat** [comment]
I'll consider it.
In the meantime, it seems the busio.SPI class only allows 8 or 9 bits, although the RP2040 supports anywhere from 4 to 16 bits and the ESP32 SPI has some really crazy settings.
I suppose it's because the SAMD21 Sercom peripheral only supports 8 or 9 bits and the NRF52840 *only* supports 8 bit words.

I wonder if the spi write and readinto functions handle 16-bit arrays transparently, without any need to set the bit width?

**Comment by dhalbert** [comment]
This is also discussed in
- #8179

**Comment by kamocat** [comment]
I'm writing a driver for ADS131M04, which uses 16 bit registers and supports 16, 24, or 32 bit words.

**Comment by dhalbert** [comment]
> I'm writing a driver for ADS131M04, which uses 16 bit registers and supports 16, 24, or 32 bit words.

You can just send 8-bit-bytes concatenated, which I'm assuming you know already. Lots of our existing CircuitPython drivers do that for various SPI devices.  You can use `struct` or `.to_bytes` and .from_bytes` to convert to/from integers.

**Comment by kamocat** [comment]
Unless anyone actually has a 9-bit SPI device, I think we can close this.
