### ISSUE TITLE
ulab.numpy.carray not available

### ISSUE THREAD

**Issue by h-milz** [adafruit/circuitpython#9052]
### CircuitPython version

```python
Adafruit CircuitPython 9.0.0-rc.1 on 2024-03-14; Adafruit Feather M4 Express with samd51j19
```
ulab.numpy does not seem to contain carray respectively it does not support complex arrays as documented
in [.](https://docs.circuitpython.org/en/latest/shared-bindings/ulab/numpy/index.html) . 
```py
>>> import ulab.numpy as np
>>> dir (np)
['__class__', '__name__', 'all', 'any', 'bool', 'sort', 'sum', '__dict__', 'acos', 'acosh', 'arange', 'arctan2', 'argmax', 'argmin', 'argsort', 'around', 'array', 'asarray', 'asin', 'asinh', 'atan', 'atanh', 'bitwise_and', 'bitwise_or', 'bitwise_xor', 'ceil', 'clip', 'compress', 'concatenate', 'convolve', 'cos', 'cosh', 'cross', 'degrees', 'delete', 'diag', 'diff', 'dot', 'e', 'empty', 'equal', 'exp', 'expm1', 'eye', 'fft', 'flip', 'float', 'floor', 'frombuffer', 'full', 'get_printoptions', 'inf', 'int16', 'int8', 'interp', 'isfinite', 'isinf', 'left_shift', 'linalg', 'linspace', 'load', 'loadtxt', 'log', 'log10', 'log2', 'logspace', 'max', 'maximum', 'mean', 'median', 'min', 'minimum', 'nan', 'ndarray', 'ndinfo', 'nonzero', 'not_equal', 'ones', 'pi', 'polyfit', 'polyval', 'radians', 'right_shift', 'roll', 'save', 'savetxt', 'set_printoptions', 'sin', 'sinc', 'sinh', 'size', 'sqrt', 'std', 'tan', 'tanh', 'trace', 'trapz', 'uint16', 'uint8', 'vectorize', 'where', 'zeros']
```
My custom 9.0.0.rc0 build with `ULAB_SUPPORTS_COMPLEX` explicitly set does support e.g. np.conjugate 
as shown below but complex arrays don't work either. 

I know that `ULAB_SUPPORTS_COMPLEX` is set to `0` in `py/circuitpy_mpconfig.h` but this setting 
seems to be checked nowhere in the entire source tree except in `ulab.h`: 

```c
#ifndef ULAB_SUPPORTS_COMPLEX
#define ULAB_SUPPORTS_COMPLEX               (1)
```
The error message below is here: 

```
./code/numpy/vector.c:904:            mp_raise_TypeError(MP_ERROR_TEXT("can't convert complex to float"));
```

### Code/REPL

```python
>>> import ulab.numpy as np
>>> a=(1+4j)
>>> np.conjugate(a)
(1-4j)
>>> complex_array = np.array([1+2j, 3+4j, 5+6j])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't convert complex to float
```

### Behavior

see above

### Description

see above

**Comment by dhalbert** [comment]
> I know that `ULAB_SUPPORTS_COMPLEX` is set to `0` in `py/circuitpy_mpconfig.h` but this setting
> seems to be checked nowhere in the entire source tree except in `ulab.h`:

I see ULAB_SUPPORTS_COMPLEX checked in many places:
```sh
~/repos/circuitpython$ ag '#if ULAB_SUPPORTS_COMPLEX' -l
extmod/ulab/code/ulab_tools.c
extmod/ulab/code/ndarray.c
extmod/ulab/code/ndarray_operators.c
extmod/ulab/code/numpy/numpy.c
extmod/ulab/code/numpy/carray/carray_tools.h
extmod/ulab/code/numpy/carray/carray_tools.c
extmod/ulab/code/numpy/carray/carray.c
extmod/ulab/code/numpy/compare.c
extmod/ulab/code/numpy/filter.c
extmod/ulab/code/numpy/create.c
extmod/ulab/code/numpy/poly.c
extmod/ulab/code/numpy/numerical.c
extmod/ulab/code/numpy/fft/fft_tools.c
extmod/ulab/code/numpy/fft/fft.h
extmod/ulab/code/numpy/fft/fft_tools.h
extmod/ulab/code/numpy/fft/fft.c
extmod/ulab/code/numpy/bitwise.c
extmod/ulab/code/numpy/vector.c
extmod/ulab/code/numpy/io/io.c
extmod/ulab/code/numpy/vector.h
extmod/ulab/code/utils/utils.c
extmod/ulab/code/scipy/signal/signal.c
extmod/ulab/code/ulab.c
extmod/ulab/code/ndarray_properties.c
extmod/ulab/code/ndarray.h
extmod/ulab/code/ulab_tools.h
```
I'm not clear if you did set it to `(1)` in `circuitpy_mpconfig.h` or not.

**Comment by h-milz** [comment]
@dhalbert I did ... 

$ grep SUPPORTS_COM ../../py/circuitpy_mpconfig.h
#ifndef ULAB_SUPPORTS_COMPLEX
#define ULAB_SUPPORTS_COMPLEX (1)

**Comment by dhalbert** [comment]
Do you see `carray` available in a MicroPython build with `ulab` on (I don't know which MicroPython builds it's turned on in).

Pinging @v923z here, as this may be a `ulab` issue.

**Comment by h-milz** [comment]
No idea, I'm not into MP atm.

**Comment by v923z** [comment]
On `micropython`, I can conjugate numbers. I settings are in https://github.com/v923z/micropython-ulab/blob/master/code/ulab.h, so I must assume that `ULAB_SUPPORTS_COMPLEX` is defined  somewhere by `circuitpython`.

**Comment by dhalbert** [comment]
@h-milz This works for me, when `#define ULAB_SUPPORTS_COMPLEX (1)`. You have to give the `dtype` explicitly.

Adafruit CircuitPython 9.0.0-1-gdc69c29dac-dirty on 2024-03-22; Adafruit Feather RP2040 with rp2040
>>> import ulab.numpy as np
>>> np.array([1,2,3])
array([1.0, 2.0, 3.0], dtype=float32)
>>> np.array([1,2,3+0j])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
>>> np.array([1,2,3+0j], dtype=np.complex)
array([1.0+0.0j, 2.0+0.0j, 3.0+0.0j], dtype=complex)
>>>

**Comment by dhalbert** [comment]
As a point of interest, turning on complex support made the RP2040 CircuitPython firmware about 12kB larger.

**Comment by v923z** [comment]
> @h-milz This works for me, when `#define ULAB_SUPPORTS_COMPLEX (1)`. You have to give the `dtype` explicitly.

This is actually a good point. I should, perhaps, inspect the arguments of `array`, and depending on the results, decide on the `dtype`. But that raises a question about the design concept: `array` defaults to float, because float was the most-inclusive `dtype` at the beginning. We have added complex since, so, if we don't want to default to complex, then we can't really save the inspection.
 
> There is no `carray` in ulab specifically (I searched for that name).

No, it's the name of a file (that also appears in your listing https://github.com/adafruit/circuitpython/issues/9052#issuecomment-1999663626).

**Comment by dhalbert** [comment]
> I should, perhaps, inspect the arguments of `array`, and depending on the results, decide on the `dtype`

@v923z That would make it work more like numpy, I suppose. You would know better if there are any traps introduced by such a change. It would require scanning all of the input values, since the user might have passed in, say, a mixed int/float list. I'm not sure if that counts as an expensive operation or not.

**Comment by h-milz** [comment]
As a user, I'd say the current way it works is probably okay (float as a default), as long as the documentation is in sync (i.e., https://docs.circuitpython.org/en/latest/shared-bindings/ulab/numpy/index.html).

**Comment by v923z** [comment]
> > I should, perhaps, inspect the arguments of `array`, and depending on the results, decide on the `dtype`
> 
> @v923z That would make it work more like numpy, I suppose. You would know better if there are any traps introduced by such a change. It would require scanning all of the input values, since the user might have passed in, say, a mixed int/float list. I'm not sure if that counts as an expensive operation or not.

It's not cheap. The float-int distinction wouldn't even cut it, because the magnitude of integers should also be inspected. 
I do see the point of `numpy`-compatibility, but I have the feeling that this would introduce a change that benefits few, but impacts everyone.

**Comment by dhalbert** [comment]
@v923z I'm not pushing for it, just wondering. @h-milz I will close this now because I think it's all explained. If not, please reopen.
