### ISSUE TITLE
Typo in board for M5 Stack Cardputer

### ISSUE THREAD

**Issue by phesterman** [adafruit/circuitpython#9057]
### CircuitPython version

```python
Adafruit CircuitPython 9.0.0-rc.1 on 2024-03-14; M5 Stack Cardputer with ESP32S3
```

### Code/REPL

```python
# for I2S audio with external I2S DAC board
import audiobusio

audio = audiobusio.I2SOut(board.I2S_BIT_CLOCK, board.I2S_WORD_SELECT, board.I2S_DATA)
```

### Behavior

code.py output:
Traceback (most recent call last):
  File "code.py", line 17, in <module>
AttributeError: 'module' object has no attribute 'I2S_DATA'

### Description

In board, the I2S pins are identified as: 'I2S_BIT_CLOCK', 'I2S_WORD_SELECT', and 'IS2_DATA'.
You can see the typo in the naming of the data pin.

### Additional information

Substituting IS2_DATA for I2S_DATA stops the error, but doesn't fix the typo, of course.

**Comment by RetiredWizard** [comment]
This is fixed in the "absolute newest" version by #9020
