### ISSUE TITLE
Rotary encoder guide

### ISSUE THREAD

**Issue by kattni** [adafruit/circuitpython#906]
Write up a guide using a rotary encoder and the new `rotaryio` in CircuitPython.

**Comment by ladyada** [comment]
if you frame the intro text generically, id like to add in a page on using with arduino too just cause it comes up
see https://learn.adafruit.com/using-servos-with-circuitpython for an example!

**Comment by kattni** [comment]
I put this in moderation.

**Comment by kattni** [comment]
Guide is live. Blogged release. Everything's set to go. Closing!
