### ISSUE TITLE
Update to new I2C API in ESP-IDF

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#9072]
This depends on esp32-camera support: https://github.com/espressif/esp32-camera/issues/649

**Comment by tannewt** [comment]
WIP commit to do this is here: https://github.com/tannewt/circuitpython/commit/8a4ad54fe71b78011050f962f8a5eb7f37ffc6b5

**Comment by tannewt** [comment]
Moving back to 9.x.x because it depends on espressif (hopefully) updating esp32-camera.

**Comment by dhalbert** [comment]
https://github.com/espressif/esp32-camera/pull/677 which updates to the new I2C API, is now merged.

**Comment by dhalbert** [comment]
- Fixed by #9671.
