### ISSUE TITLE
IDF5.2.1 connecting to secure network without a password

### ISSUE THREAD

**Issue by bill88t** [adafruit/circuitpython#9125]
### CircuitPython version

```python
Adafruit CircuitPython 9.1.0-beta.0 on 2024-03-28; DFRobot FireBeetle 2 ESP32-S3 with ESP32S3
```

### Code/REPL

```python
import wifi
wifi.radio.connect("secure_network")
```

### Behavior

```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ConnectionError: Unknown failure 210
```

### Description

Now trying to connect to a secure network with no password produces code 210.

### Additional information

I opened this issue to discuss as to what should we do now.
Do we add a new message or just reuse "Authentication failure"?

Normal authentication failure doesn't produce error 210.

**Comment by anecdata** [comment]
210 is new since our definitions:
`NO_AP_FOUND_SECURITY`

**Comment by bill88t** [comment]
If you are trying to connect to what you think is an open network and you get "Authentication failure", it's pretty easy to guess what happened. I don't think we need a new message either.

**Comment by dhalbert** [comment]
I am making a PR to fix this.
