### ISSUE TITLE
Unexpected Characters in boot_out.txt

### ISSUE THREAD

**Issue by safferyj** [adafruit/circuitpython#9180]
### CircuitPython version

```python
Adafruit CircuitPython 9.1.0-beta.0 on 2024-03-28; Adafruit Feather ESP32-S2 Reverse TFT with ESP32S2
Adafruit CircuitPython 9.1.0-beta.0 on 2024-03-28; FeatherS2 Neo with ESP32S2
```

### Code/REPL

```python
#
```

### Behavior

boot_out.txt file contains 8 unexpected characters betweeen the newline after the UID and the start of "boot.py output". The characters (in hex) are: 1b 5b 32 4b 1b 5b 30 47.

### Description

May be reproduced with no code.py file, and any boot.py file, including an empty boot.py. If there is no boot.py, then there are no unexpected characters. 

### Additional information

![unexpected_boot_out_characters](https://github.com/adafruit/circuitpython/assets/100208958/739ce3b2-8905-47ea-86ce-e02ad4c1add1)

**Comment by RetiredWizard** [comment]
Esc [2K is the ansi terminal sequence to erase the current line and Esc [0G places the cursor at column zero.

**Comment by jepler** [comment]
```c
    mp_hal_stdout_tx_str(line_clear);
    mp_hal_stdout_tx_str(_current_executing_filename);
    serial_write_compressed(MP_ERROR_TEXT(" output:\n"));
```
The "line clear" code is written by this line in main.c. It was added by @bill88t in 722d8ffca51835b26ae4a032fb5d4795faae974e for https://github.com/adafruit/circuitpython/pull/8725 and this code applies to running both boot.py and code.py. You can check that PR for more background about why it was added; It might be possible to use a different call that bypasses the output capture for boot_out.txt, but I didn't investigate it any further than that.
