### ISSUE TITLE
m5stack atomS3U pin error

### ISSUE THREAD

**Issue by gus7av** [adafruit/circuitpython#9209]
### CircuitPython version

```python
main
```

### Code/REPL

```python
not tested - just a typo spotted in source code
```

### Behavior

not tested - just a typo spotted in source code

### Description

I spotted an error in the pins.c file for m5stack atom S3u file: https://github.com/adafruit/circuitpython/blob/main/ports/espressif/boards/m5stack_atoms3u/pins.c

BOTH pin GPIO/D1/A1 and GPIO2/D2/A2 are labelled SCL - I imagine one of them should be called SDA

**Comment by dhalbert** [comment]
@n3o59hf I believe you submitted the board def?

**Comment by n3o59hf** [comment]
Yes, looks like a typo. Based on https://docs.m5stack.com/en/core/AtomS3U GPIO2 should be SDA
