### ISSUE TITLE
What's the difference of ads1x115 and INA219 based on python3.11?

### ISSUE THREAD

**Issue by augustine829** [adafruit/circuitpython#9216]
Hi all,
     I have already updated my Python 3.9 to 3.11 but found that my existing Python script can't work. It can not detect ads1x15 and INA219. I would like to know what the news is now? 

Best regard

**Comment by tannewt** [comment]
It isn't clear that this problem is CircuitPython related at all. If you purchased Adafruit hardware then please post to the support forum: https://forums.adafruit.com/viewforum.php?f=60 Otherwise, ask the manufacturer of your hardware.
