### ISSUE TITLE
prettify Adafruit_Pixie library

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#924]
we have an arduino library for these mindblasting pixels
https://www.adafruit.com/product/2741
i just made a short example that mimics NeoPixel's format but it needs a repo, splitting up into a proper module etc!
https://forums.adafruit.com/viewtopic.php?f=52&t=136796&p=677580#p677580
no rush on this one
see the circuitpy neopixel library for inspiration
https://github.com/adafruit/Adafruit_CircuitPython_NeoPixel/blob/master/neopixel.py#L78

if you can get it to cookiecutter+travis point, ill do another set of testing since i have a strand of 3 pixies for testing porpoises

**Comment by tannewt** [comment]
@rhooper may be interested to see this as he has been thinking about reorganizing the code underneath the rgb led libraries.

**Comment by kattni** [comment]
This is finished! Lib is set, guide is updated and both have been blogged!
