### ISSUE TITLE
What is board_display_obj good for?

### ISSUE THREAD

**Issue by bablokb** [adafruit/circuitpython#9283]
### CircuitPython version

```python
n.a.
```

### Code/REPL

```python
n.a.
```

### Behavior

n.a.

### Description

While porting CP to a new device, I discovered that many board.c files (I found 37) have this statement:

    fourwire_fourwire_obj_t board_display_obj;

Strange thing is that this variable is only declared, but never used within the complete codebase.

Is there some special magic creating code that actually uses this variable?

**Comment by tannewt** [comment]
I think its leftovers from older code.

**Comment by bablokb** [comment]
So I could create a PR removing these lines from all these files?

**Comment by tannewt** [comment]
> So I could create a PR removing these lines from all these files?

Yes please!
