### ISSUE TITLE
terminal of code editor malfunctions when using mDNS names on esp32* (at least)

### ISSUE THREAD

**Issue by gitcnd** [adafruit/circuitpython#9345]
### CircuitPython version

```python
Adafruit CircuitPython 9.1.0-beta.1-24-g24f2e4f994 on 2024-05-18; S2Mini with ESP32S2-S2FN4R2
and
Adafruit CircuitPython 9.1.0-beta.3-28-g03e42a8c0c-dirty on 2024-06-15; AButton V3 with ESP32
and
Adafruit CircuitPython 9.0.5 on 2024-05-22; S2Mini with ESP32S2-S2FN4R2
```

### Code/REPL

```python
Same as issue https://github.com/adafruit/circuitpython/issues/9336
```

### Behavior

Using the name (e.g. http://cpy-eaf90c.local/code/ ) instead of IP address on my esp32 boards, I find that all websockets malfunction; if they work at all, they take a very long time (minutes) to do anything, and randomly drop things.

### Description

I'm using Windows 10 with Chrome.
mDNS works (http://cpy-eaf90c.local/ loads fine)

### Additional information

Probably same cause as https://github.com/adafruit/circuitpython/issues/9336

**Comment by dhalbert** [comment]
Closing in favor of #9336, as it would be the same problem.
