### ISSUE TITLE
Windows: CIRCUITPY is read-only after Windows goes to sleep and wakes up

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#9378]
CircuitPython 9.0.5.
Noted by JungleJim in discord on a QT Py ESP32-S3 4/2.

CIRCUITPY reappears, but as read-only after the Windows 10 computer it is attached to goes to sleep and is woken up.

**Comment by samblenny** [comment]
This could possibly be related to #9454 (ESP32-S3 USB serial output stops working). Both involve odd behavior with ESP32-S3 sleep modes when USB mass storage is enabled.

**Comment by tannewt** [comment]
I suspect this is the same as #9454. The ESP usb code wasn't detecting a resume correctly. It is fixed in https://github.com/hathach/tinyusb/pull/2784. We'll update CP as soon as that is merged in.

**Comment by tannewt** [comment]
Anyone have a windows 10 computer they can test this with?

**Comment by ladyada** [comment]
@BlitzCityDIY do you mind testing this out 🙏 only if you have time (my laptop is win11)

**Comment by BlitzCityDIY** [comment]
i tested with a qt py esp32-s3 running absolute newest and this seems to be fixed.
