### ISSUE TITLE
dump processor stack trace on crashes to help debug

### ISSUE THREAD

**Issue by aguaviva** [adafruit/circuitpython#9383]
Please dump a stack trace info (both python and the processor stack) to help pin down where the error happened

This is what I got but couldn't tell why or how to proceed to debug things:
```
soft reboot

Auto-reload is off.
Running in safe mode! Not running saved code.

You are in safe mode because:
CircuitPython core code crashed hard. Whoops!
Hard fault: memory access or instruction error.
Please file an issue with your program at github.com/adafruit/circuitpython/issues.
Press reset to exit safe mode.
```

**Comment by bill88t** [comment]
Debug builds do that.
Build circuitpython with `DEBUG=1` and you'll get a dump when crashing.
Then (at least for `espressif`), you can then get it decoded with `tools/decode_backtrace.py`.

**Comment by tannewt** [comment]
Hard faults can often be due to memory corruption so we try to do as little as possible. We already have related bugs as well #8704 and #7490.

**Comment by aguaviva** [comment]
Then I suggest having an error message that is a bit more actionable and explains what the next step it, in this case something along the lines: "please build circuitpython with DEBUG=1 to get an extended debug trace and include it in the bug report"

Thanks for your great work!
