### ISSUE TITLE
wifi.radio.enabled=False causes error with debug mode on

### ISSUE THREAD

**Issue by tyeth** [adafruit/circuitpython#9406]
### CircuitPython version

```python
latest (main) ~9.1beta5  DEBUG BUILD
```

### Code/REPL

```python
calling `wifi.radio.enabled = False` (before deep sleeping)
```

### Behavior

wifi:pm stop, total sleep time: Assertion '*fmt == '%' || !"unsupported fmt char"' failed, at file mpprint.c:586

### Description

Appears the debug message contains "%" which is not supported, or at least that was my impression after visiting https://github.com/micropython/micropython/issues/3004

**Comment by jepler** [comment]
There's a hack somewhere that tries to print espidf messages via mp_printf so they are visible on the repl, not requiring a separate debug uart. I guess this isn't compatible with all formats used in espidf

**Comment by tyeth** [comment]
That was my thunk, thanks Dan. I did see a successful log example when
searching for the time related string.
Forgot to mention running on an itsy bitsy esp32

**Comment by tannewt** [comment]
This is the printf connector: https://github.com/adafruit/circuitpython/blob/8fbbb598ffd72c93e01c5ed04618e2ce89134cf1/ports/espressif/supervisor/port.c#L489-L497

I do need to comment it out from time to time when debugging too.

**Comment by jepler** [comment]
let's just back it out if it causes crashes.
