### ISSUE TITLE
IDE (PyCharm Community) can't find `APA102_SCK`

### ISSUE THREAD

**Issue by xsorifc28** [adafruit/circuitpython#9407]
### CircuitPython version

```python
Adafruit CircuitPython 9.0.5, gemma m0
```

### Code/REPL

```python
from board import APA102_MOSI, APA102_SCK
```

### Behavior

Unable to find import, though code works without issues:
<img width="876" alt="image" src="https://github.com/adafruit/circuitpython/assets/5721836/fe2266a8-c561-41f6-a4db-35b90c00ae1d">

It seems APA102_SCK is missing from `board-stubs/__init__.py` file:
<img width="388" alt="image" src="https://github.com/adafruit/circuitpython/assets/5721836/ad48f1c8-0d8f-48d9-9915-9cf648afddf0">

It is defined here:
https://github.com/adafruit/circuitpython/blob/main/ports/atmel-samd/boards/gemma_m0/pins.c#L31
and also here
https://github.com/adafruit/circuitpython/blob/main/ports/atmel-samd/boards/gemma_m0/mpconfigboard.h#L15
(not sure how those translate to the python libs)

**Comment by dhalbert** [comment]
@FoamyGuy I do not know why only some of the pins are missing. I thought at first it was aliases, but the pin is missing altogether.
