### ISSUE TITLE
Mention udev rules in Circuit Playground Express Troubleshooting guide

### ISSUE THREAD

**Issue by craigargh** [adafruit/circuitpython#941]
Computers running Ubuntu/Linux may be unable to write to the Circuit Playground Express board. To fix this udev rules need to be installed. 

The steps to install the udev rules are mentioned in Arduino guides, but are not mentioned in the CircuitPython guides. Would it be possible to add the udev rules installation steps to the CircuitPython troubleshooting guide? 

The Arduino guide can be found here https://learn.adafruit.com/adafruit-arduino-ide-setup/linux-setup#udev-rules

**Comment by dhalbert** [comment]
Adding a user to the `dialout` group has been documented for a while now in:
https://learn.adafruit.com/welcome-to-circuitpython/kattni-connecting-to-the-serial-console#setting-permissions-on-linux-3027345-8
and
https://learn.adafruit.com/welcome-to-circuitpython/advanced-serial-console-on-mac-and-linux

This is more straightfoward than using `udev` rules.

Closing - please comment if think this should remain open.
