### ISSUE TITLE
Support for Xiao RP2350

### ISSUE THREAD

**Issue by scarolan** [adafruit/circuitpython#9489]
This already supports Micropython and shouldn't require massive effort to port.  I can help test if anyone's interested in building this.
https://www.seeedstudio.com/Seeed-XIAO-RP2350-p-5944.html

**Comment by tannewt** [comment]
Do you know what USB PID they use? Do you have one already?

**Comment by scarolan** [comment]
Not yet but I may order a few...

**Comment by tannewt** [comment]
Draft PR for this is here: #9532

**Comment by jepler** [comment]
#9532 has been merged
