### ISSUE TITLE
update Mu install & REPL pages for new download!

### ISSUE THREAD

**Issue by ladyada** [adafruit/circuitpython#950]
https://learn.adafruit.com/welcome-to-circuitpython/installing-mu-editor
https://learn.adafruit.com/welcome-to-circuitpython/kattni-connecting-to-the-serial-console

to reflect new download from https://codewith.mu/en/download
and new toolbar (REPL -> Serial)

**Comment by kattni** [comment]
This should be all set to go. Links, text and screenshots are updated.
