### ISSUE TITLE
please support XIAO ESP32S3

### ISSUE THREAD

**Issue by marcobrianza** [adafruit/circuitpython#9507]
I see that most XIAO are already supported by circuitpython but XIAO ESP32S3 is missing. in there a reason for this?

https://wiki.seeedstudio.com/xiao_esp32s3_getting_started/

**Comment by deshipu** [comment]
The pull request is here. It's waiting for a USB VID/PID from Seeed.

https://github.com/adafruit/circuitpython/pull/9118

**Comment by marcobrianza** [comment]
If I understand correctly the board identifies itself with standard USB VID/PID instead of specific ones
I think that lolin boards do the same but are suported.
What is the blocking issue in having a shared VID/PID?

**Comment by dhalbert** [comment]
> What is the blocking issue in having a shared VID/PID?

The reasons for having unique VID/PIDS are discussed here: https://learn.adafruit.com/how-to-add-a-new-board-to-circuitpython/frequently-asked-questions#faq-3130480

**Comment by tannewt** [comment]
If a manufacture won't grant a USB PID, you can also request a PID from [pid.codes](https://github.com/pidcodes/pidcodes.github.com) as a third-party adding open source software on a closed source board.

**Comment by djairjr** [comment]
Ok guys, there is some issue with the firmware generation process. Both firmwares generate a read-only CIRCUITPY. But REPL works, and the pinout are correct. There is something wrong with TinyUSB? Tested on my local machine with dual boot (Ubuntu/Windows) and a Amazon virtual machine (also Ubuntu).

See if this firmwares works for you, ok?

https://github.com/djairjr/Seeed_Xiao_ESPS3_Sense_Circuitpython

**Comment by dhalbert** [comment]
@djairjr Let's discuss in #9528.

**Comment by marcobrianza** [comment]
Hi I have written an email to techsupport@seeed.io asking for VID PID and below is the replay I got
I think this helps the official support ;-) 
...

Hi Marco,

Thank you for reaching out. Here are the VID and PID for the XIAO ESP32-S3:

VID: 0x2886
PID: 0x8056
These details should assist with the process. If you have any more questions or need further assistance, feel free to ask.


Regards!

Frank
Seeed Technical Support Team

**Comment by dhalbert** [comment]
Done by #9530. The Sense is the base board with an add-on board. The same build can be used for both.
