### ISSUE TITLE
Docstring for stdio indicates binary

### ISSUE THREAD

**Issue by timdechant** [adafruit/circuitpython#9543]
### CircuitPython version

```python
Adafruit CircuitPython 9.1.0 on 2024-07-10; Waveshare RP2040-Zero with rp2040
```

### Code/REPL

```python
import sys
help(sys.stdout)
```

### Behavior

object <io.FileIO 1> is of type FileIO

### Description

Docstring for stdio indicates "FileIO", which is a binary IO stream.  As detailed in #553, stdio is not binary by design; its docstring should indicate "StringIO".

**Comment by dhalbert** [comment]
If you would like to make a pull request to fix this that would be great. If you have other doc fixes you can combine them into one PR.
