### ISSUE TITLE
Web workflow: warn about navigating away from page when an operation is in process

### ISSUE THREAD

**Issue by dhalbert** [adafruit/circuitpython#9606]
From discord:

> @ ozzloy: when i upload a directory via the web interface, i navigate away before the whole directory is done uploading.  could the page do one of these popups instead? "18 of 20 files still need to be uploaded.  are you sure you want to navigate away?"

**Comment by tannewt** [comment]
This is an HTML/JavaScript task in these files: https://github.com/adafruit/circuitpython/tree/main/supervisor/shared/web_workflow/static

In `directory.*` I think.
