### ISSUE TITLE
WiFi connection and web communication failures on QT Py ESP32-S3 with CP 9.2.0-beta.0

### ISSUE THREAD

**Issue by kattni** [adafruit/circuitpython#9657]
### CircuitPython version

```python
Adafruit CircuitPython 9.2.0-beta.0 on 2024-09-17; Adafruit QT Py ESP32-S3 no psram with ESP32S3
```

### Code/REPL

```python
import os
import ssl
import time
import wifi
import socketpool
import adafruit_requests
from adafruit_io.adafruit_io import IO_HTTP

wifi.radio.connect(os.getenv("CIRCUITPY_WIFI_SSID"), os.getenv("CIRCUITPY_WIFI_PASSWORD"))
pool = socketpool.SocketPool(wifi.radio)
requests = adafruit_requests.Session(pool, ssl.create_default_context())

io = IO_HTTP(os.getenv("AIO_USERNAME"), os.getenv("AIO_KEY"), requests)


while True:
    print(io.receive_time())
    time.sleep(3)
```

### Behavior

If I run the code as-is, I get the following on WiFi connect:
```
Traceback (most recent call last):
  File "code.py", line 9, in <module>
ConnectionError: Unknown failure 2
```

If I add `wifi.radio.tx_power = 13` after imports, it connects successfully. Working code attached (as text file to appease GitHub).
[code.txt](https://github.com/user-attachments/files/17117596/code.txt)

Often, once connected, I will receive the following error attempting to connect to Adafruit IO (or communicate with the web at all; I also tried with `requests.get()` and received the same result):
```
Traceback (most recent call last):
  File "code.py", line 85, in <module>
  File "adafruit_io/adafruit_io.py", line 870, in receive_time
  File "adafruit_io/adafruit_io.py", line 586, in _get
  File "adafruit_requests.py", line 701, in get
  File "adafruit_requests.py", line 635, in request
  File "adafruit_connection_manager.py", line 333, in get_socket
gaierror: (-2, 'Name or service not known')
```
Note this traceback is from different code, attached below. It happens intermittently even with the simple example included above.

### Description

This all started when I decided to update an older project. It is running 8.1.0-rc.2 with library versions from around that time, and it connects on the _same_ QT Py ESP32S3 successfully, and communicates with Adafruit IO successfully. (I updated CP on that board, and it experiences all of the failure explained above). 

This is the project code.
[canary_code.txt](https://github.com/user-attachments/files/17117634/canary_code.txt)

### Additional information

I have now tried this code on three separate QT Py ESP32S3 boards, with the same results across them all. Two have LED backpacks soldered to them, the other one does not. This should not matter, but I figured it was worth noting anyway.

**Comment by EAGrahamJr** [comment]
`Adafruit CircuitPython 9.1.4 on 2024-09-17; Adafruit QT Py ESP32-S3 4MB Flash 2MB PSRAM with ESP32S3`

I tried the "lowering tx_power" trick and could not connect at all. 

If I hard-reset, I will _usually_ get a connection on the first try. Interestingly, the "Unknown failure -2" _alternates_ sometimes with "No network with that ssid".

I'm wondering if (in my case) since the connection isn't used for a long period of time, the socket appears to go "stale" (the connection is dropped at the AP).

**Comment by dhalbert** [comment]
@EAGrahamJr Could you try the "Absolute Newest" builds past beta.0, which have some further fixes: https://adafruit-circuit-python.s3.amazonaws.com/index.html?prefix=bin/adafruit_qtpy_esp32s3_4mbflash_2mbpsram/

**Comment by EAGrahamJr** [comment]
> @EAGrahamJr Could you try the "Absolute Newest" builds past beta.0, which have some further fixes: https://adafruit-circuit-python.s3.amazonaws.com/index.html?prefix=bin/adafruit_qtpy_esp32s3_4mbflash_2mbpsram/

I was **just** going to reply that the _newest_ seems absolutely rock solid for 60 minutes (that's 4 HTTP requests spread out over 1 hour)...

**Comment by EAGrahamJr** [comment]
Interesting....

Over 2 hours, so I buttoned up the PLA enclosure I had printed _with an enclosed SH1106 display_ and the error resurfaced not long after. On a hunch, I popped open it back open, and the WiFi **properly** reconnected and everything went back to working. So, that's a little bit of a bummer.

**Comment by EAGrahamJr** [comment]
Started a "how long will this run" test this morning. Reference code is at https://github.com/EAGrahamJr/ispy-deskie (basically it's asyncio and checks for `wifi.radio.connected` every 5 seconds, then goes into a re-connect loop if necessary).

**Comment by EAGrahamJr** [comment]
I would say it's _generally_ stable. After about 3 hours or so, started getting more of these: 

```
26532.219: INFO - Connecting to WiFi
26535.633: ERROR - Error connecting wifi - Unknown failure 2
26535.641: WARNING - Attempting to re-connect
26537.641: INFO - Connecting to WiFi
26540.055: ERROR - Error connecting wifi - No network with that ssid
26540.055: WARNING - Attempting to re-connect
26540.297: WARNING - Weather waiting on connection
26542.055: INFO - Connecting to WiFi
26546.500: INFO - Connected to WiFi - IP address: 192.168.1.19
```
with an occasional
```
ERROR - Error connecting wifi - Unknown failure 39
```

There's no pattern to when the connection drops, so it **may** be more of an indication of the general messiness of my current wifi environment (there's at _least_ 20 AP's nearby) plus the relative strength (or not) of the embedded radio?

**Comment by bablokb** [comment]
Almost all of my boards (including S3, Pico-W) need more than a single attempt to connect to my AP. `wifi.radio.connect()` does have a timeout-parameter, but I don't think this is implemented in the way you expect it to work (if implemented at all). So I also use a retry loop for connecting.

Otherwise my S3 board is very stable. Running for days, connecting every 15 minutes to an URL fetching data.

If possible, you should check the logs of your AP to see if the AP actively stops the connection or if the client (i.e. the S3-board) does this. Maybe you have to turn on logging Wifi-events somewhere in the AP (that's what I have to do).

**Comment by EAGrahamJr** [comment]
Eh, my EP logs are pretty limited -- all I can see is when the S3 gets a MAC address, which only means the AP sees a connection. I need to put a timestamp on _my_ logs so I can correlate instead of trying to "count seconds since I plugged it in". :grinning:

**Comment by EAGrahamJr** [comment]
Mixed results early on today, but after I _moved the I2C display cable_ off of the chip within the enclosure, I've had 12 hours of nonstop service, which is :+1: from me.

**Comment by dhalbert** [comment]
> Mixed results early on today, but after I _moved the I2C display cable_ off of the chip within the enclosure, I've had 12 hours of nonstop service, which is 👍 from me.

This is very interesting. Do you just mean it was close to the ESP32-S3 chip or do you mean you unplugged (or disconnected) the I2C display?

**Comment by EAGrahamJr** [comment]
> > Mixed results early on today, but after I _moved the I2C display cable_ off of the chip within the enclosure, I've had 12 hours of nonstop service, which is 👍 from me.
> 
> This is very interesting. Do you just mean it was close to the ESP32-S3 chip or do you mean you unplugged (or disconnected) the I2C display?

Part of it was laying "over" the board and I managed to coil it all under the display, next to the STEMMA port. It's a bit easier to explain in relation to this picture:

![20241008_222016](https://github.com/user-attachments/assets/c9aeb089-a7a1-4f4b-a591-877c80e3015b)

It didn't appear to be triggering button presses, but now it _is_ looking like it may have been some RF interference from the cable and/or the :hankey: :donkey: SH1106 display.

**Comment by EAGrahamJr** [comment]
Running for over a month without _any_ issues, so **I** would consider this resolved.

**Comment by dhalbert** [comment]
@EAGrahamJr Thank you for the followup!

Other folks have also run into the "too much power" issue when small chip antennas in limited space are used. Lowering power really helps, and we've tried to make the default tx_power for various boards take this into account.
