### ISSUE TITLE
Use the display controllers scroll functionality whenever possible

### ISSUE THREAD

**Issue by mirkokral** [adafruit/circuitpython#9689]
In displayio screens, when moving an object we should use or try to use the display's scroll functionality whenever possible. 
An example of a good situation to do this in is when scrolling happens on the terminalio terminal (the text goes off the screen on the vertical axis)

**Comment by tannewt** [comment]
I filed #1170 long ago to do this. I think the tricky bit is tracking the static portions that will need to be moved during a scroll.
