### ISSUE TITLE
RP2350 does not reset i2c peripheral upon reload

### ISSUE THREAD

**Issue by bill88t** [adafruit/circuitpython#9703]
### CircuitPython version

```python
Adafruit CircuitPython 9.2.0-beta.0-25-g7f14b9c49a on 2024-10-04; Raspberry Pi Pico 2 with rp2350a
```

### Code/REPL

```python
import time, board, busio, adafruit_ssd1306
from digitalio import DigitalInOut
i2c = busio.I2C(board.GP17, board.GP16)
display = adafruit_ssd1306.SSD1306_I2C(128, 64, i2c)
```

### Behavior

SSD1306 display properly attached
First time works, then if we reload and run it again:

ValueError: I2C peripheral in use

**Comment by tannewt** [comment]
I don't think this is a bug. We keep I2C around when used by a display so that it can be used internally. Do `displayio.release_displays()` to release it.

**Comment by bill88t** [comment]
It's not a displayio display. I just met the bug with it.
It can be repro'ed with just `import board, busio; busio.I2C(board.GP17, board.GP16)`, reloading and running it again.

**Comment by dhalbert** [comment]
I tried latest `main` with a SAMD21 board, and I2C cleanup is acting flaky, though I haven't got a reproducer yet. I think this may be due to #9671, which removed `i2c_reset()` on various ports.
