### ISSUE TITLE
Can't build mpy-cross: "CircuitPython must be built from a git clone with tags"

### ISSUE THREAD

**Issue by berkut0** [adafruit/circuitpython#9728]
### CircuitPython version

```python
9.1.4
```

### Code/REPL

```python
make -C mpy-cross
```

### Behavior

make: Entering directory '/cygdrive/doesntmatter/circuitpython/mpy-cross'
- Verbosity options: any combination of "steps commands rules", as `make V=...` or env var BUILD_VERBOSE
Cannot determine version.

CircuitPython must be built from a git clone with tags.
If you cloned from a fork, fetch the tags from adafruit/circuitpython as follows:

make fetch-tags

### Description

I'm not very experienced in all this source building stuff. But I'm trying to follow the list from BUILDING.md and I don't understand what I'm doing wrong. ```git checkout tags/9.1.4``` doesn't help, nor does ```make fetch-tags```

### Additional information

It seems like this issue has come up before:
https://hackaday.io/project/197550-wk-50-trackball-keyboard/log/232329-c-building-circuitpython

**Comment by dhalbert** [comment]
I think this was just covered in https://forums.adafruit.com/viewtopic.php?t=214284. Maybe that is you?

**Comment by berkut0** [comment]
At some point I gave up and installed WSL.

The problem is that the machine I was trying to build everything on didn't have WSL. In short, I think we should just rely on WSL and not expect to be able to build anything on Windows. Given that the rest of the build process didn't go very smoothly either, I don't think it can be beaten without Linux.

In the end, I was able to build everything I wanted using WSL. I'm trying to connect two displays to one device as shown in this article: https://todbot.com/blog/2022/05/19/multiple-displays-in-circuitpython-compiling-custom-circuitpython/

**Comment by bablokb** [comment]
> Given that the rest of the build process didn't go very smoothly either,

Have you tried building in the cloud? See `.devcontainer/Readme.md`. You don't need to install anything on your computer. The cloud build-environment is Linux, but there are no prerequisites for your computer (except that you have a browser).

**Comment by berkut0** [comment]
@bablokb It's actually a very interesting idea.
It seems like we could make our own fork and build it through actions?

**Comment by bablokb** [comment]
I think actions work differently, although they probably use the same sort of infrastructure.

**Comment by dhalbert** [comment]
I'm going to close this for now. https://forums.adafruit.com/viewtopic.php?t=214284 diagnosed the problem as using a non-Unixish-shell.
