### ISSUE TITLE
circuitpython makefile should not default BOARD setting. 

### ISSUE THREAD

**Issue by mrmcwethy** [adafruit/circuitpython#975]
Between myself and sommersoft, we spent over an hour missing the most obvious typo.  To start a metro M4 build, I typed

make BUILD=metro_m4_express

The build worked and generated a uf2 file.  I moved it over into the metro M4 express board and it failed to connect via USB.  We were blind to the parameter should have been BOARD not BUILD.

**Comment by tannewt** [comment]
Thanks @mrmcwethy !
