### ISSUE TITLE
RP2350: gc.mem_free() causes hang or crash

### ISSUE THREAD

**Issue by bit-13** [adafruit/circuitpython#9760]
### CircuitPython version

```python
Adafruit CircuitPython 9.2.0-rc.0 on 2024-10-23; SparkFun Pro Micro RP2350 with rp2350a
```

### Code/REPL

```python
import gc
gc.mem_free()
```

### Behavior

REPL either hangs or system crashes (USB drive disconnect/reconnect)

### Description

Right after unboxing my new RP2350 board installed CircuitPython 9.2.0-rc.0 and ran the above command, which hung the REPL. Attempting to allocate a large amount of memory with `x = [0]*10000` also causes a hang. Either this is a bug or there's an issue with the PSRAM on this board…

**Comment by dhalbert** [comment]
This was reported earlier in #9755 and was fixed in #9759, and will be in 9.2.0 final. You can try the artifacts in #9759 if you'd like.
