### ISSUE TITLE
Add BME680 driver to Pypi

### ISSUE THREAD

**Issue by cemclellan** [adafruit/circuitpython#981]
Please add the BME680 CircuitPython driver to Pypi. Information below:

I am following the excellent Learning Guide CircuitPython on Linux and Raspberry Pi at https://learn.adafruit.com/circuitpython-on-raspberrypi-linux?view=all.

I have a BME680, not the BME280 and I would like to connect it to the Raspberry Pi using CircuitPython.

I installed the BME280 driver as per the instructions, hoping it might work, but I get the following error message:
RuntimeError: Failed to find BME280! Chip ID 0x61
[~/Python_Source/CircuitPython/BME280]

0x61 is the correct ID for the BME680 I have.

Apparently the BME280 driver is testing for 0x60.

**Comment by ladyada** [comment]
OK try this!
https://pypi.org/project/adafruit-circuitpython-bme680/

**Comment by cemclellan** [comment]
Wow! That was quick, thanks!!!

**Comment by ladyada** [comment]
ok! closing, re-open if it doesnt work (we didnt test it, just deployed)
