### ISSUE TITLE
wifi trouble : pystack exhausted

### ISSUE THREAD

**Issue by stanelie** [adafruit/circuitpython#9856]
### CircuitPython version

```python
Adafruit CircuitPython 9.2.0 on 2024-10-28; Waveshare ESP32-S3-Zero with ESP32S3
```

### Code/REPL

```python
import wifi
import time

def connect_to_wifi():
    try:
        print(f"connecting wifi")
        wifi.radio.connect("my_ssid","my_password", timeout=5)
    except ConnectionError as e:
        print(f"{e} . Retrying...")
        time.sleep(1)
        connect_to_wifi()
        
connect_to_wifi()
```

### Behavior

When trying to connect to a nonexistent access point, the ESP32 device will eventually crash after a minute or two with the following error message : 
`RuntimeError: pystack exhausted`

I would like the ESP32 to keep trying until it can connect, and not crash.

**Comment by anecdata** [comment]
you could do `while not wifi.radio.connected:` inside the function, and add some time limit or other exit trigger to the conditional  if desired

**Comment by stanelie** [comment]
Thanks for the tip, I will try that! Cheers!

**Comment by stanelie** [comment]
Yup, that works great! Thanks again!
