### ISSUE TITLE
Add sound sample generator

### ISSUE THREAD

**Issue by tannewt** [adafruit/circuitpython#988]
It should generate a note based on a set of variables. See these for ideas:

Gameboy: https://youtu.be/HyzD8pNlpwI?t=24m10s
Pico-8: https://www.youtube.com/watch?v=Wj1LJQutMCY
bfxr: https://github.com/increpare/bfxr

**Comment by ladyada** [comment]
@tannewt i think synthio is basically this? we can close :)
