### ISSUE TITLE
Refactor and move BLE stuff to shared-bindings

### ISSUE THREAD

**Issue by arturo182** [adafruit/circuitpython#995]
This way we can reuse the bindings in other future ports that support BLE

**Comment by tannewt** [comment]
Yes please!

**Comment by arturo182** [comment]
I have the `ble` module already ported and working here https://github.com/arturo182/circuitpython/commit/ecd51faa2009259743a55890271f6738f9bb4869
The code there depends on changes in #1011 so I'll wait until that is merged before i make a PR.

**Comment by tannewt** [comment]
Awesome!

**Comment by dhalbert** [comment]
Done by #1014 and #1289.
