### ISSUE TITLE
Add board files for PCA10059 - the nRF52840 dongle

### ISSUE THREAD

**Issue by arturo182** [adafruit/circuitpython#996]
It's a nifty $10 board :)

**Comment by ladyada** [comment]
@arturo182 hey! where'd you get that from?? :D

**Comment by arturo182** [comment]
Straight from the source ;) https://twitter.com/arturo182/status/1014122869142491136

**Comment by ladyada** [comment]
https://www.semiconductorstore.com/cart/pc/viewPrd.asp?idproduct=94964
fyi!

**Comment by arturo182** [comment]
I came into possession of two more dongles, does anyone from Adafruit need some for testing? @ladyada @tannewt @hathach

**Comment by jerryneedell** [comment]
@arturo182 I have some arriving in the next day or so (mouser just shipped ones that had been backordered) Be happy to test when the BSP is available.

**Comment by arturo182** [comment]
Sweet! It's still on my TODO list, just a bit lower than other things ;) I think I'll wait for #1004 to be merged as this board doesn't have a easily accessible jlink interface.

**Comment by dhalbert** [comment]
@arturo182 Thanks! A bunch of us ordered dongle samples from Symmetry; mine are out for delivery today.

**Comment by hathach** [comment]
unfortunately, I didn't have one.

**Comment by ladyada** [comment]
@hathach can you order from https://www.semiconductorstore.com/cart/pc/viewPrd.asp?idproduct=94964 ? this dongle isnt so important to support so its ok if it takes some time, i think just arturo likes it ;)

**Comment by hathach** [comment]
@ladyada the shipping cost to me is like 3x the price of the board :( . Since it is not urgent, maybe the next time you send me the prototype of feather nrf52840, you could include this as well. Also please include the later revision of feather52832 ( need it for low power testing and coding tutorial https://github.com/adafruit/Adafruit_nRF52_Arduino/issues/165 )

**Comment by ladyada** [comment]
ok we are making the feather 52840 prototypes this week. when i have some ready we'll email together and get you a package with all the items :)

**Comment by dhalbert** [comment]
I am including this in a revamp of pin definition files and also #1040.

**Comment by dhalbert** [comment]
Fixed by #1158.
